### ISSUE TITLE
Underlines between cells not connected when using bitmap font

### ISSUE THREAD

**Issue by haarp** [jwilm/alacritty#1595] opened 2018-09-27 14:24 UTC
> Which operating system does the issue occur on?

Linux X11

When the Terminus bitmap font is used with Alacritty, underline is not complete. Each individual cell appears to have its own underline, which are not connected to each other. See the screenshot:

![screenshot_2018-09-27_16-19-35](https://user-images.githubusercontent.com/781030/46152614-a29b9b80-c271-11e8-9573-1b3973101df5.png)

The same can also be witnessed with some TTF fonts at large font sizes.

**Comment by chrisduerr** [comment] 2018-09-27 14:39
This is a duplicate of #31, please subscribe to that issue if you want to stay updated. There is a PR to resolve this, however it will probably take some time until it can be merged.

**Closed by chrisduerr** 2018-09-27 14:39 UTC

**Comment by haarp** [comment] 2018-09-27 14:40
Thanks, I was sure this was an open issue, but I didn't find it.
