### ISSUE TITLE
When the terminal window is maximized, the content cannot be fully displayed.

### ISSUE THREAD

**Issue by honeway** [jwilm/alacritty#2892] opened 2019-10-18 13:21 UTC
Which operating system does the issue occur on?
Windows 10
alacritty 0.3.3 (cc3e4d3)

Issue environment:    
Connect to linux using openssh.   

When the terminal window is maximized, the content is still displayed in the old window size.
Content outside the width of the old window is obscured by black.

It works fine when connected to the same Linux using WSL ssh.

**Comment by chrisduerr** [comment] 2019-10-18 13:32
Which version of Alacritty are you running and can you reproduce this with both ConPTY and WinPTY (alacritty -v will verify which of them you're actually using).

**Comment by honeway** [comment] 2019-10-18 13:42
> Which version of Alacritty are you running and can you reproduce this with both ConPTY and WinPTY (alacritty -v will verify which of them you're actually using).
alacritty 0.3.3 (cc3e4d3)
I have tried to set `enable_experimental_conpty_backend: true`. The issue still occurs.

**Comment by chrisduerr** [comment] 2019-10-18 20:17
Could you verify that ConPTY is actually used by running `alacritty -v` from the terminal?

**Comment by honeway** [comment] 2019-10-21 01:35
```shell
PS C:\tools\alacritty> .\alacritty.exe -version
PS C:\tools\alacritty> Created log file at "C:\\Users\\xxx\\AppData\\Local\\Temp\\Alacritty-24860.log"
[2019-10-21 09:32] [INFO] Welcome to Alacritty
[2019-10-21 09:32] [INFO] Configuration loaded from "C:\\Users\\xxx\\AppData\\Roaming\\alacritty\\alacritty.yml"
[2019-10-21 09:32] [INFO] Device pixel ratio: 2.5
[2019-10-21 09:32] [INFO] Initializing glyph cache...
[2019-10-21 09:32] [INFO] ... finished initializing glyph cache in 0.029503061s
[2019-10-21 09:32] [INFO] Width: 2560, Height: 1920
[2019-10-21 09:32] [INFO] Cell Size: 20 x 42
[2019-10-21 09:32] [INFO] Padding: 0 x 0
[2019-10-21 09:32] [INFO] PTY Dimensions: Line(45) x Column(128)
[2019-10-21 09:32] [INFO] Using Winpty agent
[2019-10-21 09:32] [INFO] Initialisation complete
[2019-10-21 09:32] [INFO] Width: 0, Height: 0
```

**Comment by chrisduerr** [comment] 2019-10-21 07:59
WinPTY has many issues, so that's very possible. I'd strongly recommend updating your system either way though, probably not a bad idea.

**Comment by honeway** [comment] 2019-10-22 02:44
Our company won't upgrade util windows 10 1909 released.

**Comment by chrisduerr** [comment] 2019-10-22 15:47
That's unfortunate, though nothing we can do about that. Should be fixed once it's possible for you to update.

**Closed by chrisduerr** 2019-10-22 15:47 UTC
Labels: C - awaiting feedback, H - windows

**Comment by ifhw** [comment] 2019-11-18 10:09
Upgraded system to win10 1909, now using Conpty agent. The issue is gone.
