### ISSUE TITLE
use_thin_strokes no longer working after update to Mojave

### ISSUE THREAD

**Issue by jarednorman** [jwilm/alacritty#1635] opened 2018-10-07 21:14 UTC
On MacOS, using the latest master as of this writing, the `use_thin_strokes` options has stopped working for me. Looks like this:

<img width="2560" alt="screen shot 2018-10-07 at 2 09 31 pm" src="https://user-images.githubusercontent.com/471667/46586995-f90b9580-ca3a-11e8-81aa-89591e51b785.png">

If it helps, iTerm2 shipped a bunch of font rendering related fixes for Mojave in version 3.2.3, including the same issue:

> Get thin strokes working on macOS 10.14 with and without GPU renderer.

**Comment by chrisduerr** [comment] 2018-10-07 21:16
Just to make sure, when launching Alacritty, there are no warnings printed to the console, right?

Also could you try an earlier version which you know worked on your system, just to confirm that this is due to a macOS update?

**Comment by jarednorman** [comment] 2018-10-07 21:29
Output on launch:

```
The `scale_with_dpi` setting has been removed, on X11 the WINIT_HIDPI_FACTOR environment variable can be used instead.
Config `mouse.faux_scrollback_lines` is deprecated. Please use `mouse.faux_scrolling_lines` instead.
[unhandled osc_dispatch]: [['P','g','5','0','4','9','4','5',],] at line 754
[unhandled osc_dispatch]: [['P','h','f','9','f','5','d','7',],] at line 754
[unhandled osc_dispatch]: [['P','i','5','0','4','9','4','5',],] at line 754
[unhandled osc_dispatch]: [['P','j','d','5','c','4','a','1',],] at line 754
[unhandled osc_dispatch]: [['P','k','5','0','4','9','4','5',],] at line 754
[unhandled osc_dispatch]: [['P','l','5','0','4','9','4','5',],] at line 754
[unhandled osc_dispatch]: [['P','m','f','9','f','5','d','7',],] at line 754
```

I switched to 8b71eed and saw same issue.

**Comment by chrisduerr** [comment] 2018-10-07 21:44
Thanks, output is unrelated to this issue, so it's likely that the patch did change something about the font rendering. Potentially an update of the core dependencies of the font library might resolve this.

**Comment by dm1try** [comment] 2018-10-15 11:34
related `set_font_smoothing_style` looks like a hack, at least it is not documented anywhere.

btw I just disabled all options except the antialiasing, result on Mojave:
alacritty with antialiasing only:
<img width="528" alt="screen shot 2018-10-15 at 14 24 48" src="https://user-images.githubusercontent.com/486807/46948559-30a3be80-d087-11e8-935f-9da982188561.png">
latest iterm2 with "thin strokes":
<img width="528" alt="screen shot 2018-10-15 at 14 29 08" src="https://user-images.githubusercontent.com/486807/46948604-4fa25080-d087-11e8-8b7a-d568c9755f6e.png">
default allacrity:
<img width="528" alt="screen shot 2018-10-15 at 14 27 59" src="https://user-images.githubusercontent.com/486807/46948621-5e890300-d087-11e8-8d97-e97f5c66f87b.png">

**Comment by talal** [comment] 2018-12-06 18:44
@jarednorman can you confirm whether you are still facing the issue with latest macOS and Alacritty (built from `master`)?

If not then perhaps this issue can be closed.

**Comment by chrisniael** [comment] 2019-01-20 07:32
[https://github.com/jwilm/alacritty/issues/486#issuecomment-451664026](https://github.com/jwilm/alacritty/issues/486#issuecomment-451664026)

**Comment by evmorov** [comment] 2019-03-25 19:56
`defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO` helped me to return the font to pre Mojave state

**Comment by talal** [comment] 2019-03-26 11:19
@chrisduerr what is the wait time period for author response after which the issue can be considered stale and closed.

I think this issue can be closed. As for a fix, the solution suggested in the default config file works (as reconfirmed by @evmorov) above.

**Comment by chrisduerr** [comment] 2019-03-26 16:25
> @chrisduerr what is the wait time period for author response after which the issue can be considered stale and closed.

Generally issues are just checked every once in a while and tagged with 'awating feedback' if they should be resolved or more info is needed. If they are marked and checked again they are closed. Usually no specific timeframe.

Since github makes it easy to re-open and closing does not prevent from commenting, it's usually not a big deal. So just let me know if I should re-open, since this seems to mainly be about a macos change.

**Closed by chrisduerr** 2019-03-26 16:25 UTC
Labels: C - awaiting feedback, H - macos, S - font

**Comment by mshkrebtan** [comment] 2019-08-22 10:10
I set `use_thin_strokes` to `true` and enabled font smoothing:

```
defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO
defaults -currentHost write -globalDomain AppleFontSmoothing -int 2
```

But still the fonts do not look as good as in iTerm2, where I have `Enable subpixel anti-aliasing` box checked.

**Comment by russelldavies** [comment] 2020-01-16 09:34
@alcuadrado What I do is run `defaults write -g CGFontRenderingFontSmoothingDisabled -bool NO`, start Alacritty, and then run `defaults delete -g CGFontRenderingFontSmoothingDisabled` so that other applications are not affected.
