### ISSUE TITLE
Moving alacritty between Retina and non-Retina displays

### ISSUE THREAD

**Issue by JamesDunne** [jwilm/alacritty#1069] opened 2018-01-31 15:30 UTC
Which operating system does the issue occur on?
MacOS 10.12.3

Spawning alacritty initially on a retina display (builtin macbook pro display) looks fine initially, but moving the window to an external 1080p non-retina display causes the fonts to be scaled by 4x or more while the window dimensions remain the same. Basically, moving between monitors of different dpi settings is not accounted for and only retains the dpi of the monitor initially opened on.

**Comment by sodiumjoe** [comment] 2018-01-31 17:47
dupe of https://github.com/jwilm/alacritty/issues/71

**Closed** 2018-01-31 18:44 UTC
