### ISSUE TITLE
Dragged filename with spaces lacks quotes

### ISSUE THREAD

**Issue by cpterry** [jwilm/alacritty#2539] opened 2019-06-14 03:04 UTC
# System
|                  |                               |
|------------------|-------------------------------|
| Operating System | Linux     |
| Rust Version     | stable   |
| Display Server   | X11 |

# Summary
Dragging a file with spaces in the filename into Alacritty produces the filename missing quotation marks.

# Behavior
/mnt/storage/test file with spaces

# Expectation
'/mnt/storage/test file with spaces'

**Comment by chrisduerr** [comment] 2019-06-14 13:53
Duplicate of https://github.com/jwilm/alacritty/issues/1335.

**Closed by chrisduerr** 2019-06-14 13:53 UTC
