### ISSUE TITLE
Error in Cargo.toml - unable to parse

### ISSUE THREAD

**Issue by spiderknight** [jwilm/alacritty#1476] opened 2018-07-29 09:03 UTC
Which operating system does the issue occur on?  **Linux Peppermint 9**

If on linux, are you using X11 or Wayland? **X11**

Fix:  Under Profile Release debug=, change "1" to true.

**Comment by chrisduerr** [comment] 2018-07-29 10:13
This is a bug in cargo-deb, it has already been fixed and is going to be in the next release once an update to crates.io is pushed.

This is a duplicate of #1438, which also has some information on how to install the latest version of cargo-deb directly from github.

**Comment by enizor** [comment] 2018-07-29 10:14
Duplicate of #1438. This will be fixed when `cargo-deb` publishes its new version to `crates.io`

**Closed by chrisduerr** 2018-07-29 10:13 UTC
