### ISSUE TITLE
thread 'main' panicked at 'XOpenIM failed'

### ISSUE THREAD

**Issue by xyos** [jwilm/alacritty#838] opened 2017-10-13 15:52 UTC
Which operating system does the issue occur on?
Linux leon 4.4.0-97-generic #120-Ubuntu SMP Tue Sep 19 17:28:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
If on linux, are you using X11 or Wayland?
X11

```
xyos@leon:~/code/alacritty$ RUST_BACKTRACE=1 ./target/debug/alacritty
thread 'main' panicked at 'XOpenIM failed', /home/xyos/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.6/src/platform/linux/x11/mod.rs:692:16
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: winit::platform::platform::x11::Window2::new
             at /home/xyos/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.6/src/platform/linux/x11/mod.rs:692
   7: winit::platform::platform::Window2::new
             at /home/xyos/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.6/src/platform/linux/mod.rs:181
   8: winit::window::<impl winit::WindowBuilder>::build
             at /home/xyos/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.6/src/window.rs:113
   9: glutin::platform::platform::x11::Context::new
             at /home/xyos/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.9.2/src/platform/linux/x11.rs:213
  10: glutin::platform::platform::Context::new
             at /home/xyos/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.9.2/src/platform/linux/mod.rs:52
  11: glutin::GlWindow::new
             at /home/xyos/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.9.2/src/lib.rs:322
  12: alacritty::window::Window::new
             at src/window.rs:193
  13: alacritty::display::Display::new
             at src/display.rs:140
  14: alacritty::run
             at src/main.rs:95
  15: alacritty::main
             at src/main.rs:45
  16: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  17: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  18: main
  19: __libc_start_main
  20: _start
```

**Comment by jwilm** [comment] 2017-10-13 17:10
duplicate of #830

**Closed by jwilm** 2017-10-13 17:10 UTC
