### ISSUE TITLE
Vim theme background colours not rendered properly

### ISSUE THREAD

**Issue by CarwynNelson** [jwilm/alacritty#123] opened 2017-01-07 00:20 UTC
I have the [gruvbox](https://github.com/morhetz/gruvbox) theme setup for vim but the background colour does not seem to be rendering properly.

Alacritty on the left vs iterm2 on the right

<img width="1276" alt="screen shot 2017-01-07 at 00 16 59" src="https://cloud.githubusercontent.com/assets/3310215/21737246/fcce86aa-d46e-11e6-8ffc-e09c6d2d3c45.png">

**Comment by d3rrial** [comment] 2017-01-07 00:26
This should be a duplicate of #85

**Comment by NickeZ** [comment] 2017-01-07 00:26
I also have colour issues with vim. I use the solarized dark theme in alacritty and vim. Works in st and gnome-terminal.


![vimissue](https://cloud.githubusercontent.com/assets/492753/21737361/2bb3c832-d478-11e6-96ed-a880de6523a2.png)

**Comment by CarwynNelson** [comment] 2017-01-07 00:29
Thanks @d3rrial I will close this issue and link to it in #85.

**Comment by d3rrial** [comment] 2017-01-07 00:47
@NickeZ Your issue is a separate one: alacritty re-defines terminal colors in its config file. By default, white is 0x424242 for example, which is absolutely ludicrous.
I'd recommend you try defining those colors by hand again within the .alacritty.yml config file, in accordance with your solarized dark theme. Maybe also open a new issue. I'm interested to see what comes of this.

**Comment by yangmillstheory** [comment] 2017-04-19 04:07
Should this be closed? #85 is closed but with the current build 

```
~ alacritty --version
alacritty 0.1.0
```

In `vim` I can see background colors not rendering correctly when I page up/down:

![apr-18-2017 21-02-00](https://cloud.githubusercontent.com/assets/2729079/25162895/f3d5093c-247a-11e7-8670-8fc6aa2356da.gif)

**Comment by pvaibhav** [comment] 2017-04-23 12:10
Can confirm, I have the same bug with current master

**Comment by lwouis** [comment] 2017-07-19 18:53
Also witnessing the issue on master today.

**Comment by jwilm** [comment] 2017-07-19 19:21
@lwouis I thought we had an issue tracking this specifically, but I can't seem to find it right now.

**Comment by jwilm** [comment] 2017-08-10 16:36
Would someone experiencing this issue mind taking #720 for a spin? I believe it should fix this issue.

**Comment by DivineGod** [comment] 2017-08-10 23:58
@jwilm Can confirm #720 fixes vim background issue for me

**Comment by lord-re** [comment] 2017-08-11 08:18
Same here. #720 fixes it.

**Comment by lwouis** [comment] 2017-08-11 09:50
#720 fixes it for me too. Thank you! It also fixed the basic background color which was not taking into account outside of Vim. Amazing!

On the left is before #720. On the right is with #720.
![selection_010](https://user-images.githubusercontent.com/106195/29208550-c98fedc6-7e8a-11e7-9a84-fa1072f3895a.png)

Opening a file in Vim without scrolling
![selection_011](https://user-images.githubusercontent.com/106195/29208549-c98e996c-7e8a-11e7-964d-fbda8adea047.png)

Opening a file in Vim, then scrolling down
![selection_012](https://user-images.githubusercontent.com/106195/29208548-c98bf568-7e8a-11e7-8435-fd4f13512860.png)

**Comment by jwilm** [comment] 2017-08-11 15:29
Thanks for all the feedback!

**Closed** 2017-08-11 15:30 UTC
Labels: bug, S - parser, S - render, S - terminal
