### ISSUE TITLE
Support for wl-clipboard.

### ISSUE THREAD

**Issue by c-edw** [jwilm/alacritty#2071] opened 2019-02-04 13:26 UTC
https://github.com/bugaevc/wl-clipboard has the `wl-copy` and `wl-paste` utilities which interact with the active Wayland compositor (I believe).

This would be an alternative to the hardcoded xclip.

**Comment by c-edw** [comment] 2019-02-04 18:24
Currently working on implementing this.

**Comment by chrisduerr** [comment] 2019-02-04 18:42
xclip is only a temporary solution and there has already been work put into removing this dependency.

There is no intention to add another dependency for clipboard handling either, so `wl-clipboard` will not be intergrated into Alacritty.

There has been some great work done by @trimental to add native Wayland clipboard support, though at this moment it's not obvious yet if this will be integrated into Alacritty, Winit or a separate library.

**Closed by chrisduerr** 2019-02-04 18:42 UTC

**Comment by c-edw** [comment] 2019-02-04 19:23
An absolute wontfix? I've already got something working for Wayland clipboard support - it's no larger than 100 lines total diff. Calling another binary is admittedly a bit hacky, but I see no reason this can't be put in place in the meantime, especially given `it's not obvious yet if this will be integrated into Alacritty`.

**Comment by chrisduerr** [comment] 2019-02-04 19:56
> An absolute wontfix?

Yes, this is not going to land in Alacritty, though you're free to maintain your own fork.

> I see no reason this can't be put in place in the meantime

There's nothing more permanent than a temporary solution. If this is a pain point, the effort should be put into figuring out the remaining issues in connection with winit, rather than putting effort into including this, reviewing this, maintaining this and all the other work that goes beyond just writing the code itself.

Helping out is always incredibly appreciated, however the focus should always be on what makes most sense for Alacritty in the short **and** long term.

**Comment by c-edw** [comment] 2019-02-04 20:38
I was hoping it could serve as a solution until #1583 is merged. Anyway, I respect your decision.

For anybody looking for wl-clipboard support, I'll be doing my best to keep my [WaylandClipboard](https://github.com/c-edw/alacritty/tree/WaylandClipboard) branch rebased with master until a proper implementation is merged.

**Comment by kennylevinsen** [comment] 2019-03-24 16:16
An alternative workaround would be wl-clipboard-x11, a wrapper for wl-clipboard that impersonates xclip: https://aur.archlinux.org/packages/wl-clipboard-x11/.

Good enough for alacritty.

**Comment by c-edw** [comment] 2019-03-24 16:42
I really like this solution. I'm going to delete my branch and use it instead. Thanks for telling me about it.

**Comment by nifker** [comment] 2019-07-24 20:41
Why cant we just set a variable which will specify the clipboard application?

**Comment by c-edw** [comment] 2019-07-24 21:49
@nifker AFAIK this isn't necessary anymore because Alacritty now supports the standard Wayland clipboard protocol (through the use of a library).

**Comment by kchibisov** [comment] 2019-07-24 21:49
@nifker What is the advantage of using an external clipboard? In case you are just annoyed with #2574, please keep your annoyance with you. However you can implement `wl-clipboard` support and keep it in your fork, no one stops you from doing this.

@chrisduerr already made a very solid [point](https://github.com/jwilm/alacritty/issues/2071#issuecomment-460389767) here. Just my 2 cents here: It's better fixing our current bugs rather then adding "work around"s for them and maintaining them.

**Comment by eLvErDe** [comment] 2019-09-03 19:49
Is it really supported oob ? I just built alacritty on my Debian Buster and I cannot copy paste using select / middle click, did I miss something ?

**Comment by kchibisov** [comment] 2019-09-03 19:54
@eLvErDe Have you built the latest master? What's you compositor?

**Comment by chrisduerr** [comment] 2019-09-03 19:54
Make sure you're running the latest master (db63c31554c01667b0b8b100dea0fa35e3094e07). It really depends on which compositor you're running though, since not all support primary selection clipboards.

I think Sway and Gnome have been confirmed to work so far.

**Comment by eLvErDe** [comment] 2019-09-03 19:58
Now I built 0.3.3. can't really confirm my compositor but I'm running gnome on an old AMD card with free drivers, so I guess I'm on wayland

**Comment by kchibisov** [comment] 2019-09-03 20:03
> Now I built 0.3.3.

Do you mean the latest master here? Primary clipboard shouldn't work on GNOME wayland on plain `0.3.3`.

**Comment by kchibisov** [comment] 2019-09-03 20:07
FYI you can check that you're on Wayland with `echo $WAYLAND_DISPLAY`

**Comment by eLvErDe** [comment] 2019-09-03 20:07
Fixed the typo. I built the 0.3.3 tag so I now have an answer. A bit late here for today, I'll build master tomorrow. Thanks for your support
