### ISSUE TITLE
Mouse wheel not working in WSL + Curses

### ISSUE THREAD

**Issue by f0ff886f** [jwilm/alacritty#2008] opened 2019-01-14 11:55 UTC
Win 10 1809 with and without ConPYT enabled, Alacritty 0.2.5, Archlinux WSL, fish shell, `TERM=xterm-256color`

If I load `weechat` in WSL (using Weechat 2.3 in Archlinux), the mouse wheel is not supported in Alacritty. If I open just `cmd` and enter WSL and run weechat there, the mouse wheel works fine for scrolling buffers. The exact same behaviour happens with `ranger` as well, which similarly is a curses app.

I don't know how else to test mouse support in Alacritty, but it seems that it doesn't work with WSL.

**Comment by chrisduerr** [comment] 2019-01-14 13:58
Duplicate of https://github.com/jwilm/alacritty/issues/1663.

**Closed by chrisduerr** 2019-01-14 13:58 UTC
