### ISSUE TITLE
$-sign and freeze on unknown keys.

### ISSUE THREAD

**Issue by pimpmypixel** [jwilm/alacritty#180] opened 2017-01-07 13:00 UTC
Hi Guys and congratulations on this great achievement!

I just wanted to post that on my danish macbook pro Alacritty compiled just fine (after I added 'source $HOME/.cargo/env' to my ~/.zshrc) however it crashes whenever an unknown key (say, æøå) is pressed. 
Also, the $ sign doesn't work. It's placed left of my number 1 key, and the documentation in the .yml file doesn't really tell me how to add own "custom" keys.

Thanks again!

**Comment by jwilm** [comment] 2017-07-02 00:12
Duplicate of #209

**Closed by jwilm** 2017-07-02 00:12 UTC
