### ISSUE TITLE
OSX: No redraw when changing from/to retina

### ISSUE THREAD

**Issue by philippkeller** [jwilm/alacritty#397] opened 2017-02-08 10:50 UTC
when switching a alacritty window from thunderbold display (no retina) to the laptop screen (retina) e.g. when unplugging the external screen then the font size is wrong.

I didn't find a way to force the redraw of the screen, as when starting new alactritty instances the font size is correct both on retina as on non-retina

**Comment by philippkeller** [comment] 2017-03-09 06:43
can somebody give a pointer on how to solve this issue? I've looked through the source code but couldn't find any spot where this could be solved..

**Comment by NickeZ** [comment] 2017-03-09 08:34
Might be related to glutin/winit. I'm not a mac user so I'm not sure exactly what you want to achieve but you could try some sample application from winit and see if it behaves the same I guess.

**Comment by NickeZ** [comment] 2017-03-09 09:05
Possible duplicate of #71

**Comment by swansontec** [comment] 2017-03-09 22:17
Indeed, it is a duplicate of #71.

**Closed** 2017-07-01 23:26 UTC
Labels: F - duplicate
