### ISSUE TITLE
X11 hidpi auto-scaling failed on 0.4.0

### ISSUE THREAD

**Issue by klesh** [jwilm/alacritty#3073] opened 2019-12-06 01:53 UTC
I'm using a laptop with hiDPI screen built-in, and two ordinary monitors are attached to the laptop.

on 0.3.3 or older versions, when I moved alacritty to internal screen the font was scaled properly, and when it moved to the other screens, the font was also displayed in a correct size.. Which is why I love alacritty very much..

Last night after I upgrade alacritty to 0.4.0， this feature was not working any more...

### System

OS: Archlinux
Version: 0.4.0
Linux/BSD: X11, picom, i3-gaps

### Logs

Crashes: STDERR, STDOUT
Font/Terminal size: 
```
Created log file at "/tmp/Alacritty-58626.log"
[2019-12-06 09:44] [INFO] Welcome to Alacritty
[2019-12-06 09:44] [INFO] Configuration loaded from "/home/klesh/.config/alacritty/alacritty.yml"
[2019-12-06 09:44] [DEBUG] Estimated DPR: 1
[2019-12-06 09:44] [DEBUG] Estimated Cell Size: 11 x 21
[2019-12-06 09:44] [DEBUG] Estimated Dimensions: None
[2019-12-06 09:44] [INFO] Device pixel ratio: 1
[2019-12-06 09:44] [INFO] Initializing glyph cache...
[2019-12-06 09:44] [INFO] ... finished initializing glyph cache in 0.007880115s
[2019-12-06 09:44] [INFO] Cell Size: 11 x 21
[2019-12-06 09:44] [INFO] Padding: 0 x 0
[2019-12-06 09:44] [INFO] Width: 800, Height: 600
[2019-12-06 09:44] [INFO] PTY Dimensions: Line(28) x Column(72)
[2019-12-06 09:44] [INFO] Initialisation complete
[2019-12-06 09:44] [DEBUG] New num_cols is 86 and num_lines is 48
[2019-12-06 09:44] [INFO] Width: 950, Height: 1028
```
Keyboard and bindings: 
```
Created log file at "/tmp/Alacritty-58745.log"
[2019-12-06 09:45] [INFO] Welcome to Alacritty
[2019-12-06 09:45] [INFO] Configuration loaded from "/home/klesh/.config/alacritty/alacritty.yml"
[2019-12-06 09:45] [INFO] Device pixel ratio: 1
[2019-12-06 09:45] [INFO] Initializing glyph cache...
[2019-12-06 09:45] [INFO] ... finished initializing glyph cache in 0.007810428s
[2019-12-06 09:45] [INFO] Cell Size: 11 x 21
[2019-12-06 09:45] [INFO] Padding: 0 x 0
[2019-12-06 09:45] [INFO] Width: 800, Height: 600
[2019-12-06 09:45] [INFO] PTY Dimensions: Line(28) x Column(72)
[2019-12-06 09:45] [INFO] Initialisation complete
[2019-12-06 09:45] [INFO] glutin event: NewEvents(Init)
[2019-12-06 09:45] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(65011716))), event: Resized(LogicalSize { width: 950.0, height: 1028.0 }) }
[2019-12-06 09:45] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(65011716))), event: RedrawRequested }
[2019-12-06 09:45] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(65011716))), event: Moved(LogicalPosition { x: 2882.0, y: 164.0 }) }
[2019-12-06 09:45] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(65011716))), event: Focused(true) }
[2019-12-06 09:45] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(65011716))), event: CursorMoved { device_id: DeviceId(X(DeviceId(2))), position: LogicalPosition { x: -187.0, y: 651.0 }, modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } }
[2019-12-06 09:45] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(65011716))), event: RedrawRequested }
[2019-12-06 09:45] [INFO] glutin event: EventsCleared
[2019-12-06 09:45] [INFO] Width: 950, Height: 1028
[2019-12-06 09:45] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 44385, tv_nsec: 169195900 }, requested_resume: None })
[2019-12-06 09:45] [INFO] glutin event: EventsCleared
[2019-12-06 09:45] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { tv_sec: 44385, tv_nsec: 174809449 }, requested_resume: None })
[2019-12-06 09:45] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Return), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: fals
```

**Comment by chrisduerr** [comment] 2019-12-06 13:37
Do you have any configuration file for DPI like `Xft.dpi`?

**Comment by klesh** [comment] 2019-12-07 04:06
Yes, I do.
I use autorandr postswitch script to set dpi automatically right after I plug/unplug external monitors.
It's 144 when no external monitor attached, and 96 if non-hidpi monitor is plugged

**Comment by chrisduerr** [comment] 2019-12-07 05:37
If the `Xft.dpi` is present, we will not scale windows automatically to fall more in line with how other applications behave.

Could you try removing that file to see if that behaves more like you would expect?

**Comment by klesh** [comment] 2019-12-07 09:56
I have this script because most applications behave stupidly.
And alacritty was the only smart app which deals with this hidpi/non-hidpi coexistence pretty well.
Please, don't fall in that line...
Or leave a option at least...

**Comment by kchibisov** [comment] 2019-12-07 10:10
@klesh This thing was for a long time. even with v0.3.3. If Xft.dpi is presented then we're using it, otherwise we're trying to guess it. I don't understand what you're talking about. What script? What option?

**Comment by chrisduerr** [comment] 2019-12-07 14:44
This is a duplicate of https://github.com/jwilm/alacritty/issues/2271 and I've opened an issue about this upstream already https://github.com/rust-windowing/winit/issues/836.

**Closed by chrisduerr** 2019-12-07 14:44 UTC
Labels: DS - X11, H - linux, S - dpi

**Comment by klesh** [comment] 2019-12-08 03:10
@kchibisov 
I have a hidpi internal monitor and couple of non-hidpi external monitors,  and I use a program named autorandr : https://github.com/wertarbyte/autorandr

Basically it automatically switch display configuration when I plug/unplug monitors to my laptop.
Each configuration is a folder, and autorandr will call a script named `postswitch` if it is presented in that folder. Inside that script I reset the `Xft.dpi` 
![image](https://user-images.githubusercontent.com/61080/70383451-fabb4b00-19a8-11ea-9542-e72df61ddc8c.png)

So that when I plug non-hidpi extenal monitors, my script will set the `Xft.dpi` to 96, and put "MOST" applications like Chrome/Firefox to external monitor, alacritty(0.3.3) on internal monitor(because it's the only one can still scales properly on hidpi monitor) . When all external monitors are unplugged, I reset `Xft.dpi` to 144 and then restart those "other applications", only then they will be scaled properly on the internal hidpi monitor... 

The way I see it, this might be a bug on your perspective, but a feature to me...
