### ISSUE TITLE
Support for image viewing in shell

### ISSUE THREAD

**Issue by hauleth** [jwilm/alacritty#107] opened 2017-01-06 21:51 UTC
Like iTerm2. This would be really handy.

**Comment by kazimuth** [comment] 2017-01-13 09:06
See https://github.com/jwilm/alacritty/issues/51

**Comment by maximbaz** [comment] 2017-05-15 15:03
+1 for this, although to be fair, it is possible to [preview images](https://github.com/ranger/ranger/wiki/Image-Previews) in Alacritty right now with [ranger](https://github.com/ranger/ranger) file manager. It is a different technology comparing to what iTerm2 is doing, I guess.

![alacritty](https://cloud.githubusercontent.com/assets/1177900/26064127/527c4b4c-3990-11e7-9bf2-80a7420277e3.gif)

**Comment by AndreyAntipov** [comment] 2017-06-01 11:41
@maximbaz hello, could you please provide a bit more details about how did you configured your ranger config for that?

**Comment by vkravets** [comment] 2017-06-01 13:41
@AndreyAntipov @maximbaz it's seems there is some issue with that becouse there are a lot of people cannot preview images with latest iTerm and ranger https://github.com/ranger/ranger/issues/539

@maximbaz with version of ranger you have? and which version of iTerm?

**Comment by vkravets** [comment] 2017-06-01 14:18
@AndreyAntipov @maximbaz it seems need to improve system to be able to do it on macOS
1. Downaload https://github.com/ranger/ranger/blob/master/ranger/data/scope.sh and put ~/.config/ranger
2. Configure ranger as described here https://github.com/ranger/ranger/wiki/Image-Previews

**Comment by maximbaz** [comment] 2017-06-01 14:21
@AndreyAntipov my ranger configuration consists only of one file, see the contents and where to put it [here](https://github.com/maximbaz/dotfiles/blob/1da2a3757ab0fbcdd3028fa9904482d28ec1a739/.config/ranger/rc.conf).

I'm on ArchLinux, ranger `v1.8.1`, tmux and alacritty are built directly from latest `master` branch. 

@vkravets I don't have macOS and haven't tried how things run in iTerm, sorry if I confused you 🙂

**Comment by AndreyAntipov** [comment] 2017-06-03 14:18
@maximbaz thanks!

**Comment by jwilm** [comment] 2017-07-02 01:13
Closing as a duplicate of #51

**Closed by jwilm** 2017-07-02 01:13 UTC

**Comment by rien333** [comment] 2018-10-30 11:21
Is it possible to display images without ranger? I'm used to using `imgcat` (from iTerm) and kitty's `icat` to display images sort of inline from a regular shell session.

**Comment by AkhilJalagam** [comment] 2020-07-28 17:13
> @maximbaz hello, could you please provide a bit more details about how did you configured your ranger config for that?

`sudo pip3 install ueberzug`
rc.conf:
`set preview_images_method ueberzug`

**Comment by aarmn** [comment] 2023-01-07 04:32
> > @maximbaz hello, could you please provide a bit more details about how did you configured your ranger config for that?
> 
> `sudo pip3 install ueberzug` rc.conf: `set preview_images_method ueberzug`

well it seems like ueberzug is dead now, any alternative?

**Comment by causality-loop** [comment] 2023-01-26 03:35
> > > @maximbaz hello, could you please provide a bit more details about how did you configured your ranger config for that?
> > 
> > 
> > `sudo pip3 install ueberzug` rc.conf: `set preview_images_method ueberzug`
> 
> well it seems like ueberzug is dead now, any alternative?

On an Ubuntu-based distro, I have `w3m-img` installed.  I use Ranger as a file manager.  In `~/.config/ranger/rc.conf`, I removed the line `set preview_images_method ueberzug` and verified that the line `set preview_images true` is there.  As expressed in the same file:
```
# Set the preview image method. Supported methods:
#
# * w3m (default):
#   Preview images in full color with the external command "w3mimgpreview"?
#   This requires the console web browser "w3m" and a supported terminal.
#   It has been successfully tested with "xterm" and "urxvt" without tmux.
```
Since w3m is the default preview image method, no further configuration is necessary to generate image previews in ranger.

**Comment by carterprince** [comment] 2023-09-19 16:10
@aarmn There is [ueberzugpp](https://github.com/jstkdng/ueberzugpp), which serves as a drop-in replacement written in C++.

**Comment by aarmn** [comment] 2023-09-20 07:51
> @aarmn There is [ueberzugpp](https://github.com/jstkdng/ueberzugpp), which serves as a drop-in replacement written in C++.

As a python developer that's unfortunate, either way, I should either wrestle with porting to python or use c++ which both are sub-optimal, but thanks for informing me!

**Comment by barraIhsan** [comment] 2024-06-22 12:27
Any support for windows? Even with installing [ueberzugpp](https://github.com/jstkdng/ueberzugpp) on WSL, still doesn't work (w/ [yazi](https://github.com/sxyazi/yazi))

**Comment by Proteusiq** [comment] 2024-06-27 18:45
MacOS yazi with uebetzugpp worked for me but with terrible resolution

**Comment by Ddystopia** [comment] 2024-11-04 11:27
#51 is closed, can this issue be reopened then?

**Comment by divyaranjan1905** [comment] 2024-11-11 02:23
Is this still not in consideration? My experience was that I was able to get even something as bare-bones as suckless' `st` to work with images using ueberzug, and since Alacritty was advertised with gpu rendering, I would imagine that it supports images, but it doesn't :(

**Comment by eyyyyyyy3** [comment] 2025-02-20 17:54
How come there is still no image rendering without third party solutions? This issue was opened 2017!

**Comment by Ddystopia** [comment] 2025-02-21 07:08
> How come there is still no image rendering without third party solutions? This issue was opened 2017!

Probably nobody cares to implement it. You may give it a shot

**Comment by nixpulvis** [comment] 2025-02-21 07:22
See https://github.com/alacritty/alacritty/pull/4763

**Comment by doupongzeng** [comment] 2025-04-09 09:02
Alacritty performs exceptionally well in most scenarios, but its inability to display images is a significant drawback. This limitation has repeatedly pushed me to consider switching to other terminals. Despite this, I truly enjoy using Alacritty and believe it’s an incredibly valuable tool. Adding image preview support would address this critical need and greatly enhance its utility.

**Comment by 07AyubHaris** [comment] 2026-07-03 16:34
> This issue is older than some developers at this point, I guess either contribute this feature if you can, or use a terminal which already support it.

I am trying to find a terminal that supports both images and bitmapped fonts, however so far I have found nothing on X11.
