### ISSUE TITLE
Remember window position on macOS

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#958] opened 2017-12-23 20:20 UTC
@brycefisher opened a PR (#765) for this a while back. We decided not to merge it with the following rationale:

> This PR adds a bunch of code to achieve this behavior whereas it seems to work out-of-the-box for most macOS applications. This suggests to me that something would need to change in winit. This might also be another reason why Alacritty should actually have a native cocoa component and just embed Alacritty as a library.

Discussion in this issue should focus on whether this feature can be supported via winit, and on how typical macOS applications provide this behavior. If "standard" macOS desktop app features can't be provided through winit (not just not implemented, actually impossible), then we should start another discussion about running Alacritty from a standard cocoa app. Other motivation for such a change is supporting multiple windows within a single process.

**Comment by brycefisher** [comment] 2017-12-23 20:28
100% agree with all of that

**Comment by sodiumjoe** [comment] 2017-12-23 20:43
This is also already listed in #909.

**Comment by chrisduerr** [comment] 2019-06-20 11:29
This is a duplicate of https://github.com/jwilm/alacritty/issues/669.

**Closed by chrisduerr** 2019-06-20 11:29 UTC
Labels: H - macos, enhancement
