### ISSUE TITLE
Unknown character in window title

### ISSUE THREAD

**Issue by NicolaiRuckel** [jwilm/alacritty#1756] opened 2018-11-07 14:18 UTC
Since the last update I have an unknown symbol in my title bar.
![screenshot-2018-11-07-15 07 09](https://user-images.githubusercontent.com/831282/48136089-108aa800-e29f-11e8-9fa7-bf3b6cfb5e9d.png)
This also happens if I set the window_title to non-dynamic.
I am using Arch Linux and i3 (so I am on X11) and I don't have this problem with other applications.

**Comment by chrisduerr** [comment] 2018-11-07 19:51
It looks like it's just displaying your shell prompt. Do you have any strange characters at the end of your prompt?

Also is this always broken no matter which application sets the title? When using the dynamic title, using `weechat` for example, is the glyph at the end still the missing symbol character?

**Comment by chrisduerr** [comment] 2018-11-07 20:41
@vpzomtrrfrt Thanks a lot for the feedback, that's very helpful. I'd like to note that i3 also recently got a new update (4.16), so it's not unlikely that this introduced a regression.

**Comment by vpzomtrrfrt** [comment] 2018-11-09 01:56
This seems to be an issue with glutin, so I've opened tomaka/glutin#1083

**Comment by NicolaiRuckel** [comment] 2018-11-09 06:37
Thank you!

**Comment by crocket** [comment] 2018-11-09 12:54
After upgrading i3 to 4.16, I experience this issue, too.

**Comment by psychon** [comment] 2018-11-09 15:11
Let's do some cross linking:
- Also reported to i3: https://github.com/i3/i3/issues/3515
- Already fixed in winit: https://github.com/tomaka/winit/pull/658

**Comment by chrisduerr** [comment] 2018-11-09 16:41
This will be fixed with #1403.

**Closed** 2018-11-10 16:08 UTC
