### ISSUE TITLE
alacritty freezes after extremely long output without newline

### ISSUE THREAD

**Issue by LunarLambda** [jwilm/alacritty#2807] opened 2019-09-18 23:23 UTC
I'm on Linux, X11, Alacritty 0.3.3

Running any command which produces a ton of output without newlines (~900K-1MB?) causes alacritty to completely freeze up, hanging at 100% CPU usage and very little memory.

I'm using the default scrollback configuration (my config file is at https://github.com/lunarlambda/dotfiles/blob/master/alacritty/alacritty.yml)

The simplest way of reproducing the issue is running `while true; do; echo -n a; done` and waiting a few seconds. It doesn't always happen though, if you introduce colorization it becomes way more consistent. For example, using `fd -0` (sharkdp/fd) or piping things through `lolcat`.
Another one that triggered it consistently was `ls -R --color=always | tr -d '\n'`

In the `ls` and `fd` cases, the command finished completely and the shell prompt displayed before alacritty froze.

Memory usage stayed low, so not an OOM error, I believe.

Endlessly outputting lines via `yes` or similar didn't do anything, even after lengthy waiting.

**Comment by chrisduerr** [comment] 2019-09-19 14:00
Sounds like a duplicate of #2217, feel free to give #2438 a shot, that should fix it.

**Closed by chrisduerr** 2019-09-19 14:00 UTC

**Comment by LunarLambda** [comment] 2019-09-19 14:07
Read through #2217 and this doesn't sound like the same issue at all: No lag/delays, alacritty just freezes completely. Vim/Nano/Tmux and similar all run perfectly fine, even if used for hours, but here it would sometimes freeze after 3 seconds of output or so.

print-events also stopped outputting anything. I'll see if #2438 fixes it

**Comment by chrisduerr** [comment] 2019-09-19 14:08
Just try it out, I'm pretty confident this is the same issue.
