### ISSUE TITLE
Flickering prompt string and window resize in tiling WM

### ISSUE THREAD

**Issue by drdeimos** [jwilm/alacritty#1431] opened 2018-07-15 09:46 UTC
* Which operating system does the issue occur on?
Ubuntu 16.04 amd64

* If on linux, are you using X11 or Wayland?
X11

If compare with gnome-terminal - cmd promt flickering much more often.
On gif in attach this is badly noticeable, but in fact the gnome terminal blinks once a second if you hold enter.

Also flickering when window resize (user WM bspwm).
It's possible to reduce flickering?

So that would be visually faster:
- Launch (the window is drawn for a long time. Just like the gnome-terminal speed)
- Less flickering everiwhere. With daily seating in the console (12h work) - it's very annoying
- Do not blink while resizing the window

![flickering](https://user-images.githubusercontent.com/3472810/42732595-fae6edbe-882c-11e8-8dff-ae8ecdf54553.gif)

**Comment by drdeimos** [comment] 2018-07-15 10:01
Also filelist flickering on simple `ls -lha` command:
![flickering_2](https://user-images.githubusercontent.com/3472810/42732741-31c8613a-882f-11e8-93ad-7c248e725da0.gif)

**Comment by chrisduerr** [comment] 2018-07-15 19:40
Hello, it looks like the flickering is a duplicate of #869, this should be fixed with winit 0.15.1, so make sure you're up to date!

The other flickering might be related to the redraw-rate of Alacritty, if I had to take a guess Alacritty is redrawing while the text is being written, which causes a perceived "flickering".

**Closed** 2018-11-24 21:43 UTC
