### ISSUE TITLE
Mocp drawing is broken

### ISSUE THREAD

**Issue by DarkDefender** [jwilm/alacritty#1933] opened 2018-12-28 11:01 UTC
> Which operating system does the issue occur on?
Linux

> If on linux, are you using X11 or Wayland?
X11

I could have sworn this was fixed in the past. But I can not find the previous issue for this, so I guess this might have been on IRC (or it was only in my dreams...)

The issue is that mocp uses a terminal command to draw/redraw the progress bar. However it seems like this command is not working as it should in alacritty.

The issue happens when playing an audio file and the progress bar is moving along the bottom:
![mocp2](https://user-images.githubusercontent.com/312503/50513401-e03dd980-0a97-11e9-80c3-a6edf6f861a0.png)

The the progress bar hits the same position as the square bracket time stamp, the left most cell will vanish and there will be a gap in the progress bar too.

IIRC, this was a problem in the early days of alacritty too. But back then it was because the terminal command code used in this operation was not implemented. So this is a regression of sorts. But I don't know when the regression happened...

This happens with `TERM` set to either alacritty or xterm

**Comment by DarkDefender** [comment] 2018-12-28 12:35
@chrisduerr nope, that was a separate issue. That still works as it should.

**Comment by chrisduerr** [comment] 2018-12-28 12:53
The problem with an `optimized redraw command` is that it might not be 100% sound and cause issues with Alacritty, since some programs rely on slow drawing terminals or just partial damaging of the viewport instead of full redraws.

Would be good to find an independent example to make it clear that this is actually an issue with Alacritty and not just `mocp` trying to use a 'hack' for redrawing faster which isn't guaranteed to work properly by the various terminal specifications.

**Comment by DarkDefender** [comment] 2018-12-28 13:03
I think was a simple term code that it used. It's using ncurses from drawing IIRC.

It there a way to see the term codes sent in a debug mode?

**Comment by chrisduerr** [comment] 2018-12-28 13:16
The command `alacritty -vv` will print all unhandled escape codes sent.

To print every escape code, you'd have to modify the code. However there will likely be A LOT of escape codes.

**Comment by DarkDefender** [comment] 2018-12-28 14:12
This works as it should in the 0.1.1 release. So this seems to be a regression. I'll try to narrow down the commit that broke it.

**Comment by chrisduerr** [comment] 2018-12-28 14:15
Thanks, that will likely help a ton. Especially if it was a small commit which broke things.

**Comment by chrisduerr** [comment] 2018-12-30 20:16
Here's a simple minimal command for reproducing this issue:
```bash
echo -e "\e[41ma\e[10Xte\t\tst"
```

It seems like the `\e[10X` escape sequence should change the color for the next 10 cells, however since tabs are more than one cell long, things get messed up. The correct behavior here would be to treat all tab characters as only a single character extension.

**Comment by DarkDefender** [comment] 2018-12-31 12:14
I should note that this is a redraw issue. It renders fine at first. But some new draw commands seems to mess up the existing cells.

I also noticed some problems in weechat where letters disappear from the input field if I move the text cursor over them. But I haven't checked if it is 0c3e286 that is the cause for this too yet...

**Comment by DarkDefender** [comment] 2018-12-31 14:07
No, I'm running it without tmux/screen.
![out](https://user-images.githubusercontent.com/312503/50561632-c953ed00-0d0c-11e9-8052-1abab3939115.gif)

![out2](https://user-images.githubusercontent.com/312503/50561727-cc031200-0d0d-11e9-9d07-683f0bb47e8b.gif)

**Comment by chrisduerr** [comment] 2018-12-31 14:56
I can not reproduce this. Which shell are you running? Are you certain this is caused by the commit you've linked (do both these issues get fixed with the previous commit?)?

**Comment by DarkDefender** [comment] 2018-12-31 16:39
Yes both gets fixed if I revert the changes made to `src/term/mod.rs` in 0c3e286

**Comment by jclinton** [comment] 2019-01-02 16:09
I'm also affected by this in Emacs terminal mode and can confirm that reverting [0c3e286](https://github.com/jwilm/alacritty/commit/0c3e28617a95b4ca30ad9bdbb9114f1e4d41dce5) resolves the issue.

The symptoms are exactly the same as the animated GIFs as shown in [the comment above](https://github.com/jwilm/alacritty/issues/1933#issuecomment-450649585): when moving the cursor to the right, the character glyph under the previous position randomly vanishes.

(BTW, reverting has a minor conflict because of some refactor that has already happened in `src/renderer/mod.rs`.)

**Comment by jclinton** [comment] 2019-01-02 16:13
If it helps, my `TERM` is `xterm-24bits` whose terminfo definition came from this: https://www.gnu.org/software/emacs/manual/html_node/efaq/Colors-on-a-TTY.html .

**Closed** 2019-01-13 21:54 UTC
Labels: A - needs repro, B - bug
