### ISSUE TITLE
Alacritty does panics during compile on macOS 10.12

### ISSUE THREAD

**Issue by bronzehedwick** [jwilm/alacritty#891] opened 2017-11-07 14:01 UTC
Which operating system does the issue occur on?

This occurs on macOS, version:
```
ProductName:	Mac OS X
ProductVersion:	10.12.6
BuildVersion:	16G29
```

Rust version:
`rustup 1.7.0 (813f7b7a8 2017-10-30)`

Error output:
```

       Fresh libc v0.2.30
       Fresh foreign-types v0.2.0
       Fresh strsim v0.6.0
       Fresh log v0.3.8
       Fresh utf8-ranges v1.0.0
       Fresh lazy_static v0.2.8
       Fresh malloc_buf v0.0.6
       Fresh odds v0.2.25
       Fresh smallvec v0.4.3
       Fresh approx v0.1.1
       Fresh iovec v0.1.0
       Fresh errno v0.2.3
       Fresh nodrop v0.1.9
       Fresh ansi_term v0.9.0
       Fresh stable_deref_trait v1.0.0
       Fresh term_size v0.3.0
       Fresh arraydeque v0.2.3
       Fresh linked-hash-map v0.4.2
       Fresh fsevent-sys v0.1.6
       Fresh utf8parse v0.1.0
       Fresh shared_library v0.1.7
       Fresh memchr v1.0.1
       Fresh unicode-xid v0.0.4
       Fresh owning_ref v0.3.3
       Fresh itoa v0.3.3
       Fresh aho-corasick v0.6.3
       Fresh bitflags v0.7.0
       Fresh dtoa v0.4.2
       Fresh quote v0.3.15
       Fresh pkg-config v0.3.9
       Fresh fsevent v0.2.16
       Fresh atty v0.2.2
       Fresh block v0.1.6
       Fresh rustc-serialize v0.3.24
       Fresh serde v0.9.15
       Fresh synom v0.11.3
       Fresh linked-hash-map v0.3.0
       Fresh xdg v2.1.0
       Fresh unicode-width v0.1.4
       Fresh syn v0.11.11
       Fresh yaml-rust v0.3.5
       Fresh unicode-segmentation v1.2.0
       Fresh textwrap v0.7.0
       Fresh lazycell v0.4.0
       Fresh vec_map v0.8.0
       Fresh khronos_api v1.0.1
       Fresh void v1.0.2
       Fresh filetime v0.1.10
       Fresh serde v1.0.11
       Fresh unreachable v1.0.0
       Fresh winapi-build v0.1.1
       Fresh bitflags v0.9.1
       Fresh thread_local v0.3.4
       Fresh xml-rs v0.6.1
       Fresh clap v2.26.0
       Fresh gl_generator v0.5.5
       Fresh heapsize v0.3.9
       Fresh objc v0.2.2
       Fresh lazycell v0.5.1
       Fresh rand v0.3.16
       Fresh gleam v0.4.8
       Fresh parking_lot_core v0.2.4
       Fresh cgl v0.2.1
       Fresh regex-syntax v0.4.1
       Fresh parking_lot v0.4.5
       Fresh regex v0.2.2
       Fresh fnv v1.0.5
       Fresh core-foundation-sys v0.4.4
       Fresh core-foundation-sys v0.3.1
       Fresh env_logger v0.4.3
       Fresh core-foundation v0.4.4
       Fresh core-foundation v0.3.0
       Fresh objc_id v0.1.0
       Fresh slab v0.3.0
       Fresh vte v0.3.2
       Fresh core-graphics v0.8.2
       Fresh objc-foundation v0.1.1
       Fresh serde_derive_internals v0.15.1
       Fresh winapi v0.2.8
       Fresh cocoa v0.9.2
       Fresh copypasta v0.0.1 (file:///Users/delucac/Documents/alacritty/copypasta)
       Fresh serde_derive v1.0.11
       Fresh kernel32-sys v0.2.2
       Fresh winit v0.7.6
       Fresh num-traits v0.1.40
       Fresh cfg-if v0.1.2
       Fresh walkdir v0.1.8
       Fresh glutin v0.9.2
       Fresh cgmath v0.15.0
       Fresh net2 v0.2.31
       Fresh serde_yaml v0.7.1
       Fresh euclid v0.12.0
       Fresh serde_json v1.0.2
       Fresh mio v0.6.10
       Fresh notify v4.0.1
       Fresh core-text v6.1.2
       Fresh mio-more v0.1.0
       Fresh font v0.1.0 (file:///Users/delucac/Documents/alacritty/font)
   Compiling alacritty v0.1.0 (file:///Users/delucac/Documents/alacritty)
     Running `rustc --crate-name alacritty src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 --cfg 'feature="default"' -C metadata=5e350ff163786454 -C extra-filename=-5e350ff163786454 --out-dir /Users/delucac/Documents/alacritty/target/release/deps -L dependency=/Users/delucac/Documents/alacritty/target/release/deps --extern serde_derive=/Users/delucac/Documents/alacritty/target/release/deps/libserde_derive-bde7297987eb06f6.dylib --extern serde=/Users/delucac/Documents/alacritty/target/release/deps/libserde-b70994c07ba57906.rlib --extern xdg=/Users/delucac/Documents/alacritty/target/release/deps/libxdg-9927f7584121c845.rlib --extern parking_lot=/Users/delucac/Documents/alacritty/target/release/deps/libparking_lot-c67c52c280106222.rlib --extern cgmath=/Users/delucac/Documents/alacritty/target/release/deps/libcgmath-a548a2b52230de17.rlib --extern arraydeque=/Users/delucac/Documents/alacritty/target/release/deps/libarraydeque-be4bdd93812ca0ba.rlib --extern copypasta=/Users/delucac/Documents/alacritty/target/release/deps/libcopypasta-29ba2a45d70f5be8.rlib --extern serde_json=/Users/delucac/Documents/alacritty/target/release/deps/libserde_json-9eef2522180ee400.rlib --extern libc=/Users/delucac/Documents/alacritty/target/release/deps/liblibc-a74272b56f4b142f.rlib --extern notify=/Users/delucac/Documents/alacritty/target/release/deps/libnotify-1bac8de134bc9b65.rlib --extern mio=/Users/delucac/Documents/alacritty/target/release/deps/libmio-c3287260894458e7.rlib --extern env_logger=/Users/delucac/Documents/alacritty/target/release/deps/libenv_logger-4a2ee9c770e17b6e.rlib --extern serde_yaml=/Users/delucac/Documents/alacritty/target/release/deps/libserde_yaml-3ae955a971d2c3fc.rlib --extern vte=/Users/delucac/Documents/alacritty/target/release/deps/libvte-e98c0b606092e5fe.rlib --extern mio_more=/Users/delucac/Documents/alacritty/target/release/deps/libmio_more-8467ba602dff6b8a.rlib --extern bitflags=/Users/delucac/Documents/alacritty/target/release/deps/libbitflags-4bf914584211d875.rlib --extern font=/Users/delucac/Documents/alacritty/target/release/deps/libfont-ba2a34304f803300.rlib --extern unicode_width=/Users/delucac/Documents/alacritty/target/release/deps/libunicode_width-fa365370873b727b.rlib --extern fnv=/Users/delucac/Documents/alacritty/target/release/deps/libfnv-557bfb60b466380f.rlib --extern errno=/Users/delucac/Documents/alacritty/target/release/deps/liberrno-943a85b6dea28914.rlib --extern glutin=/Users/delucac/Documents/alacritty/target/release/deps/libglutin-1fe1605dc4634ccc.rlib --extern clap=/Users/delucac/Documents/alacritty/target/release/deps/libclap-443f7126ff6c1399.rlib --extern log=/Users/delucac/Documents/alacritty/target/release/deps/liblog-cbc3786f4c67fe67.rlib`
error: proc-macro derive panicked
   --> src/ansi.rs:463:73
    |
463 | #[derive(Debug, Copy, Clone, Eq, PartialEq, PartialOrd, Ord, Serialize, Deserialize)]
    |                                                                         ^^^^^^^^^^^
    |
    = help: message: proc_macro::__internal::with_parse_sess() called before set_parse_sess()!

error: Could not compile `alacritty`.

Caused by:
  process didn't exit successfully: `rustc --crate-name alacritty src/lib.rs --crate-type lib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 --cfg feature="default" -C metadata=5e350ff163786454 -C extra-filename=-5e350ff163786454 --out-dir /Users/delucac/Documents/alacritty/target/release/deps -L dependency=/Users/delucac/Documents/alacritty/target/release/deps --extern serde_derive=/Users/delucac/Documents/alacritty/target/release/deps/libserde_derive-bde7297987eb06f6.dylib --extern serde=/Users/delucac/Documents/alacritty/target/release/deps/libserde-b70994c07ba57906.rlib --extern xdg=/Users/delucac/Documents/alacritty/target/release/deps/libxdg-9927f7584121c845.rlib --extern parking_lot=/Users/delucac/Documents/alacritty/target/release/deps/libparking_lot-c67c52c280106222.rlib --extern cgmath=/Users/delucac/Documents/alacritty/target/release/deps/libcgmath-a548a2b52230de17.rlib --extern arraydeque=/Users/delucac/Documents/alacritty/target/release/deps/libarraydeque-be4bdd93812ca0ba.rlib --extern copypasta=/Users/delucac/Documents/alacritty/target/release/deps/libcopypasta-29ba2a45d70f5be8.rlib --extern serde_json=/Users/delucac/Documents/alacritty/target/release/deps/libserde_json-9eef2522180ee400.rlib --extern libc=/Users/delucac/Documents/alacritty/target/release/deps/liblibc-a74272b56f4b142f.rlib --extern notify=/Users/delucac/Documents/alacritty/target/release/deps/libnotify-1bac8de134bc9b65.rlib --extern mio=/Users/delucac/Documents/alacritty/target/release/deps/libmio-c3287260894458e7.rlib --extern env_logger=/Users/delucac/Documents/alacritty/target/release/deps/libenv_logger-4a2ee9c770e17b6e.rlib --extern serde_yaml=/Users/delucac/Documents/alacritty/target/release/deps/libserde_yaml-3ae955a971d2c3fc.rlib --extern vte=/Users/delucac/Documents/alacritty/target/release/deps/libvte-e98c0b606092e5fe.rlib --extern mio_more=/Users/delucac/Documents/alacritty/target/release/deps/libmio_more-8467ba602dff6b8a.rlib --extern bitflags=/Users/delucac/Documents/alacritty/target/release/deps/libbitflags-4bf914584211d875.rlib --extern font=/Users/delucac/Documents/alacritty/target/release/deps/libfont-ba2a34304f803300.rlib --extern unicode_width=/Users/delucac/Documents/alacritty/target/release/deps/libunicode_width-fa365370873b727b.rlib --extern fnv=/Users/delucac/Documents/alacritty/target/release/deps/libfnv-557bfb60b466380f.rlib --extern errno=/Users/delucac/Documents/alacritty/target/release/deps/liberrno-943a85b6dea28914.rlib --extern glutin=/Users/delucac/Documents/alacritty/target/release/deps/libglutin-1fe1605dc4634ccc.rlib --extern clap=/Users/delucac/Documents/alacritty/target/release/deps/libclap-443f7126ff6c1399.rlib --extern log=/Users/delucac/Documents/alacritty/target/release/deps/liblog-cbc3786f4c67fe67.rlib` (exit code: 101)
```

**Comment by sandersantema** [comment] 2017-11-07 16:06
I'm not knowledgeable enough to fix this but as a wild guess, have you tried updating rust? If not:
 ```sh
   rustup override set stable
   rustup update stable
   ```
I'm running Mac OS 10.12.6 with rustc 1.21.0 (manually installed, the homebrew version doesn't work according to the installation notes) and I haven't encountered any problems compiling the master branch.

**Comment by jwilm** [comment] 2017-11-07 16:09
duplicate of #537

**Closed by jwilm** 2017-11-07 16:09 UTC
