### ISSUE TITLE
mac alt modifier broken

### ISSUE THREAD

**Issue by monouser7dig** [jwilm/alacritty#1085] opened 2018-02-03 13:44 UTC
macOS 10.13.3

holding `alt + / => |` or `alt + n => ~` does somehow not work for me anymore

**Comment by monouser7dig** [comment] 2018-02-18 18:10
**seems to be an issue with german keyboard layout**, never noticed it on my US keyboard and if I switch the german one in software it works (like on a normal US keyboard)

can this mapping be added or maybe alt is just not supported?

**Comment by jwilm** [comment] 2018-02-18 19:58
There's an outstanding bug in winit to properly support non-US-QWERTY layouts. The bug is basically that the keymap is applied for _received characters_, but not for _key codes_. I believe this is a duplicate of #458.

**Closed by jwilm** 2018-02-18 19:58 UTC
