### ISSUE TITLE
Ubuntu 16.04: 

### ISSUE THREAD

**Issue by naftulikay** [jwilm/alacritty#1177] opened 2018-03-11 20:36 UTC
### Environment

```
X11, Kernel 4.13.0-36-generic, Ubuntu 16.04 (elementary OS 0.4.1 Loki) amd64
```

I have installed the packages listed in the README.

### Issue

Alacritty panics on start:

```
$ alacritty
thread 'main' panicked at 'XOpenIM failed', /home/naftuli/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.11.1/src/platform/linux/x11/mod.rs:959:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Backtrace:

```
$ RUST_BACKTRACE=1 alacritty
thread 'main' panicked at 'XOpenIM failed', /home/naftuli/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.11.1/src/platform/linux/x11/mod.rs:959:17
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:68
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:397
             at /checkout/src/libstd/panicking.rs:577
   3: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:538
   4: winit::platform::platform::x11::Window::new
             at /home/naftuli/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.11.1/src/platform/linux/x11/mod.rs:959
   5: winit::window::<impl winit::WindowBuilder>::build
             at /home/naftuli/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.11.1/src/platform/linux/mod.rs:120
             at /home/naftuli/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.11.1/src/window.rs:119
   6: glutin::platform::platform::x11::Context::new
             at /home/naftuli/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.13.0/src/platform/linux/x11.rs:207
   7: alacritty::window::Window::new
             at /home/naftuli/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.13.0/src/platform/linux/mod.rs:58
   8: alacritty::main
             at src/display.rs:140
             at src/main.rs:62
   9: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  10: main
  11: __libc_start_main
  12: _start
```

Really hoping to start using Alacritty.

**Comment by chrisduerr** [comment] 2018-03-11 20:46
This is a duplicate of #830, there are some workarounds in that issue that might help you out.

**Closed by chrisduerr** 2018-03-11 20:46 UTC
