### ISSUE TITLE
Incremental release build broken

### ISSUE THREAD

**Issue by mindriot101** [jwilm/alacritty#547] opened 2017-05-07 16:52 UTC
This is more a FYI but I recently had trouble compiling on stable rust (1.17.0) with incremental builds (CARGO_INCREMENTAL=1). I get the error pasted below.

I'm on OSX 10.12.4 with rustc 1.17.0. The build succeeds with a debug build but performance is reduced. The build also succeeds without CARGO_INCREMENTAL set (`CARGO_INCREMENTAL= cargo build --release`).

This issue also occurs with the current nightly compiler (rustc 1.19.0-nightly (2d4ed8e0c 2017-05-03)), so presumably it's some unfortunate interaction with `alacritty` and incremental builds.

In summary: build with `CARGO_INCREMENTAL= cargo build --release`

```
   Compiling alacritty v0.1.0 (file:///Users/simon/Documents/Development/forks/alacritty)
warning: the option `Z` is unstable and should only be used on the nightly compiler, but it is currently accepted for backwards compatibility; this will soon change, see issue #31847 for more details

warning: the option `Z` is unstable and should only be used on the nightly compiler, but it is currently accepted for backwards compatibility; this will soon change, see issue #31847 for more details

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-L" "/Users/simon/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alacritty.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alacritty-ansi.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alacritty-config.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alacritty-display.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alacritty-event.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alacritty-event_loop.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alacritty-grid.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alacritty-index.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alacritty-input.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alacritty-sync.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alacritty-term-cell.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alacritty-term.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alacritty-tty.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alacritty-util-fmt.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alacritty-util-thread.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alacritty-util.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alacritty.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alloc-arc.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alloc-boxed.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.alloc-raw_vec.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.collections-borrow.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.collections-slice-hack.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.collections-slice.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.collections-string.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.collections-vec.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.collections-vec_deque.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.copypasta-macos.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.core-any.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.core-convert.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.core-fmt-builders.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.core-fmt.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.core-iter.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.core-ops.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.core-option.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.core-ptr.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.core-result.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.core-slice.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.dtoa-diyfp.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.dtoa.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.glutin-events.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.glutin-window.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.itoa.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.log.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.mio-channel.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.mio-poll.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.notify-fsevent.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.serde-ser.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.serde_json-error.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.serde_json-ser.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-collections-hash-map.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-collections-hash-table.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-fs.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-io-error.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-panic.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-panicking.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-path.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-process.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-sync-mpsc-mpsc_queue.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-sync-mpsc-oneshot.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-sync-mpsc-shared.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-sync-mpsc-spsc_queue.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-sync-mpsc-stream.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-sync-mpsc-sync.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-sync-mpsc.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-sync-mutex.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-sys_common-poison.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-sys_common-remutex.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.std-thread.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.utf8parse.volatile.o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674.vte.volatile.o" "-o" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps/alacritty-5f759f91eed80674" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/simon/Documents/Development/forks/alacritty/target/release/deps" "-L" "/Users/simon/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libalacritty-015380678d6fdd2b.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libcgmath-7964b7acee178b01.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libfont-a16e9ff136289846.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libeuclid-c371a97314e3c8bb.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libserde_yaml-0f0135443de6ae4a.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libfnv-557bfb60b466380f.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libnotify-254fa238b4fb97b7.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libfiletime-d39edc245044c62f.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libxdg-7b6286b4c94e9a36.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libcopypasta-ddea575134a5bc0e.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/liberrno-bd87a5b2fb49c6b0.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libparking_lot-e18848dc5f4be263.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libparking_lot_core-1ba154618d4e3267.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libsmallvec-27b1609a55656b41.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libowning_ref-cff426d51c112da4.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libglutin-5f9089a313273330.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libcgl-0f66b08e4bd0946d.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libgleam-5f39ae9b2da9657c.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libshared_library-695c4945e77ba703.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/liblazy_static-3b2d015b4349e676.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libmio-878a6eff7e53a112.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/liblog-63006d84b4444419.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libnet2-b9a4fd6fdb00550e.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/liblazycell-72a893ba7686291a.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libwalkdir-b78c33176874cea4.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libserde_json-eea150fe898f260b.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libdtoa-45dec47a3fd56f2b.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libitoa-c7a99536044acb26.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libclap-393e575a2885d525.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libunicode_segmentation-1e8141c7f7df5aed.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libunicode_width-fa365370873b727b.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libansi_term-347e6b8ef746ea62.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libstrsim-aeeeecec407bea2e.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libvte-dcc5c4db56c47787.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libutf8parse-1975f0f2aaf4869b.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libterm_size-0e8b1b826919e9b9.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libobjc_foundation-014c2bc523b5cae8.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libblock-aa3e2a80ef73cd58.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libffi_util-c3e9cd2c90c79d7c.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libnix-269f80780caf3f7a.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libvoid-04343e1a6de985ad.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libcfg_if-bf5248a8c9bf9021.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libfsevent-74821b1c8e77f8b5.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libfsevent_sys-dca722b9ea2dfc93.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libbitflags-94a27f4e8ae7115f.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libserde-9f43c5f76d4539b5.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libbitflags-75fc9619122ee22e.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libyaml_rust-11638f6f05e5eb7e.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/liblinked_hash_map-c931f7571d7a4145.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libvec_map-e3fd3c47da30be8e.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libnum-05812d9826db4f0c.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libnum_rational-85ba535a3cd2672f.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libnum_complex-fae2d43b4c95bbf7.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libnum_iter-e661d04c49c262c1.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libnum_bigint-5e17cd98fb669a05.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libnum_integer-ce1cfd8f42c64454.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libnum_traits-27480f32ccc44222.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/librustc_serialize-cce066e04585630b.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/librand-c51db30caea04fa0.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libobjc_id-841ac2e8f91d6520.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libcore_text-00a577bcbd179829.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libheapsize-3a71f9d515bb9a0d.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libcocoa-3cf1fee776942670.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libobjc-81c3110c95ab26ed.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libmalloc_buf-2d99085ec4502bb9.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libcore_graphics-fe349d1280b76bca.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libserde-06fa8c1db3a93550.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libcore_foundation-a8d7334d5f762b5b.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libcore_foundation_sys-df39c3e833946918.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/liblibc-8d751f39a7380bf8.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libbitflags-391a0dd8b771a2a0.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libslab-fb429b45099894b8.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/liballoc_jemalloc-ea49ffd3fee5264c.rlib" "/var/folders/xs/y_f1c_r570v6hmwc7mdj208h0000gn/T/rustc.rJJDPVyI8UQl/libcompiler_builtins-1afcf087346e8edb.rlib" "-framework" "ApplicationServices" "-framework" "ApplicationServices" "-framework" "AppKit" "-framework" "OpenGL" "-framework" "OpenGL" "-framework" "Foundation" "-l" "System" "-framework" "CoreServices" "-framework" "CoreServices" "-l" "objc" "-l" "objc" "-framework" "ApplicationServices" "-framework" "AppKit" "-framework" "Foundation" "-l" "objc" "-framework" "ApplicationServices" "-framework" "ApplicationServices" "-framework" "ApplicationServices" "-framework" "ApplicationServices" "-framework" "ApplicationServices" "-framework" "ApplicationServices" "-framework" "ApplicationServices" "-framework" "CoreFoundation" "-l" "System" "-l" "pthread" "-l" "c" "-l" "m"
  = note: Undefined symbols for architecture x86_64:
            "_$LT$core..fmt..Formatter$LT$$u27$a$GT$$u20$as$u20$core..fmt..Write$GT$::write_str::h6b26151e641e4a27", referenced from:
                _vtable.0 in libansi_term-347e6b8ef746ea62.rlib(ansi_term-347e6b8ef746ea62.ansi_term.o)
            "std::io::error::Error::last_os_error::h5de5e38745c68440", referenced from:
                rand::os::imp::getrandom_fill_bytes::h30b31950c8118d64 in librand-c51db30caea04fa0.rlib(rand-c51db30caea04fa0.rand-os-imp.o)
            "_$LT$std..ffi..os_str..OsStr$u20$as$u20$std..sys..imp..ext..ffi..OsStrExt$GT$::as_bytes::h2c6aff030f3c6422", referenced from:
                _$LT$std..ffi..os_str..OsStr$u20$as$u20$clap..osstringext..OsStrExt2$GT$::starts_with::h83f55c3dc7e4dc09 in libclap-393e575a2885d525.rlib(clap-393e575a2885d525.std-ffi-os_str.o)
                _$LT$std..ffi..os_str..OsStr$u20$as$u20$clap..osstringext..OsStrExt2$GT$::is_empty_::h57e10b6e72fb2a1b in libclap-393e575a2885d525.rlib(clap-393e575a2885d525.std-ffi-os_str.o)
                _$LT$std..ffi..os_str..OsStr$u20$as$u20$clap..osstringext..OsStrExt2$GT$::contains_byte::h47e572270b039092 in libclap-393e575a2885d525.rlib(clap-393e575a2885d525.std-ffi-os_str.o)
                _$LT$std..ffi..os_str..OsStr$u20$as$u20$clap..osstringext..OsStrExt2$GT$::split_at_byte::he1fa9d6dede9c185 in libclap-393e575a2885d525.rlib(clap-393e575a2885d525.std-ffi-os_str.o)
                _$LT$std..ffi..os_str..OsStr$u20$as$u20$clap..osstringext..OsStrExt2$GT$::trim_left_matches::h70dc917930ccad6e in libclap-393e575a2885d525.rlib(clap-393e575a2885d525.std-ffi-os_str.o)
                _$LT$std..ffi..os_str..OsStr$u20$as$u20$clap..osstringext..OsStrExt2$GT$::split_at::hc97f183081cd4dd4 in libclap-393e575a2885d525.rlib(clap-393e575a2885d525.std-ffi-os_str.o)
                _$LT$std..ffi..os_str..OsStr$u20$as$u20$clap..osstringext..OsStrExt2$GT$::len_::h520d9cbfa746b7e7 in libclap-393e575a2885d525.rlib(clap-393e575a2885d525.std-ffi-os_str.o)
                ...
            "_$LT$f64$u20$as$u20$core..num..dec2flt..rawfp..RawFloat$GT$::from_int::h7d00f2010b4317c5", referenced from:
                core::num::dec2flt::algorithm::fast_path::h29917a557aadaf08 in libalacritty-015380678d6fdd2b.rlib(alacritty-015380678d6fdd2b.core-num-dec2flt-algorithm.volatile.o)
                core::num::dec2flt::algorithm::fast_path::hb67036772e663269 in libserde_yaml-0f0135443de6ae4a.rlib(serde_yaml-0f0135443de6ae4a.core-num-dec2flt-algorithm.volatile.o)
                core::num::dec2flt::algorithm::fast_path::h20cc39afac371883 in libclap-393e575a2885d525.rlib(clap-393e575a2885d525.core-num-dec2flt-algorithm.volatile.o)
            "_$LT$f64$u20$as$u20$core..num..dec2flt..rawfp..RawFloat$GT$::short_fast_pow10::heb519e875929a31c", referenced from:
                core::num::dec2flt::algorithm::fast_path::h29917a557aadaf08 in libalacritty-015380678d6fdd2b.rlib(alacritty-015380678d6fdd2b.core-num-dec2flt-algorithm.volatile.o)
                core::num::dec2flt::algorithm::fast_path::hb67036772e663269 in libserde_yaml-0f0135443de6ae4a.rlib(serde_yaml-0f0135443de6ae4a.core-num-dec2flt-algorithm.volatile.o)
                core::num::dec2flt::algorithm::fast_path::h20cc39afac371883 in libclap-393e575a2885d525.rlib(clap-393e575a2885d525.core-num-dec2flt-algorithm.volatile.o)
            "core::num::bignum::Big32x40::bit_length::h68e7038d95bdf6d5", referenced from:
                core::num::dec2flt::algorithm::quick_start::hb7ef13b977f12794 in libalacritty-015380678d6fdd2b.rlib(alacritty-015380678d6fdd2b.core-num-dec2flt-algorithm.volatile.o)
                core::num::dec2flt::algorithm::quick_start::hbe03f3dbc6719de6 in libalacritty-015380678d6fdd2b.rlib(alacritty-015380678d6fdd2b.core-num-dec2flt-algorithm.volatile.o)
                core::num::dec2flt::algorithm::underflow::h9e0e34bb38b5649d in libalacritty-015380678d6fdd2b.rlib(alacritty-015380678d6fdd2b.core-num-dec2flt-algorithm.volatile.o)
                core::num::dec2flt::algorithm::underflow::he906160b0fb6c7ba in libalacritty-015380678d6fdd2b.rlib(alacritty-015380678d6fdd2b.core-num-dec2flt-algorithm.volatile.o)
                core::num::dec2flt::algorithm::quick_start::h24de5df87be1ef87 in libserde_yaml-0f0135443de6ae4a.rlib(serde_yaml-0f0135443de6ae4a.core-num-dec2flt-algorithm.volatile.o)
                core::num::dec2flt::algorithm::underflow::hd2109b3506180d04 in libserde_yaml-0f0135443de6ae4a.rlib(serde_yaml-0f0135443de6ae4a.core-num-dec2flt-algorithm.volatile.o)
                core::num::dec2flt::algorithm::quick_start::ha532eef864b6000d in libclap-393e575a2885d525.rlib(clap-393e575a2885d525.core-num-dec2flt-algorithm.volatile.o)

                # many more lines

            "std::env::home_dir::h320fa63442792c38", referenced from:
                xdg::BaseDirectories::with_env_impl::he11da2a9136e8f78 in libalacritty-015380678d6fdd2b.rlib(alacritty-015380678d6fdd2b.xdg.volatile.o)
                xdg::BaseDirectories::with_env_impl::h62863bed84ee4903 in libxdg-7b6286b4c94e9a36.rlib(xdg-7b6286b4c94e9a36.xdg.volatile.o)
            "_$LT$std..sync..mpsc..shared..Packet$LT$T$GT$$GT$::decrement::__STATIC_FMTSTR::h02078e1efa84cb63", referenced from:
                _$LT$std..sync..mpsc..shared..Packet$LT$T$GT$$GT$::decrement::h0566c7450f269293 in alacritty-5f759f91eed80674.std-sync-mpsc-shared.volatile.o
                _$LT$std..sync..mpsc..shared..Packet$LT$T$GT$$GT$::decrement::h0201d4884d08797f in libnotify-254fa238b4fb97b7.rlib(notify-254fa238b4fb97b7.std-sync-mpsc-shared.volatile.o)
                _$LT$std..sync..mpsc..shared..Packet$LT$T$GT$$GT$::decrement::he8b897cec29cb56c in libnotify-254fa238b4fb97b7.rlib(notify-254fa238b4fb97b7.std-sync-mpsc-shared.volatile.o)
            "std::process::exit::h30368c66cf0b5fe2", referenced from:
                alacritty::main::h909f323cbaf2d153 in alacritty-5f759f91eed80674.alacritty.o
                _$LT$alacritty..event..Processor$LT$N$GT$$GT$::handle_event::hb366befeb81d1425 in alacritty-5f759f91eed80674.alacritty-event.volatile.o
                alacritty::input::Action::execute::h66948a64e4871648 in alacritty-5f759f91eed80674.alacritty-input.volatile.o
                alacritty::tty::Pty::resize::hd907fe09a9f2932e in alacritty-5f759f91eed80674.alacritty-tty.volatile.o
                alacritty::tty::new::hf24f2fdf6c6f4ea2 in alacritty-5f759f91eed80674.alacritty-tty.volatile.o
                alacritty::tty::new::_$u7b$$u7b$closure$u7d$$u7d$::h6ad87ac26f83cf49 in alacritty-5f759f91eed80674.std-process.volatile.o
                alacritty::tty::sigchld::hb9771ed2221beaa5 in libalacritty-015380678d6fdd2b.rlib(alacritty-015380678d6fdd2b.alacritty-tty.o)
                ...
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error

error: Could not compile `alacritty`.

To learn more, run the command again with --verbose.

```

**Comment by jwilm** [comment] 2017-05-07 22:19
Thanks for the report! What are the steps to reproduce?

**Comment by mindriot101** [comment] 2017-05-08 08:37
As far as I can tell, enabling incremental compilation and compiling in release mode causes the failure shown:

```sh
CARGO_INCREMENTAL=1 cargo build --release
```

I do not know if this universal, or something related to my setup though - I will try in a linux VM when I get the chance.

**Comment by mindriot101** [comment] 2017-05-08 08:53
The same issue happens in a fresh debian8 virtual machine also

```sh
vagrant init debian/jessie64
vagrant up
vagrant ssh
sudo apt-get update && sudo apt-get install -y git curl cmake libfreetype6-dev \
   libfontconfig1-dev xclip

# Install rust stable
curl https://sh.rustup.rs -sSf | sh

git clone https://github.com/jwilm/alacritty
cd alacritty
CARGO_INCREMENTAL=1 cargo +stable build --release
# build failure

```

**Comment by mindriot101** [comment] 2017-05-08 08:57
I've also been running `CARGO_INCREMENTAL=1` in by dotfiles by default since February and have not run into this issue with other repositories. This seems to be something specific with `alacritty` 😞

**Comment by jwilm** [comment] 2017-05-13 00:52
I filed an issue on the rust project about this. Closing it here since there's nothing to be done.

**Closed by jwilm** 2017-05-13 00:52 UTC
