### ISSUE TITLE
Window dimensions changed automatically in i3wm when set to floating

### ISSUE THREAD

**Issue by yedhink** [jwilm/alacritty#1893] opened 2018-12-12 04:01 UTC
OS : Arch Linux  
WM : i3wm  
Version : alacritty 0.2.3  
Im using X11 with i3.  

[gif showing the error](https://i.imgur.com/x5Ml19v.gifv)

so in i3wm we can toggle windows between tiling and floating state. In terminal emulators like "st", on toggling to floating the dimensions that will be set are the user defined dimensions from the local config file.  

But in case of alacritty, i tried setting dimensions from ~/.config/alacritty/alacritty.yml, but there seems to be no use. like on the first spawn of the windows as a tiling window the right dimensions are produced. but after toggling it to tiling window and back to floating automatically, a "logical resize" of the  window is done by alacritty.  

it's not a fault of my i3 config, since i tested it with bare bones config too. and also other terminals like st fine by drawing the right dimensions and also centers the spawned terminal to center of the screen.  

is this a bug? or am i doing something wrong here?  

attaching along the log file and necessary details:  
[alacritty config](https://pastebin.com/VcNDUJWh)
[alacritty print events file](https://pastebin.com/sG02P1FE)
[xprop of automatically dimension changed window](https://pastebin.com/g6Gyt7A4)
[.Xresources](https://pastebin.com/GxNjypQb)
[i3 config](https://pastebin.com/hcTt6vEA)

**Comment by chrisduerr** [comment] 2018-12-12 14:03
This seems to be a conflict between Alacritty trying to set a size and i3 changing window sizes. Alacritty only tries to enforce the size in dimensions at startup, so if it's later resized by the window manager, Alacritty doesn't try to go against it (and I'm not sure if it should).

If you have a single screen setup, I think specifying the window size in i3 might be a better choice, since that is always considered whenever the window is put into floating mode.

**Comment by yedhink** [comment] 2018-12-13 13:33
I had tried explicitely setting the window size in my i3 config . It also produced the same kinda outcome where on the first spawn the window size is set right and then on toggling some other dimension is being set.

I had only used alacritty for only 1 hour or so. But honestly it's too good and I was on the way to completely migrating to it from st. I'm willing to help out in resolving this issue anyway I can. If this is indeed a bug then I hope for a positive reply from the maintainers.
Cheers!

**Comment by chrisduerr** [comment] 2018-12-13 15:56
The window will automatically resize itself when the DPI of the monitor is changed, but based on my experience with i3, it should not change its dimensions if you set them to `0-0` in the config and set them manually through i3.

I'm going to close this as a duplicate of https://github.com/jwilm/alacritty/issues/1825 though, since I feel like even though they're slightly different, they pretty much cover the same fundamental problem. https://github.com/jwilm/alacritty/issues/1817 is also related.

If you have any more information, please put it in the duplicated issue. I'd have to look into it myself again to properly troubleshoot what's going on though and if it can be fixed at all in Alacritty.

**Closed by chrisduerr** 2018-12-13 15:56 UTC
