### ISSUE TITLE
When resizing, the terminal becomes transparent

### ISSUE THREAD

**Issue by lukeberry99** [jwilm/alacritty#1077] opened 2018-02-01 16:37 UTC
Which operating system does the issue occur on?
Mac OSX 10.13.2 Beta (17C83a)

When resizing the window the entire terminal becomes transparent, it reappears when resizing stops. I've uploaded a video displaying this issue.

https://dsh.re/a1d20

Also, resizing itself seems sluggish - this may be a different issue.

**Comment by thecontinium** [comment] 2018-02-01 23:26
I also have this issue on macOS. 

Additionally after moving or resizing the window the mouse remains selected causing a white selection as you move it across the window. Selection remains until you click a mouse button.

**Comment by fatih** [comment] 2018-02-02 12:29
I have the same problem as well on macOS `10.13.3 (17D2047)`. Let me know if you need any kind of debugging information, happy to provide them.

**Comment by chrisduerr** [comment] 2018-02-02 13:22
This is probably related to #969 and #869. Generally our window backend seems to do some odd things with transparency.

**Comment by johnmccabe** [comment] 2018-02-28 17:01
@chrisduerr I disabled transparency by setting the following to false:
```
.with_transparency(false)
```
And rebuilt but was still seeing the same problem.
```
make clean
make app
./target/release/osx/Alacritty.app/Contents/MacOS/alacritty
```
Am I missing something in disabling transparency?

**Comment by chrisduerr** [comment] 2018-02-28 19:35
It might be a different issue. You can make sure that transparency is disabled by setting the opacity to something transparent in the config. If it's not transparent the change worked and the issue is somewhere else.

**Comment by johnmccabe** [comment] 2018-03-01 10:18
Thanks @chrisduerr rebuilding worked, I'd not been running `cargo build --release` ... 😨

**Comment by chrisduerr** [comment] 2018-03-01 16:36
Glad that fixed it. Unfortunately there are a lot of issues caused by transparency right now.

**Comment by cryptoeraser** [comment] 2018-04-03 11:03
@johnmccabe Why do we need to rebuild? Disabling the transparency in the config YAML file is not enough?

**Comment by johnmccabe** [comment] 2018-04-03 12:38
@cryptoeraser I'd followed the suggestions in #869

**Comment by chrisduerr** [comment] 2018-04-03 15:25
The problem is not with alacritty supporting trasparency, but with alacritty spawning a window that supports transparency. To make it possible to enable transparency, alacritty is compiled with transparency support built-in. And this is causing a few issues because apparently the glutin window with transparency support has a few problems.

**Comment by cryptoeraser** [comment] 2018-04-03 15:58
So, should I re-compile, with no transparency support? I am not familiar with rustlang, is there a config make file or something like that? Where I should disable a build flag or something, to make this work?

**Comment by chrisduerr** [comment] 2018-04-03 16:08
Just apply the changes suggested in #869 and then recompile it by following the official build instructions in the README.md.

If that's a bit too much for you, you'll have to wait until this issue is resolved in glutin.

**Comment by cryptoeraser** [comment] 2018-04-03 16:12
Well, I have already built it from source. Will try it tonight, should be fine. (I am on OSX - unless there are any special cases regarding OSX). Thanks.

**Comment by chrisduerr** [comment] 2018-04-03 16:25
If there are any issues, please let me know.

**Comment by chrisduerr** [comment] 2018-05-04 20:50
Closing as a duplicate, let's keep the discussion of this issue to #869 and #969.

**Closed by chrisduerr** 2018-05-04 20:50 UTC
