### ISSUE TITLE
RTL text scrambled

### ISSUE THREAD

**Issue by alerque** [jwilm/alacritty#2357] opened 2019-04-23 12:55 UTC
Testing on Linux X11, Alacritty 0.3.2...

I understand full BiDi support (as called for in #663) is a big kettle of fish. However even assuming only LTR support, there is a bug that could perhaps be fixed as a stop gab for minimally sane usefulness in mixed environments.

Here is a use case where 99% of the content is LTR, with a few included RTL words. In the back is Termite, then Atom, with Alacritty in front:

![image](https://user-images.githubusercontent.com/173595/56582039-fe978a00-65de-11e9-9998-8a4c7bbd26de.png)

Of course of these only Atom has full BiDi support and actually displays the Hebrew word RTL. However Termite in the back does something more sensible than Alacritty. At the very least it manages to get the vowel pointing marks drawn on the proper characters. In Alacritty they are offset the wrong direction and display over the wrong characters.

Note stepping over these characters in `nvim` shows that they are built using combining diacritics. Hitting <kbd>g</kbd><kbd>a</kbd> returns that the first (last if it was RTL) character is:

    <ת> 1514, U+05EA HEBREW LETTER TAV, ^KT+ < ּ> 1468, U+05BC HEBREW POINT DAGESH OR MAPIQ < ְ> 1456, U+05B0 HEBREW POINT SHEVA

Lastly note what happens when the cursor is over the character. In Termite all is well, but in Alacritty the pointing disappears altogether (even from where it was miss-drawn on the next character) as long as the `nvim` cursor is over that character. It comes back when the cursor is moved away.

![image](https://user-images.githubusercontent.com/173595/56582304-9dbc8180-65df-11e9-8e95-7e1db2f030bc.png)

For reference here is the (Markdown) text used in the examples:

```markdown
'Büyük derinlik' olarak çevrilen [תְּהוֹם]{lang="he"} ([tehom]{lang="und"}) kelimesi denizin derinlikleri, cehennemin derinlikleri anlamına geliyor.
```

**Comment by alerque** [comment] 2019-04-23 13:34
I just noticed that [Neovim GTK](https://github.com/daa84/neovim-gtk) actually has full BiDi support working. I don't know how they are drawing the terminal bits (`gtk-rs` bindings?) but it might be something to keep in mind and-or review their Rust code. 

![image](https://user-images.githubusercontent.com/173595/56584905-6d77e180-65e5-11e9-9b0b-e21bde5f4cba.png)

**Comment by chrisduerr** [comment] 2019-04-23 14:55
This is a duplicate of #663, please keep bidirectional text issues in there. There is no plan to add support for bidirectional text in the near future, so spreading different sub-problems over multiple issues will just make things harder to track and understand if someone is ever interested in tackling the problem.

Neovim GTK works completely differently from Alacritty, so it will not help us at all.

**Closed by chrisduerr** 2019-04-23 14:55 UTC

**Comment by Archie-2021** [comment] 2022-11-10 11:35
Is there any update on this issue? I would really like to use read everything in Neovim and terminal emulator support for that is necessary.
