### ISSUE TITLE
vim display distorted under cygwin and arrow keys don't work

### ISSUE THREAD

**Issue by ajkessel** [jwilm/alacritty#2766] opened 2019-08-29 16:30 UTC
I'm using alacritty on Windows to launch cygwin bash. When I open a file with cygwin vim, the display is distorted -- some of the text that was in the terminal before invoking vim is still visible -- and arrow keys don't work. I believe this may be related to alacritty not "clearing" the screen when receiving a clear screen code from the cygwin tools. Is there an easy configuration fix both for the display distortion and the arrow codes in cygwin vim?

**Comment by chrisduerr** [comment] 2019-08-29 18:09
What's the `TERM` when running Alacritty inside cygwin? Does setting it to `cygwin` change anything?

**Comment by ajkessel** [comment] 2019-08-29 18:47
It was `xterm-256color`. Setting it to `cygwin` appears to fix the failure to clear the screen properly as well as the arrow keys, so that covers most of the problem. (For some reason, I have to set the `TERM` in `.bashrc`--putting `TERM: cygwin` in `alacritty.yml` had no effect.) The only remaining problem now is highlighted text in vim becomes invisible -- e.g. if you search for a string within vim, the highlighted text is then black-on-black. I'm sure there is some way to fix this with a vim setting, although with other Windows terminals (rxvt, mintty) I didn't have this problem.

**Comment by chrisduerr** [comment] 2019-08-29 18:51
> if you search for a string within vim, the highlighted text is then black-on-black. I'm sure there is some way to fix this with a vim setting, although with other Windows terminals (rxvt, mintty) I didn't have this problem.

That sounds like a problem with your terminal/vim colorscheme.

Anyways, the `cygwin` issue is already tracked by https://github.com/jwilm/alacritty/issues/2592, so this is a duplicate of this.

Also make sure you're using the conpty backend if you've got color issues, that could fix some problems too.

**Closed by chrisduerr** 2019-08-29 18:51 UTC
