### ISSUE TITLE
Doesn't always exit on C-d (EOF)

### ISSUE THREAD

**Issue by frozencemetery** [jwilm/alacritty#1058] opened 2018-01-27 12:24 UTC
### Which operating system does the issue occur on?

Debian Testing

### If on linux, are you using X11 or Wayland?

X11

### Description

Sometimes (feels like most of the time), alacritty doesn't exit when Control-d is sent to the shell.  This works correctly in other terminal emulators, so I don't think this is a shell misbehavior.  When it hangs like this, it will exit when I press another key (even a non-printable one, like mod1).

**Comment by frozencemetery** [comment] 2018-01-27 12:27
If it helps, printing events looks like this:

```
rharwood@seton:~/alacritty$ cargo run --release -- --print-events
    Finished release [optimized + debuginfo] target(s) in 0.0 secs
     Running `target/release/alacritty --print-events`
error: XDG_RUNTIME_DIR not set in the environment.
glutin event: WindowEvent { window_id: WindowId(X(WindowId(14680067))), event: Resized(1024, 768) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(14680067))), event: Moved(0, 0) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(14680067))), event: Resized(478, 1062) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(14680067))), event: Refresh }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(14680067))), event: Focused(true) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(38654705795))), event: CursorMoved { device_id: DeviceId(X(DeviceId(3))), position: (1827, 821), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } }
glutin event: Awakened
glutin event: Awakened
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(14680067))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 32, state: Pressed, virtual_keycode: Some(D), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(14680067))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 32, state: Pressed, virtual_keycode: Some(D), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(14680067))), event: ReceivedCharacter('\u{4}') }
glutin event: Awakened
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 29, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(14680067))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 32, state: Released, virtual_keycode: Some(D), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(14680067))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 32, state: Released, virtual_keycode: Some(D), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(10))), event: Key(KeyboardInput { scancode: 97, state: Pressed, virtual_keycode: Some(RControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
```

Where the last line is me pressing control after waiting a bit in the hung state.

**Comment by chrisduerr** [comment] 2018-01-27 12:31
Might be related to #915.

**Comment by jwilm** [comment] 2018-01-28 15:26
Closing this as a duplicate of #915.

**Closed by jwilm** 2018-01-28 15:26 UTC
