### ISSUE TITLE
panicked at 'gl function was not loaded'

### ISSUE THREAD

**Issue by kthompson** [jwilm/alacritty#2740] opened 2019-08-21 21:33 UTC
I am using alacritty  0.3.3 on Windows 

I get the following error:
![Screenshot 2019-08-21 14 30 21](https://user-images.githubusercontent.com/15068/63470016-612f5400-c420-11e9-9b94-fe5450206884.png)

I suspect it is related to trying to use alacritty while being connected via remote desktop. Any chance of supporting remote desktop?

**Comment by chrisduerr** [comment] 2019-08-21 21:39
This is a duplicate of https://github.com/jwilm/alacritty/issues/2428.

Are you running an Nvidia GPU?

**Closed by chrisduerr** 2019-08-21 21:39 UTC

**Comment by kthompson** [comment] 2019-08-21 22:03
No its an Intel Iris onboard GPU. Although the computer running remote desktop is using nvidia. I am not sure which driver matters in this case.

**Comment by chrisduerr** [comment] 2019-08-21 22:25
It's the GPU of the remote desktop that matters. So afaik I don't think this is possible with consumer Nvidia GPUs.

I'm not sure if there has ever been confirmation that it does work with other cards though. So if you've got the hardware and you're interested in testing this, please let me know if my assumption based on reading the docs are incorrect.

**Comment by kthompson** [comment] 2019-08-21 22:31
So I am initiating the connection from a PC with an NVidia GeForce GTX 1070 Ti and the target computer is a laptop with an Intel Iris (the computer im trying to run alacritty on).

Alacritty does work fine when I run it directly on the laptop.

Is there anything specific you'd like me to test?

**Comment by kthompson** [comment] 2019-08-21 22:32
Oh one thing that is interesting is if I run alacrity directly and then connect via remote desktop it continues to operate normally. I just cannot launch alacritty while connected via RDP

**Comment by chrisduerr** [comment] 2019-08-21 22:55
Oh yeah, iirc Windows uses separate methods for OpenGL if you launch it during the session or before it.

One of them actually uses proper hardware OpenGL acceleration and the other one uses software emulation. I think the software emulation is likely to be broken.

**Comment by 3rdey3** [comment] 2019-12-13 08:32
I am facing the same issue, is there any work around or solution to this?

**Comment by horseinthesky** [comment] 2020-02-14 09:11
Windows 10 1909 Build 18363.657 on 1080 Ti has this issue.

**Comment by dotjairo** [comment] 2020-12-18 05:28
hi! Apologies for reviving an old (closed) thread, but it looks like this error is occurring on Alacritty 0.6.0 on the machine run by the maintainer of the [`scoop-extras`](https://github.com/lukesampson/scoop-extras/) bucket see here https://github.com/lukesampson/scoop-extras/pull/5179. This is preventing the update of Alacritty to 0.6.0 on [`scoop`](https://scoop.sh/)

**Comment by chrisduerr** [comment] 2020-12-18 14:12
Nothing has changed about this issue, please read up on the conversation before commenting for further discussion.
