### ISSUE TITLE
Crazy fast in general but very slow to start

### ISSUE THREAD

**Issue by SRGOM** [jwilm/alacritty#2161] opened 2019-03-07 14:15 UTC
Linux, Arch, X11.

Alacritty is crazy fast compared to my current terminal in printing stuff but its very slow to start up, noticeably slower... 

I couldn't benchmark because I couldn't get `time alacritty -e 'bash -c "exit"'` to work but the lag is just very clear, at least on a slightly older machine here... with termite I get `90% cpu 0.117s total` time.

**Comment by chrisduerr** [comment] 2019-03-07 20:01
Duplicate of https://github.com/jwilm/alacritty/issues/782.

**Closed by chrisduerr** 2019-03-07 20:01 UTC
