### ISSUE TITLE
Cannot copy text on OS X

### ISSUE THREAD

**Issue by swansontec** [jwilm/alacritty#89] opened 2017-01-06 19:56 UTC
When highlighting text and pressing the Command-C keyboard shortcut, I get:

    Error storing selection to clipboard. Failed to create pasteboard: [NSPasteboard generalPasteboard] failed

This is on OS X 10.12.2 with the latest Alacritty master (commit 7d07b5a1655dc9d1cda62f1dd3005b966c0fa76a).

**Comment by azhang** [comment] 2017-01-06 21:39
It works for me on 8d8fca6. (10.12.2)

**Comment by swansontec** [comment] 2017-01-06 22:59
It could be something weird with my system, too. I'd be happy to help debug this with the right pointers.

**Comment by dannydulai** [comment] 2017-01-07 00:09
The problem is most likely with how you started alacritty. How did you start alacritty? My guess is you are not attached to the user namespace... like running inside screen or tmux?

this "reattach-to-user-namespace" program fixes your issue:

http://www.economyofeffort.com/2013/07/29/reattach-to-user-namespace-the-fix-for-your-tmux-in-os-x-woes/

**Comment by swansontec** [comment] 2017-01-07 05:53
Yup, that was the problem. When I relaunched Alacritty from outside tmux, all the clipboard problems went away.

**Comment by dannydulai** [comment] 2017-01-07 05:55
cool.. can you please close the issue?

**Closed** 2017-01-07 05:56 UTC
