### ISSUE TITLE
Rendering issue with vifm

### ISSUE THREAD

**Issue by sQVe** [jwilm/alacritty#2342] opened 2019-04-21 14:34 UTC
_Thank you for an awesome terminal!_ :pray:

I'm seeing an issue with the cursor rendering with [`vifm`](https://github.com/vifm/vifm) in `alacritty`. This is the first time I've noticed it - I'm not seeing this issue with any other curses app.

![Peek 2019-04-21 16-18](https://user-images.githubusercontent.com/2284724/56471421-a03da080-6452-11e9-8b61-b1cea7c2fc21.gif)

Here's my cursor settings in alacritty:
```
cursor:
  text: '0x343434'
  cursor: '0xf8f8f2'
```

I'd love to see this fixed, give me a ping if **I can help in any way**.

:beers:

**Comment by xaizek** [comment] 2019-04-21 16:57
I didn't try to reproduce it (too long to install this terminal) and just guess this is a stable behaviour of the terminal. If that's the case, this is likely to be a problem of `alacritty`, as the issue doesn't appear in other terminals as far as I can tell and I know that the blacked out character appears where hardware cursor is positioned by `vifm`. In normal mode the terminal cursor is invisible, yet `alacritty` displays it.

**Comment by chrisduerr** [comment] 2019-04-21 17:03
@sQVe Which version of Alacritty are you using? Can you reproduce this with the latest master?

**Comment by sQVe** [comment] 2019-04-21 17:40
@chrisduerr Sorry for not providing it in the initial report. I'm running the latest code from `master`, so yeah - I can reproduce it.

```
% alacritty --version
alacritty 0.3.0

% yay -Qi alacritty-git | rg Date
Build Date      : Sun 21 Apr 2019 09:34:58 AM CEST
Install Date    : Sun 21 Apr 2019 11:16:37 AM CEST
```

**Comment by sQVe** [comment] 2019-04-21 17:48
@chrisduerr I just tried to downgrade to `0.2.9` and I'm not getting this issue with that release.

**Comment by chrisduerr** [comment] 2019-04-21 17:51
I'm asking because this was fixed in https://github.com/jwilm/alacritty/commit/0d060d5d801e3abb55035269138d819d38fc175b, so please make sure you're running the latest version not just the latest master from a few days ago.

If it still occurs then I can't reproduce this. Does this happen inside of vim too? Or inside of the normal bash/zsh/shell prompt? Or only in vifm?

**Comment by sQVe** [comment] 2019-04-21 18:51
@chrisduerr I just ran a rebuild and still seeing the issue. I can replicate in both zsh and bash normal / default prompt. I cannot replicate it inside `nvim`.

Did you set the cursor to a specific color?

**Comment by chrisduerr** [comment] 2019-04-21 18:54
You said that downgrading to 0.2.9 fixed the issue, but I'd assume that 0.3.0 would do it too? Since the cursor rework was just recently after 0.3.0. Otherwise this would be a separate issue.

I haven't been able to test this with vifm yet though, since it does not install on my system.

**Comment by xaizek** [comment] 2019-04-21 18:59
@chrisduerr, what's the issue with the installation? Regular `./configure && make` should give you a build to try (just run it as `src/vifm`).

**Comment by sQVe** [comment] 2019-04-21 19:03
@chrisduerr Yes I would think so. I don't have the possibility to try it out now currently though. I can try later if it is useful.

**Comment by chrisduerr** [comment] 2019-04-21 19:04
It would be. Knowing which commit broke it is extremely helpful for figuring out what the issue might be.

**Comment by sQVe** [comment] 2019-04-21 19:13
@chrisduerr Roger. I'll try it out ASAP. Most likely in an hour or two.

If possible I'll try to narrow it down further to a specific commit.

**Comment by sQVe** [comment] 2019-04-21 22:05
@chrisduerr I've now had the time to debug this further.

With `HEAD` at 0d060d5d801e3abb55035269138d819d38fc175b I'm seeing the issue I initially reported: 
![0d060d5d801e3abb55035269138d819d38fc175b](https://user-images.githubusercontent.com/2284724/56476075-380eaf00-6492-11e9-9e83-de289ccfab98.png)

With `HEAD` at 371d13f8ef95157c97f7de9964bcbc89d4a8e930 I'm also seeing an issue, but inverted:
![371d13f8ef95157c97f7de9964bcbc89d4a8e930](https://user-images.githubusercontent.com/2284724/56476077-3ba23600-6492-11e9-8415-28b562462e41.png)

With `HEAD` at a47d716daace7c197392854754406a06454ec380 I'm seeing **no issue**:
![a47d716daace7c197392854754406a06454ec380](https://user-images.githubusercontent.com/2284724/56476080-3f35bd00-6492-11e9-9d45-15d0a4e176a7.png)

**Comment by chrisduerr** [comment] 2019-04-21 22:30
So I've been able to get `vifm` working by installing the official archlinux package with a few additional depedencies since the git version didn't build and I'm able to reproduce the issue.

I think I know what the issue might be and will hopefully have a PR with a fix up in a sec.

**Comment by chrisduerr** [comment] 2019-04-21 22:41
Fixed in https://github.com/jwilm/alacritty/pull/2343, let me know if there's still any problems.

**Closed** 2019-04-22 00:20 UTC
Labels: B - bug
