### ISSUE TITLE
Compile error on FreeBSD 12.0-CURRENT

### ISSUE THREAD

**Issue by kcbark** [jwilm/alacritty#75] opened 2017-01-06 14:45 UTC
$ rustup override set $(cat rustc-version)
info: using existing install for 'nightly-2016-12-16-x86_64-unknown-freebsd'
info: override toolchain for '/usr/home/kc/tmp/alacritty' set to 'nightly-2016-12-16-x86_64-unknown-freebsd'

  nightly-2016-12-16-x86_64-unknown-freebsd unchanged - rustc 1.15.0-nightly (8f02c429a 2016-12-15)
$

$ cargo build --release --verbose
       Fresh log v0.3.6
       Fresh rustc-serialize v0.3.22
       Fresh lazy_static v0.1.16
       Fresh slab v0.3.0
       Fresh semver v0.1.20
       Fresh winapi v0.2.8
       Fresh phf_shared v0.7.20
       Fresh rustc_version v0.1.7
       Fresh cfg-if v0.1.0
       Fresh quote v0.3.10
       Fresh phf v0.7.20
       Fresh byteorder v0.5.3
       Fresh copypasta v0.0.1 (file:///usr/home/kc/tmp/alacritty/copypasta)
       Fresh lazy_static v0.2.2
       Fresh bitflags v0.7.0
       Fresh owning_ref v0.2.2
       Fresh crossbeam v0.2.10
       Fresh winapi-build v0.1.1
       Fresh xml-rs v0.3.5
       Fresh num-traits v0.1.36
       Fresh gcc v0.3.40
       Fresh khronos_api v1.0.0
       Fresh wayland-scanner v0.5.11
       Fresh num-integer v0.1.32
       Fresh xdg v2.0.0
       Fresh gl_generator v0.5.2
       Fresh libc v0.2.18
       Fresh num-iter v0.1.32
       Fresh bitflags v0.6.0
       Fresh bitflags v0.4.0
       Fresh unicode-xid v0.0.3
       Fresh ffi-util v0.1.0 (file:///usr/home/kc/tmp/alacritty/ffi-util)
       Fresh lazycell v0.4.0
       Fresh shared_library v0.1.5
       Fresh pkg-config v0.3.8
       Fresh rand v0.3.15
       Fresh phf_generator v0.7.20
       Fresh filetime v0.1.10
       Fresh net2 v0.2.26
       Fresh phf_codegen v0.7.20
       Fresh num-complex v0.1.35
       Fresh libz-sys v1.0.10
       Fresh void v1.0.2
       Fresh serde v0.8.19
       Fresh freetype-sys v0.4.0
       Fresh itoa v0.1.1
       Fresh serde_test v0.8.19
       Fresh freetype-rs v0.9.0
       Fresh cmake v0.1.19
       Fresh linked-hash-map v0.3.0
       Fresh serde v0.7.15
       Fresh osmesa-sys v0.1.2
       Fresh dtoa v0.2.2
       Fresh smallvec v0.1.8
       Fresh x11-dl v2.11.0
       Fresh serde_json v0.8.4
       Fresh num-bigint v0.1.35
       Fresh parking_lot_core v0.2.0
       Fresh target_build_utils v0.1.2
       Fresh num-rational v0.1.35
       Fresh parking_lot v0.3.6
       Fresh num v0.1.36
       Fresh yaml-rust v0.3.5
       Fresh serde_yaml v0.5.0
       Fresh libloading v0.3.1
       Fresh cgmath v0.7.0
       Fresh errno v0.1.8
       Fresh dlib v0.3.1
       Fresh nix v0.7.0
       Fresh mio v0.6.1
       Fresh wayland-sys v0.5.11
       Fresh expat-sys v2.1.4
       Fresh utf8parse v0.1.0
       Fresh wayland-client v0.5.12
       Fresh vte v0.1.2
       Fresh syn v0.10.3
       Fresh serde_codegen_internals v0.11.1
       Fresh serde_codegen v0.8.19
       Fresh kernel32-sys v0.2.2
       Fresh servo-fontconfig-sys v2.11.3 (https://github.com/jwilm/libfontconfig#618a5297)
       Fresh serde_derive v0.8.19
       Fresh time v0.1.35
       Fresh heapsize v0.3.7
       Fresh servo-fontconfig v0.2.0 (https://github.com/jwilm/rust-fontconfig#419135e5)
       Fresh walkdir v0.1.8
       Fresh tempfile v2.1.4
       Fresh euclid v0.6.8
       Fresh fs2 v0.2.5
       Fresh notify v2.6.3
       Fresh wayland-window v0.2.3
       Fresh font v0.1.0 (file:///usr/home/kc/tmp/alacritty/font)
       Fresh memmap v0.2.3
       Fresh wayland-kbd v0.3.6
       Fresh glutin v0.6.1 (https://github.com/jwilm/glutin?rev=af7fe340bd4a2af53ea521defcb4f377cdc588cf#af7fe340)
   Compiling alacritty v0.1.0 (file:///usr/home/kc/tmp/alacritty)
     Running `rustc --crate-name alacritty src/lib.rs --crate-type lib -C opt-level=3 -g --cfg feature=\"default\" --cfg feature=\"err-println\" -C metadata=865a76227b2878af -C extra-filename=-865a76227b2878af --out-dir /usr/home/kc/tmp/alacritty/target/release/deps --emit=dep-info,link -L dependency=/usr/home/kc/tmp/alacritty/target/release/deps --extern notify=/usr/home/kc/tmp/alacritty/target/release/deps/libnotify-c0fc6fc3ea87cb99.rlib --extern libc=/usr/home/kc/tmp/alacritty/target/release/deps/liblibc-e40fb62df1476ed4.rlib --extern serde_derive=/usr/home/kc/tmp/alacritty/target/release/deps/libserde_derive-1a7c73a6a1f28d8e.so --extern parking_lot=/usr/home/kc/tmp/alacritty/target/release/deps/libparking_lot-67b030b321542d1e.rlib --extern cgmath=/usr/home/kc/tmp/alacritty/target/release/deps/libcgmath-696974480f434850.rlib --extern vte=/usr/home/kc/tmp/alacritty/target/release/deps/libvte-f6b7b12e8ea5b53e.rlib --extern serde=/usr/home/kc/tmp/alacritty/target/release/deps/libserde-b9afc739dea07900.rlib --extern serde_json=/usr/home/kc/tmp/alacritty/target/release/deps/libserde_json-435d32eb9dedffbe.rlib --extern xdg=/usr/home/kc/tmp/alacritty/target/release/deps/libxdg-7bfd803f253b707f.rlib --extern serde_yaml=/usr/home/kc/tmp/alacritty/target/release/deps/libserde_yaml-4f089883a7cc1bef.rlib --extern errno=/usr/home/kc/tmp/alacritty/target/release/deps/liberrno-a042128eddea98d4.rlib --extern glutin=/usr/home/kc/tmp/alacritty/target/release/deps/libglutin-99a8d71925d77a45.rlib --extern mio=/usr/home/kc/tmp/alacritty/target/release/deps/libmio-3c214b3211fe56c2.rlib --extern copypasta=/usr/home/kc/tmp/alacritty/target/release/deps/libcopypasta-d5bce7618a7b2040.rlib --extern bitflags=/usr/home/kc/tmp/alacritty/target/release/deps/libbitflags-8a29c74baf48b095.rlib --extern font=/usr/home/kc/tmp/alacritty/target/release/deps/libfont-5741ff76bc0c3142.rlib -L native=/usr/local/lib -L native=/usr/local/lib -L native=/usr/lib -L native=/usr/local/lib`
error[E0432]: unresolved import `copypasta::Clipboard`
  --> src/input.rs:23:17
   |
23 | use copypasta::{Clipboard, Load, Store};
   |                 ^^^^^^^^^ no `Clipboard` in the root

error[E0425]: unresolved name `libc::TIOCSCTTY`
   --> src/tty.rs:141:25
    |
141 |         libc::ioctl(fd, libc::TIOCSCTTY as _, 0)
    |                         ^^^^^^^^^^^^^^^ unresolved name

error[E0425]: unresolved name `openpty`
   --> src/tty.rs:245:27
    |
245 |     let (master, slave) = openpty(win.ws_row as _, win.ws_col as _);
    |                           ^^^^^^^ unresolved name

error[E0277]: the trait bound `config::Font: std::default::Default` is not satisfied
   --> src/config.rs:222:19
    |
222 |             font: Default::default(),
    |                   ^^^^^^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `config::Font`
    |
    = note: required by `std::default::Default::default`

error: no associated item named `default` found for type `config::Font` in the current scope
    --> src/config.rs:1004:5
     |
1004 |     Font::default().bold
     |     ^^^^^^^^^^^^^
     |
     = help: items from traits can only be used if the trait is implemented and in scope; the following trait defines an item `default`, perhaps you need to implement it:
     = help: candidate #1: `std::default::Default`

error: no associated item named `default` found for type `config::Font` in the current scope
    --> src/config.rs:1008:5
     |
1008 |     Font::default().italic
     |     ^^^^^^^^^^^^^
     |
     = help: items from traits can only be used if the trait is implemented and in scope; the following trait defines an item `default`, perhaps you need to implement it:
     = help: candidate #1: `std::default::Default`

error[E0277]: the trait bound `config::Font: std::default::Default` is not satisfied
   --> src/config.rs:169:17
    |
169 | #[derive(Debug, Deserialize)]
    |                 ^^^^^^^^^^^ the trait `std::default::Default` is not implemented for `config::Font`
    |
    = note: required by `std::default::Default::default`

error: aborting due to 4 previous errors

error: Could not compile `alacritty`.

Caused by:
  process didn't exit successfully: `rustc --crate-name alacritty src/lib.rs --crate-type lib -C opt-level=3 -g --cfg feature="default" --cfg feature="err-println" -C metadata=865a76227b2878af -C extra-filename=-865a76227b2878af --out-dir /usr/home/kc/tmp/alacritty/target/release/deps --emit=dep-info,link -L dependency=/usr/home/kc/tmp/alacritty/target/release/deps --extern notify=/usr/home/kc/tmp/alacritty/target/release/deps/libnotify-c0fc6fc3ea87cb99.rlib --extern libc=/usr/home/kc/tmp/alacritty/target/release/deps/liblibc-e40fb62df1476ed4.rlib --extern serde_derive=/usr/home/kc/tmp/alacritty/target/release/deps/libserde_derive-1a7c73a6a1f28d8e.so --extern parking_lot=/usr/home/kc/tmp/alacritty/target/release/deps/libparking_lot-67b030b321542d1e.rlib --extern cgmath=/usr/home/kc/tmp/alacritty/target/release/deps/libcgmath-696974480f434850.rlib --extern vte=/usr/home/kc/tmp/alacritty/target/release/deps/libvte-f6b7b12e8ea5b53e.rlib --extern serde=/usr/home/kc/tmp/alacritty/target/release/deps/libserde-b9afc739dea07900.rlib --extern serde_json=/usr/home/kc/tmp/alacritty/target/release/deps/libserde_json-435d32eb9dedffbe.rlib --extern xdg=/usr/home/kc/tmp/alacritty/target/release/deps/libxdg-7bfd803f253b707f.rlib --extern serde_yaml=/usr/home/kc/tmp/alacritty/target/release/deps/libserde_yaml-4f089883a7cc1bef.rlib --extern errno=/usr/home/kc/tmp/alacritty/target/release/deps/liberrno-a042128eddea98d4.rlib --extern glutin=/usr/home/kc/tmp/alacritty/target/release/deps/libglutin-99a8d71925d77a45.rlib --extern mio=/usr/home/kc/tmp/alacritty/target/release/deps/libmio-3c214b3211fe56c2.rlib --extern copypasta=/usr/home/kc/tmp/alacritty/target/release/deps/libcopypasta-d5bce7618a7b2040.rlib --extern bitflags=/usr/home/kc/tmp/alacritty/target/release/deps/libbitflags-8a29c74baf48b095.rlib --extern font=/usr/home/kc/tmp/alacritty/target/release/deps/libfont-5741ff76bc0c3142.rlib -L native=/usr/local/lib -L native=/usr/local/lib -L native=/usr/lib -L native=/usr/local/lib` (exit code: 101)
$
 
I know FreeBSD isn't officially supported but perhaps there's an easy way to fix this? :)

**Comment by jwilm** [comment] 2017-01-06 16:12
There are some cfg target_os attributes that only mention `macos` and `linux`. It may be that we adding the appropriate attributes for bsd would fix the problem.

**Comment by computersarehard** [comment] 2017-01-11 15:09
I was curious so I hacked something up quick. Mostly the various `target_os` attributes need to be updated to include the BSDs. I also ran into a problem where libc for FreeBSD doesn't expose the `TIOCSCTTY` constant so I dropped in a magic number (what I got when I printed out the constant in a small C program). Not sure why those constants aren't available.

Things seemed to work OK. I run FreeBSD in a VM so I wasn't really expecting great performance (it was much slower than uxrvt). Here's a diff for reference:
```diff
diff --git a/copypasta/src/lib.rs b/copypasta/src/lib.rs
index b498e2e..b09c636 100644
--- a/copypasta/src/lib.rs
+++ b/copypasta/src/lib.rs
@@ -40,9 +40,9 @@ pub trait Store : Load {
         where S: Into<String>;
 }
 
-#[cfg(target_os = "linux")]
+#[cfg(any(target_os = "linux", target_os = "freebsd"))]
 mod x11;
-#[cfg(target_os = "linux")]
+#[cfg(any(target_os = "linux", target_os = "freebsd"))]
 pub use x11::{Clipboard, Error};
 
 #[cfg(target_os = "macos")]
diff --git a/src/config.rs b/src/config.rs
index e9cd505..6b2cbb3 100644
--- a/src/config.rs
+++ b/src/config.rs
@@ -1090,7 +1090,7 @@ impl Default for Font {
     }
 }
 
-#[cfg(target_os = "linux")]
+#[cfg(any(target_os = "linux", target_os = "freebsd"))]
 impl Default for Font {
     fn default() -> Font {
         Font {
diff --git a/src/tty.rs b/src/tty.rs
index ad89397..e4ace8d 100644
--- a/src/tty.rs
+++ b/src/tty.rs
@@ -113,7 +113,7 @@ fn openpty(rows: u8, cols: u8) -> (c_int, c_int) {
     (master, slave)
 }
 
-#[cfg(target_os = "macos")]
+#[cfg(any(target_os = "macos", target_os = "freebsd"))]
 fn openpty(rows: u8, cols: u8) -> (c_int, c_int) {
     let mut master: c_int = 0;
     let mut slave: c_int = 0;
@@ -139,7 +139,7 @@ fn openpty(rows: u8, cols: u8) -> (c_int, c_int) {
 /// Really only needed on BSD, but should be fine elsewhere
 fn set_controlling_terminal(fd: c_int) {
     let res = unsafe {
-        libc::ioctl(fd, libc::TIOCSCTTY as _, 0)
+        libc::ioctl(fd, 536900705 as _, 0)
     };
 
     if res < 0 {
```

**Comment by jwilm** [comment] 2017-01-11 17:10
Thanks for putting this together @computersarehard.

> I also ran into a problem where libc for FreeBSD doesn't expose the TIOCSCTTY constant so I dropped in a magic number (what I got when I printed out the constant in a small C program). Not sure why those constants aren't available.

I asked and it's probably because nobody bothered to add it.

**Comment by jwilm** [comment] 2017-02-02 18:53
We landed support for FreeBSD a few weeks ago

**Closed by jwilm** 2017-02-02 18:53 UTC

**Comment by debdrup** [comment] 2017-02-28 19:39
I don't know your policy on necroing old issues, but I just ran into an issue with TIOCSTTY again:
error: Could not compile `alacritty`.

Caused by:
  process didn't exit successfully: `rustc src/lib.rs --crate-name alacritty --crate-type lib -C opt-level=3 -g --cfg feature="err-println" --cfg feature="default" -C metadata=72ed24aa58a10
a84 --out-dir /usr/home/debdrup/alacritty/target/release/deps --emit=dep-info,link -L dependency=/usr/home/debdrup/alacritty/target/release/deps --extern log=/usr/home/debdrup/alacritty/tar
get/release/deps/liblog-bf16bb9a4912b11d.rlib --extern vte=/usr/home/debdrup/alacritty/target/release/deps/libvte-348664c9bd99c313.rlib --extern libc=/usr/home/debdrup/alacritty/target/rele
ase/deps/liblibc-6ec63c5a0e74a074.rlib --extern xdg=/usr/home/debdrup/alacritty/target/release/deps/libxdg-c2f31771a482a07f.rlib --extern serde_derive=/usr/home/debdrup/alacritty/target/rel
ease/deps/libserde_derive-ba597fcd2d5b31ac.so --extern copypasta=/usr/home/debdrup/alacritty/target/release/deps/libcopypasta.rlib --extern serde=/usr/home/debdrup/alacritty/target/release/
deps/libserde-9bae43a863ee928e.rlib --extern clap=/usr/home/debdrup/alacritty/target/release/deps/libclap-c293040e3ef9c3f9.rlib --extern mio=/usr/home/debdrup/alacritty/target/release/deps/
libmio-d8a3ebfe89185cdb.rlib --extern lazy_static=/usr/home/debdrup/alacritty/target/release/deps/liblazy_static-7f1b96a3a3eb529d.rlib --extern errno=/usr/home/debdrup/alacritty/target/rele
ase/deps/liberrno-dd19ca814654318b.rlib --extern cgmath=/usr/home/debdrup/alacritty/target/release/deps/libcgmath-27f7802c8ba9ffa4.rlib --extern font=/usr/home/debdrup/alacritty/target/rele
ase/deps/libfont.rlib --extern fnv=/usr/home/debdrup/alacritty/target/release/deps/libfnv-1364d96376ddfb32.rlib --extern serde_yaml=/usr/home/debdrup/alacritty/target/release/deps/libserde_
yaml-cdb36860fd69c651.rlib --extern serde_json=/usr/home/debdrup/alacritty/target/release/deps/libserde_json-c9bbee72def01b43.rlib --extern glutin=/usr/home/debdrup/alacritty/target/release
/deps/libglutin-203de72556d6cf53.rlib --extern parking_lot=/usr/home/debdrup/alacritty/target/release/deps/libparking_lot-f7aa313f236c79ca.rlib --extern bitflags=/usr/home/debdrup/alacritty
/target/release/deps/libbitflags-0e272044714c8076.rlib --extern notify=/usr/home/debdrup/alacritty/target/release/deps/libnotify-710c0f59da2a1b99.rlib -L native=/usr/local/lib -L native=/us
r/local/lib -L native=/usr/local/lib -L native=/usr/lib` (exit code: 101)

I'm not entirely sure what file to edit to manually input this magic number..

**Comment by jwilm** [comment] 2017-02-28 19:43
@debdrup are you on FreeBSD or another BSD variant? Do you have the latest Alacritty source?

**Comment by debdrup** [comment] 2017-02-28 20:31
FreeBSD 11.0-STABLE r313553, with  git cloned ~10 minutes before I posted that.

**Comment by jwilm** [comment] 2017-02-28 20:52
Would you mind posting the full compilation log?

**Comment by debdrup** [comment] 2017-02-28 21:14
No problem. [alacritty.log](https://paste.sh/Uzijdikq#zmSGCd8RLqH20yM7maHgNilf)

**Comment by jiixyj** [comment] 2017-02-28 22:21
Rust does not define TIOCSCTTY for any OS besides Linux and MacOS. As @computersarehard mentioned, something like the patch below still seems to be needed. But other than that, `alacritty` builds fine on FreeBSD-CURRENT.

```diff
diff --git a/src/tty.rs b/src/tty.rs
index 39d3dee..f511108 100644
--- a/src/tty.rs
+++ b/src/tty.rs
@@ -21,7 +21,7 @@ use std::os::unix::process::CommandExt;
 use std::ptr;
 use std::process::{Command, Stdio};
 
-use libc::{self, winsize, c_int, pid_t, WNOHANG, WIFEXITED, WEXITSTATUS, SIGCHLD, TIOCSCTTY};
+use libc::{self, winsize, c_int, pid_t, WNOHANG, WIFEXITED, WEXITSTATUS, SIGCHLD};
 
 use term::SizeInfo;
 use display::OnResize;
@@ -116,8 +116,14 @@ fn openpty(rows: u8, cols: u8) -> (c_int, c_int) {
     (master, slave)
 }
 
+#[cfg(target_os = "freebsd")]
+const TIOCSCTTY: libc::c_uint = 0x20007461;
+
 /// Really only needed on BSD, but should be fine elsewhere
 fn set_controlling_terminal(fd: c_int) {
+    #[cfg(not(target_os = "freebsd"))]
+    use libc::TIOCSCTTY;
+
     let res = unsafe {
         libc::ioctl(fd, TIOCSCTTY as _, 0)
     };
```

**Comment by jwilm** [comment] 2017-02-28 22:29
It's [actually defined](https://github.com/rust-lang/libc/blob/331b179a7ba2a44d4b3192efdf46cc2ea9db9f75/src/unix/bsd/freebsdlike/mod.rs#L709) in libc since the middle of January. Won't have time to look until later specifically why it's not working for @debdrup.

**Comment by jwilm** [comment] 2017-02-28 22:32
Oh, weird. It looks like our `libc` dependency was either never updated to 0.2.19 or later, or it was reverted at some point. In any case, we should just `cargo update -p libc` and commit that.
