### ISSUE TITLE
Arch Build Error

### ISSUE THREAD

**Issue by whereswaldon** [jwilm/alacritty#398] opened 2017-02-08 12:26 UTC
When I try to build from the AUR, I get the following compilation error. (I have run `pacman -S cmake freetype2 fontconfig pkg-config make xclip`)

[alacrittylog.txt](https://github.com/jwilm/alacritty/files/760575/alacrittylog.txt)

Is this related to #383?

**Comment by jwilm** [comment] 2017-02-10 17:25
Yep, dupe of #383

**Closed by jwilm** 2017-02-10 17:25 UTC
