### ISSUE TITLE
Pressing and holding a key only registers once (Fedora 28 with Wayland)

### ISSUE THREAD

**Issue by sevagh** [jwilm/alacritty#1565] opened 2018-09-19 10:57 UTC
### Which operating system does the issue occur on?

Fedora 28 (Linux x86_64)

### If on linux, are you using X11 or Wayland?

Wayland

### Alacritty version

```
shanssian:repos $ alacritty --version
alacritty 0.2.0
```

### Issue

It seems like holding down a key is not obeyed. In vim, when I press and hold "j" to scroll down a file continually, j is only registered once.

In gnome-terminal, pressing and holding "j" behaves as expected, scrolling down the whole way.

**Comment by sevagh** [comment] 2018-09-19 11:43
Confirmed as a Wayland problem - logging back in with X11 Gnome, everything is fine.

**Comment by jwilm** [comment] 2018-09-19 15:38
Thanks for posting! This is actually a duplicate of #1257; maybe we should update the title there to be a bit more descriptive.

**Closed by jwilm** 2018-09-19 15:38 UTC
