### ISSUE TITLE
Failure to redraw screen under rapid color cycling

### ISSUE THREAD

**Issue by dankamongmen** [jwilm/alacritty#3124] opened 2019-12-25 17:16 UTC
I'm the author of [notcurses](https://github.com/dankamongmen/notcurses). Its `notcurses-demo` binary is a demanding test of any terminal emulator. alacritty handles it very well--among the best of any emulator I've found--except for one thing. During the "uniblock" section of the demo, I'm rapidly fading in a region at the top of the screen full of Unicode. Ideally, this fades in smoothly over the course of a second (kitty shows this desired behavior). If the terminal can't quite keep up, it's more of a strobe effect (VTE shows this behavior). Alacritty tends not to show any change, despite pegging the CPU. Note that new screen draws are coming in continuously--as soon as I'm done with one render, I'm shoving another one up.

I can get you a screencap, or help you to run the demo yourself. Alternatively, I can just dig into this problem myself. I wanted to post it here because (a) it needed a log and (b) it's completely reproducible, so I thought maybe you'd want to take a spin.

### System

OS: Linux, both Debian Unstable and Arch
Version: alacritty 0.4.1-dev (4d3f6de)
Linux/BSD: X11, Compiz-Reloaded 8

### Logs

Font/Terminal size:
```
[schwarzgerat](0) $ alacritty -vv
Created log file at "/tmp/user/1000/Alacritty-3184628.log"
[2019-12-25 12:12] [INFO] Welcome to Alacritty
[2019-12-25 12:12] [INFO] Configuration loaded from "/home/dank/.config/alacritty/alacritty.yml"
[2019-12-25 12:12] [DEBUG] Estimated DPR: 1.1458333333333333
[2019-12-25 12:12] [DEBUG] Estimated Cell Size: 10 x 20
[2019-12-25 12:12] [DEBUG] Estimated Dimensions: None
[2019-12-25 12:12] [INFO] Device pixel ratio: 1.1458333333333333
[2019-12-25 12:12] [INFO] Initializing glyph cache...
[2019-12-25 12:12] [INFO] ... finished initializing glyph cache in 0.029171416s
[2019-12-25 12:12] [INFO] Cell Size: 10 x 20
[2019-12-25 12:12] [INFO] Padding: 0 x 0
[2019-12-25 12:12] [INFO] Width: 917, Height: 688
[2019-12-25 12:12] [INFO] PTY Dimensions: Line(34) x Column(91)
[2019-12-25 12:12] [INFO] Initialisation complete
[2019-12-25 12:12] [DEBUG] Term::resize dimensions unchanged
[2019-12-25 12:12] [INFO] Width: 917, Height: 688
[2019-12-25 12:12] [INFO] Goodbye
Deleted log file at "/tmp/user/1000/Alacritty-3184628.log"
[schwarzgerat](0) $
```

**Comment by kchibisov** [comment] 2019-12-25 17:23
Does it speed up if you run your thing for a while?

**Comment by dankamongmen** [comment] 2019-12-25 17:32
I do not get better results, no. Here's the behavior:

* When I swap a block (write *new* Unicode characters), I get the output
* When I'm *only changing the colors* of said characters, I get no update, and churn CPU

I'm gonna get some `perf` output in a minute here.

**Comment by kchibisov** [comment] 2019-12-25 17:36
Anyway, could you try the following diff?

```
diff --git a/font/src/ft/mod.rs b/font/src/ft/mod.rs
index 431a500..48adb29 100644
--- a/font/src/ft/mod.rs
+++ b/font/src/ft/mod.rs
@@ -319,7 +319,7 @@ impl FreeTypeRasterizer {
         if use_initial_face {
             Ok(glyph_key.font_key)
         } else {
-            let key = self.load_face_with_glyph(c).unwrap_or(glyph_key.font_key);
+            let key = glyph_key.font_key;
             Ok(key)
         }
     }

```

I'm only interesting in the performance aspect of it, it'll likely give you a wrong result, etc.

**Comment by dankamongmen** [comment] 2019-12-25 17:47
Just to confirm I applied it correctly, we see the expected warning:

```
warning: method is never used: `load_face_with_glyph`
   --> font/src/ft/mod.rs:539:5
    |
539 |     fn load_face_with_glyph(&mut self, glyph: char) -> Result<FontKey, Error> {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

...and the results are...

what appears to be substantial improvement, and gets us through about half of the blocks. At that point, we fall back tot he previous behavior. You seem to be on the right track, though!

**Comment by kchibisov** [comment] 2019-12-25 17:49
Could you provide us with steps to repro the thing and also a screen capture of what you're trying to get(idk, give us the record from kitty)? By steps I mean what should I compile, how, and what should I run.

**Comment by dankamongmen** [comment] 2019-12-25 17:52
Yep, preparing the necessary uploads as we speak :) one moment please.

**Comment by dankamongmen** [comment] 2019-12-25 17:56
Here's a screencap of the behavior with your patch. It's downsampled from 30 to 15 fps, and scaled to 2/3 the original size, to fit within github's 10MB limit.

![notcurses-uniblock-0 9 3-alacritty](https://user-images.githubusercontent.com/143473/71449174-aab4e600-2715-11ea-8d41-5e21a25d7e82.gif)

Here's the code that's doing it:

https://github.com/dankamongmen/notcurses/blob/master/src/demo/unicodeblocks.c#L97

if you'd like to run this locally, it shouldn't be hard (I'd like to know about any problems you encounter). you can either clone that repo, build, and run `notcurses-demo -p ../data`, or just download it from AUR if you're on arch (`notcurses`).

**Comment by dankamongmen** [comment] 2019-12-25 17:57
Basically, what's going on in the first few blocks of the video above ought be going on for all blocks. BTW, it is not impossible that this is my bug, but I don't see this behavior in other emulators. I've tested a fair number (https://nick-black.com/dankwiki/index.php/Notcurses#Terminal_emulators).

**Comment by kchibisov** [comment] 2019-12-25 17:59
Could you do a stupid thing for me and just move your mouse over alacritty during your app running?

**Comment by dankamongmen** [comment] 2019-12-25 17:59
Sure, one sec. Continuously back-and-forth on the area in question? I'll do it and let you know if I see anything different. If I do see a difference, I'll get a capture.

**Comment by kchibisov** [comment] 2019-12-25 18:00
I mean just move it over the window, no matter how.

**Comment by dankamongmen** [comment] 2019-12-25 18:00
No change in behavior due to pointer interaction, whether focused or otherwise.

**Comment by kchibisov** [comment] 2019-12-25 18:01
Are you sure that my patch was applied btw?

**Comment by dankamongmen** [comment] 2019-12-25 18:04
I am certain that I compiled it up (see the warning output about `load_face_with_glyph` not being used). I used `cargo deb` to build a deb and then installed that. Let me rerun directly from the build directory with an absolute path, one sec...

NOPE, i fucked up. Your patch resolves my problem at the cost of losing all my glyphs :D. My apologies for the stupidity, and thanks for making me check!

**Comment by kchibisov** [comment] 2019-12-25 18:06
Oh, so I guess it's a duplicate of #511 .

**Comment by dankamongmen** [comment] 2019-12-25 18:10
With your patch, things are looking really nice, btw. 

![notcurses-uniblock-0 9 3-alacritty-patched](https://user-images.githubusercontent.com/143473/71449311-db961a80-2717-11ea-9888-da675eb62efe.gif)

**Comment by dankamongmen** [comment] 2019-12-25 18:13
The unpatched version, you mean? The patched version is sufficiently fast for my needs. I can try with the unpatched version, but I doubt it. I go through every defined Unicode block, btw, so if you've got some cache, I might very possibly blow it out.

BTW, the talk in #511 about spending too much time in column determination...are you using something besides `wcwidth(3)` for that? Because I'm also doing a `wcwidth()` on every glyph I output -- I need to, ya know? -- and it barely registers on a profile.

**Comment by dankamongmen** [comment] 2019-12-25 18:17
Yes, the unpatched version **does** speed up if left running for long enough, nice.

**Comment by dankamongmen** [comment] 2019-12-25 18:21
looking FLY: https://nick-black.com/tabpower/alacritty-notcurses-victory.mkv

**Comment by kchibisov** [comment] 2019-12-25 18:23
The problem is in our usage of fontconfig for fallbacks, so from the issue I’ve linked the only relevant part is the title iirc. If you run alacritty on perf during your demo you should see a lot of references to libfontconfig.so.

**Comment by dankamongmen** [comment] 2019-12-25 18:24
That is indeed what I see.

**Comment by chrisduerr** [comment] 2019-12-25 23:37
Closing as a duplicate of #511, which is an issue with font fallback, width determination usually isn't an issue.

**Closed by chrisduerr** 2019-12-25 23:37 UTC
