### ISSUE TITLE
crashes on an attempt to start

### ISSUE THREAD

**Issue by exebook** [jwilm/alacritty#817] opened 2017-10-06 08:49 UTC
Which operating system does the issue occur on?
Ubuntu 16

If on linux, are you using X11 or Wayland?
X11
```

$ RUST_BACKTRACE=1 alacritty 
thread 'main' panicked at 'XOpenIM failed', /home/ya/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.6/src/platform/linux/x11/mod.rs:692:16
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:71
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:396
             at /checkout/src/libstd/panicking.rs:611
   3: std::panicking::begin_panic_new
             at /checkout/src/libstd/panicking.rs:553
   4: winit::platform::platform::x11::Window2::new
             at /home/ya/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.6/src/platform/linux/x11/mod.rs:692
   5: winit::window::<impl winit::WindowBuilder>::build
             at /home/ya/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.6/src/platform/linux/mod.rs:181
             at /home/ya/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.7.6/src/window.rs:113
   6: glutin::platform::platform::x11::Context::new
             at /home/ya/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.9.2/src/platform/linux/x11.rs:213
   7: alacritty::window::Window::new
             at /home/ya/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.9.2/src/platform/linux/mod.rs:52
   8: alacritty::display::Display::new
             at src/display.rs:141
   9: alacritty::run
             at src/main.rs:95
  10: alacritty::main
             at src/main.rs:45
  11: main
  12: __libc_start_main
  13: _start



```

**Comment by jwilm** [comment] 2017-10-13 17:10
duplicate of #830

**Closed by jwilm** 2017-10-13 17:10 UTC
