### ISSUE TITLE
Full screen mode ?

### ISSUE THREAD

**Issue by hiimdoublej** [jwilm/alacritty#1252] opened 2018-04-16 03:30 UTC
A full screen mode would suite programmers with a habit like mine,
where my terminal is always full screen and I use tmux to arrange the panes myself.
Do we have a timeline for full screen mode implementation as of now ? Thanks

**Comment by sodiumjoe** [comment] 2018-04-16 03:53
I think it depends on which platform, but for macos, it should be available in https://github.com/tomaka/winit/pull/465, after it propagates up through glutin.

**Comment by sodiumjoe** [comment] 2018-04-16 06:15
I think this is actually a dupe of #34

**Comment by chrisduerr** [comment] 2018-04-16 06:16
Closing as duplicate of #34.

**Closed by chrisduerr** 2018-04-16 06:16 UTC

**Comment by monokrome** [comment] 2020-07-27 21:28
This issue still exists. MacOS menubar doesn't work at all in alacritty w/ fullscreen @chrisduerr @sodiumjoe
