### ISSUE TITLE
(Cosmetic) Reverse-i-search with non ASCII prompt shifts characters

### ISSUE THREAD

**Issue by marcov** [jwilm/alacritty#2922] opened 2019-10-27 18:26 UTC
Which operating system does the issue occur on?
macOS Mojave

When running backward search (CTRL-R), and having a prompt ending with a non ASCII character (e.g. »), the command lines displayed are all right shifted of one blank space.

E.g.:

- type `ls`:
```
»ls
... ls output...
```
- CTRL-R and type `l`:
```
» ls
bck-i-search: ls_
```
- Enter:
```
» ls
...ls output...
```

**Comment by chrisduerr** [comment] 2019-10-27 21:04
Can you reproduce this with the default config? And do other terminal emulators behave differently?

**Comment by marcov** [comment] 2019-10-28 09:20
>Can you reproduce this with the default config? 

Yes

> And do other terminal emulators behave differently?

Yes, same prompt + Terminal.app behaves as expected.

**Comment by chrisduerr** [comment] 2019-10-29 00:48
Does the cell width of the non-ascii character in iTerm match the cell width of it in Alacritty?

**Comment by marcov** [comment] 2019-10-29 09:32
The `»`  is display as a single-cell character in both.
I am using the "MesloLGMDZ Nerd Font" in both.

**Comment by chrisduerr** [comment] 2019-10-31 19:53
Does this get fixed when you use the same `TERM` in both Terminal.app and Alacritty?

**Comment by marcov** [comment] 2019-11-01 16:36
It's already `xterm-256color` for both :-)

**Comment by marcov** [comment] 2019-11-01 16:37
Oh...now I found something interesting. This is only happening with zsh, not with bash

**Comment by marcov** [comment] 2019-11-01 16:39
Actually, it's only happening with `oh-my-zsh` on top of zsh

**Comment by chrisduerr** [comment] 2019-11-01 17:23
Have you used omz in Terminal.app too? And have you tried with `alacritty` terminfo?

**Comment by marcov** [comment] 2019-11-01 18:45
in term of setup, Termnal.app and `alacritty` are identical. Installing terminfo did not help.

**Comment by marcov** [comment] 2019-11-02 08:42
Le met do a quick recap, with some clarifications.

- while I have an identitical setup in both alacritty and Terminal.app (font, shell, ...), this is only happening in alacritty

- It happens in alacritty whenever a zsh-style completion is showed. 
  With zsh-style completion I mean having some extra text temporarily displayed below the shell prompt. 

- `^R` or `<tab>`-key executbable/file completion can both trigger this.

An example for `^R` is showed above. For `<tab>`:
```
»echo $PROMPT
```
```
»
```

```
»ls
```

»lls
ls         lsappinfo  lsbom      lskq       lsm        lsmp       lsof       lsusb      lsvfs
```
»lls
ls         lsappinfo  lsbom      lskq       lsm        lsmp       lsof       lsusb      lsvfs
```

**Comment by chrisduerr** [comment] 2019-11-02 10:54
Can you share your full prompt? It's probably not just a single `»`, right? But other stuff and colors involved?

Or can you repro it if your prompt is literally just `»`?

**Comment by marcov** [comment] 2019-11-02 11:17
> Or can you repro it if your prompt is literally just `»`?

That's it. I echoed `$PROMPT` just to show you this can reproduced **without omz** and with that PROMPT.

**Comment by zsugabubus** [comment] 2019-11-09 00:34
Could you try this?

```zsh
PROMPT='%{%G»%}'
setopt promptpercent
```

**Comment by marcov** [comment] 2019-11-09 14:01
@zsugabubus: Bingo!

In fact, just this is enough to avoid the extra spacing:
>````
> PROMPT='%{%G»%}'
> ````

> Also, can you reproduce the issue with only PROMPT=» in your .zshrc? 

Yes

> What about your locale settings?
```
~ » locale
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by marcov** [comment] 2019-11-09 14:09
Finally, just using:
```
export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8
```

makes everything work as expected. So...it seems like it was my fault in the end...
😬 🙇

**Comment by zsugabubus** [comment] 2019-11-09 14:21
@marcov, Yes, "C" locale explains lot's of things; but to make sure it _always_ works, you can still wrap every non-ASCII, single-cell-width character in `%{%G...%}`.

**Comment by chrisduerr** [comment] 2019-11-09 14:25
@marcov Does this work correctly when launching Alacritty from iTerm, but not when launching Alacritty directly?

I think this might be a duplicate of https://github.com/jwilm/alacritty/issues/2566.

**Comment by marcov** [comment] 2019-11-09 15:24
@chrisduerr: right, it is working as expected with no export / PROMPT wrapping when launching the alacritty binary from Terminal.

**Comment by zsugabubus** [comment] 2019-11-09 15:24
One more note @marcov: Setting `LC_ALL` is _not advised_ because it overrides every other locale setting _by force_, instead you could try setting `LC_CTYPE`. However, I guess `LANG=en_US.UTF-8` alone also works perfectly (unless your desktop environment thinks otherwise).

**Comment by marcov** [comment] 2019-11-09 15:26
to complement what I just said, it is working cause Terminal.app is setting on its own `LC_CTYPE="UTF-8"`

Thanks for the suggestion, I'll not set `LC_ALL` then!

**Comment by chrisduerr** [comment] 2019-11-09 15:59
If you've set the `shell` parameter in your config, make sure to request a login shell. Otherwise see #2566 for more discussion on this issue.

**Closed by chrisduerr** 2019-11-09 15:59 UTC
Labels: A - needs repro, H - macos
