### ISSUE TITLE
Panick when cat-ing a torrent file

### ISSUE THREAD

**Issue by ineol** [jwilm/alacritty#104] opened 2017-01-06 21:17 UTC
With the following torrent http://releases.ubuntu.com/16.04/ubuntu-16.04.1-desktop-amd64.iso.torrent when I do
```
cat ubuntu-16.04.1-desktop-amd64.iso.torrent
```
I get
```
[unhandled] execute byte=89
[unhandled] execute byte=04
[unhandled] execute byte=03
[unhandled] execute byte=12
[unimplemented] move_down_and_cr: 1
[unhandled] execute byte=11
[unhandled] execute byte=8c
thread 'pty reader' panicked at 'index out of bounds: the len is 24 but the index is 28', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcollections/vec.rs:1371
stack backtrace:
   1:        0x10eafdfaa - std::sys::imp::backtrace::tracing::imp::write::h1461f67be4bf68a9
   2:        0x10eb0018f - std::panicking::default_hook::{{closure}}::h6dba65b2b498d274
   3:        0x10eaffe37 - std::panicking::default_hook::ha8ecbcff1f59e805
   4:        0x10eb00656 - std::panicking::rust_panic_with_hook::h5ceed7bd7aef311a
   5:        0x10eb004a4 - std::panicking::begin_panic::h091a980eb2ddd29a
   6:        0x10eb00412 - std::panicking::begin_panic_fmt::h063a49cc71e3d103
   7:        0x10eb00377 - rust_begin_unwind
   8:        0x10eb28530 - core::panicking::panic_fmt::h59374b8a88ef3536
   9:        0x10eb284a8 - core::panicking::panic_bounds_check::h78cc4243bb390438
  10:        0x10ea5b7da - <alacritty::ansi::Performer<'a, H, W> as vte::Perform>::print::he49de47c781c0e03
  11:        0x10ea53808 - <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}::hac156881432fe821
  12:        0x10ea4162b - std::panicking::try::do_call::h2c88261f55e7a440
  13:        0x10eb0152a - __rust_maybe_catch_panic
  14:        0x10ea516ba - <F as alloc::boxed::FnBox<A>>::call_box::he707c721e5ef5370
  15:        0x10eaff864 - std::sys::imp::thread::Thread::new::thread_start::haeb202749da670ee
  16:     0x7fff8a8dd99c - _pthread_body
  17:     0x7fff8a8dd919 - _pthread_start
child finished with error '256'
```

It maybe because it's not valid UTF8?

At 8d3f5f4e179b6fe55617dc72fe60fa1bdfd9b014

Thank you!

**Comment by d3rrial** [comment] 2017-01-06 21:18
Duplicate of #88 and #94

**Comment by jwilm** [comment] 2017-01-09 00:49
Closing as dupe of #63

**Closed by jwilm** 2017-01-09 00:49 UTC
