### ISSUE TITLE
active alacritty window is opaque

### ISSUE THREAD

**Issue by jcarter777** [jwilm/alacritty#2499] opened 2019-06-02 16:00 UTC
Which operating system does the issue occur on?
FreeBSD 12.0

On FreeBSD using i3-gaps the current active alacritty window is opaque but any others are transparent as desired. using compton and X11

**Comment by chrisduerr** [comment] 2019-06-02 16:03
Duplicate of #2254.

**Closed by chrisduerr** 2019-06-02 16:03 UTC
