### ISSUE TITLE
No transparency in alacritty

### ISSUE THREAD

**Issue by cata0309** [jwilm/alacritty#2901] opened 2019-10-21 20:52 UTC
Which operating system does the issue occur on?
Solus Linux 4 Fortitude
If on linux, are you using X11 or Wayland?
X11
I am using Alacritty version 0.3.3 and I can't use the transparency option as it doesn't work at all. I have read about some issues in the past regarding the version 0.3.x family and I don't know why it was closed as they didn't solved the issue.
https://github.com/jwilm/alacritty/issues/2254

**Comment by kchibisov** [comment] 2019-10-21 20:56
Transparency is fixed on the latest master.

**Comment by chrisduerr** [comment] 2019-10-21 23:37
Closing as duplicate of https://github.com/jwilm/alacritty/issues/2254.

**Closed** 2019-10-21 23:37 UTC

**Comment by cata0309** [comment] 2019-10-22 03:05
I was about to close it myself. I built Alacritty from source and now everything is working (live reload, transparency) .
