### ISSUE TITLE
Missing default keys on OS X

### ISSUE THREAD

**Issue by JanBerktold** [jwilm/alacritty#392] opened 2017-02-05 17:17 UTC
I am using the latest version of alacrity ( 82c9235) on OS X 10.12.3 with a German keyboard.

Essential key combinations for special characters do not work.

Examples include;
@ (right alt + L)
| (left alt + 7)
\ (left alt + shift +7)

**Comment by lukaslueg** [comment] 2017-02-06 14:39
This is probably the same problem as issue #372

**Comment by JanBerktold** [comment] 2017-02-06 14:58
Might be, but shouldn't [ (LAlt + 5) work in that case? My guess is that alacritty just handles the individual key presses without any context information about what combination is supposed to represent.

I fixed it for myself by adding most of the combinations as key bindings to the configuration file, so a possible fix may be to provide default configuration files for each keyboard layout?

**Comment by jwilm** [comment] 2017-02-06 18:55
> I fixed it for myself by adding most of the combinations as key bindings to the configuration file, so a possible fix may be to provide default configuration files for each keyboard layout?

Applying the keymap is the responsibility of the OS windowing API. If our windowing abstraction isn't doing everything it should to support non-U.S. layouts, we should fix it there.

**Comment by OJFord** [comment] 2017-02-09 21:58
On British Mac layouts, LAlt+3 is `#`, which also doesn't work (Python/sh comments, switch to last buffer in vim, ... 😱) - thanks for the (temp.) workaround though @JanBerktold  🙂

**Comment by chrisduerr** [comment] 2019-10-31 20:11
Duplicate of #62, since the issue is that alt keys send special characters on macos.

**Closed by chrisduerr** 2019-10-31 20:11 UTC
Labels: B - bug, H - macos, S - input
