### ISSUE TITLE
Consider allowing alacritty to be used as an application component

### ISSUE THREAD

**Issue by gwk** [jwilm/alacritty#1272] opened 2018-04-24 17:42 UTC
Alacritty appears to be a pushing the state of the art for efficient and correct terminal functionality, and I'm optimistic about the approaches taken towards parsing and rendering. I imagine that other editors and IDEs could benefit from using alacritty as an integrated terminal.

Relatedly, I have yet to adopt Alacritty due to various issues that appear to stem from the upstream cross-platform windowing library, etc. This is not surprising; getting the the various platform details right sounds very hard. But as a Mac application developer, some of these problems strike me as sad, because the native Cocoa APIs just do the right thing for things like keyboard switching, window resize, etc. This is nothing new; details about Mac user input and windowing frequently suffer in cross-platform OpenGL libraries.

This issue is meant to explore the possibility of using alacritty as a component within another application, in one of two ways:
* as a library, in which the terminal can be initialized with an existing OpenGL context, and the existing event loop and input events will call into alacritty functions.
* as a subprocess, in which the parent communicates an IOSurface and sends events via an IPC mechanism.

Perhaps this is out of scope for the project, but given what I've read, it seems like it might align well with @jwilm's stated goal of simplicity.

The idea of an IOSurface is to let a renderer subprocess draw into a parent process window or context. This can be set up by OpenGL, Metal, Core Video, etc. This is the OS technology that enables Safari and Chrome to isolate rendering into restricted processes for security and crash resilience.

For the curious here is the reference documentation on `IOSurface`: https://developer.apple.com/documentation/iosurface. It's rather opaque, but I've looked around in the past and there is additional demo code to be found.

I have no experience with Rust, but am willing to learn. I do know Swift though, and I would happily set up a demo project with a rough draft of what the boundary would look like, for either the library or split-process approaches (or both!). If this interests the alacritty community at all, please let me know!

Lastly, this would provide a solution for supporting alacritty on iOS, as requested in #873.

**Comment by sodiumjoe** [comment] 2018-04-24 17:43
seems like a dupe of https://github.com/jwilm/alacritty/issues/450

**Comment by chrisduerr** [comment] 2018-04-24 17:45
Closing because duplicate, you can also see #1023 for a WIP version of this already.

**Closed by chrisduerr** 2018-04-24 17:45 UTC
