### ISSUE TITLE
Can't see characters on Windows 10

### ISSUE THREAD

**Issue by Tembocs** [jwilm/alacritty#1763] opened 2018-11-09 15:04 UTC
I'm on Windows 10 64 bit, build 17763.107.

Compiled Alacritty from git clone successful. When starting the all the font characters appear as white boxes though the commands seem to work. I tried an executable from official Alacritty GitHub release page and got the same problem. I'm not sure how to solve this.

![Direct executables](https://user-images.githubusercontent.com/28905212/50338844-912efc00-050d-11e9-89a8-dec1e9083915.png)

**Comment by chrisduerr** [comment] 2018-11-09 16:40
Have you tried changing the default font in the configuration file?

**Comment by Tembocs** [comment] 2018-11-10 04:41
> 
> 
> Have you tried changing the default font in the configuration file?

Yes, I changed to "Courier New" and "Ubuntu Mono" (I installed on Windows) and had the same issue.

**Comment by chrisduerr** [comment] 2018-11-10 12:51
Oh wait, when you said 'white boxes' I was thinking about the missing glyph placeholder icons. However I think you're talking about something else. Are these 'white boxes' filled and have varying height and width?

If that's the case this is not a font, but an OpenGL issue.

**Comment by Tembocs** [comment] 2018-11-12 15:49
> 
> 
> Oh wait, when you said 'white boxes' I was thinking about the missing glyph placeholder icons. However I think you're talking about something else. Are these 'white boxes' filled and have varying height and width?
> 
> If that's the case this is not a font, but an OpenGL issue. Which GPU do you have?

Exactly, the 'white boxes' are filled and have varying heights and width.

**Comment by chrisduerr** [comment] 2018-12-21 11:55
Seems like there are at least three people experiencing this issue now. My assumption would be that it's a shader issue, so it might be useful to check the shader version.

If you could share the version of OpenGL and GLSL your GPUs support, that might give some insights.

So far I believe all of you are running Intel HD Graphics. Would be interesting to see if everyone running this has the same or a similar iGPU.

**Comment by chrisduerr** [comment] 2018-12-21 12:05
Note that according to Intel, the HD 3000 graphics support only version 3.1 of OpenGL on Windows, while supporting 3.3 on Linux (see [wiki](https://en.wikipedia.org/wiki/Intel_HD_Graphics#Capabilities)).

Now if we look up the GLSL versions which are supported by OpenGL 3.1, we'll notice that only GLSL 1.40.08 is supported and that OpenGL 3.3 is required for GLSL 3.3+ (see [wiki](https://en.wikipedia.org/wiki/OpenGL_Shading_Language#Versions)).

Now if we look at the other issues, there have been issues with GLSL < 3.3 before. So this is probably a duplicate of #128.

If anyone here is running into this issue with a GPU that supports OpenGL/GLSL 3.3+, please let me know and I'll re-open.

**Closed by chrisduerr** 2018-12-21 12:05 UTC
Labels: H - windows, S - render

**Comment by chrisduerr** [comment] 2018-12-21 12:46
Intel HD 2000 is the same as Intel HD 3000, where there's support for it on Linux, but not on Windows (see the links I've attached).

So so far it looks like my guess here might be correct.

Note that 2000/3000 graphics were released in 2011, which is definitely not something modern, but it would still be good to support it. That's why #128 is still open, it would definitely be appreciated, but there's probably not much drive behind it because a lot of people don't use these CPUs anymore. So if anyone's familiar with OpenGL who can test this, it would always be much appreciated!

There's one idea I do have though which you could test @derpmarine168. In the shader files located in the `res` directory, the shader version is defined as `330`. Try replacing that `330` with `150` without changing anything else and see if that makes it work.

**Comment by derpmarine168** [comment] 2018-12-21 12:47
where is this directory (I installed with scoop)?

**Comment by chrisduerr** [comment] 2018-12-21 12:57
@derpmarine168 Yeah, you'll have to compile it yourself to test this. It would be much appreciated though if someone could try to verify if that works.

**Comment by derpmarine168** [comment] 2018-12-21 13:00
No problem - already have Rust installed. <https://github.com/jwilm/alacritty/wiki/Manual-Installation>

**Comment by chrisduerr** [comment] 2018-12-21 13:39
Thanks for testing @derpmarine168. Looks like the problem is not just the version specification, but there actually are some OpenGL 3.3 features we depend on.

Progress on that front should be tracked in the issue I've linked though.
