### ISSUE TITLE
Can't select text starting near edges of the screen

### ISSUE THREAD

**Issue by smallgreyrock** [jwilm/alacritty#2650] opened 2019-07-16 17:54 UTC
OSX 10.14.5, Alacritty 0.3.3

I am unable to select text near the window edges. On the side edges, with the mouse over the first text character, the pointer switches to the window resize operation. In the corners, it's two characters.

<img width="573" alt="oops" src="https://user-images.githubusercontent.com/43232939/61317501-9ed20900-a7f2-11e9-8f38-c1a083fa6b1c.png">

**Comment by chrisduerr** [comment] 2019-07-16 22:08
This is a duplicate of https://github.com/jwilm/alacritty/issues/1671.

Unfortunately it's due to macOS requiring some are to drag the window, even with disabled decorations. So you cannot select text near the edges, since macOS reserves it as dragging space.

**Closed by chrisduerr** 2019-07-16 22:08 UTC
