### ISSUE TITLE
Not properly working on Ubuntu 18.04

### ISSUE THREAD

**Issue by Woolworths** [jwilm/alacritty#1341] opened 2018-05-31 08:21 UTC
Which operating system does the issue occur on?
Ubuntu 18.04
If on linux, are you using X11 or Wayland?
x11  
Fresh install of Ubuntu 18.04 on the newest version of Virtual Box running off my Windows 10 machine. I installed rust through rustup and followed the install process for alacritty. When running the command `alacritty`, I get an error: 
> name@hduiw10:~$ alacritty 
[winit X11 error] XError {
    description: "BadValue (integer parameter out of range for operation)",
    error_code: 2,
    request_code: 12,
    minor_code: 0
}  

Alacritty launches but with significant scaling issues:
![github_issue](https://user-images.githubusercontent.com/6524227/40770904-4aa37d3c-64ff-11e8-9488-3392a760ae06.png)
(screenshot taken with gnome-screenshot -wB & help was run in alacritty 3 times. Also note that when I run help, the output was printed side by side twice each time)  
No errors were present in installing anything. Let me know if you want any logs.

**Comment by chrisduerr** [comment] 2018-05-31 12:36
Looking at the `[winit X11 error]` message this seems to come from winit. If you clone to https://github.com/tomaka/winit and run `cargo run --example window` do you get the same error?

**Comment by Tristan971** [comment] 2018-05-31 14:01
Same here on Archlinux.
Output of alacritty-v is :
```
Welcome to Alacritty.
Configuration loaded from /home/tristan/.config/alacritty/alacritty.yml
device_pixel_ratio: inf
width: 1024, height: 768
Initializing glyph cache
Finished initializing glyph cache in 0.03183738
width: 84, height: 76
Cell Size: (1 x 3)
[winit X11 error] XError {
    description: "BadValue (integer parameter out of range for operation)",
    error_code: 2,
    request_code: 12,
    minor_code: 0
}
PTY Dimensions: Line(24) x Column(80)
thread 'main' panicked at 'Failed to lookup raw keysym: XError { description: "BadValue (integer parameter out of range for operation)", error_code: 2, request_code: 12, minor_code: 0 }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Obviously the issue is `device_pixel_ratio: inf`... Worked before updating it to last version on AUR

**Comment by chrisduerr** [comment] 2018-05-31 14:13
Tagging @francesca64 the winit guru. It seems like this is a problem for winit? Might be a good idea to just open an issue with winit if that's true and then link it here.

If I understand @Tristan971 correctly he did test the winit examples and they were broken too, so that seems like the right approach to take. Alacritty recently just made a pretty big jump in winit versions I think, so this is probably a result of that.

**Comment by francesca64** [comment] 2018-05-31 16:03
Request code 12 = [`XConfigureWindow`](https://cgit.freedesktop.org/xorg/proto/xproto/tree/Xproto.h#n2033). Since the DPR is infinite, and the window size Alacritty requests is presumably a function of that, X11 is asked to resize the window to something ridiculous, hence the ¨integer parameter out of range for operation¨. This is why I added that simplistic error logging, since as you can see, the line printed by `expect` is quite misleading; in future versions of winit I hope to automatically translate the request code to the relevant request name.

My understanding is that `device_pixel_ratio` is a function of winit's `Window::hidpi_factor`, and that Alacritty resizes the window immediately after creation in response to this info. What math goes into `device_pixel_ratio`? Either way, this is likely some issue with how winit calculates DPI wrt XRandR's supplied data. @Tristan971 what's the output of `xrandr --listmonitors --verbose`? You could also tell me the output of this little winit program:

```rust
extern crate winit;

fn main() {
    let event_loop = winit::EventsLoop::new();
    for monitor in event_loop.get_available_monitors() {
        println!("{:#?}", monitor);
    }
}
```

The info about the winit examples isn't relevant. On X11, creating a window without drawing to it just populates it with a copy of whatever's behind it at the time of creation (Windows fills it with white, but any areas exposed by resizing are black, and on macOS it's transparent... this was just some fun trivia). Besides that, the window examples just create windows of some default 800x600 physical size, so this couldn't happen there.

**Comment by chrisduerr** [comment] 2018-05-31 16:16
The `device_pixel_ratio` is exactly the return value of `window.hidpi_factor()` as far as I know.

https://github.com/jwilm/alacritty/blob/765949f256aefcc513d0bfb46b64d315f9c2f3d2/src/display.rs#L218-L219

Since the value is `inf`, I'd assume this has to do with division by 0? Since `hidpi_factor` returns a floating point value it should be `+inf` whenever the numerator is positive and the denominator is 0.0. I'm not quite sure how it's calculated internally in winit though, it seems like this is the correct place where it's calculated for X11:

https://github.com/tomaka/winit/blob/30f798b24608aaee9b727f40fb051ad66f445920/src/platform/linux/x11/monitor.rs#L69

This makes it look like it's not actually calculated in winit itself but just retrieved from the X.Org connection. Which would lead me to believe that X.Org is reporting this pixel ratio directly as infinity? I'm not entirely sure if any of this is correct, but that's what I'm getting out of this.

**Comment by francesca64** [comment] 2018-05-31 16:22
The math (along with `get_output_info`'s implementation) is right here: https://github.com/tomaka/winit/blob/30f798b24608aaee9b727f40fb051ad66f445920/src/platform/linux/x11/util/randr.rs#L52.

All `xconn` methods are defined in winit (99% of them are in `util`).

**Comment by chrisduerr** [comment] 2018-05-31 16:29
Oh okay, this would lead me to believe that either `width_mm` or  `height_mm` is reported as 0.

**Comment by francesca64** [comment] 2018-05-31 16:45
Googling "xrandr 0mm x 0mm" reveals that this can happen. This also might be relevant, though I haven't dug into it much: http://xpra.org/trac/ticket/728

Anyway, the ultimate solution here is likely to just add this to the beginning of `calc_dpi_factor`:
```rust
if width_mm == 0 || height_mm == 0 {
    return 1.0;
}
```

There's not really anything else we can do, though once logging is added it would be good to emit a warning here.

**Comment by chrisduerr** [comment] 2018-05-31 16:49
Agree with that, fine with me opening a PR to add it? Even though it might be nice to get some confirmation from @Woolworths or @Tristan971 that this is actually the issue.

If anyone of you would be ready to test a PR, please let me know and I'll ping you once I've got something working.

**Comment by francesca64** [comment] 2018-05-31 16:57
Yeah, go ahead. You'll be the first person to have any blame in the `util` module other than me.

**Comment by chrisduerr** [comment] 2018-05-31 17:02
I'm not sure if I'll be able to deal with that responsibility. :D

**Comment by chrisduerr** [comment] 2018-05-31 17:19
@Woolworths @Tristan971 This branch might fix the issue:
https://github.com/chrisduerr/alacritty/tree/winit-xorg-bugfix

Please let me know if it works for you, if it does I'll open the PR upstream with winit.

**Comment by Tristan971** [comment] 2018-05-31 20:50
Hello @chrisduerr this happens on work computer so I'll be checking that tomorrow !
Thanks for the prompt answers in any case :-) 👍

**Comment by Tristan971** [comment] 2018-06-01 10:21
Works perfectly!
alacritty -v output is as follows (so, as you expected it was indeed a div by 0 issue) : 
```
$ ./alacritty -v
Welcome to Alacritty.
Configuration loaded from /home/tristan/.config/alacritty/alacritty.yml
device_pixel_ratio: 1
width: 1024, height: 768
Initializing glyph cache
Finished initializing glyph cache in 0.029181926
width: 1124, height: 748
Cell Size: (14 x 31)
PTY Dimensions: Line(24) x Column(80)
```

**Comment by chrisduerr** [comment] 2018-06-01 12:09
Glad to hear my guess was right, thanks for the quick feedback! I've filed a PR upstream (#544) which fixes that, so once it's published on crates.io we should be able to update the dependencies and close this issue.

**Comment by Woolworths** [comment] 2018-06-04 02:10
@chrisduerr This seemed to have worked, thanks!

**Comment by NellyWhadsDev** [comment] 2018-06-15 20:11
Would someone (perhaps @chrisduerr or @Woolworths) mind condensing the steps required to apply this fix into a quick guide here? It seems there is a working fix from the conversation above, I'm just unsure of what exactly to do.

Thanks!

**Closed** 2018-06-17 09:19 UTC
Labels: S - winit
