### ISSUE TITLE
Windows: Focus with mouse highlights text

### ISSUE THREAD

**Issue by celynwalters** [jwilm/alacritty#2170] opened 2019-03-11 22:19 UTC
Operating System: Windows
Pretty sure this doesn't happen in Linux.

### Behavior summary
When focusing the window with a mouse click, all characters are highlighted up until the character clicked on.

### Expectation
The window is simply focused, no extra selection occurs.

### Extra
This is especially irritating in combination with #2050.
(`selection: save_to_clipboard: false` doesn't seem to work, resulting in pasting half the terminal screen back into the prompt)

**Comment by chrisduerr** [comment] 2019-03-12 20:05
This issue was already raised for macOS [here](https://github.com/jwilm/alacritty/issues/1291) where it was initially implemented for all platforms.

The behavior was then reverted for Linux/BSD because it's not expected there in [this PR](https://github.com/jwilm/alacritty/pull/1540).

This was all before Windows support was added, so it made sense back then to just check if the platform is not macOS. It seems like all that is needed here, would be to add another check to make sure that this behavior is also present on Windows to match macOS.

I've created a PR to fix this issue, I'd appreciate help with testing: https://github.com/jwilm/alacritty/pull/2172

**Comment by celynwalters** [comment] 2019-03-13 00:53
I built from this PR (with the build fix) and I'm still getting the same behaviour.
Just to verify, I built this with `cargo build --release`. Is this correct?
(Not sure if you can/how to download binaries build by TravisCI?)

**Comment by chrisduerr** [comment] 2019-03-13 11:00
You can not download binaries build by travis. However you do build using `cargo build`, the release is optional in this case.

Please make sure you have the right branch selected. Please let me know if you can't make it work and I'll have to test myself.

**Comment by cole-h** [comment] 2019-03-13 23:23
I can confirm the issue is not yet fixed.
![2019-03-13_16-20-12](https://user-images.githubusercontent.com/28582702/54320921-ff82d800-45ab-11e9-9c53-fb9d11c0d91f.gif)

**Comment by chrisduerr** [comment] 2019-03-17 21:48
I've just tested this on my Windows test system and can not reproduce it.

Could someone confirm that this issue still exists when running powershell in both ConPTY and WinPTY?

**Comment by cole-h** [comment] 2019-03-17 22:13
How would I do that? If it's just toggling "Use legacy console" in Powershell: nothing changed, unfortunately. I also tried toggling every possible setting in options, but there was no change.

Running it from `cmd` and doing the same things exhibits the same behavior. Windows 10 Version 1803 (OS Build 17134.648) -- from `winver`, if it helps.

**Comment by chrisduerr** [comment] 2019-03-17 22:58
Your Windows 10 version seems extremely outdated (about 1 year?). Could you try updating to see if that fixes the problem?

**Comment by celynwalters** [comment] 2019-03-17 23:23
I'm on version 1809, build 17763.379.
Unfortunately still the same with both Winpty and Conpty (didn't know this was a thing).
I'm definitely running the correct build, I checked that the PR changed lines exist in my source, and changed the window title to be sure it's a fresh build.

**Comment by chrisduerr** [comment] 2019-03-17 23:34
ConPTY does not exist until version 1810. Please make sure you're using the latest version of Windows to ensure that this is not caused by some issues with the outdated WinPTY.

**Comment by cole-h** [comment] 2019-03-18 00:59
Thanks for the tip on 1809. Dunno why I never got it. However, issue is the same and I can't find any mention of an 1810 update. I assume your system is part of the Insider program, then?

**Comment by BartXZX** [comment] 2019-03-18 11:59
I believe 1809 is actually the latest.
I am experiencing this issue as well, however I am on an older windows version 1803 build 17134.523 as this is my work laptop. Tonight I would be able to test this at home on my own PC.

**Comment by chrisduerr** [comment] 2019-03-18 16:12
> Thanks for the tip on 1809. Dunno why I never got it. However, issue is the same and I can't find any mention of an 1810 update. I assume your system is part of the Insider program, then?

That was my mistake actually, sorry. Since this was the October update, I thought the version number would be 1810 (2018.10).

If that version is present (1809), then the ConPTY option will work and is available.

Could the people who are able to reproduce share a bit more information about how to reproduce this? I feel like this would be a pretty simple bug to fix, but unfortunately I can not reproduce it. It would be interesting to get some information about the system, is this reproducible with both mouse and touchpad? Does it matter which other application is open?

Since it might not be trivial for me to fix it, this would probably be a great issue for someone interested in trying to contribute to Alacritty. I can help with getting started if someone is willing to dive in.

**Comment by chrisduerr** [comment] 2019-03-18 20:44
Turns out I've managed to reproduce it. The issue is that the `Focused` event comes *after* the `MouseInput` event, so when clicking the window it will always be focused.

**Comment by BartXZX** [comment] 2019-03-18 20:57
Well that would explain it. I tried some different commits. Issue was introduced in [104b866cb6fa1b0674abdd2bdd3668f280939ca8](https://github.com/jwilm/alacritty/commit/104b866cb6fa1b0674abdd2bdd3668f280939ca8) I think.

**Comment by chrisduerr** [comment] 2019-03-18 22:00
Turns out a straight-forward and simple fix for this issue is currently not possible with the window library Alacritty is using.

I've opened a bug upstream to discuss this issue and possible solutions for it:
https://github.com/tomaka/winit/issues/817

**Comment by chrisduerr** [comment] 2019-03-20 21:05
Thanks to Osspial, this just got fixed upstream.

Can anyone recompile Alacritty against the latest winit git version to confirm this works?

The easiest way to test that is probably to put the following in Alacritty's Cargo.toml:
```toml
[dependencies.winit]
git = 'https://github.com/tomaka/winit'
```

**Comment by cole-h** [comment] 2019-03-20 22:38
Confirmed fixed! Woohoo! 🎉

**Comment by BartXZX** [comment] 2019-03-20 22:43
Yep, it also works on my macine!

**Comment by chrisduerr** [comment] 2019-03-20 22:44
Nice, going to close this once a new version is released. Thanks for testing and thanks to Osspial for testing.

**Comment by celynwalters** [comment] 2019-03-20 23:01
Fixed for me as well! Feel free to close whenever.

**Closed** 2019-04-04 23:11 UTC
Labels: A - deps, B - bug, H - windows, S - winit/glutin
