### ISSUE TITLE
Scrolling is 50% slower than rxvt / urxvt

### ISSUE THREAD

**Issue by xeyownt** [jwilm/alacritty#885] opened 2017-11-02 10:49 UTC
Which operating system does the issue occur on?

Ubuntu 16.04

If on linux, are you using X11 or Wayland?

X11 (I guess?)

glxinfo?

```
glxinfo | grep OpenGL
# OpenGL vendor string: Intel Open Source Technology Center
# OpenGL renderer string: Mesa DRI Intel(R) Haswell Mobile 
# OpenGL core profile version string: 4.3 (Core Profile) Mesa 17.0.7
# OpenGL core profile shading language version string: 4.30
# OpenGL core profile context flags: (none)
# OpenGL core profile profile mask: core profile
# OpenGL core profile extensions:
# OpenGL version string: 3.0 Mesa 17.0.7
# OpenGL shading language version string: 1.30
# OpenGL context flags: (none)
# OpenGL extensions:
# OpenGL ES profile version string: OpenGL ES 3.1 Mesa 17.0.7
# OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
# OpenGL ES profile extensions:
```

I run the following benchmark:

```
yes | dd count=10k > yes.txt
time cat yes.txt
```

I collect the following times (real):
```
rxvt            0.815s 0.878s 0.781s 0.854s 0.785s avg 0.823s
urxvt           0.849s 0.882s 0.864s 0.838s 0.978s avg 0.882s
alacritty       1.297s 1.273s 1.228s 1.495s 1.207s avg 1.300s
terminator      2.057s 2.012s 1.998s 1.948s 2.017s avg 2.006s
```

So alacritty is roughly 50% slower than urvxt, and 60% slower than rxvt.

Note that the slow down is only in this specific benchmark, which is intensive on scrolling up

**Comment by jwilm** [comment] 2017-11-02 15:11
Able to repro

    alacritty cat yes.txt  0.00s user 0.68s system 97% cpu 0.704 total
    urxvt cat yes.txt  0.00s user 0.50s system 98% cpu 0.503 total

I suspect this will be fixed when we switch to using a VecDeque for line storage.

**Comment by jwilm** [comment] 2017-11-02 15:34
The [vec-deque-backing](https://github.com/jwilm/alacritty/tree/vec-deque-backing) branch shows performance numbers similar to urxvt on my system. Seems to be random based on system load which terminal wins this benchmark when using that branch. Fancy trying it out yourself?

**Comment by xeyownt** [comment] 2017-11-02 21:57
I tested the new branch on two laptops, one with intel card, one with nvidia quadro.
I tested alacritty, alacritty + vec-deque-backing and urxvt on both laptops.

For the test case, I basically run the "yes" test an hundred times.
```
F=alacritty-intel.txt
N=100; n=0; rm $F
yes | dd count=10k > yes.txt
while (( n < N )) ; do 
    /usr/bin/time -ao $F -f '%E' cat yes.txt; ((n++))
done
sed -ri 's/^[0:]+// $F
```

I collected stats in 6 files (`alacritty-deq-intel.txt`, `alacritty-deq-nvidia.txt`, `alacritty-intel.txt`, `alacritty-nvidia.txt`, `urxvt-intel.txt`, `urxvt-nvidia.txt`).

The results:
``` bash
awk 'BEGINFILE {sum=sq=n=0} {sum=sum+$1; sq=sq+$1*$1; n++} ENDFILE {printf "%-25s - %-10s: %f\n", FILENAME, "mean", sum/n; printf "%-25s - %-10s: %f\n", FILENAME, "std dev", sqrt((sq-sum*sum/n)/(n-1))}' *.txt
# (sorted from fastest to slowest)
# urxvt-intel.txt           - mean      : 0.871500
# urxvt-intel.txt           - std dev   : 0.108175

# alacritty-deq-intel.txt   - mean      : 0.907900
# alacritty-deq-intel.txt   - std dev   : 0.189392

# urxvt-nvidia.txt          - mean      : 1.347400
# urxvt-nvidia.txt          - std dev   : 0.072567

# alacritty-deq-nvidia.txt  - mean      : 1.475200
# alacritty-deq-nvidia.txt  - std dev   : 0.049061

# alacritty-intel.txt       - mean      : 1.658000
# alacritty-intel.txt       - std dev   : 0.175833

# alacritty-nvidia.txt      - mean      : 2.226200
# alacritty-nvidia.txt      - std dev   : 0.069874
```

To summarize, the vec-deque-backing is a significant improvement, gives almost identical results on intel but strangely not yet to par with urxvt on nvidia (10%). Not sure however it is worth the trouble to catch these last %, except for the fame of course ;-) . Note that on my nvidia laptop, alacritty cats a 10MB file in 0.56s, std dev 0.04, whereas urxvt takes 0.75s, std dev 0.04, so alacritty is 35% faster in the usual use case.

On Intel, alacritty shows quite some high std deviation. This is even more obvious in the gnuplot:

``` bash
gnuplot -p -e 'set yrange [0:2.5]; set key right bottom; plot "alacritty-deq-intel.txt" with lines lt rgb "blue", "alacritty-intel.txt" with lines lt rgb "dark-blue", "urxvt-intel.txt" with lines lt rgb "orange", "alacritty-deq-nvidia.txt" with lines lt rgb "blue" dashtype 2, "alacritty-nvidia.txt" with lines lt rgb "dark-blue" dashtype 2, "urxvt-nvidia.txt" with lines lt rgb "orange" dashtype 2'
```

![image](https://user-images.githubusercontent.com/16546024/32349138-65591198-c016-11e7-947d-93647d76d013.png)

**Comment by nixpulvis** [comment] 2017-11-02 23:44
@xeyownt just a small nit-pick, but I'm having trouble with the colors in the graph a little.

**Comment by jwilm** [comment] 2017-11-02 23:48
Thank you @xeyownt for the thorough analysis! I've got a few more tricks that we can use to maybe squeeze out those last few % and fix the large σ on intel. Will follow up again when I've got more to share.

**Comment by sadid** [comment] 2018-06-01 08:12
I use another command `time ls -lR /proc` and also add gnome-terminal to the test. I can confirm the same on par performance. Urxvt is just a bit faster. Also `optirun alacrity` (NVIDIA 960M) is slower than `alacrity` on Intel. I do mulitple consequtive run test. Each 5 times and here is the results:

| TE                    | user mean/std   | system          | cpu (total)     |
|-----------------------|-----------------|-----------------|-----------------|
| **urxvt**             | $6.74 \pm 0.08$ | $5.47 \pm 0.15$ | $6.42 \pm 0.08$ |
| **alacritty**         | $6.76 \pm 0.09$ | $5.62 \pm 0.12$ | $6.20 \pm 0.07$ |
| **gnome-terminal**    | $6.89 \pm 0.03$ | $5.58 \pm 0.07$ | $7.89 \pm 0.08$ |
| **optirun alacritty** | $6.97 \pm 0.16$ | $5.88 \pm 0.10$ | $8.88 \pm 0.21$ |


here is `glxinfo | ag "OpenGL"`:

```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2) 
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.0.4
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.0.4
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 18.0.4
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

`optirun glxinfo | ag "OpenGL"`:

```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 960M/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 396.24
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6.0 NVIDIA 396.24
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
```

**Closed** 2018-09-17 15:15 UTC
Labels: B - bug, performance
