### ISSUE TITLE
Multi-line texts aren't copied to PRIMARY on selection

### ISSUE THREAD

**Issue by vtdmhd** [jwilm/alacritty#2189] opened 2019-03-19 08:55 UTC
On Archlinux (kernel 5.0.2, X11), selecting text in a single line correctly copies it to PRIMARY, allowing pasting it by middle-click. However, if the selection spans multiple lines, the line isn't copied.
Copying to clipboard works fine.

**Comment by nixpulvis** [comment] 2019-03-19 14:37
On my Arch Linux system I don't have this issue. What version of alacritty are you running? Can you verify this on master?

**Comment by ksunden** [comment] 2019-03-26 04:40
I have found that if it is selected from the bottom up it does not get copied, but if selected from the top down, it seems to be copied properly (at least, that's my leading theory after a little bit of testing)

**Comment by Thhethssmuz** [comment] 2019-03-30 19:07
I have noticed inconsistencies as well. Same setup Arch Linux, kernel 5.0.2 and X11. Although I believe I have found a consistent way of reproducing the issue:

If I click mouse to select, drag, and then release the mouse inside the alacritty window the selection is copied to the selection board as expected. However, if I release the mouse outside of the alacritty window then selection is not copied to the selection board.

**Comment by ksunden** [comment] 2019-03-30 20:08
Yes, this seems to agree with my observations (also makes sense why I thought it was directional, As I am more likely to stray outside selecting bottom up than top down)

**Comment by chrisduerr** [comment] 2019-03-31 14:19
I've gotten reports that this has been fixed on the latest master. Can anyone confirm this?

**Comment by Thhethssmuz** [comment] 2019-03-31 15:29
Tried the 0.3.0 release candidate, and the issue is gone for me at least...

**Comment by chrisduerr** [comment] 2019-03-31 15:49
Closing the issue as resolved. If you should still encounter it @vtdmhd, please let me know.

**Closed by chrisduerr** 2019-03-31 15:49 UTC
Labels: A - needs repro, DS - X11, H - linux

**Comment by vtdmhd** [comment] 2019-03-31 15:55
I've just tried alacritty-git (as of commit cfd025b5), the issue seems to be resolved.

Thanks for your work.
