### ISSUE TITLE
Black screen when switching from virtual console

### ISSUE THREAD

**Issue by aeosynth** [jwilm/alacritty#708] opened 2017-08-02 19:32 UTC
Switch to virtual console (Ctrl+Alt+F1), switch back to X (Ctrl+Alt+F7), alacritty shows a black screen until its window is clicked. Using Void Linux, bspwm, alacritty 20170624.

**Comment by dylnmc** [comment] 2017-08-04 16:10
not something I can reproduce on arch in bspwm or gnome

**Comment by chrisduerr** [comment] 2018-05-19 00:04
Closing as duplicate of #602.

**Closed by chrisduerr** 2018-05-19 00:04 UTC
