### ISSUE TITLE
color support (probably conpty)?

### ISSUE THREAD

**Issue by musm** [jwilm/alacritty#2240] opened 2019-04-01 22:27 UTC
I can get 24-bit color using cmd.exe, yet alacritty fails to render the colors.

I suspect it's not handling conpty or VT term sequences correctly.

**Comment by chrisduerr** [comment] 2019-04-02 23:06
This is a duplicate of https://github.com/jwilm/alacritty/issues/1792.

**Closed by chrisduerr** 2019-04-02 23:06 UTC
