### ISSUE TITLE
MacOS - 'zsh: character not in range'

### ISSUE THREAD

**Issue by Timoses** [jwilm/alacritty#2848] opened 2019-10-04 12:25 UTC
Which operating system does the issue occur on? MacOS Mojave 10.14.6

If I open Terminal and
```
printf '\u2388'
⎈           
```

In Alacritty I get:
```
printf '\u2388'
zsh: character not in range
```

Not sure what the source of this is.

**Comment by kchibisov** [comment] 2019-10-04 12:29
What's your output of `locale`?

**Comment by Timoses** [comment] 2019-10-04 12:32
Terminal:
```
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

Alacritty:
```
LANG=
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```


Looks suspicious ..

**Comment by kchibisov** [comment] 2019-10-04 12:39
Would you mind trying to put `LC_CTYPE: "UTF-8"` in alacritty.yml `env` section?

**Comment by Timoses** [comment] 2019-10-04 12:48
That does the trick. Thanks!

**Comment by kchibisov** [comment] 2019-10-04 12:50
duplicate of #2566

**Closed** 2019-10-04 13:03 UTC
