### ISSUE TITLE
Alt-Space gets eaten on Windows

### ISSUE THREAD

**Issue by anaisbetts** [jwilm/alacritty#1774] opened 2018-11-12 06:01 UTC
On Windows, Alt-Space should always open the System menu for a window (i.e. the context menu attached to the window's icon in the very top-left corner). Alacritty is eating this gesture, and because I'm an Old, I can't use `Alt-Space, n` to minimize the window like I can for other windows

**Comment by kumarharsh** [comment] 2019-02-13 06:32
Yup, came here to report this too. Additionally, alacritty *always* opens in a window whose height causes it to run for the full height of the screen - which causes it to hide beneath the taskbar, so last 2-3 lines are always hidden.

**Comment by chrisduerr** [comment] 2019-02-13 19:21
Does this work with the `alt_send_esc` setting set to `true`?

Generally when pressing alt and any other key, an escape sequence must be sent to the shell. That's just one of the quirks of terminals which might conflict with some operating systems which aren't used to terminal emulator use.

The `alt_send_esc` command is setup specifically so users could intentionally break this behavior to work around things. Because of that it should hopefully fix this problem too, unless this feature is not automatic but needs to be enabled explicitly.

**Comment by kumarharsh** [comment] 2019-02-20 07:08
Yes, `alt_send_esc` is set to true on Windows, but nothing happens. Specifically, this app menu doesn't open on pressing alt+space.

![image](https://user-images.githubusercontent.com/760112/53072866-66145900-350c-11e9-9242-a8d20a72e10f.png)

**Comment by chris-morgan** [comment] 2019-04-15 03:41
The value of `alt_send_esc` seems to be irrelevant here: you can’t open the system menu whether it’s true or false. I would imagine that the underlying cause here is the same as #1939, which is more general.

<kbd>Alt</kbd> just isn’t working on Windows at all. If it’s pressed, the entire key combo is lost.

**Comment by chrisduerr** [comment] 2019-11-17 00:16
Closing as duplicate of #1939.

**Closed by chrisduerr** 2019-11-17 00:16 UTC
Labels: H - windows

**Comment by sshock** [comment] 2022-07-17 02:28
This is still broken.  Alt-space does not open the System menu on Windows like it should, and I can't find any way to make it work.

I am able to map alt-space to any supported action, but there is no `ShowSystemMenu` action, so I am unable to fix this with a key_binding.

I know this was marked as a duplicate of https://github.com/alacritty/alacritty/issues/1939 and that was marked fixed a while ago, and I'm sure some important things were fixed there related to keys being eaten, but alt-space still doesn't bring up the system menu.

**Comment by sshock** [comment] 2022-07-23 06:22
I'm working around this problem for now using AutoHotkey with the following script.  Unfortunately, I couldn't get it working to show the actual system menu with like DllCall("GetSystemMenu") and DllCall("TrackPopupMenu"), but it's working with this custom menu:

```
Menu, MySysMenu, Add, &Restore, DoWinRestore
Menu, MySysMenu, Add, Mi&nimize, DoWinMinimize
Menu, MySysMenu, Add, Ma&ximize, DoWinMaximize
Menu, MySysMenu, Add ; separator line.
Menu, MySysMenu, Add, &Close, DoWinClose
Menu, MySysMenu, Default, &Close
return

DoWinRestore:
WinRestore, A
return

DoWinMinimize:
WinMinimize, A
return

DoWinMaximize:
WinMaximize, A
return

DoWinClose:
WinClose, A
return

#IfWinActive ahk_exe alacritty.exe
!Space::
Menu, MySysMenu, Show
return
```

**Comment by sshock** [comment] 2022-08-01 01:35
I've created this upstream issue, since I was able to reproduce the problem there:
* https://github.com/rust-windowing/winit/issues/2406
