### ISSUE TITLE
Add vtebench benchmarks in CI

### ISSUE THREAD

**Issue by zacps** [jwilm/alacritty#1625] opened 2018-10-05 06:01 UTC
A cool idea I thought of because of not being able to reproduce a performance problem #1374 is to run vtebench benchmarks in travis CI. I found [this article](https://sunjay.ca/2017/04/27/rust-benchmark-comparison-travis) which discusses a setup for this.

We could even include the renderer in this by using something like [xvfb on travis](https://docs.travis-ci.com/user/gui-and-headless-browsers/).

**Comment by chrisduerr** [comment] 2018-10-05 07:18
This is a duplicate of #221.

If you look at the last comment in that issue, you'll also see that I've already investigated using xvfb on travis, but unfortunately this is not likely to be a solution for Alacritty.

To accurately measure performance regressions, it is required that we're not bottlenecked by rendering. However using xvfb on travis, it was impossible to notice any performance regressions or improvements because the renderer was so slow.

I think the best way forward would be to perform headless benchmarks on travis. I've planned to look into this and see just how accurately they'll be able to test performance, but I haven't gotten around to it yet.

Note that I've already setup a website which graphs every benchmark's result and runs it automatically by hooking into the travis build process through their API. So the problem isn't automating the benchmarks, but rather finding a good way to benchmark Alacrity in a headless environment.

**Closed by chrisduerr** 2018-10-05 07:18 UTC

**Comment by chrisduerr** [comment] 2018-10-05 08:15
It's public at https://perf.christianduerr.com/. I've stopped running it after I ran into the issues though. But it should showcase just how much variations in the different PRs there was. Usually Alacritty and vtebench show only milliseconds of difference between benchmarks.
