### ISSUE TITLE
Duplicated lines on window maximisation

### ISSUE THREAD

**Issue by tokyovigilante** [jwilm/alacritty#2866] opened 2019-10-10 11:16 UTC
Fedora 31 with Sway git (352a3e1f) and alacritty HEAD as of today (24651a6). Switching window between FS and windowed several times gives a duplicated line each time, with the result:
![screen2](https://user-images.githubusercontent.com/12971/66564114-23fd5d80-eb57-11e9-9c1d-c69ac02f902f.png)
For reference my PS1 is 
```
__git_ps1 () {
    local b="$(git symbolic-ref HEAD 2>/dev/null)";
    if [ -n "$b" ]; then
        printf " (%s)" "${b##refs/heads/}";
    fi
}
function prompt {
local WHITE="\[\033[1;37m\]"
local GREEN="\[\033[0;32m\]"
local CYAN="\[\033[0;36m\]"
local GRAY="\[\033[0;37m\]"
local BLUE="\[\033[0;34m\]"
local YELLOW="\[\033[1;33m\]"
export PS1="${YELLOW}[\$(date +'%a %l:%M%p')]${WHITE} \u@$(hostname -s)${GREEN}"'$(__git_ps1 "(%s) ") '"${WHITE}\w/\$ "
}
prompt
```
Possibly duplicate of #1668 but this is a different platform and shell so posted a new bug. Thanks!

**Comment by chrisduerr** [comment] 2019-10-10 11:42
Do you get the same behavior when reducing window size below the width of your prompt and then increasing it again? This looks like the issue you get when resizing the prompt, which Alacritty cannot resolve (this is present in all terminal emulators supporting reflow).

**Comment by tokyovigilante** [comment] 2019-10-10 11:47
I guess it's similar behaviour, although wasn't aware that behaviour (which I've noticed in general use) was a shell issue. 

However in this case the terminal remains wider than the prompt, so I'm not sure if it is the same problem or not.

**Comment by chrisduerr** [comment] 2019-10-10 12:26
Could you share the output of `alacritty -v`? That will log the window sizes and should tell us if it randomly resizes to dimensions which are too small.

**Comment by tokyovigilante** [comment] 2019-10-10 13:18
Doesn't seem to be...
```
Created log file at "/tmp/Alacritty-5082.log"
[2019-10-10 14:17] [INFO] Welcome to Alacritty
[2019-10-10 14:17] [INFO] Configuration loaded from "/home/ryan/.config/alacritty/alacritty.yml"
[2019-10-10 14:17] [INFO] Device pixel ratio: 1
[2019-10-10 14:17] [INFO] Initializing glyph cache...
[2019-10-10 14:17] [INFO] ... finished initializing glyph cache in 0.007197989s
[2019-10-10 14:17] [INFO] Cell Size: 10 x 22
[2019-10-10 14:17] [INFO] Padding: 2 x 4
[2019-10-10 14:17] [INFO] Width: 800, Height: 600
[2019-10-10 14:17] [INFO] PTY Dimensions: Line(26) x Column(79)
[2019-10-10 14:17] [INFO] Initialisation complete
[2019-10-10 14:17] [INFO] Width: 953, Height: 1043
[2019-10-10 14:17] [INFO] Font size changed to Size(26) with DPR of 2
[2019-10-10 14:17] [INFO] Width: 1906, Height: 2086
[2019-10-10 14:17] [INFO] Width: 1906, Height: 2086
[2019-10-10 14:17] [INFO] Width: 1906, Height: 2086
[2019-10-10 14:17] [INFO] Width: 1906, Height: 2086
[2019-10-10 14:17] [INFO] Width: 1906, Height: 2086
[2019-10-10 14:17] [INFO] Width: 3840, Height: 2160
[2019-10-10 14:17] [INFO] Width: 1906, Height: 2086
[2019-10-10 14:17] [INFO] Width: 3840, Height: 2160
[2019-10-10 14:17] [INFO] Width: 1906, Height: 2086
[2019-10-10 14:17] [INFO] Width: 3840, Height: 2160
[2019-10-10 14:17] [INFO] Width: 1906, Height: 2086
[2019-10-10 14:17] [INFO] Width: 3840, Height: 2160
[2019-10-10 14:17] [INFO] Width: 1906, Height: 2086
[2019-10-10 14:17] [INFO] Width: 3840, Height: 2160
[2019-10-10 14:17] [INFO] Width: 1906, Height: 2086
[2019-10-10 14:17] [INFO] Width: 3840, Height: 2160
[2019-10-10 14:17] [INFO] Width: 1906, Height: 2086
[2019-10-10 14:17] [INFO] Width: 3840, Height: 2160
[2019-10-10 14:17] [INFO] Width: 1906, Height: 2086
[2019-10-10 14:17] [INFO] Width: 1906, Height: 2086
```

**Comment by chrisduerr** [comment] 2019-10-10 17:57
Can you repro in another terminal emulator, just as sanity check?

And if you have more lines than just the terminal visible, are those affected too? Usually with stuff getting duplicated it's because the terminal is redrawing itself (only the active prompt), so only that line should get duplicated.

**Comment by tokyovigilante** [comment] 2019-10-11 13:24
Does not occur in kitty (from source) or in rxvt-unicode (from Fedora repo). It is just the active prompt that is duplicated, with other content reflowed correctly.

**Comment by chrisduerr** [comment] 2019-10-11 18:17
@tokyovigilante Are you running the default Alacritty configuration? If not, could you give that a shot?

Also just to make sure, do you have the Alacritty terminfo installed and in use?

Another thing worth a shot would be to set the history size to `0` and see if the issue is that lines are pulled from the history.

And testing out bash's default `PS1` instead of your own would rule that out.

**Comment by tokyovigilante** [comment] 2019-10-11 19:09
Turns out my `PS1` is the culprit it seems, doesn't occur with the bash default. Guess I can have a play with cutting that down and figuring out why it's causing issues.

I am indeed using the Alacritty terminfo.

**Comment by kchibisov** [comment] 2019-10-11 19:13
@tokyovigilante we've discussed your issue on IRC and I've bisect a commit, when we introduced this problem c4d2725e14ca9488b1b086024bf827c66945ae7b. However you can add `\e[0m` to your prompt's end or before the last `space` char.

**Comment by tokyovigilante** [comment] 2019-10-11 19:33
@kchibisov nice, thanks! That does indeed solve the issue, however does mean that my terminal input is not in bold as I prefer. Is there any way to preserve that?

**Comment by chrisduerr** [comment] 2019-10-11 19:45
Should probably pick a bolder font. Your prompt's escapes shouldn't leak into the input.

**Comment by tokyovigilante** [comment] 2019-10-11 20:02
@chrisduerr Fair point, but a lot of the utilities I use use bold for differentiation so I prefer to have the default in a regular font (using Source Code Pro for reference). Should I expect this to work with something like `trap 'tput sgr0' DEBUG`?

**Comment by chrisduerr** [comment] 2019-10-11 20:18
You can have a semibold font and then still have the separation between bold and semibold text. I'm running Fira Mono Medium myself. Using the prompt to color or style text is bound to mess with things.

But that's completely your choice, the issue might be related to that, but that's not the root cause of it. So it will be fixed in the future should you choose to stick with it.

**Comment by tokyovigilante** [comment] 2019-10-12 09:00
Great, thanks. I'll keep an eye on this in the meantime.

**Comment by chrisduerr** [comment] 2019-11-02 23:45
Minimal repro in bash:
 - `export PS1="\e[31;1mTEST > "`
 - shrink and grow terminal

**Comment by tokyovigilante** [comment] 2019-11-05 07:48
Fix works a treat, thanks!

**Comment by chrisduerr** [comment] 2019-11-12 22:19
It seems like there's still an issue in this specific scenario:
 - bash
 - `echo -e "\e[41m"`
 - resize

**Comment by chrisduerr** [comment] 2019-11-14 21:59
After some further testing I have been able to confirm that the same bug exists in VTE. This remaining issue is simply a limitation of reflow and the only way to work around it would be to add the option to disable it.

**Closed by chrisduerr** 2019-11-14 21:59 UTC
Labels: B - bug, B - regression

**Comment by cata0309** [comment] 2020-09-19 18:34
This happened to me very recently. How to solve this ?
![image](https://user-images.githubusercontent.com/35623921/93686599-ebcd0180-fabf-11ea-8b0c-9111f12e8238.png)
