### ISSUE TITLE
Ctrl + Alt + Cmd + Space freezes Alacritty on OSX

### ISSUE THREAD

**Issue by mondras** [jwilm/alacritty#244] opened 2017-01-09 00:49 UTC
First of all, amazing project! It's blazing fast!

I use that shortcut for switching input sources, disabled the shortcut and still end up with a frozen terminal. 

Happy to help fix it, but I have no idea on how to debug this.

**Comment by okuuva** [comment] 2017-01-09 14:42
That's odd, I have that exact shortcut for exact same purpose, but for me it's working just fine, no frozen terminal. Just compiled it this morning from commit 2fa271419c4765f7758dcf336fe0b913c12c18a6.

**Comment by mitchellhenke** [comment] 2017-01-09 15:44
this happens to me as well.  If I do some tmux commands like `ctrl+space s`

**Comment by okuuva** [comment] 2017-01-09 19:13
@mondras and @mitchellhenke, see #99 for a temporary workaround.

**Comment by mondras** [comment] 2017-01-09 20:06
@okuuva it helps with avoiding the terminal with freezing but it's not relaying the shortcut to the OS. I also tried recompiling with the latest source and the problem is still there.

**Comment by okuuva** [comment] 2017-01-19 14:09
@mondras ok, that's odd. Never the less, this is duplicate of #99 and should be tracked there.

**Closed** 2017-01-19 17:47 UTC
Labels: duplicate
