### ISSUE TITLE
Ubuntu : child finished with error

### ISSUE THREAD

**Issue by vinayvinodmarar** [jwilm/alacritty#269] opened 2017-01-10 06:18 UTC
Hi I tried to run the executable after compilation. The below was the output and the error messaged popped.

device_pixel_ratio: 1
width: 1024, height: 716
Initializing glyph cache
num fonts = 673
num fonts = 673
num fonts = 673
Finished initializing glyph cache in 0.069083935
set_inner_size: 644px × 436px
width: 644, height: 436
Cell Size: (8 x 18)
PTY Dimensions: Line(24) x Column(80)
num_cols, num_lines = 128, 39
width: 1024, height: 716
**child finished with error '256'**

**Comment by 1inuxoid** [comment] 2017-01-16 16:10
I've got the same issue, is there any way to make it more verbose?

P. S. I created a config in user folder if that can be relevant. I am running Ubuntu LTS 16.04, Kernel 4.4.0-59-generic, Nvidia Drivers 367.57. What else can I provide to help tackling the issue?

**Comment by 1inuxoid** [comment] 2017-01-16 16:18
In my case it was crashing due to following setting:
shell: /bin/zsh

**Comment by vinayvinodmarar** [comment] 2017-01-16 16:39
I didnt dig through the issue. I will let you know if I get any relevant
ideas related to the issue. Please ping in case any solution arises.

Thanks

**Comment by olivierbeltrando** [comment] 2017-04-04 18:46
I can reproduce the issue:
1 - launch alacritty (either from the /usr/local/bin folder or directly from the target folder)
2 - in the newly opened alacritty do **crtl-c**, then **ctrl-d**. The error will show in the parent TTY : **child finished with error '256'**"

My setup: 
- Ubuntu 16.04
- Rustc 1.16.0
- Video driver : nvidia-375
- Shell: zsh

**Comment by olivierbeltrando** [comment] 2017-04-04 19:26
Hum Ok, it was because I built the new code with the old settings it seems 'nightly-2016-12-16-x86_64-unknown-linux-gnu', now I really used rustc 1.16.0 (stable) and I cannot reproduce the bug.

Maybe this ticket can be closed (has it seems it was related with old versions).

**Comment by jwilm** [comment] 2017-04-04 20:42
Thanks for the feedback @olivierbeltrando! We landed a patch last night that resolves this.

**Closed by jwilm** 2017-04-04 20:42 UTC
