### ISSUE TITLE
README section about Wayland/glutin no longer accurate?

### ISSUE THREAD

**Issue by nh2** [jwilm/alacritty#702] opened 2017-07-30 16:14 UTC
Currently it says

> Is wayland supported? Not yet. Alacritty is currently on a fork of glutin that needs some updates to work with Wayland. To stop glutin from detecting Wayland (e.g. for use on XWayland) launch Alacritty like this: `env WAYLAND_DISPLAY= alacritty`

But it seems commit 8e7dd009 - "Update to latest Glutin/winit (#671)" does away with that.

**Comment by NickeZ** [comment] 2017-08-01 20:58
is this a dupe of #97?

**Comment by nh2** [comment] 2017-08-02 09:30
Possibly; I don't know about how well Wayland support works but at least `is currently on a fork of glutin` seems no longer accurate.

**Comment by jwilm** [comment] 2017-08-02 17:09
README definitely needs to be updated a bit. Even though we have some Wayland support now, there are a few caveats, and some might prefer to use XWayland still.

**Closed** 2019-01-04 17:17 UTC
Labels: DS - Wayland
