### ISSUE TITLE
macOS - Window scaling has ghost text artifacts

### ISSUE THREAD

**Issue by vaibhav-y** [jwilm/alacritty#2490] opened 2019-05-29 14:01 UTC
Which operating system does the issue occur on?
macOS Mojave 10.14.5

Steps to reproduce:

1. Enable window trasparency
2. Resize an alacritty window, note the position of any existing text on the window at the maximum size scaled to by dragging the corner
3. Once the redraw happens, there are artifacts of the on-screen text as it appeared just before releasing the resize-drag. 

These seem to be a part of the window background and are unselectable. Other notable behaviours:

1. The artifacts are not visible if the window focus is lost. They are restored on restoring window focus
2. Resizing the window after this replaces the old artifacts with new ones.
3. These don't seem to exist in full-screen mode.

Related screenshot

![Screen Shot 2019-05-29 at 09 48 26](https://user-images.githubusercontent.com/3663231/58562694-bed44b80-81f7-11e9-969f-c85d43d263a6.png)

**Comment by chrisduerr** [comment] 2019-05-29 14:08
This looks like a duplicate of https://github.com/jwilm/alacritty/issues/889.

**Closed by chrisduerr** 2019-05-29 14:08 UTC
