### ISSUE TITLE
Alacritty's making vim flash

### ISSUE THREAD

**Issue by benmezger** [jwilm/alacritty#2460] opened 2019-05-20 21:22 UTC
**MacOS:** `Darwin seds.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64`
**Alacritty's version:** `alacritty 0.3.2`
**Shell:** `zsh/fish`
**Env:**
* `TERM:` `xterm-256color`

When using `Vim` within Alacritty, it makes the buffer disappear completely. It also happens to some terminal commands, such as `ls`, but that varies.

Video: https://asciinema.org/a/IRQT259K1iTy0D8MZbEf0Dxpb

**Comment by chrisduerr** [comment] 2019-05-20 21:30
Duplicate of https://github.com/jwilm/alacritty/issues/2353.

**Closed by chrisduerr** 2019-05-20 21:30 UTC
