### ISSUE TITLE
Dead keys make terminal freeze on macOS

### ISSUE THREAD

**Issue by ldorigo** [jwilm/alacritty#264] opened 2017-01-09 19:46 UTC
Hi, I was pretty excited to try this out but unfortunately it's unusable due to this issue:

All characters that require more than a keypress to be entered ( ' , " , ^ , ~ , ...) make Alacritty freeze and I have no choice but to force quit it.

I'm running macOS Sierra 10.12.1 (16B2555).
Let me know if there is additional information you need.

Cheers!

**Comment by okuuva** [comment] 2017-01-12 19:44
I have this same problem. All dead key characters cause the terminal window to freeze. I can resize and select text but Alacritty stops responding to keyboard.

Running macOS Sierra 10.12.2 (16C67).

**Comment by IwanKaramazow** [comment] 2017-01-12 20:48
I can confirm, having the exact same problem.

**Comment by tylerhou** [comment] 2017-01-15 05:25
I'm running macOS Sierra 10.12.2 (16C67) on build 67aba7f and I'm not running into this issue.

**Comment by okuuva** [comment] 2017-01-15 11:44
Hmm, that's odd. I just updated my binary to 67aba7f4e4758c5fcb7eda50f083b138017fbfdb and the problem still persists. @tylerhou: what keyboard layout you are using?

**Comment by tylerhou** [comment] 2017-01-15 13:50
I'm using US.

**Comment by okuuva** [comment] 2017-01-16 13:29
Well, for me the terminal window hangs if I try to type e.g. diaeresis on any particular layout on both my work and personal Mac. @tylerhou could you confirm you can write it on yours? It's `Option+u` on the US layout.

**Comment by tylerhou** [comment] 2017-01-16 13:31
`option+u` does cause my keyboard to hang (but not `"`, `~`, etc.).

**Comment by okuuva** [comment] 2017-01-16 14:27
That's probably because you can type tilde (`~`) either as regular character with `Shift + >` or as a dead key with `Option + n` and you've been using the former. I just tested it again and all dead keys on US layout (`~ ¨ ´ ˆ ` and back tick) cause terminal window to hang, so this issue is still valid even though you can type some of those characters as regular characters as well.

**Comment by tylerhou** [comment] 2017-01-16 15:06
Oh, my bad. I misinterpreted the original issue; I thought that there were issues with all keys which needed two keyboard-presses to be entered (like capital letters for instance). Didn't realize that OP was referring to keys which required them to press a key *after* they entered the first.

**Comment by okuuva** [comment] 2017-01-16 16:55
Actually the original issue seems to be how @tylerhou interpreted and I've just hijacked it because I didn't read it carefully enough... :sweat_smile:

Could @ldorigo confirm this so I can open a new issue?

**Comment by ldorigo** [comment] 2017-01-16 16:57
No, you're right. I just didn't know the right word for dead keys. Fixed that.

**Comment by okuuva** [comment] 2017-01-17 19:33
This is possibly related / duplicate of #209.

**Comment by jwilm** [comment] 2017-01-17 19:43
thanks @okuuva

**Closed by jwilm** 2017-01-17 19:43 UTC

**Comment by okuuva** [comment] 2017-01-17 19:50
No problem :)
