### ISSUE TITLE
Failed to open Input Method on Locale en_IN.

### ISSUE THREAD

**Issue by chshbh** [jwilm/alacritty#2634] opened 2019-07-10 03:01 UTC
Which operating system does the issue occur on?
OS: Manjaro Linux x86_64
Kernel: 4.19.56-1-MANJARO
DE: GNOME 3.32.2 
If on linux, are you using X11 or Wayland?
```bash
$ echo $XDG_SESSION_TYPE                                                                                                                                                                     
# x11
$ echo $LANG
# en_IN
```

![ala](https://user-images.githubusercontent.com/9166890/60936739-c0f7f280-a2eb-11e9-8c58-15ec6cf21131.png)

If the image is unclear, Please do ask me. 
I tried installing it from pacman, and then tried the git flagged version from Arch User Repo(AUR). FInally, [building](https://github.com/jwilm/alacritty/blob/master/INSTALL.md) from scratch, but the same problem persist. I followed the guide, only difference was installing Rust compiler which I installed using Pacman rather than rustup.

**Comment by kchibisov** [comment] 2019-07-10 05:41
Are you using IME or it just fails with such error? In case of 1st, what input method are you using? Is it fails right after IME triggering?

**Comment by chshbh** [comment] 2019-07-10 17:54
No, it just fails with such error. I am not using IME afaik. 
![alcrtty](https://user-images.githubusercontent.com/9166890/60992104-774ded00-a369-11e9-9ef8-c727f0a5e604.png)

I am using default settings for the input method. I would need more information regarding IME. Appreciate it.

**Comment by chshbh** [comment] 2019-07-10 18:05
It is working now, I changed my locale to en_US.UTF-8 from en_IN. That does the trick. 
But, en_IN is also English locale based on India. Is it because of UTF-8?

**Comment by chrisduerr** [comment] 2019-07-10 18:22
This is a duplicate of https://github.com/jwilm/alacritty/issues/2553.

**Closed by chrisduerr** 2019-07-10 18:22 UTC
