### ISSUE TITLE
Rendering issue with Kakoune editor

### ISSUE THREAD

**Issue by jwhett** [jwilm/alacritty#2842] opened 2019-10-03 19:29 UTC
Which operating system does the issue occur on?

- Fedora 30

If on linux, are you using X11 or Wayland? 

- X11

---

Section prior to triggering the bug:

![2019-10-03-152119_191x194_scrot](https://user-images.githubusercontent.com/4229885/66157307-843d4e00-e5f1-11e9-8326-b34749160ab5.png)

Example of bug: 
![2019-10-03-145900_220x191_scrot](https://user-images.githubusercontent.com/4229885/66155783-628e9780-e5ee-11e9-95fa-b1ce0f5605c8.png)

Apparent malformation during re-render. The example in the screen shot is the easiest to reproduce. I started searching for `string(` and the redraw struggles. Leaving the search and scrolling through the searched line produces the following though the cursor is two lines beyond this line:

![2019-10-03-150234_198x196_scrot](https://user-images.githubusercontent.com/4229885/66156020-d7fa6800-e5ee-11e9-8f8b-9e0eed64578c.png)

Both Alacritty and Kakoune are built from the source; commits:
- [Kakoune](https://github.com/mawww/kakoune) - 2f1be14b5f4d3668df14f56239978e7e00102806
- Alacritty - f6f444bc2d3a9f95a206c9d09843d54009f89f58

x11 pkgs:

```
xorg-x11-drv-evdev-2.10.6-4.fc30.x86_64
xorg-x11-xkb-utils-7.7-29.fc30.x86_64
xorg-x11-utils-7.5-30.fc30.x86_64
xorg-x11-proto-devel-2018.4-3.fc30.noarch
xorg-x11-server-Xwayland-1.20.5-7.fc30.x86_64
xorg-x11-fonts-misc-7.5-21.fc30.noarch
xorg-x11-drv-vesa-2.4.0-6.fc30.x86_64
xorg-x11-drv-wacom-serial-support-0.36.1-6.fc30.x86_64
xorg-x11-drv-libinput-0.29.0-1.fc30.x86_64
xorg-x11-fonts-ISO8859-1-100dpi-7.5-21.fc30.noarch
xorg-x11-drv-nouveau-1.0.15-7.fc30.x86_64
xorg-x11-font-utils-7.5-41.fc30.x86_64
xorg-x11-fonts-Type1-7.5-21.fc30.noarch
xorg-x11-drv-openchrome-0.6.0-7.fc30.x86_64
xorg-x11-drv-ati-19.0.1-2.fc30.x86_64
xorg-x11-server-utils-7.7-28.fc30.x86_64
xorg-x11-drv-fbdev-0.5.0-3.fc30.x86_64
xorg-x11-xinit-1.4.0-4.fc30.x86_64
xorg-x11-server-common-1.20.5-7.fc30.x86_64
xorg-x11-xbitmaps-1.1.1-16.fc30.noarch
xorg-x11-server-Xorg-1.20.5-7.fc30.x86_64
xorg-x11-xauth-1.0.9-14.fc30.x86_64
xorg-x11-drv-vmware-13.2.1-9.fc30.x86_64
xorg-x11-drv-intel-2.99.917-42.20180618.fc30.x86_64
xorg-x11-drv-wacom-0.36.1-6.fc30.x86_64
xorg-x11-drv-qxl-0.1.5-11.fc30.x86_64
xorg-x11-apps-7.7-24.fc30.x86_64
```

[`script` output of replicating from `bash` in Alacritty](https://github.com/jwilm/alacritty/files/3687729/typescript.txt)

Bug occurred after rebuilding Alacritty at the commit noted above.

This behavior does not appear to exist in `gnome-terminal` when attempting to replicate elsewhere.

**Comment by kchibisov** [comment] 2019-10-03 19:41
> Bug occurred after rebuilding Alacritty at the commit noted above.

So can you repro on an older version of alacritty?

**Comment by chrisduerr** [comment] 2019-10-03 19:46
Did you change the configuration file at all? Specifically the tab width?

**Comment by jwhett** [comment] 2019-10-16 15:15
Sorry for the extreme delay, had some life get in the way. I'll attempt to reproduce in older versions of Alacritty. @chrisduerr, I didn't not modify the configuration in any way. I encountered this issue after my periodic "update and recompile all my tools."

**Comment by jwhett** [comment] 2019-10-16 15:19
An interesting point to note, I cannot trigger this issue while running in `tmux`. Terminfo when attempting to replicate in `tmux`: `screen-256color`.

**Comment by chrisduerr** [comment] 2019-10-16 18:46
Please make sure the terminfo `Alacritty` is used outside of tmux when trying to reproduce this.

**Comment by jwhett** [comment] 2019-10-18 12:46
Understood. Looks like my _weekly_ rebuilds were slacking quite a bit...

I've replicated the issue in the 0.3.2 and 0.3.3 Alacritty releases on the latest kakoune commits. It appears something may have been introduced between 82d99aa12b8bea66cd8751368181eaa1a39b160a (early september; no rendering issue) and 2f1be14b5f4d3668df14f56239978e7e00102806 (early october; rendering issue) on kakoune's master branch.

I'll bisect to see if I can pin the issue to a specific commit in kakoune. Might not be Alacritty at all.

**Comment by chrisduerr** [comment] 2019-10-18 13:04
That **really** sounds like it's not redrawing enough now. I'll close this issue so it won't be forgotten, but if it turns out that Kakoune is not at fault, please let me know so I can re-open.

**Closed by chrisduerr** 2019-10-18 13:04 UTC

**Comment by jwhett** [comment] 2019-10-18 13:22
Sorry to take up your time, but thanks for your assistance.

**Comment by chrisduerr** [comment] 2019-10-18 13:25
> Sorry to take up your time, but thanks for your assistance.

Absolutely no worries, please let me know if you need any more help.

**Comment by jwhett** [comment] 2019-10-21 18:01
@chrisduerr,

There's been some discussion on the [Kakoune issue](https://github.com/mawww/kakoune/issues/3144) and it turns out that the [latest terminfo](https://invisible-island.net/ncurses/terminfo.src.html) from ncurses resolves the issue. Manually installing that terminfo for my user resolves the issue and `root` continues to experience the rendering issues as expected without an updated terminfo db. Is that enough to run with?

Thanks,
Josh

**Comment by chrisduerr** [comment] 2019-10-21 18:07
Yeah that sounds about right, thanks for the update!

**Comment by jwhett** [comment] 2019-10-31 19:27
Latest update and rebuild today, along with replacing my `alacritty.yml` file with the one in the repo, seems to have resolved it. [Here's my old, seemingly broken, config](https://github.com/jwilm/alacritty/files/3795490/alacritty.txt).
