### ISSUE TITLE
Alacritty crashes when using a to big font size. 

### ISSUE THREAD

**Issue by sandersantema** [jwilm/alacritty#903] opened 2017-11-16 09:58 UTC
Which operating system does the issue occur on? Mac OS 10.12.6
To reproduce: Open up Alacritty zoom with cmd + until it crashes.
[AlacrittyCrashLog.txt](https://github.com/jwilm/alacritty/files/1478101/AlacrittyCrashLog.txt)

**Comment by maximbaz** [comment] 2017-11-16 13:27
Duplicate of #842 and #898

**Closed** 2017-11-16 16:56 UTC
