### ISSUE TITLE
Terminal window not taking all available space 

### ISSUE THREAD

**Issue by Tanuj69** [jwilm/alacritty#2062] opened 2019-02-02 06:58 UTC
Which operating system does the issue occur on?
KDE Neon
If on linux, are you using X11 or Wayland?
X11
KDE Neon comes with Kwin and window manager in which I use [this extension](https://github.com/lingtjien/Grid-Tiling-Kwin) for tiling every other application works fine but not alacritty it just don't follow the tiling 
[Image for reference](https://i.imgur.com/BXV66gS.png)

**Comment by chrisduerr** [comment] 2019-02-02 11:43
Duplicate of https://github.com/jwilm/alacritty/issues/1825.

**Closed by chrisduerr** 2019-02-02 11:43 UTC
