### ISSUE TITLE
[Ubuntu, Unity] Input lag in fullscreen only

### ISSUE THREAD

**Issue by parsonsmatt** [jwilm/alacritty#785] opened 2017-09-17 15:58 UTC
When I open alacritty, it is blazing fast and awesome. In any window configuration other than full screen, it works without a hitch.

When I fullscreen the terminal, there is noticeable draw/render lag on the last line of the terminal. If I `cat **/*.csv`, it renders everything super fast, but when it's done, it doesn't display my prompt. When I type a single letter, it doesn't show that letter until I type the next one, click the window, or otherwise interact with the window.

This problem does not occur when using xmonad window manager.

> Which operating system does the issue occur on?

Ubuntu 16.04

> If on linux, are you using X11 or Wayland?

Whatever Unity has by default

**Comment by jwilm** [comment] 2017-09-17 20:39
This sounds like a duplicate of #540.

**Closed by jwilm** 2017-09-17 20:39 UTC

**Comment by parsonsmatt** [comment] 2017-09-18 00:48
Thanks! I've subscribed to that issue.
