### ISSUE TITLE
Implement xkbcommon stuff for Wayland

### ISSUE THREAD

**Issue by johalun** [jwilm/alacritty#354] opened 2017-01-25 02:58 UTC
Hey

I really want to get this up and running on Wayland. What it's missing to run with newer glutin that supports Wayland is implementing key event handling using xkbcommon as described here: https://xkbcommon.org/doc/current/md_doc_quick-guide.html

Do you have any plan for this yet?  I'm not sure but I guess that won't be done in glutin since they only forward key events from Wayland as is so it's up to alacritty to keep a state of modifiers, etc. 

I can give an initial implementation a shot, unless you have some other plans or info I don't know about.

**Comment by jwilm** [comment] 2017-01-25 03:51
I talked with @vberger about this on IRC a long time ago. At the time, the wayland-kbd crate was stealing all of the keboard events to handle the keymap and produce UTF-8 codes. In theory, the modifiers should be provided to glutin/winit instead of being swallowed by wayland-kbd. I'm not sure what the story is now.

The proper way to implement this is to actually update glutin/winit if something we need is missing. There's some ongoing work in this area already at [winit#112](https://github.com/tomaka/winit/pull/112).

**Comment by johalun** [comment] 2017-01-25 03:56
Thanks, I will look into it. 

I guess both yes and no. If you're a game, you want to be able to get "raw" events and not have glutin consuming modifier events. But I guess that could be something you could opt in for in your glutin-client.

**Comment by vberger** [comment] 2017-01-25 12:59
It's been some time I've worked on it, but afaik winit should forward for each keypress both the raw key event *and* its utf8 interpretation given the modifier context. If it is not the case, then it is definitely a bug.

I'm not completely sure I understand what is missing from that for alacritty, could you explain a little more your needs? Is it that winit swallows the key events for modifiers keys (ctrl, alt, shift) without forwarding them properly?

**Comment by jwilm** [comment] 2017-01-25 16:17
@vberger Alacritty is currently on a pre-winit fork of glutin. One of the changes was adding a `Mods` argument to the `Event::KeyboardInput`. The mods are what is provided by the underlying windowing API since tracking them in the application [doesn't always work](https://github.com/tomaka/winit/issues/77). 

This issue is (I believe) doing the same for the Wayland backend in winit. There's an [active PR](https://github.com/tomaka/winit/pull/112) for upstreaming the feature as a whole, but the Wayland section is still unimplemented.

**Comment by jwilm** [comment] 2017-01-25 16:17
Oh, to directly answer your question

> Is it that winit swallows the key events for modifiers keys (ctrl, alt, shift) without forwarding them properly?

Yes.

**Comment by vberger** [comment] 2017-01-26 07:32
I see. I've opened an issue on wayland-kbd. It should not require a lot of changes to implement the wayland part of this winit PR.

**Comment by vberger** [comment] 2017-01-29 10:21
Just to make sure I followed this correctly, would https://github.com/tomaka/winit/pull/112 with proper wayland support fix this issue?

**Comment by jwilm** [comment] 2017-01-29 15:08
I believe so.

**Comment by jonhoo** [comment] 2017-06-02 01:41
Oooh, so this is likely the reason for #148 then?

**Comment by jonhoo** [comment] 2017-06-02 01:42
Also, tomaka/winit#112 has landed.

**Comment by jwilm** [comment] 2017-07-01 23:33
At this point, this is a duplicate of #234.

**Closed by jwilm** 2017-07-01 23:33 UTC
