### ISSUE TITLE
alt_send_esc doesn't seem to work on Windows

### ISSUE THREAD

**Issue by radix** [jwilm/alacritty#2135] opened 2019-02-27 20:33 UTC
**OS:** Windows 10
**Alacritty Version:** 0.2.9
**backend:** Both WinPTY and ConPTY

I can't use alt-b, alt-f, and alt-d in powershell on windows, even though the native terminal does allow me to do those things (to jump between words, and delete words, respectively). I noticed that if I explicitly configure alacritty to bind those keys it seems to work:

```yaml
  - { key: B,        mods: Alt,     chars: "\x1bb"}
  - { key: F,        mods: Alt,     chars: "\x1bf"}
  - { key: D,        mods: Alt,     chars: "\x1bd"}
```

**Comment by chrisduerr** [comment] 2019-02-27 20:39
Is this using ConPTY or WinPTY?

**Comment by radix** [comment] 2019-02-27 21:42
WinPTY, I have `enable_experimental_conpty_backend: false`

**Comment by chrisduerr** [comment] 2019-02-27 21:50
Would you mind testing with ConPTY, assuming that you have the required update installed?

I wouldn't be surprised if WinPTY would mess with things here, since it doesn't comply with the typical unix terminal standards at all.

**Comment by radix** [comment] 2019-02-28 00:44
As I understand it, ConPTY is still a Windows Insider feature? I'm just using normal windows pro (fully up to date). When I tried enabling alacritty's ConPTY support, the verbose output still said it was using WinPTY.

**Comment by chrisduerr** [comment] 2019-02-28 06:38
ConPTY just requires to have the 2018.10 update to be installed. It does not require you to be part of the Windows Insider program.

Make sure the config is loaded from the right directory, this should be printed in the verbose output too.

**Comment by radix** [comment] 2019-02-28 15:26
If I set `enable_experimental_conpty_backend: true` in `"C:\Users\radix\AppData\Roaming\alacritty\alacritty.yml"`, it still doesn't actually use ConPTY, the verbose startup still shows it's using WinPTY. And it prints out that exact path.  (I know this config file is being used, as well, because it also has the changes to make my Alt-b, Alt-f, and Alt-d keys work).

I'm not really sure how to tell if I have 2018.10 installed. That's not a version format that I see anywhere else in the Windows settings. Here's what the "Windows Specifications" sections of "About your PC" says:

```
Edition:        Windows 10 Pro
Version:        1803
Installed on:   9/10/2018
OS build:       17134.590
```

Is the `Version: 1803` supposed to be `1810` if I have 2018.10?  When I use "Check for updates", I don't get any new updates.

Oh wait! Well, I used "Check for updates" it yesterday and didn't get any updates. But today it's telling me that there's an `1809` update that I can install, which I'm doing now. Will report back later.

**Comment by radix** [comment] 2019-02-28 16:29
Ok, that update seems to have enabled ConPTY. 

```
[2019-02-28 10:28] [INFO] Using Conpty agent
```

And the problem persists. I can't use alt-f, alt-b, alt-d unless I explicitly bind them in alacritty.yml, even though `alt_send_esc` is `true`.

**Comment by radix** [comment] 2019-02-28 17:52
I think this is a duplicate of #1939.

**Comment by chrisduerr** [comment] 2019-02-28 18:56
Yeah, if this doesn't work in ConPTY either, it's a duplicate of #1939.

**Closed by chrisduerr** 2019-02-28 18:56 UTC
