### ISSUE TITLE
Ranger doesn't get ctrl+h event

### ISSUE THREAD

**Issue by Eyenseo** [jwilm/alacritty#810] opened 2017-10-03 16:23 UTC
#### Which operating system does the issue occur on?
Archlinux

#### If on linux, are you using X11 or Wayland?
X11

#### Issue:
I'm not completely sure if this is a issue with alacritty(scrollback branch & master) or ranger(1.8.1 & 1.9.0b5). I noticed that `ctrl+h` does not show the hidden files when I use ranger in alacritty - when I use termite and ranger `ctrl+h` works as expected. Now the suspicious thing is, that this is seems to affect only `h`- if I remap the combination to "anything" else (randomly picked a few keys eg `ctrl+e`or`ctrl+y`...) the key combination works. 

For now I will fallback to another mapping but it would be nice if this will be fixed.

**Comment by C0DEHERO** [comment] 2017-10-05 21:47
~~Oddly enough, ctrl+h does not work with xterm, konsole, terminology, cool-retro-term or gnome-terminal either. It does work with urxvt, termite, st~~

Scrap that. I'm not exactly sure why this is happening, but ranger doesn't work if `$TERM` is `xterm` or `xterm-256color`. Do `export TERM=xterm-termine`, which is the TERM variable termite uses, and ranger will work as expected. So, this is obviously not a problem with alacritty, but it is also not a problem with ranger, and that was discussed [here](https://github.com/ranger/ranger/issues/559) in a ranger bug report with a detailed explanation found in the linked stackexchange thread.

From what I've gathered, there are a few solutions to this problem. Either: you can change your TERM variable, Archlinux can fix the terminfo files for xterm~~, or alacritty can ship its own terminfo file like urxvt, termite, and st (among others) are doing.~~

~~A custom terminfo for alacritty would be the most consistent solution, but that can cause problems when using ncurses applications over ssh because those applications will need that custom terminfo file to function correctly. I think the custom terminfo would be the best solution if alacritty enjoyed widespread usage like urxvt, but it would likely cause even more issues at the moment.~~

So, apparently alacritty does have a custom terminfo but still uses xterm-256color as the base, so a good solution might be to overwrite the specific parts needed for C-h to work correctly on all distros, which seems to be simply adding `kbs=\177`.

Of course, this won't fix the issue if you don't install the terminfo file into /usr/share/terminfo, so you would have to either manually copy the file or use makepkg (or an AUR helper) to install alacritty. And of course, you would have to install the terminfo file on any server you use.

**Comment by jwilm** [comment] 2017-10-05 21:51
Sounds like we should just update our terminfo file as you've suggested.

> Of course, this won't fix the issue if you don't install the terminfo file into /usr/share/terminfo, so you would have to either manually copy the file or use makepkg (or an AUR helper) to install alacritty. And of course, you would have to install the terminfo file on any server you use.

I don't think there's much we can do about that.

**Comment by freed00m** [comment] 2018-04-22 18:38
It happens to gnome-termin 3.28 as well. When I set "export TERM=xterm-termine" the <C-h> works but when I exit ranger, the screen is not refreshed and I have to do it myself.

@PyroLagus 
> 
which seems to be simply adding kbs=\177.
> 

Where, also what it does? I've tried to put it in ~/.terminfo but nothing happened.

**Comment by Limero** [comment] 2018-09-24 20:56
Any update on this? I installed the [alacritty-terminfo](https://www.archlinux.org/packages/community/x86_64/alacritty-terminfo/) package and tried running `export TERM=alacritty` before opening ranger and it still doesn't work. If I do `export TERM=st` in alacritty, it does work as intended.

**Comment by Limero** [comment] 2019-04-17 12:41
It works. Issue can be closed :)

**Closed** 2019-04-17 18:16 UTC
