### ISSUE TITLE
Ubuntu: Error creating GL context; Some of the required attributes are not supported

### ISSUE THREAD

**Issue by TaylorDennisLee** [jwilm/alacritty#1204] opened 2018-03-24 02:57 UTC
Which operating system does the issue occur on?

Ubuntu 17.10

If on linux, are you using X11 or Wayland?

Wayland?

It seems to build fine, but when I try to execute the binary, I get this error:

Error creating GL context; Some of the required attributes are not supported

**Comment by DaGuich** [comment] 2018-04-12 12:11
#1083 
env WAYLAND_DISPLAY= alacritty

**Comment by chrisduerr** [comment] 2018-10-02 21:02
Closing this as a duplicate of #1083.

**Closed by chrisduerr** 2018-10-02 21:02 UTC
