### ISSUE TITLE
Key repeat sluggish

### ISSUE THREAD

**Issue by ulf5** [jwilm/alacritty#2514] opened 2019-06-06 10:05 UTC
Which operating system does the issue occur on?
Linux (Fedora 30)

If on linux, are you using X11 or Wayland?
X11 (issue does not occur in wayland)

I'm running gnome and have set the following settings for key repeat:
```
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 15
gsettings set org.gnome.desktop.peripherals.keyboard delay 275
```

If I hold a key and then let it up the key will continue repeating for a while in alacritty, this does not happen in gnome-terminal. The longer I've held the key the longer it continues it seems. 

E.g.:
Have a long line in vim and go to the right by holding "l" in normal mode, then when I reach the point I want to stop at I let go of "l" in alacritty the cursor will continue going right for a bit.
This happens outside vim as well.

**Comment by yesacs** [comment] 2019-06-06 15:15
I'm seeing similar behavior on my late 2018 Macbook Pro in macOS 10.14.5, but only with my external usb keyboard. The internal keyboard doesn't seem to have this problem. My key repeat settings in sys prefs are Key Repeat set to Fast (the fastest) and Delay set to short (the shortest), but changing these doesn't seem make a difference in the issue. The key repeat happens at the same rate on both keyboards, but my external keyboard will continue repeating past key release for about half a second where the internal keyboard will stop at key release. It also doesn't happen all the time, sometimes switching back and forth between apps will fix it temporarily but it always starts happening a few moments later. Usually a graphical stutter in alacritty will happen right before the repeat problem starts.

This started for me after upgrading from 10.13 to 10.14. Other applications, like iTerm2, aren't exhibiting this behavior.

Here's a quick screencast I made to show what i'm seeing:
https://drive.google.com/file/d/1BJ5SbTtpsZ46yWGSFsuXXMzNk2KT_Bca/view?usp=sharing

**Comment by chrisduerr** [comment] 2019-06-06 17:44
This seems to be a duplicate of https://github.com/jwilm/alacritty/issues/1466.

If anyone is interested in helping a bit, I'd be interested if the #2438 PR fixes this. This doesn't work on macOS yet, though.

I'd also like to try again if cloning https://github.com/rust-windowing/winit has the same issues, this can be tested with `cargo run --example window` and checking if the output keeps going after the key has been released should be a reliable way of testing this. The OP of the #1466 issue said this only happens with glutin, however that seems very surprising to me.

**Closed by chrisduerr** 2019-06-06 17:44 UTC
