### ISSUE TITLE
Switching from/to screen to external monitor resolution problem

### ISSUE THREAD

**Issue by nashio** [jwilm/alacritty#649] opened 2017-07-02 22:25 UTC
If I load Alacritty from my retina laptop and then later on I connect it to an external monitor and I move the window to said monitor. The font/resolution will be out of proportion (big). Same thing happens backwards. If I open Alacritty on the monitor and pass the laptop window, the font will be very very small. If I open and close it, that fixes this, but its not ideal.
Is there a way to reload the config so a re-render fixes this without actually closing Alacritty?

**Comment by jwilm** [comment] 2017-07-02 22:37
Duplicate of #71.

**Closed by jwilm** 2017-07-02 22:37 UTC
