### ISSUE TITLE
Random colour issues

### ISSUE THREAD

**Issue by xfbs** [jwilm/alacritty#2434] opened 2019-05-10 21:05 UTC
Occurs on macOS 10.13 and 10.14.

This particular instance was me running `lsof -p 3691 | less` in alacritty (vanilla bash, not inside tmux). However I've also managed to get alacritty to do this in vim, the issue seems to occur randomly.

![Screen Shot 2019-05-10 at 22 58 45](https://user-images.githubusercontent.com/786420/57556632-dbf3c800-7377-11e9-88fb-585f8aaa6c4e.png)

**Comment by nicolashahn** [comment] 2019-05-19 18:03
+1 on vim, I get this when I switch from `background=light` to `dark` or vice versa.

**Comment by nicolashahn** [comment] 2019-05-19 18:04
Screenshot: 
<img width="724" alt="Screen Shot 2019-05-19 at 2 04 22 PM" src="https://user-images.githubusercontent.com/9121818/57986139-0c55f900-7a3f-11e9-9a2a-3b3aaf9c2128.png">

**Comment by chrisduerr** [comment] 2019-05-20 15:35
I personally can't reproduce this issue, which is a bit odd, but I'd assume this is because of some mistake with the template cell.

Recording a ref test could help here though, this can be done by running Alacritty with `alacritty --ref-test` and it will write all escape sequences to a file. I'd assume that would make reproduction a bit easier.

**Comment by nicolashahn** [comment] 2019-05-22 03:35
I can't seem to reproduce my vim issue unless I'm already in tmux, but I was able to make an `alacritty.recording`: https://gist.github.com/nicolashahn/6b1d10cf72155dde26d9f986a8a45cf7

This is me opening tmux, opening my .vimrc in vim, then swapping the background to light.

**Comment by chrisduerr** [comment] 2019-05-22 18:27
Can you reproduce this issue by doing `cat alacritty.recording` or does that not do the job for you?

I've tried it with this recording and it does seem like the recording worked correctly but I can't reproduce the issue.

**Comment by nicolashahn** [comment] 2019-05-22 18:38
Sorry, I shouldn't have included the section where I close tmux and vim before stopping recording. I updated the gist, now when I `cat alacritty.recording` I end up with this: 
<img width="471" alt="Screen Shot 2019-05-22 at 2 36 37 PM" src="https://user-images.githubusercontent.com/9121818/58199775-402f5980-7c9f-11e9-8a6c-de950264e9e0.png">

**Comment by chrisduerr** [comment] 2019-05-22 19:15
I can reproduce it with the new gist, thanks. I'll take a look once some other issues are resolved.

The great thing about these ref tests is that just the escape sequences are recorded, so it doesn't matter at all what your vim or tmux configuration is, since these are never actually run.

**Comment by nicolashahn** [comment] 2019-05-23 13:54
Thanks for looking into this. If it helps, I found another way to reproduce the issue, without tmux. If I open a file in vim, then change alacritty's font size a few times, then scroll, the problem will show up. Another `alacritty.recording` to demonstrate: https://gist.github.com/nicolashahn/3b7db73b3db44849114d63f0e4956e30

**Comment by kchibisov** [comment] 2019-07-09 19:20
Seems like it was fixed by af30f3735a5e402509cb14b994576d0ea4799557

**Comment by chrisduerr** [comment] 2019-07-09 19:36
@kchibisov I was hoping so, but forgot about updating this issue! Thanks for testing. Based on my test the performance fix PR also does not break this, so we should be good to go!

**Closed by chrisduerr** 2019-07-09 19:36 UTC
Labels: B - bug, C - awaiting followup
