### ISSUE TITLE
Adding support for an include directive in the config file

### ISSUE THREAD

**Issue by vegizombie** [jwilm/alacritty#1830] opened 2018-11-21 01:33 UTC
For most other applications I have set up my config files such that they are stored on a private git repo, and I can then link to them using the include directives that the config format supports. For example:

- .bashrc: source
- .inputrc: $include
- .ssh/config: Include
- .tmux.conf: source-file

This obviously isn't a high priority requirement (for now I am just using a symlink). As I am interested in rust I also wouldn't mind having a go at implementing this myself, if you were happy to approve the high level idea.

**Comment by chrisduerr** [comment] 2018-11-21 01:40
This is a duplicate of https://github.com/jwilm/alacritty/issues/779.

**Closed by chrisduerr** 2018-11-21 01:40 UTC

**Comment by vegizombie** [comment] 2018-11-21 01:41
Thank you for the link :)
