### ISSUE TITLE
Thread 'pty reader' panicked due to index out of bounds

### ISSUE THREAD

**Issue by jonathanio** [jwilm/alacritty#68] opened 2017-01-05 21:30 UTC
Just trying out alacritty (thanks) and if I use a full-window application such as `top` or `htop` it crashes on exit (however periodic screen updates are fine):

```
thread 'pty reader' panicked at 'index out of bounds: the len is 133 but the index is 134',
/buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcollections/vec.rs:1371
stack backtrace:
   1:     0x5622aa5cf28a - <unknown>
   2:     0x5622aa5d452f - <unknown>
   3:     0x5622aa5d412e - <unknown>
   4:     0x5622aa5d49d7 - <unknown>
   5:     0x5622aa5d4864 - <unknown>
   6:     0x5622aa5d4789 - <unknown>
   7:     0x5622aa5d4717 - <unknown>
   8:     0x5622aa60075d - <unknown>
   9:     0x5622aa600708 - <unknown>
  10:     0x5622aa4b40df - <unknown>
  11:     0x5622aa4c4cca - <unknown>
  12:     0x5622aa4b04fb - <unknown>
  13:     0x5622aa5db89a - <unknown>
  14:     0x5622aa4c2bea - <unknown>
  15:     0x5622aa5d3824 - <unknown>
  16:     0x7f326f881453 - start_thread
  17:     0x7f326f3ad7de - __GI___clone
  18:                0x0 - <unknown>
child finished with error '256'
```

Using tools such as `less`, `watch`, or `vim`, don't have the same effect, just `top` and `htop` so far.

**Comment by jwilm** [comment] 2017-01-05 21:38
That's surprising. `htop` and `top` have worked fine in my testing.

Would you be willing to reproduce this once more but run alarcritty with the `--ref-test` flag? This will generate a file called `alacritty.recording` which contains all of the terminal protocol from your session. The recording is incredibly helpful for debugging.

Alternatively, if you could give more information about the system and specific steps to reproduce it, I could try and do so myself. (the recording would be preferred).

Thanks for the report!

**Comment by jonathanio** [comment] 2017-01-05 21:52
[alacritty.recording.zip](https://github.com/jwilm/alacritty/files/688466/alacritty.recording.zip)

No problem; attached. Steps: Start `alacritty`, start `top`, press `q` to quit. Not sure if this helps, but if I run inside of `byobu` (i.e. `tumx`) it exits cleanly and I can continue on as normal.

As for my system: i7/32GB, Nvidia GTX-960 2GB (with Nvidia binary drivers), Arch Linux/X11/i3/compton connected to a 4K display (although it affects my other 1200p display too).

**Comment by jwilm** [comment] 2017-01-05 22:30
Thanks! Hoping to get a chance to look at your recording this evening. I forgot to ask in the first place, was the window resized at all, or was this recorded with single size?

**Comment by jonathanio** [comment] 2017-01-05 22:48
Always a fixed size. Not tried any resizing yet really.

**Comment by jwilm** [comment] 2017-01-05 22:59
ah, great. I'm not sure what happens when trying to replay a recording at a different size.

**Comment by jonathanio** [comment] 2017-01-06 09:21
[alacritty.recording.zip](https://github.com/jwilm/alacritty/files/689461/alacritty.recording.zip)

I've created a smaller window this time so this should make it easier for you.

```thread 'pty reader' panicked at 'index out of bounds: the len is 61 but the index is 62', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcollections/vec.rs:1371```

**Comment by shanemhansen** [comment] 2017-01-06 19:17
I've created what seems to be a similar problem, but with a full stacktrace. Steps to reproduce:

 * Start alacritty
 * Run top
 * Make top colored (type 'z')
 * Exit top (type 'q')

```
thread 'pty reader' panicked at 'index out of bounds: the len is 24 but the index is 25', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcollections/vec.rs:1371
stack backtrace:
   1:     0x55c5c71eb81a - std::sys::imp::backtrace::tracing::imp::write::h2b860f17b6b0f511
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x55c5c71f0abf - std::panicking::default_hook::{{closure}}::hedea7d569eb1e6b8
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:349
   3:     0x55c5c71f06be - std::panicking::default_hook::he87e0c76c89c52a4
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:365
   4:     0x55c5c71f0f67 - std::panicking::rust_panic_with_hook::h304127bde2d3d5e2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:553
   5:     0x55c5c71f0df4 - std::panicking::begin_panic::h814f60faa3ce8314
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:515
   6:     0x55c5c71f0d19 - std::panicking::begin_panic_fmt::hf4f7d700fa077693
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:499
   7:     0x55c5c71f0ca7 - rust_begin_unwind
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:475
   8:     0x55c5c721cced - core::panicking::panic_fmt::hee207ff21fb62166
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   9:     0x55c5c721cc98 - core::panicking::panic_bounds_check::hca28eae069525a56
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:56
  10:     0x55c5c70d019f - vte::Parser::perform_action::he3ae7936b63290ef
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcollections/vec.rs:1371
                        at /home/shansen/code/alacritty/src/grid.rs:209
                        at /home/shansen/code/alacritty/src/term/mod.rs:896
                        at /home/shansen/code/alacritty/src/ansi.rs:566
                        at /home/shansen/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:205
  11:     0x55c5c70e0dea - <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}::hf0a0a180ba5dba31
                        at /home/shansen/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:158
                        at /home/shansen/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:137
                        at /home/shansen/code/alacritty/src/ansi.rs:85
                        at /home/shansen/code/alacritty/src/event_loop.rs:211
                        at /home/shansen/code/alacritty/src/event_loop.rs:308
  12:     0x55c5c70cc58b - std::panicking::try::do_call::hcfd56f88629ff96d
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:295
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:458
  13:     0x55c5c71f7e2a - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  14:     0x55c5c70decaa - <F as alloc::boxed::FnBox<A>>::call_box::h93a8c2ebc41d9ac9
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:434
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:351
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:287
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  15:     0x55c5c71efdb4 - std::sys::imp::thread::Thread::new::thread_start::h460a0adc61139b06
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  16:     0x7f2d11ca06b9 - start_thread
  17:     0x7f2d117c082c - clone
  18:                0x0 - <unknown>
child finished with error '1'

```

**Comment by Aaron1011** [comment] 2017-06-20 06:59
I believe that this is fixed with the latest `vte`.

**Comment by jwilm** [comment] 2017-06-20 15:07
Thanks for the reminder @Aaron1011. I published the latest fixes for `vte` and updated Alacritty. Agree that this should be fixed.

**Closed by jwilm** 2017-06-20 15:07 UTC
