### ISSUE TITLE
an error initializing the shaders

### ISSUE THREAD

**Issue by kkhxd520** [jwilm/alacritty#2726] opened 2019-08-18 14:52 UTC
Which operating system does the issue occur on?

linux (Ubuntu 18.04)

If on linux, are you using X11 or Wayland?

X11 and Wayland

error:
There was an error initializing the shaders: Failed compiling shader at /build/alacritty-Ag4TJi/alacritty-0.3.3~1560809133~18.04~fdf1b7c/alacritty_terminal/../res/text.v.glsl: 0:14(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

**Comment by chrisduerr** [comment] 2019-08-18 14:56
Duplicate of #128.

**Closed by chrisduerr** 2019-08-18 14:56 UTC
