### ISSUE TITLE
ime_spot set incorrectly on high DPI displays

### ISSUE THREAD

**Issue by awused** [jwilm/alacritty#2061] opened 2019-02-02 05:58 UTC
Linux (Fedora 29), X11

When using a high DPI display the IME input position isn't scaled by the DPI, so at 150% DPI my IME's preview window is 50% further from the origin on both axes.

![2019-02-01_21-21-55](https://user-images.githubusercontent.com/1551320/52160542-3f30d880-266c-11e9-931d-7f6e44972042.png)

**Comment by chrisduerr** [comment] 2019-02-02 11:48
Duplicate of https://github.com/jwilm/alacritty/issues/2056.

**Closed by chrisduerr** 2019-02-02 11:48 UTC
