### ISSUE TITLE
X11 crashes while holding C-+ to increase font size

### ISSUE THREAD

**Issue by valentjedi** [jwilm/alacritty#898] opened 2017-11-13 06:03 UTC
Hi, I know that alacritty is in early stage of development, but it already looks and works just awesome for the most part.

Which operating system does the issue occur on?
Arch Linux

If on linux, are you using X11 or Wayland?
I hold Ctrl plus to increase my font, and I suppose it goes beyond scaling limit at some point, so X11 crashes entirely forcing me to type `startx` again :)

X11 traceback looks more or less like this:
```
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
```

Since this `10-scale-bitmap-fonts.conf` is not that big, I'll post it here too, just in case. Its value is default one:

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>

<!--
  If font is bitmap, calculate scale factor.
  Note that color bitmap fonts have scalable=true, while
  non-color ones have scalable=false.  Both groups have outline=false.
  -->
<match target="font">
  <test name="outline" compare="eq">
    <bool>false</bool>
  </test>
  <edit name="pixelsizefixupfactor" mode="assign">
    <divide>
      <name target="pattern">pixelsize</name>
      <name target="font"   >pixelsize</name>
    </divide>
  </edit>
</match>
<!--
  For non-scalable bitmap fonts (ie. non-color), skip
  minor scaling if hinting is enabled.
  -->
<match target="font">
  <test name="outline" compare="eq">
    <bool>false</bool>
  </test>
  <test name="scalable" compare="eq">
    <bool>false</bool>
  </test>
  <test name="hinting" compare="eq">
    <bool>true</bool>
  </test>
  <edit name="scalingnotneeded" mode="assign">
    <and>
      <less>
        <name>pixelsizefixupfactor</name>
        <double>1.2</double>
      </less>
      <more>
        <name>pixelsizefixupfactor</name>
        <double>0.8</double>
      </more>
    </and>
  </edit>
</match>
<match target="font">
  <test name="scalingnotneeded" compare="eq">
    <bool>true</bool>
  </test>
  <edit name="pixelsizefixupfactor" mode="assign">
    <double>1.0</double>
  </edit>
</match>
<!--
  If we *are* going to scale, go ahead and do it.
  -->
<match target="font">
  <test name="outline" compare="eq">
    <bool>false</bool>
  </test>
  <test name="pixelsizefixupfactor" compare="not_eq">
    <double>1.0</double>
  </test>
  <edit name="matrix" mode="assign">
    <times>
      <name>matrix</name>
      <matrix>
        <name>pixelsizefixupfactor</name> <double>0</double>
        <double>0</double> <name>pixelsizefixupfactor</name>
       </matrix>
    </times>
  </edit>
  <edit name="size" mode="assign">
    <divide>
      <name>size</name>
      <name>pixelsizefixupfactor</name>
    </divide>
  </edit>
</match>

</fontconfig>
```

I've checked `termite` and `kitty` terminals just in case it's something with my setup and they both work fine. Maybe there is some missing boundary check?

**Comment by maximbaz** [comment] 2017-11-13 18:33
Sounds like an extreme case of #842

**Comment by valentjedi** [comment] 2017-11-14 04:25
Yes, indeed! I even saw something similar to
```
Size(24)
Size(28)
Size(30)
Size(32)
Size(38)
Size(44)
Size(48)
Size(50)
Size(54)
Size(56)
Size(58)
Size(62)
```
part, but cluttered with X11 trace. I've tried to look for a similar issue, but haven't found #842 for some reason.

**Comment by jwilm** [comment] 2017-11-14 17:06
@valentjedi is there a backtrace generated for Alacritty when this happens? Perhaps you can start Alacritty in a tmux session so that the tty survives the X11 crash. Make sure to run with RUST_BACKTRACE=1 to get the full trace.

**Comment by valentjedi** [comment] 2017-11-15 19:11
RUST_BACKTRACE=1 is an environment variable right?

**Comment by Aaron1011** [comment] 2017-11-24 19:19
Duplicate of https://github.com/jwilm/alacritty/issues/842

**Closed** 2017-12-22 21:18 UTC
Labels: B - bug, DS - X11, H - linux
