### ISSUE TITLE
Can't get w3m-img to work with alacritty

### ISSUE THREAD

**Issue by LelouBil** [jwilm/alacritty#1690] opened 2018-10-20 09:03 UTC
Which operating system does the issue occur on?
Ubuntu 18.04
If on linux, are you using X11 or Wayland?
X11

Hey, so I have a little problem, w3m-img doesn't draw images in alacritty.

I realized that while I was trying neofetch with a custom image.

I found this command online that I used to test 
`echo -e '0;1;0;0;200;160;;;;;13931833.jpeg\n4;\n3;' | /usr/lib/w3m/w3mimgdisplay`
It works in urxvt and in termite but not in alacritty.

I also tried using the script provided here https://github.com/jwilm/alacritty/issues/1021 but it didn't work either.

I have also tried to put background_opacity to 1 (since I had it on 0.5) but that didn't help :/

**Comment by chrisduerr** [comment] 2018-10-20 12:45
This is a duplicate of #1021 and should be tracked there.

Note that `w3mimgdisplay` is a huge hack, so I don't think Alacritty will ever spend much time trying to actively support it. Instead tools should be used which use the shell escapes available to render output.

See https://github.com/jwilm/alacritty/issues/910 for one such alternative.

**Closed by chrisduerr** 2018-10-20 12:45 UTC
