### ISSUE TITLE
Window can't restore or minimize after Command+H on macOS

### ISSUE THREAD

**Issue by pass86** [jwilm/alacritty#2934] opened 2019-10-29 12:11 UTC
# System
macOS

# Summary
Window can't restore or minimize after Ctrl+H on macOS

# Behavior
Open Alacritty
Command + H
Click Alacritty icon on Dock, window can't restore
Click the yellow minimize button, window can't minimize

**Comment by chrisduerr** [comment] 2019-10-30 03:47
This is a duplicate of https://github.com/jwilm/alacritty/issues/1465.

**Closed by chrisduerr** 2019-10-30 03:47 UTC
