### ISSUE TITLE
Missing Icon in KDE (breaks Freedesktop specification)

### ISSUE THREAD

**Issue by guygma** [jwilm/alacritty#1591] opened 2018-09-26 17:12 UTC
**Which operating system does the issue occur on?**
Arch Linux

**If on linux, are you using X11 or Wayland?**
KDE on X11

**Problem description**:
In the desktop file, the `Icon` is set to `utilities-terminal` which properly picks up the svg icon to display in the menu and the taskbar. However, the icon displayed in the window decoration (upper left hand corner by default in KDE Plasma) and in the task switcher (pulled up by `Alt-Tab` by default) is just the default X11 icon. This can get a quite confusing when spawning graphics windows from the terminal and trying to switch back to your terminal if they all have the same icon in the task switcher... This was literally *the* thing that kept me going back to kitty terminal, out of pure annoyance.

**Current workaround**:
I can resolve this (and others on KDE could as well) by updating the Window Rules for the application. As of KDE Plasma 5.13 this amounts to right clicking the Menu icon and selecting `More Actions > Special Application Settings`, then under `Appearance & Fixes` settings the Desktop Filename to `alacritty` and choosing `Force` from the drop down. This causes Kwin to pull the icon from the desktop file instead of using the icon Alacritty tells is about (which is *none*). 

**Potential Global Solution**:
The icon to be used for window decorations, task switching, and other Xserver tasks should be made known to the Xserver. If you run `xprop` you can see that the `_NET_WM_ICON` parameter is not set (more specifications on that [here](https://specifications.freedesktop.org/wm-spec/1.3/ar01s05.html).

Rather than re-hashing the background on this part a good overview on the current state is [here](https://www.reddit.com/r/kde/comments/7yuwd6/how_to_make_the_task_switcher_icons_nonpixelated/). The underlying issue is also the root cause for some applications having pixelated icons in the task switcher. From what I have read it sounds like this issue will eventually fade away with Wayland, but we are not quite there yet.

**Comment by E5ten** [comment] 2018-09-30 21:11
I have the same issue in openbox as well, alacritty doesn't seem to set a netwm icon as the issue says.

**Comment by Iambecomeroot** [comment] 2018-11-12 16:48
Reproduced on tint2 and alt-tab menu in openbox.

**Comment by mercster** [comment] 2018-12-19 18:57
I am doing something similar for a shortcut to konsole on my panel that ssh's to a remote server for IRSSI.  I change the Special Windows Settings to change Desktop Filename to 'kopete' (has a nice IRC-looking icon).  This changes the Kwin icon in top left, and the icon in task switcher (Alt-Tab).  But the Task Manager in the panel still shows Konsole's icon, instead of Kopete's.  If anyone has a clue...

**Comment by gabrielsimoes** [comment] 2019-05-24 01:46
The same problem seems to occur with Awesome WM's task bar. All other programs have icons together with the window title, but Alacritty doesn't.

I tried setting an icon manually with [xseticon](http://www.leonerd.org.uk/code/xseticon/), and it worked (albeit ugly), so it seems to be just a matter of setting the icon during runtime.

**Comment by gabrielsimoes** [comment] 2019-05-24 02:32
Actually, I tried compiling the master branch manually, and I found out that my end of the issue was solved since commit 37b66a7. Unless this is not the case with the other people who reported an issue here, I think this could be closed.

**Comment by chrisduerr** [comment] 2019-05-24 18:50
That commit should have closed this issue, it seems like I just missed it. Thanks for pointing it out!

**Closed by chrisduerr** 2019-05-24 18:50 UTC
Labels: DS - X11, H - linux
