### ISSUE TITLE
MacOS Significant Energy Usage

### ISSUE THREAD

**Issue by apiarian** [jwilm/alacritty#1648] opened 2018-10-12 22:06 UTC
Which operating system does the issue occur on?

MacOS

Whenever I'm on battery power on my MacBook, it's claiming that Alacritty is one of the few apps that are "Using Significant Energy" in the battery status bar menu. Is this normal and inevitable? It would seem that a terminal wouldn't need to use much of the GPU to be graphically accelerated? Is the GPU an all-or-nothing sort of thing, even if it doesn't have to render 60 unique frames every second?

**Comment by apiarian** [comment] 2018-10-15 10:09
Yes, there's a Built-In Intel HD Graphics 4000 and a PCIe NVIDIA GeForce GT 650 M on my mac. Anything I can do to help test or benchmark?

**Comment by apiarian** [comment] 2018-10-17 10:10
I may be able to close all but the minimal required programs on my computer and see how it drains the battery with alacritty running and without. Anything I should try running in the terminal while I do it? Perhaps the test without alacritty should be run with something like Terminal.app in the same tmux session? I can do it this weekend, let me know how best to set up the experiment.

**Comment by chrisduerr** [comment] 2018-10-17 18:30
@apiarian A comparison to the other terminal emulators would definitely be useful. However you'll have to make sure that the comparison is fair and the same output is processed.

So rather than running one benchmark until it's done, you should run the test for a fixed amount of time and make sure all benchmarks finish on both iTerm/Terminal.app and Alacritty. Otherwise iTerm/Terminal.app might show less battery usage, simply because they haven't processed the same amount of data as Alacritty.

Benchmarks which should put the terminal emulator under a bit of load can be found in https://github.com/jwilm/vtebench. However this is a pretty unlikely scenario for real-world usecases. So you might want to run some less straining tests too.

Also on macOS it should make a big difference if you're running master or #1403. Since the latest glutin update introduces some significant changes. It might be possible to test both, or you can pick whichever one you're more interested in.

Any kind of data on this topic would be interesting. So thanks for looking into this!

**Comment by jansol** [comment] 2018-12-04 09:12
Seems to be fixed now? Installed Alacritty from homebrew and it sticks to the iGPU as it should. Do note that the fix IIRC only works when launched as a .app bundle, since it relies on the bundle's `Info.plist`.

**Comment by luchenyuxx** [comment] 2018-12-04 09:18
Seems to be fixed.

**Comment by chrisduerr** [comment] 2018-12-04 15:58
Thanks for the heads-up @luchenyuxx. Closing this as resolved, probably by the glutin PR.

If it should still be present, please let me know and I'll re-open.

**Closed by chrisduerr** 2018-12-04 15:58 UTC

**Comment by starcraft66** [comment] 2019-04-20 17:10
@chrisduerr It seems like there is a regression on 0.3.0 causing this to happen again on macOS. After upgrading to Alacritty 0.3.0 (downloaded from the releases page), launching the app immediately causes my macbook to switch from the low power Intel graphics card to the power-hungry AMD card. The app happily ran on the Intel card before upgrading to 0.3.0.

**Comment by chrisduerr** [comment] 2019-04-20 18:27
This is intentional since there has been a bug in the macOS drivers. This will likely be fixed in the next release once Apple has patched this issue.

**Comment by starcraft66** [comment] 2019-04-20 18:41
Ah okay thanks for letting me know. Is there an issue tracking the status of this apple bug?

**Comment by chrisduerr** [comment] 2019-04-20 18:47
There is: https://github.com/jwilm/alacritty/issues/2221.
