### ISSUE TITLE
Alacritty doesn't recognize input when in the process of printing lots of stuff

### ISSUE THREAD

**Issue by rbtying** [jwilm/alacritty#69] opened 2017-01-05 23:09 UTC
repro:

open alacritty and type the command `yes`

then, attempt to Ctrl-C or type other characters in.

Expected behavior:
Ctrl-C immediately ends the stream of `y`s being printed out.
Other characters are echoed to screen

(aka input thread should always interrupt drawing thread)

Observed behavior:
holding Ctrl-C for a long time eventually kills `yes`.

**Comment by jwilm** [comment] 2017-01-05 23:13
This seems to work as expected for me. Which shell are you using and which platform are you on?

**Comment by gmjosack** [comment] 2017-01-05 23:40
I also have this problem. I'm using `/bin/bash` on Ubuntu 14.04

**Comment by rbtying** [comment] 2017-01-06 00:21
I was using zsh on Ubuntu 16.04

**Comment by jwilm** [comment] 2017-01-06 00:21
Sounds like I need to try this when I'm back on Linux; thanks for the reports!

**Comment by basile-henry** [comment] 2017-01-06 00:24
`Ctrl-C` on the stream of `y`s works immediately for me. I tried with both bash and zsh on Linux Mint 17.3

**Comment by rbtying** [comment] 2017-01-06 00:27
I can't reproduce the `^C` behavior on OSX, but the expected character-echo doesn't seem to happen either? (or it's just scrolling by too fast, I can't tell)

**Comment by aurabindo** [comment] 2017-01-07 11:25
I can reproduce this bug on Archlinux. And it never recognized the input. yes kept running

**Comment by marceloandrader** [comment] 2017-02-21 21:33
with the yes command Ctrl + C works on my linux with zsh, but I do have problems like that when doing something like `cat /someverylargefile` or `rg find /big/project`

**Comment by jwilm** [comment] 2017-02-21 21:40
@marceloandrader how recent is your build? I thought we had fixed this bug.

**Comment by marceloandrader** [comment] 2017-02-21 23:16
@jwilm nvm I did a build today and haven't tested that, just had it on my mind, I just tested and is working with my latest build. thnx

**Comment by jwilm** [comment] 2017-02-21 23:17
@marceloandrader Great!

Closing this issue since it's been resolved.

**Closed by jwilm** 2017-02-21 23:17 UTC
