### ISSUE TITLE
Make the window decorations nicer

### ISSUE THREAD

**Issue by marekdedic** [jwilm/alacritty#2867] opened 2019-10-10 11:24 UTC
Given that Gnome on Wayland probably isn't getting server-side-decorations (https://gitlab.gnome.org/GNOME/mutter/issues/217, :man_facepalming:), the window decorations provided by Alacritty should be nicer - I don't have any particular style in mind, but I think they could use some work.

To be clear - the current ones are functionally perfectly OK, I'm talking about appearance only.

Spin-off from #2860

**Comment by kchibisov** [comment] 2019-10-10 11:29
@marekdedic Would you mind to test #2047? It introduces one more option for Wayland to change your decorations.

**Comment by chrisduerr** [comment] 2019-10-10 11:36
> he window decorations provided by Alacritty should be nicer

This seems extremely subjective. And I am strongly against favoring any specific DEs. CSDs should look just as well for KDE as they should for GNOME or Sway.

I personally don't see how the current look of the decorations would be seen as a problem, however we will be able to style them according to the terminal theme in the future (this is tracked in https://github.com/jwilm/alacritty/pull/2047, so please close this issue if that addresses your problem).

**Comment by marekdedic** [comment] 2019-10-10 16:23
> This seems extremely subjective. And I am strongly against favoring any specific DEs. CSDs should look just as well for KDE as they should for GNOME or Sway.

I agree with all of that completely. And I also agree the current look is not a problem - it works, that's the main thing. But I cannot say it is *nice* from an "aesthetic" point of view - that's what I'm trying to get at...

#2047 goes a long way - that was actually one of the things I had in mind, it just didn't turn up when I was searching for related issues. Other things that I had in mind was a some better design for the buttons, let the user choose to put them on the left or on the right or hide some of the buttons.

**Comment by chrisduerr** [comment] 2019-10-10 17:43
> But I cannot say it is nice from an "aesthetic" point of view - that's what I'm trying to get at...

That's purely preference.

> Other things that I had in mind was a some better design for the buttons, let the user choose to put them on the left or on the right or hide some of the buttons.

If you do not like the way CSDs look, the usual approach should be to use SSDs instead. Our job is to offer all possible window actions and make it look uniform with the rest of Alacritty and that's mostly it.

I don't think there's anything wrong with the buttons once the Wayland theme rework comes through, so I'd recommend staying tuned for that.

Removing certain buttons or moving them to the other side of the window are both things that's traditionally the purpose of the SSDs. These are changes with the goal of fitting in with the rest of the system, not with the Application itself. I don't see Alacritty ever exposing this functionality for Wayland CSDs.

So I'll mark this issue as duplicate of #2092. I don't think I want to take any measures beyond that.

**Closed by chrisduerr** 2019-10-10 17:43 UTC
Labels: DS - Wayland, H - linux

**Comment by marekdedic** [comment] 2019-10-10 17:55
So the user gets caught in the cross-fire of neither the application nor the DE wanting to support proper decorations. :disappointed:

**Comment by chrisduerr** [comment] 2019-10-10 18:07
Of course we'll try to make them look nicely with Alacritty, but we simply don't have the capacity or capability to do things a display server should do. As many, many people have stated in the issue of the gnome bug, this just isn't something that can be nicely fixed in every single application without spending completely bogus amount of resources to work around an issue caused by a decision like this.

While GNOME might be nice for a lot of users, the only recommendation I can make is to pick something that fits your needs. If it's not that big of a deal that's fine, however if this bothers you, Alacritty will definitely not be the only one affected and you're likely better off picking software that fits your needs.

**Comment by nixpulvis** [comment] 2019-10-10 18:59
@marekdedic I'm not quite sure I'd call this a "cross-fire" between Alacritty and the DE, since Gnome (in this case) is really just imposing itself upon application developers. It's not like Alacritty just has a different idea about how CSDs should work, instead it's a fundamental issue with CSDs in general. AFAICT, CSDs have been a [wildly unsuccessful UI design idea](https://askubuntu.com/questions/961161/how-do-i-disable-client-side-decoration-globally-in-gnome), which puts the onus on application developers to maintain a consistent aesthetic, thus ensuring it's not possible, since all application developers will not agree about these things.

Depending what you consider "proper", #2092 will get you closer perhaps, but without SSDs there's just no way applications can make things consistent (that's the whole point of SSDs). CSDs are potentially "cool" I suppose, since they allow greater flexibility in the design, but if your goal is consistency it should be obvious that, in geneal, they will be worse in that respect.

**Comment by marekdedic** [comment] 2019-10-16 10:01
Maybe a bit too strong of a wording to call it "cross-fire", but the fact that Gnome developers push CSDs so hard while everybody else thinks it's a terrible idea doesn't change the fact that in the end it's the user who gets the short end of the stick.

Anyway, I think this discussion got way to fixated on Gnome and its idiosyncrasies - my original intent was to ope up a debate about making the built-in decorations nicer (however subjective that may be), not about making them fit in with Gnome.

**Comment by ripefig** [comment] 2020-05-10 13:00
Non-native CSD obviously looks terrible, but it's not the app developer's job to make their app look native across multiple desktops.

It looks like a couple of Gnome devs have seen sense and are working on a CSD library to help applications draw their decorations. Development is proceeding very slowly and it may be too little too late but when, or rather IF EVER, this library is ready to use it would be something to consider.

**Comment by kchibisov** [comment] 2020-05-10 13:04
Or someone could just use SSD...
