### ISSUE TITLE
Certain CSI sequences don't behave like expected

### ISSUE THREAD

**Issue by miba072** [jwilm/alacritty#2652] opened 2019-07-17 22:00 UTC
**Arch Linux**
**Wayland**
**alacritty 0.3.3**

Some private CSI sequences don't behave like in other major terminal emulators (lxterminal, etc.).

From [An issue encountered with ble.sh](https://github.com/akinomyoga/ble.sh/issues/28)

>Thank you for the information! I took a glance at the codes of alacritty. The DA1 response is issued here (alacritty/mod.rs) which is called from here (alacritty/ansi.rs). It seems that the alacritty doesn't check intermediate bytes of CSI sequences and just sees the last byte to determine the control function associated with the CSI sequence. So alacritty cannot distinguish DA2 request (CSI > c) and even DA3 request (CSI = c) from DA / DA1 request (CSI c).

>>maybe it is a bug in alacritty not responding to the escape sequence properly, maybe a bug report should be made to them too?

>I'm not sure if it should be regarded as a "bug" of alacritty because there is no formal standard for these "private CSI sequences". DA is defined in so-called "ANSI Standard" (ANSI X3.64, ECMA-48 and ISO/IEC 6429), but the CSI sequences that starts with <, =, >, ? are designated as "private sequences" and the meaning can be defined by implementations. In this sense, if it's the design of alacritty, it's not a bug.

**Comment by chrisduerr** [comment] 2019-07-18 20:04
I'm pretty sure this is a duplicate of https://github.com/jwilm/alacritty/issues/2171.

It's definitely planned for Alacritty to follow the lead of other terminal emulators here and do things properly. However I haven't yet found the time to appropriately scope it out and check exactly what is required to make this work. It's definitely something I'd like to get done reasonably soon though.

**Closed by chrisduerr** 2019-07-18 20:04 UTC
