### ISSUE TITLE
can't clear window when using git bash

### ISSUE THREAD

**Issue by keshavchand** [jwilm/alacritty#2610] opened 2019-07-02 13:37 UTC
Which operating system does the issue occur on?
Windows 10 64bit

alacritty 0.3.3 (cc3e4d3) 

clear command in git bash cant clear the screen
![Alacritty2019-07-0218-56-49](https://user-images.githubusercontent.com/22835817/60516530-97dbce80-9cfb-11e9-8c21-ee446065b8ed.gif)

no such problem in powershell
![WindowsPowerShell2019-07-0219](https://user-images.githubusercontent.com/22835817/60517002-847d3300-9cfc-11e9-89fa-957016d2652b.gif)

**Comment by chrisduerr** [comment] 2019-07-02 15:34
That looks like an issue with git bash to me, especially if powershell works. Could you try running `printf '\e[2J\e[H\e[3J'` in git bash?

**Comment by keshavchand** [comment] 2019-07-02 17:07
Interestingly that worked. Thanks for the help.

**Comment by chrisduerr** [comment] 2019-07-02 17:32
That sounds to me like git bash isn't sending the correct escape sequences. You do not have any special configuration, right? IIRC on Windows 7 everything worked properly with the git bash.

**Comment by keshavchand** [comment] 2019-07-02 18:29
Git bash's clear sequence:
00000000: 1b5b 481b 5b32 4a1b 5b33 4a              .[H.[2J.[3J

And nano and vim looks something like this:
![alac_nano](https://user-images.githubusercontent.com/22835817/60536704-865aec80-9d24-11e9-81ac-bfc21868eb48.jpg)

![alac_vim](https://user-images.githubusercontent.com/22835817/60536692-7fcc7500-9d24-11e9-940d-61aa79a8a072.jpg)

Results are same when ran from git bash or windows cmd. I guess the problem is really with git bash's programs.

**Comment by chrisduerr** [comment] 2019-07-02 18:35
Sounds like this is a duplicate of https://github.com/jwilm/alacritty/issues/1967, but I don't think there's much Alacritty can do.

**Closed by chrisduerr** 2019-07-02 18:35 UTC
Labels: A - needs repro
