### ISSUE TITLE
First character doubled when pressing tab to autocomplete a command

### ISSUE THREAD

**Issue by marekbrainhub** [jwilm/alacritty#1800] opened 2018-11-15 07:52 UTC
Which operating system does the issue occur on?
macOS Mojave

![jqy9q0xbnu](https://user-images.githubusercontent.com/40170732/48537984-7d133180-e8b3-11e8-8f61-4e5b9902b0d5.gif)

This seems to occur only in zsh. Does not happen when the command is on a separate line (for example when in a git repository). Does not happen in other terminal emulators.

**Comment by chrisduerr** [comment] 2018-11-15 09:32
Is this only a problem with Alacritty, or can this be reproduced in iTerm/Terminal.app?

**Comment by marekbrainhub** [comment] 2018-11-15 10:36
It does not happen in other terminal emulators (iTerm2, Terminal, Hyper).

**Comment by chrisduerr** [comment] 2018-11-15 10:42
What happens if you reset your prompt to be completely empty, or just a simple `$`? This might be a zero-width character issue.

**Comment by chrisduerr** [comment] 2018-11-15 12:30
Then this is likely a duplicate of #1318. Currently Alacritty incorrectly renders zero-width characters with a width of 1 instead. Since terminal programs often only clear what needs to be cleared and the cell shouldn't contain anything, it's not updated.

**Closed by chrisduerr** 2018-11-15 12:30 UTC
Labels: H - macos, S - input
