### ISSUE TITLE
Extremely high memory usage on alacritty 0.2.0

### ISSUE THREAD

**Issue by ishanjain28** [jwilm/alacritty#1555] opened 2018-09-18 12:15 UTC
Which operating system does the issue occur on?
Arch linux 
Linux y50 4.18.7-arch1-1-ARCH #1 SMP PREEMPT Sun Sep 9 11:27:58 UTC 2018 x86_64 GNU/Linux

If on linux, are you using X11 or Wayland?
X11

Shell 
ZSH

Alacritty is taking up 530MB RAM in idle mode. I start alacritty and it jumps to 530+ MB ram. There is absolutely nothing running in terminal. 

![](https://imgur.com/download/9HW2WqV)

**Comment by haarp** [comment] 2018-09-18 13:02
Did you set a large value for scrolling->history? It seems Alacritty allocates a static buffer that eats quite a lot of RAM.

**Comment by ishanjain28** [comment] 2018-09-18 13:08
@haarp looks like that is the problem. I had set it to 100000 which was causing high memory usage. 

I set it to 10000 and it's still taking up 100mb ram.

**Comment by NickeZ** [comment] 2018-09-18 13:41
I think that it is good that it pre-allocates the required amount. What would be the benefits of allocating on-demand?

**Comment by haarp** [comment] 2018-09-18 14:11
> What would be the benefits of allocating on-demand?

Not occupying memory that isn't needed. How often does one actually use all scrollback lines? Better keep that unused memoery around for disk caching and other useful things.

**Comment by ishanjain28** [comment] 2018-09-18 14:12
@NickeZ Often my terminal sessions are short lived, I probably won't be doing anything that'll print 100000 lines to console. In these cases, the 500mb taken by alacritty is a waste of resources. 

But setting history to 100000 is nice to have just in case I do end up doing something that printed that many lines and I need to go back. Setting a lower limit will cause alacritty to delete older lines and I can not go back. 

I think allocating/freeing RAM like Vectors would be nice. As in, Start with some initial amount, Allocate double of that when more memory is needed and free when 3/4 is unused. 

And I am sorry I searched the issue tracker for a bit and didn't found any related issues so I created a new one.

**Comment by NickeZ** [comment] 2018-09-18 14:18
I would be afraid of the OOM killer killing random processes simply because I launched a verbose program if Alacritty was allocating on-demand. But I see where you come from.

**Comment by NickeZ** [comment] 2018-09-18 14:42
@ishanjain28 There is some discussion about how much Alacritty allocates per line and why in the other issue: #1236

**Comment by chrisduerr** [comment] 2018-09-18 15:54
Closing as a duplicate of #1236.

**Closed by chrisduerr** 2018-09-18 15:54 UTC
