### ISSUE TITLE
Terminal Resize Issue on External Monitor

### ISSUE THREAD

**Issue by discreet** [jwilm/alacritty#1997] opened 2019-01-10 00:13 UTC
Which operating system does the issue occur on?
Mac OS X High Sierra

Using alacritty version 0.2.5 compiled locally

If I open alacritty on my MacBook Pro display everything is rendered fine. When I move the terminal window to my external display (HP Envy 32 2560x1440 over DisplayPort) all of the font turn unrecognizably small and half of the terminal window is unused. If I open alacritty on my external display the same thing happens and when I move the terminal window to my MacBook Pro display everything returns to normal. I have attached the logs and screenshots below.

```
❯ alacritty -vvv
Created log file at "/var/folders/d2/57lkt7fs5958vjrfd91sk0pdm8myfb/T/Alacritty-23967.log"
[2019-01-09 19:10] [INFO] Welcome to Alacritty
[2019-01-09 19:10] [INFO] Configuration loaded from "/Users/mya561/.config/alacritty/alacritty.yml"
[2019-01-09 19:10] [INFO] Device pixel ratio: 1
[2019-01-09 19:10] [INFO] Width: 1024, Height: 768
[2019-01-09 19:10] [INFO] Initializing glyph cache...
[2019-01-09 19:10] [INFO] ... finished initializing glyph cache in 0.081317607s
[2019-01-09 19:10] [INFO] Width: 564, Height: 340
[2019-01-09 19:10] [INFO] Cell Size: (7 x 14)
[2019-01-09 19:10] [INFO] Padding: (2 x 2)
[2019-01-09 19:10] [INFO] PTY Dimensions: Line(24) x Column(80)
[2019-01-09 19:10] [TRACE] [/Users/mya561/.cargo/git/checkouts/alacritty-de74975f496aa2c0/8570ee0/src/lib.rs:81] Scaling RGB by 0.66 from Rgb { r: 234, g: 234, b: 234 } to Rgb { r: 154, g: 154, b: 154 }
[2019-01-09 19:10] [TRACE] [/Users/mya561/.cargo/git/checkouts/alacritty-de74975f496aa2c0/8570ee0/src/term/color.rs:74] Using config-provided dim colors
[2019-01-09 19:10] [TRACE] [/Users/mya561/.cargo/git/checkouts/alacritty-de74975f496aa2c0/8570ee0/src/lib.rs:81] Scaling RGB by 0.66 from Rgb { r: 234, g: 234, b: 234 } to Rgb { r: 154, g: 154, b: 154 }
[2019-01-09 19:10] [TRACE] [/Users/mya561/.cargo/git/checkouts/alacritty-de74975f496aa2c0/8570ee0/src/term/color.rs:74] Using config-provided dim colors
[2019-01-09 19:10] [INFO] Initialisation complete
[2019-01-09 19:10] [INFO] Font size changed to Size(24) with DPR of 1
[2019-01-09 19:10] [DEBUG] Resizing terminal
[2019-01-09 19:10] [DEBUG] Term::resize dimensions unchanged
[2019-01-09 19:10] [INFO] Width: 564, Height: 340
[2019-01-09 19:10] [TRACE] [/Users/mya561/.cargo/git/checkouts/alacritty-de74975f496aa2c0/8570ee0/src/term/mod.rs:1931] Setting attribute: Foreground(Named(Green))
[2019-01-09 19:10] [TRACE] [/Users/mya561/.cargo/git/checkouts/alacritty-de74975f496aa2c0/8570ee0/src/term/mod.rs:1931] Setting attribute: Reset
[2019-01-09 19:10] [TRACE] [/Users/mya561/.cargo/git/checkouts/alacritty-de74975f496aa2c0/8570ee0/src/term/mod.rs:1931] Setting attribute: Foreground(Named(Cyan))
[2019-01-09 19:10] [TRACE] [/Users/mya561/.cargo/git/checkouts/alacritty-de74975f496aa2c0/8570ee0/src/term/mod.rs:1931] Setting attribute: Reset
[2019-01-09 19:10] [TRACE] [/Users/mya561/.cargo/git/checkouts/alacritty-de74975f496aa2c0/8570ee0/src/term/mod.rs:1600] Carriage return
[2019-01-09 19:10] [TRACE] [/Users/mya561/.cargo/git/checkouts/alacritty-de74975f496aa2c0/8570ee0/src/term/mod.rs:1600] Carriage return
[2019-01-09 19:10] [TRACE] [/Users/mya561/.cargo/git/checkouts/alacritty-de74975f496aa2c0/8570ee0/src/term/mod.rs:1608] Linefeed

Moving to MacBook Pro Display

[2019-01-09 19:11] [INFO] Font size changed to Size(24) with DPR of 2
[2019-01-09 19:11] [DEBUG] Resizing terminal
[2019-01-09 19:11] [DEBUG] Term::resize dimensions unchanged
[2019-01-09 19:11] [INFO] Width: 1128, Height: 680
[2019-01-09 19:11] [TRACE] [/Users/mya561/.cargo/git/checkouts/alacritty-de74975f496aa2c0/8570ee0/src/term/mod.rs:1600] Carriage return
[2019-01-09 19:11] [TRACE] [/Users/mya561/.cargo/git/checkouts/alacritty-de74975f496aa2c0/8570ee0/src/term/mod.rs:1787] Clearing line: Right

Moving Back to External Display

[2019-01-09 19:11] [INFO] Font size changed to Size(24) with DPR of 1
[2019-01-09 19:11] [DEBUG] Resizing terminal
[2019-01-09 19:11] [DEBUG] Term::resize dimensions unchanged
[2019-01-09 19:11] [INFO] Width: 564, Height: 340
[2019-01-09 19:11] [TRACE] [/Users/mya561/.cargo/git/checkouts/alacritty-de74975f496aa2c0/8570ee0/src/term/mod.rs:1600] Carriage return
[2019-01-09 19:11] [TRACE] [/Users/mya561/.cargo/git/checkouts/alacritty-de74975f496aa2c0/8570ee0/src/term/mod.rs:1787] Clearing line: Right
```
External Display:
![screen shot 2019-01-09 at 7 12 18 pm](https://user-images.githubusercontent.com/5614960/50937621-92838280-1442-11e9-9674-6f227a74992c.png)

MacBook Pro Display:
<img width="568" alt="screen shot 2019-01-09 at 7 12 32 pm" src="https://user-images.githubusercontent.com/5614960/50937629-97e0cd00-1442-11e9-82fd-3bb63ffb0811.png">

**Comment by chrisduerr** [comment] 2019-01-10 00:30
This is a duplicate of https://github.com/jwilm/alacritty/issues/1631.

It would be helpful to know if setting `window.decorations` to `full` or `none` resolves this. That seems to be the cause of the issue based on the feedback in #1631.

**Closed by chrisduerr** 2019-01-10 00:30 UTC

**Comment by discreet** [comment] 2019-01-10 01:55
Thanks for the update. I will follow that issue. Unfortunately setting decorations in the config file to full of mine doesn't seem to change the behavior.
