### ISSUE TITLE
Alacritty causing 1-2 mins of busy cursor on i3 desktop, and extreme i3 performance issues

### ISSUE THREAD

**Issue by RonanZer0** [jwilm/alacritty#868] opened 2017-10-26 03:30 UTC
Which operating system does the issue occur on?
Arch Linux

If on linux, are you using X11 or Wayland?
X11

Version: current version in arch user repository, unsure how to check version number

Opening an Alacritty instance causes the mouse to be stuck on "busy" instead of the normal cursor, only when the mouse is hovering over the i3wm desktop. Not the biggest of deals, but can be distracting. This effect seems to usually go away after *approximately*  1.5-2 to minutes, but it persists even after the terminal is closed. Running `i3 restart` resets the cursor to normal.

Alacritty also seems to cause performance issues specifically with i3 after long periods of time and many terminals opened and closed. The longer my session lasts and the more Alacritty terminals I open (and close), the worse i3 performance gets (e.g. switching between workspaces becomes extremely slow) while application performance is fine. It eventually becomes unusuable. These issues *only* happen when I'm using Alacritty.

**Comment by cideM** [comment] 2017-10-28 09:46
Are you sure that's because of alacritty? I can reproduce the issue but then again if I have the busy cursor super often in i3, see https://www.google.de/search?q=i3+busy+cursor&oq=i3+busy+cursor&aqs=chrome.0.0j69i61j69i57.1482j0j7&sourceid=chrome&ie=UTF-8

**Comment by DuBistKomisch** [comment] 2017-12-23 01:28
https://wiki.archlinux.org/index.php/I3#Mouse_cursor_remains_in_waiting_mode

**Comment by jwilm** [comment] 2017-12-23 01:32
Closing this. I haven't experienced anything like this myself, and it sounds like it's unlikely due to Alacritty. Feel free to reopen if there is evidence otherwise.

**Closed by jwilm** 2017-12-23 01:32 UTC

**Comment by AndrewVos** [comment] 2018-08-15 08:08
This is actually due to alacritty not sending some sort of "ready" signal or whatever.

https://faq.i3wm.org/question/118/mouse-cursor-remains-waiting-after-closing-last-tile.1.html

A workaround is to do something like:

```
bindsym $mod+Return split h; exec --no-startup-id alacritty
```

That will get rid of the busy pointer.

**Comment by eyadsibai** [comment] 2020-02-10 09:07
I am experiencing the same thing with alacritty. I understand that adding --no-startup-id is a workaround, but would be nice to have a solution

**Comment by DiggsAsura** [comment] 2022-02-18 20:28
I experience the same thing on i3, xorg, debian 11

**Comment by vdudnikov** [comment] 2024-10-19 22:01
> I experience the same thing on i3, xorg, debian 11
Try find alacritty .desktop (something like /usr/share/applications/Alacritty.desktop) and turn off StartupNotify parameter. Helped me on x11.
