### ISSUE TITLE
macOS cmd+h doesn't hide window and change active app

### ISSUE THREAD

**Issue by dfischer** [jwilm/alacritty#2813] opened 2019-09-20 14:40 UTC
Which operating system does the issue occur on?
macOS 

When pressing cmd+h it still stays active... (window hides, but alacrity is active app).

**Comment by chrisduerr** [comment] 2019-09-20 18:41
In your title you say that it doesn't hide the window, however in your description you mention it does. Could you clarify this?

I think this is a duplicate of https://github.com/jwilm/alacritty/issues/1465, does that sound right?

**Comment by dfischer** [comment] 2019-09-20 20:46
Sorry, it hides the alacrity window but it doesn't make the application inactive, so if I continued to type or click it would still go into the alacrity window and not the most immediate window that was last active before it (cmd+tab).

**Comment by dfischer** [comment] 2019-09-20 20:46
Yes it's similar to #1465 however I can regain focus by cmd+tabbing back into it after making another application active by clicking on it.

**Comment by chrisduerr** [comment] 2019-09-21 22:31
I think this should be resolved when #1465 is fixed. So we can just use that issue to track this.

**Closed by chrisduerr** 2019-09-21 22:31 UTC
Labels: A - deps, H - macos, S - winit/glutin
