### ISSUE TITLE
It is not possible to select text with the mouse in Tmux with horizontal splits

### ISSUE THREAD

**Issue by dgmora** [jwilm/alacritty#1511] opened 2018-08-17 20:10 UTC
Related to the latest comments in #146

_Which operating system does the issue occur on?_ 
Mac OS High Sierra 10.13.6
Tmux 2.7

If I have a horizontal split and I want to select text with the mouse, I do it pressing shift. That works fine, but if there's a split, you will select text for the whole terminal.

<img width="1440" alt="screen shot 2018-08-17 at 22 09 34" src="https://user-images.githubusercontent.com/3609616/44286693-456ffb80-a26a-11e8-840f-3a2103506df1.png">

With iterm2 + tmux it is possible to select a square by holding Shift and alt (in mac). I have been looking around and I am not sure if this works out of the box or if it's something I added to my configuration. 

If it could be relevant, that's part of my `tmux.conf`
```
# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe "reattach-to-user-namespace pbcopy"
setw -g mode-keys vi
setw -g mouse on

set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tpm'                   # manage plugins
set -g @plugin 'tmux-plugins/tmux-sensible'         # Better defaults than the defaults 
set -g @plugin 'tmux-plugins/tmux-pain-control'     # standard tmux pane navigation bindings
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-sessionist'       # easy tmux session
set -g @plugin 'tmux-plugins/tmux-yank'             # Copy tmux > clipboard
set -g @plugin 'tmux-plugins/tmux-copycat'         # Predefined searches.

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

**Comment by chrisduerr** [comment] 2018-08-17 20:18
Hey, thanks for opening this issue!

Block selection is currently tracked in #526, so this is a duplicate of this issue and your best bet is to watch #526 for updates.

I've implemented a very ugly version of block selection in this PR already: #1398, this still needs some work and some design decisions have to be made, however it's definitely something I'd love to see in Alacritty!

Note that this is unrelated to tmux, so once rectangle/block selection works in the Alacritty, it should work everywhere!

**Closed by chrisduerr** 2018-08-17 20:18 UTC

**Comment by deft01** [comment] 2023-01-13 20:05
Hello, in my opinion this issue is not fixed.
This is not fixed by the block selection implementation.

When you create a split with tmux in alacritty, you still cannot select a bash line.
Maybe this is issue is not possible to solve.

The following example has no problem, you can select multiple line with mouse very easily with one drag : 
![image](https://user-images.githubusercontent.com/10063471/212409113-066656e5-2b9f-477b-a846-aee393a4fb28.png)

Now comes the nightmare, if you are using multiple panes : 
![image](https://user-images.githubusercontent.com/10063471/212409324-e30f0a1c-d973-4c59-9387-c0457d67604f.png)

I can't make a clean multiline selection easily because if I use the block selection it still wont be ok, I will have to remove the  
`user@mymachine:/home/myuser/:~$ ` characters like so : 
![image](https://user-images.githubusercontent.com/10063471/212409679-7adb3c11-2f15-4338-94c8-1ab7c9fc2d4c.png)

**Comment by kchibisov** [comment] 2023-01-13 21:02
Use mouse mode in tmux and delegate the selection to the terminal controlling the grid in that case(tmux). Alacritty has very little to do with that.

**Comment by deft01** [comment] 2023-01-17 08:47
Thanks, I think you idea is my solution. My problem now is that I don't know how I can deactivate the mouse selection in alacritty since it conflict with tmux selection (same shortcut).

**Comment by deft01** [comment] 2023-01-17 09:44
Ok i found out I was using tmux the wrong way.
You have to use the tmux copy-mode instead of the traditional `Shift + mouse`.

See my erratum here for more details https://github.com/alacritty/alacritty/issues/420#issuecomment-1385105036
