### ISSUE TITLE
alt+< and alt+> doesn't work correctly

### ISSUE THREAD

**Issue by kpcyrd** [jwilm/alacritty#1321] opened 2018-05-21 01:22 UTC
I'm trying to migrate from xfce4-terminal to alacritty for weechat, I've quickly noticed that `alt+<` does not work, which is used in weechat to navigate to the previous buffer. `alt+>` is working correctly (which navigates forward in the buffer history), but stops working when alt+shift are not explicitly released.

I use this feature heavily, in xfce4-terminal+bash it selects the oldest command of the history, in alacritty it's the same as just pressing `<`.

For `alt+>` it seems to implicitly release the modifier keys on sequential key presses, so I have to release alt+shift manually and press all 3 keys again if I want to step forward in history multiple times.

### Version
24e8a19e7d981fbc8853891ad4a17a9de2ac36bd

### Which operating system does the issue occur on?
Archlinux

### If on linux, are you using X11 or Wayland?
X11

**Comment by chrisduerr** [comment] 2018-05-21 10:45
Are you running the default linux configuration file? This works on my machine without any issues.

**Comment by kpcyrd** [comment] 2018-05-21 15:27
I've retested with an US keyboard layout and I can indeed navigate backwards there, it seems the fact that I don't have to press shift is causing the issue.

**Comment by chrisduerr** [comment] 2018-05-21 15:49
Oh sorry, I thought you mean right/left arrow key not the actualy `<` and `>` symbols. I can indeed reproduce that this doesn't work with my layout either. IIRC alacritty might currently not report modifiers on repeated key presses, so this probably is a valid bug, thanks for the report.

**Comment by chrisduerr** [comment] 2018-05-21 15:50
This is a duplicate of #1062. Should be resolved when that is resolved.

**Closed by chrisduerr** 2018-05-21 15:50 UTC
