### ISSUE TITLE
cargo build very slow 

### ISSUE THREAD

**Issue by jackiilong** [jwilm/alacritty#1391] opened 2018-06-22 11:59 UTC
macos

**Comment by chrisduerr** [comment] 2018-06-22 12:14
Hi, Alacritty has a lot of dependencies so it is only natural that the build process takes a while. As far as I know there is no significant slow-down caused by the Alacritty project itself.

If you're compiling Alacritty master you can get a bit of speedup by disabling `lto` in the `Cargo.toml`, other than that there aren't a lot of options.

**Comment by nixpulvis** [comment] 2018-07-02 04:17
Relevant tracking issue in Rust, rust-lang/rust#48547. This is a known area of improvement for the compiler. I doubt there's much we should be bothered to do at this point to optimize for compile times.

**Comment by chrisduerr** [comment] 2018-07-02 14:46
Closing this since it doesn't seem to be an issue of Alacritty and the `lto` fix I've mentioned should offer at least some improvements.

**Closed** 2018-07-03 15:29 UTC
