### ISSUE TITLE
Copying From Firefox and Pasting into Alacritty Doesn't Work When Using Wayland as the GDK Backend

### ISSUE THREAD

**Issue by ode79** [jwilm/alacritty#2097] opened 2019-02-11 02:58 UTC
Which operating system does the issue occur on?
Linux
If on Linux, are you using X11 or Wayland?
Wayland (using Sway 1.0-rc1)
Firefox Version: 65.0
Alacritty Versions tested: 0.2.7 and 0.2.8

If I start Firefox normally (running under XWayland [tested with xeyes]), copying from Firefox and pasting into Alacritty seems to work fine.
However if I start Firefox with `$ GDK_BACKEND=wayland firefox &` pasting then fails with the error
```
$ Error: target STRING not available
Error:: command not found
```

**Comment by chrisduerr** [comment] 2019-02-11 15:44
Duplicate of #5.

**Closed by chrisduerr** 2019-02-11 15:44 UTC
