### ISSUE TITLE
GLSL / Intel Integrated Graphics / Shader compile fail

### ISSUE THREAD

**Issue by nantronic2** [jwilm/alacritty#530] opened 2017-04-30 22:06 UTC
I installed Alacritty onto my Arch machine through the pacman/yaourt manager and receive an error when I try to run Alacritty:

> There was an error initializing the shaders: failed compiling shader: 0:14(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

I couldn't find a relevant ticket on this Alacritty Git; but I found a corresponding error on a different Git: https://github.com/c42f/displaz/issues/89

I'm not an expert of any sort but I expect (from the displaz git ticket) that the error I'm receiving is from the integrated Intel graphics chip itself not supporting GLSL versions higher than 1.20. 

Here is lspci for my VGA:

> [johnd@aa8440]: ~>$ sudo lspci -vnn | grep VGA -A 12
[sudo] password for johnd: 
00:02.0 VGA compatible controller [0300]: Intel Corporation Core Processor Integrated Graphics Controller [8086:0046] (rev 02) (prog-if 00 [VGA controller])
	Subsystem: Hewlett-Packard Company Device [103c:172a]
	Flags: bus master, fast devsel, latency 0, IRQ 32
	Memory at d0000000 (64-bit, non-prefetchable) [size=4M]
	Memory at c0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 5058 [size=8]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
	Capabilities: [d0] Power Management version 2
	Capabilities: [a4] PCI Advanced Features
	Kernel driver in use: i915
	Kernel modules: i915

Edit: Some more info...

> [johnd@aa8440]: ~>$ lshw -numeric -C display
WARNING: you should run this program as super-user.
  *-display                 
       description: VGA compatible controller
       product: Core Processor Integrated Graphics Controller [8086:46]
       vendor: Intel Corporation [8086]
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 02
       width: 64 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:32 memory:d0000000-d03fffff memory:c0000000-cfffffff ioport:5058(size=8) memory:c0000-dffff

Inxi and glxinfo...

> [johnd@aa8440]: ~>$ inxi -M
Machine:   Device: laptop System: Hewlett-Packard product: HP EliteBook 8440p
           Mobo: Hewlett-Packard model: 172A v: KBC Version 30.35
           BIOS: Hewlett-Packard v: 68CCU Ver. F.60 date: 11/11/2015
Battery    BAT0: charge: 24.1 Wh 69.0% condition: 34.9/34.9 Wh (100%)
[johnd@aa8440]: ~>$ glxinfo | grep OpenGL
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Ironlake Mobile 
OpenGL version string: 2.1 Mesa 17.0.5
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 17.0.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:

Let me know if there is anymore info I can provide! Thanks! :)

**Comment by lilianmoraru** [comment] 2017-05-04 08:47
Same issue in VMWare:
```
$ sudo lspci -vnn | grep VGA -A 12
00:0f.0 VGA compatible controller [0300]: VMware SVGA II Adapter [15ad:0405] (prog-if 00 [VGA controller])
	Subsystem: VMware SVGA II Adapter [15ad:0405]
	Flags: bus master, medium devsel, latency 64, IRQ 16
	I/O ports at 10d0 [size=16]
	Memory at d0000000 (32-bit, prefetchable) [size=128M]
	Memory at c8800000 (32-bit, non-prefetchable) [size=8M]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: [40] Vendor Specific Information: Len=00 <?>
	Kernel driver in use: vmwgfx
	Kernel modules: vmwgfx

00:10.0 SCSI storage controller [0100]: LSI Logic / Symbios Logic 53c1030 PCI-X Fusion-MPT Dual Ultra320 SCSI [1000:0030] (rev 01)
	Subsystem: VMware LSI Logic Parallel SCSI Controller [15ad:1976]
	Flags: bus master, medium devsel, latency 64, IRQ 17
```
```
$ sudo lshw -numeric -C display
  *-display               
       description: VGA compatible controller
       product: SVGA II Adapter [15AD:405]
       vendor: VMware [15AD]
       physical id: f
       bus info: pci@0000:00:0f.0
       version: 00
       width: 32 bits
       clock: 33MHz
       capabilities: vga_controller bus_master cap_list rom
       configuration: driver=vmwgfx latency=64
       resources: irq:16 ioport:10d0(size=16) memory:d0000000-d7ffffff memory:c8800000-c8ffffff memory:c0000-dffff
```
```
$ glxinfo | grep OpenGL
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: Gallium 0.4 on SVGA3D; build: RELEASE;  LLVM;
OpenGL version string: 2.1 Mesa 11.2.0
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 11.2.0
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```

**Comment by jwilm** [comment] 2017-05-04 14:43
Thanks for the reports @nantronic2 and @lilianmoraru.

This looks like a dupe of #128. Please subscribe to that issue for further updates.

**Closed by jwilm** 2017-05-04 14:43 UTC
