### ISSUE TITLE
Control Space does not work and prevents further input

### ISSUE THREAD

**Issue by legendre6891** [jwilm/alacritty#137] opened 2017-01-07 02:01 UTC
After pressing Control-Space, alacritty stops responding to keyboard input and has to be restarted to function correctly. (I use Control-Space as my tmux prefix.)

I suspect I need an entry in the `.alacritty.yml` but am unsure what the right `char` should be.

**Comment by d3rrial** [comment] 2017-01-07 02:11
duplicate of #99

**Comment by jwilm** [comment] 2017-01-09 00:57
Thanks @d3rrial

**Closed** 2017-01-09 00:57 UTC
Labels: duplicate
