### ISSUE TITLE
Terminal print `6c6c6c` into the prompt after executing `cat`

### ISSUE THREAD

**Issue by Matmaus** [jwilm/alacritty#2981] opened 2019-11-14 19:01 UTC
# System
|                  |                               |
|------------------|-------------------------------|
| Operating System | Linux 4.19.81-1-MANJARO     |
| Rust Version     | 1.38.0   |
| Display Server   | X11 |
| Window Manager   | i3 |
| Compositor       | compton |

# Summary
Alacritty v0.3.3 print `6c6c6c6c6c` characters into the prompt after executing `cat` or similar program.
This happen everytime on a few files.
Number of `6c` printed depends on the amount of file's content printed (more content = more `6c`).
Seems like alacritty issue, because:
- both ZSH and BASH print this characters in alacritty
- terminator and gnome-terminal works fine (no `6c6c6c` characters)

# Behavior
( `|` stands for cursor position)
```
user-pc$ cat file
Lorem ipsum
...
sit amet.
user-pc$ 6c6c6c6c6c|
```

# Expectation
( `|` stands for cursor position)
```
user-pc$ cat file
Lorem ipsum
...
sit amet.
user-pc$ |
```

# Extra
An example of a file having this issue:
[sample.zip](https://github.com/jwilm/alacritty/files/3848102/sample.zip)

**Comment by chrisduerr** [comment] 2019-11-14 19:37
Which terminfo are you using? This sounds like a strange system configuration, so can you repro this with an empty Alacritty config running bash without any specific rc files?

**Comment by chrisduerr** [comment] 2019-11-14 19:43
There are a lot of special characters in that file and it's not unlikely that one of these causes issues. URxvt also shows similar behavior, however I cannot say why XTerm and VTE do not.

It probably makes sense to investigate a minimal repro case, but generally I don't think it should be a problem. However if there's some reasonable workaround we might as well make use of it.

**Comment by nicm** [comment] 2019-11-15 09:42
6c is alacritty's DA response so almost certainly the file contains some sequences of \033[c.

alacritty differs from xterm in that DA is only responded to if it matches exactly \033[c - arguments aren't allowed, try for example:
~~~~
printf '\033[999c'

**Comment by Matmaus** [comment] 2019-11-15 10:38
Thank you for responses.
You are right, when I try `printf '\033[999c'` it prints `6c`.
I don't really understand, why alacritty differ from other terminals in this matching. Why does it expect parameters?

**Comment by nicm** [comment] 2019-11-15 10:43
@Matmaus it doesn't expect them, it just doesn't ignore the sequence if they are present - but it doesn't really matter if it does or not. Don't cat binary files to the terminal. If you must, use cat -v.

**Comment by Matmaus** [comment] 2019-11-15 13:36
Ok, in the case, this is not considered as a bug, I'll close the issue.

But still, `cat -v ` is not a right solution for me.

For example:
**alacritty**:
![2019-11-15-143024_952x140_scrot](https://user-images.githubusercontent.com/31512884/68946897-5c2a3880-07b4-11ea-906d-2c17b6639c5b.png)
VS
**terminator**:
![2019-11-15-143105_953x128_scrot](https://user-images.githubusercontent.com/31512884/68946928-7106cc00-07b4-11ea-9e74-522a31396b36.png)
`cat` without `-v` is much more pretty and readable in my opinion.

The only solution is (for this issue) to use another terminal.

**Comment by kchibisov** [comment] 2019-11-15 13:38
@Matmaus We'll implement a fix for it to follow other terminals, so, please, reopen your bug.

@nicm Thanks for your investigation into this issue.

**Comment by Matmaus** [comment] 2019-11-15 15:45
Well, then I'll reopen the issue.

Thank you guys @chrisduerr @nicm @kchibisov . I like alacritty, it's pretty fast.

@kchibisov I don't use `cat` just for PDFs and don't mean to use it as a "document" reader. Rather I use `cat` to see quickly a raw content of a file, regardless its type (may be unknown). This issue is related to more file types, not just a PDF. Also, PDFs could have a much printable text mixed with binary parts.

**Comment by nicm** [comment] 2019-11-15 15:53
@Matmaus - the point we are trying to make is that you will see funny stuff if you cat binary data to any terminal.

**Comment by Matmaus** [comment] 2019-11-15 16:09
@nicm Thank you for explaining. I have tried it and nothing happened, but I know what do you mean. So thanks, good to know.

**Comment by chrisduerr** [comment] 2019-11-15 19:54
Cating binary files can completely mess up your terminal state too, to the degree where most people probably don't know how to recover from it. If a stray `\e(0` makes it in your output, you'll probably find yourself reading hieroglyphics for the rest of the terminal session for example.

So while we might be able to be stricter here, there's absolutely no way we can prevent this completely and that is intentional and good the way it is. If you don't want to output escapes to the terminal, you need to filter them.

**Comment by chrisduerr** [comment] 2019-11-17 17:25
After some research, @kchibisov managed to fix some issues with files that contain the terminal identification escape in https://github.com/jwilm/alacritty/commit/bcdc605436ebe137173c531844a739eda6ee41ae, however that does not fix this specific issue.

As previously stated, this problem will never be completely fixed in any terminal emulator, but it turns out that there might be an issue with the handling of 8-bit C1 control characters.

The specific issue of this file can be reproduced with `echo -e "\x9a"`, which is in theory the value of the 8-bit C1 control character for identifying the terminal. However based on my understanding, these values need to be encoded in UTF-8, which means it should be `echo -e "\xc2\x9a"` instead.

XTerm does not seem to support either of those formats and the terminal identification escape is not supported in VTE either, however the escape `echo -e "\xc2\x85"` does work with VTE, which is used as a linebreak.

**Comment by dnkl** [comment] 2019-12-14 19:09
My understanding is that XTerm ignores 8-bit C1 control characters when in UTF8-mode (which it normally is by default).

You can make XTerm recognize C1 controls by starting it with `+u8`
```sh
$ xterm +u8
```
```
$ echo -e 'donald\x84duck'
donald
      duck
```

**Comment by kchibisov** [comment] 2019-12-14 19:34
@dnkl this make sense, I wonder where did we missed it in xterm source code, but it also supports `\x9a` (I wonder where did we missed it in its code).

However the main question that we have is why some terminals doesn't respect such escapes, since according to what we've seen [1] (I don't remember the link to VT 500 parser states), these bytes shouldn't be ignored etc. Is there a notion about UTF-8 mode in terminals that is actually a part of some spec? Since from our testing some terminals require a proper utf8 and output something (e.g. `echo -e "\xc2\x85"` in vte), some don't (the same escape in xterm), some are alacritty, which just require a proper byte to show up and do things.

[1] - https://vt100.net/emu/dec_ansi_parser

**Comment by dnkl** [comment] 2019-12-14 19:42
I _think_ the problem is that the old DEC documents predate utf8. As such, there might not _be_ a standard, that is relevant.

Though I admit I haven't read through the entire ECMA standard... perhaps it covers this somewhere.

Assuming it doesn't, then I'm guessing terminal emulator developers are just guessing, more or less...

> it also supports \x9a(just plain thing)

Hmm, mine doesn't (unless started with `+u8`). I get empty output for `echo -e '\x9a'`. The 7-bit equivalent (`echo -e '\eZ'`) works, however.

**Comment by kchibisov** [comment] 2019-12-14 19:54
>Hmm, mine doesn't (unless started with +u8). I get empty output for echo -e '\x9a'. The 7-bit equivalent (echo -e '\eZ') works, however.

I was about starting with `+u8`, so our xterms should be similar.

>Though I admit I haven't read through the entire ECMA standard... perhaps it covers this somewhere.

I guess @chrisduerr was searching through this "ancient papers" recently, so leaving it up to him. However the link I've sent was initially posted by him on IRC.

>Assuming it doesn't, then I'm guessing terminal emulator developers are just guessing, more or less...

This is likely the case, so maybe guessing like most terminals are doing it will make sense. However I also feel like this question was discussed in the past somewhere, that being said I feel like searching through old mailing lists/logs of some aged terminals could provide some insights, but it's a hard task and unlikely rewarding.

**Comment by dnkl** [comment] 2019-12-14 20:03
Right at the beginning of https://invisible-island.net/xterm/ctlseqs/ctlseqs.html there's this:

> Controls (including the escape code 27) are processed once:
>
> o   This means that a C1 control can be mistaken for badly-formed UTF-8
>     when the terminal runs in UTF-8 mode because C1 controls are valid
>     continuation bytes of a UTF-8 encoded (multibyte) value.
> 
> o   It is not possible to use a C1 control obtained from decoding the
>     UTF-8 text, because that would require reprocessing the data.  Con-
>     sequently there is no ambiguity in the way this document uses the
>     term "character" to refer to bytes in a control sequence.

It seems relevant, but I don't know exactly what conclusions to draw from it. It at least seem to indicate that C1 + UTF-8 is a bad combo.

**Comment by dnkl** [comment] 2019-12-14 20:12
Looking through the XTerm changelog, I found these two notes:

> Patch 282
> * add -8, -c, -d and -u options to 88colors2.pl and 256colors2.pl scripts. **No current terminal emulator recognizes C1 controls while handling UTF-8 encoding**—see notes in patch #119 and patch #109 regarding utf8controls—but the -u and -8 options are useful for demonstrating this point.

> Patch 190
> * correct state for values in the range 128-159 after translating from UTF-8: this should be ignored unless the user overrides it with the allowC1Printable resource (reported by Simon Strandgaard).

**Comment by chrisduerr** [comment] 2019-12-14 21:40
Based on my understanding, there are two different versions of these C1 escapes. The 8-bit ascii versions and the utf8 encoding.

When encoded as utf-8, the `\xc2` is added to the start of the UTF8 grapheme, which means that there is no conflict with ascii, but there is also no advantage over just using the `\e` versions, since both are two bytes in that case. Terminals like VTE do handle these as UTF-8 graphemes though.

The ascii version, so just `\x85` for example, is not recognized in VTE at all. Based on my research, it seems like there might be some conflict with some character sets according to wikipedia, so in some cases these might be printable characters. I'd assume that is why terminals like VTE do not support this. However I am uncertain if any character set that creates issues can actually be selected in a terminal, it seems like the wikipedia page was mostly talking about other forms of documents, so I don't think so.

**Comment by dnkl** [comment] 2019-12-14 22:20
> When encoded as utf-8, the \xc2 is added to the start of the UTF8 grapheme

I assume this is what the second point in https://github.com/jwilm/alacritty/issues/2981#issuecomment-565748765 refers to; processing C1 control characters _after_ having decoded them from UTF-8 would invalidate the ECMA-48 processing model. We know for a fact that XTerm ignores UTF-8 encoded C1 control characters, and I believe this is the reason.

Perhaps the first point explains why it ignores plain C1 (non UTF-8 encoded) characters? It might confuse its UTF-8 decoder if the C1 character follows directly after an UTF-8 sequence?

Of course, this is my interpretation of **one** terminals interpretation of ECMA-48 - bound to be errors :smile:

**Comment by chrisduerr** [comment] 2019-12-14 22:29
> Of course, this is my interpretation of one terminals interpretation of ECMA-48 - bound to be errors

Yeah and ultimately that's what it boils down to and why I haven't made any changes yet.

XTerm seems to have opt-in ascii 8-bit options, but does not support UTF-8 with these escapes.

VTE does not seem to support ascii 8-bit option, but does support UTF-8 with these escapes.

Alacritty always supports ascii 8-bit, but does not support UTF-8 with these escapes, however has no option to disable it.

So it feels like Alacritty is already doing something acceptable, but on the other hand it also feels like whatever you do it's acceptable. Some terminals just don't do either.

I think the only combination I haven't seen is supporting both UTF-8 and 8-bit mode, but even that doesn't sound too unreasonable.

**Comment by egmontkob** [comment] 2019-12-15 22:27
I'm really uncertain VTE does the right thing by supporting C1. Now I think we should remove it. See the brand new [VTE 209](https://gitlab.gnome.org/GNOME/vte/issues/209).

**Comment by chrisduerr** [comment] 2019-12-15 23:07
In theory it might even be possible to improve our VTE parser if we do decide that 8-bit escapes shouldn't be a thing anymore, at least the original resource after which I believe the parser was implemented notes this as a detail.

**Closed** 2019-12-31 20:56 UTC
Labels: B - bug
