### ISSUE TITLE
Alacritty scrolling doesn't work

### ISSUE THREAD

**Issue by diegoviola** [jwilm/alacritty#2080] opened 2019-02-05 21:56 UTC
Which operating system does the issue occur on?

Arch Linux

If on linux, are you using X11 or Wayland?

X11

--

When trying to scroll with alacritty using shift+pageup/pagedown I get `2~2~2~2~` instead, I am not sure if the problem is these keybindings, I am using the default configuration.

alacritty 0.2.7-2 from community Arch Linux repository.

**Comment by chrisduerr** [comment] 2019-02-05 22:08
Duplicate of https://github.com/jwilm/alacritty/issues/1989.

**Closed by chrisduerr** 2019-02-05 22:08 UTC

**Comment by ngortheone** [comment] 2019-03-28 17:34
@chrisduerr it does not look like this is a dup

I am on 0.2.9 OSX and my config already contains this:
```
key_bindings:
  - { key: PageUp,     mods: Shift,   action: ScrollPageUp   }
  - { key: PageDown,   mods: Shift,   action: ScrollPageDown }
  - { key: End,        mods: Shift,   action: ScrollToBottom }
  - { key: Home,       mods: Shift,   action: ScrollToTop    }

```

but I still can't scroll up and I get `2~` when I press Shift+PageUp
