### ISSUE TITLE
Hiding window on OS X disappears the window

### ISSUE THREAD

**Issue by simmel** [jwilm/alacritty#2891] opened 2019-10-18 12:12 UTC
Which operating system does the issue occur on?
```
kaka:~$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.14.6
BuildVersion:   18G103
```

I usually recompile alacritty every monday on OS X for some light testing. Since a couple of weeks I've noticed that whenever I hide the window Alacritty can't find it again. I have to force close Alacritty and start over (thank $DEITY for tmux ; ).

```
kaka:~$ /Applications/Alacritty.app/Contents/MacOS/alacritty -V
alacritty 0.3.3 (cc3e4d3)
```
is not affected by this.

I'm gonna try to narrow it down but don't hold your breath.

### How to reproduce.
1. In `~/.alacritty.yml`:
    ```yaml
    key_bindings:
    […]
      - { key: H,        mods: Command, action: Hide                         }
    […]
    ```
1. Press cmd+h
1. Either:
    1. Click on another applications icon in the Dock.
    1. Press the Alacritty icon in the Dock.
    * or
    1. cmd+tab into another application
    1. cmd+tab back into Alacritty
1. Alacritty and it's window should appear.

This works in cc3e4d3 but not in a75e949.

**Comment by chrisduerr** [comment] 2019-10-18 20:10
Does https://github.com/jwilm/alacritty/issues/1465 sound like this issue?

https://github.com/jwilm/alacritty/issues/2813 might also be related.

**Comment by nixpulvis** [comment] 2019-10-18 21:31
I can definitely reproduce this, along with various issues related to comments in those linked issues @chrisduerr. This issue seems to have existed to some degree before, since I've tested against the 0.3.3 release, cc3e4d3. 

In the 0.3.3 release, <kbd>cmd-H</kbd> hides the window but doesn't unfocus the application. Then trying to refocus the window doesn't do anything, and so it doesn't un-hide, however focusing another application, then focusing the hidden alacritty will work as expected. It's also worth noting that on this release, even without hiding the window, the focus event is not always triggered or handled properly when clicking on an un-focused window.

On master, we still don't unfocus when hiding, but the issue with clicking to gain focus described above is gone, however now the window will not un-hide even when clicking on it's dock icon while not focused.

Sorry if this isn't 100% clear.

**Comment by chrisduerr** [comment] 2019-10-18 21:35
@nixpulvis Do you think it makes sense to keep multiple issues open about this, seems like they're all pretty much just different variations of the same root issue.

Maybe just renaming the issue to be a little more broad would be a good idea?

**Comment by nixpulvis** [comment] 2019-10-19 00:42
I'd be all for a unified macOS focus + hiding issue. It seems they are related. Just as long as they're all linked.

I'm curious to see if this is something you can reproduce with basic winit examples. I'm assuming at the moment it's not.

**Comment by chrisduerr** [comment] 2019-10-19 01:36
Closing as duplicate of https://github.com/jwilm/alacritty/issues/1465.

**Closed by chrisduerr** 2019-10-19 01:36 UTC
Labels: H - macos
