### ISSUE TITLE
Quake-style terminal mode

### ISSUE THREAD

**Issue by fdcds** [jwilm/alacritty#2975] opened 2019-11-13 16:40 UTC
I would like to have a setting for alacritty, where it would start maximized to the width of the display at the top of the screen, hidden. With the press of a button (usually F12), it would unhide itself (possibly with a nice animation). I.e. I would like for alacritty to have a Quake-style terminal mode.

**Comment by kchibisov** [comment] 2019-11-13 16:56
Duplicate of #1119

**Closed** 2019-11-13 18:01 UTC
