### ISSUE TITLE
Cannot Load User Font

### ISSUE THREAD

**Issue by RcrsvSquid** [jwilm/alacritty#1493] opened 2018-08-05 18:52 UTC
Which operating system does the issue occur on?
MacOS

I'm using the following config to attempt to load a nerd font to no avail. How do I translate the name of the font with nested styles from font book to the name needed in the yaml configuration?
```yaml
font:
  # The normal (roman) font face to use.
  normal:
    family: Sauce Code Pro
    # Style can be specified to pick a specific face.
```

**Comment by zhangxiubo** [comment] 2018-08-07 11:00
Try surround the name of the font in double quotes:
```yaml
font:
  # The normal (roman) font face to use.
  normal:
    family: "Sauce Code Pro"
    # Style can be specified to pick a specific face.
```

**Comment by sodiumjoe** [comment] 2018-08-11 03:35
I don't think the quotes are necessary, and it should just be the title in Font Book:

For example, this works for me:

```
# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Inconsolata Nerd Font
```

![image](https://user-images.githubusercontent.com/845857/43987861-f21a8c4e-9cdc-11e8-887b-85289acc902b.png)

**Comment by takehironet** [comment] 2018-08-20 18:10
Is it solved?
If not, verify the font name is correct. It should be "Source Code Pro", not "Sauce Code Pro".

**Comment by sjug** [comment] 2018-09-06 13:00
Duplicate of https://github.com/jwilm/alacritty/issues/1474

**Comment by chrisduerr** [comment] 2018-09-06 14:50
Thanks for the heads up @sjug, closing as duplicate of #1474.

**Closed by chrisduerr** 2018-09-06 14:50 UTC
