### ISSUE TITLE
Open URL via key binding / send URLs to external tool via key binding

### ISSUE THREAD

**Issue by simmel** [jwilm/alacritty#1736] opened 2018-11-01 12:25 UTC
I'm loving #113! Finally no more precision selection, copy, switch to $BROWSER and pasting.

But it would be even more awesome to be able open URLs via a key binding!

I'm guessing showing a list of URLs in the current window and having the user being able to select it and open it via the `url.launcher` is OK but it might not be desirable from your side?

An alternative is to be able to send the content of the current window to an external tool, like urlscan, urlview etc, which can handle it. That of course requires waiting for an external application to complete so that might be even more undesirable = D

**Comment by chrisduerr** [comment] 2018-11-01 13:46
This is a duplicate of https://github.com/jwilm/alacritty/issues/1725.

**Closed by chrisduerr** 2018-11-01 13:46 UTC
