### ISSUE TITLE
Improper font scaling across various DPI screens

### ISSUE THREAD

**Issue by kwaugh** [jwilm/alacritty#951] opened 2017-12-20 20:19 UTC
Occurs on MacOS High Sierra 10.13.1. Untested on other OSs. When alacritty is started on the built in macbook pro display, the font is rendered correctly. If the window is dragged to a standard 1080p monitor, the text is huge. Conversely, if alacritty is started on the 1080p monitor, then dragged onto the build-in display, the text is tiny.

**Comment by chrisduerr** [comment] 2017-12-20 20:28
This is a duplicate of #71.

**Closed** 2017-12-22 02:58 UTC
