### ISSUE TITLE
Alacritty crashes on minimize

### ISSUE THREAD

**Issue by gurpreetshanky** [jwilm/alacritty#1669] opened 2018-10-17 12:58 UTC
Which operating system does the issue occur on?

Windows 10

If minimize, alacritty would simply exit and would have to start it again.

**Comment by zacps** [comment] 2018-10-18 04:04
Could you try using the [new build](https://ci.appveyor.com/project/jwilm/alacritty/build/job/r68ukagh9iqv8hrm/artifacts) and running from another terminal:

```
alacritty -vvv
```

**Comment by gurpreetshanky** [comment] 2018-10-18 12:02
Ok I tried new build. This is the error.

Term::resize
Assertion failed: ASSERT_CONDITION("wp != nullptr && cols > 0 && rows > 0"), file src/libwinpty/winpty.cc, line 924

**Comment by zacps** [comment] 2018-10-19 04:43
That's... weird.

There are **two** checks that should have stopped that from happening before it got to that point.

First `set_size(0,0)` events are ignored [here](https://github.com/jwilm/alacritty/blob/master/src/tty/windows.rs#L279).

Then there's an assert in the winpty bindings [here](https://github.com/jwilm/alacritty/blob/master/winpty/src/lib.rs#L213).

**Comment by gurpreetshanky** [comment] 2018-10-19 14:03
What does set_size do in windows.rs? I'm happy to help if you need something more. Also it only fails if I minimize this and not when i don't(alacritty not in focus).

**Comment by zacps** [comment] 2018-10-19 21:09
It sets the size of the terminal (in this case via winpty) when the window is resized.

Usually any event setting the size to (0,0) is ignored, because winpty will panic.

Could you run it with this patch

**Comment by gurpreetshanky** [comment] 2018-10-20 05:46
This is the output set_size: 18446744073709551613 18446744073709551615
Assertion failed: ASSERT_CONDITION("wp != nullptr && cols > 0 && rows > 0"), file src/libwinpty/winpty.cc, line 924.

These numbers are maximum size of u64 which then are passed to unsafe block which are i32 so I think there is integer truncation happening.

**Comment by zacps** [comment] 2018-10-20 22:17
Can you try with this patch?

```
diff --git a/src/index.rs b/src/index.rs
index ab8e741..f88b927 100644
--- a/src/index.rs
+++ b/src/index.rs
@@ -436,7 +436,7 @@ macro_rules! ops {

             #[inline]
             fn sub(self, rhs: usize) -> $ty {
-                $construct(self.0 - rhs)
+                $construct(self.0.saturating_sub(rhs))
             }
         }
     }
```

**Comment by zacps** [comment] 2018-10-20 23:16
Actually if you could try with my [resize_underflow_fix](https://github.com/zacps/alacritty/tree/resize_underflow_fix) branch instead.

**Comment by gurpreetshanky** [comment] 2018-10-20 23:33
Nope same problem. It crashes.

**Comment by zacps** [comment] 2018-10-27 21:44
Could you try debugging alacritty under msvc and trying to find where the underflow happens?

I can't reproduce it reliably on my machine without making the window have no size, and that issue was fixed by the branch above.

**Comment by gurpreetshanky** [comment] 2018-10-27 21:51
@zacps Whats your screen resolution? because mine is 4k so maybe this is the problem.Also, I'll try the debugging. What do you use for debugging on Windows? VsCode?

**Comment by zacps** [comment] 2018-10-27 21:55
My resolution is 1920x1080, it could definitely be the cause.

I'm using vscode with the following `launch.json`:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(Windows) Launch",
            "type": "cppvsdbg",
            "request": "launch",
            "program": "${workspaceFolder}/target/debug/alacritty.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": true
        }
    ]
}
```

**Comment by gurpreetshanky** [comment] 2018-10-27 21:56
@zacps Thanks I'll try it.

**Comment by gurpreetshanky** [comment] 2018-10-28 22:35
@zacps I think your resize_underflow_fix is working. I didn't change anything but now its working. Weird.

**Closed** 2018-11-24 21:08 UTC
Labels: B - bug, H - windows, S - I/O and PTY
