### ISSUE TITLE
Printed character changes the second time `Alt+l` is pressed

### ISSUE THREAD

**Issue by elaye** [jwilm/alacritty#2354] opened 2019-04-23 08:41 UTC
# System
MacOS Mojave 10.14.3

# Summary

When running `/bin/cat`, if I type `Alt+l` it prints `^[l` the first time, but prints `^[-` every time after that

# Expectation
It should print the same thing every time `Alt+l` is pressed.

# Extra

I have custom bindings in tmux to change panes:
 - `Alt+h` to go left
 - `Alt+j` to go down
 - `Alt+k` to go up
 - `Alt+l` to go right

I added these keybindings in `alacritty.yml` to make it work:

```yml
  - { key: J,      mods: Alt, chars: "\x1bj"             }
  - { key: K,      mods: Alt, chars: "\x1bk"             }
  - { key: H,      mods: Alt, chars: "\x1bh"             }
  - { key: L,      mods: Alt, chars: "\x1bl"             }
```

`Alt+j`, `Alt+k`, `Alt+h` work as expected but `Alt+l` doesn't. So I tried these bindings by just running `/bin/cat` (outside of tmux) and when I press repeatedly `Alt+l` I get this:

```
$ cat
^[l^[-^[-^[-
```

**Comment by chrisduerr** [comment] 2019-04-23 14:58
I can't reproduce this on Linux/X11. Can you verify that this happens outside of tmux too? Also does this issue only happen when you keep alt pressed or also when you release it between `L` presses?

**Comment by elaye** [comment] 2019-04-23 16:17
It happens outside of tmux. It happens when I keep the `Alt` key pressed.
However if I release the `Alt` key after the first time I get something different. Meaning if I do the following sequence of key presses:

`Alt+l` then `l` then `l`

I get this:

```
$ cat
^[lłl
```

**Comment by chrisduerr** [comment] 2019-04-23 17:54
This is a duplicate of https://github.com/jwilm/alacritty/issues/2017.

**Closed by chrisduerr** 2019-04-23 17:54 UTC
Labels: A - needs repro, H - macos, S - input
