### ISSUE TITLE
Change Font Size with Mouse Wheel

### ISSUE THREAD

**Issue by a0n** [jwilm/alacritty#2674] opened 2019-07-24 13:26 UTC
I tried this Configuration:
`mouse_bindings:
  - { mods: Shift, mouse: "4", action: DecreaseFontSize }
  - { mods: Shift, mouse: "5", action: IncreaseFontSize }

Is this supposed to work.`

Which operating system does the issue occur on?
Arch

If on linux, are you using X11 or Wayland?
Sway / Wayland

**Comment by kchibisov** [comment] 2019-07-24 19:58
> Is this supposed to work.`

No.

 it's a duplicate of #2512.

**Closed** 2019-07-24 20:24 UTC
