### ISSUE TITLE
Unicode characters not rendering

### ISSUE THREAD

**Issue by arunvelsriram** [jwilm/alacritty#1397] opened 2018-06-28 18:05 UTC
Which operating system does the issue occur on?
Mac OS X

Unicode characters are not rendered when opened using `Alacritty.app`.

### Alacritty:
<img width="222" alt="screen shot 2018-06-28 at 9 46 11 pm" src="https://user-images.githubusercontent.com/6568319/42052087-77177728-7b2b-11e8-80c9-3e48f89c2345.png">

<img width="372" alt="screen shot 2018-06-28 at 9 46 19 pm" src="https://user-images.githubusercontent.com/6568319/42052093-7dd132f2-7b2b-11e8-8d87-0170b7736c8e.png">

### iTerm
<img width="347" alt="screen shot 2018-06-28 at 11 32 53 pm" src="https://user-images.githubusercontent.com/6568319/42052150-a2155936-7b2b-11e8-9c9a-4d348782d531.png">

<img width="447" alt="screen shot 2018-06-28 at 11 33 02 pm" src="https://user-images.githubusercontent.com/6568319/42052165-a8705844-7b2b-11e8-809d-5a5f72cf1965.png">

However, it's working if I open the `alacritty` binary directly like this:

```
/Applications/Alacritty.app/Contents/MacOS/alacritty
```

**Comment by chrisduerr** [comment] 2018-06-28 18:28
This sounds like a duplicate of #153. This is probably due to a font configuration issue where iTerm is picking a different fallback font than Alacritty. The font configuration is currently scheduled for a rework (see #957), which will probably help with this issue once implemented, so watching these two might be your best choice for now.

I'm going to close this issue as duplicate, if you think that your issue is not covered by #153, please re-open this issue.

**Closed by chrisduerr** 2018-06-28 18:29 UTC

**Comment by arunvelsriram** [comment] 2018-06-28 18:36
Actually it seem to be a `tmux` issue. Telling `tmux` that the terminal supports `UTF-8` by setting `locales` correctly or explicitly using `tmux -u` fixes the issue.

Its described here: [https://github.com/tmux/tmux/issues/328 (https://github.com/tmux/tmux/issues/328)
