### ISSUE TITLE
Resizing window on macOS begins selection

### ISSUE THREAD

**Issue by jwilm** [jwilm/alacritty#47] opened 2017-01-04 19:47 UTC

**Comment by sterpe** [comment] 2017-01-06 20:05
+1

**Comment by uvesten** [comment] 2017-01-07 11:13
+1

**Comment by casey** [comment] 2017-01-26 05:28
Here's a video of it happening in macOS: https://youtu.be/4MTutlRWTqE

(you can also see issue #194 which is separate)

**Comment by sodiumjoe** [comment] 2018-04-15 04:13
should be fixed in https://github.com/tomaka/winit/pull/466

**Comment by sodiumjoe** [comment] 2018-04-15 21:15
merged, just has to be released and propagated through glutin now

**Comment by sodiumjoe** [comment] 2018-04-21 20:36
Unfortunately that PR had to be reverted because of some unintended side effects. Looks like it might have to wait for some potentially breaking changes in winit's fundamental api. [This](https://github.com/tomaka/winit/issues/463) is the winit issue that causes this bug, and [this](https://github.com/tomaka/winit/issues/231) and [this](https://github.com/tomaka/winit/issues/459) are the ones to follow for the underlying api discussions.

**Comment by francesca64** [comment] 2018-06-18 16:46
This should be fixed now.

**Comment by chrisduerr** [comment] 2018-06-18 17:28
This is probable because of the following change, right?
`On macOS, CursorMoved and MouseInput events are only generated if they occurs within the window's client area.`

Is there now no way to get `CursorMoved` events anymore when the cursor is outside of the window? This might make it significantly harder to implement selection properly, because usually people expect the selection to change when they mouse-down inside the window and then move the mouse left/right outside of the window.

Thanks for the heads-up though, closing this issue!

**Closed by chrisduerr** 2018-06-18 17:28 UTC
Labels: B - bug, H - macos, S - input, S - winit

**Comment by francesca64** [comment] 2018-06-18 17:56
Would it make sense to use the delta from `DeviceEvent` for that? 

Was that working on X11? macOS seemed to be the only platform that generated `CursorMoved` outside of the window, but I might be misremembering.

**Comment by chrisduerr** [comment] 2018-06-18 18:07
I'm only using X11 and I was able to get `CursorMoved` events there even when the mouse has left the window as long as the window was still focused.

Having a delta motion event in `DeviceEvent` would certainly be possible, however I'm pretty sure this could require Alacritty to deal with quite a lot more stuff. We'd have to handle every `DeviceEvent` (currently we're discarding it) and if it's a delta we'd have to apply the change to the last received `CursorMoved` event and always keep track of where the cursor position currently is until the cursor enters the window again. I don't think we need to care about the cursor movement being inside the window at all, since this is quite easy to check, so it might make sense to actually switch to `DeviceEvent` for everything if this is the only option.

**Comment by francesca64** [comment] 2018-06-18 19:43
Ah, sorry, I must've only compared against Windows. Tomorrow I'll look into making all platforms able to detect mouse movement outside of the client area, instead of the other way around.

**Comment by chrisduerr** [comment] 2018-06-18 19:45
@francesca64 Thanks so much for the quick responses and willingness to work on this! This is getting a bit repetitive now but I really can't stress enough how nice it is to see all your work. :)

**Comment by francesca64** [comment] 2018-06-21 22:45
I'm easily distracted (I got halfway through complete multi-plat gamepad support for winit), so I missed "tomorrow" by a decent margin, but here I am.

Testing on Xfwm and KWin, I don't get `WindowEvent::CursorMoved` outside of the window. Consequently, selection in Alacritty doesn't work as you described for presumably the majority of people. I've confirmed that this happens at least as far back as 0.13.1, so it's a not a regression.

**Comment by chrisduerr** [comment] 2018-06-21 23:04
Just to prove that I didn't make this up: https://u.teknik.io/m2rM3.webm

Note that this is done through the `WindowEvent::CursorMoved` event, however this is only reported when the cursor is outside of the window and the LMB was pressed inside the window before (and has been held down since then).

I would assume removing this would also remove this functionality, unless this is something different, then I'm sorry for causing you any trouble.

This is on i3, so an X11 window manager (with compton compositor but that shouldn't matter here). I'd assume this behavior might be similar with other WMs, so you'd need to hold down the mouse inside the window first.

No matter how this turns out, thanks for helping out with this issue @francesca64. If this gets a bigger issue and more discussion is needed, maybe moving to an issue in winit is appropriate so others can have part in the conversation too.

**Comment by francesca64** [comment] 2018-06-21 23:37
> Just to prove that I didn't make this up

I didn't think you had. X11 WMs are notorious for inconsistency.

> the cursor is outside of the window and the LMB was pressed inside the window before

I tested the selection feature exactly as you described. `XI_Motion` simply isn't generated in this case under most WMs. If you don't believe me, you can install some more WMs... it's a *really* good idea to test software on a variety of WMs, since stuff like this is shockingly common.

> I would assume removing this would also remove this functionality

I only changed macOS, but yes, it prevents `CursorMoved` from being used for this purpose there. Seeing as it seems impossible to reliably support this on X11 (it's possible on Windows, though not currently in place), I don't consider the macOS change to be a bad thing.

> This is on i3

i3 is a fairly quirky WM, from what I've seen. Even mainstream WMs have serious oversights, and the standards for how WMs should behave are poorly defined to begin with.

> maybe moving to an issue in winit is appropriate

Feel free to open an issue if A) using `DeviceEvent` for this isn't viable for some reason, or B) if I'm demonstrably wrong about this.

**Comment by nixpulvis** [comment] 2018-06-21 23:41
I really need to build myself a nice little alacritty testing rig, with like 7283162 WMs on it. One day...
