### ISSUE TITLE
Cannot select individual characters in nvim.

### ISSUE THREAD

**Issue by tinchoz49** [jwilm/alacritty#2347] opened 2019-04-22 17:57 UTC
**Which operating system does the issue occur on?**

5.0.7-1-MANJARO

**If on linux, are you using X11 or Wayland?**

X11

**Description**

With the latest versions `>= 3.0` I cannot select a part of a word using the mouse in neovim.

![Peek 2019-04-22 14-53](https://user-images.githubusercontent.com/819446/56515687-d7718780-650e-11e9-9b89-74efc297a565.gif)

**Comment by chrisduerr** [comment] 2019-04-22 18:00
I can't reproduce this myself on Linux/X11/i3/compton with neovim.

Can you try to repro in a different terminal emulator?

**Comment by tinchoz49** [comment] 2019-04-22 18:19
Hi @chrisduerr, I check it using kitty and it works well.
![Peek 2019-04-22 15-19](https://user-images.githubusercontent.com/819446/56516902-06d5c380-6512-11e9-9391-3ba93300b392.gif)

**Comment by chrisduerr** [comment] 2019-04-22 18:29
Which version of Alacritty are you using?

**Comment by tinchoz49** [comment] 2019-04-22 21:26
Right now 0.3.1 but it is started happening in the 0.3.0

**Comment by tinchoz49** [comment] 2019-04-22 21:32
This is a record gif of alacritty 0.2.9 working fine
![Peek 2019-04-22 18-30](https://user-images.githubusercontent.com/819446/56532820-e6673280-652c-11e9-97f4-eba2e459c6cb.gif)

**Comment by chrisduerr** [comment] 2019-04-22 21:59
Could you bisect the specific commit?

**Comment by narpfel** [comment] 2019-04-27 07:37
I bisected between `v0.2.9` (3ec53b4f0b748e10259036152312192370f33748) and `master` (9c6d12ea2c863ba76015bdedc00db13b7307725a):

    » git bisect log
    git bisect start
    # good: [3ec53b4f0b748e10259036152312192370f33748] Bump version to 0.2.9
    git bisect good 3ec53b4f0b748e10259036152312192370f33748
    # good: [3ec53b4f0b748e10259036152312192370f33748] Bump version to 0.2.9
    git bisect good 3ec53b4f0b748e10259036152312192370f33748
    # bad: [9c6d12ea2c863ba76015bdedc00db13b7307725a] Fix position of zero-width over double-width characters
    git bisect bad 9c6d12ea2c863ba76015bdedc00db13b7307725a
    # bad: [48d781d1238835db9f2d30742ccf50dd53be7bed] Fix Windows deployment
    git bisect bad 48d781d1238835db9f2d30742ccf50dd53be7bed
    # good: [b1032bcc6b79135f87f327548e43563da05657fb] Add text reflow
    git bisect good b1032bcc6b79135f87f327548e43563da05657fb
    # bad: [d8272662db4a4dc1ef58b8379dc88162066a3241] Fix URL parsing with double-width characters
    git bisect bad d8272662db4a4dc1ef58b8379dc88162066a3241
    # good: [fc28e49c277f777dbced6cbfeccb106c04486f15] Add change log entry for Wayland title fix
    git bisect good fc28e49c277f777dbced6cbfeccb106c04486f15
    # bad: [c6ab2a8867ad0d064d67dc5e32138cbb3d3ab833] Fix URLs getting incorrectly extended to next line
    git bisect bad c6ab2a8867ad0d064d67dc5e32138cbb3d3ab833
    # bad: [a672f7d553ac17d5aaef8dc667dee31d5815677d] Add URL hover highlighting
    git bisect bad a672f7d553ac17d5aaef8dc667dee31d5815677d
    # good: [eb7a1ea803ba54d3b8cd6af49255eb8fbe0d7544] Remove InclusiveRange code
    git bisect good eb7a1ea803ba54d3b8cd6af49255eb8fbe0d7544
    # first bad commit: [a672f7d553ac17d5aaef8dc667dee31d5815677d] Add URL hover highlighting

Minimal neovim repro:

    » nvim --version
    NVIM v0.3.4
    Build type: Release
    LuaJIT 2.0.5
    Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
    Compiled by builduser

    Features: +acl +iconv +jemalloc +tui
    See ":help feature-compile"

       system vimrc file: "$VIM/sysinit.vim"
      fall-back for $VIM: "/usr/share/nvim"

    Run :checkhealth for more info

    » nvim -u /dev/null --cmd ':set mouse=a' build.rs      # or any other file

OS: Arch Linux; neovim installed from Arch repos.

**Comment by chrisduerr** [comment] 2019-04-27 09:37
Just to make sure this is not a configuration error, does this happen with `alacritty --config-file /dev/null` too?

**Comment by chrisduerr** [comment] 2019-04-27 15:58
Fixed in https://github.com/jwilm/alacritty/pull/2375.

**Closed** 2019-04-28 22:36 UTC
Labels: B - bug, B - regression, S - input, S - selection

**Comment by tinchoz49** [comment] 2019-04-29 12:48
Tested! working great! thanks for fixing it so quick!
