### ISSUE TITLE
Recent launcher removal in Alacritty.app bundle breaks the app (macOS)

### ISSUE THREAD

**Issue by spamwax** [jwilm/alacritty#943] opened 2017-12-15 06:17 UTC
After the commits that fiddle with window focus and removal of script launcher under macOS (https://github.com/jwilm/alacritty/commit/d0fb4c563f8fe9d995cdcaec7b2b16e77e19d1a2 and https://github.com/jwilm/alacritty/commit/d0fb4c563f8fe9d995cdcaec7b2b16e77e19d1a2)
double clicking on the app in Finder or trying to `open` it from terminal doesn't work anymore:

```bash
$ open assets/osx/Alacritty.app
LSOpenURLsWithRole() failed with error -10810 for the file ~/rust/alacritty/assets/osx/Alacritty.app.
```

The recent built of executable in `assets/osx/Alacritty.app/Contents/MacOS` folder has `+x` flag as it was suggested [here](https://apple.stackexchange.com/questions/181026/lsopenurlswithrole-failed-with-error-10810-cant-open-install-os-x-yosemite)

Of course, Alacritty can be launchd from command line of Terminal.app:

```
target/release/alacritty 
```

Any help is appreciated.

**Comment by spamwax** [comment] 2017-12-15 06:30
To me, it seems the Alacritty.app should have a `MacOS` folder like other native apps. Removal of `launcher` and __its folder__ seems to be cause of this issue.

**Comment by chrisduerr** [comment] 2017-12-15 06:47
Have you tried the fixes mentioned in https://github.com/jwilm/alacritty/commit/d0fb4c563f8fe9d995cdcaec7b2b16e77e19d1a2#comments?

This sounds like a duplicate of #942 to me.

**Comment by spamwax** [comment] 2017-12-15 07:07
Thanks for your comment, I did try those.
Removing `MacOS` folder and copying executable to `Contents` folder, however, fixes the problem.

**Comment by giorgiga** [comment] 2018-01-04 04:32
@spamwax not sure I am getting this right, but the .app in `assets/osx` is just a stub.

This works for me:

    $ make app
    $ open target/release/osx/Alacritty.app

**Comment by jwilm** [comment] 2018-01-04 05:16
Solution is available in https://github.com/jwilm/alacritty/commit/d0fb4c563f8fe9d995cdcaec7b2b16e77e19d1a2#comments

**Closed by jwilm** 2018-01-04 05:16 UTC
