### ISSUE TITLE
In which use cases can an user see performance boost?

### ISSUE THREAD

**Issue by janjur** [jwilm/alacritty#1383] opened 2018-06-18 13:02 UTC
This is just a quick question. My default Ubuntu terminal emulator boots up under 100 ms. So I don't think there is a need for improvement here. So, in what situations would I need the extra speed you provide? Like 120Hz screen refreshing?

**Comment by chrisduerr** [comment] 2018-06-18 17:50
There's certainly different levels of issues which warrant switching to a faster terminal emulator, they range from being pretty trivial to severe UX problems.

Some terminal emulators are so slow that on certain machines it's troublesome to edit a file in vim because it's slow or just feels a bit unresponsive, this should be the most obvious point since when there's an obvious problem impacting the user caused by performance issues, the solution to switch to a faster terminal emulator should be pretty simple.

However on my machine this isn't an issue at all, nothing is extremely slow inside of other terminal emulators like Termite. But even then I still enjoy seeing the little speedups that are even present when catting a super big file or just messing around with the terminal in some other odd way like running cmatrix at a super low resolution. These things certainly aren't critical, using a different terminal emulator this would never be an issue, but when you switch to Alacritty you can certainly notice the difference every once in a while and I personally welcome that even though I don't actually ***need*** that.

And then of course there's all the other things. It's not good enough to be a super blazingly fast terminal emulator when it sucks in every other imaginable way. The goal is to make sure Alacritty is fast, without having to sacrifice every other aspect for it. In this case it doesn't even matter if Alacritty is the fastest terminal emulator or the second/third/fourth, but the question is more "which fast terminal emulator is also nice to use?". This is probably one of the bigger reasons Alacritty even exists, a lot of fast terminal emulators aren't even available on MacOS, so even when you don't need "THE FASTEST", just getting a decently fast one might be near impossible. And even on linux often terminal emulators which work great and are super fast, still struggle from other issues like annoyances in the configuration (which is how I'd describe urxvt).

But in the end that all doesn't really matter. If you, or anyone else starts up Alacritty and asks themselves "Why do we need this? It's just another terminal emulator!", I would always encourage you to play around with it a bit more, but there's no "secret trick" Alacritty has which someone can recommend that suddenly makes everyone go "Oh, this changes everything!" (except for the live config update maybe, that certainly blew me away! :D). If you don't see any reason to use Alacritty and you prefer other terminal emulators, that's perfectly fine! And if you love Alacritty but don't know why, that's also fine.

I hope this at least touches on some of the reasons why you were asking this question, if you want to know anything else, feel free to keep asking until all your questions are answered! I'm going to close this issue because I don't think there's any problem that needs to be resolved, but don't let that hold you back!

**Closed by chrisduerr** 2018-06-18 17:50 UTC

**Comment by janjur** [comment] 2018-06-18 19:35
Thank you! Your answer is very robust and comprehensive :) I think I will give it a shot when you release the Windows version. Good luck!

**Comment by chrisduerr** [comment] 2018-06-18 19:43
Thanks for asking, always happy to answer any questions! :)
