### ISSUE TITLE
Provided binary build somewhere.

### ISSUE THREAD

**Issue by pauldotknopf** [jwilm/alacritty#1090] opened 2018-02-05 08:37 UTC
Maybe you can occasionally create some GitHub release?

I am on Arch, and ```alacritty-git``` has many large dependencies and takes ~5 minutes to compile, all for a single ~5MiB file.

**Comment by pauldotknopf** [comment] 2018-02-05 09:26
Maybe we can statically link in musl to make it super portable?

**Comment by RealOrangeOne** [comment] 2018-02-05 09:32
Looks like a duplicate of https://github.com/jwilm/alacritty/issues/927. [This comment](https://github.com/jwilm/alacritty/issues/927#issuecomment-348594235) may be of interest

**Closed** 2018-02-05 10:28 UTC
