### ISSUE TITLE
MacOS can't correctly remap Alt/Option key combinations which produce diacritics

### ISSUE THREAD

**Issue by eraserhd** [jwilm/alacritty#1610] opened 2018-09-30 17:30 UTC
If I have this:

```
  - { key: I,         mods: Alt, chars: "\x1bi"                    }
```

Then, when I type "Alt-i b", I get ESC i, then a `b` *with a circumflex*.  This likely affects other keys which produce diacritics, including `e` and `o`.

I have a work-around for now, which is to use a [Karabiner](https://pqrs.org/osx/karabiner/index.html) config to [make a "soft" Meta key](https://github.com/pqrs-org/KE-complex_modifications/pull/441).  And in fact I like this work-around as it is in the spirit of "trust each program to do only one thing and do it well".

This is related to #62 .

**Comment by pinn3** [comment] 2019-02-19 22:59
> This likely affects other keys which produce diacritics

Confirmed, getting a similar behaviour with <kbd>Option</kbd>+<kbd>N</kbd>, while having configured
```
 - { key: N,         mods: Alt,       chars: "\x1bn"                       }
```

<kbd>Option</kbd>+<kbd>N</kbd> <kbd>B</kbd>
Produces `˜b`

**Comment by chrisduerr** [comment] 2019-03-18 16:53
Closed as duplicate of https://github.com/jwilm/alacritty/issues/2017.

**Closed by chrisduerr** 2019-03-18 16:53 UTC
