### ISSUE TITLE
Key repeat on long press doesn't work on wayland

### ISSUE THREAD

**Issue by EastAPOLO** [jwilm/alacritty#1712] opened 2018-10-27 19:07 UTC
Which operating system does the issue occur on? Arch Linux

If on linux, are you using X11 or Wayland? Wayland (Sway)

When I try to hold backspace nothing happens, I have to press it each time for the cursor to go back. When I am working in vim holding j to go down or any of the other keys to navigate in a file doesn't work, has to be pressed each time. 

I tried alacritty-git in the arch user repository and it still does that. I was originally running alacritty using the package from community repo.

**Comment by chrisduerr** [comment] 2018-10-27 19:38
Duplicate of https://github.com/jwilm/alacritty/issues/1257.

**Closed by chrisduerr** 2018-10-27 19:38 UTC
