### ISSUE TITLE
Unable to parse Cargo.toml

### ISSUE THREAD

**Issue by alejandrorosas** [jwilm/alacritty#1458] opened 2018-07-21 09:39 UTC
Hi,

I was trying to install alacritty on a ubuntu and after running `cargo install cargo-deb` I've got:

```
cargo-deb: unable to parse Cargo.toml
  because: invalid type: integer `1`, expected a boolean for key `profile.release.debug`
```

Which operating system does the issue occur on?
Ubuntu 16.04.1

If on linux, are you using X11 or Wayland?
X11

**Comment by chrisduerr** [comment] 2018-07-21 11:11
This is a bug in `cargo-deb`, it has already been fixed and is going to be in the next release once an update to `crates.io` is pushed.

This is a duplicate of #1438, which also has some information on how to install the latest version of `cargo-deb` directly from github.

**Closed by chrisduerr** 2018-07-21 11:11 UTC

**Comment by alejandrorosas** [comment] 2018-07-22 09:29
thanks @chrisduerr
