### ISSUE TITLE
abnormal font position (always align bottom)

### ISSUE THREAD

**Issue by LER0ever** [jwilm/alacritty#485] opened 2017-03-17 00:31 UTC
As you can see in the pic below, especially the airline/powerline, the fonts are like stick to the bottom, and the y-offset can only adjust the height above the font. 
It would probably be better if the font is centered in line height instead of sinked in the bottom.
![image](https://cloud.githubusercontent.com/assets/10568668/24024066/777c27dc-0a7e-11e7-903a-43bcebd24128.png)

I'm using Manjaro Linux 17.0
Installed alacritty from AUR.
The terminal font is a powerline-patched Hack font called Knack Nerd Font

**Comment by kreedz** [comment] 2017-03-18 18:03
Same.
![2017-03-18-225920_1366x768_scrot](https://cloud.githubusercontent.com/assets/2128965/24074663/468d1946-0c37-11e7-9f43-38e02c00e723.png)

**Comment by nikolowry** [comment] 2017-03-25 02:32
![2017-03-24-22 31 30-alacritty-vs-termite-line-height-comparison-screenshot](https://cloud.githubusercontent.com/assets/597310/24318788/c32b2fde-10e1-11e7-8fd2-67a06a6d2d7c.png)

Termite (Left) vs Alacritty (Right)

**Comment by squareduck** [comment] 2017-03-31 06:18
This issue has a solution in this pull request:
https://github.com/jwilm/alacritty/pull/317

I use it at the moment and with a bit of tinkering with glyph offsets fonts look better than in iTerm.
It looks like it's ready to be merged, but it's been this way for quite a while.

**Comment by ryanoasis** [comment] 2017-03-31 17:59
If the problem is related to the font (looks like it might not be?) then there will be fixes in v1.1 of [Nerd Fonts](https://github.com/ryanoasis/nerd-fonts): https://github.com/ryanoasis/nerd-fonts/issues/142#issuecomment-287571485

**Comment by nikolowry** [comment] 2017-04-02 23:21
But @squareduck even if I switch to the a non-powerline monospace font the line-height of fonts is  permanently 1.  The offset does nothing to help because it pulls the type only in one direction and does not equally disperse "padding" to the top and bottom.

While the "x" offset does do a good group at spacing, the "y" offset will never be a true replacement for real line-height control.

**Comment by riquito** [comment] 2017-05-02 17:20
I think that this issue has been solved by [PR 317 - Add Glyph Offset Option to User Configuration](https://github.com/jwilm/alacritty/pull/317), now on master

**Comment by jwilm** [comment] 2017-05-02 18:33
Thanks for following up on this issue @riquito. The vertical centering issue should be solvable now with a combination of `offset` and `glyph_offset` configuration. Please see #533 for additional info.

**Closed by jwilm** 2017-05-02 18:33 UTC
Labels: M - fonts, T - enhancement

**Comment by PezCoder** [comment] 2020-05-12 19:36
A little note on this, while I tried to adjust the fonts here.
1. You'll need to restart alacritty for `glyph_offset` changes to take effect
2. Keep the glyph_offset as half of the offset is my rule of thumb. My offset y was: 15 hence a glyph_offset y of 8 just worked out for me.

Hope this helps.
