### ISSUE TITLE
[Linux] Font anti-aliasing configuration issue

### ISSUE THREAD

**Issue by andreyorst** [jwilm/alacritty#940] opened 2017-12-11 10:53 UTC
Arch Linux, X11, KDE Plasma 5.11.4.
Builds from git and aur both.

I didn't configure my fonts sync installation of archlinux, and they are fine in konsole and other vte terms, like gnome-terminal, xfce4, etc. But in alacritty they're looking just like in editors. I like how fonts look int editors, but I don't think that terminal should use same rules for font rendering. I use alot of unicode characters and for example zsh and Vim looks blurry in alacritty.
![image](https://user-images.githubusercontent.com/19470159/33825811-e19c024e-de73-11e7-9aa8-3178639bff7e.png)

Alacritty suggests to disable rgba, but nothing changes in particular, I've tryed a lot of configurations, and still my fonts look blurry in alacritty. Even with font-antialiasing switched off completely (fonts look bad everywhere in the system), alacritty shows bad fonts compared to other terms:
![image](https://user-images.githubusercontent.com/19470159/33827397-49231fd8-de79-11e7-9830-dd92bf9c776a.png)
(alacritty at the top, any other term at the bottom)

With these settings:
```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <dir>~/.fonts</dir>
 <match target="font">
  <edit name="rgba" mode="assign">
   <const>none</const>
  </edit>
 </match>
 <match target="font">
  <edit name="hinting" mode="assign">
   <bool>false</bool>
  </edit>
 </match>
 <match target="font">
  <edit name="hintstyle" mode="assign">
   <const>hintnone</const>
  </edit>
 </match>
 <match target="font">
  <edit name="antialias" mode="assign">
   <bool>true</bool>
  </edit>
 </match>
</fontconfig>
```
fonts look like this:
![image](https://user-images.githubusercontent.com/19470159/33827551-cf533afc-de79-11e7-8b2a-4fcbcfea26bb.png)
(xfce4 at the top, alacritty at the bottom)
Which is slightly better, then in the beginning, but still nothing in comparison with other terms.
Am I doing something wrong? Or I missed something in configuration?

Test symbols, if needed
```
┌─╼[~] 
└────╼ 
```

**Comment by jwilm** [comment] 2017-12-11 16:40
I would suggest trying with `hintslight` for the `"hintstyle"` property. I can investigate further if that doesn't resolve it.

**Comment by andreyorst** [comment] 2017-12-11 18:25
Tried as you suggested, but no luck. 
![image](https://user-images.githubusercontent.com/19470159/33846624-abaf37f6-deb8-11e7-95fb-9c1098cc5982.png)
What I fugured out is font remains blurry only when font size is not even. 9 - blurry, 10 - clear, 11 - blurry, and so on for even really big values. 
![screenshot_20171211_212305](https://user-images.githubusercontent.com/19470159/33846816-7c6e8784-deb9-11e7-969b-1e794bcf64a4.png)
![screenshot_20171211_212313](https://user-images.githubusercontent.com/19470159/33846826-8078c0d8-deb9-11e7-8971-3bb90e656b23.png)

**Comment by chrisduerr** [comment] 2017-12-11 19:39
I'm not sure if this is the same problem, but it kinda looks similar. I'm having problems with symbols kinda "overlapping".

This is how grid characters are looking for me:
![Image](https://u.teknik.io/7N4Sb.png)

**Comment by yshui** [comment] 2018-02-08 10:56
Same problem here. Changing the fonts.conf seems to have no effect on how the font is rendered in alacritty

**Comment by jwilm** [comment] 2018-05-05 15:14
Duplicate of #118

**Closed by jwilm** 2018-05-05 15:14 UTC
