### ISSUE TITLE
Panics if no imei application is running

### ISSUE THREAD

**Issue by umurgdk** [jwilm/alacritty#701] opened 2017-07-30 10:51 UTC
Not all the linux environments running IME automatically. In my case I just run ibus xim on demand. Alacritty panics if ibus xim is not working at that moment

**Comment by NickHu** [comment] 2018-04-11 08:24
Possible duplicate of #830

**Comment by chrisduerr** [comment] 2018-05-15 21:35
Thanks for mentioning the duplication. Closing this in favor of #830 (even though this came first the other seems to have more relevant information).

**Closed by chrisduerr** 2018-05-15 21:35 UTC
