### ISSUE TITLE
Right Vertical Box Line; draws wrong

### ISSUE THREAD

**Issue by mountainstorm** [jwilm/alacritty#1670] opened 2018-10-17 15:27 UTC
The "right vertical box line" (\u23b9) draws wrong; it draws as the left one (\u23b8)

python -c  "print(u'\u23b8\nH\n\u23b9\n\u23b9\n')"

It also doesn't connect forming a smooth line; thus making it unsuitable for box drawing

macOS 10.14

**Comment by chrisduerr** [comment] 2018-10-17 21:34
@mountainstorm I'm afraid your response didn't get displayed the way you wanted it to. I can't see any of the images on github.

**Comment by mountainstorm** [comment] 2018-10-17 22:10
This is what Alacritty looks like.
<img width="320" alt="pastedgraphic-1" src="https://user-images.githubusercontent.com/1919087/47119096-7050de80-d21e-11e8-9a0b-7073ead27c96.png">

This is what Terminal.app looks like.
<img width="30" alt="pastedgraphic-2" src="https://user-images.githubusercontent.com/1919087/47119110-7a72dd00-d21e-11e8-9609-ced99c9897f7.png">

You can see that Alacritty has two problems;
1. it is drawing the "right vertical box line" (\u23b9) codepoint as the "left vertical box line" (\u23b8) codepoint.
2. The vertical box lines don't cover the whole height of the character cell

You can also see that whilst Terminal.app draws the correct character, and it's full height, it has a similar to you "smooth line" (overlapping one).

**Comment by chrisduerr** [comment] 2018-10-18 20:41
This looks like a font fallback issue to me (see #1560).

The rendering at the left side is not because Alacritty does something incorrectly, but rather because the font puts it there. This is likely also why there is a gap between the lines, since the line height of the other font is not the same as the line height of your primary font.

**Comment by mountainstorm** [comment] 2018-10-19 00:57
I've had a look through FontBook (macOS) and you appear to be right; my font is both missing those code points.  So "something" is happening to make it choose them from elsewhere. 

IS there a workaround or do I need to find/make a patched version of my font with those characters?

**Comment by chrisduerr** [comment] 2018-10-19 08:02
Unfortunately the RFC for font configuration #957 is still a WIP. That might allow you to specify fallback fonts yourself. Currently I don't think there's a way to do this on macOS. On Linux you could set up your fontconfig fallbacks though.

Closing this as a duplicate of #1560 then. If you have any more questions, feel free to ask them there.

**Closed** 2018-10-19 08:02 UTC
Labels: F - duplicate
