### ISSUE TITLE
Funny bug on NeoVIM

### ISSUE THREAD

**Issue by roehst** [jwilm/alacritty#684] opened 2017-07-22 00:37 UTC
Hi, I have a funny bug.

When I change the colorscheme on NVIM and scroll the screen down, the background color gets messed up. But this does NOT happen if the screen is small enough.

Interestingly enough, when I record the session using ASCII cinema, it looks correct.

![image](https://user-images.githubusercontent.com/21047691/28486781-887081cc-6e5c-11e7-8944-b11a35866df1.png)

**Comment by DivineGod** [comment] 2017-07-22 07:15
This is probably the same bug as #123

**Comment by gmile** [comment] 2017-07-23 00:16
@DivineGod are you using neovim tagged as 0.2.0, or the one from master?

I've been using 0.2.0 and seeing this behavior as well. As a workaround, try setting `TERM` env to `""`:

```
TERM="" nvim
```
As a permanet fix, try installing neovim from sources (I just did today, and it works well; had to remove the workaround above that I had in place for some time).

**Comment by jwilm** [comment] 2017-07-23 16:30
@DivineGod I thought there was a ticket already but couldn't find it; thanks for the comment!

Duplicate of #123.

**Closed by jwilm** 2017-07-23 16:30 UTC
