### ISSUE TITLE
X11: No redraw when resizing in tiling WM (xmonad)

### ISSUE THREAD

**Issue by jbrechtel** [jwilm/alacritty#1884] opened 2018-12-08 16:10 UTC
Which operating system does the issue occur on?

ArchLinux
`Linux dev 4.19.4-arch1-1-ARCH #1 SMP PREEMPT Fri Nov 23 09:06:58 UTC 2018 x86_64 GNU/Linux`

My NVIDIA versions
```
lib32-nvidia-utils 415.22-1
nvidia 415.22-1
nvidia-settings 415.22-1
nvidia-utils 415.22-1
opencl-nvidia-beta 390.25-1
```

If on linux, are you using X11 or Wayland?
X11

-----

I've had this problem for a while now and I keep checking Alacritty to see if it's gone away. I can't seem to find any other issues that match this description exactly (several are close, though). Essentially, when an alacritty window gets resized, then the text that no longer fits in the new size does not get reflowed *and* once the window is put back in its original size then the old text is no longer visible and never gets redrawn.

I'm not actually sure which behavior alacritty even wants to do here (reflow or redraw) but I suspect at least one of those two behaviors is intended.

I've attached a gif showing the behavior. I can link to a higher resolution MP4 if that's desired or if more detail is needed please let me know.

![ezgif-4-2e6e4611a4d0](https://user-images.githubusercontent.com/72143/49688005-9df92c00-fad9-11e8-934d-ff53268342f1.gif)

Notably, this also happens if I'm using i3wm.

**Comment by chrisduerr** [comment] 2018-12-08 16:18
This is a duplicate of https://github.com/jwilm/alacritty/issues/591.

**Closed by chrisduerr** 2018-12-08 16:18 UTC

**Comment by chrisduerr** [comment] 2018-12-08 16:37
@jbrechtel No problem, there are so many issues that it's hard to find exactly what you're looking for sometimes!
