### ISSUE TITLE
Colors are drastically darker than Terminal.app

### ISSUE THREAD

**Issue by josefaidt** [jwilm/alacritty#2537] opened 2019-06-13 20:45 UTC
macOS 10.14.5

![image](https://user-images.githubusercontent.com/5033303/59465823-63a67980-8df1-11e9-95d0-49130934dfef.png)
*Pictured left to right: Terminal.app, Alacritty*

Just installed Alacritty this morning and converted a theme, Lavandula, to use. However the colors are *much* darker in Alacritty than Terminal.app or iTerm2. I'm not quite sure what may be causing this, perhaps I need to adjust the color scheme to cater to Alacritty?

Any insight is appreciated! I've dug through a few resources like the [announcement blog post](https://jwilm.io/blog/announcing-alacritty/) looking for information on the colors to no avail. I'm really enjoying the product thus far.

**Comment by chrisduerr** [comment] 2019-06-13 20:50
This is a duplicate of https://github.com/jwilm/alacritty/issues/2468.

**Closed by chrisduerr** 2019-06-13 20:50 UTC

**Comment by josefaidt** [comment] 2019-06-13 20:59
Hi @chrisduerr boy you are quick. Is this behavior due to the use of OpenGL? I'm trying to figure out how to programmatically adjust my color scheme without manually adjusting. Do you have any insight as to how these colors should be adjusted? Perhaps I can document this later for newcomers as it certainly threw me for a loop.

**Comment by chrisduerr** [comment] 2019-06-13 21:20
Alacritty actually doesn't adjust the colors at all, however Terminal.app does adjust them. So the problem is not that Alacritty is adjusting them, but that it is not.

You'll likely be able to match the colors by getting a colorpicker out and then using those hex values, rather than going by what hex values you've defined in terminal.app. For foreground stuff you can probably invert it by selecting to get better results, otherwise you'll likely run into aliasing issues which will mess with the colors reported.

**Comment by josefaidt** [comment] 2019-06-14 00:16
Apologies I was suggesting adjusting the colors myself to match what I've been used to in Terminal.app, but you do make a good point. I'll port it with the color dropper
