### ISSUE TITLE
Anything special alacritty did for `Alt + n`?

### ISSUE THREAD

**Issue by tinder-falood** [jwilm/alacritty#2873] opened 2019-10-12 15:36 UTC
Which operating system does the issue occur on?
Macos 10.14.5

I tried alacritty master branch, v0.3.3, v0.3.0 and v0.2.9, I can reproduce this for all these versions.

I'm using emacs(https://github.com/remacs/remacs) inside alacritty with
```
key_bindings:
  - { key: N, mods: Alt, chars: "\x1bn" }
  - { key: P, mods: Alt, chars: "\x1bp" }

shell:
 program: /path/to/remacsclient
 args:
   - -t
```

I bind `alt-n` and `alt-p` to the same command in emacs, and when I triggered it with `alt-p` everything works well but when I triggered it with `alt-n`, I got extra `~` char at the cursor.
Also, when I type `Esc` `n` instead of `Alt-n`, everything works well.

I also tried the same thing on the Terminal, no this issue.

Thanks

attached all my config file, hope it's helpful.

```
draw_bold_text_with_bright_colors: true
dynamic_title: true
hide_cursor_when_typing: false
live_config_reload: true

window:
  decorations: none

font:
  normal:
    family: monofur for Powerline
    style: Regular
  bold:
    family: monofur for Powerline
    style: Bold
  italic:
    family: monofur for Powerline
    style: Italic
  size: 16.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  scale_with_dpi: true
  use_thin_strokes: true

colors:
  primary:
    background: '0x2e3440'
    foreground: '0xd8dee9'

  cursor:
    text: '0x2e3440'
    cursor: '0xd8dee9'

  normal:
    black: '0x3b4252'
    red: '0xbf616a'
    green: '0xa3be8c'
    yellow: '0xebcb8b'
    blue: '0x81a1c1'
    magenta: '0xb48ead'
    cyan: '0x88c0d0'
    white: '0xe5e9f0'

  bright:
    black: '0x4c566a'
    red: '0xbf616a'
    green: '0xa3be8c'
    yellow: '0xebcb8b'
    blue: '0x81a1c1'
    magenta: '0xb48ead'
    cyan: '0x8fbcbb'
    white: '0xeceff4'

visual_bell:
  animation: EaseOutExpo
  duration: 0

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: true

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>_-"
  save_to_clipboard: true

shell:
 program: /path/to/remacsclient
 args:
   - -t

key_bindings:
  - { key: Home,                    chars: "\x1bOH",   mode: AppCursor   }
  - { key: Home,                    chars: "\x1b[1~",  mode: ~AppCursor  }
  - { key: End,                     chars: "\x1bOF",   mode: AppCursor   }
  - { key: End,                     chars: "\x1b[4~",  mode: ~AppCursor  }
  - { key: PageUp,                  chars: "\x1b[5~"                     }
  - { key: PageDown,                chars: "\x1b[6~"                     }
  - { key: Left,     mods: Shift,   chars: "\x1b[1;2D"                   }
  - { key: Left,     mods: Control, chars: "\x1b[1;5D"                   }
  - { key: Left,     mods: Alt,     chars: "\x1b[1;3D"                   }
  - { key: Left,                    chars: "\x1b[D",   mode: ~AppCursor  }
  - { key: Left,                    chars: "\x1bOD",   mode: AppCursor   }
  - { key: Right,    mods: Shift,   chars: "\x1b[1;2C"                   }
  - { key: Right,    mods: Control, chars: "\x1b[1;5C"                   }
  - { key: Right,    mods: Alt,     chars: "\x1b[1;3C"                   }
  - { key: Right,                   chars: "\x1b[C",   mode: ~AppCursor  }
  - { key: Right,                   chars: "\x1bOC",   mode: AppCursor   }
  - { key: Up,       mods: Shift,   chars: "\x1b[1;2A"                   }
  - { key: Up,       mods: Control, chars: "\x1b[1;5A"                   }
  - { key: Up,       mods: Alt,     chars: "\x1b[1;3A"                   }
  - { key: Up,                      chars: "\x1b[A",   mode: ~AppCursor  }
  - { key: Up,                      chars: "\x1bOA",   mode: AppCursor   }
  - { key: Down,     mods: Shift,   chars: "\x1b[1;2B"                   }
  - { key: Down,     mods: Control, chars: "\x1b[1;5B"                   }
  - { key: Down,     mods: Alt,     chars: "\x1b[1;3B"                   }
  - { key: Down,                    chars: "\x1b[B",   mode: ~AppCursor  }
  - { key: Down,                    chars: "\x1bOB",   mode: AppCursor   }
  - { key: Tab,      mods: Shift,   chars: "\x1b[Z"                      }
  - { key: F1,                      chars: "\x1bOP"                      }
  - { key: F2,                      chars: "\x1bOQ"                      }
  - { key: F3,                      chars: "\x1bOR"                      }
  - { key: F4,                      chars: "\x1bOS"                      }
  - { key: F5,                      chars: "\x1b[15~"                    }
  - { key: F6,                      chars: "\x1b[17~"                    }
  - { key: F7,                      chars: "\x1b[18~"                    }
  - { key: F8,                      chars: "\x1b[19~"                    }
  - { key: F9,                      chars: "\x1b[20~"                    }
  - { key: F10,                     chars: "\x1b[21~"                    }
  - { key: F11,                     chars: "\x1b[23~"                    }
  - { key: F12,                     chars: "\x1b[24~"                    }
  - { key: Back,                    chars: "\x7f"                        }
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                    }
  - { key: Insert,                  chars: "\x1b[2~"                     }
  - { key: Delete,                  chars: "\x1b[3~",  mode: AppKeypad   }
  - { key: Delete,                  chars: "\x1b[P",   mode: ~AppKeypad  }

  - { key: A, mods: Alt, chars: "\x1ba" }
  - { key: B, mods: Alt, chars: "\x1bb" }
  - { key: C, mods: Alt, chars: "\x1bc" }
  - { key: D, mods: Alt, chars: "\x1bd" }
  - { key: E, mods: Alt, chars: "\x1be" }
  - { key: F, mods: Alt, chars: "\x1bf" }
  - { key: G, mods: Alt, chars: "\x1bg" }
  - { key: H, mods: Alt, chars: "\x1bh" }
  - { key: I, mods: Alt, chars: "\x1bi" }
  - { key: J, mods: Alt, chars: "\x1bj" }
  - { key: K, mods: Alt, chars: "\x1bk" }
  - { key: L, mods: Alt, chars: "\x1bl" }
  - { key: M, mods: Alt, chars: "\x1bm" }
  - { key: N, mods: Alt, chars: "\x1bn" }
  - { key: O, mods: Alt, chars: "\x1bo" }
  - { key: P, mods: Alt, chars: "\x1bp" }
  - { key: Q, mods: Alt, chars: "\x1bq" }
  - { key: R, mods: Alt, chars: "\x1br" }
  - { key: S, mods: Alt, chars: "\x1bs" }
  - { key: T, mods: Alt, chars: "\x1bt" }
  - { key: U, mods: Alt, chars: "\x1bu" }
  - { key: V, mods: Alt, chars: "\x1bv" }
  - { key: W, mods: Alt, chars: "\x1bw" }
  - { key: X, mods: Alt, chars: "\x1bx" }
  - { key: Y, mods: Alt, chars: "\x1by" }
  - { key: Z, mods: Alt, chars: "\x1bz" }

  - { key: A, mods: Alt|Shift, chars: "\x1bA" }
  - { key: B, mods: Alt|Shift, chars: "\x1bB" }
  - { key: C, mods: Alt|Shift, chars: "\x1bC" }
  - { key: D, mods: Alt|Shift, chars: "\x1bD" }
  - { key: E, mods: Alt|Shift, chars: "\x1bE" }
  - { key: F, mods: Alt|Shift, chars: "\x1bF" }
  - { key: G, mods: Alt|Shift, chars: "\x1bG" }
  - { key: H, mods: Alt|Shift, chars: "\x1bH" }
  - { key: I, mods: Alt|Shift, chars: "\x1bI" }
  - { key: J, mods: Alt|Shift, chars: "\x1bJ" }
  - { key: K, mods: Alt|Shift, chars: "\x1bK" }
  - { key: L, mods: Alt|Shift, chars: "\x1bL" }
  - { key: M, mods: Alt|Shift, chars: "\x1bM" }
  - { key: N, mods: Alt|Shift, chars: "\x1bN" }
  - { key: O, mods: Alt|Shift, chars: "\x1bO" }
  - { key: P, mods: Alt|Shift, chars: "\x1bP" }
  - { key: Q, mods: Alt|Shift, chars: "\x1bQ" }
  - { key: R, mods: Alt|Shift, chars: "\x1bR" }
  - { key: S, mods: Alt|Shift, chars: "\x1bS" }
  - { key: T, mods: Alt|Shift, chars: "\x1bT" }
  - { key: U, mods: Alt|Shift, chars: "\x1bU" }
  - { key: V, mods: Alt|Shift, chars: "\x1bV" }
  - { key: W, mods: Alt|Shift, chars: "\x1bW" }
  - { key: X, mods: Alt|Shift, chars: "\x1bX" }
  - { key: Y, mods: Alt|Shift, chars: "\x1bY" }
  - { key: Z, mods: Alt|Shift, chars: "\x1bZ" }

  - { key: Key0, mods: Alt, chars: "\x1b0" }
  - { key: Key1, mods: Alt, chars: "\x1b1" }
  - { key: Key2, mods: Alt, chars: "\x1b2" }
  - { key: Key3, mods: Alt, chars: "\x1b3" }
  - { key: Key4, mods: Alt, chars: "\x1b4" }
  - { key: Key5, mods: Alt, chars: "\x1b5" }
  - { key: Key6, mods: Alt, chars: "\x1b6" }
  - { key: Key7, mods: Alt, chars: "\x1b7" }
  - { key: Key8, mods: Alt, chars: "\x1b8" }
  - { key: Key9, mods: Alt, chars: "\x1b9" }

  - { key: Key0, mods: Alt|Shift, chars: "\x1b!" }
  - { key: Key1, mods: Alt|Shift, chars: "\x1b@" }
  - { key: Key2, mods: Alt|Shift, chars: "\x1b#" }
  - { key: Key3, mods: Alt|Shift, chars: "\x1b$" }
  - { key: Key4, mods: Alt|Shift, chars: "\x1b%" }
  - { key: Key5, mods: Alt|Shift, chars: "\x1b^" }
  - { key: Key6, mods: Alt|Shift, chars: "\x1b&" }
  - { key: Key7, mods: Alt|Shift, chars: "\x1b*" }
  - { key: Key8, mods: Alt|Shift, chars: "\x1b(" }
  - { key: Key9, mods: Alt|Shift, chars: "\x1b)" }

  - { key: Key0, mods: Command, chars: "\x080" }
  - { key: Key1, mods: Command, chars: "\x081" }
  - { key: Key2, mods: Command, chars: "\x082" }
  - { key: Key3, mods: Command, chars: "\x083" }
  - { key: Key4, mods: Command, chars: "\x084" }
  - { key: Key5, mods: Command, chars: "\x085" }
  - { key: Key6, mods: Command, chars: "\x086" }
  - { key: Key7, mods: Command, chars: "\x087" }
  - { key: Key8, mods: Command, chars: "\x088" }
  - { key: Key9, mods: Command, chars: "\x089" }

  - { key: Semicolon, mods: Alt, chars: "\x1b;" }
  - { key: Comma,     mods: Alt, chars: "\x1b," }
  - { key: Period,    mods: Alt, chars: "\x1b." }
  - { key: LBracket,  mods: Alt, chars: "\x1b[" }
  - { key: RBracket,  mods: Alt, chars: "\x1b]" }
  - { key: Slash,     mods: Alt, chars: "\x1b/" }
  - { key: Space,     mods: Alt, chars: "\x1b " }
  - { key: Backslash, mods: Alt, chars: "\x1b\\" }

  - { key: Semicolon, mods: Alt|Shift, chars: "\x1b:" }
  - { key: Comma,     mods: Alt|Shift, chars: "\x1b<" }
  - { key: Period,    mods: Alt|Shift, chars: "\x1b>" }
  - { key: LBracket,  mods: Alt|Shift, chars: "\x1b{" }
  - { key: RBracket,  mods: Alt|Shift, chars: "\x1b}" }
  - { key: Slash,     mods: Alt|Shift, chars: "\x1b?" }
  - { key: Backslash, mods: Alt|Shift, chars: "\x1b|" }
```

**Comment by falood** [comment] 2019-10-12 16:13
addition informatin:

I just tried such config to also bind `Cmd-n` to send the same chars with `alt-n`, which also works well

```
  - { key: N, mods: Command, chars: "\x1bn" }
```

**Comment by falood** [comment] 2019-10-13 07:40
I think it's the same issue with https://github.com/jwilm/alacritty/issues/2830

**Comment by chrisduerr** [comment] 2019-10-13 12:32
Yeah, I'm sorry this issue got kinda lost in my queue. This is a duplicate of an issue on macOS where we cannot prevent it from sending its special characters with the option key.

As mentioned in #2830, this is a duplicate of #62 basically and is tracked upstream in https://github.com/rust-windowing/winit/issues/768.

I'm sorry for the delay, but I don't think there's any way around this at the moment.

**Closed by chrisduerr** 2019-10-13 12:32 UTC

**Comment by falood** [comment] 2019-10-13 21:21
Thanks @chrisduerr 

I used [Karabiner](https://pqrs.org/osx/karabiner/index.html) to globally modify `option + n` to `esc + n` with such profile.

It works to me, holp it's also helpful for people who have the same issue

```
                "rules": [
                    {
                        "description": "Change option + n to esc + n",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "n",
                                    "modifiers": {
                                        "mandatory": [
                                            "left_option"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "escape"
                                    },
                                    {
                                        "key_code": "n"
                                    }
                                ],
                                "type": "basic"
                            },
                            {
                                "from": {
                                    "key_code": "n",
                                    "modifiers": {
                                        "mandatory": [
                                            "right_option"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "escape"
                                    },
                                    {
                                        "key_code": "n"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
                ]
```

**Comment by meain** [comment] 2019-10-14 06:41
@falood 

I already had a mapping which was converting caps to alt. So I tried

```
{
    "description": "Change caps_lock + n to esc + n",
    "manipulators": [
        {
            "from": {
                "key_code": "n",
                "modifiers": {
                    "mandatory": [
                        "caps_lock"
                    ]
                }
            },
            "to": [
                {
                    "key_code": "escape"
                },
                {
                    "key_code": "n"
                }
            ],
            "type": "basic"
        }
    ]
}
```
but did not have much luck with it, it was still giving me the same issues.

**Comment by falood** [comment] 2019-10-16 17:10
@meain 
here's my whole config file
```
{
    "global": {
        "check_for_updates_on_startup": true,
        "show_in_menu_bar": true,
        "show_profile_name_in_menu_bar": false
    },
    "profiles": [
        {
            "complex_modifications": {
                "parameters": {
                    "basic.simultaneous_threshold_milliseconds": 50,
                    "basic.to_delayed_action_delay_milliseconds": 500,
                    "basic.to_if_alone_timeout_milliseconds": 1000,
                    "basic.to_if_held_down_threshold_milliseconds": 500,
                    "mouse_motion_to_scroll.speed": 100
                },
                "rules": [
                    {
                        "description": "Change option + n to esc + n",
                        "manipulators": [
                            {
                                "from": {
                                    "key_code": "n",
                                    "modifiers": {
                                        "mandatory": [
                                            "left_option"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "escape"
                                    },
                                    {
                                        "key_code": "n"
                                    }
                                ],
                                "type": "basic"
                            },
                            {
                                "from": {
                                    "key_code": "n",
                                    "modifiers": {
                                        "mandatory": [
                                            "right_option"
                                        ]
                                    }
                                },
                                "to": [
                                    {
                                        "key_code": "escape"
                                    },
                                    {
                                        "key_code": "n"
                                    }
                                ],
                                "type": "basic"
                            }
                        ]
                    }
                ]
            },
            "devices": [
                {
                    "disable_built_in_keyboard_if_exists": false,
                    "fn_function_keys": [],
                    "identifiers": {
                        "is_keyboard": true,
                        "is_pointing_device": false,
                        "product_id": 636,
                        "vendor_id": 1452
                    },
                    "ignore": false,
                    "manipulate_caps_lock_led": true,
                    "simple_modifications": [
                        {
                            "from": {
                                "key_code": "caps_lock"
                            },
                            "to": {
                                "key_code": "left_command"
                            }
                        },
                        {
                            "from": {
                                "key_code": "left_command"
                            },
                            "to": {
                                "key_code": "left_control"
                            }
                        },
                        {
                            "from": {
                                "key_code": "right_command"
                            },
                            "to": {
                                "key_code": "right_control"
                            }
                        }
                    ]
                },
                {
                    "disable_built_in_keyboard_if_exists": false,
                    "fn_function_keys": [],
                    "identifiers": {
                        "is_keyboard": true,
                        "is_pointing_device": false,
                        "product_id": 24616,
                        "vendor_id": 7504
                    },
                    "ignore": false,
                    "manipulate_caps_lock_led": false,
                    "simple_modifications": []
                }
            ],
            "fn_function_keys": [
                {
                    "from": {
                        "key_code": "f1"
                    },
                    "to": {
                        "key_code": "f1"
                    }
                },
                {
                    "from": {
                        "key_code": "f2"
                    },
                    "to": {
                        "key_code": "f2"
                    }
                },
                {
                    "from": {
                        "key_code": "f3"
                    },
                    "to": {
                        "key_code": "f3"
                    }
                },
                {
                    "from": {
                        "key_code": "f4"
                    },
                    "to": {
                        "key_code": "f4"
                    }
                },
                {
                    "from": {
                        "key_code": "f5"
                    },
                    "to": {
                        "key_code": "f5"
                    }
                },
                {
                    "from": {
                        "key_code": "f6"
                    },
                    "to": {
                        "key_code": "f6"
                    }
                },
                {
                    "from": {
                        "key_code": "f7"
                    },
                    "to": {
                        "key_code": "f7"
                    }
                },
                {
                    "from": {
                        "key_code": "f8"
                    },
                    "to": {
                        "key_code": "f8"
                    }
                },
                {
                    "from": {
                        "key_code": "f9"
                    },
                    "to": {
                        "key_code": "f9"
                    }
                },
                {
                    "from": {
                        "key_code": "f10"
                    },
                    "to": {
                        "key_code": "f10"
                    }
                },
                {
                    "from": {
                        "key_code": "f11"
                    },
                    "to": {
                        "key_code": "f11"
                    }
                },
                {
                    "from": {
                        "key_code": "f12"
                    },
                    "to": {
                        "key_code": "f12"
                    }
                }
            ],
            "name": "ergodox",
            "parameters": {
                "delay_milliseconds_before_open_device": 1000
            },
            "selected": true,
            "simple_modifications": [],
            "virtual_hid_keyboard": {
                "country_code": 0,
                "mouse_key_xy_scale": 100
            }
        }
    ]
}
```

**Comment by meain** [comment] 2019-10-18 03:51
Alacritty does not seem to handle `esc` + `n` for me. Atleast it does not do anything.
I have to look a bit more into this.
