### ISSUE TITLE
Weechat rendering improperly 

### ISSUE THREAD

**Issue by Succo** [jwilm/alacritty#290] opened 2017-01-11 16:42 UTC
Hi

I'm not sure who is wrong between weechat (the irc client) and alacritty, but it seems to render improperly in alacritty.

![screenshot from 2017-01-11 17-23-45](https://cloud.githubusercontent.com/assets/8531875/21857180/dbc22e3a-d824-11e6-95ce-50a9a974a1c6.png)

You can see on the attached picture, the vertical line of blue X should be a thin bleu line. And the horizontal status line should be blue not just around the word but from beginning to end.

I can provide better comparison screenshoot or debuging info if needed. I'd just rather avoid publishing too many info about my chats online.

**Comment by jwilm** [comment] 2017-01-11 16:55
The `x`s are due to a lack of graphics mode support. We've got an issue for that: #263.

The horizontal bar is either improperly displaying some invisible characters or it's the same issue as with `htop`: #195.

**Comment by xyin96** [comment] 2017-02-02 01:13
What is your `$TERM` set to (`$ echo $TERM`)?
This issue doesn't seem to occur if you're using `screen` or `screen-256colors`. It seems to only happen to me when it's set to `xterm` or `xterm-256colors`.

**Comment by jwilm** [comment] 2017-02-02 01:44
The `x`s should be fixed on master, and the color issue is easy [now that we know what the problem is](https://github.com/jwilm/alacritty/issues/85#issuecomment-272072183).

**Comment by jwilm** [comment] 2017-02-02 01:45
@xyin96 the reason it doesn't work with `xterm` and `xterm-256colors` is that they both claim to support _background color erase_ which Alacritty doesn't but should (we are claiming to be `xterm-256colors`).

**Closed** 2017-04-04 03:44 UTC
Labels: T - bug
