### ISSUE TITLE
Feature request: Scrolling

### ISSUE THREAD

**Issue by aurabindo** [jwilm/alacritty#173] opened 2017-01-07 11:28 UTC
Heading says it all. I only see escape characters in the terminal when I try to scroll.

**Comment by g2p** [comment] 2017-01-07 11:32
Duplicate of #124.

**Closed** 2017-01-07 20:34 UTC

**Comment by mordof-work** [comment] 2017-03-31 14:29
Maybe I've got the wrong idea about the intention behind this ticket, but those aren't duplicates to me. The capability to scroll is not the same as the feature of scrollback.

Capability to scroll means that in tmux copy mode, I could scroll with my mouse wheel (which currently doesn't work for me, and I'm having a bit of a hard time finding where to do that). That has nothing to do with scrollback in alacritty. As to whether the OP was referring to that.... I have no idea.

**Comment by mordof-work** [comment] 2017-03-31 14:31
On second examination - I note that the OP stated escape characters showing up in his terminal. That means his scrolling is fine, and requesting scrollback. >.>;; ignore me and my incoherent ramblings.
