### ISSUE TITLE
Rendering issue with minimize windows

### ISSUE THREAD

**Issue by Jangmingjin** [jwilm/alacritty#3047] opened 2019-11-28 13:10 UTC
![alacritty](https://user-images.githubusercontent.com/28175935/69808758-46405d00-1223-11ea-85eb-e75e9ad30e87.gif)

Once I have minimized the window and restore, the contents alignment is broken

OS: Windows 10
Font: Hack Nerd Font
Font Size: 9.0

And also resizing is still not working properly

**Comment by chrisduerr** [comment] 2019-11-30 07:19
Which shell are you running? It looks like cmd, since I think powershell prints something different about the prompt at startup?

I'd recommend trying another shell, either cmd/powershell (depending on which one you're running right now), maybe that will already help.

**Comment by Jangmingjin** [comment] 2019-11-30 10:30
I have set default shell as cmd

**Comment by Jangmingjin** [comment] 2019-11-30 11:05
I have tried with powershell and it looks same
![alacritty](https://user-images.githubusercontent.com/28175935/69899642-40be5080-13a4-11ea-9ea9-9dfde7abf467.gif)

**Comment by chrisduerr** [comment] 2019-11-30 12:26
When resizing the window with cmd.exe or powershell.exe, does that cause content to be lost? So when sizing it back to a bigger window size, will the columns you've shrunk the terminal still be gone?

I believe that's a problem with cmd.exe/powershell.exe internally, since they manually delete content on resize. So generally this wouldn't be a problem with a different shell I think and a resize should fix it, however with Microsoft's shells it cannot work this way.

We'll likely have to make sure minimizing does not change window properties with our winit depedency if this is the case. If resizing should show the errors I've just talked about, please share the output of `alacritty -v` when minimizing, which should print window size changes.

**Comment by Jangmingjin** [comment] 2019-12-01 09:58
I have tried with WSL, Powershell core and cmd
![image](https://user-images.githubusercontent.com/28175935/69912423-1e8c0780-1464-11ea-921a-c622e782c4d2.png)
When minimize, the width has been changed into 9

**Comment by chrisduerr** [comment] 2019-12-01 14:58
It seems like when a window is minimized on Windows, we get a resize event to width and height 0x0. Then when it is maximized again, the width and height is restored, but since Windows' WinPTY backend does some resizing magic itself behind the scenes, it's not possible for us to restore the truncated text.

Could you try setting [this config option](https://github.com/jwilm/alacritty/blob/master/alacritty.yml#L349) to `true` and starting Alacritty with `alacritty -v` again?

**Comment by Jangmingjin** [comment] 2019-12-01 15:58
![image](https://user-images.githubusercontent.com/28175935/69916481-6cb9fe80-1496-11ea-84a4-60a3e1f7dd6c.png)
Thanks for your updating
Once I have set `enable_experimental_conpty_backend`:`true`, the last issue has been fixed
But when restored the windows, current line is not visible

**Comment by chrisduerr** [comment] 2019-12-01 16:14
So the prompt is missing? What happens when you press 'enter', 'space' or 'backspace'?

**Comment by Jangmingjin** [comment] 2019-12-01 16:20
When press `enter` or any key, the scroll just move to bottom
![image](https://user-images.githubusercontent.com/28175935/69916715-86107a00-1499-11ea-8d1b-94c961f4cf58.png)

**Comment by chrisduerr** [comment] 2019-12-05 16:28
Sorry for the delay, but is it correct that the prompt just never shows up again? That seems very strange. But the space for the prompt is still reserved?

Can you reproduce this by making the window very small and then making it big again?

**Comment by MayhemYDG** [comment] 2019-12-05 17:22
Before:
![image](https://user-images.githubusercontent.com/567105/70258136-92d7eb00-1783-11ea-9fee-9956eced768d.png)

After minimizing and restoring:
![image](https://user-images.githubusercontent.com/567105/70258152-9bc8bc80-1783-11ea-8654-9cf239250067.png)

You can scroll back to see the output:
![image](https://user-images.githubusercontent.com/567105/70258210-b307aa00-1783-11ea-958a-689b4f473b4a.png)

As you can see `≡` is missing somehow, and the cursor has shifted.

**Comment by MayhemYDG** [comment] 2019-12-05 17:23
If you have alacritty minimized while some output is being written, then restore the window, this is what I see after I scroll back up:

![image](https://user-images.githubusercontent.com/567105/70258344-f6faaf00-1783-11ea-8908-ffca49c7824a.png)

**Comment by chrisduerr** [comment] 2019-12-05 17:37
@MayhemYDG That result should only happen with WinPTY, which is not an Alacritty bug. Please switch to ConPTY.

**Comment by MayhemYDG** [comment] 2019-12-05 17:39
I have `enable_experimental_conpty_backend: true` in my config, and I'm on win10 1909, so I believe I'm already on ConPTY.

**Comment by chrisduerr** [comment] 2019-12-05 17:44
When running `alacritty -v`, make sure it's telling you that ConPTY is used.

**Comment by MayhemYDG** [comment] 2019-12-05 17:46
ConPTY is used indeed:
![image](https://user-images.githubusercontent.com/567105/70259937-2a8b0880-1787-11ea-97fc-81938d974876.png)

**Comment by Jangmingjin** [comment] 2019-12-05 17:48
How to switch into conPty?

**Comment by chrisduerr** [comment] 2019-12-05 17:52
Then it seems like your experience doesn't match up with @Jangmingjin's, who said that issue is fixed with ConPTY.

Can this be reproduced in another terminal emulator on Windows? I feel like this might be an upstream issue.

**Comment by MayhemYDG** [comment] 2019-12-05 18:01
I think I figured out what the issue is:
- alacritty sets the dimensions to 9x19 when minimized
- while conpty(?) handles resizing correctly for what's visible, the output in the scrollback doesn't get resized
- so when restoring the window, alacritty resizes back from 9x19, but that's too small and the entire output was moved back to the scrollback, so it doesn't get restored
video: https://streamable.com/akw1d

**Comment by MayhemYDG** [comment] 2019-12-05 18:05
Tested with the powershell terminal emulator, it handles resizes fine, even in the scrollback.

**Comment by Jangmingjin** [comment] 2019-12-05 18:27
I have tested with WSL, powershell-core and there was same issue

**Comment by chrisduerr** [comment] 2019-12-05 18:28
Resizing should work just fine, however iirc the Windows PTY is interfering with that. I think @davidhewitt has mentioned that in the past, could you confirm this?

Unfortunately both Windows backends are doing a lot of silly stuff that Alacritty can't fix after they've messed it up.

**Comment by MayhemYDG** [comment] 2019-12-05 18:40
![image](https://user-images.githubusercontent.com/567105/70263499-6a092300-178e-11ea-872a-105d175048c8.png)

FWIW minimizing/restoring with Alacritty 0.3.3 works just fine.
I don't mind the scrollback not being perfect as much, but if minimizing/restoring could be fixed that'd be absolutely lovely.

**Comment by chrisduerr** [comment] 2019-12-05 19:50
On 0.3.3 we ignored the resize to 0x0 pixels completely iirc, which is not super great either. It's a bit strange with how the Windows platform behaves here though, since a minimized window is automatically resized by the system to 0x0.

In theory on 0.3.3 you should have the exact same issue when you resize the window yourself.

**Comment by VideoPlayerCode** [comment] 2019-12-05 22:37
@chrisduerr @zacps @davidhewitt 

Yeah during minimize, Windows animates a shrinking effect on the window. I guess you are passing that info along to the terminal which makes conpty/winpty resize itself and lose/rearrange data. So perhaps the solution is to not send the console layer the resizing data when it is related to a window minimize event? 

Could a fix be as easy as ignoring the "window has been resized" event when the wParam flag says that the window is hidden/minimized? https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-size And not passing on the "window is now 0x0 pixels" junk to the console process being run?

Another potential solution is to look for the "window wants to minimize" event and ignoring sizing after that. Windows tells the app that it is about to be hidden/minimized via this event: https://docs.microsoft.com/en-us/windows/win32/winmsg/wm-showwindow

**Comment by chrisduerr** [comment] 2019-12-05 23:28
I'd like to confirm that the Windows PTY is trying to do anything on its own, so could someone edit the following lines and replace both `!is_alt` and `is_alt` with `false`?

https://github.com/jwilm/alacritty/blob/master/alacritty_terminal/src/term/mod.rs#L1088-L1089

**Comment by davidhewitt** [comment] 2019-12-06 03:26
I haven't got the time right now to try the suggested patch (might try over the weekend). However I did just attempt the minimise / restore and can confirm I also have this issue.

AFAIK the windows conpty backend has an internal buffer which it will be scrolling and resizing. It'll then instruct alacritty to redraw the whole window to match its internal buffer. Somewhere the interaction between conpty and alacritty has gone awry.

Alacritty might be able to do something smart to work around it, or we might be able to report it as an upstream bug.

The fact the prompt line also vanishes is equally suspicious.

**Comment by VideoPlayerCode** [comment] 2019-12-06 09:11
Ah, so it may be that the ConPTY and WinPTY backends are responsible for handing the resize events? If Alacrity is responsible, maybe my suggested fix will work: Ignoring the window size events during the "minimize" and "restore" events so that the backend never realizes that the window was shrunk/regrown during minimize/restore. A fix would have to be tested with several actions:

1. Minimize; should be ignored
2. Restore from minimized; should be ignored
3. Maximize (from normal window state); should be applied
4. Restore from maximized; should be applied
5. Minimize and then right click Taskbar and maximize from a minimized state (the minimize resize should be ignored, but the maximize resize after that should be applied).

But of course first the Chris's suggestion should be tested, which I assume disables the resize code from being sent to the backend, to test whether the backend is reacting to windows events on its own without alacrity being at fault...

**Comment by chrisduerr** [comment] 2019-12-06 15:24
> Ah, so it may be that the ConPTY and WinPTY backends are responsible for handing the resize events?

Interactive shells have no business managing these kind of things. While they are of course informed about resize, all history is managed by Alacritty and should not be a concern of the shell at all.

> If Alacrity is responsible, maybe my suggested fix will work: Ignoring the window size events during the "minimize" and "restore" events so that the backend never realizes that the window was shrunk/regrown during minimize/restore.

That would be a workaround, not a fix. Shrinking the window would still show the exact same issue.

**Comment by davidhewitt** [comment] 2019-12-07 22:06
> 
> 
> I'd like to confirm that the Windows PTY is trying to do anything on its own, so could someone edit the following lines and replace both `!is_alt` and `is_alt` with `false`?
> 
> https://github.com/jwilm/alacritty/blob/master/alacritty_terminal/src/term/mod.rs#L1088-L1089

I just had a go at this patch; the issue still occurs.

I don't think it's related, but I'm also seeing one of these each time I minimize / restore:

    [DEBUG] [Unhandled CSI] action='l', args=[25], intermediates=[]

I think this is meant to be `CSI ? 25 l` but it's missing the `?`. Seems like Windows' side may have some bugs here..?

**Comment by chrisduerr** [comment] 2019-12-08 00:28
> I just had a go at this patch; the issue still occurs.

Does the content inside the terminal still get resized, or is it truncated?

**Comment by Jangmingjin** [comment] 2019-12-08 12:15
Hi, what is the status of this issue, since it is a blocking issue?

**Comment by davidhewitt** [comment] 2019-12-09 05:37
> Does the content inside the terminal still get resized, or is it truncated?

To clarify: I'm using ConPTY backend. Setting those arguments to `false` (i.e. disabling the grid reflow), I see the following effects:

- There is significantly less flicker when resizing the window. Because alacritty is no longer reflowing text, only the ConPTY backend is now doing reflowing.
- The text is still vanishing on minimise, and reappears after hitting enter, just like what @Jangmingjin  observes.

It could actually be worth introducing a windows-specific patch to replace `!is_alt` and `is_alt` with false, to reduce the flicker.

**Comment by davidhewitt** [comment] 2019-12-09 06:36
Further results: I've been experimenting what Windows Terminal does in this situation. I've run into what seems to be a bug in Windows Terminal which causes the prompt line to break when the window is resized small enough. Issue is microsoft/terminal#3889 (which was marked as a dupe of microsoft/terminal#1465)

Given that Windows Terminal is also using ConPTY, this is almost certainly the same bug that's causing us problems here. (In particular microsoft/terminal#1465 covers many scenarios which Alacritty would benefit from seeing fixed.)

**Comment by VideoPlayerCode** [comment] 2019-12-09 14:20
@davidhewitt Half-Alacritty, half-upstream. Because Windows Terminal handles minimize + restore properly.

**Comment by davidhewitt** [comment] 2019-12-09 16:05
> This is half-Alacritty, half-upstream. 

Kinda. It's a combination of two upstreams: `winit` fires a zero-size `Resize` event when minimizing. And ConPTY seems not to like being resized to near zero (as per the terminal bug I linked).

Either way, I've got a potential workaround at #3081

**Comment by chrisduerr** [comment] 2019-12-09 17:20
>  I've run into what seems to be a bug in Windows Terminal which causes the prompt line to break when the window is resized small enough.

That's not really a bug, that kinda just naturally happens when you reflow the prompt. That's the behavior of all terminal emulators on all platforms that support reflow.

> It's a combination of two upstreams: winit fires a zero-size Resize event when minimizing. 

Winit just propagates it. The event originates from Windows.

**Closed** 2019-12-09 17:26 UTC
Labels: B - bug, H - windows
