### ISSUE TITLE
Beam, Underline cursor not working

### ISSUE THREAD

**Issue by gglanzani** [jwilm/alacritty#736] opened 2017-08-17 07:49 UTC
Hi there, I've commented on #608 but I guess here it's more appropriate. 

I'm using Alacritty 492d1bd and I don't see the cursor changing when using Neovim. When using iTerm or Terminal.app I do see that, I that *should* rule out issues with my copy of Neovim.

Is there anything I can do to help test/diagnose this?

**Comment by jwilm** [comment] 2017-08-17 16:43
Hmm, might be good to verify that you can manually change with these escape sequences:

```bash
printf "\e[6q" # pipe
printf "\e[4q" # underline
printf "\e[2q" # block
```

**Comment by gglanzani** [comment] 2017-08-17 18:33
Ah, that is very interesting. They indeed actually work from outside neovim. But they are persisted inside neovim, i.e. if I do `printf "\e[6q"` then I get the pipe, and upon launching neovim the cursor remains a pipe, independently of the mode (normal/insert).

Does that help?

**Comment by jwilm** [comment] 2017-08-17 19:48
Sounds like neovim isn't emitting these sequences in Alacritty. What is the value you're using for TERM in both cases?

**Comment by gglanzani** [comment] 2017-08-17 20:03
You mean the `TERM` env variable? It's `xterm-256color` in Alacritty, `xterm` in iTerm.

However if I manually change it to `xterm` in Alacritty, that doesn't help. In nvim the cursor shape still doesn't change.

**Comment by maximbaz** [comment] 2017-08-17 20:12
@gglanzani put this in your .vimrc / init.vim:

```
set guicursor=n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20
```

**Comment by gglanzani** [comment] 2017-08-17 20:19
It's there already

**Comment by maximbaz** [comment] 2017-08-17 20:27
Huh, otherwise it would have been too simple :)
Are you using tmux, and what is your nvim version?

For tmux there is another thing needed:

```
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'
```

It works on my side, with and without tmux, nvim is v0.2.0, so I guess it must be _some_ kind of configuration difference.

**Comment by gglanzani** [comment] 2017-08-17 20:34
No tmux, but fish is the underlying shell. 


I'm using neovim head (of two days ago).

**Comment by maximbaz** [comment] 2017-08-17 20:55
Just tried neovim head, the cursor shapes work there as well. Perhaps try with bash (works for me), and try [my nvim config](https://github.com/maximbaz/dotfiles/blob/master/.config/nvim/init.vim) (just to eliminate the possibility of configuration difference) - remove the first `Plugins` section entirely, nvim will complain on the missing color theme, but the cursor shapes should work.

**Comment by wayneashleyberry** [comment] 2017-08-17 22:47
Interestingly enough, in Alacritty the neovim cursors are working for me _only_ in tmux. iTerm 2 has the cursors working in and out of tmux.

```
NVIM v0.2.1-780-g5b32bce73
tmux 2.5
Alacritty 4e9b1c590e8b0990f5f43fa9d7c53a31a92840a8
zsh 5.4.1 (x86_64-apple-darwin16.7.0)
xterm-256color (outside tmux)
screen-256color (inside tmux)
```

**Comment by gglanzani** [comment] 2017-08-18 14:37
So, I'm not using tmux. I've set alacritty to start with Bash, `TERM` set to `xterm`, and I've tried using an empty .`vimrc` (with the `-u` option) as well as with a `.vimrc` with `set guicursor=n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20`. I've also tried a `.vimrc` with the relevant parts from @maximbaz 's nvim config, i.e.

```viml
set termguicolors
set background=dark
set guioptions+=c
set guioptions-=T
set guioptions-=m
set guicursor=n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20
```

but I had no luck :(

**Comment by DarkDefender** [comment] 2017-08-19 02:02
For terminal cursor shapes to work in nvim with alacritty, you need to use a TERM that defines that the terminal supports it.

It should work if you use a new enough xterm term info. However, if you have modified your xterm term info, then chances are that this cursor info stuff was discarded.

An other posibility is that mac comes with outdated term info databases. IE on mac xterm term info is missing the cursor stuff as this was added a few years ago.

It works for me in linux with xterm term info (no tmux etc).

**Comment by gglanzani** [comment] 2017-08-19 06:51
@Darkdefender how would I update that term info? And if that'd be the case, would it work with iTerm but not with Alacritty while both have TERM set to xterm?

**Comment by DarkDefender** [comment] 2017-08-19 09:37
It works with iTerm because neovim has special workarounds for popular terminals. Less popular termials are expected to do things correctly :p

Anyways, I've found other bug reports like https://github.com/lionheart/openradar-mirror/issues/15500 so it seems like I guessed correctly that OSX ships with too old terminfo files. On linux these are supplied but ncurses. But I don't know if you could easily upgrade them yourself on OSX.

Here is my xterm terminfo file:
[xterm-256color.zip](https://github.com/jwilm/alacritty/files/1236221/xterm-256color.zip)
You could just be able to put it in `~/.terminfo/` (so `~/.terminfo/xterm-256color`) and you should be good to go. You can check where your terminfo is read from by typing the `infocmp` command in the terminal. That way, you can see if it reads you new local terminfo or not.

**Comment by gglanzani** [comment] 2017-10-18 12:22
Sorry for the long silence.

It seems like the xterm info file doesn't help and it indeed seems that, inside tmux, nvim cursor shapes change as they should (using Alacritty).

**Comment by bronzehedwick** [comment] 2017-11-13 17:23
I am getting the same behavior, in Neovim 0.2.1, but I wasn't having the issue in Neovim 0.2.0. The issue is also fixed for me if I use tmux.

**Comment by gibfahn** [comment] 2017-11-14 21:13
>When using iTerm or Terminal.app I do see that, I that should rule out issues with my copy of Neovim.

FWIW I have the same problem with Terminal.app.

>The issue is also fixed for me if I use tmux.

`alias nvim="TERM=tmux-256color nvim"` Seems to work well enough as a workaround (you don't have to actually be using tmux). Not sure if it works if you don't even have it installed though (although it's only a `brew install tmux` away).

**Comment by gibfahn** [comment] 2017-11-14 23:53
@DarkDefender 

>Here is my xterm terminfo file:
>You should just be able to put it in ~/.terminfo/ (so ~/.terminfo/xterm-256color) and you should be good to go. You can check where your terminfo is read from by typing the infocmp command in the terminal. That way, you can see if it reads you new local terminfo or not.

For me`infocmp` shows ` ~/.terminfo/78/xterm-256color` replacing that file with the one you uploaded does indeed fix the problem on both `Alacritty` and `Terminal.app`.

```bash
▶▶▶ ls                                                                                                                                                                                        ~/.terminfo
31             35             39             4d             58             64             68             6c             70             74             78
32             36             41             4e             61             65             69             6d             71             75             7a
33             37             45             50             62             66             6a             6e             72             76             
34             38             4c             51             63             67             6b             6f             73             77
```

Is there a recommended way to get an up to date terminfo file (other than copying from your comment 😁 )?

For anyone else having this problem, this is what I did:

```bash
curl -sL -O https://github.com/jwilm/alacritty/files/1236221/xterm-256color.zip
unzip xterm-256color.zip
cp ~/.terminfo/78/xterm-256color ~/.terminfo/78/xterm-256color.bak
mv xterm-256color ~/.terminfo/78/xterm-256color
```

**Comment by DarkDefender** [comment] 2017-11-15 06:46
@gibfahn Sadly I do not think there is a recommended way to do that. The best would of course be if Apple updated their system libraries to more recent versions.

Correct me if I'm wrong, but to me it seems like most libraries are quite outdated on mac, so the workflow on mac usually involves using a 3rd party packaging system (like brew) to update and get the libraries that you are interested in.

But as other people has reported, it seems like the ncurses library (at least this is the one that usually supplies the terminfo files on linux) does not update the terminfo files (if installed via brew that is).

So I guess that we'll have to add back a previously removed hack into neovim to fix this. (Or everyone could just migrate to linux... Just kidding ;) )

**Comment by gibfahn** [comment] 2017-11-17 10:54
>Correct me if I'm wrong, but to me it seems like most libraries are quite outdated on mac, so the workflow on mac usually involves using a 3rd party packaging system (like brew) to update and get the libraries that you are interested in.

Yep, to be honest I'm surprised there isn't a `brew install terminfo` command that gives you a `~/.terminfo` folder. I just checked and clean installs don't have it at all, so it wouldn't overwrite the system `/usr/local/share/terminfo`.

It's certainly common to update all the old BSD tools to their GNU equivalents (e.g. to enable `sed -i`). Probably just waiting for someone to write it.

**Comment by sodiumjoe** [comment] 2018-03-29 07:00
seems like this can be closed as it's not an issue with alacritty?

**Comment by chrisduerr** [comment] 2018-03-29 13:40
Yeah seems like this is a macos issue, the only potential workaround would be setting up our completely own terminfo file that doesn't relay on xterm-256color. But that's probably better covered in a different issue, this issue should probably be solved by just using a different terminfo/updating the system's terminfo.

**Closed by chrisduerr** 2018-03-29 13:40 UTC

**Comment by floam** [comment] 2018-11-15 11:11
I'm the original reporter of lionheart/openradar-mirror#15500. For [fish](https://github.com/fish-shell/fish-shell), I ended up just using [hard-coded escapes for dim and italics](https://github.com/fish-shell/fish-shell/commit/635e714bb40507ae041dd6da3bea501943a64d2d#diff-4ac27b696a84d0633805d592436a76fa) if we're running on a Mac 😢. I'd encourage anybody that's had a hard time due to ancient terminfo on macOS to [report the issue to Apple](http://bugreport.apple.com). My issue has been open for years now, but they keep track of the number of duplicates in order to figure out what the squeaky wheels are.
