### ISSUE TITLE
Sometimes alacritty does't redraw on commit gdbad1b62

### ISSUE THREAD

**Issue by cossonleo** [jwilm/alacritty#2466] opened 2019-05-22 07:03 UTC
Which operating system does the issue occur on?
archlinux

If on linux, are you using X11 or Wayland? 
X11

Sometimes alacritty does't redraw on commit gdbad1b62

**Comment by sci4me** [comment] 2019-05-22 15:13
I have the exact same problem; not sure what commit. Hard to tell when/why it happens.

**Comment by chrisduerr** [comment] 2019-05-22 18:23
Duplicate of https://github.com/jwilm/alacritty/issues/2217.

**Closed by chrisduerr** 2019-05-22 18:23 UTC
