### ISSUE TITLE
WIndows 10: Failed compiling shader - version '330' is not supported

### ISSUE THREAD

**Issue by mattpodwysocki** [jwilm/alacritty#2078] opened 2019-02-05 16:45 UTC
Which operating system does the issue occur on?
Operating System: Windows 10 version 1903 OS Build 18329.1

Rust version: rustc 1.32.0 (9fda7c223 2019-01-16)
LLVM version: 
  clang version 7.0.1 (tags/RELEASE_701/final)
  Target: x86_64-pc-windows-msvc
  Thread model: posix
  InstalledDir: C:\Program Files\LLVM\bin

Both downloading from scoop and compiling with source gives the following error when trying to run Alacritty gives the following error:

```
[2019-02-05 11:01] [ERROR] Alacritty encountered an unrecoverable error:

	[31mThere was an error initializing the shaders: Failed compiling shader at C:\git\alacritty/res/text.v.glsl: ERROR: 0:14: '' :  version '330' is not supported
ERROR: 0:14: '' : syntax error: #version
ERROR: 0:16: 'layout' : syntax error: syntax error
```

Is this also related to #128?

**Comment by chrisduerr** [comment] 2019-02-05 17:11
This is a duplicate of #128. Your GPU is likely too old for Alacritty's current shaders.

If you do have a recent GPU, please let me know and I'll re-open.

**Closed by chrisduerr** 2019-02-05 17:11 UTC

**Comment by mattpodwysocki** [comment] 2019-02-05 17:12
@chrisduerr this is via Parallels on macOS, so I'm assuming that's the issue?

**Comment by chrisduerr** [comment] 2019-02-05 17:23
Very likely, yes. Sounds like it doesn't support OpenGL.
