### ISSUE TITLE
Text not displayed properly

### ISSUE THREAD

**Issue by talal** [jwilm/alacritty#2454] opened 2019-05-17 08:53 UTC
Which operating system does the issue occur on?
macOS 10.14.4

Sorry for the generic title but the issue is a bit difficult to explain and inconsistent.

### Issue Description

On macOS when in fullscreen, Alacritty doesn't show the entire output of a program (vim, fzf, etc.). Sometimes it only shows the text above the cursor and sometimes below the cursor.

The frequency of this issue is inconsistent, sometimes I can go on for hours in fullscreen mode before getting this issue and sometimes it surfaces within a few minutes.

Reopening Alacritty fixes it (temporarily).

I have added a screencast of this issue so that you can get a better understanding of what I mean.

### Demo

In the screencast, I have demoed the issue with and without tmux. For your understanding: whenever there is a green bar at the bottom this means that I am in a tmux session.

Screencast: https://streamable.com/iimcy

The screencast demo:
1. I have a Alacritty window and open an example file in neovim: no issue
2. I go fullscreen and open same file: issue occurs
3. I exit tmux session, remain still in fullscreen, and open same file: issue occurs
4. I exit fullscreen and open same file again: no issue

Even though I have demoed with neovim, I have also seen this issue happen with fzf.

Let me know if I can help in anyway :)

**Comment by kchibisov** [comment] 2019-05-17 09:02
Can you reproduce this with the latest git master?

**Comment by chrisduerr** [comment] 2019-05-17 18:15
This is a duplicate of https://github.com/jwilm/alacritty/issues/2353 and has been fixed on the latest master.

If you can still reproduce this on the latest Alacritty master, please let me know and I'll re-open.

**Closed by chrisduerr** 2019-05-17 18:15 UTC

**Comment by talal** [comment] 2019-05-18 15:52
@chrisduerr @kchibisov Sorry for the late reply. `master` seems to have resolved this.
