### ISSUE TITLE
Windows neovim color problem

### ISSUE THREAD

**Issue by dakom** [jwilm/alacritty#2107] opened 2019-02-12 20:13 UTC
Using Windows / Powershell + Neovim

I am having this weird purple background... even with the settings mentioned in #109 

In this picture you can see Alacritty, followed by powershell, followed by neovim-qt:

![vim pics](https://user-images.githubusercontent.com/6406986/52665021-2ac5c900-2f13-11e9-8e69-98feced6b0d6.jpg)

This actually also occured to me when trying out Hyper... not sure if there's some commonality shared between them?

Tried setting `COLORTERM` as an environment var to `truecolor` but no dice.

As an aside - would be really cool to get ligatures support (#50 ) ;)

**Comment by chrisduerr** [comment] 2019-02-12 20:23
Do you have neovim setup to use GUI colors? Otherwise please make sure that your cterm colors are correct.

**Comment by dakom** [comment] 2019-02-12 20:28
I have this in init.vim

```
let &t_8f="\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b="\<Esc>[48;2;%lu;%lu;%lum"
set termguicolors
```

and theme config:

```
set background=dark
let g:palenight_terminal_italics=1
colorscheme palenight
```

anything else to set?

**Comment by chrisduerr** [comment] 2019-02-12 21:03
Looks like a duplicate of https://github.com/jwilm/alacritty/issues/1792 / https://github.com/jwilm/alacritty/issues/2074.

Note that cterm colors should work perfectly fine on Windows though, it's just problematic with truecolors.

**Closed by chrisduerr** 2019-02-12 21:03 UTC

**Comment by cup** [comment] 2020-02-12 01:52
https://github.com/alacritty/alacritty/issues/2107
https://github.com/alacritty/alacritty/issues/1792
https://github.com/alacritty/alacritty/issues/1662
https://github.com/alacritty/alacritty/issues/2088
https://github.com/alacritty/alacritty/issues/2578
