### ISSUE TITLE
Ncurse lines strangely "stripped" (with Inconsolata font)

### ISSUE THREAD

**Issue by Gomme-** [jwilm/alacritty#1055] opened 2018-01-26 13:43 UTC
Which operating system does the issue occur on?
Archlinux

If on linux, are you using X11 or Wayland?
Wayland, and I start Alacritty with `env WAYLAND_DISPLAY= alacritty`

I am using the Inconsolata font and I have noticed that lines in ncurses are "stripped", here is an image : 
![alacritty_ncurse_lines](https://user-images.githubusercontent.com/9958466/35442209-b26a0b7c-02a6-11e8-8acc-4eda62fea593.png)

I tried other terminal to be sure it was not a problem with my config but I didn't get that. 

Do I miss something to set or configure?

**Comment by jwilm** [comment] 2018-01-28 15:29
What should I be looking at?

**Comment by Gomme-** [comment] 2018-01-28 15:32
Sorry. In the picture, ranger running in alacritty and I am talking about the white lines it draws.

**Comment by chrisduerr** [comment] 2018-01-28 17:27
@jwilm I think he's talking about the anti-aliasing issue with the characters used for line drawing "overlapping".

**Comment by DSpeckhals** [comment] 2018-01-29 16:02
Same here...it's the anti-aliasing with the borders, using the same font: Inconsolata. It looks like it started in 59b561b440060e7b0d13160fb69519d127e6c687 or after.

![image](https://user-images.githubusercontent.com/3310769/35520009-d219af7e-04e3-11e8-826e-a7111828cf7e.png)

**Comment by sandersantema** [comment] 2018-01-29 20:18
I've been seeing the same thing but it also happens in a older fork from @chrisduerr (which has working scrolling). This fork is older than It's a bit hard to see though and only happens using certain font sizes. The version of Alacritty which I'm using is older than this commit: 59b561b440060e7b0d13160fb69519d127e6c687 however this is on Mac OS.
![schermafbeelding 2018-01-29 om 21 11 25](https://user-images.githubusercontent.com/21057514/35531996-01e5b928-0539-11e8-8378-20d005ecadb8.png)

**Comment by rkanati** [comment] 2018-02-05 21:29
To hazard a guess, this is because the glyphs are rendered slightly overlapped, and we appear to be blending instead of just overwriting pixels.

**Comment by r888800009** [comment] 2018-05-01 14:17
![alacritty_bug](https://user-images.githubusercontent.com/14235139/39476036-295fc6a0-4d8d-11e8-8d8a-126131dd6f8c.png)
font:DejaVu Sans Mono
linux
alacritty 0.1.0
X11

**Comment by jwilm** [comment] 2018-05-05 15:12
This is a duplicate of #118

**Closed by jwilm** 2018-05-05 15:12 UTC
