### ISSUE TITLE
Windows single-line splitting

### ISSUE THREAD

**Issue by JDTX** [jwilm/alacritty#2093] opened 2019-02-10 03:47 UTC
OS: **Windows 10** 64bit version **1809**
Alacritty version: **v0.2.7** (latest)
Shell: **Cygwin** (bash.exe)
[Alacritty cfg](https://github.com/jwilm/alacritty/files/2842209/alacritty.txt)

Single line copying seems bugged. When `cat`ing a file that has 1 line that's really long and copying the contents on Alacritty, it copies as multiple lines instead of one.  I noticed this while trying to copy a SSH public key.

MinTTY, PuTTY, and other terms do not have this issue. Only Alacritty. I've tried both the winPTY/conPTY backends, no change.

Here is a demonstration of the problem. (wc -l shows the file has one line, copying it turns into 14 lines.)
![issue](https://user-images.githubusercontent.com/24833917/52529213-cb1db280-2cb3-11e9-8df1-b28e91428eab.gif)

Is this a known problem? I couldn't find any relevant issues reporting this problem.

**Comment by chrisduerr** [comment] 2019-02-10 10:51
I'm unable to reproduce this on Linux. Which shell are you using?

**Comment by JDTX** [comment] 2019-02-10 18:29
I’m using Cygwin

**Comment by chrisduerr** [comment] 2019-02-10 18:34
Can you reproduce this with powershell?

**Comment by JDTX** [comment] 2019-02-10 18:50
@chrisduerr Yes I can. I undefined my shell (to set it to PowerShell, which is default) and it has the same problem.

![powershell](https://user-images.githubusercontent.com/24833917/52537973-66ee0380-2d32-11e9-92a0-faf92610c117.gif)

**Comment by chrisduerr** [comment] 2019-03-24 21:36
Just to make sure, this does not happen when running powershell (or cmd.exe) directly, right?

**Comment by kumarharsh** [comment] 2019-03-25 03:10
Yes. Even running tmux in `wsl.exe` doesn't show this behaviour. As far as I know, this bug only happens in Alacritty on Windows.

**Comment by davidhewitt** [comment] 2019-04-02 20:40
+1, I've noticed this, and it's a little frustrating. I've had a brief look into it a couple of times, but I'm not sure what Alacritty can do about it.

I think what is happening is that Windows is doing line-wrapping before sending the console output to Alacritty, using escape sequences to move the cursor to the start of the next line rather than letting Alacritty do text wrapping.

This means that [Alacritty never detects a line-wrap situation](https://github.com/jwilm/alacritty/blob/6f4d1afcf88e275f4a6b8c73cfc904e3833d0dd0/src/term/mod.rs#L1520), and subsequently doesn't know not to insert a newline when copying.

**Comment by djmcgill** [comment] 2019-04-05 11:35
Is it possible for Alacritty to detect those escape sequences? I would say that this is the only real issue I have with alacritty.

One kind-of work around for my (WSL) use case is: https://www.raymondcamden.com/2017/10/19/copying-to-clipboard-with-windows-subsystem-for-linux

**Comment by chrisduerr** [comment] 2019-04-05 18:25
If what @davidhewitt says is true and the shell actually inserts newlines itself, it would likely be impossible to fix this in Alacritty since there wouldn't be a way to determine what is a true and what is a 'fake' newline.

**Comment by davidhewitt** [comment] 2019-04-05 22:03
As @chrisduerr says, as they're just artificial newlines Alacritty will have no way to tell a real one from a fake one. Microsoft are aware of this limitation - I asked about it here: https://github.com/Microsoft/console/issues/405

**Comment by coldiron** [comment] 2019-05-16 17:18
Not sure if this is definitely windows creating the newlines rather than alacritty, as testing in wsl.exe's built-in term doesn't insert the newlines:

![image](https://user-images.githubusercontent.com/4825148/57873740-9cdcd100-77d4-11e9-9f2e-0519a52ce088.png)

**Comment by ajkessel** [comment] 2019-09-25 21:54
Has anyone found a workaround for this issue? As the OP noted, it doesn't occur in other common windows terminals (PuTTY, MinTTY, Cygwin RXVT when it worked). Is there a way the user could manually specify that a multiline block should be copied as a single line, at least until Alacritty/Windows figure this out?

**Comment by chrisduerr** [comment] 2019-09-26 10:56
> Has anyone found a workaround for this issue?

It's an upstream bug, so it has to get fixed there. Alacritty isn't going to implement platform-specific workarounds to try and hack around things that need to be resolved upstream.

As mentioned in the linked bug above, there's no reliable way to fix this at this moment.

**Comment by chrisduerr** [comment] 2019-12-05 17:53
Closing, since the issue is unrelated to Alacritty.

**Closed by chrisduerr** 2019-12-05 17:53 UTC
Labels: H - windows, S - selection
