### ISSUE TITLE
On `wsl.exe --shutdown`, Alacritty doesn't close the window until an event is fired

### ISSUE THREAD

**Issue by chris-morgan** [jwilm/alacritty#2889] opened 2019-10-18 05:25 UTC
Unlike #915 and the handful of duplicates that have followed it, this is on *Windows*. I’m currently running Alacritty 28cf90d1308ecd14d9a5646909f7637ddbf105ff (HEAD~3).

Windows Insider Preview, and Alacritty is running `wsl.exe -d arch -u me`, where arch is a WSL 2 machine.

When I run `wsl.exe --shutdown` (“Immediately terminates all running distributions and the WSL 2 lightweight utility virtual machine.”), the program that Alacritty was running is killed off, but the Alacritty window remains around until I press a key, move the mouse or something similar.

This is not applying to normal exits; this WSL shutdown is the primary way of triggering it that I’ve found, though I *think* I’ve triggered it in other ways before as well.

**Comment by chrisduerr** [comment] 2019-10-18 09:26
Can you reproduce this with something like `sleep 10; exit`?

**Comment by chris-morgan** [comment] 2019-10-18 10:13
Yes.

**Comment by chrisduerr** [comment] 2019-10-18 10:57
Interesting, so that would indicate that it's a problem with quitting in general.

On Windows the PTY handling is significantly different, so that means our Signal handling might not be accurate, but if I understand you correctly you're using WSL 2, right?

IIRC, WSL 2 is just Linux VMs, which would mean that you installed our Linux version and create a Linux PTY? So if you start up with `alacritty -v` there will be no mention of ConPTY or WinPTY, correct?

Maybe there's a problem with signal handling through WSL 2 then?

**Comment by chris-morgan** [comment] 2019-10-18 11:45
This is all Windows Alacritty, not Linux Alacritty. (I am running no X server or similar, and don’t intend to.)

With alacritty running `cmd.exe` instead of `wsl.exe -d arch -u me`, `sleep 1 && exit` behaves just as it did in WSL, not closing the window until the next input event (meanwhile, `sleep 0 && exit` does close the window immediately, in both cmd and wsl).

I therefore conclude that WSL is not a contributing factor.

This has all been using ConPTY. When I switch to WinPTY, quitting the shell *at all* makes Alacritty hang, with infinite `[YYYY-MM-DD HH:MM] [INFO] wait_object_0` log lines when run with `-v`. Judging by the thread stacks and the cycle counts for the two key threads (main one and event loop proxy), I suspect that something in the event loop handler is posting a new message to the event loop, so that it ends up with some kind of busy waiting deadlock. I believe that to be a completely different bug, and one that’s probably a deal more severe, because you can’t even force close the window once it’s in this state, due to where in the event loop it’s hung—got to kill the process manually. Workaround to avoid this bug: never quit the shell, instead use the window close button.

I’m on Windows 10 build 19002 (the current Windows Insider Preview build at the time of writing). I don’t believe this window closing bug is related to that (I only switched over to WIP this week, and I’ve definitely experienced the bug before), though I believe the other bug with WinPTY only affects WIP.

**Comment by chrisduerr** [comment] 2019-10-18 11:50
> I therefore conclude that WSL is not a contributing factor.

That's great to know, thanks.

> Alacritty hang, with infinite [YYYY-MM-DD HH:MM] [INFO] wait_object_0 log lines when run with -v. Judging by the thread stacks and the cycle counts for the two key threads (main one and event loop proxy), I suspect that something in the event loop handler is posting a new message to the event loop, so that it ends up with some kind of busy waiting deadlock

`wait_object_0` is not related to any cross-platform Alacritty code. I suspect this is Windows PTY related. As such, it is completely unrelated to the event loop (proxy).

> I believe that to be a completely different bug, and one that’s probably a deal more severe, because you can’t even force close the window once it’s in this state

That's quite interesting though, since it would be a regression. I wonder if that's due to the Windows version you're running or because of an Alacritty change.

**Comment by kchibisov** [comment] 2019-10-18 12:29
@chris-morgan I can't repro your issue(wsl + `sleep 10; exit`), would you mind to try `v0.3.3` (or bisecting)?

**Comment by cfiet** [comment] 2019-10-22 21:49
Hi, not an OP but I did manage to reproduce it on `v0.3.3`. The trick is not to have the alacritty in fullscreen and keep the mouse pointer away from the window.

The window sticks around for as long as the mouse doesn't move

![alacritty-sticking-cropped](https://user-images.githubusercontent.com/377311/67336939-17e1aa80-f51e-11e9-81f6-0a8530eade17.gif)

**Comment by cfiet** [comment] 2019-10-23 07:10
Might be something connected to log file handling. Doesn't reproduce for me with `persistent-logging` enabled or when running with increased verbosity.

**Comment by chrisduerr** [comment] 2019-10-23 18:45
That might also cause some racing condition to not happen though, so I would be a bit careful following down this path.

Very interesting observation though, wondering if the issue on latest master can also be resolved with these changes?

**Comment by cfiet** [comment] 2019-10-23 19:28
@chrisduerr: Just tested the same thing on 9e0b9d5de1b8fe2d9d8ed80f73b4ad0fda171f22 debug build with both
- `nightly-x86_64-pc-windows-msvc unchanged - rustc 1.40.0-nightly (7979016af 2019-10-20)`
- `stable-x86_64-pc-windows-msvc unchanged - rustc 1.38.0 (625451e37 2019-09-23)`

App seems to be going into a live-lock where it consumes just below 2 CPU cores and never exits, also stops reacting to Windows events and redrawing. Persistent logging or increasing verbosity have no effect on that. I guess that's the separate issue.

**Comment by cfiet** [comment] 2019-10-23 21:06
Ok, I reproduced the problem on `v0.3.3` tag (cc3e4d3d5cb2f658d6faef02e4216b9342451efc) with profiler attached. Here's the hot path where alacritty seems to be spending most of it's time while it's window is sticking around

![image](https://user-images.githubusercontent.com/377311/67433891-e7af1000-f5e0-11e9-8d7e-9b7767ad6eeb.png)

Seems like a loop of panicking and unwinding casing another event that's panicking.

**Comment by cfiet** [comment] 2019-10-23 21:33
And it's similar on master (9e0b9d5) but with 50% of time stuck in the above unwinding and the other 50% of the time in this stack

![image](https://user-images.githubusercontent.com/377311/67435698-99037500-f5e4-11e9-84d4-069ed72bd0ae.png)
 
```
Function Name	Total CPU [unit, %]	Self CPU [unit, %]	Module
|| + __scrt_common_main_seh	13210 (42.35%)	0 (0.00%)	alacritty.exe
||| + main	13210 (42.35%)	0 (0.00%)	alacritty.exe
|||| + std::rt::lang_start<()>	13210 (42.35%)	0 (0.00%)	alacritty.exe
||||| + std::rt::lang_start_internal	13210 (42.35%)	0 (0.00%)	alacritty.exe
|||||| + panic_unwind::__rust_maybe_catch_panic	13210 (42.35%)	0 (0.00%)	alacritty.exe
||||||| + std::panicking::try::do_call<closure-0,i32>	13210 (42.35%)	0 (0.00%)	alacritty.exe
|||||||| + std::rt::lang_start::{{closure}}<()>	13210 (42.35%)	0 (0.00%)	alacritty.exe
||||||||| + alacritty::main	13210 (42.35%)	0 (0.00%)	alacritty.exe
|||||||||| + alacritty::run	13210 (42.35%)	0 (0.00%)	alacritty.exe
||||||||||| + alacritty::event::Processor<alacritty_terminal::event_loop::Notifier>::run<alacritty_terminal::event_loop::Notifier,alacritty::event::EventProxy>	13210 (42.35%)	0 (0.00%)	alacritty.exe
|||||||||||| + winit::platform::desktop::{{impl}}::run_return<alacritty_terminal::event::Event,closure-0>	13210 (42.35%)	0 (0.00%)	alacritty.exe
||||||||||||| + winit::platform_impl::platform::event_loop::EventLoop<alacritty_terminal::event::Event>::run_return<alacritty_terminal::event::Event,closure-0>	13210 (42.35%)	47 (0.15%)	alacritty.exe
|||||||||||||| + [External Code]	13150 (42.16%)	10069 (32.28%)	Multiple modules
||||||||||||||| + winit::platform_impl::platform::event_loop::thread_event_target_callback<alacritty_terminal::event::Event>	3081 (9.88%)	88 (0.28%)	alacritty.exe
|||||||||||||||| + [System Call] ntoskrnl.exe	1 (0.00%)	1 (0.00%)	ntoskrnl.exe
|||||||||||||||| - std::sync::mpsc::Receiver<alacritty_terminal::event::Event>::recv<alacritty_terminal::event::Event>	1168 (3.74%)	66 (0.21%)	alacritty.exe
|||||||||||||||| - winit::platform_impl::platform::event_loop::ThreadMsgTargetSubclassInput<alacritty_terminal::event::Event>::send_event<alacritty_terminal::event::Event>	1720 (5.51%)	24 (0.08%)	alacritty.exe
|||||||||||||||| - winit::platform_impl::platform::event_loop::{{impl}}::deref	104 (0.33%)	7 (0.02%)	alacritty.exe
```

**Comment by cfiet** [comment] 2019-10-24 07:38
After debugging with different config settings this seems to be 2 issues on top of each other:

1. When shell exits on its own or crashes, Alacritty window does not close itself until next Windows event is received. It's also [busy-looping here](https://github.com/jwilm/alacritty/blob/master/alacritty_terminal/src/event_loop.rs#L315) in `pty reader` thread. This happens with both ConPTY and WinPTY.

2. With WinPTY only, in the same scenario, main thread is busy looping in [`winit main loop`](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/windows/event_loop.rs#L249). There `winuser::PeekMessageW` doesn't block and returns the same event on every iteration. No new events seem to be received by the Window and it has to be terminated from task manager.

**Comment by cfiet** [comment] 2019-10-24 08:38
Second issue was introduced in 729eef0c933831bccfeac6a355bdb410787fbe5f

**Comment by cfiet** [comment] 2019-10-24 22:32
@chrisduerr: Ok, I think I found the reason for the livelock. It seems to be a mix of how now there's separate IO loop and UI loop and how the winit EventLoop 2.0 seems to be working on Windows.

So, when internal process exits, the IO thread still keeps spamming window with `User::Wakeup` messages from [`pty_read`](https://github.com/jwilm/alacritty/blob/master/alacritty_terminal/src/event_loop.rs#L254) since it's part of [`event_loop`](https://github.com/jwilm/alacritty/blob/master/alacritty_terminal/src/event_loop.rs#L354).

This seems to be a lot faster then the [main `winint` loop](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/windows/event_loop.rs#L241), at least with WinPTY when the `winpty-agent` has crashed. The current implementation of the loop doesn't exit unless the windows events queue is empty indicated by call to [`winuser::PeekMessageW`](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/windows/event_loop.rs#L249) returning 0, but it never is, because of `User::Wakeup` events stacking up there.

This seem like a bug in `winint` itself, because it seems that setting [`*control_flow = `ControlFlow::Exit](https://github.com/jwilm/alacritty/blob/master/alacritty/src/event.rs#L354) in handler is not enough to terminate the loop on Windows, there's an assumption that all the events will be handled as well.

Ive throttled `User::Wakeup` sending with `thread::sleep(time::Duration::from_millis(1)` and it seems to have resolved the issue. The right solution would be to either fix the `winit` handling of `ControlFlow::Exit` on Windows or get Alacritty to stop the `event_loop` when it sets `ControlFlow::Exit`.

**Comment by chrisduerr** [comment] 2019-10-24 23:20
> The current implementation of the loop doesn't exit unless the windows events queue is empty

Do you mean on winit's side or on our event loop processing side? Because we definitely quit our loop even if it is not empty.

> This seem like a bug in winint itself, because it seems that setting *control_flow = ControlFlow::Exit in handler is not enough to terminate the loop on Windows, there's an assumption that all the events will be handled as well.

Thas makes it sound like you mean that regardless of us setting the control flow to `Exit`, a new iteration of our event loop is triggered? Do I understand that correctly? That would definitely be a winit bug. We need to verify that we actually do set `Exit` though.

**Comment by cfiet** [comment] 2019-10-24 23:30
I think the main problem is on `winit` side. Alacritty seems to be setting `ControlFlow::Exit` correctly but this doesn't ever get checked by winit because of long queue of `User::Wakeup` events that Alacritty is sending from `pty reader` thread.

Currently, the only issue on Alacritty side is, it expects glutin/winit loop to exit before terminating `pty reader` loop. But the latter keeps spamming event loop with events that prevent winit main loop from terminating.

I'll see if I can make a small winit only app that reproduces the bug and report it with them.

**Comment by cfiet** [comment] 2019-10-24 23:39
It also might be related to the [caveats](https://docs.rs/winit/0.20.0-alpha4/winit/platform/desktop/trait.EventLoopExtDesktop.html#caveats) or `run_return` method that you're using.

**Comment by chrisduerr** [comment] 2019-10-24 23:48
Yeah the lacking winit API certainly doesn't help with this. But maybe we can work around it by changing our behavior too.

**Comment by cfiet** [comment] 2019-10-24 23:54
Definitely the issue on `winit` side, isolated it here https://github.com/cfiet/winit-windows-events-bug/blob/master/src/main.rs

**Comment by cfiet** [comment] 2019-10-25 00:28
I think a workaround could be to somehow share [tty::process_should_exit](https://github.com/jwilm/alacritty/blob/master/alacritty/src/event.rs#L351) check with `pty thread` so it just terminates.

I'm new to the code so I'm not sure if that's the best way, happy to give it a try over the weekend.

**Comment by cfiet** [comment] 2019-10-25 10:27
@chrisduerr: I've sent a PR for a work around for the `winit` issue. Let me know, if you think this is an acceptable approach, I'll look into adding tests and fixing TODOs.

**Closed** 2019-11-16 21:11 UTC
Labels: B - bug, H - windows
