### ISSUE TITLE
Italic fails when style contains spaces e.g. "Light Italic"

### ISSUE THREAD

**Issue by lewisthompson** [jwilm/alacritty#2799] opened 2019-09-14 19:32 UTC
macOS Catalina

With the following font style defined italics work as expected, e.g. `echo -e "\e[3mItalic"` is italic:

```yaml
  italic:
    family: "IBMPlexMono Nerd Font Mono"
    style: Italic
```

When I include spaces in the style italics do not work as expected.  This fails both with & without quotes:

```yaml
  italic:
    family: "IBMPlexMono Nerd Font Mono"
    style: "ExtraLight Italic"
```

**Comment by chrisduerr** [comment] 2019-09-14 19:38
Are you sure `ExtraLight Italic` is a dedicated font name? Whitespace in the styles is not a problem, as you can see even our default configuration uses it for the bold italic font. However it will only work when that's actually the proper style name for the font.

Have you tried `ExtraLight Italic` or `ExtraLight`?

**Comment by lewisthompson** [comment] 2019-09-14 19:41
I use `ExtraLight` as my regular font and it works.  In Font Book on macOS there is an `ExtraLight Italic`:

<img width="218" alt="Screen Shot 2019-09-14 at 12 41 02" src="https://user-images.githubusercontent.com/4053372/64913007-f0145100-d6ec-11e9-8d2e-b628255a3824.png">

**Comment by chrisduerr** [comment] 2019-09-15 00:55
I'm not familiar with how the Font Book works on macOS or if the labels specified here are accurate, which is why I think it would be worthwhile to try some variations.

Having `IBMPlexMono Nerd Font Mono ExtraLight` as name and `Italic` as style might also be worth a shot.

**Comment by lewisthompson** [comment] 2019-09-22 06:01
So I believe that this is the correct way on Mac to determine font family & style:

```system_profiler SPFontsDataType
[...]
    IBM Plex Mono ExtraLight Italic Nerd Font Complete Mono.otf:

      Kind: OpenType
      Valid: Yes
      Enabled: Yes
      Location: /Users/lewis_thompson/Library/Fonts/IBM Plex Mono ExtraLight Italic Nerd Font Complete Mono.otf
      Typefaces:
        IBMPlexMonoNerdFontCompleteM-Italic:
          Full Name: IBM Plex Mono ExtraLight Italic Nerd Font Complete Mono
          Family: IBMPlexMono Nerd Font Mono
          Style: ExtraLight Italic
          Version: Version 2.000
          Vendor: Bold Monday
          Unique Name: 2.000;IBM ;IBMPlexMono-ExtraLightItalic
          Designer: Mike Abbink, Paul van der Laan, Pieter van Rosmalen
          Copyright: Copyright 2017 IBM Corp. All rights reserved.
          Trademark: IBM Plex™ is a trademark of IBM Corp, registered in many jurisdictions worldwide.
          Outline: Yes
          Valid: Yes
          Enabled: Yes
          Duplicate: Yes
          Copy Protected: No
          Embeddable: Yes
[...]
```

`ExtraLight Italic` does not show as italic within Alacritty while it does in iTerm2.

**Comment by lewisthompson** [comment] 2019-09-22 06:06
FYI I also tried various combinations of `family` and `style` as per your earlier suggestion but none worked.

As I can adjust the `normal` and `bold` styles without changing the `family` makes me think this is not likely to be the right option either.

**Comment by chrisduerr** [comment] 2019-09-22 19:30
Hmm, I'm unsure what could be going on here. It seems like the problem is just that the style is something a bit unconventional. Usually setting `family` and `style` to what is listed in the font description should do the job.

It might be worth testing out if things work when renaming the style to just `Italic`, but that's a lot of effort and I'd expect that to just fix it which wouldn't necessarily help other than just confirming the issue.

**Comment by lewisthompson** [comment] 2019-09-22 22:09
So I used http://www.glyphrstudio.com/online/ to upload the "ExtraLight Italic" font which I renamed to "ExtraLightItalic" and now things work as expected.

I did notice in fontforge that the italic font had a "weight" of "ExtraLight" and nowhere did I actually see "ExtraLight Italic" as the style.  I suspect that the issue all along was with the font itself.

**Comment by chrisduerr** [comment] 2019-09-22 22:12
> I did notice in fontforge that the italic font had a "weight" of "ExtraLight" and nowhere did I actually see "ExtraLight Italic" as the style. I suspect that the issue all along was with the font itself.

If there is no style `ExtraLight Italic` at all and there's just a weight `ExtraLight`, that would explain why Alacritty isn't able to find it. Since Alacritty only checks for family and style.

**Comment by OJFord** [comment] 2019-09-25 09:34
I had a very similar confusion / fight with Font Book recently (#2812).

What's the current mechanism for looking up fonts that it depends on 'Font Book'? In my case `fc-match` was working properly, and `Font Book.app` had something weird and wrong, and of course the underlying files in `{,~}/Libarary/Fonts` were correct.

**Comment by chrisduerr** [comment] 2019-09-25 19:40
> What's the current mechanism for looking up fonts that it depends on 'Font Book'?

What do you mean by this? How are we depending on Font Book?

**Comment by OJFord** [comment] 2019-09-25 21:13
'Depending' perhaps a poor choice of word - I meant that the name used has to match what's in Font Book, which in my case was different (Font Book caching bug, it seemed) from `fc-match`/`fc-list`, which matched the actual file.

I assume therefore, on macOS, Font Book is somehow used in locating the font file from the given name & style?

**Comment by chrisduerr** [comment] 2019-09-26 10:29
We don't have anything to do with Font Book at all. But we use the native macOS APIs to load our fonts, which Font Book is probably too, while fc-match is not. So that's probably why we're closer to the results of Font Book.

**Comment by chrisduerr** [comment] 2019-09-26 10:31
> I suspect that the issue all along was with the font itself.

@lewisthompson Would you be fine with closing this issue then? As far as I can tell, we should be good then.

**Comment by lewisthompson** [comment] 2019-10-02 07:44
Apologies for slow response.  Yes, from my end now I've updated my font I'm totally happy for it to be closed.  Thanks for your help!

**Closed** 2019-10-02 09:32 UTC
Labels: B - bug, C - awaiting feedback, H - macos, S - font
