### ISSUE TITLE
disable selection?

### ISSUE THREAD

**Issue by dannydulai** [jwilm/alacritty#420] opened 2017-02-17 22:35 UTC
Is there a way to disable mouse selection?

I ask because since the semantic selection stuff, alacritty mouse selection is interfering with tmux selection in strange ways :-(

**Comment by dannydulai** [comment] 2017-02-17 22:37
I can work around the conflict by doing this:

  double_click: { threshold: 0 }
  triple_click: { threshold: 0 }

But really, there should be a way to just turn off all selection. If scrollback is ever implemented, make sure it's optional too!

**Comment by NickeZ** [comment] 2017-02-19 10:21
On gnome-terminal i believe that you need to hold down shift if you want to ignore the applications mouse behavior. Maybe we can do the same? In general i think alacritty should not handle mouse events if the running application can do that

**Comment by jwilm** [comment] 2017-02-19 16:34
>  In general i think alacritty should not handle mouse events if the running application can do that

The input handling attempts to do that. Failing in this case is a bug.

**Comment by dannydulai** [comment] 2017-02-19 16:36
oh, in that case, just start up tmux with `set -g mouse` and notice that you can squeeze in alacritty selection with the default yml

**Comment by NickeZ** [comment] 2017-02-24 14:48
btw, it would be very nice if you could copy/paste even if the application supports mouse. Like gnome-terminal does if you hold down shift.

I often have tmux/vim running with mouse support over ssh tunnels, but currently I can't easily copy/paste from those sessions in alacritty without disabling mouse support in both tmux and vim...

**Comment by jwilm** [comment] 2017-02-24 16:38
Sounds reasonable. We first need glutin to provide modifier keys with mouse events (at least on button press/release).

**Comment by NickeZ** [comment] 2017-03-02 08:46
I have also managed to reproduce this bug a couple of times. Even though mouse is enabled in tmux I have managed to double click to select something in alacritty. This feels kind of racy though since I cannot reproduce it deterministically..

**Comment by chrisduerr** [comment] 2018-05-18 23:16
There have been a few changes to how mouse handling works, I believe this is fixed in the latest master, at least I'm not able to reproduce it.

If it should still exist for someone, please let me know and I'll re-open this issue.

**Closed by chrisduerr** 2018-05-18 23:16 UTC
Labels: B - bug, S - input

**Comment by deft01** [comment] 2023-01-17 08:36
Hello this is still the case for me, I have updated this ticket https://github.com/alacritty/alacritty/issues/1511 thinking alacritty had something wrong with mouse selection. But I realised the issue is that tmux and alacritty have the same shortcut for selection.
And I don't know how I can deactivate it in alacritty.

**Comment by kchibisov** [comment] 2023-01-17 08:47
I'm not sure about what are you talking about. When you use tmux's mouse mode selection it'll take over the alacritty's selection automatically(you could notice the cursor change). The only way to use the alacritty's selection in that case is by holding the `Shift` button.

**Comment by deft01** [comment] 2023-01-17 08:57
Natively without any hacks, in my case, tmux mouse selection work with `Shift + mouse`. This is conflicting with alacritty.

## Working use case
When I use tmux in another terminal emulator (e.g terminator), I works well. Tmux handle the mouse selection, everything is fine.

## Problem with alacritty
When I try the same use case with alacritty, it handle `Shift + mouse` before tmux, so I can't use the tmux mouse selection.

## Conclusion
I would like to desactivate this behavior or finding a bypass. Ideally I wouldnt like changing the tmux behavior because of this.

**Comment by kchibisov** [comment] 2023-01-17 09:16
But you've already changed tmux behavior since you don't need to press shift in it by default to select? This behavior won't change, sorry.

**Comment by deft01** [comment] 2023-01-17 09:40
## ERRATUM
I was wrong and you was right. After digging more into tmux documentation, I think `Shift` with mouse selection is moving out tmux copy-mode.

I think I was using tmux the wrong way.
I found out the right way to use tmux + alacritty is to enter the tmux copy-mode with `<prefix> + [` and then use the mouse or the tmux vi-motion to get the selection.

Sorry about that.

**Comment by kchibisov** [comment] 2023-01-17 09:59
You can set mouse mode in tmux directly, so you don't need to press the prefix at all.

**Comment by deft01** [comment] 2023-01-17 10:09
I don't know how you succeed. I have `set -g mouse one` in my tmux config file. But I'm still forced to use the prefix.

**Comment by kchibisov** [comment] 2023-01-17 10:48
It's `set -g mouse on`, not `one`.
