### ISSUE TITLE
Reflow on resize

### ISSUE THREAD

**Issue by Aaron1011** [jwilm/alacritty#591] opened 2017-05-29 19:30 UTC
If the Alacritty window is resized horizontally to a smaller size, and then resized to its original size, the restored cells will be black instead of displaying their proper contents.

It's best shown in an image:

![](https://i.imgur.com/kf4xXUz.png)

The fact that the last line displays properly after resizing appears to have something to do with zsh - it seems to re-print the prompt during a resize.

**Comment by NickeZ** [comment] 2017-05-29 19:47
This is a "feature" in the same way that not being able to scrollback is a "feature". You need to buffer everything that has been outputted from the underlying process so that you can reflow it on resize.

**Comment by nixpulvis** [comment] 2018-01-11 02:31
@NickeZ Although it's a much smaller buffer needed to implement this, still I want both <3.

Has there been any work started here, or maybe people are hesitant because this will clearly want to use the same facilities that #124 uses? I'm might be interested in trying to write up a PR for this though.

**Comment by NickeZ** [comment] 2018-01-11 13:24
Since I wrote my comment there has been a lot of work on scrollback. I haven't looked at the details, but depending on how the scrollback buffer is implemented you could get reflow on resize at the same time. If, on the other hand, the scrollback buffer only buffers the "view" and not the real output from the pty I think "reflow on resize" is quite a big task to implement.

**Comment by synaptiko** [comment] 2018-04-08 18:41
@jwilm Is or will be this issue fixed by new scrollback implementation (scrollback branch)?

**Comment by chrisduerr** [comment] 2018-04-08 21:48
I highly doubt it will be fixed by the new scrollback implementation. I don't think it would be a smart idea to delay scrollback for this feature.

**Comment by ti-mo** [comment] 2018-08-27 12:03
Would also love to have this! Using the scrollback branch at the moment, but this behavior is not implemented there either.

**Comment by haarp** [comment] 2018-09-18 09:09
now that scrollback has been implemented (thanks btw!), this feature should be considered again.

**Comment by cauebs** [comment] 2018-09-19 16:27
Is this a duplicate of #390?

**Comment by chrisduerr** [comment] 2018-09-19 18:28
Yeah, these two issues are completely separate. #390 was actually implemented already, but this one still needs a resolution.

**Closed** 2019-03-13 18:55 UTC
Labels: P - high, S - terminal, enhancement
