### ISSUE TITLE
Alacritty window fails to close after quitting vim

### ISSUE THREAD

**Issue by gcmt** [jwilm/alacritty#1164] opened 2018-03-09 15:11 UTC
When I launch Alacritty with `alacritty -e vim` and then close vim with `:quit` (or `:exit`, `ZZ`, `ZQ`), the window remains open until I move the mouse or press something. This is what I see just after executing `:quit`: [imgur link](https://i.imgur.com/yEJWVka.png). This happens independently of how the windows are organized (stacked, tabbed or split mode in i3).

This happens all the time with my personal vimrc, 6 times out of 10 with no vimrc at all (stock vim) and never with `vim -u NONE`.

I'm not sure this is Alacritty's  fault, but it doesn't happen with any other terminal I've tried (st and termite).

System info:
- Arch Linux 4.14.15
- i3-gaps 4.14.1
- Vim 8.0.1436 
- Compton 0.1_beta2.5

**Comment by chrisduerr** [comment] 2018-03-09 15:15
Closed because this is a duplicate of #915.

**Closed by chrisduerr** 2018-03-09 15:16 UTC
