### ISSUE TITLE
Quitting Vim after "alacritty -e vim" requires additional keystroke to close the terminal

### ISSUE THREAD

**Issue by geneotech** [jwilm/alacritty#915] opened 2017-11-22 16:35 UTC
If I run 

``alacritty -e vim``

And then quit right away with

``:q``

There remains a dangling Alacritty window with no text and just a cursor in the top left corner.
It persists until I move the mouse or press a key, which is a little bit annoying.
I've tested the same command with ``urxvt``, ``terminator``, ``st`` and behaviour of all seems to be the same in that they all close the terminal once ``vim`` quits.

For the record, I am writing this from Arch Linux with an i3 window manager. My server is ``X11``.

Other than that, thank you for an amazing terminal... I've been struggling to find one that takes advantage of my 144 Hz monitor, especially since I am a former FPS player and can immediately tell whether something responds to my keystrokes in 16ms or 7ms!

**Comment by jwilm** [comment] 2017-11-22 17:47
I'm unable to repro this. Would you mind trying this again with `alacritty --print-events -e vim` and take note of what happens between the time it hangs and actually exits?

> 144 Hz monitor

I've been wanting to try Alacritty on one of those; sounds fun!

**Comment by geneotech** [comment] 2017-11-22 18:00
Here is the full log:

```
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: Resized(1920, 522) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: Moved(0, 0) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: Refresh }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: MouseEntered { device_id: DeviceId(X(DeviceId(2))) } }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: Moved(0, 18) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: Focused(true) }
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 36, state: Released, virtual_keycode: Some(Return), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 36, state: Released, virtual_keycode: Some(Return), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: Awakened
[unhandled osc_dispatch]: [['1','0',],['?',],] at line 778
[unhandled osc_dispatch]: [['1','1',],['?',],] at line 791
glutin event: Awakened
glutin event: Awakened
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 50, state: Pressed, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 50, state: Pressed, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 47, state: Pressed, virtual_keycode: Some(Semicolon), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 47, state: Pressed, virtual_keycode: Some(Semicolon), modifiers: ModifiersState { shift: true, ctrl: false, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: ReceivedCharacter(':') }
glutin event: Awakened
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 47, state: Released, virtual_keycode: Some(Semicolon), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 47, state: Released, virtual_keycode: Some(Semicolon), modifiers: ModifiersState { shift: true, ctrl: false, alt: false, logo: false } } } }
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 50, state: Released, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 50, state: Released, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: true, ctrl: false, alt: false, logo: false } } } }
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 24, state: Pressed, virtual_keycode: Some(Q), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 24, state: Pressed, virtual_keycode: Some(Q), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: ReceivedCharacter('q') }
glutin event: Awakened
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 24, state: Released, virtual_keycode: Some(Q), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 24, state: Released, virtual_keycode: Some(Q), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 36, state: Pressed, virtual_keycode: Some(Return), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 36, state: Pressed, virtual_keycode: Some(Return), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: ReceivedCharacter('\r') }
glutin event: Awakened
glutin event: Awakened
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 36, state: Released, virtual_keycode: Some(Return), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(48234499))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 36, state: Released, virtual_keycode: Some(Return), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
glutin event: Awakened # After this command, there is silence and the dangling window
# The next command is due to my pressing enter to close the terminal 
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(11))), event: Key(KeyboardInput { scancode: 36, state: Pressed, virtual_keycode: Some(Return), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
```

**Comment by geneotech** [comment] 2017-11-23 15:40
I'll also add, this mostly occurs when, after writing ``:q``, I press and release enter very fast. If you hold the final enter for more milliseconds the prompt sometimes exits cleanly.

**Comment by mamins1376** [comment] 2017-11-28 05:18
That's because of a `keyup` event emitted after vim exit, and so it's still dependent on such keystroke.

**Comment by mamins1376** [comment] 2017-11-28 12:00
The issue comes from event loop which needs to be notified when child process exits. Currently the `sigchld` function in `tty.rs` handles this event and just sets `SHOULD_EXIT` flag, while the event loop is waiting for new events from window system. One __hack__ can be manually faking an event to the terminal window using unsafe C code. The better solution is to create a new stream to `poll` and trigger it on `sigchld`. I don't have enough knowledge about the internal design and control flow, but am interested in fixing this.

Reproduction can be done by running a command that takes a while to finish automatically (such as `sync`) through `-e` as argument, under gdb to watch the traceback. Then killing it using `SIGSTOP` and looking `where` it is hanging (goes down to `poll`). Sending signal can be automatically done this way to avoid triggering unwanted key events (assuming one instance is running):
```bash
$ sleep 3 && pgrep alacritty | xargs kill -SIGSTOP
```

**Comment by gibfahn** [comment] 2017-12-29 11:20
FWIW `nvim` doesn't seem to have this problem, so if you're looking for a quick workaround, using neovim should work.

**Comment by Infinisil** [comment] 2018-01-25 14:42
Having the same issue with weechat (`alacritty -e weechat`) not closing until moving the mouse or typing something

**Comment by technetos** [comment] 2018-02-01 04:22
Neovim does have this issue.

**Comment by gibfahn** [comment] 2018-02-06 14:46
>Neovim does have this issue. I am also using i3 and x11.

Hmm okay, I'm not seeing it on macOS High Sierra with neovim (but am with vim).

**Comment by nixpulvis** [comment] 2018-02-07 02:39
FWIW: a debug compilation of alacritty doesn't have this issue for me. Only when I compile with `--release` can I reproduce.

**Comment by johnae** [comment] 2018-02-19 15:52
This issue is not related to vim specifically but rather likely the signal handling of alacritty. I've seen this in lots of situations where the exit of the only process should have caused alacritty to also exit.

**Closed** 2019-03-12 19:44 UTC
