### ISSUE TITLE
Wrong font width

### ISSUE THREAD

**Issue by averrin** [jwilm/alacritty#902] opened 2017-11-15 19:04 UTC
Which operating system does the issue occur on?
Arch Linux

If on linux, are you using X11 or Wayland?
X11

Alacritty version:
from AUR

![screenshot](https://i.imgur.com/bi7vQW7.png)

For this screenshot i use Iosevka-ss03, but with other fonts gaps between chars much bigger.

**Comment by meskarune** [comment] 2017-12-08 17:11
That looks like the default monospace font. You might want to double check your config. I use arch and it works fine for me.

**Comment by ne-sted** [comment] 2017-12-08 17:42
It looks like Iosevka (i.e. see `@` symbol). Same issue there.
@meskarune did you also use Iosevka font?

**Comment by mikoim** [comment] 2017-12-11 04:39
@averrin **Workaround** is here. https://gist.github.com/mikoim/498dfcdd39439316e3eb9b8897914302

**Comment by autoferrit** [comment] 2018-01-03 06:34
can confirm this issue and the patch @mikoim links above fixes it for me

Ubuntu 17.10
```bash
❯ alacritty --version
alacritty 0.1.0

❯ alacritty -v
Welcome to Alacritty.
Configuration loaded from /home/shawn/.config/alacritty.yml
device_pixel_ratio: 1
width: 1024, height: 768
Initializing glyph cache
Finished initializing glyph cache in 0.049488378
width: 724, height: 412
Cell Size: (9 x 17)
PTY Dimensions: Line(24) x Column(80)
width: 1024, height: 768
width: 724, height: 412

❯ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
```

**Comment by samundra** [comment] 2018-01-10 13:45
I also have the similar issue. In my case, it happened with Menlo patched powerline fonts. With Monospace font the terminal looks fine.

## output of `alacritty --version`

```
alacritty 0.1.0
```

## output of `alacritty -version`

```
Welcome to Alacritty.
Configuration loaded from /home/samundra/.config/alacritty/alacritty.yml
device_pixel_ratio: 1
width: 1024, height: 664
Initializing glyph cache
Finished initializing glyph cache in 0.039618481
width: 724, height: 412
Cell Size: (9 x 17)
PTY Dimensions: Line(24) x Column(80)
Command::spawn() failed: No such file or directory (os error 2)
```

## output of `lsb_release -a`

```
No LSB modules are available.

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

**Comment by polyzen** [comment] 2018-03-02 22:30
@averrin, have you gotten a chance to test master after #1029? This appears to be the only thing holding back the 0.2 release.

**Comment by ne-sted** [comment] 2018-03-02 22:39
I can confirm that https://github.com/jwilm/alacritty/pull/1029 fixed this

**Comment by chrisduerr** [comment] 2018-03-02 22:47
Closing this because it seems fixed. If this exact issue still exists, you can reopen the issue or just open a new one.

**Closed by chrisduerr** 2018-03-02 22:47 UTC
