### ISSUE TITLE
Significantly slower than st

### ISSUE THREAD

**Issue by rouanth** [jwilm/alacritty#179] opened 2017-01-07 12:44 UTC
```
$ ls -lh file
-rw-r--r-- 1 rouanth rouanth 39M Jan  7 15:25 file
```

I've ran `base64 file` multiple times so it would be properly cached. Then I've ran `time base64 file` on `st` with the following results:
```
real    0m9.786s
user    0m0.500s
sys     0m2.600s
```
Multiple attempts have shown that `st` outputs consistently in 9 to 10 seconds.

Then I've ran the same command with `alacritty` off-screen:
```
real    1m1.395s
user    0m1.407s
sys     0m5.950s
```
If it is present on the screen, it takes
```
real    1m25.855s
user    0m2.003s
sys     0m8.593s
```
Multiple attempts have confirmed these numbers.

I use Arch Linux, recently updated. alacritty was built just now from AUR. I use the default configuration file. `st` is built from commit `e44832408bb3` dated November 24th.

`lspci | grep VGA` says
```
00:02.0 VGA compatible controller: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display (rev 0e)
```

Both terminal emulators are run under XWayland.

I'm ready to provide additional information if requested.

**Comment by ton** [comment] 2017-01-07 15:08
I can confirm this.

Using st (latest from git), `time -p base64 alacritty` outputs:
```
real 1.29
user 0.11
sys 1.01
```
Using alacritty itself:
```
real 56.54
user 0.40
sys 2.65
```
I am running Arch Linux as well. `lspci | grep VGA` output:
```
04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Cypress PRO [Radeon HD 5850]
```

**Comment by gnunn1** [comment] 2017-01-07 19:14
In my testing alacritty is considerably slower then other terminal emulators on Linux, when I run ```time find /usr``` I see the following results:

```
alacritty: real 0m58.104s, user 0m0.590s, sys 0m1.147s

xterm: real 0m33.216s, user 0m0.717s, sys 0m1.127s

gnome-terminal: real 0m2.845s, user 0m0.367s, sys 0m0.817s
```

One reason why gnome-terminal is so fast is that I believe the VTE widget renders to a fixed frame rate in an almost vsync fashion and thus doesn't waste time rendering intermediate frames. I think this is a good design choice personally.

**Comment by Pyrolistical** [comment] 2017-01-07 19:16
Probably related to #110

**Comment by Muffindrake** [comment] 2017-01-07 20:08
Slow mesa implementation is to blame here. This is a duplicate of #125

**Comment by jwilm** [comment] 2017-01-08 03:04
Thanks for the diagnosis

**Closed by jwilm** 2017-01-08 03:04 UTC

**Comment by Samarth2005** [comment] 2021-02-11 16:13
Yeah, its true, even opening and closing the terminal somehow feels snappier when I use st. Alacritty sometimes takes a sec to open.
