### ISSUE TITLE
Unable to compile from git master

### ISSUE THREAD

**Issue by kekePower** [jwilm/alacritty#2023] opened 2019-01-20 17:06 UTC
```
error: Could not compile `alacritty`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name alacritty src/main.rs --color always --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C debuginfo=1 --cfg 'feature="default"' -C metadata=e6369db6685c562a -C extra-filename=-e6369db6685c562a --out-dir /projects/alacritty/target/release/deps -L dependency=/projects/alacritty/target/release/deps --extern alacritty=/projects/alacritty/target/release/deps/libalacritty-570a929996bbc377.rlib --extern arraydeque=/projects/alacritty/target/release/deps/libarraydeque-520a5d1526b58632.rlib --extern base64=/projects/alacritty/target/release/deps/libbase64-68bca43383b52fab.rlib --extern bitflags=/projects/alacritty/target/release/deps/libbitflags-60e13e25b621ef91.rlib --extern cgmath=/projects/alacritty/target/release/deps/libcgmath-eccf20b1a8cfa062.rlib --extern clap=/projects/alacritty/target/release/deps/libclap-2ade7f8f745df3cc.rlib --extern copypasta=/projects/alacritty/target/release/deps/libcopypasta-91d6edec8f225cfe.rlib --extern env_logger=/projects/alacritty/target/release/deps/libenv_logger-3c7775e475a5645d.rlib --extern errno=/projects/alacritty/target/release/deps/liberrno-63b52a9089a5f7fd.rlib --extern fnv=/projects/alacritty/target/release/deps/libfnv-70c0036e9413c12c.rlib --extern font=/projects/alacritty/target/release/deps/libfont-5f66cede3909f17c.rlib --extern glutin=/projects/alacritty/target/release/deps/libglutin-f650426de7170a69.rlib --extern libc=/projects/alacritty/target/release/deps/liblibc-8c74c59556b04e3f.rlib --extern log=/projects/alacritty/target/release/deps/liblog-b4f864a8b72ee11d.rlib --extern mio=/projects/alacritty/target/release/deps/libmio-c2a15f0eaf7c3038.rlib --extern mio_extras=/projects/alacritty/target/release/deps/libmio_extras-c0c76063427c300f.rlib --extern notify=/projects/alacritty/target/release/deps/libnotify-fd51588c91702729.rlib --extern parking_lot=/projects/alacritty/target/release/deps/libparking_lot-9fd59cef6b764901.rlib --extern serde=/projects/alacritty/target/release/deps/libserde-ffe0f3227c7fc3a7.rlib --extern serde_derive=/projects/alacritty/target/release/deps/libserde_derive-f33a2ce2802c6d60.so --extern serde_json=/projects/alacritty/target/release/deps/libserde_json-1246e201ec34228a.rlib --extern serde_yaml=/projects/alacritty/target/release/deps/libserde_yaml-29b3b3b9440048e2.rlib --extern static_assertions=/projects/alacritty/target/release/deps/libstatic_assertions-eab1507ec6d9e159.rlib --extern terminfo=/projects/alacritty/target/release/deps/libterminfo-564d4a586f4adb81.rlib --extern time=/projects/alacritty/target/release/deps/libtime-708408e35f77602d.rlib --extern unicode_width=/projects/alacritty/target/release/deps/libunicode_width-c2b36738eb65befe.rlib --extern url=/projects/alacritty/target/release/deps/liburl-6bd8554677ca150e.rlib --extern vte=/projects/alacritty/target/release/deps/libvte-c8e89ff1edfa8ff6.rlib --extern x11_dl=/projects/alacritty/target/release/deps/libx11_dl-ad02edc4fc67bc1e.rlib --extern xdg=/projects/alacritty/target/release/deps/libxdg-a8dda4ea534a320f.rlib -L native=/usr/lib64 -L native=/usr/lib64 -L native=/usr/lib64 -L native=/usr/lib64 -L native=/projects/alacritty/target/release/build/libloading-e1d37807919ab80c/out`
(signal: 11, SIGSEGV: invalid memory reference)
```

```
% cargo --version
cargo 1.32.0
```

```
% uname -a
Linux dellirium 4.20.3-420-joeghi-desktop-1.mga7 #1 SMP PREEMPT Wed Jan 16 23:28:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by chrisduerr** [comment] 2019-01-20 17:39
Which version of the Rust compiler are you using? This is not reproducible for me.

**Comment by kekePower** [comment] 2019-01-20 17:46
```
% rustc --version
rustc 1.32.0
```

I will ask our Rust maintainer to take a look as well. It might be something with our implementation or something...

**Comment by chrisduerr** [comment] 2019-01-20 17:51
I'd recommend testing with a different compiler version like beta or nightly. Our CI builds are all doing great, so I don't think this is an Alacritty issue.

**Comment by kekePower** [comment] 2019-01-20 17:53
I've been able to compile other things, like neovim-gtk and cargo-vendor, without issues. By far an expert, though :-)

Cheers.

**Comment by kekePower** [comment] 2019-01-20 17:56
And you're right.

Found this https://github.com/rust-lang/rust/issues/57762

**Comment by chrisduerr** [comment] 2019-01-20 17:58
Only because a certain application might not trigger a bug in Rust or your system setup, doesn't mean that it's a bug in Alacritty. :P 

I'm fine with keeping this open to track the upstream bug though.

**Comment by kekePower** [comment] 2019-01-20 18:01
I only saw it with alacritty and, as I mentioned not being an expert, thought of you :-)

**Comment by kekePower** [comment] 2019-01-20 18:05
Another reference https://github.com/void-linux/void-packages/pull/7335

**Comment by chrisduerr** [comment] 2019-01-20 18:06
Thanks for the report! Hopefully this will help others that run into the same issue.

**Comment by kekePower** [comment] 2019-01-21 16:45
Looks like it's "lto=true" that is the culprit in https://github.com/jwilm/alacritty/blob/31271c726e31f90729b5d23dac597edf68cc437a/Cargo.toml#L89

https://github.com/rust-lang/rust/issues/57801

**Comment by chrisduerr** [comment] 2019-01-21 17:05
While `lto = true` might be a requirement to trigger this bug, it's certainly not incorrect to specify it here. Alacritty actually needs LTO because disabling it would lead to performance degradation.

**Comment by forkbomb9** [comment] 2019-01-21 17:07
I cannot build with git master neither...

**Comment by kekePower** [comment] 2019-01-21 17:08
Yeah. This has been marked as a regression in Rust.

I just compiled Alacritty with it set to false to verify.

**Comment by chrisduerr** [comment] 2019-01-21 17:08
If you're unable to build from git master at this point, the recommendation is to either use rustup or disable lto until the upstream issue has been resolved.

**Comment by Mic92** [comment] 2019-01-21 17:20
This is also tracked for archlinux ([#61490](https://bugs.archlinux.org/task/61490)) and on NixOS ([#54323](https://github.com/NixOS/nixpkgs/pull/54323#issuecomment-455831637))

**Comment by chrisduerr** [comment] 2019-01-24 18:02
This has been fixed in the latest rust master.

**Closed by chrisduerr** 2019-01-24 18:02 UTC
Labels: A - deps, B - build failure
