### ISSUE TITLE
[OSX] Typing ~ freeze alacritty

### ISSUE THREAD

**Issue by DocWinter** [jwilm/alacritty#508] opened 2017-04-07 15:03 UTC
As the title says. When I type a ~, alacritty freeze. 
The symbol does not appear thought.

I don't have any logs. OSX's version is 10.12.4

**Comment by okuuva** [comment] 2017-04-16 19:39
Duplicate of #209

**Comment by jwilm** [comment] 2017-05-25 17:47
Should be fixed

**Closed by jwilm** 2017-05-25 17:47 UTC
