### ISSUE TITLE
Terminal colors do not persist after switching from tiling to floating in an editor

### ISSUE THREAD

**Issue by Cubxity** [jwilm/alacritty#3064] opened 2019-12-03 16:49 UTC
Terminal colors do not persist after switching from tiling to floating in an editor.

### System

OS: Arch Linux
Version: alacritty 0.4.0
Linux/BSD: X11, i3-gaps, compositor: picom

## Steps to reproduce:
- `printf "\e]4;1;rgb:ff/00/ff"`
- run nano
- resize the window
- exit nano (discard changes)

**Comment by chrisduerr** [comment] 2019-12-03 17:09
Can you reproduce this issue in a different terminal emulator?

It sounds like your editor might just be resetting the terminal colors, though I'm not 100% sure I understand the exact steps you're taking.

**Comment by Cubxity** [comment] 2019-12-03 17:24
Does not happen in Konsole

**Comment by Cubxity** [comment] 2019-12-03 17:26
![Peek 2019-12-03 18-25](https://user-images.githubusercontent.com/27609129/70074085-5b8a0280-15fa-11ea-9800-eda0e3f65e21.gif)

Here's a gif demonstrating

**Comment by chrisduerr** [comment] 2019-12-03 17:34
If the change in tiling mode **and** nano required? I think simplifying the repro for this would likely be very helpful.

It seems strange to me that resizing would have anything to do with it.

**Comment by chrisduerr** [comment] 2019-12-03 17:41
Also it might be worth it to test with just `printf "\e]4;1;rgb:ff/00/ff"`, instead of running the full pywal script. That should probably help make this repro even less complex.

**Comment by Cubxity** [comment] 2019-12-03 17:47
That works too

**Comment by chrisduerr** [comment] 2019-12-03 17:59
Looks like an issue with nano, if you run `TERM=xterm-termite` for example this will not happen in Alacritty.

So it seems like nano is just telling Alacritty to reset its colors and Alacritty obviously complies. So this would have to be fixed in nano I'd assume.

**Closed by chrisduerr** 2019-12-03 17:59 UTC
Labels: A - needs repro

**Comment by kchibisov** [comment] 2019-12-03 18:02
I wonder if you can repro with `TERM=alacritty` in konsole.

**Comment by chrisduerr** [comment] 2019-12-03 18:03
I was able to reproduce with `TERM=alacritty` in URxvt, so I'd assume so.

Testing Konsole is tough because it's so massive, but the behavior was consistent between Termite, Alacritty and URxvt. I'd assume that's the same for Konsole.

**Comment by kchibisov** [comment] 2019-12-03 18:07
>I was able to reproduce with TERM=alacritty in URxvt, so I'd assume so.

>Testing Konsole is tough because it's so massive, but the behavior was consistent between Termite, Alacritty and URxvt. I'd assume that's the same for Konsole.

@chrisduerr Yeah, it's enough,I guess.

Just OP mentioned Konsole, so I mentioned it.

**Comment by Cubxity** [comment] 2019-12-04 13:22
Would it be possible for you guys to add something in config like script/command to run after resize?

**Comment by nixpulvis** [comment] 2019-12-04 17:30
@Cubxity we've generally avoided too much user scripting so far, however I can see the desire for some hooks to added. For example #1528 is talking about a possible `bell_command`. However, I'd want to be careful to avoid adding an `<event>_command` for every event we process though.

This specific issue does seem better fixed by `nano` itself, since I can't reproduce it at all with `vim`. I could however get `nano` to stop doing this by running with `env TERM=ansi nano`, so depending on you use case you may be happy with that.

**Comment by chrisduerr** [comment] 2019-12-04 19:59
We will never support running scripts on resize, that just doesn't sound like a great idea at all.

But yeah, generally I'd say if you're really frequently running into this, you probably might want to look into some nicer terminal editors anyways.

If it's just about the occasional accidental nano opening, a good idea would be to just alias nano to run under a different terminfo, that should solve the issue and is basically what other terminal emulators do.
