### ISSUE TITLE
Doesn't work for Mac OSX Sierra

### ISSUE THREAD

**Issue by nojvek** [jwilm/alacritty#1853] opened 2018-11-30 18:32 UTC
![image](https://user-images.githubusercontent.com/1018196/49307799-2731b280-f48b-11e8-89bb-71de915f9f51.png)

I'd expect it to at-least work for last two versions of a major OS

**Comment by laggardkernel** [comment] 2018-12-12 04:44
Similar problem here. Failed to open the app. A prohibition symbol covers on the application icon.
macOS 10.12.6, alacritty 0.2.4.

**Comment by sts10** [comment] 2018-12-12 15:56
Same issue for me on OS X El Capitan (10.11.6). Earlier versions of Alacritty worked on this machine.

**Comment by chrisduerr** [comment] 2018-12-12 15:58
Can someone confirm if https://github.com/jwilm/alacritty/commit/973db4845c1430dc490c3a952a16d79adac4aac4 was the commit that broke everything?

It's the only thing I can imagine causing this if it worked previously.

Otherwise I'd appreciate bisecting if someone has the time to do so.

**Comment by sts10** [comment] 2018-12-12 16:37
Not sure if these are the steps you had in mind, but I went and `git reset` to the commit before [`973db48`](https://github.com/jwilm/alacritty/commit/973db4845c1430dc490c3a952a16d79adac4aac4) (742a6b48a196cabf65354862548c07d057a28d5) and built from source. To do this I ran:

```
git clone https://github.com/jwilm/alacritty.git
cd alacritty
git reset --hard 742a6b48a196cabf65354862548c07d057a28d5
make app
cp -r target/release/osx/Alacritty.app /Applications/
```

I was then able to successfully launch and run Alacritty.

**Comment by sts10** [comment] 2018-12-12 17:04
Ack, sorry, the plot thickens here a bit. 

I should have said that, when I did the steps above, I had Rust `1.30.1` installed for other purposes. 

After doing the above procedure, I removed Alacritty from my system and ran `rustup update stable` (`rustup --version` gives me `rustc 1.31.0 (abe02cefd 2018-12-04)`). I then built the latest version (not and older commit) of Alacritty from source. It worked!

**Comment by chrisduerr** [comment] 2018-12-12 17:06
Sounds like updating Rust version resolves this problem. Thanks for the update.

Closing as resolved, if updating Rust does not work, please let me know and I'll re-open.

**Comment by sts10** [comment] 2018-12-12 17:17
Well, two things: 

1. It'd be interesting to see what happens to a user running OS X 10.11 or 10.12 who doesn't have `rustup` installed at all who ruins `brew cask install alacritty` (I built from source). For example, I"d be curious what steps @laggardkernel and @nojvek to install Alacritty that led to their errors, whether that had a previous version of Alacritty installed already, and whether they had Rust installed beforehand. 

2. For users who are upgrading from Alacritty 0.2.2 or 0.2.3 to 0.2.4 (like me), it might be worth putting a note about this Rust upgrade being a troubleshooting step in the documentation somewhere.

**Comment by chrisduerr** [comment] 2018-12-12 17:57
Things like that should probably be handled by the package manager, which would be `brew` in this case. Though it might be a bit lacking compared to what Linux offers here.

It might be a constraint compiled into the binary, in which case the cask creator (not sure where the binary is coming from) would have to change it.

**Comment by nojvek** [comment] 2018-12-12 22:36
I really don’t want download rust, compile from source, fight conflicts. 

I tried both downloading the macos package from release and that failed. 

I tried brew install, that failed too. 

It’s almost 2019. Installing software on a major software shouldn’t be that hard.

**Comment by nojvek** [comment] 2018-12-12 22:38
Why are we closing this issue without getting an actual resolution ? 

Expected functionality should be that a user should be able to go to releases, download the macosx version of alacritty and it should just work.

**Comment by jedahan** [comment] 2018-12-13 15:48
Seems reasonable to open a homebrew issue to check the version of macOS and if it is before 10.13, patch in a revert to https://github.com/jwilm/alacritty/commit/973db4845c1430dc490c3a952a16d79adac4aac4 .

Next, maybe someone can investigate if there is a way to make those options in the plist optional. Either at runtime which would be a hack, or some official way. Contacting people like https://www.felix-schwarz.org/blog/2018/06/apple-event-sandboxing-in-macos-mojave might be helpful as they seem more knowledgeable at this kind of thing.

**Comment by chrisduerr** [comment] 2018-12-13 15:53
@jedahan From what I understand, 973db48 did not actually break it.

I've yet to get any reports that updating to the latest stable compiler when producing the binary does not resolve the problem. If that's really all that is required, the problem should solve itself over time once the full build pipeline of brew and travis is up to date.

Of course if that's not actually the problem, different measures would have to be taken. But so far I haven't gotten any other response.

**Comment by jedahan** [comment] 2018-12-13 16:41
Oh I misread. What confuses me is that it seems that @nojvek tried `brew cask install alacritty` and downloading the release dmg from https://github.com/jwilm/alacritty/releases/tag/v0.2.4 and neither of those worked. But other people like @laggardkernel said that `brew cask install alacritty` does work. I wonder where the discrepancy is.

**Comment by 0xazure** [comment] 2018-12-14 01:35
I can confirm that alacritty `v0.2.4` does not run on macOS `10.12.6`, neither by installing using `brew cask install alacritty` nor installing the [release `.dmg`](https://github.com/jwilm/alacritty/releases/tag/v0.2.4) (which isn't surprising given the homebrew formula just [uses the published releases](https://github.com/Homebrew/homebrew-cask/blob/2f57d71d78aa04f1aabc5ddfc539bd19800d3ca3/Casks/alacritty.rb#L5) and the formula doesn't even appear to give the option to compile from source).

Indeed,

```text
brew cask install alacritty
Updating Homebrew...

[snip]

==> Satisfying dependencies
==> Downloading https://github.com/jwilm/alacritty/releases/download/v0.2.4/Alacritty-v0.2.4.dmg
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws.com/51980455/1f2fec00-fbca-11e8-88cb-33a4e35c6f18?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Crede
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'alacritty'.
==> Installing Cask alacritty
==> Moving App 'Alacritty.app' to '/Applications/Alacritty.app'.
🍺  alacritty was successfully installed!
```

The `0.2.3` `.dmg` [from the releases page](https://github.com/jwilm/alacritty/releases/tag/v0.2.3) doesn't work either.

@chrisduerr you said:

> the problem should solve itself over time once the full build pipeline of brew and travis is up to date.

Building from source with `cargo 1.31.0 (339d9f9c8 2018-11-16)` seems to work fine, which is odd because the `0.2.4` release was built [using the same rust version](https://travis-ci.org/jwilm/alacritty/jobs/465755130), so I don't think there's any build pipeline issues to _be_ resolved.

Can we reopen this issue until there is a resolution in place? It's a bit disconcerting that following the [macOS installation instructions](https://github.com/jwilm/alacritty#macos) doesn't actually result in a working application.

**Comment by chrisduerr** [comment] 2018-12-14 01:44
If anyone owns two different versions of macOS, it might be worth testing if compiling on a higher version prevents it from working on a lower version. If that's the case, there's likely not much we can do, but that seems to be the most likely scenario.

**Comment by laggardkernel** [comment] 2018-12-14 04:03
@jedahan Sorry, I didn't make it clear. Installing alacritty through homebrew-cask doesn't work for me. After I clicked the installed app, nothing happened. Then I opened the `/Applications` folder and found a prohibition symbol covered the alacrity icon. The same thing happened with alacritty 0.2.3 and 0.2.2 I got from guthub release page. 

I guess alacrity fails to be recognized as a valid app on macOS 10.12.6. Cause if you execute the binary `/Application s/Alacritty/Contents/MacOS/alacritty` from another terminal app, it gets launched.

**Comment by dairyisscary** [comment] 2018-12-24 17:09
Apologies if this is duplicate information, but to be very clear: I'm running macos sierra and was unable to get the brew binary to run on my machine because of the messaging in OP. However, I built the binary myself with the latest rust compiler and the latest alacritty release tag and was able to use it then without troubles.

```
macos 10.12.6
rustc 1.31.1 (b6c32da9b 2018-12-18)
alacirtty  0.2.4 (7ab0b448479c9705fa14003bda97040630710b7a)
```

I suspect @chrisduerr is correct, in that building on the target platform is the cure. I don't have a 10.13 machine to test this theory with.

**Comment by dm1try** [comment] 2018-12-24 20:06
I think the build script should specify minimum supported version in `MACOSX_DEPLOYMENT_TARGET` instead of rely on the build machine version. `https://github.com/jwilm/alacritty/blob/f0180430dfea33d806ab530e789d2edb1488af6b/Makefile#L11

`$ man clang`
```
       MACOSX_DEPLOYMENT_TARGET
              If  -mmacosx-version-min  is unspecified, the default deployment target is read from this environment variable. This option only affects Darwin tar-
              gets.
```

**Comment by codevbus** [comment] 2019-01-03 17:41
Still getting this issue with OSX 10.12.6 and the brew cask install of alacritty.

**Comment by chrisduerr** [comment] 2019-01-03 18:16
@codevbus This will not be resolved until #1922 is merged and a new version is released.

**Closed** 2019-01-06 19:12 UTC
Labels: H - macos

**Comment by chrisduerr** [comment] 2019-01-07 21:46
Now that a new version is released, I'd love to get some testing done if the fix actually worked.

If anyone can test the 0.2.5, it would be much appreciated.

**Comment by dm1try** [comment] 2019-01-07 22:07
I doubt that the change in #1975 will work as expected. I think you missed the point that the binary on CI is cached between compilations(not between the CI builds, but between the compilations in the context of a single CI build).

**Comment by codevbus** [comment] 2019-01-07 22:07
Homebrew cask is still 0.2.4. Will try a download.

**Comment by codevbus** [comment] 2019-01-07 22:10
Confirming @dm1try's comment, this does **not** work for me on OSX 10.12, Alacritty 0.2.5.

**Comment by chrisduerr** [comment] 2019-01-07 22:13
@dm1try Oh, you're correct the `cargo test` runs in release mode with macOS. Now I know what you've been talking about.

https://github.com/jwilm/alacritty/pull/1987 should fix this though, I'll run that on my own CI and replace the 0.2.5 binaries asap.

I'll let you know @codevbus once that's done so we can test this again.

**Comment by dm1try** [comment] 2019-01-07 22:23
> #1987 should fix this though, I'll run that on my own CI and replace the 0.2.5 binaries asap.

Does it make more sense to run the tests with the same `MACOSX_DEPLOYMENT_TARGET` which is used for packing the binary?

**Comment by chrisduerr** [comment] 2019-01-07 22:32
@dm1try Though I understand the notion for reproducibility, I don't think it makes any difference in practice. And this way is future-proof if we ever want to set other environment variables in the Makefile. I think it should provide an appropriate solution to this problem.

**Comment by chrisduerr** [comment] 2019-01-07 23:36
@codevbus Can you confirm that https://github.com/chrisduerr/alacritty/releases/download/vmacos-ci3/Alacritty-vmacos-ci3.dmg works properly?

Of course the more testers the merrier, so help from others would be much appreciated too.

**Comment by codevbus** [comment] 2019-01-07 23:59
> @codevbus Can you confirm that https://github.com/chrisduerr/alacritty/releases/download/vmacos-ci3/Alacritty-vmacos-ci3.dmg works properly?
> 
> Of course the more testers the merrier, so help from others would be much appreciated too.

Confirming this version works.

**Comment by chrisduerr** [comment] 2019-01-08 00:12
Thanks a ton for testing! Going to upload it to the release then. The PR should cover it for future releases.

**Comment by 0xyeti** [comment] 2019-02-14 10:00
My OS version: 10.12.6
