### ISSUE TITLE
Break out a shared library for terminal emulation

### ISSUE THREAD

**Issue by dflemstr** [jwilm/alacritty#2132] opened 2019-02-26 12:25 UTC
I have created https://crates.io/crates/terminal-emulator which consists of the code from `alacritty` related to terminal emulation but packaged as a standalone library solely for that.  The idea is that this library does no IO on its own, but can be used in conjunction with a pty and UI to build a terminal emulator.

It would be great if `alacritty` could switch over to using this library for terminal emulation to separate a few concerns and increase re-use.  The terminal emulator does for example not support configuration right now; this is seen as a concern that should live outside of that library.

Right now, the emulator library lives in a "mini-mono-repo" together with https://github.com/dflemstr/mux, which uses the library in a real world application to ensure correctness and to test any changes.

If this is a good idea, the next steps would be to clean up the API of the library (now it's more or less ripped out directly) and add more tests etc. I can grant direct contributor access or break out the library into a separate repository if necessary.

**Comment by chrisduerr** [comment] 2019-02-26 12:42
While this is fundamentally something that Alacritty aims to provide, there are some problems with the process taken here.

First of all, this issue is a duplicate of #450.

There's also already an open PR which attempted to make this work better here: #1023.

It is not an option to maintain a library like this out of tree. This is a fundamental part of Alacritty which was specifically written for Alacritty and needs to be maintained by the Alacritty project. That is why the #1023 PR aims to separate the library and binary in the Alacritty repository, making it easy to manage the project in a centralized fashion.

There also is some issue with spearheading into one direction without any clear guidelines as to what the goal is. People have wanted to extract several features of Alacritty into libraries for various different reasons and these have to be unified *in advance* to make a cut that is logical for the project. It should also be explicitly stated that Alacritty will always be the primary focus of Alacritty. Functionality which is not desired in Alacritty, would not make it into a library Alacritty uses internally.

**Closed by chrisduerr** 2019-02-26 12:42 UTC

**Comment by dflemstr** [comment] 2019-02-26 13:37
@chrisduerr thanks for the reply and apologies for not linking to the existing issues (which I still think are different but related)! I will keep using the broken out library until a better option is available, and if the "`alacritty` library" fills the same use-case I'd be willing to relinquish the `terminal-emulator` crate name if necessary.

For now I prefer shipping code over participating in a design discussion about this, especially since it would seem like the discussion you linked to has stagnated.  Please consider re-opening this issue if your purist stance on alacritty dependencies changes.
