### ISSUE TITLE
Installing from cargo fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by nelsyeung** [jwilm/alacritty#1438] opened 2018-07-17 11:14 UTC
OS: Ubuntu 18.04 (Wayland)
Rust: 1.27.1

### Exact reproduction steps
I've not installed rust before, so all the commands below are exactly what I've done:
```sh
curl https://sh.rustup.rs -sSf | sh
git clone https://github.com/jwilm/alacritty.git
cd alacritty
cargo install cargo-deb
cargo deb --install
cargo-deb: unable to parse Cargo.toml
  because: invalid type: integer `1`, expected a boolean for key `profile.release.debug`
```
I am definitely on the latest version of rust:
```sh
$ rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: checking for self-updates

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.27.1 (5f2b325f6 2018-07-07)
```
This Linux machine is basically a clean install, since the only thing I've installed are `build-essentials`, `git`, `tmux` and `vim-gtk3`.

I see that #1435 is basically the same issue, but it was closed with no information and the user perhaps wasn't using the latest version.

**Comment by chrisduerr** [comment] 2018-07-17 14:51
Please make sure that `cargo` and `rustc` actually are the correct binaries provided by rustup.

The output of `cargo --version` and `rustc --version` should be `cargo 1.27.0` and `rustc 1.27.1`.

**Comment by nelsyeung** [comment] 2018-07-17 14:59
```sh
$ cargo --version
cargo 1.27.0 (1e95190e5 2018-05-27)
$ rustc --version
rustc 1.27.1 (5f2b325f6 2018-07-07)
```

**Comment by enizor** [comment] 2018-07-17 15:02
I can reproduce this.

The problem is that in Cargo.toml, `profile.XXX.debug` is parsed as either a u32 or bool by [cargo](https://github.com/rust-lang/cargo/blob/558eee4fbca56bdc4969e114ed2cc4ed7c3913bb/src/cargo/core/profiles.rs#L349) and only as a bool by [cargo-deb](https://github.com/mmstick/cargo-deb/blob/4bd257dbd9700b1b587619c0938f2013e6e25e0d/src/manifest.rs#L405)

**Comment by chrisduerr** [comment] 2018-07-17 15:04
Thanks for digging this up, it probably makes sense to fix this in `cargo-deb` then. I can look into sending a PR in a bit.

**Comment by enizor** [comment] 2018-07-17 15:11
If you don't mind I would like to try to make a PR in `cargo-deb` by myself as it seems easy to fix and would be a nice way for me to begin my Rust contributions

**Comment by chrisduerr** [comment] 2018-07-17 15:30
Please do! Thanks!

**Comment by zaript** [comment] 2018-07-17 16:22
I have solved this particular issue by changing profile.release section in Cargo.toml to
```
[profile.release]
lto = true
debug = false
```

**Comment by chrisduerr** [comment] 2018-07-17 17:02
Thanks for sharing this workaround, however we should strive to implement a solution in `cargo-deb` so everyone can benefit from it.

**Comment by enizor** [comment] 2018-07-17 17:19
PR in `cargo-deb`: https://github.com/mmstick/cargo-deb/pull/69

Actually the build would not fail with the latest commit from `cargo-deb` (uses `cargo-toml: "0.3.0"`), my PR only makes `debug: 0` be interpreted as `false` instead of `true`.

The issue will be solved when `cargo-deb` has a new release. In the meantime, one can either:

 - replace `debug = 1` by either `debug = true`, `debug = false`
 - use latest cargo-deb by installing it via `cargo install --git https://github.com/mmstick/cargo-deb cargo-deb`

**Comment by chrisduerr** [comment] 2018-07-17 17:21
Thanks for the heads-up! Closing this issue then since it seems to already be fixed upstream.

**Closed by chrisduerr** 2018-07-17 17:21 UTC

**Comment by vanor89** [comment] 2019-06-19 20:56
Using latest did not fix;
```
alacritty on  master via 𝗥 v1.35.0 took 1m 23s 
➜ cargo deb --install --manifest-path Cargo.toml                            
cargo-deb: There is no root package in cargo metadata
```

Possibly should have just changed to true

**Comment by chrisduerr** [comment] 2019-06-19 21:09
@vanor89 Please see the INSTALL.md for instructions on building the cargo-deb. The instructions there should work.
