### ISSUE TITLE
Resizing window gives bad performance

### ISSUE THREAD

**Issue by tellowkrinkle** [jwilm/alacritty#1529] opened 2018-08-31 08:57 UTC
OS: Mac OS 10.13.6（17G65）

Steps to reproduce:
- Launch alacritty
- Quickly resize the window to something large
- Run [this program](https://github.com/jwilm/alacritty/files/2339241/main.c.zip) with the argument `10000` which will write 10000 4096-byte buffers of `a`s to stdout

Expected result: takes the same amount of time as it does if you don't resize (0.7s on my computer)
Actual result: takes over 10 times as long (10.7s on my computer)
Note: For some reason, resizing the window a few characters at a time avoids the issue, it only happens if you resize it a bunch at a time.

Possible cause:
I ran an Instruments System Trace on alacritty while the issue was happening and there appears to be an issue with a mutex being held during an OpenGL call which ends up taking 16ms.  
Here's what appears to be a processing thread, which appears to be happily spamming the read syscall until it suddenly gets stuck on a mutex and is blocked for 19.12ms on a psynch_cvwait call.  In the end, it only ends up processing anything about 15% of the time, the rest of the time is spent waiting. 
<img width="1680" alt="parsethread" src="https://user-images.githubusercontent.com/3315070/44901754-e1b7ea80-accd-11e8-95e0-fa49ffa8a270.png">
At the time that the processing thread was waiting for the main thread, the main thread was in the middle of what I assume is an OpenGL call, since the stack trace goes through a bunch of functions that look like they're from OpenGL.  The main thread proceeds to call two more OpenGL things (the two other `mach_msg_trap`s have similar backtraces) before finally calling `psynch_cvsignal` which unblocks the processing thread.
<img width="1680" alt="mainthread" src="https://user-images.githubusercontent.com/3315070/44901842-1461e300-acce-11e8-845d-1cfab3d8c5f6.png">

**Comment by chrisduerr** [comment] 2018-08-31 14:34
Thanks for the report and thanks for looking into this!

There's an issue which might be slightly related to this which can be found here: #969.

Since there aren't a lot of places where Alacritty blocks on a mutex, I'd assume that this is related to the `draw` method in the `Display` struct. The current master includes a workaround for mesa which might cause suboptimal timings with the mutex lock.

You can try #1518 though, it changes the workaround of the mesa bug a bit and also causes different mutex locking behavior. With a bit of luck the slight reordering of instructions might resolve this issue already.

**Comment by tellowkrinkle** [comment] 2018-09-02 09:51
Neither of those fixes worked

What did work is moving [this `drop(terminal)`](https://github.com/jwilm/alacritty/blob/1adb5cb7fc05054197aa08e0d1fa957df94888ab/src/display.rs#L394) in front of [this block](https://github.com/jwilm/alacritty/blob/1adb5cb7fc05054197aa08e0d1fa957df94888ab/src/display.rs#L356-L391) and caching the result of [`terminal.renderable_cells(config, selection, window_focused)`](https://github.com/jwilm/alacritty/blob/1adb5cb7fc05054197aa08e0d1fa957df94888ab/src/display.rs#L377) into a vec right before the drop, though I would guess that's not the optimal solution.

I also checked what was different about the pre-resize window, and it appears that the slow OpenGL call is instead one that happens directly after the release of the mutex (rather than one before) and is a call with this backtrace: 
<img width="509" alt="image" src="https://user-images.githubusercontent.com/3315070/44954460-2a0b1000-ae68-11e8-992d-e17480b9f69a.png">
Due to the timing, I would guess it's [this call](https://github.com/jwilm/alacritty/blob/1adb5cb7fc05054197aa08e0d1fa957df94888ab/src/display.rs#L409), and moving the drop past it does indeed make it slow no matter what.

Note: The backtrace of the slow program is in a call to `RenderApi::render_batch` so I would guess it's during [this call](https://github.com/jwilm/alacritty/blob/1adb5cb7fc05054197aa08e0d1fa957df94888ab/src/display.rs#L376)

**Comment by trimental** [comment] 2018-09-02 12:40
With https://github.com/jwilm/alacritty/pull/1518 changing the `terminal` argument for `draw()` to a `FairMutex`, perhaps `api.render_cells()` can take that mutex and call `terminal.renderable_cells()` while terminal isn't blocked. 

@chrisduerr If that is decided to be the best solution I can add it to https://github.com/jwilm/alacritty/pull/1518 if you think its in the scope of that PR.

**Comment by trimental** [comment] 2018-09-02 13:13
Sorry my bad, I didn't realize that `api.render_cells()` took an iterator, maybe storing the cells is the only way like @tellowkrinkle said?

**Comment by jwilm** [comment] 2018-09-05 16:26
I filed #1535 to track implementation.

**Comment by jwilm** [comment] 2018-09-05 16:27
> If that is decided to be the best solution I can add it to #1518 if you think its in the scope of that PR.

If you decide to work on this, it would be preferable to have an independent PR.

**Comment by trimental** [comment] 2018-09-06 04:43
@jwilm I'll probably wait till #1518 is merged before I put in a PR as it depends quite a bit on how it passes FairMutexs to drawing functions and locks the terminal however, some else can make the PR now if they'd like and rebase it later

**Comment by chrisduerr** [comment] 2018-09-29 12:42
The #1607 PR aims to fix this issue, however it hasn't been tested on macOS. So if anyone is willing to see if this issue is still present, please report on that PR.

**Closed** 2018-09-30 21:54 UTC
Labels: B - bug, H - macos, performance

**Comment by chrisduerr** [comment] 2018-09-30 21:55
This has been automatically closed since #1607 has been merged and it should resolve this problem. However it was never confirmed if it actually does fix this.

So if this issue is still present, please leave a comment and I'll re-open it.

**Comment by mymmrac** [comment] 2021-11-25 08:17
@chrisduerr On MacOS Big Sur 11.6.1 with Alacritty 0.9.0 (fed349a) issue still present, but only on MacBook, on Mac Mini no issues found with same configuration.

**Comment by Foosec** [comment] 2022-01-21 15:44
This issue still persists on Monterey

**Comment by tellowkrinkle** [comment] 2022-03-08 22:48
> This issue still persists on Monterey

I can no longer reproduce the issue.  If you're still having the issue, grab an Instruments System Trace similar to the one I posted when I was having the issue.  If you're having trouble interpreting it, save the trace and upload it and I can take a look.
