### ISSUE TITLE
crashes on cat /dev/urandom

### ISSUE THREAD

**Issue by matthiaskrgr** [jwilm/alacritty#2231] opened 2019-03-29 18:59 UTC
Which operating system does the issue occur on?
linux

If on linux, are you using X11 or Wayland?
x11

alacritty @ 28636923e02a6cfac0fc950b963623cbcad5fda9

build with `RUSTFLAGS="-C opt-level=3 -C debuginfo=2    -C debug-assertions=y"`

````
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=02
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1716] Carriage return
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=81
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=01
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1c
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:2184] Setting active charset G1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1f
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8f
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=89
[2019-03-29 19:58] [DEBUG] [unhandled] esc_dispatch params=[], ints=[], byte='9' (39)
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=02
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1677] Putting tab: 1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=18
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1706] Backspace
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8a
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1779] Setting horizontal tabstop
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=04
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=86
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=16
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=11
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=13
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=03
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1736] Bell
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:2184] Setting active charset G0
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=86
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:2184] Setting active charset G1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=89
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=10
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8f
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8f
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8b
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1779] Setting horizontal tabstop
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=01
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=03
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8b
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=82
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=92
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8c
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1677] Putting tab: 1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=14
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1f
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8a
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=82
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8c
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8f
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=9c
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8f
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1779] Setting horizontal tabstop
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=17
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1716] Carriage return
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=03
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1779] Setting horizontal tabstop
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:2184] Setting active charset G0
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1779] Setting horizontal tabstop
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8f
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=19
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=12
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=11
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=91
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8b
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8d
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=18
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=99
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1c
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=93
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=06
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=99
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=01
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8a
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:2184] Setting active charset G0
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=94
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=01
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1779] Setting horizontal tabstop
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=15
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=14
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=81
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1779] Setting horizontal tabstop
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=93
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=99
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=91
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=92
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8d
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:2184] Setting active charset G0
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1716] Carriage return
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=94
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1716] Carriage return
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=92
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=00
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1779] Setting horizontal tabstop
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=94
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=00
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=06
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:2184] Setting active charset G1
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
thread 'main' panicked at 'assertion failed: self.is_char_boundary(new_len)', src/liballoc/string.rs:1123:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   6: rust_begin_unwind
             at src/libstd/panicking.rs:312
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::panicking::panic
             at src/libcore/panicking.rs:49
   9: alacritty::url::UrlParser::url
             at ./<::core::macros::panic macros>:3
             at src/url.rs:114
  10: <alacritty::term::Term as alacritty::term::Search>::url_search
             at src/term/mod.rs:137
  11: <alacritty::input::Processor<'a, A>>::update_url_highlight
             at ./src/input.rs:446
  12: <alacritty::event::Processor<N>>::handle_event
             at ./src/input.rs:409
             at ./src/event.rs:419
  13: winit::platform::platform::x11::EventsLoop::process_event
             at ./src/event.rs:527
             at /rustc/88acdb53c52cf9d3b6a2be5252e320ef443838a6/src/libcore/ops/function.rs:269
             at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.0/src/platform/linux/x11/mod.rs:844
  14: <alacritty::event::Processor<N>>::process_events
             at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.0/src/platform/linux/x11/mod.rs:264
             at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.0/src/platform/linux/mod.rs:505
             at /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.0/src/lib.rs:276
             at ./src/window.rs:223
             at ./src/event.rs:541
  15: alacritty::main
             at src/main.rs:221
             at src/main.rs:102
  16: std::rt::lang_start::{{closure}}
             at /rustc/88acdb53c52cf9d3b6a2be5252e320ef443838a6/src/libstd/rt.rs:64
  17: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:297
  18: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:87
  19: std::rt::lang_start_internal
             at src/libstd/panicking.rs:276
             at src/libstd/panic.rs:388
             at src/libstd/rt.rs:48
  20: main
  21: __libc_start_main
  22: _start
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=19
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=86
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=01
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1736] Bell
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=80
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1c
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=06
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1d
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=81
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=91
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=16
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1779] Setting horizontal tabstop
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1779] Setting horizontal tabstop
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=9c
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=96
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1743] [unimplemented] Substitute
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:2184] Setting active charset G0
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=80
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:2184] Setting active charset G1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=15
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=86
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=04
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=96
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=02
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1706] Backspace
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1472] Wrapping input
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=01
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8f
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=17
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1e
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=86
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=84
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1779] Setting horizontal tabstop
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=95
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1716] Carriage return
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=98
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1736] Bell
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8e
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=84
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:2184] Setting active charset G1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=03
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8d
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1736] Bell
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=86
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8e
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1716] Carriage return
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=18
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=14
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=04
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=04
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8c
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=84
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1706] Backspace
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8f
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8d
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1e
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=82
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1677] Putting tab: 1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=89
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=05
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1e
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1706] Backspace
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8d
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=19
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=05
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1716] Carriage return
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=05
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=11
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=84
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=89
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=80
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8e
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1d
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1716] Carriage return
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=01
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=80
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=86
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1716] Carriage return
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=98
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=12
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:2184] Setting active charset G0
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1706] Backspace
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=02
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:2184] Setting active charset G0
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=12
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=98
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1716] Carriage return
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8c
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=12
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=91
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=02
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=89
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=06
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=95
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=97
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1c
[2019-03-29 19:58] [DEBUG] [unhandled] esc_dispatch params=[], ints=[], byte='i' (69)
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=98
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1d
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=86
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=00
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=9c
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=97
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=92
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8f
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1743] [unimplemented] Substitute
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1d
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=05
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8e
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=11
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:2184] Setting active charset G0
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=97
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=01
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=9c
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1e
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=84
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1677] Putting tab: 1
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:2184] Setting active charset G1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=18
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1e
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1c
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=02
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=13
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=89
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=00
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1e
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=05
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=91
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=06
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=02
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8d
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:2184] Setting active charset G1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8f
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=83
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8a
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=19
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=81
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=10
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1736] Bell
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=80
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=81
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1472] Wrapping input
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1724] Linefeed
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1340] Scrolling up relative: origin=0, lines=1
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8a
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=92
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:2184] Setting active charset G1
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1779] Setting horizontal tabstop
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=96
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:2184] Setting active charset G0
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=17
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=86
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=12
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=01
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=9c
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=95
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=05
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=89
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=05
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1c
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=19
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=1f
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=97
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=89
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1743] [unimplemented] Substitute
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=91
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=82
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=93
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1716] Carriage return
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=94
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=98
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=04
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=02
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=84
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=92
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=89
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=91
[2019-03-29 19:58] [TRACE] [src/term/mod.rs:1716] Carriage return
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=16
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8f
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8b
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=94
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=9c
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=82
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=19
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=82
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=17
[2019-03-29 19:58] [DEBUG] [unhandled] execute byte=8a
````

**Comment by chrisduerr** [comment] 2019-03-29 20:57
Looks like the issue is at https://github.com/jwilm/alacritty/blob/master/src/url.rs#L114, which clearly has absolutely no respect for Unicode at all.

In general I'd say that most instances of `chars().enumerate()` are probably a bad idea and this is actually done correctly (using `char_indices()` just a couple of lines above that.

I've included a fix for this in https://github.com/jwilm/alacritty/pull/2230 since it's kinda related to URL issues, that fixes the issue.

**Closed** 2019-03-30 09:23 UTC
Labels: B - bug
