### ISSUE TITLE
crash on long escape sequence

### ISSUE THREAD

**Issue by thrig** [jwilm/alacritty#1505] opened 2018-08-11 14:31 UTC
printf "\033[32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32;32m"

Which operating system does the issue occur on?

Mac OS X 10.11 with some old version of alacrity (6debc4f3351446417d0c4e38173cd9ef0faa71d5), also confirmed on IRC channel.

(Other terminals support (or at least do not crash, some of them) such stupidly long sequences and stop displaying color changes after... some number of iterations.)

**Comment by chrisduerr** [comment] 2018-08-11 14:39
See https://github.com/jwilm/vte/blob/master/src/lib.rs#L299 for where the issue is caused.

The error reported is an index out of bounds with the index being 16 and the length being 16. The max length of parameters is specified [here](https://github.com/jwilm/vte/blob/master/src/lib.rs#L67).

I would assume that this simply is an off-by-one error, where the parsing is stopped at index 16 instead of at the 16th parameter (index 15).

**Comment by chrisduerr** [comment] 2018-08-11 14:41
Also note that this is not an issue with Alacritty, but with the `vte` crate you can find [here](https://github.com/jwilm/vte).

**Comment by chrisduerr** [comment] 2018-08-11 14:56
See https://github.com/jwilm/vte/pull/16 for a fix.

**Comment by chrisduerr** [comment] 2018-08-11 14:57
Also reopening since it hasn't been merged upstream yet. Github doing weird things with auto-closing issues right now.

**Closed** 2018-08-13 16:01 UTC
Labels: D - easy
