### ISSUE TITLE
diff-so-fancy rendering strange characters

### ISSUE THREAD

**Issue by wayneashleyberry** [jwilm/alacritty#1203] opened 2018-03-23 15:20 UTC
> Which operating system does the issue occur on?

macOS

> If on linux, are you using X11 or Wayland?

n/a

---

The output from [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy) does not render correctly on Alacritty.

*Alacritty*

<img width="1250" alt="screen shot 2018-03-23 at 17 19 08" src="https://user-images.githubusercontent.com/727262/37837662-797beb02-2ebe-11e8-9cc6-da81745df86f.png">

*iTerm2*

<img width="1382" alt="screen shot 2018-03-23 at 17 19 20" src="https://user-images.githubusercontent.com/727262/37837667-7d7839cc-2ebe-11e8-8bd1-d73239cf3827.png">

**Comment by sodiumjoe** [comment] 2018-03-23 17:16
seems related to https://github.com/jwilm/alacritty/issues/993

might be worth trying this branch: https://github.com/jwilm/alacritty/pull/1087

**Comment by wayneashleyberry** [comment] 2018-03-23 20:37
*iTerm2*

```
 ~ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

*Alacritty*

```
 ~ locale
LANG="en_ZA.UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by chrisduerr** [comment] 2018-03-23 20:45
Have you tried the PR that @sodiumjoe has linked?

**Comment by wayneashleyberry** [comment] 2018-03-23 21:42
Unfortunately that branch doesn't change the output for me.

**Comment by sodiumjoe** [comment] 2018-03-23 21:50
are you starting your shell as a login shell? e.g.

```
shell:
  program: /bin/zsh
  args:
    - --login
```

**Comment by wayneashleyberry** [comment] 2018-03-23 23:11
Yeah, unfortunately that doesn't change anything @sodiumjoe.

Here's my full config:

```yaml
# Configuration for Alacritty, the GPU enhanced terminal emulator

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty it self.
env:
  # TERM env customization.
  #
  # If this property is not set, alacritty will set it to xterm-256color.
  #
  # Note that some xterm terminfo databases don't declare support for italics.
  # You can verify this by checking for the presence of `smso` and `sitm` in
  # `infocmp xterm-256color`.
  TERM: xterm-256color

window:
  # Window dimensions in character columns and lines
  # (changes require restart)
  dimensions:
    columns: 162
    lines: 50

  # Adds this many blank pixels of padding around the window
  # Units are physical pixels; this is not DPI aware.
  # (change requires restart)
  padding:
    x: 4
    y: 4

  # Window decorations
  # Setting this to false will result in window without borders and title bar.
  decorations: true

scrolling:
  # How many lines of scrollback to keep,
  # '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line
  # scrolled when scrollback is enabled (history > 0).
  multiplier: 3

  # Faux Scrolling
  #
  # The `faux_multiplier` setting controls the number
  # of lines the terminal should scroll when the alternate
  # screen buffer is active. This is used to allow mouse
  # scrolling for applications like `man`.
  #
  # To disable this completely, set `faux_multiplier` to 0.
  faux_multiplier: 3


# Display tabs using this many cells (changes require restart)
tabspaces: 4

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: true

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Menlo
    # Style can be specified to pick a specific face.
    # style: Regular

  # The bold font face
  bold:
    family: Menlo
    # Style can be specified to pick a specific face.
    style: Regular

  # The italic font face
  italic:
    family: Menlo
    # Style can be specified to pick a specific face.
    style: Italic

  # Point size of the font
  size: 12.0

  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0.0
    y: 0.0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.
  glyph_offset:
    x: 0.0
    y: 0.0

  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true

# Should display the render timer
render_timer: false

# Use custom cursor colors. If true, display the cursor in the cursor.foreground
# and cursor.background colors, otherwise invert the colors of the cursor.
custom_cursor_colors: true

# Colors (Hybrid)
colors:
  # Default colors
  primary:
    background: '0x27292c'
    foreground: '0xd0d2d1'

  # Normal colors
  normal:
    black:   '0x35383b'
    red:     '0xb05655'
    green:   '0x769972'
    yellow:  '0xe1a574'
    blue:    '0x7693ac'
    magenta: '0x977ba0'
    cyan:    '0x749e99'
    white:   '0x848b92'

  # Bright colors
  bright:
    black:   '0x484c52'
    red:     '0xd27c7b'
    green:   '0xdffebe'
    yellow:  '0xf0d189'
    blue:    '0x96b1c9'
    magenta: '0xbfa5c7'
    cyan:    '0x9fc9c3'
    white:   '0xfcf7e2'

# Visual Bell
#
# Any time the BEL code is received, Alacritty "rings" the visual bell. Once
# rung, the terminal background will be set to white and transition back to the
# default background color. You can control the rate of this transition by
# setting the `duration` property (represented in milliseconds). You can also
# configure the transition function by setting the `animation` property.
#
# Possible values for `animation`
# `Ease`
# `EaseOut`
# `EaseOutSine`
# `EaseOutQuad`
# `EaseOutCubic`
# `EaseOutQuart`
# `EaseOutQuint`
# `EaseOutExpo`
# `EaseOutCirc`
# `Linear`
#
# To completely disable the visual bell, set its duration to 0.
#
visual_bell:
  animation: EaseOutExpo
  duration: 0

# Background opacity
background_opacity: 1

# Mouse bindings
#
# Currently doesn't support modifiers. Both the `mouse` and `action` fields must
# be specified.
#
# Values for `mouse`:
# - Middle
# - Left
# - Right
# - Numeric identifier such as `5`
#
# Values for `action`:
# - Paste
# - PasteSelection
# - Copy (TODO)
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # Faux Scrollback
  #
  # The `faux_scrollback_lines` setting controls the number
  # of lines the terminal should scroll when the alternate
  # screen buffer is active. This is used to allow mouse
  # scrolling for applications like `man`.
  #
  # To disable this completely, set `faux_scrollback_lines` to 0.
  faux_scrollback_lines: 1

selection:
  semantic_escape_chars: ",‚îÇ`|:\"' ()[]{}<>"

dynamic_title: true

hide_cursor_when_typing: false

# Style of the cursor
#
# Values for 'cursor_style':
# - Block
# - Underline
# - Beam
cursor_style: Block

# Live config reload (changes require restart)
live_config_reload: true

# Shell
#
# You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
# Entries in shell.args are passed unmodified as arguments to the shell.
#
shell:
  program: /usr/local/bin/fish
  args:
    - --login

# Key bindings
#
# Each binding is defined as an object with some properties. Most of the
# properties are optional. All of the alphabetical keys should have a letter for
# the `key` value such as `V`. Function keys are probably what you would expect
# as well (F1, F2, ..). The number keys above the main keyboard are encoded as
# `Key1`, `Key2`, etc. Keys on the number pad are encoded `Number1`, `Number2`,
# etc.  These all match the glutin::VirtualKeyCode variants.
#
# A list with all available `key` names can be found here:
# https://docs.rs/glutin/*/glutin/enum.VirtualKeyCode.html#variants
#
# Possible values for `mods`
# `Command`, `Super` refer to the super/command/windows key
# `Control` for the control key
# `Shift` for the Shift key
# `Alt` and `Option` refer to alt/option
#
# mods may be combined with a `|`. For example, requiring control and shift
# looks like:
#
# mods: Control|Shift
#
# The parser is currently quite sensitive to whitespace and capitalization -
# capitalization must match exactly, and piped items must not have whitespace
# around them.
#
# Either an `action`, `chars`, or `command` field must be present.
#   `action` must be one of `Paste`, `PasteSelection`, `Copy`, or `Quit`.
#   `chars` writes the specified string every time that binding is activated.
#     These should generally be escape sequences, but they can be configured to
#     send arbitrary strings of bytes.
#   `command` must be a map containing a `program` string, and `args` array of
#     strings. For example:
#     - { ... , command: { program: "alacritty", args: ["-e", "vttest"] } }
key_bindings:
  - { key: V,        mods: Command, action: Paste                        }
  - { key: C,        mods: Command, action: Copy                         }
  - { key: Q,        mods: Command, action: Quit                         }
  - { key: W,        mods: Command, action: Quit                         }
  - { key: Home,                    chars: "\x1bOH",   mode: AppCursor   }
  - { key: Home,                    chars: "\x1b[H",   mode: ~AppCursor  }
  - { key: End,                     chars: "\x1bOF",   mode: AppCursor   }
  - { key: End,                     chars: "\x1b[F",   mode: ~AppCursor  }
  - { key: Key0,     mods: Command, action: ResetFontSize                }
  - { key: Equals,   mods: Command, action: IncreaseFontSize             }
  - { key: Minus,    mods: Command, action: DecreaseFontSize             }
  - { key: PageUp,   mods: Shift,   chars: "\x1b[5;2~"                   }
  - { key: PageUp,   mods: Control, chars: "\x1b[5;5~"                   }
  - { key: PageUp,                  chars: "\x1b[5~"                     }
  - { key: PageDown, mods: Shift,   chars: "\x1b[6;2~"                   }
  - { key: PageDown, mods: Control, chars: "\x1b[6;5~"                   }
  - { key: PageDown,                chars: "\x1b[6~"                     }
  - { key: Tab,      mods: Shift,   chars: "\x1b[Z"                      }
  - { key: Back,                    chars: "\x7f"                        }
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                    }
  - { key: Insert,                  chars: "\x1b[2~"                     }
  - { key: Delete,                  chars: "\x1b[3~"                     }
  - { key: Left,     mods: Shift,   chars: "\x1b[1;2D"                   }
  - { key: Left,     mods: Control, chars: "\x1b[1;5D"                   }
  - { key: Left,     mods: Alt,     chars: "\x1b[1;3D"                   }
  - { key: Left,                    chars: "\x1b[D",   mode: ~AppCursor  }
  - { key: Left,                    chars: "\x1bOD",   mode: AppCursor   }
  - { key: Right,    mods: Shift,   chars: "\x1b[1;2C"                   }
  - { key: Right,    mods: Control, chars: "\x1b[1;5C"                   }
  - { key: Right,    mods: Alt,     chars: "\x1b[1;3C"                   }
  - { key: Right,                   chars: "\x1b[C",   mode: ~AppCursor  }
  - { key: Right,                   chars: "\x1bOC",   mode: AppCursor   }
  - { key: Up,       mods: Shift,   chars: "\x1b[1;2A"                   }
  - { key: Up,       mods: Control, chars: "\x1b[1;5A"                   }
  - { key: Up,       mods: Alt,     chars: "\x1b[1;3A"                   }
  - { key: Up,                      chars: "\x1b[A",   mode: ~AppCursor  }
  - { key: Up,                      chars: "\x1bOA",   mode: AppCursor   }
  - { key: Down,     mods: Shift,   chars: "\x1b[1;2B"                   }
  - { key: Down,     mods: Control, chars: "\x1b[1;5B"                   }
  - { key: Down,     mods: Alt,     chars: "\x1b[1;3B"                   }
  - { key: Down,                    chars: "\x1b[B",   mode: ~AppCursor  }
  - { key: Down,                    chars: "\x1bOB",   mode: AppCursor   }
  - { key: F1,                      chars: "\x1bOP"                      }
  - { key: F2,                      chars: "\x1bOQ"                      }
  - { key: F3,                      chars: "\x1bOR"                      }
  - { key: F4,                      chars: "\x1bOS"                      }
  - { key: F5,                      chars: "\x1b[15~"                    }
  - { key: F6,                      chars: "\x1b[17~"                    }
  - { key: F7,                      chars: "\x1b[18~"                    }
  - { key: F8,                      chars: "\x1b[19~"                    }
  - { key: F9,                      chars: "\x1b[20~"                    }
  - { key: F10,                     chars: "\x1b[21~"                    }
  - { key: F11,                     chars: "\x1b[23~"                    }
  - { key: F12,                     chars: "\x1b[24~"                    }
  - { key: F1,       mods: Shift,   chars: "\x1b[1;2P"                   }
  - { key: F2,       mods: Shift,   chars: "\x1b[1;2Q"                   }
  - { key: F3,       mods: Shift,   chars: "\x1b[1;2R"                   }
  - { key: F4,       mods: Shift,   chars: "\x1b[1;2S"                   }
  - { key: F5,       mods: Shift,   chars: "\x1b[15;2~"                  }
  - { key: F6,       mods: Shift,   chars: "\x1b[17;2~"                  }
  - { key: F7,       mods: Shift,   chars: "\x1b[18;2~"                  }
  - { key: F8,       mods: Shift,   chars: "\x1b[19;2~"                  }
  - { key: F9,       mods: Shift,   chars: "\x1b[20;2~"                  }
  - { key: F10,      mods: Shift,   chars: "\x1b[21;2~"                  }
  - { key: F11,      mods: Shift,   chars: "\x1b[23;2~"                  }
  - { key: F12,      mods: Shift,   chars: "\x1b[24;2~"                  }
  - { key: F1,       mods: Control, chars: "\x1b[1;5P"                   }
  - { key: F2,       mods: Control, chars: "\x1b[1;5Q"                   }
  - { key: F3,       mods: Control, chars: "\x1b[1;5R"                   }
  - { key: F4,       mods: Control, chars: "\x1b[1;5S"                   }
  - { key: F5,       mods: Control, chars: "\x1b[15;5~"                  }
  - { key: F6,       mods: Control, chars: "\x1b[17;5~"                  }
  - { key: F7,       mods: Control, chars: "\x1b[18;5~"                  }
  - { key: F8,       mods: Control, chars: "\x1b[19;5~"                  }
  - { key: F9,       mods: Control, chars: "\x1b[20;5~"                  }
  - { key: F10,      mods: Control, chars: "\x1b[21;5~"                  }
  - { key: F11,      mods: Control, chars: "\x1b[23;5~"                  }
  - { key: F12,      mods: Control, chars: "\x1b[24;5~"                  }
  - { key: F1,       mods: Alt,     chars: "\x1b[1;6P"                   }
  - { key: F2,       mods: Alt,     chars: "\x1b[1;6Q"                   }
  - { key: F3,       mods: Alt,     chars: "\x1b[1;6R"                   }
  - { key: F4,       mods: Alt,     chars: "\x1b[1;6S"                   }
  - { key: F5,       mods: Alt,     chars: "\x1b[15;6~"                  }
  - { key: F6,       mods: Alt,     chars: "\x1b[17;6~"                  }
  - { key: F7,       mods: Alt,     chars: "\x1b[18;6~"                  }
  - { key: F8,       mods: Alt,     chars: "\x1b[19;6~"                  }
  - { key: F9,       mods: Alt,     chars: "\x1b[20;6~"                  }
  - { key: F10,      mods: Alt,     chars: "\x1b[21;6~"                  }
  - { key: F11,      mods: Alt,     chars: "\x1b[23;6~"                  }
  - { key: F12,      mods: Alt,     chars: "\x1b[24;6~"                  }
  - { key: F1,       mods: Command, chars: "\x1b[1;3P"                   }
  - { key: F2,       mods: Command, chars: "\x1b[1;3Q"                   }
  - { key: F3,       mods: Command, chars: "\x1b[1;3R"                   }
  - { key: F4,       mods: Command, chars: "\x1b[1;3S"                   }
  - { key: F5,       mods: Command, chars: "\x1b[15;3~"                  }
  - { key: F6,       mods: Command, chars: "\x1b[17;3~"                  }
  - { key: F7,       mods: Command, chars: "\x1b[18;3~"                  }
  - { key: F8,       mods: Command, chars: "\x1b[19;3~"                  }
  - { key: F9,       mods: Command, chars: "\x1b[20;3~"                  }
  - { key: F10,      mods: Command, chars: "\x1b[21;3~"                  }
  - { key: F11,      mods: Command, chars: "\x1b[23;3~"                  }
  - { key: F12,      mods: Command, chars: "\x1b[24;3~"                  }
```

**Comment by sodiumjoe** [comment] 2018-03-23 23:19
does either `export LANG=en_ZA.UTF-8`  or `export LC_CTYPE=en_ZA.UTF-8` fix it?

**Comment by sodiumjoe** [comment] 2018-03-23 23:21
for reference, this is what I get from `locale`:

```bash
➤ locale
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

**Comment by wayneashleyberry** [comment] 2018-03-24 09:12
Turns out there is no `en_ZA.UTF-8` locale!

I've switched to `en_US.UTF-8` and now all is well. The problem has even gone away on the [scrollback](https://github.com/jwilm/alacritty/tree/scrollback) branch which is what I've been running day to day!

Although this is fine for me, I'm not sure if this issue should be considered closed. Alacritty was assuming a locale that didn't exist on my machine.

**Comment by sodiumjoe** [comment] 2018-03-25 03:34
http://www.localeplanet.com/icu/en-ZA/index.html

Are you in South Africa?

It's pretty weird in any case, since it's querying the os for the locale identifier:

```rust
        let identifier: *const Object = msg_send![locale, localeIdentifier];
```

and #1087 queries for the country code:

```rust
        let country_code: *const Object = msg_send![locale, countryCode];
```

I copied that logic from iterm, so I'm not sure why the results are different. What do you get from `locale` from that branch?

**Comment by wayneashleyberry** [comment] 2018-03-25 08:42
I am indeed in South Africa.

It looks like the results of `locale` are the same on that branch:

```sh
 ~ locale
LANG="en_ZA.UTF-8"
LC_COLLATE="C"
LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

However, if I look at the available locale's... `en_ZA` doesn't even show up:

```sh
 ~ locale -a | grep ZA
af_ZA
af_ZA.UTF-8
af_ZA.ISO8859-15
af_ZA.ISO8859-1
```

**Comment by sodiumjoe** [comment] 2018-03-26 02:17
what do you get from `locale` in Terminal.app?

**Comment by wayneashleyberry** [comment] 2018-03-26 02:25
*Terminal.app*

```sh
 ~ locale
LANG=
LC_COLLATE="C"
LC_CTYPE="UTF-8"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by sodiumjoe** [comment] 2018-03-26 03:02
Ok, I found the iterm code that handles this case. I can add that to my branch, but I think in your case, the root cause is that macos doesn't support that locale properly, as you noted: https://stackoverflow.com/questions/9991603/add-a-locale-in-mac-osx

I think you may still run into issues because of this, and you probably want to stick with `en_US` or create an `en_ZA` locale.

**Comment by wayneashleyberry** [comment] 2018-03-26 06:46
Interesting @sodiumjoe, thank you for helping me find the root cause! I will be permanently switching to the `en_GB.UTF-8` locale anyway as I'm moving to the UK... but it just seemed strange that iTerm and Terminal.app could handle the output where Alacritty couldn't.

**Comment by sodiumjoe** [comment] 2018-03-27 07:44
@wayneashleyberry I just added a commit adding a check for supported locales. Do you mind trying that branch again?

**Comment by wayneashleyberry** [comment] 2018-03-27 09:21
That fixes it for me @sodiumjoe. The locale being set is slightly different, but not sure if that matters.

```diff
LANG=
LC_COLLATE="C"
- LC_CTYPE="UTF-8"
+ LC_CTYPE="C"
LC_MESSAGES="C"
LC_MONETARY="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_ALL=
```

**Comment by sodiumjoe** [comment] 2018-03-27 15:50
@wayneashleyberry iterm sets it to `UTF-8`?

**Comment by wayneashleyberry** [comment] 2018-03-27 15:59
@sodiumjoe correct

**Comment by sodiumjoe** [comment] 2018-03-27 16:00
interesting, i'll poke around some more in iterm code

**Comment by sodiumjoe** [comment] 2018-03-28 03:03
So I found where iterm does this: https://github.com/gnachman/iTerm2/blob/4d54d77ee790ca24c0b0b6bb2c8187e7011e2e43/sources/PTYSession.m#L1704

And I found this issue: https://gitlab.com/gnachman/iterm2/issues/3991#note_2635587

from gnachman:
> You can ask iTerm2 not to set this in advanced prefs in the beta version. The setting is "Never set the CTYPE environment variable.". It's not really clear what to do for certain combinations of language and country--this approach seems to fix UTF-8 support in many cases but I know it's not quite right.

IMO we should leave this logic out until somebody actually asks for it, and then figure out what to do. Seems to me that users for whom `LC_CTYPE=C` or whatever actual locale they use doesn't work should set it to `UTF-8` or whatever else manually in their shell profile.

**Comment by wayneashleyberry** [comment] 2018-03-28 06:30
Perfect. I'm very happy with that @sodiumjoe - thank you for all the help!

This issue will be closed in https://github.com/jwilm/alacritty/pull/1087

**Comment by chrisduerr** [comment] 2018-05-18 22:37
Closing because #1087 has been merged.

**Closed by chrisduerr** 2018-05-18 22:37 UTC

**Comment by unphased** [comment] 2018-05-22 20:45
Hi, I tested latest master, and unicode stopped working for all child processes: 

```
~ ❯❯❯ locale
LANG="en_US"
LC_COLLATE="en_US"
LC_CTYPE="en_US"
LC_MESSAGES="en_US"
LC_MONETARY="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_ALL=
```

I wonder if we could troubleshoot this. what's wrong with my macOS environment to make this so? if I manually `LANG=en_US.UTF-8`, things become fine.

**Comment by sodiumjoe** [comment] 2018-05-25 06:47
@unphased that was my fault, sorry about that. should be fixed in https://github.com/jwilm/alacritty/pull/1327
