### ISSUE TITLE
Incorrect space and new line handling

### ISSUE THREAD

**Issue by jerryc05** [jwilm/alacritty#3062] opened 2019-12-02 22:51 UTC
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Windows
Version: alacritty 0.4.0-rc5 (eb842c3)
Windows: ConPTY 

## Example
run `rustup default nightly-msvc`:
```
info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
info: latest update on 2019-12-02, rust version 1.41.0-nightly (4007d4ef2 2019-12-01)
info: skipping nightly which is missing installed component 'clippy-preview'
info: syncing channel updates for 'nightly-2019-12-01-x86_64-pc-windows-msvc'
info: latest update on 2019-12-01, rust version 1.41.0-nightly (d8bdb3fdc 2019-11-30)
info: skipping nightly which is missing installed component 'clippy-preview'
info: syncing channel updates for 'nightly-2019-11-30-x86_64-pc-windows-msvc'
info: latest update on 2019-11-30, rust version 1.41.0-nightly (25d8a9494 2019-11-29)
info: skipping nightly which is missing installed component 'clippy-preview'
info: syncing channel updates for 'nightly-2019-11-29-x86_64-pc-windows-msvc'
info: latest update on 2019-11-29, rust version 1.41.0-nightly (bbb664a99 2019-11-28)
info: skipping nightly which is missing installed component 'clippy-preview'
info: syncing channel updates for 'nightly-2019-11-28-x86_64-pc-windows-msvc'
info: latest update on 2019-11-28, rust version 1.41.0-nightly (e87a205c2 2019-11-27)
info: skipping nightly which is missing installed component 'clippy-preview'
info: syncing channel updates for 'nightly-2019-11-27-x86_64-pc-windows-msvc'
info: latest update on 2019-11-27, rust version 1.41.0-nightly (797fd9262 2019-11-26)
info: skipping nightly which is missing installed component 'clippy-preview'
info: syncing channel updates for 'nightly-2019-11-26-x86_64-pc-windows-msvc'
info: latest update on 2019-11-26, rust version 1.41.0-nightly (a44774c3a 2019-11-25)
info: skipping nightly which is missing installed component 'clippy-preview'
info: syncing channel updates for 'nightly-2019-11-25-x86_64-pc-windows-msvc'
info: latest update on 2019-11-25, rust version 1.41.0-nightly (412f43ac5 2019-11-24)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
  7.0 MiB /  11.9 MiB ( 58 %)   0 B/s in  1s ETA: Unknown                                                          11.9 MiB /  11.9 MiB (100 %)   7.0 MiB/s in  1s ETA:  0s
info: downloading component 'rust-std'
  7.3 MiB /  14.9 MiB ( 49 %)   0 B/s in  1s ETA: Unknown                                                          13.8 MiB /  14.9 MiB ( 93 %)   7.3 MiB/s in  2s ETA:  0s
                                                   14.9 MiB /  14.9 MiB (100 %)   6.9 MiB/s in  2s ETA:  0s
info: downloading component 'rustc'
  6.8 MiB /  35.7 MiB ( 19 %)   0 B/s in  1s ETA: Unknown                                                          13.3 MiB /  35.7 MiB ( 37 %)   6.8 MiB/s in  2s ETA:  3s
                                                   20.3 MiB /  35.7 MiB ( 57 %)   6.7 MiB/s in  3s ETA:  2s                                                          26.8 MiB /  3
5.7 MiB ( 75 %)   6.8 MiB/s in  4s ETA:  1s                                                          33.5 MiB /  35.7 MiB ( 94 %)   6.7 MiB/s in  5s ETA:  0s
                                     35.7 MiB /  35.7 MiB (100 %)   6.7 MiB/s in  5s ETA:  0s
info: downloading component 'rustc-dev'
  6.7 MiB / 170.9 MiB (  4 %)   0 B/s in  1s ETA: Unknown                                                          13.0 MiB / 170.9 MiB (  8 %)   6.7 MiB/s in  2s ETA: 23s
                                                   18.8 MiB / 170.9 MiB ( 11 %)   6.5 MiB/s in  3s ETA: 23s                                                          24.8 MiB / 17
0.9 MiB ( 14 %)   6.3 MiB/s in  4s ETA: 23s                                                          31.5 MiB / 170.9 MiB ( 18 %)   6.2 MiB/s in  5s ETA: 22s
                                     37.3 MiB / 170.9 MiB ( 22 %)   6.3 MiB/s in  6s ETA: 21s                                                          43.8 MiB / 170.9 MiB ( 26 %
)   6.1 MiB/s in  7s ETA: 20s                                                          50.2 MiB / 170.9 MiB ( 29 %)   6.2 MiB/s in  8s ETA: 19s
                       56.9 MiB / 170.9 MiB ( 33 %)   6.3 MiB/s in  9s ETA: 18s                                                          63.0 MiB / 170.9 MiB ( 37 %)   6.4 MiB/s
in 10s ETA: 16s                                                          68.5 MiB / 170.9 MiB ( 40 %)   6.3 MiB/s in 11s ETA: 16s
         73.8 MiB / 170.9 MiB ( 43 %)   6.2 MiB/s in 12s ETA: 15s                                                          80.2 MiB / 170.9 MiB ( 47 %)   6.0 MiB/s in 13s ETA: 15
s                                                          87.0 MiB / 170.9 MiB ( 51 %)   6.0 MiB/s in 14s ETA: 13s                                                          93.4
MiB / 170.9 MiB ( 55 %)   6.0 MiB/s in 15s ETA: 12s                                                          98.4 MiB / 170.9 MiB ( 58 %)   6.1 MiB/s in 16s ETA: 11s
                                            104.7 MiB / 170.9 MiB ( 61 %)   6.0 MiB/s in 17s ETA: 11s                                                         111.4 MiB / 170.9 Mi
B ( 65 %)   6.2 MiB/s in 18s ETA:  9s                                                         118.2 MiB / 170.9 MiB ( 69 %)   6.2 MiB/s in 19s ETA:  8s
                              124.9 MiB / 170.9 MiB ( 73 %)   6.2 MiB/s in 20s ETA:  7s                                                         131.2 MiB / 170.9 MiB ( 77 %)   6.
3 MiB/s in 21s ETA:  6s                                                         138.3 MiB / 170.9 MiB ( 81 %)   6.6 MiB/s in 22s ETA:  4s
                144.4 MiB / 170.9 MiB ( 84 %)   6.7 MiB/s in 23s ETA:  3s                                                         150.8 MiB / 170.9 MiB ( 88 %)   6.6 MiB/s in 24s
 ETA:  3s                                                         157.7 MiB / 170.9 MiB ( 92 %)   6.5 MiB/s in 25s ETA:  2s
  165.0 MiB / 170.9 MiB ( 97 %)   6.6 MiB/s in 26s ETA:  0s                                                         170.9 MiB / 170.9 MiB (100 %)   6.8 MiB/s in 27s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
  3.2 MiB /  11.9 MiB ( 27 %)   0 B/s in  1s ETA: Unknown                                                           7.2 MiB /  11.9 MiB ( 60 %)   3.2 MiB/s in  2s ETA:  1s
                                                    8.5 MiB /  11.9 MiB ( 71 %)   3.6 MiB/s in  3s ETA:  0s                                                           9.7 MiB /  1
1.9 MiB ( 81 %)   2.8 MiB/s in  4s ETA:  0s                                                          11.9 MiB /  11.9 MiB (100 %)   2.4 MiB/s in  4s ETA:  0s
info: installing component 'rust-std'
info: installing component 'rustc'
 13.4 MiB /  35.7 MiB ( 37 %)   0 B/s in  1s ETA: Unknown                                                          27.9 MiB /  35.7 MiB ( 78 %)  13.4 MiB/s in  2s ETA:  0s
                                                   35.7 MiB /  35.7 MiB (100 %)  13.9 MiB/s in  2s ETA:  0s
info: installing component 'rustc-dev'
 15.9 MiB / 170.9 MiB (  9 %)   0 B/s in  1s ETA: Unknown                                                          51.1 MiB / 170.9 MiB ( 30 %)  15.9 MiB/s in  2s ETA:  7s
                                                   77.1 MiB / 170.9 MiB ( 45 %)  25.6 MiB/s in  3s ETA:  3s                                                         117.0 MiB / 17
0.9 MiB ( 68 %)  25.7 MiB/s in  4s ETA:  2s                                                         135.7 MiB / 170.9 MiB ( 79 %)  29.2 MiB/s in  5s ETA:  1s
                                    163.1 MiB / 170.9 MiB ( 95 %)  27.1 MiB/s in  6s ETA:  0s                                                         170.9 MiB / 170.9 MiB (100 %
)  29.4 MiB/s in  6s ETA:  0s
info: installing component 'rustfmt'
info: default toolchain set to 'nightly-x86_64-pc-windows-msvc'
```

**Comment by chrisduerr** [comment] 2019-12-02 22:58
What exactly is the issue? Could you please describe the expected behavior?

I'd assume that you're talking about the identation of the download tracking, which looks like you might not have the right terminfo setup. What's your `TERM` set to?

**Comment by jerryc05** [comment] 2019-12-02 23:10
@chrisduerr Ahh yes I am talking about the incorrect indentation thing. 

I have no idea where the `terminfo` is and I don't think I have touched this setting anywhere. You may assume that every setting is in `default` state except `enable_experimental_conpty_backend=true`.

**Comment by davidhewitt** [comment] 2019-12-03 11:06
I believe that this is caused by the same upstream issue as #2093

Windows' pty implementation currently does the text wapping, inserting extra newlines when the line needs to wrap. I think that cargo's using `\r` to over-write the status line multiple times, but thanks to windows this glitches out visually.

If you resize the window wide enough that the line doesn't need to wrap, you should see things behave correctly.

**Comment by chrisduerr** [comment] 2019-12-03 16:22
Could you try what @davidhewitt has suggested @jerryc05, so we can confirm this is a duplicate?

**Comment by jerryc05** [comment] 2019-12-04 03:10
@chrisduerr @davidhewitt I have maximized the window, but that does not solve the problem.
Sceenshot: ![](https://i.ibb.co/q5vGgDr/Untitled.png)

**Comment by davidhewitt** [comment] 2019-12-04 13:32
Interesting, thanks. I also just had a go at the same `rustup install` command and can confirm I get the same issue as you.

I just tried in Windows Terminal, where it formats correctly. This implies it's either an old Windows conpty API issue that was fixed (and so we'll have it working soon as the fix comes downstream), or it's an unrelated bug in Alacritty.

Give me a few days to find a moment to investigate further.

**Comment by chrisduerr** [comment] 2019-12-04 20:01
Testing a few different `TERM`s would probably be a good idea. Rustup has had issues with Windows in the past, so it wouldn't surprise me if it isn't handling things correctly and just assuming things it shouldn't.

**Comment by davidhewitt** [comment] 2019-12-09 10:24
> Testing a few different TERMs would probably be a good idea. Rustup has had issues with Windows in the past, so it wouldn't surprise me if it isn't handling things correctly and just assuming things it shouldn't.

This turned out to be interesting: in Alacritty, `TERM` is set to `xterm256-color`. In Windows Terminal, `TERM` is unset.

Accordingly:
- If I set `TERM` in Windows Terminal, then the rustup output looks broken as above.
- If I unset `TERM` in Alacritty, then the rustup output looks correct

FWIW I've found an upstream rustup issue at rust-lang/rustup#1826

**Comment by kchibisov** [comment] 2019-12-09 10:35
>This turned out to be interesting: in Alacritty, TERM is set to xterm256-color. In Windows Terminal, TERM is unset.

@davidhewitt Just to make it clear. It should be `xterm-256color` and not `xterm256-color`, right?

**Comment by davidhewitt** [comment] 2019-12-09 10:40
> @davidhewitt Just to make it clear. It should be xterm-256color and not xterm256-color, right?

Yes, that's a fat finger typo by me. I've edited my comment above to avoid confusion.

**Comment by chrisduerr** [comment] 2019-12-09 17:15
Doesn't look like it's our fault. So I'll close this in favor of the rustup issue.

**Closed by chrisduerr** 2019-12-09 17:15 UTC
Labels: C - awaiting feedback, H - windows
