### ISSUE TITLE
Cargo-deb: unable to parse Cargo.toml (profile.release.debug)

### ISSUE THREAD

**Issue by acirtautas** [jwilm/alacritty#1446] opened 2018-07-19 07:08 UTC
cargo deb --install    
    cargo-deb: unable to parse Cargo.toml
       because: invalid type: integer `1`, expected a boolean for key `profile.release.debug`

https://github.com/jwilm/alacritty/blob/3dabb9783e13580ba283942d632c5469eca8956a/Cargo.toml#L61

I believe it expects a true/false value

**Comment by enizor** [comment] 2018-07-19 09:30
duplicate of #1438

**Closed** 2018-07-19 11:00 UTC
