### ISSUE TITLE
Accents bug with US International Keyboard layout (GIF)

### ISSUE THREAD

**Issue by kurko** [jwilm/alacritty#1620] opened 2018-10-03 13:48 UTC
_**Preface:** this is with Vim. Outside Vim accents don't work at all._

Just installed from `master` (64a7ca6) and the following is happening on Vim.

![screen recording 2018-10-03 at 10 39 am](https://user-images.githubusercontent.com/70312/46414266-21248d00-c6f9-11e8-8bb5-6a911047d2d6.gif)

After accents, spaces are added automatically. Then I press ESC and spaces are removed (probably by Vim), but then as I move they are still there. Not sure this is caused by Alacritty in any sense or it's just Vim tried to emulate chars.

Outside Vim, accents don't work at all.

**Which operating system does the issue occur on?**
macOS High Sierra

**Comment by chrisduerr** [comment] 2018-10-03 19:19
Would you mind testing this PR: https://github.com/jwilm/alacritty/pull/1318?

I'm pretty sure this is a duplicate of #1317, so please let me know if the linked PR resolves the issue and I can mark this as duplicate.

**Comment by chrisduerr** [comment] 2018-11-14 21:14
Closing this as a duplicate of #1317.

**Closed by chrisduerr** 2018-11-14 21:14 UTC
Labels: C - awaiting feedback
