### ISSUE TITLE
macOS mojave: ctrl-/ (ctrl-shift-7), undo doesn't work on international keyboard

### ISSUE THREAD

**Issue by dxlr8r** [jwilm/alacritty#2850] opened 2019-10-04 19:47 UTC
As the subject says. My keyboard layout doesn't have a dedicated "/" button, for this I have to press "shift-7". This works with an the same international keyboard/layout, using the Linux client though. 

It also works with iTerm2 and xterm (XQuartz) on the same macOS.

**Comment by chrisduerr** [comment] 2019-10-04 20:04
What exactly is the problem? What 'undo' are you talking about?

**Comment by dxlr8r** [comment] 2019-10-04 20:30
ctrl-/ is used by bash, emacs, etc. to undo. But in general, ctrl-shift doesn't work, I only used undo as a an example.

**Comment by chrisduerr** [comment] 2019-10-04 20:39
What do you get when pressing ctrl+v and then press ctrl+shift+7?

**Comment by dxlr8r** [comment] 2019-10-04 20:42
nothing happens in bash nor emacs

**Comment by kchibisov** [comment] 2019-10-04 20:51
Would you mind to launch alacritty with `--print-events` option and pressing `Shift + 7` and looking what event you're getting there.

Also we do have some wiki for international keyboards and macOS as a temporary workaround in [wiki](https://github.com/jwilm/alacritty/wiki/Keyboard-mappings).

And one more, if you don't mind, could you test #2438, since our windowing library has changed its handling of international keyboards a bit, maybe things will just work for you.

**Comment by dxlr8r** [comment] 2019-10-04 20:55
--print-events

```
[2019-10-04 22:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140239371113840)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
[2019-10-04 22:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140239371113840)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: true, ctrl: true, alt: false, logo: false } } } }
[2019-10-04 22:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140239371113840)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 26, state: Pressed, virtual_keycode: Some(Key7), modifiers: ModifiersState { shift: true, ctrl: true, alt: false, logo: false } } } }
[2019-10-04 22:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140239371113840)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 26, state: Released, virtual_keycode: Some(Key7), modifiers: ModifiersState { shift: true, ctrl: true, alt: false, logo: false } } } }
[2019-10-04 22:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140239371113840)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
[2019-10-04 22:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140239371113840)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
```

**Comment by kchibisov** [comment] 2019-10-04 21:16
Would you mind to try these bindings?
```
- { key: 26,       mods: Shift, chars: "/" }
- { key: 26,       mods: Control | Shift, chars: "\x1f"       }
```

**Comment by dxlr8r** [comment] 2019-10-04 21:28
I wasn't able to fetch that particular commit, so I took the latest (b0c6fdff763f7271506d26d7e768e6377fdc691b) and no difference. 

Adding the keybindings seems to have fixed that specific keybinding.

**Comment by kchibisov** [comment] 2019-10-04 21:39
To fetch #2438 you need to run `git clone https://github.com/chrisduerr/alacritty -b evlp2`

**Comment by dxlr8r** [comment] 2019-10-04 21:40
I actually just figured that out, building as we speak.

**Comment by dxlr8r** [comment] 2019-10-04 21:49
built, no difference

**Comment by kchibisov** [comment] 2019-10-04 21:51
Does `--print-events` look any different though?

**Comment by dxlr8r** [comment] 2019-10-04 21:53
```
[2019-10-04 23:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437424137056)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: true, ctrl: false, alt: false, logo: false } } } }
[2019-10-04 23:52] [INFO] glutin event: EventsCleared
[2019-10-04 23:52] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 39078944370446 }, requested_resume: None })
[2019-10-04 23:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437424137056)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: true, ctrl: true, alt: false, logo: false } } } }
[2019-10-04 23:52] [INFO] glutin event: EventsCleared
[2019-10-04 23:52] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 39078964293152 }, requested_resume: None })
[2019-10-04 23:52] [INFO] glutin event: EventsCleared
[2019-10-04 23:52] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 39079452595787 }, requested_resume: None })
[2019-10-04 23:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437424137056)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 26, state: Pressed, virtual_keycode: Some(Key7), modifiers: ModifiersState { shift: true, ctrl: true, alt: false, logo: false } } } }
[2019-10-04 23:52] [INFO] glutin event: EventsCleared
[2019-10-04 23:52] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 39079453960164 }, requested_resume: None })
[2019-10-04 23:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437424137056)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 26, state: Released, virtual_keycode: Some(Key7), modifiers: ModifiersState { shift: true, ctrl: true, alt: false, logo: false } } } }
[2019-10-04 23:52] [INFO] glutin event: EventsCleared
[2019-10-04 23:52] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 39079543810412 }, requested_resume: None })
[2019-10-04 23:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437424137056)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: true, ctrl: false, alt: false, logo: false } } } }
[2019-10-04 23:52] [INFO] glutin event: EventsCleared
[2019-10-04 23:52] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 39079679300112 }, requested_resume: None })
[2019-10-04 23:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140437424137056)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
```

**Comment by kchibisov** [comment] 2019-10-04 21:58
Does only `Shift + 7` work any different btw? Don't press Control, only `Shift + 7`.

**Comment by dxlr8r** [comment] 2019-10-04 22:01
```
[2019-10-05 00:00] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140202855253472)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: true, ctrl: false, alt: false, logo: false } } } }
[2019-10-05 00:00] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140202855253472)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 26, state: Pressed, virtual_keycode: Some(Slash), modifiers: ModifiersState { shift: true, ctrl: false, alt: false, logo: false } } } }
[2019-10-05 00:00] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140202855253472)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 26, state: Released, virtual_keycode: Some(Slash), modifiers: ModifiersState { shift: true, ctrl: false, alt: false, logo: false } } } }
[2019-10-05 00:00] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140202855253472)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
```

**Comment by kchibisov** [comment] 2019-10-04 22:02
so you're getting `/` right?

**Comment by dxlr8r** [comment] 2019-10-04 22:03
correct

**Comment by kchibisov** [comment] 2019-10-04 22:07
Let me sum up this issue a bit. 
On master: `Shift + 7` - doesn't work, `Shift + Control + 7` - doesn't - work
On #2438: `Shift + 7` - work, `Shift + Control + 7` - doesn't work 

right?

Also what's your keyboard layout, I need to report this bug upstream, that's why I'm asking.

**Comment by dxlr8r** [comment] 2019-10-04 22:10
Not quite: 

On master: `Shift + 7` - work, `Shift + Control + 7` - doesn't work
On #2438: `Shift + 7` - work, `Shift + Control + 7` - doesn't work

My keyboard layout is "Norwegian", the one for macOS is a bit different than it is for Linux/Windows, but for "/" it's the same (Shift + 7). And as I said, this was only one example, it's the same with "_" which is `Shift + -` etc.

**Comment by kchibisov** [comment] 2019-10-04 22:15
@dxlr8r I'm surprised that master work for you without any bindings though. I'm aware that some keys aren't working properly, I've used `Shift + 7` as an example.

As a work around you can use `--print-events` to get `scancode`s and bind by `scancode` like I did above.

**Comment by dxlr8r** [comment] 2019-10-04 22:22
For now I'll remain with iTerm2, but thank you for the suggestion. But I look forward to the day I can use Alacritty instead.

**Comment by chrisduerr** [comment] 2019-10-04 22:41
This is a duplicate of https://github.com/jwilm/alacritty/issues/458.

**Closed by chrisduerr** 2019-10-04 22:41 UTC
Labels: H - macos, S - keybindings

**Comment by kchibisov** [comment] 2019-10-04 22:53
@dxlr8r Sorry about asking one more thing, would you mind to post the entire log from `--print-events` when you're hitting `Shift + Control + 7`?

**Comment by dxlr8r** [comment] 2019-10-04 23:11
```
Created log file at "/var/folders/_m/b92d2cfx05bc39jpbl77gt8h0000gn/T/Alacritty-15491.log"
[2019-10-05 01:10] [INFO] Welcome to Alacritty
[2019-10-05 01:10] [INFO] Configuration loaded from "/Users/simeny/.config/alacritty/alacritty.yml"
[2019-10-05 01:10] [INFO] Device pixel ratio: 1
[2019-10-05 01:10] [INFO] Initializing glyph cache...
[2019-10-05 01:10] [INFO] ... finished initializing glyph cache in 0.045742741s
[2019-10-05 01:10] [INFO] Cell Size: 6 x 13
[2019-10-05 01:10] [INFO] Padding: 0 x 0
[2019-10-05 01:10] [INFO] Width: 800, Height: 600
[2019-10-05 01:10] [INFO] PTY Dimensions: Line(46) x Column(133)
[2019-10-05 01:10] [INFO] Initialisation complete
[2019-10-05 01:10] [INFO] glutin event: NewEvents(Init)
[2019-10-05 01:10] [INFO] glutin event: UserEvent(Wakeup)
[2019-10-05 01:10] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140507480153168)), event: RedrawRequested }
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43767733448849 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140507480153168)), event: Focused(true) }
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43767759228498 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43767761445306 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43767762396882 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43767762610093 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43767762775139 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43767762843409 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43767763431926 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43767763765674 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43767763882032 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43767763976453 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43768166478139 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43768245643564 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43768245786845 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43768245925609 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43768246121243 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140507480153168)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 56, state: Pressed, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: true, ctrl: false, alt: false, logo: false } } } }
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43769301536247 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43769301928656 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140507480153168)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: true, ctrl: true, alt: false, logo: false } } } }
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43769324433943 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140507480153168)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 26, state: Pressed, virtual_keycode: Some(Key7), modifiers: ModifiersState { shift: true, ctrl: true, alt: false, logo: false } } } }
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43769813541131 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140507480153168)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 26, state: Released, virtual_keycode: Some(Key7), modifiers: ModifiersState { shift: true, ctrl: true, alt: false, logo: false } } } }
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43769893113779 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140507480153168)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 56, state: Released, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43770037450085 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140507480153168)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43770069230131 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43770620920675 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140507480153168)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43770621285494 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43770766365293 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43770767145078 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43770767408893 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43770767606544 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140507480153168)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 2, state: Pressed, virtual_keycode: Some(D), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
[2019-10-05 01:10] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140507480153168)), event: ReceivedCharacter('\u{4}') }
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43770902315424 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: UserEvent(MouseCursorDirty)
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43770902512880 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: UserEvent(Wakeup)
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 43770903371401 }, requested_resume: None })
[2019-10-05 01:10] [INFO] glutin event: UserEvent(Wakeup)
[2019-10-05 01:10] [INFO] glutin event: UserEvent(Wakeup)
[2019-10-05 01:10] [INFO] glutin event: UserEvent(Wakeup)
[2019-10-05 01:10] [INFO] glutin event: UserEvent(Exit)
[2019-10-05 01:10] [INFO] glutin event: UserEvent(Wakeup)
[2019-10-05 01:10] [INFO] glutin event: EventsCleared
[2019-10-05 01:10] [INFO] glutin event: NewEvents(Poll)
[2019-10-05 01:10] [INFO] glutin event: LoopDestroyed
[2019-10-05 01:10] [INFO] Goodbye
Deleted log file at "/var/folders/_m/b92d2cfx05bc39jpbl77gt8h0000gn/T/Alacritty-15491.log"
```
