### ISSUE TITLE
add font fallback example to config template

### ISSUE THREAD

**Issue by matthiaskrgr** [jwilm/alacritty#1254] opened 2018-04-17 08:53 UTC
Hi, I didn't manage to get a font fallback working.
I tried different things like
````
font:
  normal:
     family: hack
     family: monospace
````

````
font:
  normal:
     family: hack
       family: monospace
````

````
font:
  normal:
     - family: hack
     - family: monospace
````

but none appeared to work.
Could we have a working fallback example in the config template?

I use alacritty from the scrollback branch.

**Comment by chrisduerr** [comment] 2018-04-17 11:09
It is currently not possible to specify fallback fonts like that. As a feature proposal this issue is a duplicate of #957.

**Closed by chrisduerr** 2018-04-17 11:09 UTC
