### ISSUE TITLE
C-SPC causes hang

### ISSUE THREAD

**Issue by zoratu** [jwilm/alacritty#283] opened 2017-01-11 01:00 UTC
Using origin/master, latest commit is 4fb7801ba3515922e3dbb8b27c1c28ec2efaf22b.

In an emacs buffer, setting a mark (C-@ or C-SPC) causes alacritty to hang. The emacs child process is healthy but doesn't receive any other signals and the screen doesn't update.

Subsequent to the hang, alacritty begins using all of one core.  MacOS "samples" attached of both emacs and alacritty.

[Sample of alacritty.txt](https://github.com/jwilm/alacritty/files/697781/Sample.of.alacritty.txt)
[Sample of emacs-25.1.txt](https://github.com/jwilm/alacritty/files/697782/Sample.of.emacs-25.1.txt)

**Comment by jwilm** [comment] 2017-01-11 02:04
I had [filed an issue](https://github.com/tomaka/glutin/issues/837) about the cocoa event loop in glutin going to 100% CPU and blocking Alacritty. Need to reopen that on winit.

Does your description reliably reproduce the problem?

**Comment by zoratu** [comment] 2017-01-11 03:59
Yes, I made sure it was repeatable before I filed the bug.

**Comment by eugene** [comment] 2017-01-16 09:47
Can confirm. In nvim, I have a binding on Ctrl+Space to clear hlsearch which also causes Alacritty to hang:

```vim
if maparg('<C-Space>', 'n') ==# ''
  nnoremap <silent> <C-Space> :nohlsearch<CR><C-L>
endif
```

**Comment by zoratu** [comment] 2017-01-16 15:56
In a new terminal running just bash, invoking C-SPC causes the hang.  No emacs or nvim required. Thanks for the confirmation!

**Comment by zoratu** [comment] 2017-01-16 16:00
I think this may be related to https://github.com/jwilm/alacritty/issues/264

**Comment by okuuva** [comment] 2017-01-19 14:10
Duplicate of #99.

**Closed** 2017-01-19 17:48 UTC
Labels: duplicate
