### ISSUE TITLE
arrow keys not repeated when held down

### ISSUE THREAD

**Issue by greg-alfaro** [jwilm/alacritty#1456] opened 2018-07-20 22:22 UTC
Which operating system does the issue occur on?
Arch x64
If on linux, are you using X11 or Wayland?
Wayland

When pressed down, the arrow keys do not function as a repeated key. Instead, when pressed and held, they only issue one instance of the key. `Urxvt` performs this operation properly and `showkey` on Alacritty indicates that it's only receiving the key once.

Using the AUR alacritty-git package. Most recent update broke this feature.

**Comment by jwilm** [comment] 2018-07-20 23:06
duplicate of #1257

**Closed by jwilm** 2018-07-20 23:06 UTC
Labels: F - duplicate
