### ISSUE TITLE
Crash when displaying CJK char

### ISSUE THREAD

**Issue by suzumiyasmith** [jwilm/alacritty#563] opened 2017-05-12 14:16 UTC
alacritty crash when
```
cat trial
```
file `trial` with content
```
JKたりやき
```
```
$ alacritty -vv
Welcome to Alacritty.
device_pixel_ratio: 1
width: 952, height: 1046
Initializing glyph cache
got font path="/usr/share/fonts/OTF/Meslo LG M DZ Regular for Powerline.otf"
got font path="/usr/share/fonts/OTF/Meslo LG M DZ Regular for Powerline.otf"
got font path="/usr/share/fonts/OTF/Meslo LG M DZ Regular for Powerline.otf"
Finished initializing glyph cache in 0.04593804
set_inner_size: 960px × 648px
width: 964, height: 652
Cell Size: (12 x 27)
PTY Dimensions: Line(24) x Column(80)
Term::resize
num_cols, num_lines = 79, 38
width: 952, height: 1046
[unhandled osc_dispatch]: [['7',],['f','i','l','e',':','/','/','S','u','z','u','/','h','o','m','e','/','s','u','z','u','m','i','y','a','/','t','m','p',],] at line 678
Term got unhandled attr: Dim
thread 'main' panicked at 'index 38 out of range for slice of length 36', /checkout/src/libcore/slice.rs:578
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Term got unhandled attr: Dim
```

**Comment by acz13** [comment] 2017-05-13 00:17
Works fine for me

```
~/dev
> cat trial
JKたりやき
```

**Comment by jwilm** [comment] 2017-05-13 00:51
There's an issue we haven't quite been able to figure out with FreeType (or the bindings) that is causing this problem. It occasionally returns data suggesting the buffer is larger than it is.

In any case, this is a dupe of #515.

**Closed by jwilm** 2017-05-13 00:51 UTC
