### ISSUE TITLE
alacritty is slower than xterm (but uses less cpu??)

### ISSUE THREAD

**Issue by Elronnd** [jwilm/alacritty#338] opened 2017-01-22 01:51 UTC
If I, for instance, do a `find /usr`, the command takes around 6 seconds to execute under alacritty but only 1 second under xterm.  However, using the `time` command, I get the following number for alacritty:

    find /usr  0.14s user 0.26s system 5% cpu 6.794 total

and for xterm:

    find /usr  0.21s user 0.35s system 42% cpu 1.318 total

What's going on here?

**Comment by okuuva** [comment] 2017-01-22 10:06
What OS are you running, I'm guessing some BSD? And what graphics drivers are you using? Could you post output for `glxinfo | grep OpenGL`?

**Comment by fatso83** [comment] 2017-01-22 10:45
Is this consistent? The second time you run a command on the file system will always be a lot faster - regardless of terminal. Could try first piping the output to a file and verify that this command takes the same amount of time in both terminals.

**Comment by Elronnd** [comment] 2017-01-22 17:49
@okuuva Arch linux.  Here are the relevant parts (I think) of that output:

    OpenGL vendor string: Intel Open Source Technology Center
    OpenGL renderer string: Mesa DRI Intel(R) HD Graphics 5500 (Broadwell GT2)
    OpenGL core profile version string: 4.5 (Core Profile) Mesa 13.0.3

@fatso83 yup, completely consistent.  I ran it a few times on both and got pretty much the same results.

**Comment by okuuva** [comment] 2017-01-22 19:58
@Elronnd ok, I made the assumption based on your user pic, even though one should never assume... Anyway, slow rendering on Mesa is a known issue, this is a duplicate of #125.

**Comment by jwilm** [comment] 2017-01-22 21:12
Closed as duplicate. Please subscribe to #125 for updates.

**Closed** 2017-01-22 21:12 UTC
Labels: duplicate
