### ISSUE TITLE
MacOS: Force uses Nvidia Graphic card.

### ISSUE THREAD

**Issue by tywtyw2002** [jwilm/alacritty#1292] opened 2018-05-02 20:22 UTC
In MacOS, the alacritty force switches to the Nvidia Graphic card.

Is possible to use Intel graphic card in order to save the battery.

**Comment by chrisduerr** [comment] 2018-05-02 20:30
This is a duplicate of #210.

**Closed by chrisduerr** 2018-05-02 20:30 UTC
