### ISSUE TITLE
cat /dev/random crashes alacritty after few seconds

### ISSUE THREAD

**Issue by artem-zinnatullin** [jwilm/alacritty#256] opened 2017-01-09 10:38 UTC
To check performance of `alacritty` I've decided to run `cat /dev/random` and compared it with standard Mac Terminal, have to say that `alacritty` is visible faster!

The problem is that `alacritty` crashes after few seconds of `cat /dev/random` with following error:

```
thread 'pty reader' panicked at 'ansi::ClearMode::Above not implemented', src/term/mod.rs:971
note: Run with `RUST_BACKTRACE=1` for a backtrace.
child finished with error '256'
``` 

I'm on commit `2fa271419c4765f7758dcf336fe0b913c12c18a6`.

**Comment by brasilikum** [comment] 2017-01-09 10:42
Same commit, backtrace is:

```sh
thread 'pty reader' panicked at 'ansi::ClearMode::Above not implemented', src/term/mod.rs:971
stack backtrace:
   1:        0x10469d086 - std::sys::imp::backtrace::tracing::imp::write::h36dcd6719b30e145
   2:        0x10469c461 - std::panicking::default_hook::{{closure}}::hce0d7336eef94718
   3:        0x10469b678 - std::panicking::rust_panic_with_hook::h33761bada49f3713
   4:        0x1045e26c1 - std::panicking::begin_panic::h5871bdf0eba452a7
   5:        0x1045e6470 - vte::Parser::perform_action::h6519e0b92f1ec8dd
   6:        0x1045f2fd2 - <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}::h90a1b963376a6c26
   7:        0x1045f1025 - <F as alloc::boxed::FnBox<A>>::call_box::h7e4796793e0fa9f9
   8:        0x1046a75b8 - std::sys::imp::thread::Thread::new::thread_start::he1b44499d44cc4a4
   9:     0x7fff90269aaa - _pthread_body
  10:     0x7fff902699f6 - _pthread_start
child finished with error '256'
```

**Comment by zinking** [comment] 2017-01-09 12:21
you are quite good at testing. 
I just typed that into my macOS terminal, and that crashed too

**Comment by theduke** [comment] 2017-01-09 12:41
Just as a side note, /dev/urandom is probably the wiser choice for perf testing, /dev/random will stall pretty quickly.

**Comment by pmatos** [comment] 2017-01-09 14:16
Can't reproduce. Get #258 instead.

**Comment by okuuva** [comment] 2017-01-09 14:51
Possible duplicate of #63.

**Comment by jwilm** [comment] 2017-01-09 17:17
Tracking this in #63

**Closed by jwilm** 2017-01-09 17:17 UTC
