### ISSUE TITLE
LBracket matches both [ and { on OS X

### ISSUE THREAD

**Issue by hellerve** [jwilm/alacritty#2579] opened 2019-06-22 20:10 UTC
This issue occurs on OS X 10.14.5. I’m using a standard German keyboard, and thus would like to use these mappings for brackets:

```
  - { key: LBracket, mods: Alt,     chars: "["                           }
  - { key: RBracket, mods: Alt,     chars: "]"                           }
```

And these for curlies:

```
# NB: LCurlyBracket doesn’t exist.
  - { key: LCurlyBracket, mods: Alt,     chars: "{"                           }
  - { key: RCurlyBracket, mods: Alt,     chars: "}"                           }
```

Apart from the problem that glutin apparently does not expose curly brackets as a key—which I could work around using the integer keycodes, as I did with `|`—, the `LBracket` and `RBracket` rules also match curly brackets!

This means that a left bracket will be inserted on both `Alt+5`—the standard—and `Alt+8`—the standard for curly brackets.

I’m not sure whether anyone can reproduce this, but I’m using the builtin Mac keyboard on a standard early 2016 Macbook Pro, so I don’t think it should be caused by any peripheral acting weirdly? (Terminal.app or any other application I use also doesn’t seem to have this problem)

Cheers

**Comment by hellerve** [comment] 2019-06-22 20:10
This is possibly related, but AFAICT not the same as #1349?

**Comment by chrisduerr** [comment] 2019-06-22 20:50
This is probably because the { character is just the shifted version of the [ character on the US keyboard. When you start Alacritty with `--print-events`, do you get the same output for both keys?

**Comment by hellerve** [comment] 2019-06-23 09:26
I do, even the scancodes are the same actually. That’s a little suboptimal.

I assume this is a glutin problem rather than an alacritty problem, though?

**Comment by chrisduerr** [comment] 2019-06-23 12:48
Usually the scancode comes directly from the OS. So that sounds like the operating system reports them as the same keys. I'm not sure if there's anything winit can do about that.

**Comment by kchibisov** [comment] 2019-06-23 13:08
@chrisduerr macOS i a little bit weird in some [cases](https://github.com/rust-windowing/winit/blob/8d6e8bb8d1bc49da251fe16a16ac1b3cb1636717/src/platform_impl/macos/event.rs#L211)(I've initially implemented this function long time ago and yeah, there is no way to check it `F21-F24`, I guess). So maybe this chars have the same `scancode`s, but encoded in char properties?

**Comment by hellerve** [comment] 2019-06-23 17:27
How does that work, since other applications do not seem to have that problem? Do they have access to other properties?

**Comment by kchibisov** [comment] 2019-06-23 18:26
@hellerve I don't know how apple implements this, but what I know is that keyboard events have `characters` + `scancode`, and `winit` (our windowing library) matches by `scancode` and searches in `characters` (thats a thing you get from low level api) for `F21-F24`. So we can perform similar checks for other characters as it's done for `F21-F24` and create proper events.

As for other applications, I think they are using more high level abstractions provided by apple. So such cases are handled.

Could you launch alacritty with `--print-events`, press your problem keys and post your output here? I'll try to prove my theory (create a patch) about macOs behavior, but no guaranties ( I have neither macOs nor german keyboard to test this).

**Comment by hellerve** [comment] 2019-06-23 18:29
The output is pretty verbose, but I believe these are the relevant lines:

```
[2019-06-23 20:28] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140713932144800)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 61, state: Pressed, virtual_keycode: Some(RAlt), modifiers: ModifiersState { shift: false, ctrl: false, alt: true, logo: false } } } }
[2019-06-23 20:28] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140713932144800)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 23, state: Pressed, virtual_keycode: Some(LBracket), modifiers: ModifiersState { shift: false, ctrl: false, alt: true, logo: false } } } }
[2019-06-23 20:28] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140713932144800)), event: ReceivedCharacter('[') }
[2019-06-23 20:28] [INFO] glutin event: Awakened
[2019-06-23 20:28] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140713932144800)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 23, state: Released, virtual_keycode: Some(LBracket), modifiers: ModifiersState { shift: false, ctrl: false, alt: true, logo: false } } } }
[2019-06-23 20:28] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140713932144800)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 28, state: Pressed, virtual_keycode: Some(LBracket), modifiers: ModifiersState { shift: false, ctrl: false, alt: true, logo: false } } } }
[2019-06-23 20:28] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140713932144800)), event: ReceivedCharacter('{') }
```

Let me know if you need the entire output.

**Comment by kchibisov** [comment] 2019-06-23 18:48
@hellerve I assume you've tried this binding and it doesn't work? 
`- { key: 28, mods: Alt,     chars: "{"                           }`

**Comment by hellerve** [comment] 2019-06-23 18:58
I hadn’t! Working through all of the keycodes that I noticed as missing/not working, OS X with a German keyboard seems to work (AFAICT) with these bindings:

```
  - { key: 23,       mods: Alt,     chars: "["                           }
  - { key: 22,       mods: Alt,     chars: "]"                           }
  - { key: 26,       mods: Alt,     chars: "|"                           }
  - { key: 28,       mods: Alt,     chars: "{"                           }
  - { key: 25,       mods: Alt,     chars: "}"                           }
  - { key: Backslash, mods: Alt|Shift, chars: "\\"                       }
  - { key: 37,       mods: Alt,       chars: "\x40"                      }
```

**Comment by kchibisov** [comment] 2019-06-23 19:31
@hellerve glad it works. I've looked at `winit v0.18.0` and they just matching by `scancode`. However in `winit master` things have [changed](https://github.com/rust-windowing/winit/blob/9dd15d00d8124d33421c6d2780cc3877920393b7/src/platform_impl/macos/event.rs#L15), so maybe this situation is improved. However we can't check it in `alacritty` at the moment, due to [this problem](https://github.com/jwilm/alacritty/pull/2438#issuecomment-502449278).

**Comment by chrisduerr** [comment] 2019-06-23 19:37
It should still be possible to check the glutin events in the latest master by running the glutin example.

**Comment by chrisduerr** [comment] 2019-10-31 20:12
Closing as duplicate of https://github.com/jwilm/alacritty/issues/2421.

**Closed by chrisduerr** 2019-10-31 20:12 UTC

**Comment by lovasoa** [comment] 2020-08-20 10:45
Here is what I use on my french mac keyboard

```
 # (macOS only)
  - { key: K,      mods: Command, mode: ~Vi, chars: "\x0c"            }
  - { key: Key0,   mods: Command,            action: ResetFontSize    }
  - { key: Equals, mods: Command,            action: IncreaseFontSize }
  - { key: Add,    mods: Command,            action: IncreaseFontSize }
  - { key: Minus,  mods: Command,            action: DecreaseFontSize }
  - { key: K,      mods: Command,            action: ClearHistory     }
  - { key: V,      mods: Command,            action: Paste            }
  - { key: C,      mods: Command,            action: Copy             }
  - { key: C,      mods: Command, mode: Vi,  action: ClearSelection   }
  - { key: H,      mods: Command,            action: Hide             }
  - { key: M,      mods: Command,            action: Minimize         }
  - { key: Q,      mods: Command,            action: Quit             }
  - { key: W,      mods: Command,            action: Quit             }
  - { key: N,      mods: Command,            action: SpawnNewInstance }
  - { key: F,      mods: Command|Control,    action: ToggleFullscreen }
  - { key: F,      mods: Command,            action: SearchForward    }
  - { key: B,      mods: Command,            action: SearchBackward   }
  - { key: Comma,     mods: Command,      command:
      {program: "open", args: ["~/.config/alacritty/alacritty.yml"]}     }
  - { key: N,         mods: Command,      action: SpawnNewInstance       }
  - { key: Space,     mods: Alt,          chars: " "                     }
  - { key: Back, mods: Super, chars: "\x15" } # delete word/line
  - { key: Left,     mods: Alt,     chars: "\x1bb"                       } # one word left
  - { key: Right,    mods: Alt,     chars: "\x1bf"                       } # one word right
  - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
  - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End
   # French keyboard
  - { key: LBracket, mods: Alt,     chars: "{"                           }
  - { key: RBracket, mods: Alt,     chars: "}"                           }
  - { key: LBracket, mods: Alt|Shift,chars: "["                          }
  - { key: RBracket, mods: Alt|Shift,chars: "]"                          }
  - { key: 37,        mods: Alt|Shift,chars: "|"                          }
  - { key: 47, mods: Alt|Shift, chars: "\\"                       
```

**Comment by nixpulvis** [comment] 2020-08-27 04:42
@lovasoa if you have the time, perhaps consider taking a look at https://github.com/alacritty/alacritty/wiki/Keyboard-mappings#mac-os-6 and making sure things are updated there correctly. I see other language mentions of the brackets, but not for these exact entries in French.
