### ISSUE TITLE
Fedora 31 777;preexec PS0

### ISSUE THREAD

**Issue by sbennett18** [jwilm/alacritty#3105] opened 2019-12-15 18:45 UTC
Using `alacritty` on Fedora 31 prints `777;preexec` from PS0 in bash.

See the following issue for another terminal emulator for more details/discussions:
https://github.com/TragicWarrior/libvterm/issues/147

### System

OS: Linux
Version: `alacritty 0.4.1-dev (8a83340)`
Linux/BSD: Wayland

**Comment by kchibisov** [comment] 2019-12-15 19:04
@sbennett18 can't repro on fedora 31 using a default bash settings providing by system.

However I feel like this is a duplicate of #2981 and the link you've posted kind of exposes it.

**Comment by sbennett18** [comment] 2019-12-15 20:37
Just out of curiosity, is your `TERM` set to something that doesn't begin with `xterm` or `vte`?  I'm also using a brand new install of Fedora 31.
I only did a `cargo build --release` and am running the resulting bin from Gnome for now.

The last case statement in `/etc/profile.d/vte.sh` is the source of the `777;preexec` string, and, unsurprisingly, commenting it out prevents this from showing up.

![image](https://user-images.githubusercontent.com/1417401/70868616-55781800-1f50-11ea-8d33-fe01f251428d.png)

**Comment by chrisduerr** [comment] 2019-12-15 21:14
> The last case statement in /etc/profile.d/vte.sh is the source of the 777;preexec string, and, unsurprisingly, commenting it out prevents this from showing up.

Do I understand it correctly that this issue only appears with an `xterm` or `vte` terminfo then?

First of all it seems pretty clear that it is an upstream issue, since it happens on multiple terminals and is caused by something in the shell profile.

And the other thing is that only the `alacritty` and `alacritty-direct` terminfos are supported. So with everything else, you're on your own.

**Comment by egmontkob** [comment] 2019-12-15 21:38
Do you launch Alacritty from a VTE-based terminal? (I.e. do you have the `VTE_VERSION` environment variable defined?)

Fedora patches VTE to add support for command completion notification on OSC 777, and hook up to using it in `/etc/profile.d/vte.sh`, given that VTE is detected.

That being said, OSC escape sequences have a well defined generic syntax. Alacritty should silently ignore the ones with unrecognized numbers, without emitting garbage. Otherwise it's impossible to add new OSC features without causing breakage in older Alacritty versions. Trust me, we've been there with VTE :)

**Comment by sbennett18** [comment] 2019-12-15 21:45
My loose understanding is that the Fedora recently adopted Enlightenment's `OSC 777` escape sequence for notifications in the terminal.

From this mailing list [Add signals proxying an interactive shell's precmd and preexec hooks](https://lists.fedoraproject.org/archives/list/scm-commits@lists.fedoraproject.org/thread/PNZP6VPNCDUTUXSITGK7TJBCTG7KTHXU/)
> Add sequences
>   OSC 777 ; preexec BEL
>   OSC 777 ; preexec ST
> 
> that can be used from an interactive shell's preexec hook to notify
> the terminal emulator that a new command is about to be executed.

I think I'm proposing what @egmontkob said about silently ignoring unrecognized OSC escape sequences.

**Comment by chrisduerr** [comment] 2019-12-15 21:55
> Fedora patches VTE to add support for command completion notification on OSC 777, and hook up to using it in /etc/profile.d/vte.sh, given that VTE is detected.

Oh we do. Using `echo -e "\e]777;preexec\007"` (which I assume is what this command does), will not print anything in Alacritty.

**Comment by egmontkob** [comment] 2019-12-15 21:57
Then how come a literal `777;prexec` appears, as per the original report? I guess that's what you're also trying to figure out, right? :)

**Comment by chrisduerr** [comment] 2019-12-15 21:59
> Then how come a literal 777;prexec appears, as per the original report? I guess that's what you're also trying to figure out, right? :)

Oh, it's because of the way they write their escape:

```
printf "\u009D777;preexec\u009C"
```

I'm pretty sure the only terminal that is going to work in are the VTE based ones. I'm not sure why they've gone for using the UTF8 encoding for OSC.

**Comment by chrisduerr** [comment] 2019-12-15 22:01
Closing this issue since I don't think Alacritty is doing anything 'wrong' here. If there's interest in supporting this escape, we can open a separate issue.

**Closed by chrisduerr** 2019-12-15 22:01 UTC
Labels: C - awaiting feedback

**Comment by egmontkob** [comment] 2019-12-15 22:07
Yup, I also just discovered that they use C1 here.

C1 is quite problematic, especially when combined with UTF-8. xterm deliberately doesn't support it. It's also problematic from security point of view if an application wants to make sure that it doesn't send control characters to the terminal (as part of untrusted data), but it cannot be absolutely certain about the terminal's encoding (it can only assume that the locale is set up correctly). I already regret that I added C1 support in VTE. I think it's fair if you decide not to add C1 support.

---

> Alacritty should never be advertised as VTE-based though, regardless of support for this escape.

VTE-based terminals set `$VTE_VERSION`, and _if_ you're launching Alacritty from one of them then this variable remains set. You could unset it, but arguably it shouldn't be your job. The proper solution would be if terminals agreed in one common environment variable to identify the terminal (as opposed to `$TERM` which describes its behavior), e.g. VTE would set TERM_APP=vte and you would overwrite it with TERM_APP=alacritty. But this is another story...

**Comment by chrisduerr** [comment] 2019-12-15 22:15
> I already regret that I added C1 support in VTE. I think it's fair if you decide not to add C1 support.

It's kinda interesting that it came up in here, since #2981 introduced me to the "problem" of C1 support and handling of different terminal emulators.

I've noticed that almost no terminal emulator other than Alacritty (I don't think I found any), supports the 8-bit non-utf8 encoded C1 escapes by default.

While some (Kitty and VTE at least), support only the UTF-8 encoded ones by default.

@egmontkob Are you aware of why VTE only supports them encoded as UTF-8? Is this a problem with potential character encoding conflicts, or is it just because they're never used?

> The proper solution would be if terminals agreed in one common environment variable to identify the terminal (as opposed to $TERM which describes its behavior), e.g. VTE would set TERM_APP=vte and you would overwrite it with TERM_APP=alacritty. But this is another story...

This is a way, way bigger issue, but generally I do not think there's any reason why a terminal emulator should be directly identified at all anyways, right?

Generally we shouldn't query for VTE here, but instead for OSC 777 support, regardless of which terminal emulator it is.

**Comment by egmontkob** [comment] 2019-12-15 22:26
> Are you aware of why VTE only supports them encoded as UTF-8?

In VTE, C1 is supported as the U+0080 .. U+009F characters encoded according to the current encoding.

The raw bytes 0x80 .. 0x9F cannot be supported in UTF-8 environment because they conflict with UTF-8, valid printable characters might contain these bytes.

**Comment by egmontkob** [comment] 2019-12-15 22:29
> Generally we shouldn't query for VTE here, but instead for OSC 777 support, regardless of which terminal emulator it is.

Yes, but how? There's no good answer. Hence a suboptimal workaround.

**Comment by egmontkob** [comment] 2019-12-15 22:45
I've filed [Red Hat 1783802](https://bugzilla.redhat.com/show_bug.cgi?id=1783802).

**Comment by chrisduerr** [comment] 2019-12-15 22:54
> Yes, but how? There's no good answer. Hence a suboptimal workaround.

Yeah, it makes sense, but I still feel like if people are willing to check an environment variable for manually comparing terminal emulators, they'd be willing to support some better way of querying if there was one. There's just not an easy solution to that.

> I've filed Red Hat 1783802.

That's a good idea to work around this, though in general all terminals where this is run should support VTE. But it doesn't hurt either way.

> The raw bytes 0x80 .. 0x9F cannot be supported in UTF-8 environment because they conflict with UTF-8, valid printable characters might contain these bytes.

I'm definitely not very knowledgeable about UTF-8 and unicode, but isn't there a clear destinction between the byte `0x85` for example and the unicode glyph `U+0F85`?

Since Alacritty has a separate UTF-8 and non-UTF-8 parser, we do actually add a newline when the user does `echo -e "\x85"`, but the glyph `echo -e "\u0f85"` still shows the correct glyph of course.

That's what you've been talking about, right?

Or is the issue that VTE combines these both in the same parser and thus an introducer of an escape sequence like the 8-bit CSI (`0x9b`) would cause the parser to stop interpreting unicode and instead start an escape sequence?

Thanks for your help by the way, it's very good to get some insight into how some other terminal emulators handle this.

**Comment by egmontkob** [comment] 2019-12-15 23:07
> but isn't there a clear destinction between the byte 0x85 for example and the unicode glyph U+0F85?

Yes there is. In UTF-8 the glyph U+0F85 TIBETAN MARK PALUTA is encoded as three bytes: 0xE0 0xBE 0x85. Notice the last byte, it happens to be 0x85.

Now, you might say that a valid UTF-8 character cannot _begin_ by 0x85, or by any of the single-byte C1, therefore at any moment either there's a next valid UTF-8 character or there's a next valid C1 control byte, it's always unambiguous. But it's about as ugly and fragile as it could be. E.g. control characters would make the otherwise UTF-8 stream no longer valid UTF-8, thus breaking `luit` and similar charset converting tools (`screen` and `tmux` have this functionality built-in as far as I remember, those would break too); you'd need to carefully decide what to do if a sequence is rejected because it's overlong or encodes a UTF-16 surrogate and yet contains a raw C1 byte, would you interpret that as a control character or not; and I'm sure the list of dilemmas or troubles doesn't end here. I definitely would not attempt to do this, sounds like terrible design to me.

**Comment by chrisduerr** [comment] 2019-12-15 23:12
@egmontkob Sounds very fair to me. It's important to point out that Alacritty doesn't actually accept the 8-bit escapes like `\x9b`, but instead just accepts `NEL`, `HTS` and `DECID`. So those are definitely a bit simpler and don't require the complexity of permitting full 8-bit C1 escape sequences.

**Comment by egmontkob** [comment] 2019-12-15 23:17
I don't see a difference between supporting just a few C1's or supporting all of them. If you even support just one, there's already the question: Which format do you exactly support: the single byte 0x85, or U+0085 which becomes two bytes in UTF-8? If the former then you interfere with the UTF-8 encoding in weird ways.

**Comment by chrisduerr** [comment] 2019-12-16 00:35
We support only the `0x85` format, however we do not accept them as a CSI introducer for example. It's just the distinction that the C1s are passed to Alacritty from our parser, but the parser itself just passes them through. Though in theory I don't think it would be much of a problem.

**Comment by nicm** [comment] 2019-12-16 14:17
IMO it is unfortunate to see people implementing 8-bit C1, especially when there are obvious conflicts with UTF-8 and there are no obvious advantages to using it with modern terminals. Because so few terminals support it by default, hardly anyone uses it. It would be nice if it could just be left to die.

**Comment by egmontkob** [comment] 2019-12-16 21:41
In [VTE 209](https://gitlab.gnome.org/GNOME/vte/issues/209) we decided to keep C1 support as we already have it (i.e. the U+0080 .. U+009F characters encoded in UTF-8 or whatever the current charset is). See over there for our reasons.

**Comment by chrisduerr** [comment] 2019-12-16 21:54
Very unfortunate, since this clearly has a negative impact on other terminal emulators. But that's up to VTE of course. Thanks for keeping us updated.

**Comment by egmontkob** [comment] 2019-12-16 21:57
The negative impact on other terminal emulators was _not_ done by mainstream VTE, it was introduced by Fedora's patch. And that still doesn't imply that Fedora is the culprit rather than Alacritty.

**Comment by chrisduerr** [comment] 2019-12-16 22:13
As mentioned in that issue, VTE is one of the biggest terminal emulators, so of course that comes with a certain responsibility. So that puts pressure on other terminals that these escapes should be supported too, even though that might not be a good idea.

> And that still doesn't imply that Fedora is the culprit rather than Alacritty.

Are you implying that it's Alacritty's fault that it does not work when expecting it to be VTE? I don't think that's a reasonable complaint.

**Comment by egmontkob** [comment] 2019-12-16 22:34
>  comes with a certain responsibility. So that puts pressure on other terminals that these escapes should be supported too

Following this logic, we shouldn't be able to invent anything new; and even should restrict ourselves to the common features of all other terminals? I'm not buying this.

(By the way, in _this_ story we did not even _invent_ anything new, we just interpreted contradicting specifications in one possible way, following some other terminals.)

> Are you implying that it's Alacritty's fault that it does not work when expecting it to be VTE?

It's hard to tell who is the culprit here, probably there isn't a clear answer, or it isn't solely one component responsible.

The entire `/etc/profile.d/vte.sh` is conceptually broken, but would require buy-in from at least the shells or the distributions to fix, and no one among them cares enough. The file is at the wrong place, and should not be shipped by VTE but be something common for all the terminals (or at least the ones that support OSC 7). Fedora's notification patch is broken in many ways, which was why we didn't accept it to upstream VTE; mind you, fixing it would - again - require support from bash which its author rejected. The choice of C1 rather than C0 in the patch is unfortunate. Having to rely on VTE_VERSION and not having a TERM_APP agreement among terminals is also part of the story. And so is that the bug only occurs if you launch Alacritty from VTE, which can sure happen while one is playing/experimenting/debugging terminals, but presumably shouldn't happen when one picks their favorite terminal and stick to that, no matter what that choice is.

There are many ways the problem could be mitigated, e.g. Alacritty could unset VTE_VERSION, or could implement C1 support at least to the extent that the sequence is recognized and silently dropped, or Fedora could switch to C0 (which bug is still open and I hope they will do it). And indeed one way to mitigate it could be for VTE to drop C1 support, thus forcing Fedora to change to C0, but VTE's main developer convinced me that we should not do this.

**Comment by chrisduerr** [comment] 2019-12-16 22:48
> Following this logic, we shouldn't be able to invent anything new; and even should restrict ourselves to the common features of all other terminals? I'm not buying this.

I think if something is worthwhile, pushing it is a different story than something that might be less desirable. I also think that just implementing something in a 'popular' terminal like iTerm/VTE and hoping someone buys into it is not the right approach (not saying that's the case here).

> It's hard to tell who is the culprit here, probably there isn't a clear answer, or it isn't solely one component responsible.

I'm not much concerned with finding someone to blame personally, since that's not constructive.

> Alacritty could unset VTE_VERSION

This would never, ever be an option. If we start with trying to reset things other terminals might set, that story will never end. It's just hacky workarounds all the way down.

> Having to rely on VTE_VERSION and not having a TERM_APP agreement among terminals is also part of the story

I still don't think this is a good way to solve this and this is a great issue for showcasing the problems it can cause.

**Comment by egmontkob** [comment] 2019-12-16 23:13
> I also think that just implementing something in a 'popular' terminal like iTerm/VTE and hoping someone buys into it is not the right approach

So market leaders shouldn't be allowed to invent, while 'small' ones should? I severely disagree.

> I'm not much concerned with finding someone to blame personally, since that's not constructive.

Locating the culprit (in terms of piece of software, not in terms of person to blame) is part of analyzing the situation, which might be an important step towards coming up with a solution.

> [Alacritty could unset VTE_VERSION] This would never, ever be an option.

Then I honestly hope you don't mind if the other party is not willing to workaround your problem either. ;)

**Comment by chrisduerr** [comment] 2019-12-16 23:17
> So market leaders shouldn't be allowed to invent, while 'small' ones should? I severely disagree.

There's a difference between just implementing something and abusing the userbase to force adoption in other terminal emulators and cooperating with other terminal emulators to determine what might be worthwhile adding and standardizing.

> Then I honestly hope you don't mind if the other party is not willing to workaround your problem either. ;)

So you're saying the other party, which introduced the problem by adding a non-standardized workaround that clearly doesn't work, should expect others to work around the fact that their newly standardized thing doesn't work? How does that make any sense at all?

**Comment by egmontkob** [comment] 2019-12-16 23:32
> There's a difference between just implementing something and abusing the userbase [...]

I don't see how supporting C1 would be abuse at all. We've supported them for 5 years, and we weren't the first to add them. Some other terminals had already supported them in 8-bit and in UTF-8 mode too, and some other had already supported them in 8-bit encodings only.

When it comes to interpreting multiple contradicting specifications to figure out how C1 in UTF-8 is supposed to work, what we ended up doing is _perhaps_ the most sensible resolution to this dilemma (see my comment in the VTE bug); and again, is not something without precedence.

But if I understand correctly, the current problem is not specific to UTF-8, it could easily occur with Latin-1 too, correct?

> So you're saying [...]

Please don't blame VTE for someone emitting an escape sequence in Alacritty that Alacritty does not understand. Don't even _indirectly_ blame VTE for this, as in abusing its power or whatever, please.

**Comment by chrisduerr** [comment] 2019-12-16 23:52
> I don't see how supporting C1 would be abuse at all.

I don't think I would call support for C1 abuse, it's just unfortunately specified, but that's not VTE's fault. This was more a general statement than about C1, the problem is more with the environment variable than the C1 support really.

> But if I understand correctly, the current problem is not specific to UTF-8, it could easily occur with Latin-1 too, correct?

The C1 problem wouldn't happen without UTF-8 encoding.

> Please don't blame VTE for someone emitting an escape sequence in Alacritty that Alacritty does not understand. Don't even indirectly blame VTE for this, as in abusing its power or whatever, please.

VTE introduced the `VTE_VERSION`, right? Unless the intention wasn't to identify VTE, this means VTE introduced a non-standard way to identify it meant to be used by applications running inside it, right? If VTE encourages this usage, it seems like the possible hazards probably were considered and it was accepted that it might cause problems for other terminals?

Unless VTE made this environment variable for something else of course and applications just decided to use it on their own. But based on your previous statements it seems like this is the VTE approved way to query for this feature.

Coming back to your point about finding someone to blame, so the problem can be addressed, how would this not partially be VTE's fault, if they encourage a way to query for features which causes problems for other terminal emulators? I can hardly blame Fedora for querying for a feature in the recommended way.

**Comment by egmontkob** [comment] 2019-12-17 00:34
> VTE introduced the VTE_VERSION, right?

I believe the vast majority of terminals set an environment variable to identify itself. Even xterm does.

> how would this not partially be VTE's fault, if they encourage a way to query for features which causes problems for other terminal emulators?

Do you have a better idea?

I mentioned the idea of TERM_APP, you didn't like that, although that would definitely be an improvement compared to all terminals setting their own variables, and would solve the current issue.

(And please don't come with terminfo because I could point you to a mile long page describing how utterly broken that is. For starter, it doesn't have a slot to denote whether OSC 777 is supported for desktop notification or not. The story goes on with central maintainership, lack of versioning, no ability to forward over ssh, etc.)

You just happen to pick on VTE due to the constellation of several independent issues, namely that VTE uses OSC 7 to preserve the directory when opening a new terminal; in order to do this it ships a shell startup file where it checks for itself (as reliably as it can, i.e. failing when another terminal is launched from VTE); a distribution happens to patch this script and happens to use there something that Alacritty does not support.

It _could_ just as easily happen with pretty much every other terminal, it's mostly accidental rather than by design that only VTE happens to trigger the given problem for you. If Red Hat patches VTE, why doesn't it patch Konsole, Xterm etc. for desktop notification, and add a similar /etc/profile.d/*.sh checking for KONSOLE_VERSION, XTERM_VERSION etc.? You happen to blame mainstream VTE because Red Hat decided to add a new feature to this product, whereas if they added it to Konsole or Xterm instead you would probably just as equally blame Konsole or Xterm.

I don't like VTE_VERSION and the check for it as we currently have it, but I can't think of anything better that we could start using immediately.

Let's mention again that the bug only occurs if someone launches one terminal from another, presumably an extremely rare scenario during normally using a system. Can we just conclude that launching one terminal from another (and I don't mean VTE vs. Alacritty, but pretty much any two terminals) is not a supported setup, since shell startup scripts are not tested and not guaranteed to work as expected?

I'd like to emphasize again that mainstream VTE (which I'm a developer of) does _not_ trigger this problem in Alacritty, it's a modification created by Red Hat / Fedora (which I'm not affiliated with) that triggers it. As you've seen, I've already _asked_ that distribution to change this. We could _force_ them by removing C1 from mainstream VTE, but as I agreed with VTE's main developer, we're not going to do this. The buggy behavior is the result of the constellation of many-many tiny issues, including having C1 UTF-8 support, having a vte.sh because of OSC 7, shells refusing to automatically support OSC 7 by themselves, shells refusing to add the necessary features for a proper desktop notification, Red Hat adding a new sequence using C1 rather than C0, no common environment variable or no other good standard for identifying the terminal or its OSC 777 support, and so on. Yet all I can hear from your comments is that VTE is doing pretty much everything wrong, and even if someone adds a piece of code that results in broken end-user behavior then that's also VTE's fault.

It's the end of the day for me, and unfortunately this thread has become pretty unpleasant to me, listening to how you insist that it's VTE to blame (while you refuse to fix it on your side). I'm not planning to come back to continue this discussion. Thanks for your understanding.

**Comment by chrisduerr** [comment] 2019-12-17 01:15
> I believe the vast majority of terminals set an environment variable to identify itself. Even xterm does.

I'm not sure if any of those terminal emulators encourages to use this to query for features though?

> I mentioned the idea of TERM_APP, you didn't like that, although that would definitely be an improvement compared to all terminals setting their own variables, and would solve the current issue.

Sure, it would be an improvement over `VT_VERSION`, but it would still come with many of the same issues. It's still just a hack.

> You happen to blame mainstream VTE because Red Hat decided to add a new feature to this product, whereas if they added it to Konsole or Xterm instead you would probably just as equally blame Konsole or Xterm.

Yes, I blame VTE for causing issues, because VTE caused the issue, not Konsole or XTerm. If those would be causing the issue, I'd blame them. That makes sense, right? If a cooperation of Terminal X and Distro Y, which uses an unreliable method to determine terminal features, causes problems for other projects, then of course I ask myself why Terminal X and Distro Y have to do things this way. That's only natural I'd say.

> I don't like VTE_VERSION and the check for it as we currently have it, but I can't think of anything better that we could start using immediately.

I'm not sure why it has to be used *immediately* though? Implementing a hacky workaround, just to get things done quicker and as a result affecting everyone else is precisely one of the big problems with this. The solution itself is just one approach of many possible, but rushing it out for a single terminal without sufficient regard for others is what causes troubles, not necessarily the solution itself.

> Let's mention again that the bug only occurs if someone launches one terminal from another, presumably an extremely rare scenario during normally using a system. Can we just conclude that launching one terminal from another (and I don't mean VTE vs. Alacritty, but pretty much any two terminals) is not a supported setup, since shell startup scripts are not tested and not guaranteed to work as expected?

This means that now I have to somehow explain to my users though, that it is not possible to launch Alacritty from VTE (or possibly any other terminal emulator), because the other terminal emulator has decided not to support that. Sure, I could just redirect all reports in that regard to VTE, similar to what I have to do because of GNOME CSDs already, but that's certainly not desirable?

I personally don't think making it 'unsupported' to launch one terminal emulator from another is something we should strive for at all. I'd much rather just keep playing nicely with everyone else rather than creating such a mess.

> I'd like to emphasize again that mainstream VTE (which I'm a developer of) does not trigger this problem in Alacritty, it's a modification created by Red Hat / Fedora (which I'm not affiliated with) that triggers it.

There's a couple of things that have to play together to cause this issue, that's for sure. And generally I don't think it's a big problem for Alacritty, since we can just tell people that they shouldn't have the VTE environment variable set and we should be good.

> Yet all I can hear from your comments is that VTE is doing pretty much everything wrong, and even if someone adds a piece of code that results in broken end-user behavior then that's also VTE's fault.

I don't think I've ever stated that VTE is doing **everything** wrong. I think VTE is doing something wrong by encouraging the use of an environment variable to identify terminal capabilities  and I don't think fundamentally anyone would disagree with that? It's likely just a question of weighing benefits vs rewards and for me as someone solely negatively impacted by this, it clearly doesn't sound amazing to me.

RedHat certainly should have considered the possibilities of this going wrong, but I'd assume they likely didn't have the expertise to predict this problem (I might have missed it myself if I would have just looked at the code). The only reason why I say that VTE is at least partially responsible for this, is because they use VTE's recommended way to query for a feature and that way to query for the specific feature is not sufficient to positively ID the terminal.

> It's the end of the day for me, and unfortunately this thread has become pretty unpleasant to me, listening to how you insist that it's VTE to blame (while you refuse to fix it on your side).

It's unfortunate that you see this as unpleasant, but as previously stated I have no intention of just trying to shift blame.

Though I still do not understand what you mean by me refusing to fix things on my side, since you've suggested yourself that C1 UTF-8 encoding support is something people should rather stay away from and VTE mainly keeps it because it already works. Both supporting C1 UTF-8 and VTE's environment variable would be VTE 'forcing' other projects to implement their features because of the traction it has, which is exactly what VTE is not trying to do if I understood you correctly. So that would mean that Alacritty is doing absolutely nothing wrong.

> I'm not planning to come back to continue this discussion. Thanks for your understanding.

Fair enough, I think everything relevant has been iterated on more than enough anyways.

**Comment by dnkl** [comment] 2019-12-17 17:31
I'm really sorry to see this going the way it did. It doesn't benefit anyone.

I'm with @nicm on this; 8-bit C1 control characters should go away. As seen here, they just complicate things and I think we all would be much better of if terminal emulators stopped supporting them. Especially considering the 7-bit variants are much more commonly used _and_ since both the 8-bit and 7-bit variants need 2 bytes when UTF-8 encoded.

Applications would have **one** way to do things, not two, or three - if you count single-byte 8-bit C1s and UTF-8 encoded C1s as two different variants. Leaving much less room for errors.

That said, @chrisduerr _if_ you would want to support the UTF-8 encoded variants, I do think the only sane way to do it is to put the UTF-8 decoder *before* the VT parser, and not make it _a part_ of the VT parser, like it is today. This is the way the VTE guys are doing it. But let me stress that _I_ would prefer you did **not** add support for it.

> Can we just conclude that launching one terminal from another (and I don't mean VTE vs. Alacritty, but pretty much any two terminals) is not a supported setup, since shell startup scripts are not tested and not guaranteed to work as expected?

I'm sorry, but this is just plain stupid. To me, it's like saying launching a QT/KDE from Gnome isn't a supported setup.

**Comment by chrisduerr** [comment] 2019-12-17 18:29
> I do think the only sane way to do it is to put the UTF-8 decoder before the VT parser, and not make it a part of the VT parser, like it is today.

Alacritty does the same, it first parses the content as UTF-8 and goes on in non-UTF-8 mode if it is not valid UTF-8.

What we do not do though is accept CSI/DCS/OSC introducers in UTF-8 or non-UTF-8 mode. We only accept the C0 variants of these, meaning the escape is currently not interpreted as C1, but rather as UTF-8.

**Comment by nixpulvis** [comment] 2019-12-17 20:15
From [VTE 209](https://gitlab.gnome.org/GNOME/vte/issues/209):

> The latest edition of ECMA-48 is from June 1991, UTF-8 was created in Sep 1992.

I feel like this alone is pretty good evidence that there may be some standardization work to be done here. This work would ideally be done with buy in from the major players in the terminal emulator business, but I suppose there's nothing stopping a "grassroots" standard from forming, as long as it's clear and well thought out.

Without trying to talk about the details specifically, the problem we face is in maintaining backwards compatibility with applications that are unlikely to be able or willing to change (at least not quickly). If we had a game plan for a staged removal of C1 control sequences, I feel like this could be to the benefit of everyone. While I understand we may still have untrusted data in text that causes problems, this would be one less possible case for this to happen (I haven't truly evaluated the risk here myself yet).

It's a very good property of the terminal to allow applications to be **very sure** that the control sequences they emit will be properly interpreted, regardless of locale. Otherwise we force application developers to manage far more than they are typically able, resulting in broken applications for non-native users. This is no small point.

**Comment by chrisduerr** [comment] 2019-12-17 21:30
> I suppose there's nothing stopping a "grassroots" standard from forming

I'm not sure that ever goes down pleasantly though.

> Without trying to talk about the details specifically, the problem we face is in maintaining backwards compatibility with applications that are unlikely to be able or willing to change (at least not quickly). 

Which applications are you talking about here exactly? X11 doesn't support these by default, neither does URxvt iirc. Afaik these are not used by applications yet.

**Comment by nicm** [comment] 2019-12-17 21:41
This Fedora thing is the first time I have come across anyone trying to use 8-bit C1. If there are any applications at all that won't work without it they are very rare.

**Comment by egmontkob** [comment] 2019-12-18 22:35
> > Can we just conclude that launching one terminal from another [...] is not a supported setup

> I'm sorry, but this is just plain stupid.

I stated a fact. It does not work, as you can see in this thread. I didn't say "is not supposed to be a supported setup", I said "is not a supported setup". The current situation is bad. Maybe you, or anyone else here feels like working on fixing it?

> To me, it's like saying launching a QT/KDE app from Gnome isn't a supported setup.

It's a totally wrong analogy. A better analogy would be to say that launching the KDE _desktop_ from GNOME desktop does not work. Which indeed does not.

**Comment by egmontkob** [comment] 2019-12-18 22:42
> I've heard of the ISO 6429 standard, but haven't personally read it, since it seems to cost ~$200

ECMA-48 (which is free) says "The fourth edition [...] was adopted by ISO/IEC [...] as second edition of ISO 6429". So you did not miss anything.
