### ISSUE TITLE
Flickering and dirty blocks in vim8.1

### ISSUE THREAD

**Issue by Karmenzind** [jwilm/alacritty#1424] opened 2018-07-07 07:09 UTC
env:
Arch + x11 + i3wm

-----

The flickering looks just like https://github.com/jwilm/alacritty/issues/1084.
`set nolazyredraw` didn't help.

-----

During page scrolling:
![vokoscreen-2018-07-07_14-55-19](https://user-images.githubusercontent.com/17923071/42407875-de5cdc90-81f5-11e8-9db6-915012d1f715.gif)
It doesn't happen inside tmux.

**Comment by chrisduerr** [comment] 2018-07-07 15:10
Is this on the `master` branch? Does the same issue also happen on the `scrollback` branch?

**Comment by Karmenzind** [comment] 2018-07-07 15:40
@chrisduerr  I tried master branch and the transparent blocks disappeared. Thank you very much.
Is there a plan for solving the flickering problem?

**Comment by chrisduerr** [comment] 2018-07-07 16:08
Then this sounds like a duplicate of #1376, please subscribe to that issue to stay updated.

It is a known issue and it's definitely planned to resolve it!

**Closed by chrisduerr** 2018-07-07 16:08 UTC

**Comment by darthdeus** [comment] 2018-07-23 20:57
@chrisduerr As someone curious to maybe contribute a patch (or at least dig around the code to see what's going on), could you give a hint as to what might be causing it?

**Comment by chrisduerr** [comment] 2018-07-23 21:14
See #1376 for discussions about this topic. I've already posted a potential fix for this issue, I'm still unsure if there are any issues with this though.

So if you want to help out, the best action would probably be to run that patch and see if you find any issues with it. If you're already running scrollback anyways, this should be an improvement without any drawbacks.
