### ISSUE TITLE
Emoji color display is not normal

### ISSUE THREAD

**Issue by taigacute** [jwilm/alacritty#2160] opened 2019-03-07 04:27 UTC
Which operating system does the issue occur on?
macos
If on linux, are you using X11 or Wayland?

Emoji color display is not normal like this pic，how to set this？
![qq20190307-122717](https://user-images.githubusercontent.com/41671631/53932392-5b44f100-40d4-11e9-851d-bd51f540a321.png)

**Comment by chrisduerr** [comment] 2019-03-07 13:54
It seems like it might be taking the text foreground color as color for the emoji? Can you confirm this by printing the emoji with a different color escape (like `echo -e "\e[31m<EMOJI HERE>")?

**Comment by taigacute** [comment] 2019-03-07 14:02
@chrisduerr  hi  this is my color setting 
```
```

**Comment by chrisduerr** [comment] 2019-03-07 14:06
@taigacute Looks like I messed up the Github formatting. You need to add the emoji after the color escape.

**Comment by taigacute** [comment] 2019-03-07 14:09
> @taigacute Looks like I messed up the Github formatting. You need to add the emoji after the color escape.

thanks for your help. you can see this pic
![123](https://user-images.githubusercontent.com/41671631/53962315-b3581380-4125-11e9-851b-57b93f657293.png)

**Comment by chrisduerr** [comment] 2019-03-07 20:04
Closing as a duplicate of https://github.com/jwilm/alacritty/issues/1864.

While originally these issues were a bit different, I think it should be possible to fix it with one common solution.

**Closed by chrisduerr** 2019-03-07 20:04 UTC

**Comment by taigacute** [comment] 2019-03-08 04:16
> 结束为[＃1864](https://github.com/jwilm/alacritty/issues/1864)的副本。
> 
> 虽然最初这些问题有点不同，但我认为应该可以通过一个通用的解决方案来解决它。

yes 。I think these two questions are related. I expect it to be solved

**Comment by taigacute** [comment] 2019-04-06 09:50
@chrisduerr  
Thank you for your work, I have been paying attention to this issue and it has not been resolved. Unable to use emoji causes me not to switch to alacritty

**Comment by koterpillar** [comment] 2020-03-11 04:34
I'd like to point out that when your background color is set to white, this leads to emojis being not visible at all. I've found this issue searching for "emojis don't work in Alacritty".
