### ISSUE TITLE
Extremely slow performance with some Unicode

### ISSUE THREAD

**Issue by jonjensen** [jwilm/alacritty#2858] opened 2019-10-08 17:58 UTC
On Fedora 30 running Xorg with package alacritty-0.3.3-1.fc30.x86_64, I find that some Unicode such as [the official emoji list](https://unicode.org/emoji/charts/emoji-list.html) rendered by w3m in alacritty, are slow.

But the most clear demonstration of a serious problem is simply using cat to dump [this spam mixing Arabic & CJK](https://jon.endpoint.com/tmp/unicode-spam.txt). It takes 100% of one CPU for nearly 2 minutes to render.

Using LXTerminal it renders fine. Alacritty seems to do better than LXTerminal with ASCII, but not here. Thanks in advance for taking a look!

**Comment by nixpulvis** [comment] 2019-10-08 18:38
I can notice this as well, though for me it's closer to 5 seconds. It's also worth noting that after printing the file once, further runs of `cat slow_unicode.txt` are instant, as expected. This means it's probably something to do with loading the glyphs into the atlas (or something like that), and not the rendering itself.

**Comment by chrisduerr** [comment] 2019-10-08 19:05
Duplicate of https://github.com/jwilm/alacritty/issues/511.

**Closed by chrisduerr** 2019-10-08 19:05 UTC
