### ISSUE TITLE
alt_send_esc has no affect in Windows and other missing default keybindings

### ISSUE THREAD

**Issue by CypherZealot** [jwilm/alacritty#2988] opened 2019-11-17 00:06 UTC
## Summary
Configuration option `alt_send_esc` does not have any affect in Windows and the default behavior is that no Alt key-chords work.

Somewhat related, `ctrl+space` should be `^@` and `ctrl+\` should be `\x1c` but they are not mapped.

This behavior is seen for both ConPTY and WinPTY backends.

### How the issue was verified

Use a minimal `alacritty.yml`:
```
enable_experimental_conpty_backend: true
alt_send_esc: true
```

Use `showkey -a` to see the result of the following key-chords:
- `alt+p`
- `alt+2`
- `alt+]`
- `alt-ctrl-f`
- `ctrl+space`
- `ctrl+\`
- `ctrl+b`
- `ctrl+d`

Results:
```
cmd> wsl.exe -e showkey -a

Press any keys - Ctrl-D will terminate this program

         32 0040 0x20
^\       28 0034 0x1c
^B        2 0002 0x02
^D        4 0004 0x04
```

With every other terminal emulator I tested, including the default for cmd.exe, I see the expected result:
```
cmd> wsl.exe -e showkey -a

Press any keys - Ctrl-D will terminate this program

^[p      27 0033 0x1b
        112 0160 0x70
^[2      27 0033 0x1b
         50 0062 0x32
^[]      27 0033 0x1b
         93 0135 0x5d
^[^F     27 0033 0x1b
          6 0006 0x06
^@        0 0000 0x00
^\       28 0034 0x1c
^B        2 0002 0x02
^D        4 0004 0x04
```

Toggling `alt_send_esc` between true and false and restarting Alacritty has no affect.

![image](https://user-images.githubusercontent.com/23530447/69000550-14c8a880-0897-11ea-8339-e8cc05c7c7ab.png)

Toggling `enable_experimental_conpty_backend` between true and false (WinPTY and ConPTY) has no affect. Proof both were tested:
![image](https://user-images.githubusercontent.com/23530447/69000879-83a80080-089b-11ea-8aaf-6eacbc0aa03d.png)

**Which operating system does the issue occur on?**
Windows 10 Pro version 1909

---

There seem to be several open and closed issues that mention this problem, but none of them are specifically addressing why `alt_send_esc` has no affect and a few control sequence mappings are missing in Windows .

https://github.com/jwilm/alacritty/issues/1939
https://github.com/jwilm/alacritty/issues/1774
https://github.com/jwilm/alacritty/issues/2390

**Comment by CypherZealot** [comment] 2019-11-17 00:13
As a workaround I painstakingly mapped all of the Alt key-chords for my 40% US keyboard.

```yaml
# alacritty.yml

key_bindings:
  - { key: A,          mods: Alt,               chars: "\x1ba"    }
  - { key: A,          mods: Alt|Shift,         chars: "\x1bA"    }
  - { key: A,          mods: Alt|Control,       chars: "\x1b\x01" }
  - { key: B,          mods: Alt,               chars: "\x1bb"    }
  - { key: B,          mods: Alt|Shift,         chars: "\x1bB"    }
  - { key: B,          mods: Alt|Control,       chars: "\x1b\x02" }
  - { key: C,          mods: Alt,               chars: "\x1bc"    }
  - { key: C,          mods: Alt|Shift,         chars: "\x1bC"    }
  - { key: C,          mods: Alt|Control,       chars: "\x1b\x03" }
  - { key: D,          mods: Alt,               chars: "\x1bd"    }
  - { key: D,          mods: Alt|Shift,         chars: "\x1bD"    }
  - { key: D,          mods: Alt|Control,       chars: "\x1b\x04" }
  - { key: E,          mods: Alt,               chars: "\x1be"    }
  - { key: E,          mods: Alt|Shift,         chars: "\x1bE"    }
  - { key: E,          mods: Alt|Control,       chars: "\x1b\x05" }
  - { key: F,          mods: Alt,               chars: "\x1bf"    }
  - { key: F,          mods: Alt|Shift,         chars: "\x1bF"    }
  - { key: F,          mods: Alt|Control,       chars: "\x1b\x06" }
  - { key: G,          mods: Alt,               chars: "\x1bg"    }
  - { key: G,          mods: Alt|Shift,         chars: "\x1bG"    }
  - { key: G,          mods: Alt|Control,       chars: "\x1b\x07" }
  - { key: H,          mods: Alt,               chars: "\x1bh"    }
  - { key: H,          mods: Alt|Shift,         chars: "\x1bH"    }
  - { key: H,          mods: Alt|Control,       chars: "\x1b\x08" }
  - { key: I,          mods: Alt,               chars: "\x1bi"    }
  - { key: I,          mods: Alt|Shift,         chars: "\x1bI"    }
  - { key: I,          mods: Alt|Control,       chars: "\x1b\x09" }
  - { key: J,          mods: Alt,               chars: "\x1bj"    }
  - { key: J,          mods: Alt|Shift,         chars: "\x1bJ"    }
  - { key: J,          mods: Alt|Control,       chars: "\x1b\x0a" }
  - { key: K,          mods: Alt,               chars: "\x1bk"    }
  - { key: K,          mods: Alt|Shift,         chars: "\x1bK"    }
  - { key: K,          mods: Alt|Control,       chars: "\x1b\x0b" }
  - { key: L,          mods: Alt,               chars: "\x1bl"    }
  - { key: L,          mods: Alt|Shift,         chars: "\x1bL"    }
  - { key: L,          mods: Alt|Control,       chars: "\x1b\x0c" }
  - { key: M,          mods: Alt,               chars: "\x1bm"    }
  - { key: M,          mods: Alt|Shift,         chars: "\x1bM"    }
  # - { key: M,          mods: Alt|Control,       chars: "\x1b\x0d" }
  - { key: N,          mods: Alt,               chars: "\x1bn"    }
  - { key: N,          mods: Alt|Shift,         chars: "\x1bN"    }
  - { key: N,          mods: Alt|Control,       chars: "\x1b\x0e" }
  - { key: O,          mods: Alt,               chars: "\x1bo"    }
  - { key: O,          mods: Alt|Shift,         chars: "\x1bO"    }
  - { key: O,          mods: Alt|Control,       chars: "\x1b\x0f" }
  - { key: P,          mods: Alt,               chars: "\x1bp"    }
  - { key: P,          mods: Alt|Shift,         chars: "\x1bP"    }
  - { key: P,          mods: Alt|Control,       chars: "\x1b\x10" }
  - { key: Q,          mods: Alt,               chars: "\x1bq"    }
  - { key: Q,          mods: Alt|Shift,         chars: "\x1bQ"    }
  - { key: Q,          mods: Alt|Control,       chars: "\x1b\x11" }
  - { key: R,          mods: Alt,               chars: "\x1br"    }
  - { key: R,          mods: Alt|Shift,         chars: "\x1bR"    }
  - { key: R,          mods: Alt|Control,       chars: "\x1b\x12" }
  - { key: S,          mods: Alt,               chars: "\x1bs"    }
  - { key: S,          mods: Alt|Shift,         chars: "\x1bS"    }
  - { key: S,          mods: Alt|Control,       chars: "\x1b\x13" }
  - { key: T,          mods: Alt,               chars: "\x1bt"    }
  - { key: T,          mods: Alt|Shift,         chars: "\x1bT"    }
  - { key: T,          mods: Alt|Control,       chars: "\x1b\x14" }
  - { key: U,          mods: Alt,               chars: "\x1bu"    }
  - { key: U,          mods: Alt|Shift,         chars: "\x1bU"    }
  - { key: U,          mods: Alt|Control,       chars: "\x1b\x15" }
  - { key: V,          mods: Alt,               chars: "\x1bv"    }
  - { key: V,          mods: Alt|Shift,         chars: "\x1bV"    }
  - { key: V,          mods: Alt|Control,       chars: "\x1b\x16" }
  - { key: W,          mods: Alt,               chars: "\x1bw"    }
  - { key: W,          mods: Alt|Shift,         chars: "\x1bW"    }
  - { key: W,          mods: Alt|Control,       chars: "\x1b\x17" }
  - { key: X,          mods: Alt,               chars: "\x1bx"    }
  - { key: X,          mods: Alt|Shift,         chars: "\x1bX"    }
  - { key: X,          mods: Alt|Control,       chars: "\x1b\x18" }
  - { key: Y,          mods: Alt,               chars: "\x1by"    }
  - { key: Y,          mods: Alt|Shift,         chars: "\x1bY"    }
  - { key: Y,          mods: Alt|Control,       chars: "\x1b\x19" }
  - { key: Z,          mods: Alt,               chars: "\x1bz"    }
  - { key: Z,          mods: Alt|Shift,         chars: "\x1bZ"    }
  # - { key: Z,          mods: Alt|Control,       chars: "\x1b\x1a" }
  - { key: Key1,       mods: Alt,               chars: "\x1b1"    }
  - { key: Key1,       mods: Alt|Shift,         chars: "\x1b!"    }
  - { key: Key2,       mods: Alt,               chars: "\x1b2"    }
  - { key: Key2,       mods: Alt|Shift,         chars: "\x1b@"    }
  - { key: Key3,       mods: Alt,               chars: "\x1b3"    }
  - { key: Key3,       mods: Alt|Shift,         chars: "\x1b#"    }
  - { key: Key4,       mods: Alt,               chars: "\x1b4"    }
  - { key: Key4,       mods: Alt|Shift,         chars: "\x1b$"    }
  - { key: Key5,       mods: Alt,               chars: "\x1b5"    }
  - { key: Key5,       mods: Alt|Shift,         chars: "\x1b%"    }
  - { key: Key6,       mods: Alt,               chars: "\x1b6"    }
  - { key: Key6,       mods: Alt|Shift,         chars: "\x1b^"    }
  # - { key: Key6,       mods: Alt|Control|Shift, chars: "\x1b\x1e" }
  - { key: Key7,       mods: Alt,               chars: "\x1b7"    }
  - { key: Key7,       mods: Alt|Shift,         chars: "\x1b&"    }
  - { key: Key8,       mods: Alt,               chars: "\x1b8"    }
  - { key: Key8,       mods: Alt|Shift,         chars: "\x1b*"    }
  - { key: Key9,       mods: Alt,               chars: "\x1b9"    }
  - { key: Key9,       mods: Alt|Shift,         chars: "\x1b("    }
  - { key: Key0,       mods: Alt,               chars: "\x1b0"    }
  - { key: Key0,       mods: Alt|Shift,         chars: "\x1b)"    }
  - { key: Minus,      mods: Alt,               chars: "\x1b-"    }
  - { key: Minus,      mods: Alt|Shift,         chars: "\x1b_"    }
  - { key: Minus,      mods: Alt|Control,       chars: "\x1b\x1f" }
  - { key: Equals,     mods: Alt,               chars: "\x1b="    }
  - { key: Equals,     mods: Alt|Shift,         chars: "\x1b+"    }
  - { key: LBracket,   mods: Alt,               chars: "\x1b["    }
  - { key: LBracket,   mods: Alt|Shift,         chars: "\x1b{"    }
  # - { key: LBracket,   mods: Alt|Control,       chars: "\x1b\x1b" } # unsure
  - { key: RBracket,   mods: Alt,               chars: "\x1b]"    }
  - { key: RBracket,   mods: Alt|Shift,         chars: "\x1b}"    }
  # - { key: RBracket,   mods: Alt|Control,       chars: "\x1b\x1d" } # unsure
  - { key: Backslash,  mods: Alt,               chars: "\x1b\\"   }
  # - { key: Backslash,  mods: Alt|Control,       chars: "\x1b\x1c" } # unsure
  - { key: 39,         mods: Alt,               chars: "\x1b;"    }
  - { key: 39,         mods: Alt|Shift,         chars: "\x1b:"    }
  - { key: Apostrophe, mods: Alt,               chars: "\x1b'"    }
  - { key: Apostrophe, mods: Alt|Shift,         chars: "\x1b\""   }
  - { key: Comma,      mods: Alt,               chars: "\x1b,"    }
  - { key: Comma,      mods: Alt|Shift,         chars: "\x1b<"    }
  - { key: Period,     mods: Alt,               chars: "\x1b."    }
  - { key: Period,     mods: Alt|Shift,         chars: "\x1b>"    }
  - { key: Slash,      mods: Alt,               chars: "\x1b/"    }
  - { key: Slash,      mods: Alt|Shift,         chars: "\x1b?"    }
  - { key: Grave,      mods: Alt,               chars: "\x1b`"    }
  - { key: Grave,      mods: Alt|Shift,         chars: "\x1b~"    }
  - { key: Space,      mods: Alt,               chars: "\x1b\x20" }

  - { key: Space, mods: Control, chars: "\x00" }
  - { key: Slash, mods: Control, chars: "\x1f" }
```

**Comment by chrisduerr** [comment] 2019-11-17 00:16
The config option `alt_send_esc` is used to disable the sending of escapes when alt is pressed, not to enable it. It's also enabled by default.

So the issue is not the config option not working, but instead this is a duplicate of #1939.

**Closed by chrisduerr** 2019-11-17 00:16 UTC

**Comment by CypherZealot** [comment] 2019-11-17 01:13
How is the issue not that the config option `alt_send_esc` is not working?

From the description in the [default config](https://github.com/jwilm/alacritty/blob/495a6f3526f5127c342d67980d0335f1ed4e235b/alacritty.yml#L351):
```
# Send ESC (\x1b) before characters when alt is pressed.
#alt_send_esc: true
```
Is it, "if `alt_send_esc` is true and `Alt` is held append, `\x1b` before the other characters in a key-chord"?

I do not know rust, but it seems this should be adding `\x1b` when `alt_send_esc` is true.
https://github.com/jwilm/alacritty/blob/495a6f3526f5127c342d67980d0335f1ed4e235b/alacritty/src/input.rs#L638
Either way, true or false, it does not do anything.

**Comment by chrisduerr** [comment] 2019-11-17 01:39
The `alt_send_esc` option is working perfectly fine, that is not the issue. Feel free to verify that yourself, however that would just be a waste of time.
