### ISSUE TITLE
Line missing in NVIM

### ISSUE THREAD

**Issue by roehst** [jwilm/alacritty#627] opened 2017-06-19 23:27 UTC
![image](https://user-images.githubusercontent.com/21047691/27310019-b0600e84-552d-11e7-98b8-b1ef22d52f85.png)

I use alacritty + tmux + nvim.

When this happens I have to quit nvim and get back.

Don't know how to reproduce, but it happens fairly often!

**Comment by Aaron1011** [comment] 2017-06-20 07:06
Is that 'missing line' affected by scrolling up/down in vim?

**Comment by roehst** [comment] 2017-06-23 14:52
Not the missing line per se. After the first glitch happens, scrolling and typing only make everything more buggy:

29 is really a blank line. 50 is also buggy. 57 is repeated.

![image](https://user-images.githubusercontent.com/21047691/27487506-4dcb2d46-580a-11e7-88e5-76126ac27580.png)

**Comment by roehst** [comment] 2017-06-23 14:52
BTW, i would never get back to other terminals. Alacritty is wicked fast.

**Comment by rafi** [comment] 2017-06-25 08:30
It happens to me a lot, when it does, I run `:redraw!` and n/vim redraws screen back to normal. It's hard to reproduce..

**Comment by DarkDefender** [comment] 2017-06-25 09:31
@rafi Does it happen with just vim (not nvim)? There is currently a lot of work going on tweaking the terminal UI in nvim. However that is not to say alacritty is not doing something wrong. See #598  for example

**Comment by roehst** [comment] 2017-06-25 20:43
@DarkDefender I get with NVIM.

**Comment by lynndylanhurley** [comment] 2017-06-25 23:44
I'm seeing this as well with nvim. `:redraw!` does set the screen to normal.

Not seeing it in iTerm2 if that helps.

**Comment by maximbaz** [comment] 2017-06-26 08:55
Do you guys use the latest tmux version (2.5, I believe)? And does it repro without tmux?

I experience the same bug in htop, which unfortunately doesn't have `:redraw!` command. Reproduces only in tmux session, by the way.

**Comment by DarkDefender** [comment] 2017-06-26 11:39
@maximbaz you can force redraw in many terminal applications (including htop) with ctrl+L

**Comment by maximbaz** [comment] 2017-06-26 11:49
Thank you for the tip, works indeed 🙂

**Comment by asilvadesigns** [comment] 2017-06-26 12:38
@maximbaz I've only noticed it using Tmux. Especially common when editing python files, painful experience. I've screwed up code a lot because I don't notice the glitch since my terminal background color is the same as my Neovim background.

**Comment by jwilm** [comment] 2017-06-26 15:14
@asilvadesigns what are you using for `TERM` within tmux?

**Comment by asilvadesigns** [comment] 2017-06-26 15:21
@jwilm a custom one in order to use Operator Mono with italics... so that's probably not good... these are the contents of said term:
```
xterm-256color-italic|xterm with 256 colors and italic,
  sitm=\E[3m, ritm=\E[23m,
  use=xterm-256color,
```

**Comment by DarkDefender** [comment] 2017-06-26 15:26
Try setting TERM to "tmux-256color" instead and see if that helps.

**Comment by jwilm** [comment] 2017-06-26 15:57
@asilvadesigns `xterm-256color` as a `TERM` value is almost certainly causing the issue you're seeing. For something that works out of the box, you could try using `screen-256color`, but you'll probably want to install a tmux terminfo file.

**Comment by rafi** [comment] 2017-06-26 18:53
I can confirm this happens in regular Vim _and_ Neovim.
I'm able to randomly reproduce it editing a file with many, long, lines. (e.g. my bash_history with >14k lines)

All these distorted fragments are fixed when I run `:redraw!` either in Vim or Neovim.

### Screenshots

_With_ tmux, `TERM=tmux-256color`, Neovim v0.2.1-368-gca385db4 (_Notes:_ Empty false line between 527-528, entire statusline has disappeared, all lines distored and mixed together.)
![image](https://user-images.githubusercontent.com/147918/27554935-c487e9e6-5ab8-11e7-8884-f2ea4412fae1.png)

_With_ tmux, `TERM=tmux-256color`, Vim 8 (_Notes:_ False line between 530-531, only a small part of the statusline has disappeared, the left side, and all lines distored and mixed together.)
![image](https://user-images.githubusercontent.com/147918/27555136-7b2d8e1c-5ab9-11e7-9786-adc841daacd9.png)

_Without_ tmux, `TERM=xterm-256color`, both Vim+Neovim  (_Notes:_ Background has a different tint once I start scroll screen)
![image](https://user-images.githubusercontent.com/147918/27555059-352289f4-5ab9-11e7-9d52-8a7b023f5e65.png)

**Comment by lynndylanhurley** [comment] 2017-06-27 04:16
Here's a screencap of what I'm seeing:

![alacritty-redraw-issue](https://user-images.githubusercontent.com/468037/27570617-1a869980-5ac5-11e7-88b2-d13bf7f50a29.gif)

Scrolling in one pane trashes the adjacent pane and adds incorrect bg colors to the focused pane. Re-drawing the screen sets it back to normal.

**Comment by jwilm** [comment] 2017-06-27 05:47
@lynndylanhurley could you share the alacritty log from when you ran that? It kinda looks like nvim is trying to use DECSLRM which we don't yet support.

**Comment by lynndylanhurley** [comment] 2017-06-27 15:24
@jwilm - sure, where are the logs on macOS?

**Comment by jwilm** [comment] 2017-06-27 15:32
@lynndylanhurley referring to console output rather than actual logs. You can run alacritty from the command line to get the output.

**Comment by lynndylanhurley** [comment] 2017-06-27 15:54
@jwilm so this is weird - the problem only happens when I run alacritty from `/Applications/Alacritty.app`. When I start it with `./target/release/alacritty` then I no longer see the issue.

**Comment by NickeZ** [comment] 2017-06-27 16:00
I also have this issue, but only sometimes... I use Linux

**Comment by asilvadesigns** [comment] 2017-06-28 15:54
@jwilm @DarkDefender issue only occurs when using `dd` and then undoing the deleted line in nvim in tmux, and still persists with different TERM value.

**Comment by NickeZ** [comment] 2017-07-07 09:40
Here is the output when I have this issue. I open vim with two windows split vertically. Both windows have more text than fits the window. And then I scroll one window. For every line I scroll. One line dissappears in the non-scrolled window.

```
glutin event: Awakened
glutin event: Awakened
glutin event: Awakened
glutin event: Awakened
glutin event: Focused(true)
glutin event: Awakened
glutin event: Awakened
glutin event: Awakened
glutin event: Awakened
glutin event: KeyboardInput(Released, 64, Some(LAlt), ALT, None)
glutin event: KeyboardInput(Pressed, 116, Some(Down), , None)
glutin event: Awakened
glutin event: Awakened
[Unhandled CSI] action='h', args=[69], intermediates=[63]
[Unhandled CSI] action='l', args=[69], intermediates=[63]
glutin event: Awakened
glutin event: Awakened
glutin event: KeyboardInput(Released, 116, Some(Down), , None)
glutin event: Awakened
glutin event: Awakened
glutin event: Awakened
glutin event: Awakened
glutin event: Awakened
```

**Comment by NickeZ** [comment] 2017-07-07 10:19
@jwilm Looks like you are right that nvim is trying to use margins. I found the following in "XTerm Control Sequences" documentation:

```
CSI ? Pm h
...
            Ps = 6 9  -> Enable left and right margin mode (DECLRMM),
```

The question is. How do we disable it? Through terminfo somehow?

**Comment by DarkDefender** [comment] 2017-07-07 10:36
@NickeZ I think that is a problem with neovim that just got fixed ~12h ago. If you use the latest neovim master do you still have the problem?

However it seems like the neovim fix broke true color. So now only 256 color mode works in neovim :/

**Comment by NickeZ** [comment] 2017-07-07 11:21
Oh, the joy of running bleeding edge.. I will have to wait until the PPA for neovim is recompiled. Thanks for the heads up @DarkDefender

**Comment by lynndylanhurley** [comment] 2017-07-07 16:30
Just pulled down the latest nvim (773ea9dbdccd9252b0901e64ccb1c4fef6ca7cb9), this issue has been resolved for me.

**Comment by jwilm** [comment] 2017-07-07 17:12
cc #160

**Comment by asymmetric** [comment] 2017-07-18 13:44
In my case, the fix [in this comment](https://github.com/jwilm/alacritty/issues/660#issuecomment-315239034) also helps with this issue.

**Comment by kronos29296** [comment] 2017-07-20 12:14
I tried to use neovim 0.2.1 dev release with alacritty in tmux and The entire background becomes black except the text. Every time I scroll down or up it happens while switching between panes makes it go away.

**Comment by asivitz** [comment] 2017-07-21 01:27
Not sure if more reports are needed, but nvim (either 0.2 or HEAD) + tmux + alacritty HEAD is very buggy for me. One way to reproduce is just to scroll up or down using j/k. The linked workaround in asymmetric's comment does not work for me.

**Comment by lambdalisue** [comment] 2017-07-21 03:17
I'm using macOS + tmux (HEAD) + alacritty (HEAD) + neovim (2.0) with lazyredraw, ttyfast, and the workaround.

I don't feel any performance issue except when nvim shows two vertically splitted buffers, it gets bit slow (it should be fixed #160 right?)

Btw, it seems nvim HEAD has issue on tmux for now so alacritty shoud be tested with 0.2 at least for now.
https://github.com/neovim/neovim/issues/7041

**Comment by jwilm** [comment] 2017-08-22 18:26
Is anyone still seeing this issue? I _believe_ it's been fixed.

**Comment by asilvadesigns** [comment] 2017-08-22 18:38
@jwilm not seeing it anymore

**Comment by maximbaz** [comment] 2017-08-22 18:54
Hey hey, my issue with `htop` is also fixed! Huge thanks @jwilm and @hiciu!

**Comment by jwilm** [comment] 2017-08-22 19:28
Thanks for testing @maximbaz and @asilvadesigns.

@roehst, are you still using Alacritty? Would like to make sure this patch works for you if so.

**Comment by Libbum** [comment] 2017-09-17 10:51
I can confirm that updating alacritty to HEAD (neovim 2.0, tmux 2.5) has resolved the bugs I've observed related to this issue.

**Comment by jwilm** [comment] 2017-09-17 20:36
Thanks for the additional feedback @Libbum.

**Closed by jwilm** 2017-09-17 20:36 UTC
Labels: bug, S - terminal
