### ISSUE TITLE
`swap_lines` breaks with `cat /dev/urandom`

### ISSUE THREAD

**Issue by pmatos** [jwilm/alacritty#258] opened 2017-01-09 14:16 UTC
While trying to reproduce #256 found:

```
thread 'pty reader' panicked at 'swap_lines dst out of bounds; len=114, dst=114', src/grid.rs:163
stack backtrace:
   1:     0x564d918c73ca - std::sys::imp::backtrace::tracing::imp::write::h9c41d2f69e5caabf
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x564d918c6851 - std::panicking::default_hook::{{closure}}::h1f61f3c769fffe7a
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x564d918c5a17 - std::panicking::rust_panic_with_hook::hffbc74969c7b5d87
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   4:     0x564d918c5571 - std::panicking::begin_panic::h3bbdbb2a23440035
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   5:     0x564d918c54e9 - std::panicking::begin_panic_fmt::h34f5b320b0f94559
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
   6:     0x564d917b5781 - alacritty::term::Term::scroll_up_relative::h62df3f49e0598206
                        at /home/pmatos/Projects/alacritty/<panic macros>:8
                        at /home/pmatos/Projects/alacritty/src/grid.rs:138
                        at /home/pmatos/Projects/alacritty/src/term/mod.rs:615
   7:     0x564d9179ab10 - vte::Parser::perform_action::hdc022bd1ccfcbadf
                        at /home/pmatos/Projects/alacritty/src/term/mod.rs:839
                        at /home/pmatos/Projects/alacritty/src/ansi.rs:568
                        at /home/pmatos/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:205
   8:     0x564d917ad6a2 - <alacritty::event_loop::EventLoop<Io>>::spawn::{{closure}}::h611a00c07d8ab92f
                        at /home/pmatos/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:158
                        at /home/pmatos/.cargo/registry/src/github.com-1ecc6299db9ec823/vte-0.1.2/src/lib.rs:137
                        at /home/pmatos/Projects/alacritty/src/ansi.rs:85
                        at /home/pmatos/Projects/alacritty/src/event_loop.rs:211
                        at /home/pmatos/Projects/alacritty/src/event_loop.rs:308
   9:     0x564d917aabf4 - <F as alloc::boxed::FnBox<A>>::call_box::h789415a8ffb21203
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:296
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:460
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/thread/mod.rs:357
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:605
  10:     0x564d918d3748 - std::sys::imp::thread::Thread::new::thread_start::h76badbf9b0ecaf58
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/liballoc/boxed.rs:615
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys_common/thread.rs:21
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/thread.rs:84
  11:     0x7f04760fa6c9 - start_thread
  12:     0x7f0475c1df7e - clone
  13:                0x0 - <unknown>
child finished with error '1'
```

This is at commit `2fa271`.

**Comment by okuuva** [comment] 2017-01-09 14:51
Possible duplicate of #63.

**Comment by jwilm** [comment] 2017-01-09 17:15
Yep this is a duplicate; tracking in #63.

**Closed by jwilm** 2017-01-09 17:15 UTC
