### ISSUE TITLE
Font/text rendering failing

### ISSUE THREAD

**Issue by derpmarine168** [jwilm/alacritty#1918] opened 2018-12-21 10:46 UTC
> Which operating system does the issue occur on?

Windows 10 Home
( Intel Integrated Graphics )

after installing with both scoop and directly downloading executables, I'm getting a weird error/bug with font rendering.

![Direct executables](https://user-images.githubusercontent.com/28905212/50338844-912efc00-050d-11e9-89a8-dec1e9083915.png)
when copying the text, it works fine, so it's most likely a rendering issue. I can also `cd` around and use `dir`, etc.
however, when running large amounts of text through it, it's being *reeaaallllyyyyy* slow.
`npm i hacker-terminal -g` and then `hacker-terminal` runs at about 0mph. 
this leads me to believe it's GPU related.

**Comment by derpmarine168** [comment] 2018-12-21 10:47
ps - the actual text is the usual 
```
Microsoft Windows [Version 10.0.17134.471]
(c) 2018 Microsoft Corporation. All rights reserved.

C:\Users\admin>
```

**Comment by chrisduerr** [comment] 2018-12-21 11:51
This is a duplicate of https://github.com/jwilm/alacritty/issues/1763, though with a picture it would probably be easier to tell.

Going to use your picture to update the issue, hopefully that's fine with you.

**Closed by chrisduerr** 2018-12-21 11:51 UTC
