### ISSUE TITLE
Windows + alacritty + vim has weird behavior with the <esc> key

### ISSUE THREAD

**Issue by ubsan** [jwilm/alacritty#1914] opened 2018-12-19 21:10 UTC
Basically, whenever I try to exit out of insert-mode, I have to wait for the escape key to "catch", about a second - otherwise, I get a modified character and continue on inserting. For example, if I type <esc>j, I get `ê`.

**Comment by chrisduerr** [comment] 2018-12-19 22:06
I wasn't able to notice something like that when running Alacritty on Windows myself. Repro might be interesting if anyone else also has the issue.

Would be interesting to see if the ESC alternatives (I believe it was Ctrl+]) create the same problem?

**Comment by zacps** [comment] 2018-12-20 02:20
Duplicate of https://github.com/jwilm/alacritty/issues/1680

**Closed by zacps** 2018-12-20 02:20 UTC
Labels: A - needs repro, H - windows, S - input

**Comment by ubsan** [comment] 2018-12-20 09:38
Ah, sorry @zacps, I missed it
