### ISSUE TITLE
(Some?) key bindings don't follow keyboard layout on OSX

### ISSUE THREAD

**Issue by pikajude** [jwilm/alacritty#332] opened 2017-01-20 20:38 UTC
I use dvorak. From my config file:

```
key_bindings:
  - { key: V,        mods: Command, action: Paste                        }
```

but to actually paste, I have to Cmd+K, as Dvorak K is in the same place as QWERTY V.

**Comment by okuuva** [comment] 2017-01-21 09:00
Duplicate of #61.

**Comment by jwilm** [comment] 2017-01-21 20:21
Thanks @okuuva

**Closed by jwilm** 2017-01-21 20:21 UTC
