### ISSUE TITLE
On MacOS does not recognize keyboard layout for Key Combos like copy/paste 

### ISSUE THREAD

**Issue by cyphactor** [jwilm/alacritty#322] opened 2017-01-17 04:12 UTC
For some reason on MacOS it doesn't recognize the system configured keyboard layout (for me Dvorak) with the key commands.

The normal terminal interaction works properly. It is just the key commands that seem to ignore the keyboard layout configured in the system settings.

**Comment by okuuva** [comment] 2017-01-17 08:35
I can confirm this. I'm using a custom Dvorak layout and all commands in `key_bindings` (copy, paste etc.) still behave like I have QWERTY layout enabled. It doesn't matter if the key binding has modifiers or not and the problem is the same on the default US Dvorak layout as well.

I'm running macOS Sierra 10.12.2 (16C67) on a MacBook Pro (Retina, 13-inch, Early 2015) and I'm at a2cd4b647c1058c3012348774481ade30dddd601.

**Comment by cyphactor** [comment] 2017-01-17 10:51
I am running macOS Sierra 10.12.2 on a MacBook Pro 15" Retina and am on a2cd4b6 and I have the problem.

**Comment by okuuva** [comment] 2017-01-17 19:34
Possibly related to / duplicate of #61.

**Closed** 2017-01-17 19:44 UTC
Labels: duplicate
