### ISSUE TITLE
"-e command" cli option

### ISSUE THREAD

**Issue by kurnevsky** [jwilm/alacritty#341] opened 2017-01-22 09:58 UTC
It would be convenient to have this option for launching console apps (tmux, mc, etc) instead of shell.

**Comment by Elronnd** [comment] 2017-01-22 17:51
Duplicate of #176.

**Comment by Elronnd** [comment] 2017-01-22 17:52
Duplicate of #176.  It should probably get more attention, though, since it would probably be pretty easy.

**Comment by jwilm** [comment] 2017-01-22 21:21
Thanks @Elronnd. Closing as duplicate; please subscribe to the original issue for updates.

**Closed by jwilm** 2017-01-22 21:21 UTC
Labels: duplicate
