### ISSUE TITLE
Alacritty panic at start when en_DK locale is used

### ISSUE THREAD

**Issue by mmerfort** [jwilm/alacritty#2553] opened 2019-06-17 11:21 UTC
I am using alacritty 0.3.2 on Arch Linux with xorg.

I use the en_DK locale on my machine which causes alacritty to panic on startup:
```
 m8769@laptop4023  ~  locale
LANG=en_DK.utf8
LC_CTYPE="en_DK.utf8"
LC_NUMERIC="en_DK.utf8"
LC_TIME="en_DK.utf8"
LC_COLLATE="en_DK.utf8"
LC_MONETARY="en_DK.utf8"
LC_MESSAGES="en_DK.utf8"
LC_PAPER="en_DK.utf8"
LC_NAME="en_DK.utf8"
LC_ADDRESS="en_DK.utf8"
LC_TELEPHONE="en_DK.utf8"
LC_MEASUREMENT="en_DK.utf8"
LC_IDENTIFICATION="en_DK.utf8"
LC_ALL=
 m8769@laptop4023  ~  alacritty 
thread 'main' panicked at 'Failed to open input method: PotentialInputMethods {
    xmodifiers: None,
    fallbacks: [
        PotentialInputMethod {
            name: "@im=local",
            successful: Some(
                false
            )
        },
        PotentialInputMethod {
            name: "@im=",
            successful: Some(
                false
            )
        }
    ],
    _xim_servers: Err(
        GetPropertyError(
            TypeMismatch(
                0
            )
        )
    )
}', /build/.cargo/git/checkouts/winit-081229dbb0c89e9b/57680d2/src/platform/linux/x11/mod.rs:92:17
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
 ✘ m8769@laptop4023  ~  LANG=en_US.UTF-8
 m8769@laptop4023  ~  alacritty
# Everything is working
```

**Comment by chrisduerr** [comment] 2019-06-17 18:12
Do you have any kind of IME setup?

**Comment by mmerfort** [comment] 2019-06-18 07:20
I updated to alacritty 0.3.3 on the 17th but the problem still persists. Should I compile the most recent version from git?

I am also not using any IME.

**Comment by chrisduerr** [comment] 2019-06-18 15:09
> Should I compile the most recent version from git?

If you've tested 0.3.3 from the Archlinux repos, please try recompiling the most recent version from git. The Archlinux repo downgrades the winit dependency to fix current transparency issues.

**Comment by mmerfort** [comment] 2019-06-18 16:39
I compiled the current version from git but it still fails:
```
 m8769@laptop4023  ~  alacritty --version                 
alacritty 0.3.3 (a39459ec)
 m8769@laptop4023  ~  RUST_BACKTRACE=1 alacritty
thread 'main' panicked at 'Failed to open input method: PotentialInputMethods {
    xmodifiers: None,
    fallbacks: [
        PotentialInputMethod {
            name: "@im=local",
            successful: Some(
                false,
            ),
        },
        PotentialInputMethod {
            name: "@im=",
            successful: Some(
                false,
            ),
        },
    ],
    _xim_servers: Err(
        GetPropertyError(
            TypeMismatch(
                0,
            ),
        ),
    ),
}', /home/m8769/.cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.19.1/src/platform/linux/x11/mod.rs:92:17
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: __libc_start_main
  11: <unknown>
```

**Comment by chrisduerr** [comment] 2019-06-18 20:39
Can you try to test the latest winit by running the following command? This should hopefully show if this is Alacritty's fault or not.

```
git clone https://github.com/rust-windowing/winit && cd winit && cargo run --example winit
```

**Comment by mmerfort** [comment] 2019-06-19 04:48
This seems to confirm that it is a winit problem:
``` ✘ m8769@laptop4023  ~/S/R/winit   master  cargo run --example window                              
  Downloaded parking_lot v0.8.0                                                                        
  Downloaded lock_api v0.2.0                                                                           
  Downloaded parking_lot_core v0.5.0                                                                   
  Downloaded scopeguard v1.0.0                                                                         
  Downloaded calloop v0.4.4                                                                            
   Compiling proc-macro2 v0.4.30                                                                       
   Compiling cc v1.0.37                                                                                
   Compiling libc v0.2.58                                                                              
   Compiling unicode-xid v0.1.0                                                                        
   Compiling arrayvec v0.4.10                                                                          
   Compiling bitflags v1.1.0                                                                           
   Compiling cfg-if v0.1.9                                                                             
   Compiling autocfg v0.1.4                                                                            
   Compiling slab v0.4.2                                                                               
   Compiling semver-parser v0.7.0                                                                      
   Compiling lazy_static v1.3.0                                                                        
   Compiling byteorder v1.3.2                                                                          
   Compiling nodrop v0.1.13                                                                            
   Compiling nix v0.14.1                                                                               
   Compiling xml-rs v0.8.0                                                                             
   Compiling lazycell v1.2.1                                                                           
   Compiling void v1.0.2                                                                               
   Compiling scopeguard v0.3.3                                                                         
   Compiling rand_core v0.4.0                                                                          
   Compiling memoffset v0.2.1                                                                          
   Compiling syn v0.15.36                                                                              
   Compiling rayon-core v1.5.0                                                                         
   Compiling memchr v2.2.0                                                                             
   Compiling pkg-config v0.3.14                                                                        
   Compiling num-derive v0.2.5                                                                         
   Compiling downcast-rs v1.0.4                                                                        
   Compiling same-file v1.0.4                                                                          
   Compiling smallvec v0.6.10                                                                          
   Compiling xdg v2.2.0                                                                                
   Compiling scopeguard v1.0.0                                                                         
   Compiling either v1.5.2                                                                             
   Compiling regex v1.1.7                                                                              
   Compiling adler32 v1.0.3                                                                            
   Compiling ucd-util v0.1.3                                                                           
   Compiling color_quant v1.0.1                                                                        
   Compiling lzw v0.10.0                                                                               
   Compiling utf8-ranges v1.0.3                                                                        
   Compiling quick-error v1.2.2                                                                        
   Compiling scoped_threadpool v0.1.9                                                                  
   Compiling percent-encoding v1.0.1                                                                   
   Compiling termcolor v1.0.5                                                                          
   Compiling log v0.4.6                                                                                
   Compiling num-traits v0.2.8                     
   Compiling rand_chacha v0.1.1                                              
   Compiling rand_pcg v0.1.2              
   Compiling num-integer v0.1.41                                                                       
   Compiling rand v0.6.5                                                                                                                                   
   Compiling num-iter v0.1.39                      
   Compiling num-rational v0.2.2                   
   Compiling libloading v0.5.1                                               
   Compiling crossbeam-utils v0.6.5
   Compiling thread_local v0.3.6                                             
   Compiling semver v0.9.0                      
   Compiling rand_core v0.3.1                                                
   Compiling rand_jitter v0.1.4                                                                                                                            
   Compiling walkdir v2.2.8                                                                            
   Compiling lock_api v0.2.0                                                 
   Compiling x11-dl v2.18.3                                                  
   Compiling inflate v0.4.5 
   Compiling regex-syntax v0.6.7                                             
   Compiling humantime v1.2.0                      
   Compiling gif v0.10.2                                                                               
   Compiling rand_isaac v0.1.1                                                                         
   Compiling rand_xorshift v0.1.1                                                                      
   Compiling rand_hc v0.1.0                                                  
   Compiling rustc_version v0.2.3                                                                      
   Compiling crossbeam-queue v0.1.2                                          
   Compiling iovec v0.1.2                                                    
   Compiling net2 v0.2.33                          
   Compiling rand_os v0.1.3                                                                            
   Compiling num_cpus v1.10.1                                                                                                                              
   Compiling memmap v0.7.0                                                   
   Compiling atty v0.2.11                                                    
   Compiling crossbeam-epoch v0.7.1                                                                    
   Compiling quote v0.6.12                                                   
   Compiling stb_truetype v0.2.6                                             
   Compiling deflate v0.7.19                    
   Compiling aho-corasick v0.7.3                                                                                                                           
   Compiling parking_lot_core v0.5.0                                         
   Compiling parking_lot v0.8.0                                                                                                                            
   Compiling mio v0.6.19                           
   Compiling wayland-scanner v0.23.5                                                                   
   Compiling crossbeam-deque v0.6.3                                          
   Compiling dlib v0.4.1                                                     
   Compiling ordered-float v1.0.2                                            
   Compiling approx v0.3.2                                                   
   Compiling line_drawing v0.7.0            
   Compiling mio-extras v2.0.5                                               
   Compiling wayland-sys v0.23.5                                             
   Compiling wayland-client v0.23.5                                                                    
   Compiling wayland-protocols v0.23.5                                       
   Compiling rusttype v0.7.7            
   Compiling calloop v0.4.4            
   Compiling wayland-commons v0.23.5                                         
   Compiling rayon v1.1.0                          
   Compiling env_logger v0.5.13                                              
   Compiling andrew v0.2.1                                                                             
   Compiling png v0.14.1                                                                               
   Compiling derivative v1.0.2                                                                         
   Compiling jpeg-decoder v0.1.15            
   Compiling tiff v0.2.2                           
   Compiling image v0.21.2                         
   Compiling smithay-client-toolkit v0.6.2                                   
   Compiling winit v0.19.1 (/home/m8769/Source/Rust/winit)                                                                                                 
warning: unused `#[macro_use]` import                                                                                                                      
  --> src/lib.rs:88:1                                                                                                                                      
   |                                               
88 | #[macro_use]                                  
   | ^^^^^^^^^^^^                                  
   |                                               
   = note: #[warn(unused_imports)] on by default   
                                                   
warning: variable does not need to be mutable      
  --> src/platform_impl/linux/wayland/pointer.rs:18:9    
   |                                               
18 |     let mut mouse_focus = None;    
   |         ----^^^^^^^^^^^    
   |         |                                     
   |         help: remove this `mut`               
   |                                               
   = note: #[warn(unused_mut)] on by default                                                           
                                                   
warning: variable does not need to be mutable                                                          
  --> src/platform_impl/linux/wayland/pointer.rs:19:9                                                  
   |                                                                                                   
19 |     let mut axis_buffer = None;
   |         ----^^^^^^^^^^^  
   |         |                                     
   |         help: remove this `mut`               
                                                   
warning: variable does not need to be mutable      
  --> src/platform_impl/linux/wayland/pointer.rs:20:9                                                                                                      
   |                                               
20 |     let mut axis_discrete_buffer = None;
   |         ----^^^^^^^^^^^^^^^^^^^^              
   |         |                                     
   |         help: remove this `mut`               
                                                   
warning: variable does not need to be mutable      
  --> src/platform_impl/linux/wayland/pointer.rs:21:9                                                                                                      
   |                                               
21 |     let mut axis_state = TouchPhase::Ended;   
   |         ----^^^^^^^^^^                        
   |         |                                     
   |         help: remove this `mut`               
                                                   
warning: variable does not need to be mutable                                                          
   --> src/platform_impl/linux/wayland/keyboard.rs:115:17                                 
    |                                                                                                  
115 |             let mut target = None;                                     
    |                 ----^^^^^^                                             
    |                 |                                                      
    |                 help: remove this `mut`                                

    Finished dev [unoptimized + debuginfo] target(s) in 2m 04s                                                                                             
     Running `target/debug/examples/window`                                  
thread 'main' panicked at 'Failed to open input method: PotentialInputMethods {                                                                            
    xmodifiers: None,                                                        
    fallbacks: [                                                             
        PotentialInputMethod {                                               
            name: "@im=local",                                               
            successful: Some(                                                
                false,                                                       
            ),                                                               
        },                                                                   
        PotentialInputMethod {                                               
            name: "@im=",                                                    
            successful: Some(                                                
                false,                                                       
            ),                                                               
        },                                                                   
    ],                                                                       
    _xim_servers: Err(                                                       
        GetPropertyError(                                                    
            TypeMismatch(                                                    
                0,                                                           
            ),                                                               
        ),                                                                   
    ),                                                                       
}', src/platform_impl/linux/x11/mod.rs:80:17                                 
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
 ```

**Comment by chrisduerr** [comment] 2019-06-19 18:39
If you're willing to open the winit issue and link it here, that would be much appreciated.

**Comment by dimamedvedev** [comment] 2019-08-21 10:01
Linking winit issue https://github.com/rust-windowing/winit/issues/636

**Comment by chrisduerr** [comment] 2019-11-17 22:36
Duplicate of https://github.com/jwilm/alacritty/issues/1574.

**Closed by chrisduerr** 2019-11-17 22:36 UTC
Labels: A - deps, B - bug, B - crash, S - winit/glutin
