### ISSUE TITLE
Can't bind Ctrl-> and Ctrl-<

### ISSUE THREAD

**Issue by sambrightman** [jwilm/alacritty#2125] opened 2019-02-19 15:13 UTC
Which operating system does the issue occur on?

Linux

If on linux, are you using X11 or Wayland?

X11

I try to bind Ctrl-> and Ctrl-< like this:

```
  - { key: Period,        mods: Control|Shift,     chars: "\e[emacs-C->"     }
  - { key: Comma,         mods: Control|Shift,     chars: "\e[emacs-C-<"     }
```

I only get the plain "<" or ">" output when pressing them. Other bindings work fine, including Ctrl-. and Ctrl-, (removing these does not fix Ctrl-> and Ctrl-<).

Here is the `--print-events` output:

```
[2019-02-19 14:57] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(155189253))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 28, state: Released, virtual_keycode: Some(Return), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
[2019-02-19 14:57] [INFO] glutin event: Awakened
[2019-02-19 14:57] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(13))), event: Key(KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
[2019-02-19 14:57] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(155189253))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
[2019-02-19 14:57] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(13))), event: Key(KeyboardInput { scancode: 52, state: Pressed, virtual_keycode: Some(Period), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
[2019-02-19 14:57] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(155189253))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 52, state: Pressed, virtual_keycode: Some(Period), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
[2019-02-19 14:57] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(155189253))), event: ReceivedCharacter('.') }
[2019-02-19 14:57] [INFO] glutin event: Awakened
[2019-02-19 14:57] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(13))), event: Key(KeyboardInput { scancode: 52, state: Released, virtual_keycode: Some(Period), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
[2019-02-19 14:57] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(155189253))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 52, state: Released, virtual_keycode: Some(Period), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
[2019-02-19 14:57] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(13))), event: Key(KeyboardInput { scancode: 29, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
[2019-02-19 14:57] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(155189253))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
```
```
[2019-02-19 14:57] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(13))), event: Key(KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
[2019-02-19 14:57] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(155189253))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
[2019-02-19 14:57] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(13))), event: Key(KeyboardInput { scancode: 42, state: Pressed, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
[2019-02-19 14:57] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(155189253))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 42, state: Pressed, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
[2019-02-19 14:57] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(13))), event: Key(KeyboardInput { scancode: 52, state: Pressed, virtual_keycode: Some(Period), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
[2019-02-19 14:57] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(155189253))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 52, state: Pressed, virtual_keycode: None, modifiers: ModifiersState { shift: true, ctrl: true, alt: false, logo: false } } } }
[2019-02-19 14:57] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(155189253))), event: ReceivedCharacter('>') }
[2019-02-19 14:57] [INFO] glutin event: Awakened
[2019-02-19 14:57] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(13))), event: Key(KeyboardInput { scancode: 52, state: Released, virtual_keycode: Some(Period), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
[2019-02-19 14:57] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(155189253))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 52, state: Released, virtual_keycode: None, modifiers: ModifiersState { shift: true, ctrl: true, alt: false, logo: false } } } }
[2019-02-19 14:57] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(13))), event: Key(KeyboardInput { scancode: 42, state: Released, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
[2019-02-19 14:57] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(155189253))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 42, state: Released, virtual_keycode: Some(LShift), modifiers: ModifiersState { shift: true, ctrl: true, alt: false, logo: false } } } }
[2019-02-19 14:57] [INFO] glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(13))), event: Key(KeyboardInput { scancode: 29, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } }) }
[2019-02-19 14:57] [INFO] glutin event: WindowEvent { window_id: WindowId(X(WindowId(155189253))), event: KeyboardInput { device_id: DeviceId(X(DeviceId(3))), input: KeyboardInput { scancode: 29, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }

```

**Comment by enizor** [comment] 2019-02-26 13:05
See https://github.com/tomaka/winit/issues/600

You can use instead its keycode as shown when you used `--print-events`:
```yaml
key_bindings:
  - { key: 52,  mods: Shift|Control,  chars: "action"  }
```

**Comment by chrisduerr** [comment] 2019-02-26 13:09
As @enizor has already correctly mentioned, this issue is caused by our dependency winit and might be a little more difficult to resolve. Using scancodes instead is a reliable solution which should work without any issues. Note that you can see the scancodes by looking at your `--print-events` output or by invoking `showkey --scancodes` on X11.

**Comment by sambrightman** [comment] 2019-02-26 13:56
Thanks, that works. Since tomaka/winit#600 is starting to age a bit, perhaps the wiki should be updated to emphasize this issue? Is it considered to only be an issue with `Shift`?

**Comment by chrisduerr** [comment] 2019-02-26 19:25
I think the support for scancodes is definitely not super well known, so it might make sense to add some form of documentation for this.

My initial thought was that it might be good to add it to the configuration file, but I feel like that's not something people read through completely when running into issues like that, so maybe the github wiki is a better solution.

@sambrightman Since you ran into this issue, where would you have looked to find out that this can be resolved with scancodes? Many people likely won't even be aware of what scancodes are, so that makes things even more difficult. If you've got any great idea on where this should be documented, I'd love to hear about it.

**Comment by sambrightman** [comment] 2019-02-26 20:12
I think I would have found it in both places but primarily the wiki, which sort of documents the behaviour & configuration, and comes up in search results. If the issue is specific to `Shift`, then the examples there incorrectly using virtual key codes led me to waste extra time before reporting this, and they should be updated too.

Am I correct in assuming that it would not be possible for alacritty to automatically use key codes: map configured key names to them instead virtual keys (or do so only when `Shift` is invoked?). My memory of keyboard logic is sketchy but I think the virtual part exists to abstract over keyboard models/maps?

**Comment by chrisduerr** [comment] 2019-02-26 20:17
This is only a problem with certain keys, not with `Shift` in general. Most keys work just as expected in my experience.

And all these issues need to be resolved upstream, it makes no sense trying to add additional maps in Alacritty when winit is already doing much of that.

**Comment by sambrightman** [comment] 2019-02-27 08:50
Ok, then I think just a clear wiki note makes sense.

**Comment by enizor** [comment] 2019-03-04 14:19
I added a [wiki note](https://github.com/jwilm/alacritty/wiki/Unmapped-keybindings:-using-a-keycode), if you could check that it's clear or would word something differently

**Comment by sambrightman** [comment] 2019-03-04 14:34
I would have it either in the main keyboard mappings page (my personal preference) or linked from the section "How to create a mapping".

I'm not sure it's technically correct to say that the problem is the lack of mapping in the source code. I get the impression that you should be able to add the `Shift` modifier in this example, without needing `GreaterThan` or similar. I also get the impression that when `winit` is fixed the mappings in Alacritty will not need updating to take advantage. Maybe I've misunderstood.

**Comment by chrisduerr** [comment] 2019-03-07 21:03
The wiki has been updated to document the support for scancodes and a reference to the default configuration file for a full syntax documentation has been added.

**Closed by chrisduerr** 2019-03-07 21:03 UTC
Labels: A - deps, S - docs, S - winit/glutin, help wanted
