### ISSUE TITLE
Characters inserted into neovim since foreground/background request escape codes added

### ISSUE THREAD

**Issue by E5ten** [jwilm/alacritty#2543] opened 2019-06-15 02:24 UTC
Which operating system does the issue occur on?
Linux

If on linux, are you using X11 or Wayland?
X11

Seemingly randomly (I can't tell what causes the bug to occur some times but not others, or why one escape is displayed in one instance but another at another time) when starting neovim since f790070, escapes get input as if I typed them, for example after starting nvim the most recent time it starts in command mode with `:.rgb:0/0/0^G` as the typed out command, another one is starting in search mode with either `/0` or `/0/0`.
![image](https://user-images.githubusercontent.com/24554283/59545850-b3b93500-8ef2-11e9-8956-40c600879214.png)

**Comment by chrisduerr** [comment] 2019-06-15 13:34
Getting the output of `alacritty -vvv | grep "Writing escape sequence for dynamic color code"` would be very helpful I think.

I personally can't reproduce this with the latest master, so I can only take guesses here. Could you try this with an empty nvim config and give detailed instructions on how you're causing this?

I'd also be very interested in seeing if this can be reproduced with XTerm.

The following patch might also solve it already, please give that a try if you've got some time:

```diff
diff --git a/alacritty_terminal/src/term/mod.rs b/alacritty_terminal/src/term/mod.rs
index 5cfd503..4a07d5b 100644
--- a/alacritty_terminal/src/term/mod.rs
+++ b/alacritty_terminal/src/term/mod.rs
@@ -1883,7 +1883,7 @@ impl ansi::Handler for Term {
     fn dynamic_color_sequence<W: io::Write>(&mut self, writer: &mut W, code: u8, index: usize) {
         trace!("Writing escape sequence for dynamic color code {}: color[{}]", code, index);
         let color = self.colors[index];
-        let _ = write!(writer, "\x1b]{};rgb:{:x}/{:x}/{:x}\x07", code, color.r, color.g, color.b);
+        let _ = write!(writer, "\x1b]{};rgb:{1:x}{1:x}/{2:x}{2:x}/{3:x}{3:x}\x07", code, color.r, color.g, color.b);
     }
 
     /// Reset the indexed color to original value
```

**Comment by chrisduerr** [comment] 2019-06-15 13:49
Oh, I think I've figured it out. I think this will be fixed if you set your background color to anything above hex `0F/0F/0F`.

I think the problem is that `0/0/0` is written as single-digits.

**Comment by chrisduerr** [comment] 2019-06-15 13:58
Attempted to fix this in https://github.com/jwilm/alacritty/pull/2544, please let me know if that does it for you.

**Comment by E5ten** [comment] 2019-06-15 14:39
```
[2019-06-15 10:33] [TRACE] [alacritty_terminal/src/term/mod.rs:1884] Writing escape sequence for dynamic color code 11: color[257]
[2019-06-15 10:33] [TRACE] [alacritty_terminal/src/term/mod.rs:1884] Writing escape sequence for dynamic color code 11: color[257]
[2019-06-15 10:33] [TRACE] [alacritty_terminal/src/term/mod.rs:1884] Writing escape sequence for dynamic color code 11: color[257]
[2019-06-15 10:34] [TRACE] [alacritty_terminal/src/term/mod.rs:1884] Writing escape sequence for dynamic color code 11: color[257]
[2019-06-15 10:34] [TRACE] [alacritty_terminal/src/term/mod.rs:1884] Writing escape sequence for dynamic color code 11: color[257]
[2019-06-15 10:34] [TRACE] [alacritty_terminal/src/term/mod.rs:1884] Writing escape sequence for dynamic color code 11: color[257]
[2019-06-15 10:34] [TRACE] [alacritty_terminal/src/term/mod.rs:1884] Writing escape sequence for dynamic color code 11: color[257]
[2019-06-15 10:34] [TRACE] [alacritty_terminal/src/term/mod.rs:1884] Writing escape sequence for dynamic color code 11: color[257]
[2019-06-15 10:34] [TRACE] [alacritty_terminal/src/term/mod.rs:1884] Writing escape sequence for dynamic color code 11: color[257]
```
Each line looks the same to me, each one is for one opening of nvim the exact same way (and I didn't this time but I previously tested with both `nvim -u NORC` and `nvim -u NONE`, #2544 seems to have just increased how many 0s there are. The first picture attached is related to the second line, the second picture to the third line, the third one to the last line, and all other lines had nothing weird upon opening nvim
![Screenshot 2019-06-15 10-33-51](https://user-images.githubusercontent.com/24554283/59552830-bd29b800-8f59-11e9-94ec-213bca56a82a.png)
![Screenshot 2019-06-15 10-34-11](https://user-images.githubusercontent.com/24554283/59552838-cfa3f180-8f59-11e9-9d41-de74df7ce13b.png)
![Screenshot 2019-06-15 10-39-03](https://user-images.githubusercontent.com/24554283/59552841-d29ee200-8f59-11e9-9d3b-f4a0e519e971.png)

**Closed** 2019-06-15 16:52 UTC
Labels: B - bug, P - high
