### ISSUE TITLE
Nerd font not displayed correctly on Windows 10

### ISSUE THREAD

**Issue by Tagussan** [jwilm/alacritty#1863] opened 2018-12-05 09:53 UTC
Which operating system does the issue occur on?
> Windows 10

If on linux, are you using X11 or Wayland?

Hi. If I use UbuntuMono nerd font on Windows10, it is not displayed correctly. This is screenshot.
![alacritty_nerd](https://user-images.githubusercontent.com/3764516/49505310-d5d85780-f8be-11e8-86c1-c93844638af7.PNG)

It should be displayed like this(on mintty, wsl)
![mintty](https://user-images.githubusercontent.com/3764516/49505393-061ff600-f8bf-11e8-8c65-d598d29feaaf.PNG)

**Comment by chrisduerr** [comment] 2018-12-05 19:37
@zacps Is there any font fallback behavior on Windows?

I think it's just loading your default font, which doesn't support the glyphs required to render the powerline symbols.

**Comment by zacps** [comment] 2018-12-05 19:41
There isn't font fallback support yet. If it's the specified font it shouldn't matter however.

Either way I suspect this will be fixed by https://github.com/jwilm/alacritty/pull/1720.

**Comment by chrisduerr** [comment] 2018-12-06 14:34
> It would be helpful to show error message, if the specified font are invalid

The problem is that 'invalid' is a very subjective term here. I wouldn't be surprised if a large chunk of users has an invalid font inside their configuration file. Theoretically even the default `monospace` often isn't a real font, but just resolves to the primary monospace font.

So font loading is all about trying to interpret incorrect/imprecise user input into a potential correct selection which hopefully matches what the user desires. In your case the selected font was just not what you expected, but there's little that can be done since Alacritty can't read your mind (YET!).

**Closed by chrisduerr** 2018-12-06 14:34 UTC
Labels: H - windows, S - font

**Comment by vinz243** [comment] 2019-01-06 18:10
I have the same issue, but the font configuration is right. I'm using `FuraCode NF`, and once I set this value the font changed, so I know it's working :
before :
![image](https://user-images.githubusercontent.com/4569266/50739900-80a5a380-11e6-11e9-8c2d-81bd23435236.png)
after :
![image](https://user-images.githubusercontent.com/4569266/50739912-a337bc80-11e6-11e9-9eed-8b2b483c7ae6.png)
