### ISSUE TITLE
tmux background colors cause windows to become completely opaque

### ISSUE THREAD

**Issue by fallwith** [jwilm/alacritty#1180] opened 2018-03-12 20:12 UTC
macOS 10.13.3 with tmux 2.6

I have Alacritty's opacity level set to 80%:

```
background_opacity: 0.8
```

The resulting Alacritty window is partially opaque as desired. Then I launch tmux and the window becomes completely opaque.

I have discovered that if I stop specifying background colors in tmux's configuration, the Alacritty window remains correctly at the desired 80% opacity.

```
# original tmux configuration
set -g window-style 'fg=colour250,bg=colour233'
set -g window-active-style 'fg=colour255,bg=black'

# workaround for Alacritty opacity issue
set -g window-style 'fg=colour250'
set -g window-active-style 'fg=colour255'
```

My expectation is that a background color choice from a terminal application should not have an impact on that terminal's window opacity. If there is anything I can do currently in either Alacritty or tmux to leverage both background colors and transparency, please let me know.

**Comment by jwilm** [comment] 2018-03-12 22:20
Does this not show up in other terminals? From what I've looked at with eg urxvt, background is always filled in at 100% opacity *unless* it's the default background color.

**Comment by chrisduerr** [comment] 2018-03-12 22:28
I guess it's a question of how you want to look at it. Our global `opacity` setting should probably always take place and just make every background transparent.

Then alternatively the background color of the terminal could be set to something like `0xff00ff22` to have transparency just  for the default background color.

I can see why you'd expect everything to be transparent when setting a global opacity to a certain value.

Allowing RGBA notation is probably a bit too much, but I can see where the confusion is coming from.

**Comment by maximbaz** [comment] 2018-03-12 22:42
For reference: https://github.com/jwilm/alacritty/pull/847

**Comment by fallwith** [comment] 2018-03-12 22:46
@jwilm the other terminals I've tested recently under macOS are Terminal and iTerm 2 and both of those retain transparency despite the presence of a background color. It's a fair point about the current behavior possibly matching the expected behavior of most terminals (Linux ones especially). I'd be ok with the default behavior remaining as is if that's the case.

**Comment by fallwith** [comment] 2018-03-12 22:49
@chrisduerr You've summarized the situation perfectly and greatly helped with my understanding of why things are the way they are now. Thank you. Since opening this issue I've realized that it is not tmux specific (can reproduce with a Vim background color as well outside of tmux). Your comment explaining the background color behavior is quite helpful.

**Comment by sodiumjoe** [comment] 2018-04-05 04:28
I think this is a dupe of #1082

**Comment by chrisduerr** [comment] 2018-10-02 21:04
Closing as a duplicate of #1082. Thanks for the heads-up joe.

**Closed by chrisduerr** 2018-10-02 21:04 UTC

**Comment by RichardBronosky** [comment] 2021-03-06 04:35
I don't think this should be closed. There is no solution that I can find.

**Comment by jakewilliami** [comment] 2022-07-10 12:54
@RichardBronosky, I also could not find a solution for a while, but in the [most recent configuration](https://github.com/alacritty/alacritty/releases/download/v0.10.1/alacritty.yml) at time of writing, I found on [line 333](https://github.com/alacritty/alacritty/blob/2844606db8201d40462a01b29299ac3c5a52c523/alacritty.yml#L333) a setting which, if you set to `true`, will allow `tmux` to have a transparent background.  That is:
```yaml
colors:
  # ...
  transparent_background_colors: true
```

I hope this helps others debug the same issue.
