### ISSUE TITLE
0.29 window content disappears during resize in High Sierra

### ISSUE THREAD

**Issue by igorclark** [jwilm/alacritty#2144] opened 2019-03-02 10:58 UTC
_Which operating system does the issue occur on?_ MacOS 10.13.6 High Sierra

Since upgrading Alacritty to 0.29 from Homebrew, all window content disappears during resizes, but the title bar stays visible. See [screencast video](https://vimeo.com/320924172).

**Comment by chrisduerr** [comment] 2019-03-02 12:56
Duplicate of https://github.com/jwilm/alacritty/issues/1471.

**Closed by chrisduerr** 2019-03-02 12:56 UTC

**Comment by igorclark** [comment] 2019-03-02 20:10
Hi, thanks for looking at this - I'm not sure this is the same bug because (a) the edges of the window don't show up in the video I sent, it looks quite different from the one in #1471, and (b) this didn't happen on 0.25 on High Sierra which I've been using for a month+ and which worked perfectly well, so if it is the same issue, it seems like it might be a regression. Also I'm not using a specific branch or commit, just whatever comes out of Homebrew, which seems like it ought to be a 'last known good' or similar :-)

**Comment by chrisduerr** [comment] 2019-03-02 20:25
Even if this is not exactly the same issue, I'd be surprised if the cause wouldn't be the same. So I think tracking it in the other issue should be fine and I'd recommend subscribing to that.

**Comment by igorclark** [comment] 2019-03-02 21:06
OK will do. Thanks.
