### ISSUE TITLE
alacritty 0.3.0 occasionally fails to redraw the screen

### ISSUE THREAD

**Issue by baergj** [jwilm/alacritty#2321] opened 2019-04-16 22:41 UTC
_Which operating system does the issue occur on?_ Gentoo Linux
_If on linux, are you using X11 or Wayland?_ X11

Ever since updating to the 0.3 series, alacritty will occasionally fail to redraw until something forces the redraw (such as input or moving the mouse over the terminal window).

Let me know what additional information I can provide.

**Comment by nixpulvis** [comment] 2019-04-16 23:58
Can you run `alacritty -vvv` and see what it prints before it hangs perhaps?

**Comment by jbolila** [comment] 2019-04-17 08:27
+1 on Linux X11 and it seems to happen, at least more frequently in full screen mode, and for commands who take time without screen updates, e.g. durring a rust project compilation. Alacritty doesn't hang, but stops redrawing while there's no keystrokes, after a keystroke the screen gets updated and everythink works as expected again.

Can't see any error with `-vvv`

**Comment by nixpulvis** [comment] 2019-04-17 14:42
I wasn't really expecting to see an error if all it's doing is hanging for a moment then moving on. I was curious to see the last few log messages logged when the terminal is hanging, before you hit  keystroke and unhang it.

**Comment by baergj** [comment] 2019-04-17 15:00
I'm still trying to capture this. I can't make the issue happen at will so it will take a bit of time. :)

**Comment by baergj** [comment] 2019-04-17 15:11
OK, observing this, it's going to be tricky to match the logs up with the issue.

I think what I'm seeing is that when alacritty stops redrawing, the log output continues as normal. In my current test, it's repeating:
```
[2019-04-17 09:09] [TRACE] [src/term/mod.rs:1689] Carriage return
[2019-04-17 09:09] [TRACE] [src/term/mod.rs:1697] Linefeed
[2019-04-17 09:09] [TRACE] [src/term/mod.rs:1333] Scrolling up relative: origin=0, lines=1
```
In this case, the output is periodically freezing and unfreezing - something I didn't notice before I watched the alacritty logs.

**Comment by baergj** [comment] 2019-04-17 15:18
Also occasionally:
```
[2019-04-17 09:18] [TRACE] [src/term/mod.rs:1450] Wrapping input
```

**Comment by baergj** [comment] 2019-04-17 17:16
OK, here's an entire log sequence leading up to a redraw issue (i.e., the screen was drawn correctly before, but not redrawn properly after this sequence).

```
[2019-04-17 11:12] [TRACE] [src/term/mod.rs:1609] Moving backward: 8
[2019-04-17 11:12] [TRACE] [src/term/mod.rs:2014] Setting attribute: Bold
[2019-04-17 11:12] [TRACE] [src/term/mod.rs:2147] Configuring charset G0 as Ascii
[2019-04-17 11:12] [TRACE] [src/term/mod.rs:2014] Setting attribute: Reset
[2019-04-17 11:12] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Named(Cyan))
[2019-04-17 11:12] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Named(Foreground))
[2019-04-17 11:12] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Named(Cyan))
[2019-04-17 11:12] [TRACE] [src/term/mod.rs:2147] Configuring charset G0 as Ascii
[2019-04-17 11:12] [TRACE] [src/term/mod.rs:2014] Setting attribute: Reset
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2127] Setting scrolling region: Line(43)..Line(85)
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1535] Going to: line=0, col=0
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1535] Going to: line=84, col=318
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1697] Linefeed
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1333] Scrolling up relative: origin=43, lines=1
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2127] Setting scrolling region: Line(0)..Line(86)
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1535] Going to: line=0, col=0
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1535] Going to: line=84, col=0
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2087] Unsetting mode: BracketedPaste
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2127] Setting scrolling region: Line(43)..Line(85)
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1535] Going to: line=0, col=0
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1535] Going to: line=84, col=318
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1697] Linefeed
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1333] Scrolling up relative: origin=43, lines=1
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2127] Setting scrolling region: Line(0)..Line(86)
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1535] Going to: line=0, col=0
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1535] Going to: line=84, col=0
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2127] Setting scrolling region: Line(43)..Line(85)
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1535] Going to: line=0, col=0
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1333] Scrolling up relative: origin=43, lines=3
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1535] Going to: line=81, col=0
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1689] Carriage return
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1697] Linefeed
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1689] Carriage return
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1697] Linefeed
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2127] Setting scrolling region: Line(0)..Line(86)
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1535] Going to: line=0, col=0
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1535] Going to: line=84, col=0
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2047] Setting mode: BracketedPaste
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Dim
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2147] Configuring charset G0 as Ascii
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Reset
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1535] Going to: line=84, col=0
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1689] Carriage return
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1868] Clearing line: Right
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Indexed(250))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Background(Indexed(240))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Indexed(240))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Background(Indexed(31))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Named(BrightWhite))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Indexed(31))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Background(Indexed(237))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Indexed(250))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Indexed(244))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Indexed(254))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Indexed(237))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Background(Indexed(148))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Named(Black))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Indexed(148))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Background(Indexed(240))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Indexed(250))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Indexed(240))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Indexed(250))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Indexed(240))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Background(Indexed(236))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Named(BrightWhite))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Background(Named(Background))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Indexed(236))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:2014] Setting attribute: Foreground(Named(Foreground))
[2019-04-17 11:13] [TRACE] [src/term/mod.rs:1868] Clearing line: Right
```

Specifically, I believe I see that first `Linefeed` being redrawn (when I hit `<enter>` for a command), but nothing after that.

**Comment by chrisduerr** [comment] 2019-04-17 18:13
This is a duplicate of https://github.com/jwilm/alacritty/issues/2217.

**Closed by chrisduerr** 2019-04-17 18:13 UTC
Labels: B - bug, H - linux

**Comment by baergj** [comment] 2019-04-17 19:29
Excellent, thanks!
