### ISSUE TITLE
alacritty freezes i3wm when alacritty is killed

### ISSUE THREAD

**Issue by vitiral** [jwilm/alacritty#95] opened 2017-01-06 20:30 UTC
Love the app.

I am having an issue where alacritty sometimes freezes the i3 window manager (can still move the mouse, but can't type or change workspaces) when I "kill" alacritty via i3.

I was wondering if there was somewhere where I could find logs to see what might be going on?

**Comment by vitiral** [comment] 2017-01-06 20:34
the issue also seems to happen when I type "exit" into my zsh terminal. My guess is that alacritty is exiting ungracefully somehow and i3wm isn't cleaning up after it (never had a problem with i3 before this)

**Comment by d3rrial** [comment] 2017-01-06 20:34
```zsh
./alacritty > somelogfile.log
```
And then kill it in i3wm?

**Comment by jwilm** [comment] 2017-01-06 20:41
Wow, that's really bad! Thanks for the report. Going to prioritize issues like this.

**Comment by vitiral** [comment] 2017-01-06 20:50
I got these logs with these commands:
```
i3-msg 'debuglog on; shmlog on; reload' 
alacritty > alacritty.log; DISPLAY=:0 i3-dump-log > i3.log
```

alacritty loaded up great, I then typed just `exit<RETURN>` into the terminal. This prevented me from typing anything else, or switching to a different work space (but the mouse still worked, which is *weird*)

<details>
  <summary>alacritty log</summary>
```
device_pixel_ratio: 1
width: 956, height: 1029
Initializing glyph cache
num fonts = 195
num fonts = 195
num fonts = 195
Finished initializing glyph cache in 0.020326923
set_inner_size: 644px � 436px
width: 644, height: 436
Cell Size: (8 x 18)
PTY Dimensions: Line(24) x Column(80)
num_cols, num_lines = 119, 57
width: 956, height: 1029
Goodbye
```
</details>

The i3 log is too big for github comment:

http://pastebin.com/SwJ9PtQk

**Comment by d3rrial** [comment] 2017-01-06 20:57
argh, my bad, you need to redirect stderr, not stdout
```zsh
alacritty 2> alacritty.log; DISPLAY=:0 i3-dump-log > i3.log
```

**Comment by vitiral** [comment] 2017-01-06 21:06
here is the new command (both stdout and stderr)
```
alacritty &> alacritty.log; DISPLAY=:0 i3-dump-log > i3.log
```

here are the logs:
- [alacritty](http://pastebin.com/j0anRa6A)
- [i3wm](http://pastebin.com/G8xQM5pb)

**Comment by vitiral** [comment] 2017-01-06 21:07
I should also mention that after exiting I punched a few keys for a while (trying to type into the terminal and change workspaces)

**Comment by vitiral** [comment] 2017-01-06 21:08
Alright, I'm done crashing my system over and over again for the day, time to get some work done :smile:

**Comment by wbthomason** [comment] 2017-01-06 22:04
I can also help debug/repro this, as I've experienced it also. What would help?

**Comment by d3rrial** [comment] 2017-01-06 22:14
I've just experimented a little and I believe I do experience this as well sometimes.
When this error occurs, can you change workspaces by moving the mouse over the i3bar and using the scrollwheel? After you've done this, are you able to use i3 normally again?

Because that's how it works for me (I can also hover the mouse over another i3 urxvt window to change focus and this unlocks i3 for me again as well)

For me all keyboard input goes into a black hole, but mouse input is still valid.

**Comment by daniel-ferguson** [comment] 2017-01-06 22:25
I can also repro, however when alacritty is quit while in 'floating' mode (as opposed to the default 'tiling' mode) the issue doesn't occur.

@d3rrial's suggestion to change workspaces with a mouse scroll (or a click) works for me.

**Comment by vitiral** [comment] 2017-01-06 22:46
@d3rrial Can confirm that manually selecting workspaces by clicking on them gets everything back to normal again.

So it's probably just stealing all the keyboard input -- which is weird, because my $mod key commands normally have priority over ANYTHING (seems like it might be an i3 bug as well TBH).

**Comment by brownjohnf** [comment] 2017-01-06 23:22
I'm having the same issues, also fixed by scrolling in the i3 workspace section. Generally love it though.

```
$ i3 --version
i3 version 4.13 (2016-11-08) © 2009 Michael Stapelberg and contributors
$ uname -a
Linux 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
```

**Comment by wbthomason** [comment] 2017-01-07 02:29
I now only sometimes observe the buggy behavior. When it does happen, scrolling/clicking also fixes it for me.

I've seen something like this with the Spotify desktop client (when it's running, i3 will periodically freeze in a similar way), so I could buy that this is an i3 bug. I'm not certain, though.

FWIW, I'm using i3-gaps-git from the AUR.

**Comment by d3rrial** [comment] 2017-02-12 08:33
Still very relevant. I've made alacritty my standard terminal on my laptop, and now whenever I close alacritty without having any other workspaces open, all keyboard input is ignored and I'm helpless to do anything, except rebooting by hitting the power key, which is very much something that can ruin the terminal for me.

I hope this is fixed soon. If you need me to help running any tests, just e-mail me or reply here and I'll do my best, but this has got to go.

**Comment by antoyo** [comment] 2017-04-20 20:02
I am able to get this issue by running the command `alacritty -e "tmux 2"`.
It shows the following output (without showing alacritty): `Command::spawn() failed: No such file or directory (os error 2)` and then I cannot use the keyboard until I change window or workspace.
I you need, I can try debugging this issue.

**Comment by yonson2** [comment] 2017-04-27 23:40
I'm also getting the same issue on with alacritty on i3, running arch.
If I can help in any way by providing logs or w/e I'm all for it.

**Comment by jwilm** [comment] 2017-07-02 03:18
Is this still a problem for anyone?

**Comment by badboy** [comment] 2017-07-02 13:10
I quickly tried it with a fresh checkout and couldn't reproduce it anymore.

**Comment by jwilm** [comment] 2017-07-02 15:44
Thanks for the feedback!

**Closed by jwilm** 2017-07-02 15:44 UTC
Labels: bug, H - linux, P - high
