### ISSUE TITLE
Strips blank lines on copy from terminal

### ISSUE THREAD

**Issue by inducer** [jwilm/alacritty#731] opened 2017-08-16 00:13 UTC
If I mouse-copy (i.e. select and press Shift-Ctrl-C) some text containing blank lines, then these blank lines do not make it into the copied text. They're significant in some cases (such as diffs), so this is not ideal.

**Comment by NickeZ** [comment] 2017-08-16 14:47
Possible dupe of #432

**Comment by FichteFoll** [comment] 2018-01-19 14:50
Also running into this. Usually not too severe, but definitely annoying for situations where empty lines matter, such as for diffs.

**Comment by chrisduerr** [comment] 2018-12-17 16:08
This has been resolved on the latest master.

**Closed by chrisduerr** 2018-12-17 16:08 UTC
