### ISSUE TITLE
Moving alacritty from or to a retina display change the font size

### ISSUE THREAD

**Issue by MarioAriasC** [jwilm/alacritty#754] opened 2017-08-24 19:12 UTC
In OSX, if I move alacritty from or to a screen that isn't retina it messes up the font size. 

I suppose that is an issue with high-resolution displays

**Comment by asilvadesigns** [comment] 2017-08-24 19:36
@MarioAriasC there are a few issues which exists related to this, see:
#625, #71

**Comment by jwilm** [comment] 2017-08-24 19:38
Thanks @asilvadesigns 

Closing as duplicate of #71.

**Closed by jwilm** 2017-08-24 19:38 UTC
