### ISSUE TITLE
Jumping from VAAPI-rendered screen to alacritty causes GPU to hang

### ISSUE THREAD

**Issue by nagisa** [jwilm/alacritty#150] opened 2017-01-07 03:24 UTC
Reproducible: always.
CPU/GPU: Intel® Core™ i7-4750HQ/Integrated
Driver packages: xf86-video-intel 1:2.99.917+746+g169c74f-1 + i915 1.6.0 20160711

So I’ve used alacrity twice to launch `mpv` (which uses VAAPI decoding and rendering). As soon as I tab from `mpv` directly to `alacrity`, the display (gpu) hangs and no amount of blind typing salvages the system (CPU reset is necessary).

While I doubt there’s anything actionable to be done here, I thought it would be a good idea to report the issue nevertheless.

**Comment by accaldwell** [comment] 2017-01-07 03:40
I have a very similar system: up to date Arch Linux w/ Haswell iGPU and I can't reproduce this issue. Launched mpv with --hwdec=vaapi --vo=vaapi.

I suspect whatever your issue is it doesn't have to do with alacritty.

**Comment by jwilm** [comment] 2017-01-07 06:01
Thanks for the report! Sorry you're having issues :(

**Comment by jwilm** [comment] 2017-07-02 01:02
Closing this since there's not anything actionable on our side. Thanks for documenting the problem, though!

**Closed by jwilm** 2017-07-02 01:02 UTC
