### ISSUE TITLE
High CPU usage after a while

### ISSUE THREAD

**Issue by michele** [jwilm/alacritty#1861] opened 2018-12-04 10:12 UTC
I'm currently running 0.2.3 and I've noticed that after a couple of hours since launch, alacritty's CPU usage gets to around 60-70% on a fully spec'd x1c6, and it stays there until I quit it.
I tried opening alacritty and leaving it open without anything running inside it and after a few hours it's CPU usage went through the roof.

Which operating system does the issue occur on?

Arch

If on linux, are you using X11 or Wayland?

i3 on X11.

**Comment by NickeZ** [comment] 2018-12-04 14:57
Are you using multiple monitors? https://github.com/jwilm/alacritty/issues/1790

**Comment by chrisduerr** [comment] 2018-12-04 15:57
Likely a duplicate of #1790, closing for now as duplicate.

If you do only have a single monitor which is using a 1.0 DPR (see `alacritty -v`), then please let me know and I'll re-open.

**Closed by chrisduerr** 2018-12-04 15:57 UTC

**Comment by michele** [comment] 2018-12-04 16:07
@chrisduerr @NickeZ it looks like a duplicate indeed. Sorry about it!
