### ISSUE TITLE
Feature request: Underline links on hover

### ISSUE THREAD

**Issue by jplatte** [jwilm/alacritty#2100] opened 2019-02-11 13:12 UTC
This would make it more obvious that they are clickable (I only learned about that by reading the config file) and show the user which part of the text was detected as a link.

**Comment by nixpulvis** [comment] 2019-02-11 14:49
This feature has been discussed before in a few threads, I'm personally happy to have a full feature issue for it.

I think the main complexity here is determaining "when" to show the underline. On mouse hover? Or when the user holds a modifier key? I can see advantages of both.

**Comment by chrisduerr** [comment] 2019-02-11 15:43
Duplicate of #1618.

**Closed by chrisduerr** 2019-02-11 15:43 UTC
