### ISSUE TITLE
[Feature] Simple fullscreen

### ISSUE THREAD

**Issue by ahmedelgabri** [jwilm/alacritty#1051] opened 2018-01-24 19:57 UTC
I'd really like to move to alacritty but I use iTerm in fullscreen all the time & there are two things that I can't get used to with alacritty:

- #168 
- And using macOS native fullscreen (it distracts me & I can't use it) I use iTerm2 every day in fullscreen but not the native fullscreen (don't know what to call it) but it doesn't use separate space, can alacritty support for something like this?

**Comment by chrisduerr** [comment] 2018-01-24 20:01
Duplicate of #34.

**Closed by chrisduerr** 2018-01-24 20:01 UTC

**Comment by ahmedelgabri** [comment] 2018-01-24 22:26
Just knew about [`decorations`](https://github.com/jwilm/alacritty/blob/59b561b440060e7b0d13160fb69519d127e6c687/alacritty_macos.yml#L32) & that's already awesome!
