### ISSUE TITLE
Text shrinks when moving Alacritty between 4k monitor and retina display

### ISSUE THREAD

**Issue by robert-snakard** [jwilm/alacritty#1196] opened 2018-03-19 17:48 UTC
Which operating system does the issue occur on? OSX Sierra

If I start alacritty on my 4k monitor then drag it to my laptop the text shrinks by 4x. If I start it on my laptop then drag it to my monitor the text grows by 4x.

**Comment by chrisduerr** [comment] 2018-03-19 18:01
This is a duplicate of #71.

**Closed by chrisduerr** 2018-03-19 18:01 UTC
