### ISSUE TITLE
Quotes, double-quotes, sharp accents are not working

### ISSUE THREAD

**Issue by jojoyuji** [jwilm/alacritty#764] opened 2017-08-29 14:36 UTC
pressing quotes/doublequotes/sharp accents is not working for me :(

**Comment by jwilm** [comment] 2017-08-29 15:38
Are you on macOS or Linux? Wayland or X11?

**Comment by jojoyuji** [comment] 2017-08-29 16:30
macOS El captain
sorry for the lack of information

**Comment by jwilm** [comment] 2017-08-29 16:36
Are you using an alternate keyboard layout?

**Comment by jojoyuji** [comment] 2017-08-29 16:38
Using U.S. International - PC keyboard layout

**Comment by dawsonfi** [comment] 2017-09-06 20:04
Hi,
I'm having the same problem here.

Specs:
Branch: Master
OS: MacOS Sierra
Keyboard: U.S. International - PC keyboard layout
Alacritty Configs: All Default
Rust: from rustup -> rustc 1.19.0 (0ade33941 2017-07-17)

**Comment by dawsonfi** [comment] 2017-09-06 20:06
If possible @jwilm, i would like to help finding the problem and fixing it.

Could you please help me finding where can i start looking in the code to check why those characters are not working?

**Comment by dawsonfi** [comment] 2017-09-06 21:27
It look's like that glutin is not creating an `ReceivedCharacter` event when quotes is pressed.

**Comment by dawsonfi** [comment] 2017-09-07 02:05
I've tracked down the problem, and it looks like a bug in [cocoa-rs](https://github.com/servo/cocoa-rs), but i haven't figured out where exactly yet.

The dependency path:
[alacritty](https://github.com/jwilm/alacritty) ->  [glutin](https://github.com/tomaka/glutin) -> [winit](https://github.com/tomaka/winit) -> [cocoa-rs](https://github.com/servo/cocoa-rs)

In winit crate, there's a [call](https://github.com/tomaka/winit/blob/342d5d8587d96bec804ef45f3f7d6abec950e826/src/platform/macos/events_loop.rs#L316) to **cocoa-rs** `NSEvent::characters` function, witch should return the pressed key, but when pressing **Quote** it returns `empty`.

I will try to find a fix for **cocoa-rs** or some workaround here to fix this.

If someone have any ideias, i would love to hear.

**Comment by dawsonfi** [comment] 2017-09-07 02:25
I've created the [issue](https://github.com/servo/cocoa-rs/issues/168) in cocoa-rs crate.

**Comment by dawsonfi** [comment] 2017-09-07 18:51
Hey @jojoyuji,

I've created an [temporary fix](https://github.com/dawsonfi/alacritty/blob/master/src/event.rs) to allow us to use alacritty until a better solution to the cocoa-rs issue is found.

Is not pretty, but at least it works.

Just add this code to the start of event.rs archive:

```
use glutin::VirtualKeyCode;

trait CharTranslator {
    fn can_translate(self) -> bool;
    fn to_char(self, shift_pressed: bool) -> char;
}

impl CharTranslator for VirtualKeyCode {
    fn can_translate(self) -> bool {
        match self {
            VirtualKeyCode::Apostrophe | VirtualKeyCode::Grave => true,
            _ => false,
        }
    }

    fn to_char(self, shift_pressed: bool) -> char {
        match self {
            VirtualKeyCode::Apostrophe => {
                if shift_pressed { '\"' } else { '\'' }
            },
            VirtualKeyCode::Grave => {
                if shift_pressed { '~' } else  { '`' }
            },
            _ => ' ',
        }
    }
}
```

And change the [handle_event function](https://github.com/jwilm/alacritty/blob/8990aa4568ea8a7481f827512b7487be4d39332a/src/event.rs#L280) adding the following logic:

```
if virtual_keycode.unwrap().can_translate() {
    processor.received_char(virtual_keycode.unwrap().to_char(modifiers.shift));
}
```

It will look like this:

```
                    KeyboardInput { input, .. } => {
                        let glutin::KeyboardInput { state, virtual_keycode, modifiers, .. } = input;
                        processor.process_key(state, virtual_keycode, &modifiers);
                        if state == ElementState::Pressed {
                            // Hide cursor while typing
                            *hide_cursor = true;

                            if virtual_keycode.unwrap().can_translate() {
                                processor.received_char(virtual_keycode.unwrap().to_char(modifiers.shift));
                            }
                        }
                    },
```

Hope it helps you.

**Comment by jojoyuji** [comment] 2017-09-14 16:11
Thx @dawsonfi, however for each quote press it prints twice the quotes :/

**Comment by AdrienGiboire** [comment] 2018-03-16 10:44
Hi! I just landed on Alacritty and I'm really interested in the resolution of this issue :)

**Comment by jojoyuji** [comment] 2018-03-16 12:29
me too @AdrienGiboire

**Comment by dawsonfi** [comment] 2018-03-16 19:04
I just saw that the [cocoa-rs](https://github.com/servo/cocoa-rs) is deprecated, there's the [core-foundation-rs](https://github.com/servo/core-foundation-rs/) to replace.
I'll try to change the dependencies and see if it works.

**Comment by yofriadi** [comment] 2018-04-15 10:46
Hi I just want to report that backtick & tilde is not functioning too.

**Comment by francesca64** [comment] 2018-05-15 21:04
Does it work on this branch? https://github.com/francesca64/alacritty/tree/macos-kb

(Relevant winit PR: tomaka/winit#518)

**Comment by nixpulvis** [comment] 2018-05-15 22:29
FWIW, I just got a Mac I'm setting up today (for work), and I'm able to enter quotes and tilde and everything just fine on master. I'm running macOS 10.13.4 (17E199).

**Comment by francesca64** [comment] 2018-05-15 23:34
@nixpulvis with what keyboard layout / input source?

**Comment by nixpulvis** [comment] 2018-05-16 00:46
@francesca64 Just plain "U.S." I can reproduce when I switch to "U.S. International - PC" as the author had mentioned he was using. Sorry for the noise.

**Comment by nixpulvis** [comment] 2018-05-16 00:58
@francesca64 just pulled your branch, and no dice.

**Comment by francesca64** [comment] 2018-05-16 01:46
It seems to work as expected for me, though it's less intuitive due to the lack of visual feedback. `'`+ `Space`= `'`, `'`+ `e` = `é`.

**Comment by jojoyuji** [comment] 2018-05-17 12:58
It's working beautifully @francesca64 !

**Comment by nixpulvis** [comment] 2018-05-18 10:18
Ok I'm not sure why this didn't work for me, but feel free to ignore my attempts at helping on this issue.

**Closed** 2018-05-29 16:50 UTC
Labels: A - awaiting feedback, B - bug, S - input, S - winit
