### ISSUE TITLE
Mouse selection is not cleared by scrolling

### ISSUE THREAD

**Issue by grinapo** [jwilm/alacritty#877] opened 2017-10-30 10:29 UTC
***Which operating system does the issue occur on?***
Debian Linux/sid

***If on linux, are you using X11 or Wayland?***
X11

***What's your pain?***
1) ```ls /usr/bin | while read i ; do echo $i; sleep 1; done```
2) select anything by mouse
3) the selection (reverse strip) stays there while the content scrolls up

I'm not sure whether this is by design or a bug, but OtherTerminals™ work differently.

**Comment by grinapo** [comment] 2017-11-28 21:32
dup of #836  ?

**Comment by jwilm** [comment] 2017-11-29 02:00
Yep, dupe of #836. Not by design, but we also haven't done the work to implement this part of selections; maybe you could call it a bug :).

**Closed by jwilm** 2017-11-29 02:00 UTC
