### ISSUE TITLE
pictures in terminal

### ISSUE THREAD

**Issue by StrictAvacado** [jwilm/alacritty#1364] opened 2018-06-10 03:19 UTC
i cant get w3m to work in alacritty i can see an image if a scroll i am using the scrollback branch
this is used in neofetch for images. is this an issue with scrollback? works in gnome-terminal.

https://github.com/dylanaraps/neofetch/wiki/What-is-Waifu-Crop%3F

take at look at this concept image 
https://askubuntu.com/questions/97542/how-do-i-make-my-terminal-display-graphical-pictures?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by chrisduerr** [comment] 2018-06-10 10:30
I'm going to close this as a duplicate of #1021, there also is a hacky workaround script in the comments there that might help you out.

**Closed by chrisduerr** 2018-06-10 10:30 UTC
