### ISSUE TITLE
Alacritty window rescales during startup

### ISSUE THREAD

**Issue by tmalsburg** [jwilm/alacritty#204] opened 2017-01-07 19:13 UTC
When I start alacrity, it first creates a large window which is then very quickly resized to the final size (~70%).  The resizing is really fast and wouldn't bother me but my window manager (fvwm2) places the window based on the original size and that means that the window position ends up not being what it is supposed to be. 

Ubuntu 16.10.  Default alacritty.yml except that I changed the font size to 13.

**Comment by jwilm** [comment] 2017-01-07 22:45
Thanks for filing this issue. The problem here is we need to know some font metrics to know the proper window size to create, but we can't know the font metrics without having the DPI scaling factor which comes from the window.

Glutin needs a way to get the DPI scaling info for a monitor without actually creating a window.

**Comment by tmalsburg** [comment] 2017-02-13 19:28
A workaround would be to open a window to get the DPI scaling factor, then close it and open a new one with the correct size.  Not great but perhaps better than the current state of affairs.

**Comment by bosslady6880** [comment] 2017-02-13 19:31
Sent from Alto

On Monday, February 13, 2017 at 12:28 PM Titus von der Malsburg <notifications@github.com> wrote:

A workaround would be to open a window to get the DPI scaling factor, then close it and open a new one with the correct size. Not great but perhaps better than the current state of affairs.

**Comment by 5paceToast** [comment] 2017-10-14 14:21
I personally find the resizing extremely distracting, especially for something I open on a regular basis.
A possible workaround could be allowing one to detect the dpi scaling factor (e.g launch with a flag, giving the output), which could then be added to alacritty.yml (if it's found in there, there then wouldn't be a need to resize)

**Comment by noctuid** [comment] 2018-03-08 22:04
Alacritty will resize the window after it has been mapped even if the window size has already been altered (e.g. by an `xdotool` command). As an example of where this might happen, tdrop (which is a wrapper to run programs as dropdowns) uses xdotool to set the window size before alacritty resizes itself (see noctuid/tdrop#38 for the original issue). This behavior is not a big issue w.r.t. using xdotool since `-d 0 0` can be used to prevent it, but I found it unexpected.

**Comment by pnrao** [comment] 2018-03-23 01:46
@jwilm Could you change the parameters we enter in the config file so that we enter dimensions in pixels and you calculate the lines and columns after you initialize the window? At least that way, the window manager can make good decisions on where to place the window.

**Comment by chrisduerr** [comment] 2019-04-12 21:49
Can someone check if https://github.com/jwilm/alacritty/pull/2307 fixes this?

**Comment by 5paceToast** [comment] 2019-04-13 01:35
@chrisduerr still seeing the behavior with that branch.
The default size will typically stick and be fine, but is not a realistic use-case.
If you set the configuration file to a given terminal size in cols/lines (e.g my preferred ratio of 90/27) it still resizes down.
I suspect that the issue you were trying to address is a secondary one mentioned in a comment (resizing even if the size was already set by xdotool or similar), rather than the resizing on startup in general (the actual bug).

The original comment by @jwilm suggests that the issue is with lack of API support within glutin, but as per the two bugs above (tomaka/glutin#1096 and tomaka/winit#785) that's not apparently an issue.

What exactly is stopping us from figuring out the font metrics before actually creating a window at this point?
If there is something, could the one with that knowledge also follow up in tomaka/winit#785?

**Comment by chrisduerr** [comment] 2019-04-13 01:45
>  If you set the configuration file to a given terminal size in cols/lines (e.g my preferred ratio of 90/27) it still resizes down.

If you set window dimensions and the DPI factor is not equal to 1, it's impossible not to resize at startup.

> The original comment by @jwilm suggests that the issue is with lack of API support within glutin, but as per the two bugs above (tomaka/glutin#1096 and tomaka/winit#785) that's not apparently an issue.

The issue is exactly what vberger has said in the winit issue. It's pointless that we're able to get the DPI for all displays when we do not know which display the window is going to be spawned on.

**Comment by 5paceToast** [comment] 2019-04-13 01:52
At this point, I think the question becomes "how do other terminals handle it?"
I don't experience the same problems in, say, Konsole.
All of my displays (at least at home) have a non-1 DPI factor, but all of my displays per-system also have identical DPI factors (same-size displays with same resolution in all multi-display setups).
Surely there's some way for alacritty to handle these common scenarios with equal grace to virtually every other alternative?

**Comment by chrisduerr** [comment] 2019-04-13 16:33
@5paceToast I've updated the PR to guess the DPI based on the first monitor available in the monitor list. This should prevent even more resizes at startup. Now the only condition where it will resize is when you have multi-DPI setup, specify dimensions and the DPI guess is incorrect.

Honestly this was a lot more complex than I would have liked, but now that I've already done the work it seems reasonable to include this. However I don't think there's anything left to do if this doesn't do the job.

I'd appreciate some feedback if this works for you, I've marked it to close this PR so let me know if it still doesn't help.

**Comment by 5paceToast** [comment] 2019-04-13 17:20
@chrisduerr fixes it entirely on my laptop.
Can't verify on my office system (not being in the office or anything), but I doubt it'd be any different.
Tried to build on my windows setup, but the build fails (not alacritty's fault, I think my rust setup is broken there).

I'll comment here if I run into further problems on either of the remaining two systems above.
If you don't hear from me it's because this UX issue is solved (at least on my end)!

P.S. I would have preferred if there was a simpler solution as well, but UX problems are pretty important in terminal emulators :/

**Closed** 2019-04-14 15:37 UTC
Labels: B - bug
