### ISSUE TITLE
Drawing freeze on Debian stretch

### ISSUE THREAD

**Issue by juggle-tux** [jwilm/alacritty#2732] opened 2019-08-19 20:47 UTC
Which operating system does the issue occur on?
Debian GNU/Linux 9.9 (stretch)
and all previews version of stretch i used

If on linux, are you using X11 or Wayland?
X11 + i3wm

I use alacritty now quite a while (since way before the scroll back).
and since the beginning i have a odd problem, hard to reproduce, but
appearing at least once a day (of the days i use my computer).

**The problem:**

The output freezes at a random point (the drawing on screen but nothing more)
until i at least hover the mouse over the alacritty tail.

**Last seen on**

alacritty 0.3.3 (a869298)

**To reproduce (really hard):**

let any program with continues output (apt upgrade, rustup update or even tree sometimes)
running and don't do any think (the mouse don't crosses over the alacritty tail and no
key is pressed in the active window).

**Why did i not report it more early**

Short answer i travel a lot have not often internet.
So don't think i can replay a lot to the issue. **Sorry**!

**Comment by kchibisov** [comment] 2019-08-19 21:23
Your issue is a duplicate of #2217. There is a PR(#2438) that aims to solve this problem, it's quite usable from my testing experience. If you don't mind, you could try running it.

**Closed** 2019-08-19 21:55 UTC
Labels: F - duplicate

**Comment by juggle-tux** [comment] 2019-08-19 22:01
oh didn't saw that issue sry.
will now try
`git clone https://github.com/chrisduerr/alacritty.git -b evlp2 ala-fix`

**Comment by chrisduerr** [comment] 2019-08-19 22:05
@juggle-tux If you have any feedback, please let us know in the PR. I think we should be able to merge this into master soon hopefully.
