### ISSUE TITLE
Alacritty stops responding when opening OSX emoji panel

### ISSUE THREAD

**Issue by hhsnopek** [jwilm/alacritty#467] opened 2017-03-07 16:34 UTC
## Description
Upon opening the OSX emoji panel, alacritty becomes non-responsive.

## Steps to reproduce
1. Open alacritty (HEAD)
2. Open emoji panel `ctrl + cmd ⌘ + space`

## Emoji Panel
![](https://cldup.com/biKjYiIE02.png)

**Comment by jwilm** [comment] 2017-03-07 19:05
Thanks for the report! This is the first reliable repro we've had for a bug in the macOS event loop in glutin :D

**Comment by casey** [comment] 2017-03-09 05:47
I think this is a dupe of #411

**Comment by hlieberman** [comment] 2017-04-01 18:34
Closing in favor of #411.

**Closed by hlieberman** 2017-04-01 18:34 UTC
