### ISSUE TITLE
URL detection should work for local, absolute paths

### ISSUE THREAD

**Issue by sts10** [jwilm/alacritty#2447] opened 2019-05-16 12:49 UTC
It'd be cool if local absolute paths, like `/Users/sschlinkert/Documents/code/reports/` could be command-clicked like URLs, and open in user's file manager. iTerm2 has this feature, and I find it useful. 

Which operating system does the issue occur on?
MacOS 10.11.6

**Comment by chrisduerr** [comment] 2019-05-16 16:41
I'm not so sure how I feel about the idea of making every path a URL.

There are a lot of paths in terminal emulators and I think that making all of them clickable would definitely be annoying with the mouse cursor constantly changing and all of them getting underlined.

Another problem is that while URLs are fairly easy to identify (start with http:// or https://), it's extremely difficult to clearly identify paths without false positives. And having just URLs everywhere after compiling a file would certainly be a bit annoying.

The syntax `file:///home/user/path` is already supported, which I think is a much clearer and more useful way to make paths clickable, since it does not come with the same troubles that clicking normal paths has.

**Comment by chrisduerr** [comment] 2019-05-16 16:43
Closing this as a duplicate of https://github.com/jwilm/alacritty/issues/2051, there's a lot more discussion there for anyone interested.

**Closed by chrisduerr** 2019-05-16 16:43 UTC

**Comment by sts10** [comment] 2019-05-16 16:56
Ah, ok. Didn't know about the `file:///...` syntax being supported. Think that solves my particular snag. And apologies for not finding #2051 before creating this issue.

**Comment by chrisduerr** [comment] 2019-05-16 17:03
No worries! Always better to have two issues than none!

**Comment by dicktyr** [comment] 2021-01-07 04:39
please reopen as this is not a duplicate of #2051
(this refers specifically to *local absolute file paths*)

lets not confuse decoration with function

i.e. enabling local absolute paths to be used as a unit
by a simple mouse- or key-binding is indeed very useful
if not an unconditional requirement for some users
and it need not change the appearance

indeed url appearance is another issue #4669
