### ISSUE TITLE
Alacritty not updating when no input is happening

### ISSUE THREAD

**Issue by zethra** [jwilm/alacritty#2345] opened 2019-04-22 13:25 UTC
When not activity interacting with the alacritty window it will sometime stop redrawing the terminal until user input is received.  For instance when wait for code to build the output would seem to freeze until I attempt to scroll, then all the new text would appear at once.

Which operating system does the issue occur on?
Linux, Elementary OS
(Not happening on my Manjaro machine)

If on linux, are you using X11 or Wayland?
X11

**Comment by chrisduerr** [comment] 2019-04-22 13:47
This is a duplicate of https://github.com/jwilm/alacritty/issues/2217.

**Closed by chrisduerr** 2019-04-22 13:47 UTC

**Comment by drrossum** [comment] 2019-10-04 11:50
I just switched from Wayland back to X11 and this issue now hits me as well. This was no issue under Wayland, only under X11 (xlib) apparently.

I'm on version 0.3.3.

**Comment by nixpulvis** [comment] 2019-10-07 00:23
@drrossum master should have a fix for this now that #2438 has landed. You could give that a shot, or wait for the upcoming release of 0.3.4.
