### ISSUE TITLE
Unhandled CSI

### ISSUE THREAD

**Issue by ivegotasthma** [jwilm/alacritty#857] opened 2017-10-22 13:46 UTC
Which operating system does the issue occur on?
Arch Linux

If on linux, are you using X11 or Wayland?
X11

I'm getting a bunch of unhandled CSI characters. I compiled master just now.

```
asthma@dev ~ $ alacritty 
[Unhandled CSI] action='h', args=[34], intermediates=[]
[Unhandled CSI] action='l', args=[1005], intermediates=[63]
[Unhandled CSI] action='l', args=[34], intermediates=[]
[Unhandled CSI] action='h', args=[34], intermediates=[]
[Unhandled CSI] action='l', args=[1003], intermediates=[63]
[Unhandled CSI] action='h', args=[34], intermediates=[]
[Unhandled CSI] action='l', args=[34], intermediates=[]
[Unhandled CSI] action='h', args=[34], intermediates=[]
[Unhandled CSI] action='l', args=[1003], intermediates=[63]
[Unhandled CSI] action='h', args=[34], intermediates=[]
[Unhandled CSI] action='h', args=[34], intermediates=[]
^ this 50 times more
```

**Comment by mgsloan** [comment] 2018-01-14 23:29
Ran into this too on X11, Ubuntu 17.10

Something deeper and unexpected is going on, though, because I'm also getting "GL context creation failed".  glxgears fails with

```
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  28
  Current serial number in output stream:  29
```

I haven't changed my system setup much.  Going to try a reboot to see if it relie

**Comment by huttli** [comment] 2018-04-03 00:01
Got the same on my XWayland on Ubuntu 17.10.

It happens when I press and hold the key. I use that constantly in Vim for moving the cursor a few steps away towards one direction. It is not specific to Vim. In a shell prompt, if I press and hold a letter key, I get only one letter on the input, not the usual continuous key input events.

It works if I release the key and press it again, which gives me two key events.

**Comment by chrisduerr** [comment] 2018-07-16 11:36
I doubt these errors are related to the crashing. This usually just indicates a terminal feature which is not supported by Alacritty yet, it's unlikely that Alacritty not doing something would crash it. However nothing's impossible :D.

It's hard to troubleshoot an issue like this if you're not able to reproduce it when running Alacritty from another terminal instance, however I'd recommend discussing this in a separate issue if you would like to investigate more.

**Comment by expectocode** [comment] 2018-07-16 12:08
Yeah, strange. I'm happy to leave it, though, it doesn't happen often. Thanks for the prompt reply to my weird bug :)

**Comment by chrisduerr** [comment] 2019-03-08 01:07
Closing this as it is not about any specific escapes necessary to work properly. This was originally just debug output and the log level has been changed to represent that.

If there should be any escape sequences necessary to make something work, opening a separate issue for that sequence explicitly is the way to go.

**Closed by chrisduerr** 2019-03-08 01:07 UTC
