### ISSUE TITLE
Issues with pinned Dock icon in OSX

### ISSUE THREAD

**Issue by mscharley** [jwilm/alacritty#628] opened 2017-06-20 10:15 UTC
I've been having issues with Alacritty pinned to the Dock in OSX. Some of the time it will open a second icon instead of using the pinned icon. It seems to be pretty non-deterministic so I think there's a timing issue here. Based on the animations it seems it may be going through the loading sequence twice for each launch (the icon does half a bounce then starts again).

**Comment by tbodt** [comment] 2017-07-13 20:33
The cause of this is alacritty using a launcher script. I'm working on a PR to do everything the launcher script is doing in alacritty itself.

**Comment by tbodt** [comment] 2017-07-13 20:59
#661

**Comment by sodiumjoe** [comment] 2018-03-29 07:09
looks like this was fixed by #879 and can be closed

**Comment by chrisduerr** [comment] 2018-03-29 13:33
Closing it for now because @sodiumjoe says it should be fixed. If it's still an issue, feel free to reopen this.

**Closed by chrisduerr** 2018-03-29 13:33 UTC
Labels: H - macos, S - packaging
