### ISSUE TITLE
Crash when opening '\xef\xbb\xbf' in vis

### ISSUE THREAD

**Issue by milhnl** [jwilm/alacritty#1894] opened 2018-12-12 12:03 UTC
OS: Windows
Rust version: stable
alacritty version: latest master (217ad9ec285b4923de1790b0976c8c793039c994), built with debug

Alacritty crashes when opening a specific file in the `vis` editor (also current latest master). Opening the file in `vim` or displaying it with `cat` does not crash alacritty. How to reproduce:

  - Start alacritty (no config file)
  - `printf '\xef\xbb\xbf' > crash.txt`
  - `vis crash.txt`

####Stack trace

    thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore\option.rs:355:21
    stack backtrace:
       0: std::sys::windows::backtrace::set_frames
                 at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\sys\windows\backtrace\mod.rs:104
       1: std::sys::windows::backtrace::set_frames
                 at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\sys\windows\backtrace\mod.rs:104
       2: std::sys_common::backtrace::_print
                 at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\sys_common\backtrace.rs:71
       3: std::sys_common::backtrace::_print
                 at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\sys_common\backtrace.rs:71
       4: std::panicking::default_hook::{{closure}}
                 at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\panicking.rs:211
       5: std::panicking::default_hook
                 at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\panicking.rs:227
       6: std::panicking::rust_panic_with_hook
                 at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\panicking.rs:476
       7: std::panicking::continue_panic_fmt
                 at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\panicking.rs:390
       8: std::panicking::rust_begin_panic
                 at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\panicking.rs:325
       9: core::panicking::panic_fmt
                 at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libcore\panicking.rs:77
      10: core::panicking::panic
                 at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libcore\panicking.rs:52
      11: core::option::Option<(usize, stb_truetype::{{impl}}::glyph_shape_positive_contours::FlagData)*>::unwrap<(usize, stb_truetype::{{impl}}::glyph_shape_positive_contours::FlagData)*>
                 at \libcore\macros.rs:20
      12: stb_truetype::FontInfo<rusttype::SharedBytes>::glyph_shape_positive_contours<rusttype::SharedBytes>
                 at .\.cargo\registry\src\github.com-1ecc6299db9ec823\stb_truetype-0.2.4\src\lib.rs:911
      13: stb_truetype::FontInfo<rusttype::SharedBytes>::get_glyph_shape<rusttype::SharedBytes>
                 at .\.cargo\registry\src\github.com-1ecc6299db9ec823\stb_truetype-0.2.4\src\lib.rs:655
      14: rusttype::PositionedGlyph::draw<closure>
                 at .\.cargo\registry\src\github.com-1ecc6299db9ec823\rusttype-0.4.3\src\lib.rs:786
      15: font::rusttype::{{impl}}::get_glyph
                 at .\alacritty\font\src\rusttype\mod.rs:122
      16: alacritty::renderer::{{impl}}::get::{{closure}}<alacritty::renderer::RenderApi>
                 at .\alacritty\src\renderer\mod.rs:276
      17: std::collections::hash::map::Entry<font::GlyphKey, alacritty::renderer::Glyph>::or_insert_with<font::GlyphKey,alacritty::renderer::Glyph,closure>
                 at \libstd\collections\hash\map.rs:2120
      18: alacritty::renderer::GlyphCache::get<alacritty::renderer::RenderApi>
                 at .\alacritty\src\renderer\mod.rs:273
      19: alacritty::renderer::RenderApi::render_cells<core::slice::Iter<alacritty::term::RenderableCell>>
                 at .\alacritty\src\renderer\mod.rs:906
      20: alacritty::display::{{impl}}::draw::{{closure}}
                 at .\alacritty\src\display.rs:421
      21: alacritty::renderer::QuadRenderer::with_api<closure,()>
                 at .\alacritty\src\renderer\mod.rs:684
      22: alacritty::display::Display::draw
                 at .\alacritty\src\display.rs:419
      23: alacritty::run
                 at .\alacritty\src\main.rs:244
      24: alacritty::main
                 at .\alacritty\src\main.rs:79
      25: std::rt::lang_start::{{closure}}<()>
                 at \libstd\rt.rs:74
      26: std::rt::lang_start_internal::{{closure}}
                 at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\rt.rs:59
      27: std::rt::lang_start_internal::{{closure}}
                 at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\rt.rs:59
      28: panic_unwind::__rust_maybe_catch_panic
                 at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libpanic_unwind\lib.rs:102
      29: std::panicking::try
                 at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\panicking.rs:289
      30: std::panicking::try
                 at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\panicking.rs:289
      31: std::panicking::try
                 at /rustc/abe02cefd6cd1916df62ad7dc80161bea50b72e8\src/libstd\panicking.rs:289
      32: std::rt::lang_start<()>
                 at \libstd\rt.rs:74
      33: main
      34: invoke_main
                 at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
      35: invoke_main
                 at d:\agent\_work\3\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
      36: BaseThreadInitThunk
      37: RtlUserThreadStart

I'd be happy to help, but I don't have any experience with Rust.

**Comment by chrisduerr** [comment] 2018-12-12 13:53
@milhnl Does Alacritty also crash when just echoing that character? I'm unsure why this would be related to `vis`. Based on the backtrace, it looks like a font error, I'd say it can't draw the glyph.

This should hopefully be resolved by #1568.

**Comment by milhnl** [comment] 2018-12-12 16:50
@chrisduerr It doesn't crash when just running `printf '\xef\xbb\xbf'`, so no. Also not with vim. I don't think it really has anything to do with vis, but it is the only way I can reproduce the issue.

I also checked out the fontkit branch from #1568 (62a066f866ad41e4ae428e44b2a979f76cabfa47), built it with `cargo build`, and it crashes with the same backtrace. Should I comment on his PR, create an issue on his fork, or continue here?

PS: I checked out the branch fontkit from his fork, and ran `cargo build`. Is there some feature flag I have to turn on to actually test the fontkit feature?

**Comment by jabagawee** [comment] 2018-12-12 21:44
Looks similar to #1674

**Comment by chrisduerr** [comment] 2018-12-12 22:33
Closing as duplicate of #1674 for now. If this isn't resolved once that's closed, we can re-consider.

**Closed by chrisduerr** 2018-12-12 22:33 UTC
Labels: H - windows, S - font

**Comment by milhnl** [comment] 2018-12-13 14:00
I actually tried to reproduce the initial `protonmail_gray.txt` crash from that issue before creating this issue. Didn't crash. The [version](https://github.com/jwilm/alacritty/issues/1674#issuecomment-446750679) @jabagawee posted does. So I think this issue is indeed a duplicate. Thanks for helping! I'll continue testing!
