### ISSUE TITLE
Support for Alt+key (option as meta)

### ISSUE THREAD

**Issue by k-bx** [jwilm/alacritty#93] opened 2017-01-06 20:13 UTC
I'm actually on macOS and not sure how to correctly describe the issue from technical side.

When in terminal, you can go forward/backward by pressing ctrl+f/ctrl+b and it works in Alacritty, and usually you can jump between words by pressing alt(option)+f/alt(option)+b, but it doesn't work right now.

**Comment by rspeer** [comment] 2017-01-06 21:42
I don't know if this is relevant, but I notice that on Linux, alt+Left and alt+Right are working for me, and serving their purpose of switching windows in tmux. Does macOS's Option key send a different key code?

**Comment by dannydulai** [comment] 2017-01-07 00:04
I use alt-hjkl in vim, so I found this limiting as well.

I solved it by adding this to my config:

```
  - { key: J,        mods: Alt,     chars: "\x1bj"                       }
  - { key: K,        mods: Alt,     chars: "\x1bk"                       }
  - { key: H,        mods: Alt,     chars: "\x1bh"                       }
  - { key: L,        mods: Alt,     chars: "\x1bl"                       }
```

**Comment by cmyr** [comment] 2017-01-07 23:35
I'm also seeing alt not being correctly passed on macOS. I have a bunch of alt+key bindings in vim, but also the alt+b / alt+f bash/readline commands don't work.

**Comment by dannydulai** [comment] 2017-01-08 03:08
@cmyr  -- did you try my above bindings? they work for me on MacOS.

**Comment by jwilm** [comment] 2017-01-09 01:04
I just pushed a branch `alt-key-tester`. Would you guys mind trying it without the bindings and sharing the log?

**Comment by cmyr** [comment] 2017-01-09 17:25
@dannydulai your config works, thanks!

@jwilm:

Here's the console output for a few alt+keys on your new branch without the binidings. I'm getting the macOS default special characters.

```process_key got string="˙", mods=ALT, key=Some(H)
process_key sending "˙"
process_key got string="¬", mods=ALT, key=Some(L)
process_key sending "¬"
process_key got string="∆", mods=ALT, key=Some(J)
process_key sending "∆"
process_key got string="˚", mods=ALT, key=Some(K)
process_key sending "˚"
process_key got string="†", mods=ALT, key=Some(T)
process_key sending "†"
process_key got string="¥", mods=ALT, key=Some(Y)
process_key sending "¥"```

**Comment by jwilm** [comment] 2017-01-09 17:42
Oh, right... hmm. I can see one easy solution to this, but then you wouldn't be able to send the special characters. Does iTerm not allow you to send those special characters?

**Comment by dannydulai** [comment] 2017-01-09 19:22
In Terminal.app, I get the funny chars by default unless I turn on the checkbox for "Use Option as Meta key". Once done, then I see ^[[<char>

**Comment by jwilm** [comment] 2017-01-09 20:31
Ah cool; sounds like this is a config issue then.

**Comment by jra** [comment] 2017-01-19 18:00
Me too! I want Meta, not the special characters. What is the easy solution? Is there something I can drop into the config file?

**Comment by casey** [comment] 2017-02-20 02:47
Is this issue actually a dupe of #62?

I think that fixing #62 would fix this, although I may be missing something.

**Comment by rafi** [comment] 2017-02-20 17:06
Has anyone been able to map <kbd>Ctrl</kbd>+<kbd>6</kbd>? I use it a lot in Vim but am not able to use it with Alacritty. I've tried:
```yml
- { key: Key6,     mods: Control, chars: "\x1b[27;5;54~" }
```

**Comment by joshuarubin** [comment] 2017-03-28 18:15
I am able to use the Alt key (MacOS) with a line like:

```
{ key: P,  mods: Alt,           chars: "\x1bp"                       }
```

However, using the Alt key without an explicit mapping like that, e.g. `<alt>i`, causes Alacritty to peg the cpu to 100% and become unresponsive.

**Comment by nanzhong** [comment] 2017-06-07 13:05
Similar to what @dannydulai suggested, if you use a different keyboard layout (eg. dvorak) you will need to map the keys to their qwerty equivalent.

For dvorak:
```
  - { key: N,        mods: Alt,     chars: "\x1bb"                       }
  - { key: Y,        mods: Alt,     chars: "\x1bf"                       }
```

**Comment by lambdalisue** [comment] 2017-07-04 01:39
@rafi 

```
  - { key: Key6,     mods: Control, chars: "\x1e"                        }
```

Works for me on macOS.

**Comment by jedahan** [comment] 2017-10-06 15:35
With latest alacritty and tmux, I finally got forward and backward movement with the following: 

```js
- { key: F,  mods: Alt,           chars: "\x1bf"                       }
- { key: B,  mods: Alt,           chars: "\x1bb"                       }
```

**Comment by meain** [comment] 2017-11-02 10:02
How to add alt + number keymaps?

**Comment by yqrashawn** [comment] 2017-12-22 00:10
@meain I solved by adding these configurations.
```
  - { key: Key0, mods: Alt, chars: "\x1b0" }
  - { key: Key1, mods: Alt, chars: "\x1b1" }
  - { key: Key2, mods: Alt, chars: "\x1b2" }
  - { key: Key3, mods: Alt, chars: "\x1b3" }
  - { key: Key4, mods: Alt, chars: "\x1b4" }
  - { key: Key5, mods: Alt, chars: "\x1b5" }
  - { key: Key6, mods: Alt, chars: "\x1b6" }
  - { key: Key7, mods: Alt, chars: "\x1b7" }
  - { key: Key8, mods: Alt, chars: "\x1b8" }
  - { key: Key9, mods: Alt, chars: "\x1b9" }
```

**Comment by meain** [comment] 2017-12-22 02:54
That works, thank you @yqrashawn

**Comment by radiosilence** [comment] 2018-05-02 10:34
On OSX do this:
```
  - { key: Up,       mods: Alt,     chars: "\x1b[1;5A"                   }
  - { key: Down,     mods: Alt,     chars: "\x1b[1;5B"                   }
  - { key: Left,     mods: Alt,     chars: "\x1bb"                       }
  - { key: Right,    mods: Alt,     chars: "\x1bf"                       }
```

```
  - { key: Key0,     mods: Alt,     chars: "º"                           }
  - { key: Key1,     mods: Alt,     chars: "¡"                           }
  - { key: Key2,     mods: Alt,     chars: "€"                           }
  - { key: Key3,     mods: Alt,     chars: "#"                           }
  - { key: Key4,     mods: Alt,     chars: "¢"                           }
  - { key: Key5,     mods: Alt,     chars: "∞"                           }
  - { key: Key6,     mods: Alt,     chars: "§"                           }
  - { key: Key7,     mods: Alt,     chars: "¶"                           }
  - { key: Key8,     mods: Alt,     chars: "•"                           }
  - { key: Key9,     mods: Alt,     chars: "ª"                           }
```

**Comment by frontsideair** [comment] 2018-05-17 10:03
@jedahan your solution worked for me, since you're the author would you like to make a PR to add it to default config? If you'd rather not, I can do it. Thanks!

**Comment by justinmk** [comment] 2018-05-17 10:48
For reference, kitty solved this natively: https://github.com/kovidgoyal/kitty/search?q=alt+macos&type=Commits

**Comment by chrisduerr** [comment] 2018-09-28 08:51
Closing this as a duplicate of #62. Looks like that issue should resolve this one too.

**Closed by chrisduerr** 2018-09-28 08:51 UTC
Labels: B - bug, H - macos, S - input, S - winit/glutin

**Comment by adc17** [comment] 2018-10-06 17:28
In case anyone landing here also wants the forward-delete binding, it's this:
```
- { key: D,  mods: Alt,           chars: "\x1bd"                       }

**Comment by ipatch** [comment] 2018-10-14 18:43
Didn't really see it mentioned above, and have made it back to this thread a couple of times now, but if anyone wanting to setup meta key bindings, ie. <kbd>alt</kbd> + <kbd>[ALPHA_KEY]</kbd>, as far as I can tell, any of the alpha keys on the keyboard can be used, i.e **A** through **z**.  All that is required is to do something like,

**alacritty.yml**

```
key_bindings:
- { key: [ALPHA_KEY],        mods: Alt,     chars: "\x1b[ALPHA_KEY]"                       }
```

> Substitute `[ALPHA_KEY]` with a key of **A** through **z** on the keyboard. 

**Ex**

```
key_bindings:
- { key: Q,        mods: Alt,     chars: "\x1bq"                       }
```

The example above adds a keybinding for <kbd>alt</kbd> + <kbd>q</kbd>

I hope this note helps future me. 🙋‍♂️

**Comment by iugo-eric** [comment] 2019-05-17 19:09
This was closed spuriously. Read the title. "**option as meta**". Option still does not work as meta. Therefore the issue is still open.

**Comment by chrisduerr** [comment] 2019-05-17 19:11
This was closed as a duplicate, not as resolved.

**Comment by mbigras** [comment] 2019-10-18 05:54
Using:

* https://github.com/jwilm/alacritty/issues/93#issuecomment-334790547
* https://github.com/jwilm/alacritty/issues/93#issuecomment-427592040
* https://godoc.org/github.com/tiborvass/uniline/ansi#Code

Helped me get the forward and backward movement and the delete forward one word ability I wanted. These are the relevant sections of my `~/.config/alacritty/alacritty.yml` file:

```
  # https://godoc.org/github.com/tiborvass/uniline/ansi#Code
  # https://github.com/jwilm/alacritty/issues/93#issuecomment-334790547
  - { key: F,  mods: Alt,           chars: "\x1bf"                       }
  - { key: B,  mods: Alt,           chars: "\x1bb"                       }
  # https://github.com/jwilm/alacritty/issues/93#issuecomment-427592040
  - { key: D,  mods: Alt,           chars: "\x1bd"                       }
```

**Comment by manu0600** [comment] 2020-09-25 08:18
Hi, i'm having difficulties with Alt+numbers : I have a french keyboard, and when I do Alt+key[0-9], some of them are seen as normal keys (without alt). On the french keyboard, the numbers require shift, and the normal keys are : &,é,",',(,§,è,!,ç,à .
Here is a screenshot of each Alt+key with Xterm (which works as intended) and Alacritty (which misses a few of them) : 
![Screenshot](https://user-images.githubusercontent.com/35146118/94243603-e9333780-ff17-11ea-9049-0f4ad39ad637.png)
Can you help me figure out what to put in the config file to make it work ?
I tried yqrashawn's answer, but it didn't change anything for me.

Thank you

**Comment by ncfavier** [comment] 2021-02-12 13:40
I have the same issue as @manu0600 .

**Comment by paxperscientiam** [comment] 2021-06-23 20:23
> @meain I solved by adding these configurations.
> 
> ```
>   - { key: Key0, mods: Alt, chars: "\x1b0" }
>   - { key: Key1, mods: Alt, chars: "\x1b1" }
>   - { key: Key2, mods: Alt, chars: "\x1b2" }
>   - { key: Key3, mods: Alt, chars: "\x1b3" }
>   - { key: Key4, mods: Alt, chars: "\x1b4" }
>   - { key: Key5, mods: Alt, chars: "\x1b5" }
>   - { key: Key6, mods: Alt, chars: "\x1b6" }
>   - { key: Key7, mods: Alt, chars: "\x1b7" }
>   - { key: Key8, mods: Alt, chars: "\x1b8" }
>   - { key: Key9, mods: Alt, chars: "\x1b9" }
> ```

Sweet. Thank you! It works!

**Comment by alexchaichan** [comment] 2022-01-27 22:26
Hey, I'm still struggeling maping the 

Alt + (5,6,7,8,9) and Alt + Shift + 7 keys.

for example alt +5 is mapped to `^[[`

I'm trying like this:

`- { key: Key6, mods: Alt,     chars: "\x5d"  }` #for ]
`- { key: Key7, mods: Alt|Shift,     chars: "\x20\x5c"  }` # for \

etc...

but without succes :/

Anyone a solution?

**Comment by sultanahamer** [comment] 2022-01-29 19:04
@k-bx  and others here is some solution that might help you.

https://github.com/alacritty/alacritty/issues/4048#issuecomment-1024966230

**Comment by jaohaohsuan** [comment] 2022-03-12 21:11
For the `alt` + `.`,   the following setting works for me on my macOS. 
```
key_bindings:
  - { key: Period, mods: Alt, chars: "\e." }
```

**Comment by reverseila** [comment] 2022-03-21 02:45
for having the behavior of Alt-backspace in browsers:

```yaml
  - { key: Back,            mods: Alt,           chars: "\x1b\x7f"            }
```

source: [#315 (comment)](https://github.com/alacritty/alacritty/issues/315#issuecomment-279191383)

**Comment by augustfengd** [comment] 2022-08-07 14:43
I needed this to be able to use `C-space` as a prefix in tmux:
```yaml
key_bindings:
# ...
  - { key: Space, mods: Control, chars: "\x00" }
```

**Comment by baggiponte** [comment] 2022-11-19 14:31
Hi, sorry to necrobump this. The solution is that we should manually re-map every alt + any-other-char we want to use?

**Comment by chrisduerr** [comment] 2022-11-19 14:38
#62.

**Comment by otavioschwanck** [comment] 2022-12-26 01:17
For alacritty users:

```
  - { key: A,         mods: Alt,       chars: "\x1ba"                       }
  - { key: B,         mods: Alt,       chars: "\x1bb"                       }
  - { key: C,         mods: Alt,       chars: "\x1bc"                       }
  - { key: D,         mods: Alt,       chars: "\x1bd"                       }
  - { key: E,         mods: Alt,       chars: "\x1be"                       }
  - { key: F,         mods: Alt,       chars: "\x1bf"                       }
  - { key: G,         mods: Alt,       chars: "\x1bg"                       }
  - { key: H,         mods: Alt,       chars: "\x1bh"                       }
  - { key: I,         mods: Alt,       chars: "\x1bi"                       }
  - { key: J,         mods: Alt,       chars: "\x1bj"                       }
  - { key: K,         mods: Alt,       chars: "\x1bk"                       }
  - { key: L,         mods: Alt,       chars: "\x1bl"                       }
  - { key: M,         mods: Alt,       chars: "\x1bm"                       }
  - { key: N,         mods: Alt,       chars: "\x1bn"                       }
  - { key: O,         mods: Alt,       chars: "\x1bo"                       }
  - { key: P,         mods: Alt,       chars: "\x1bp"                       }
  - { key: Q,         mods: Alt,       chars: "\x1bq"                       }
  - { key: R,         mods: Alt,       chars: "\x1br"                       }
  - { key: S,         mods: Alt,       chars: "\x1bs"                       }
  - { key: T,         mods: Alt,       chars: "\x1bt"                       }
  - { key: U,         mods: Alt,       chars: "\x1bu"                       }
  - { key: V,         mods: Alt,       chars: "\x1bv"                       }
  - { key: W,         mods: Alt,       chars: "\x1bw"                       }
  - { key: X,         mods: Alt,       chars: "\x1bx"                       }
  - { key: Y,         mods: Alt,       chars: "\x1by"                       }
  - { key: Z,         mods: Alt,       chars: "\x1bz"                       }
  - { key: A,         mods: Alt|Shift, chars: "\x1bA"                       }
  - { key: B,         mods: Alt|Shift, chars: "\x1bB"                       }
  - { key: C,         mods: Alt|Shift, chars: "\x1bC"                       }
  - { key: D,         mods: Alt|Shift, chars: "\x1bD"                       }
  - { key: E,         mods: Alt|Shift, chars: "\x1bE"                       }
  - { key: F,         mods: Alt|Shift, chars: "\x1bF"                       }
  - { key: G,         mods: Alt|Shift, chars: "\x1bG"                       }
  - { key: H,         mods: Alt|Shift, chars: "\x1bH"                       }
  - { key: I,         mods: Alt|Shift, chars: "\x1bI"                       }
  - { key: J,         mods: Alt|Shift, chars: "\x1bJ"                       }
  - { key: K,         mods: Alt|Shift, chars: "\x1bK"                       }
  - { key: L,         mods: Alt|Shift, chars: "\x1bL"                       }
  - { key: M,         mods: Alt|Shift, chars: "\x1bM"                       }
  - { key: N,         mods: Alt|Shift, chars: "\x1bN"                       }
  - { key: O,         mods: Alt|Shift, chars: "\x1bO"                       }
  - { key: P,         mods: Alt|Shift, chars: "\x1bP"                       }
  - { key: Q,         mods: Alt|Shift, chars: "\x1bQ"                       }
  - { key: R,         mods: Alt|Shift, chars: "\x1bR"                       }
  - { key: S,         mods: Alt|Shift, chars: "\x1bS"                       }
  - { key: T,         mods: Alt|Shift, chars: "\x1bT"                       }
  - { key: U,         mods: Alt|Shift, chars: "\x1bU"                       }
  - { key: V,         mods: Alt|Shift, chars: "\x1bV"                       }
  - { key: W,         mods: Alt|Shift, chars: "\x1bW"                       }
  - { key: X,         mods: Alt|Shift, chars: "\x1bX"                       }
  - { key: Y,         mods: Alt|Shift, chars: "\x1bY"                       }
  - { key: Z,         mods: Alt|Shift, chars: "\x1bZ"                       }
  - { key: Key1,      mods: Alt,       chars: "\x1b1"                       }
  - { key: Key2,      mods: Alt,       chars: "\x1b2"                       }
  - { key: Key3,      mods: Alt,       chars: "\x1b3"                       }
  - { key: Key4,      mods: Alt,       chars: "\x1b4"                       }
  - { key: Key5,      mods: Alt,       chars: "\x1b5"                       }
  - { key: Key6,      mods: Alt,       chars: "\x1b6"                       }
  - { key: Key7,      mods: Alt,       chars: "\x1b7"                       }
  - { key: Key8,      mods: Alt,       chars: "\x1b8"                       }
  - { key: Key9,      mods: Alt,       chars: "\x1b9"                       }
  - { key: Key0,      mods: Alt,       chars: "\x1b0"                       }
  - { key: Space,     mods: Control,   chars: "\x00"                        } # Ctrl + Space
  - { key: Grave,     mods: Alt,       chars: "\x1b`"                       } # Alt + `
  - { key: Grave,     mods: Alt|Shift, chars: "\x1b~"                       } # Alt + ~
  - { key: Period,    mods: Alt,       chars: "\x1b."                       } # Alt + .
  - { key: Key8,      mods: Alt|Shift, chars: "\x1b*"                       } # Alt + *
  - { key: Key3,      mods: Alt|Shift, chars: "\x1b#"                       } # Alt + #
  - { key: Period,    mods: Alt|Shift, chars: "\x1b>"                       } # Alt + >
  - { key: Comma,     mods: Alt|Shift, chars: "\x1b<"                       } # Alt + <
  - { key: Minus,     mods: Alt|Shift, chars: "\x1b_"                       } # Alt + _
  - { key: Key5,      mods: Alt|Shift, chars: "\x1b%"                       } # Alt + %
  - { key: Key6,      mods: Alt|Shift, chars: "\x1b^"                       } # Alt + ^
  - { key: Backslash, mods: Alt,       chars: "\x1b\\"                      } # Alt + \
  - { key: Backslash, mods: Alt|Shift, chars: "\x1b|"                       } # Alt + |```

**Comment by aquilacf** [comment] 2023-01-13 10:57
Vim/Helix users might have noticed semicolon is not on that list:
```
  - { key: Semicolon, mods: Alt,       chars: "\x1b;"                       } # Alt + ;
```

**Comment by helmesjo** [comment] 2023-02-02 19:49
> Hi, sorry to necrobump this. The solution is that we should manually re-map every alt + any-other-char we want to use?

I skimmed through this and thought the same... Re-binding could be a fine _temporary_ workaround, but is there any reason it can't be fixed as in eg. ìterm2` (where you basically say "make `option` key behave like `alt`)?

**Comment by kchibisov** [comment] 2023-02-02 20:19
You've read through this you might find that the link issue was fixed.

**Comment by helmesjo** [comment] 2023-02-02 20:56
@kchibisov All I see is that you can rebind your way out of it.

**Comment by kchibisov** [comment] 2023-02-02 21:10
https://github.com/alacritty/alacritty/issues/93#issuecomment-425368538

**Comment by groteck** [comment] 2023-02-13 14:58
Sorry, can we reopen this issue since It is not working in my Computer, I have the mappings and doesn't matter opt+key is still interesting œ∑´®†¥¨ˆøπ“‘«åß∂ƒ©˙∆˚¬…æΩ≈ç√∫˜µ≤≥÷

**Comment by kchibisov** [comment] 2023-02-13 15:09
You need to use config option. Not sure what mappings you have.

**Comment by mokshadharma** [comment] 2023-02-13 18:37
The option key is still acting like option instead of ALT for me, despite having nothing in my `~.config/alacritty/alacritty.yml` except:
```
window:
  option_as_alt: Both
```

I'm using alacritty 0.11.0 (8dbaa0b) on macOS Ventura 13.2

**Comment by kchibisov** [comment] 2023-02-13 18:40
>I'm using alacritty 0.11.0 (https://github.com/alacritty/alacritty/commit/8dbaa0bbd308a72075910ff32d8ffcca09ae3529) on macOS Ventura 13.2

Ofc, you need alacritty from c82de4ccadcaf2e74dc8e8ef2da1ebe13e2ca5a9

**Comment by kchibisov** [comment] 2023-02-13 18:41
I'm locking the issue to avoid further spam.

For issues with the new option open another issue, but be sure that you've build alacritty that supports this settings first.
