### ISSUE TITLE
Ctrl-C does not work when using with alternative layouts (e.g. Dvorak)

### ISSUE THREAD

**Issue by aignas** [jwilm/alacritty#1917] opened 2018-12-20 11:47 UTC
Which operating system does the issue occur on? Mac, if I remember things correctly, this works on linux just fine.

If on linux, are you using X11 or Wayland?

Short description:
- When I am using the standard QWERTY layout, everything works fine.
- When using dvorak, Ctrl-C stops working

The config is here: https://github.com/aignas/dotfiles/blob/master/alacritty/alacritty.yml.symlink

**Comment by chrisduerr** [comment] 2018-12-20 13:15
Could you share the output of `alacritty --print-events` at the specific time you press ^C?

Also, just to make sure your keymap works properly, does Ctrl + the key that's C on QWERTY work with dvorak too? Does typing in dvorak work at all?

**Comment by aignas** [comment] 2018-12-21 11:56
`C` on QWERTY is `J` on Dvorak and I am not sure if I am not seeing any mixed behaviour, as the key does not behave exactly as it does when using Qwerty.

The output, when I am trying to type `Ctrl-C` in Dvorak:
```
❯ ./alacritty --print-events
Created log file at "/var/folders/53/13ph1xvn54scddtb7l6v38j40000gn/T/Alacritty-89400.log"
[2018-12-21 13:52] [INFO] Welcome to Alacritty.
[2018-12-21 13:52] [INFO] Configuration loaded from /Users/aignas/.config/alacritty/alacritty.yml
[2018-12-21 13:52] [INFO] device_pixel_ratio: 2
[2018-12-21 13:52] [INFO] width: 2048, height: 1536
[2018-12-21 13:52] [INFO] Initializing glyph cache
[2018-12-21 13:52] [INFO] Finished initializing glyph cache in 0.180827324
[2018-12-21 13:52] [INFO] width: 1040, height: 624
[2018-12-21 13:52] [INFO] Cell Size: (13 x 26)
[2018-12-21 13:52] [INFO] Padding: (0 x 0)
[2018-12-21 13:52] [INFO] PTY Dimensions: Line(24) x Column(80)
[2018-12-21 13:52] [INFO] Initialisation complete
[2018-12-21 13:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140311302084720)), event: HiDpiFactorChanged(2.0) }
[2018-12-21 13:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140311302084720)), event: Resized(LogicalSize { width: 1024.0, height: 768.0 }) }
[2018-12-21 13:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140311302084720)), event: Resized(LogicalSize { width: 520.0, height: 312.0 }) }
[2018-12-21 13:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140311302084720)), event: Moved(LogicalPosition { x: 208.0, y: 492.0 }) }
[2018-12-21 13:52] [INFO] Font size changed: Size(22) [DPR: 2]
[2018-12-21 13:52] [INFO] width: 1040, height: 624
[2018-12-21 13:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140311302084720)), event: Focused(true) }
[2018-12-21 13:52] [INFO] glutin event: Awakened
[2018-12-21 13:52] [INFO] glutin event: Awakened
[2018-12-21 13:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140311302084720)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Pressed, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
[2018-12-21 13:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140311302084720)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 34, state: Pressed, virtual_keycode: Some(I), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
[2018-12-21 13:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140311302084720)), event: ReceivedCharacter('\u{3}') }
[2018-12-21 13:52] [INFO] glutin event: Awakened
[2018-12-21 13:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140311302084720)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 34, state: Released, virtual_keycode: Some(I), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
[2018-12-21 13:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140311302084720)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 34, state: Pressed, virtual_keycode: Some(I), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
[2018-12-21 13:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140311302084720)), event: ReceivedCharacter('\u{3}') }
[2018-12-21 13:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140311302084720)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 34, state: Released, virtual_keycode: Some(I), modifiers: ModifiersState { shift: false, ctrl: true, alt: false, logo: false } } } }
[2018-12-21 13:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140311302084720)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 59, state: Released, virtual_keycode: Some(LControl), modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: false } } } }
[2018-12-21 13:52] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140311302084720)), event: Focused(false) }
```

**Comment by chrisduerr** [comment] 2018-12-21 12:11
First of all, just to make sure, you're using Ctrl+Shift+C, right? Not just Ctrl+C? Alacritty doesn't bind copying to Ctrl+C by default since that's usually sending a `SIGINT` signal.

If Ctrl+Shift+C doesn't work, you should remap the key binding in your config to Ctrl+Shift+I. Looking at the output of `--print-events`, it looks like the `I` key is reported to Alacritty for you.

**Comment by aignas** [comment] 2018-12-26 14:46
Sorry for the delay in replying. I don't mean to use `Ctrl-c` for copying, I mean `Ctrl-c` for doing the keyboard interrupt to exit a program. When I press `Ctrl-c` in Dvorak (Physical `Ctrl-i`), alacritty missinterprets it as `Ctrl-i` and not `Ctrl-c`. However, TMUX is receiving the correct key combination when using the prefix (`Ctrl-b` in my case).

Since I am using Dvorak and QWERTY interchangably (Dvorak with the laptop keyboard, QWERTY with external keyboards), it means that alacritty only works as intended when using an external keyboard.

**Comment by chrisduerr** [comment] 2018-12-26 15:17
Looks like this is a duplicate of https://github.com/jwilm/alacritty/issues/458. That issue mostly mentions the `Command` key, but it should still be the same issue.

**Closed by chrisduerr** 2018-12-26 15:17 UTC
Labels: H - macos, S - input
