### ISSUE TITLE
Swapping modifier keys

### ISSUE THREAD

**Issue by aste4** [jwilm/alacritty#2738] opened 2019-08-21 16:01 UTC
Mac OS - Is there a way to swap the modifier keys i.e make Ctrl behave like Command, and make Comand behave like Ctrl? I know that it is possible to remap those keys system wide but I would rather not do that. 

iterm2 has this feature. I don't think this is possible in alacritty right now but it would be a great feature. 

Thank you.

**Comment by chrisduerr** [comment] 2019-08-21 18:20
This is a duplicate of https://github.com/jwilm/alacritty/issues/62.

**Closed by chrisduerr** 2019-08-21 18:20 UTC
