### ISSUE TITLE
using a composite manager makes background transparent

### ISSUE THREAD

**Issue by diefans** [jwilm/alacritty#1195] opened 2018-03-19 16:00 UTC
Which operating system does the issue occur on?
Ubuntu 16.04, awesome wm

If on linux, are you using X11 or Wayland?
I use X11

If I run one of `compton`, `xcompmgr` or `unagi` the background of an alacritty window gets transparent.

**Comment by chrisduerr** [comment] 2018-03-19 16:33
This should only be the case if you've setup your composite manager to make windows transparent.

I'm using `compton` myself and it seems to work just as intended.

**Comment by jwilm** [comment] 2018-03-19 16:57
This sounds like it's working as intended?

**Comment by diefans** [comment] 2018-03-19 19:59
To clarify: in my setup no focused windows get an opacity of 0.85, while focused get 1.0. All other windows work as expected - they get semi transparent when not focused. Alacrity windows behave always the same way: their background is transparent==opacity of 0.0, foreground color is always the same focused or not focused.

**Comment by maximbaz** [comment] 2018-03-19 20:34
Could you share the relevant bits of `.compton.conf` to help reproducing this?

**Comment by diefans** [comment] 2018-03-19 20:37
I have no config

**Comment by diefans** [comment] 2018-03-19 20:43
left is a focused alacritty window and right is a urxvt window, while compton is running.
![alacritty-compton](https://user-images.githubusercontent.com/513316/37621132-60587cec-2bbe-11e8-9649-973a717dd03c.jpg)

**Comment by jwilm** [comment] 2018-03-19 20:49
@diefans can you please post your _alacritty.yml_?

**Comment by diefans** [comment] 2018-03-19 21:08
```yaml
# Configuration for Alacritty, the GPU enhanced terminal emulator


# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty it self.
env:
  # TERM env customization.
  #
  # If this property is not set, alacritty will set it to xterm-256color.
  #
  # Note that some xterm terminfo databases don't declare support for italics.
  # You can verify this by checking for the presence of `smso` and `sitm` in
  # `infocmp xterm-256color`.
  TERM: xterm-256color

# Window dimensions in character columns and lines
# Falls back to size specified by window manager if set to 0x0.
# (changes require restart)
dimensions:
  columns: 80
  lines: 24

# Adds this many blank pixels of padding around the window
# Units are physical pixels; this is not DPI aware.
# (change requires restart)
padding:
  x: 2
  y: 2

# Display tabs using this many cells (changes require restart)
tabspaces: 8

# When true, bold text is drawn using the bright variant of colors.
draw_bold_text_with_bright_colors: false

# Font configuration (changes require restart)
#
# Important font attributes like antialiasing, subpixel aa, and hinting can be
# controlled through fontconfig. Specifically, the following attributes should
# have an effect:
#
# * hintstyle
# * antialias
# * lcdfilter
# * rgba
#
# For instance, if you wish to disable subpixel antialiasing, you might set the
# rgba property to "none". If you wish to completely disable antialiasing, you
# can set antialias to false.
#
# Please see these resources for more information on how to use fontconfig
#
# * https://wiki.archlinux.org/index.php/font_configuration#Fontconfig_configuration
# * file:///usr/share/doc/fontconfig/fontconfig-user.html
font:
  # The normal (roman) font face to use.
  normal:
    family: Fantasque Sans Mono # should be "Menlo" or something on macOS.
    # family: Fantasque Sans Mono # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: Fantasque Sans Mono # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: Fantasque Sans Mono # should be "Menlo" or something on macOS.
    # Style can be specified to pick a specific face.
    style: Italic

  # Point size of the font
  size: 12.0

  # Offset is the extra space around each character. offset.y can be thought of
  # as modifying the linespacing, and offset.x as modifying the letter spacing.
  offset:
    x: 0.0
    y: 0.0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increase the x offset to move the glyph to
  # the right, increase the y offset to move the glyph upward.
  glyph_offset:
    x: 0.0
    y: 0.0

  # OS X only: use thin stroke font rendering. Thin strokes are suitable
  # for retina displays, but for non-retina you probably want this set to
  # false.
  use_thin_strokes: true

# Should display the render timer
render_timer: false

# Use custom cursor colors. If true, display the cursor in the cursor.foreground
# and cursor.background colors, otherwise invert the colors of the cursor.
custom_cursor_colors: false

# Colors (Tomorrow Night Bright)
colors:
  # Default colors
  primary:
    background: '0x120707'
    foreground: '0xfffedc'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x000000'
    cursor: '0xffffff'

  # Normal colors
  normal:
    black:   '0x000000'
    red:     '0xd54e53'
    green:   '0xb9ca4a'
    yellow:  '0xe6c547'
    blue:    '0x7aa6da'
    magenta: '0xc397d8'
    cyan:    '0x70c0ba'
    white:   '0xffffff'

  # Bright colors
  bright:
    black:   '0x666666'
    red:     '0xff3334'
    green:   '0x9ec400'
    yellow:  '0xe7c547'
    blue:    '0x7aa6da'
    magenta: '0xb77ee0'
    cyan:    '0x54ced6'
    white:   '0xffffff'

  # Dim colors (Optional)
  dim:
    black:   '0x333333'
    red:     '0xf2777a'
    green:   '0x99cc99'
    yellow:  '0xffcc66'
    blue:    '0x6699cc'
    magenta: '0xcc99cc'
    cyan:    '0x66cccc'
    white:   '0xdddddd'

# Visual Bell
#
# Any time the BEL code is received, Alacritty "rings" the visual bell. Once
# rung, the terminal background will be set to white and transition back to the
# default background color. You can control the rate of this transition by
# setting the `duration` property (represented in milliseconds). You can also
# configure the transition function by setting the `animation` property.
#
# Possible values for `animation`
# `Ease`
# `EaseOut`
# `EaseOutSine`
# `EaseOutQuad`
# `EaseOutCubic`
# `EaseOutQuart`
# `EaseOutQuint`
# `EaseOutExpo`
# `EaseOutCirc`
# `Linear`
#
# To completely disable the visual bell, set its duration to 0.
#
visual_bell:
  animation: EaseOutExpo
  duration: 0

# Background opacity
background_opacity: 1.0

# Mouse bindings
#
# Currently doesn't support modifiers. Both the `mouse` and `action` fields must
# be specified.
#
# Values for `mouse`:
# - Middle
# - Left
# - Right
# - Numeric identifier such as `5`
#
# Values for `action`:
# - Paste
# - PasteSelection
# - Copy (TODO)
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"

hide_cursor_when_typing: false

# Style of the cursor
#
# Values for 'cursor_style':
# - Block
# - Underline
# - Beam
cursor_style: Block

# Live config reload (changes require restart)
live_config_reload: true

# Shell
#
# You can set shell.program to the path of your favorite shell, e.g. /bin/fish.
# Entries in shell.args are passed unmodified as arguments to the shell.
# shell:
#   program: /bin/bash
#   args:
#     - --login


# Key bindings
#
# Each binding is defined as an object with some properties. Most of the
# properties are optional. All of the alphabetical keys should have a letter for
# the `key` value such as `V`. Function keys are probably what you would expect
# as well (F1, F2, ..). The number keys above the main keyboard are encoded as
# `Key1`, `Key2`, etc. Keys on the number pad are encoded `Number1`, `Number2`,
# etc.  These all match the glutin::VirtualKeyCode variants.
#
# Possible values for `mods`
# `Command`, `Super` refer to the super/command/windows key
# `Control` for the control key
# `Shift` for the Shift key
# `Alt` and `Option` refer to alt/option
#
# mods may be combined with a `|`. For example, requiring control and shift
# looks like:
#
# mods: Control|Shift
#
# The parser is currently quite sensitive to whitespace and capitalization -
# capitalization must match exactly, and piped items must not have whitespace
# around them.
#
# Either an `action`, `chars`, or `command` field must be present.
#   `action` must be one of `Paste`, `PasteSelection`, `Copy`, or `Quit`.
#   `chars` writes the specified string every time that binding is activated.
#     These should generally be escape sequences, but they can be configured to
#     send arbitrary strings of bytes.
#   `command` must be a map containing a `program` string, and `args` array of
#     strings. For example:
#     - { ... , command: { program: "alacritty", args: ["-e", "vttest"] } }
#
# Want to add a binding (e.g. "PageUp") but are unsure what the X sequence
# (e.g. "\x1b[5~") is? Open another terminal (like xterm) without tmux,
# then run `showkey -a` to get the sequence associated to a key combination.
key_bindings:
  - { key: V,        mods: Control|Shift,    action: Paste               }
  - { key: C,        mods: Control|Shift,    action: Copy                }
  - { key: Q,        mods: Command, action: Quit                         }
  - { key: W,        mods: Command, action: Quit                         }
  - { key: Insert,   mods: Shift,   action: PasteSelection               }
  - { key: Key0,     mods: Control, action: ResetFontSize                }
  - { key: Equals,   mods: Control, action: IncreaseFontSize             }
  - { key: Subtract, mods: Control, action: DecreaseFontSize             }
  - { key: Home,                    chars: "\x1bOH",   mode: AppCursor   }
  - { key: Home,                    chars: "\x1b[H",   mode: ~AppCursor  }
  - { key: End,                     chars: "\x1bOF",   mode: AppCursor   }
  - { key: End,                     chars: "\x1b[F",   mode: ~AppCursor  }
  - { key: PageUp,   mods: Shift,   chars: "\x1b[5;2~"                   }
  - { key: PageUp,   mods: Control, chars: "\x1b[5;5~"                   }
  - { key: PageUp,                  chars: "\x1b[5~"                     }
  - { key: PageDown, mods: Shift,   chars: "\x1b[6;2~"                   }
  - { key: PageDown, mods: Control, chars: "\x1b[6;5~"                   }
  - { key: PageDown,                chars: "\x1b[6~"                     }
  - { key: Tab,      mods: Shift,   chars: "\x1b[Z"                      }
  - { key: Back,                    chars: "\x7f"                        }
  - { key: Back,     mods: Alt,     chars: "\x1b\x7f"                    }
  - { key: Insert,                  chars: "\x1b[2~"                     }
  - { key: Delete,                  chars: "\x1b[3~"                     }
  - { key: Return,   mods: Shift,   chars: "\x1b[1;2Q"                     }
  - { key: Return,   mods: Control, chars: "\x1b\x0d"                     }
  - { key: Left,     mods: Shift,   chars: "\x1b[1;2D"                   }
  - { key: Left,     mods: Control, chars: "\x1b[1;5D"                   }
  - { key: Left,     mods: Alt,     chars: "\x1b[1;3D"                   }
  - { key: Left,     mods: Alt|Control,     chars: "\x1b[1;7D"                   }
  - { key: Left,     mods: Alt|Shift,     chars: "\x1b[1;9D"                   }
  - { key: Left,                    chars: "\x1b[D",   mode: ~AppCursor  }
  - { key: Left,                    chars: "\x1bOD",   mode: AppCursor   }
  - { key: Right,    mods: Shift,   chars: "\x1b[1;2C"                   }
  - { key: Right,    mods: Control, chars: "\x1b[1;5C"                   }
  - { key: Right,    mods: Alt,     chars: "\x1b[1;3C"                   }
  - { key: Right,    mods: Alt|Control,     chars: "\x1b[1;7C"                   }
  - { key: Right,    mods: Alt|Shift,     chars: "\x1b[1;9C"                   }
  - { key: Right,                   chars: "\x1b[C",   mode: ~AppCursor  }
  - { key: Right,                   chars: "\x1bOC",   mode: AppCursor   }
  - { key: Up,       mods: Shift,   chars: "\x1b[1;2A"                   }
  - { key: Up,       mods: Control, chars: "\x1b[1;5A"                   }
  - { key: Up,       mods: Alt,     chars: "\x1b[1;3A"                   }
  - { key: Up,       mods: Alt|Control,     chars: "\x1b[1;7A"                   }
  - { key: Up,       mods: Alt|Shift,     chars: "\x1b[1;9A"                   }
  - { key: Up,                      chars: "\x1b[A",   mode: ~AppCursor  }
  - { key: Up,                      chars: "\x1bOA",   mode: AppCursor   }
  - { key: Down,     mods: Shift,   chars: "\x1b[1;2B"                   }
  - { key: Down,     mods: Control, chars: "\x1b[1;5B"                   }
  - { key: Down,     mods: Alt,     chars: "\x1b[1;3B"                   }
  - { key: Down,     mods: Alt|Control,     chars: "\x1b[1;7B"                   }
  - { key: Down,     mods: Alt|Shift,     chars: "\x1b[1;9B"                   }
  - { key: Down,                    chars: "\x1b[B",   mode: ~AppCursor  }
  - { key: Down,                    chars: "\x1bOB",   mode: AppCursor   }
  - { key: F1,                      chars: "\x1bOP"                      }
  - { key: F2,                      chars: "\x1bOQ"                      }
  - { key: F3,                      chars: "\x1bOR"                      }
  - { key: F4,                      chars: "\x1bOS"                      }
  - { key: F5,                      chars: "\x1b[15~"                    }
  - { key: F6,                      chars: "\x1b[17~"                    }
  - { key: F7,                      chars: "\x1b[18~"                    }
  - { key: F8,                      chars: "\x1b[19~"                    }
  - { key: F9,                      chars: "\x1b[20~"                    }
  - { key: F10,                     chars: "\x1b[21~"                    }
  - { key: F11,                     chars: "\x1b[23~"                    }
  - { key: F12,                     chars: "\x1b[24~"                    }
  - { key: F13,                     chars: "\x1bO2P"                    }
  - { key: F14,                     chars: "\x1bO2Q"                    }
  - { key: F15,                     chars: "\x1bO2R"                    }
  #- { key: F16,                     chars: "\x1bO2S"                    }
  #- { key: F17,                     chars: "\x1b[15;2~"                    }
  #- { key: F18,                     chars: "\x1b[17;2~"                    }
  #- { key: F19,                     chars: "\x1b[18;2~"                    }
  #- { key: F20,                     chars: "\x1b[19;2~"                    }
  #- { key: F21,                     chars: "\x1b[20;2~"                    }
  #- { key: F22,                     chars: "\x1b[21;2~"                    }
  #- { key: F23,                     chars: "\x1b[23;2~"                    }
  #- { key: F24,                     chars: "\x1b[24;2~"                    }
  #- { key: F25,                     chars: "\x1bO5P"                    }
  #- { key: F26,                     chars: "\x1bO5Q"                    }
  #- { key: F27,                     chars: "\x1bO5R"                    }
  #- { key: F28,                     chars: "\x1bO5S"                    }
  #- { key: F29,                     chars: "\x1b[15;5~"                    }
  #- { key: F30,                     chars: "\x1b[17;5~"                    }
  #- { key: F31,                     chars: "\x1b[18;5~"                    }
  #- { key: F32,                     chars: "\x1b[19;5~"                    }
  #- { key: F33,                     chars: "\x1b[20;5~"                    }
  #- { key: F34,                     chars: "\x1b[21;5~"                    }
  #- { key: F35,                     chars: "\x1b[23;5~"                    }
  #- { key: F36,                     chars: "\x1b[24;5~"                    }
  #- { key: F37,                     chars: "\x1bO6P"                    }
  #- { key: F38,                     chars: "\x1bO6Q"                    }
  #- { key: F39,                     chars: "\x1bO6R"                    }
  #- { key: F40,                     chars: "\x1bO6S"                    }
  #- { key: F41,                     chars: "\x1b[15;6~"                    }
  #- { key: F42,                     chars: "\x1b[17;6~"                    }
  #- { key: F43,                     chars: "\x1b[18;6~"                    }
  #- { key: F44,                     chars: "\x1b[19;6~"                    }
  #- { key: F45,                     chars: "\x1b[20;6~"                    }
  #- { key: F46,                     chars: "\x1b[21;6~"                    }
  #- { key: F47,                     chars: "\x1b[23;6~"                    }
  #- { key: F48,                     chars: "\x1b[24;6~"                    }
  - { key: F1,       mods: Shift,   chars: "\x1b[1;2P"                   }
  - { key: F2,       mods: Shift,   chars: "\x1b[1;2Q"                   }
  - { key: F3,       mods: Shift,   chars: "\x1b[1;2R"                   }
  - { key: F4,       mods: Shift,   chars: "\x1b[1;2S"                   }
  - { key: F5,       mods: Shift,   chars: "\x1b[15;2~"                  }
  - { key: F6,       mods: Shift,   chars: "\x1b[17;2~"                  }
  - { key: F7,       mods: Shift,   chars: "\x1b[18;2~"                  }
  - { key: F8,       mods: Shift,   chars: "\x1b[19;2~"                  }
  - { key: F9,       mods: Shift,   chars: "\x1b[20;2~"                  }
  - { key: F10,      mods: Shift,   chars: "\x1b[21;2~"                  }
  - { key: F11,      mods: Shift,   chars: "\x1b[23;2~"                  }
  - { key: F12,      mods: Shift,   chars: "\x1b[24;2~"                  }
  - { key: F1,       mods: Control, chars: "\x1b[1;5P"                   }
  - { key: F2,       mods: Control, chars: "\x1b[1;5Q"                   }
  - { key: F3,       mods: Control, chars: "\x1b[1;5R"                   }
  - { key: F4,       mods: Control, chars: "\x1b[1;5S"                   }
  - { key: F5,       mods: Control, chars: "\x1b[15;5~"                  }
  - { key: F6,       mods: Control, chars: "\x1b[17;5~"                  }
  - { key: F7,       mods: Control, chars: "\x1b[18;5~"                  }
  - { key: F8,       mods: Control, chars: "\x1b[19;5~"                  }
  - { key: F9,       mods: Control, chars: "\x1b[20;5~"                  }
  - { key: F10,      mods: Control, chars: "\x1b[21;5~"                  }
  - { key: F11,      mods: Control, chars: "\x1b[23;5~"                  }
  - { key: F12,      mods: Control, chars: "\x1b[24;5~"                  }
  - { key: F1,       mods: Alt,     chars: "\x1b[1;6P"                   }
  - { key: F2,       mods: Alt,     chars: "\x1b[1;6Q"                   }
  - { key: F3,       mods: Alt,     chars: "\x1b[1;6R"                   }
  - { key: F4,       mods: Alt,     chars: "\x1b[1;6S"                   }
  - { key: F5,       mods: Alt,     chars: "\x1b[15;6~"                  }
  - { key: F6,       mods: Alt,     chars: "\x1b[17;6~"                  }
  - { key: F7,       mods: Alt,     chars: "\x1b[18;6~"                  }
  - { key: F8,       mods: Alt,     chars: "\x1b[19;6~"                  }
  - { key: F9,       mods: Alt,     chars: "\x1b[20;6~"                  }
  - { key: F10,      mods: Alt,     chars: "\x1b[21;6~"                  }
  - { key: F11,      mods: Alt,     chars: "\x1b[23;6~"                  }
  - { key: F12,      mods: Alt,     chars: "\x1b[24;6~"                  }
  - { key: F1,       mods: Super,   chars: "\x1b[1;3P"                   }
  - { key: F2,       mods: Super,   chars: "\x1b[1;3Q"                   }
  - { key: F3,       mods: Super,   chars: "\x1b[1;3R"                   }
  - { key: F4,       mods: Super,   chars: "\x1b[1;3S"                   }
  - { key: F5,       mods: Super,   chars: "\x1b[15;3~"                  }
  - { key: F6,       mods: Super,   chars: "\x1b[17;3~"                  }
  - { key: F7,       mods: Super,   chars: "\x1b[18;3~"                  }
  - { key: F8,       mods: Super,   chars: "\x1b[19;3~"                  }
  - { key: F9,       mods: Super,   chars: "\x1b[20;3~"                  }
  - { key: F10,      mods: Super,   chars: "\x1b[21;3~"                  }
  - { key: F11,      mods: Super,   chars: "\x1b[23;3~"                  }
  - { key: F12,      mods: Super,   chars: "\x1b[24;3~"                  }
```

**Comment by maximbaz** [comment] 2018-03-19 21:26
Looks similar? https://github.com/jwilm/alacritty/issues/1059

**Comment by diefans** [comment] 2018-03-19 22:46
@maximbaz I think so...

**Comment by jwilm** [comment] 2018-03-19 23:37
Thanks for the link @maximbaz 

It appears the author of that other issue filed an issue upstream which has so far been ignored. https://github.com/tomaka/glutin/issues/984

**Comment by chrisduerr** [comment] 2018-03-19 23:43
I do wonder how useful the `background_opacity` setting in alacritty really is with the ability to set this up with compositors. I guess for macos it's nice.

But so far it has mainly created issues for me with windows flickering on resize and the issue mentioned in #1059 (and potentially this issue).

If this issue is solved by disabling transparency (as mentioned in #1059), it can probably be closed as duplicate.

**Comment by maximbaz** [comment] 2018-03-20 00:13
The "native" alacritty's opacity is fancier than what compton can provide, compton can only apply a certain level of opacity on _everything_, while alacritty is being smart and renders some blocks with fully opaque, which although [confuses some people](https://github.com/jwilm/alacritty/issues/1180), in my mind makes alacritty look better and improves readability (an example can be seen on the text `~/private/alacritty` in the bottom of the screenshots below).

Some screenshots are in order 🙂

compton at opacity 95%:

![transparency_compton](https://user-images.githubusercontent.com/1177900/37628806-7c0bb036-2bdb-11e8-82ea-aae2b7164734.png)

alacritty at opacity 95%:

![transparency_native](https://user-images.githubusercontent.com/1177900/37628808-8321af56-2bdb-11e8-9e9d-c75e6e2f6a6c.png)

differences highlighted:

![transparency_native_diff](https://user-images.githubusercontent.com/1177900/37628814-8dc71d56-2bdb-11e8-9bbd-808986d49317.png)

**Comment by gordol** [comment] 2018-03-20 20:49
> I do wonder how useful the background_opacity setting in alacritty really is with the ability to set this up with compositors. I guess for macos it's nice.

Huh? Setting the transparency with your compositor causes the WHOLE window to have transparency applied, console contents, and all... That's not good, ideally, since text is then not as sharp.

I did notice something interesting however... Here I'm running xfce4 w/ compositing enabled, and am showing xterm w/ transset, xfce4-terminal, and alacritty (all with 0.92 opacity) but only alacritty even shows the opacity properly in the screenshot, though they all look very similar on my screen (aside from the text being slightly transparent in xterm due to transset)

![screenshot](https://node.zeneval.com/snaps/095fb51060f515a9d36e62cffe064b66.png)

I'm wondering if this isn't a compositor issue, actually...

Anyone else using xfce4's compositor and having issues? Works fine for me, aside from the screenshots not showing the actual background transparency. In the screenshot, the two bottom windows have less transparency than I see on the actual screen.

Makes me wonder if there's some kind of rendering issue that y'all are having on your screens, that's similar to the effect this screenshot is showing, where alacritty is actually lighter than the other windows, even though when I actually look at them, they all look correct.

**Comment by diefans** [comment] 2018-03-20 21:36
@gordol I am not a native english speaker, but are you really questioning whether my screenshot shows exactly what my screen is showing or not and that my windows may "look correct", if I would "actually look at them"? 
hmmm....

**Comment by gordol** [comment] 2018-03-20 23:09
@diefans 

I'm saying there is nuance in regards to how your particular compositor may be drawing windows to the screen. Especially with the reports of many users saying their windows flicker when resizing. I do not experience these issues with alacritty, for what that's worth.

What I see on the screen, and what my screenshot shows are not the same. I physically see way more transparency in the bottom two windows than the screenshot reflects.

I am not questioning whether your screenshot reflects what you say you see. My point is, your compositor may be the problem, not Nvidia, or alacritty, nor even glutin.

**Comment by diefans** [comment] 2018-03-21 08:44
@gordol I tried it with `xcompmgr`, `unagi` and `compton` - all with the same result. I also tried the archlinux fork with scrolling from https://github.com/neon64/alacritty, which works as expected but seems outdated. So there must be introduced something, which leads to my issue.

**Comment by gordol** [comment] 2018-03-21 12:35
Indeed, as noted above by @jwilm, I believe the issue is triggered by the recent glutin upgrade: https://github.com/tomaka/glutin/issues/984 An older check out of alacritty would be using an older version of glutin libs.

**Comment by chrisduerr** [comment] 2018-05-04 20:47
I'm gonna close this since it seems to be a duplicate of #1059. Just easier to keep the discussion in one place.

**Closed by chrisduerr** 2018-05-04 20:47 UTC
