### ISSUE TITLE
Performance issue with cat /dev/urandom

### ISSUE THREAD

**Issue by 08A** [jwilm/alacritty#3053] opened 2019-11-29 12:19 UTC
**OS**: Archlinux with X11
**WM**: dwm
**CPU**: Intel i5-8350U (8) @ 3.600GHz
**GPU**: Intel UHD Graphics 620

I don't know if it is a bug or a performance issue, but when I launch the command ```cat /dev/urandom```.

The terminal starts to slow down and I lose access to the tty, I can't use any bind key of dwm. The only way to recover is kill alacritty. After the destruction of the process after 1 or 2 seconds I regain access to WM.

I try to set ```scrolling.history: 0``` but i don't see any difference.
I try another terminal such as kitty or st and it work more smoothly.
It is maybe a problem with Intel's GPU?

**Comment by chrisduerr** [comment] 2019-11-30 05:03
Doing `cat /dev/urandom` is a really bad benchmark for anything, since you rely on so, so many different components of your system.

What exactly are you trying to achieve by running `cat /dev/urandom`? If you want to benchmark terminal emulators, it's much better to have a constant file with fixed text and escapes to make sure you can reliably reproduce the same performance numbers. And even then this has to be taken with a huge grain of salt, because running `cat` against a file doesn't necessarily say anything about the actual performance, since the terminal might just stop redrawing under load.

**Comment by dnkl** [comment] 2019-11-30 10:50
I agree with @chrisduerr that as a benchmark it is bad.

However, when I do this experiment on Wayland/Sway, Alacritty becomes unresponsive, if I let it run long enough, at which point <kbd>ctrl</kbd>+<kbd>c</kbd> will stop working and I have to kill the `cat` process (from another terminal). When I do, it stops immediately. So it doesn't appear Alacritty has queued up lots of data, making it _look_ like <kbd>ctrl</kbd>+<kbd>c</kbd> doesn't work. I haven't seen this problem with e.g. xterm.

But I don't have any issues with the WM not responding, and I can launch and run other programs without any issues.

**Comment by 08A** [comment] 2019-11-30 11:26
> Doing cat /dev/urandom is a really bad benchmark

It was not for benchmark purpose. I was writing a shell, and when I tried to test the piping system I discover this behavior.

> But I don't have any issues with the WM not responding, and I can launch and run other programs
without any issues.

Maybe it is the way that dwm handle unresponsive application?

**Comment by chrisduerr** [comment] 2019-11-30 12:19
The initial performance might be slightly worse than other terminals due to #2858, but it should accelerate in speed quickly since there's usually not a lot of unicode characters printed.

@dnkl Does it immediately become unresponsive, or do you have to wait a bit until this happens?

I've been doing `cat /dev/urandom` for a while now and neither bash nor zsh show any issues at all. Which shells are you guys using?

And we're talking about just standard Linux setups, right? With /dev/urandom generating data even if no entropy is left? Using /dev/random might starve entropy, but urandom shouldn't be a problem.

**Comment by chrisduerr** [comment] 2019-11-30 12:20
Note that I have tested with i3, though that should not make a difference.

Also please verify you're running at least 0.4.0 using `alacritty --version`.

**Comment by dnkl** [comment] 2019-11-30 13:44
> Also please verify you're running at least 0.4.0
alacritty 0.4.0

> Does it immediately become unresponsive, or do you have to wait a bit until this happens?
I have to wait for a while, say 30s. Unclear _what_ needs to happen; is it a build up of something that has to pass a certain threshold? Or is it a certain sequence of escapes that makes Alacritty enter some weird state? No idea... The time needed to wait varies wildly though.

> Which shells are you guys using?
zsh, but I managed to trigger it in bash too.

> And we're talking about just standard Linux setups, right? With /dev/urandom generating data even if no entropy is left
Yes. Output/rendering speed doesn't seem to be affected. Once we're past the initial glyph cache population the speed remains the same.

Wild guess is the input flow is starved in some way.

Not sure if related, but once i kill `cat`, the screen is more or less filled with `6c6c6c6c...`. How much seems to depend on how long I waited before killing it. I didn't see that in xterm.

**Comment by dnkl** [comment] 2019-11-30 13:49
> Yes. Output/rendering speed doesn't seem to be affected. Once we're past the initial glyph cache population the speed remains the same.

I think I misread #2858. But anyway, urandom isn't blocking, and alacritty seems to process it and render it at constant speed.

**Comment by chrisduerr** [comment] 2019-11-30 14:05
> Wild guess is the input flow is starved in some way.

That would have been my assumption, that Alacritty drains `/dev/urandom` because it is faster and that can cause other systems to fail that rely on these pseudo-random numbers.

However, the entire point of `/dev/urandom` is to have a fast rng that doesn't require entropy to work but just generates good enough 'garbage' data instead of randomness.

> Not sure if related, but once i kill cat, the screen is more or less filled with 6c6c6c6c.... How much seems to depend on how long I waited before killing it. I didn't see that in xterm.

That's just our response to `/dev/urandom` asking Alacritty to identify itself as a VT100 terminal emulator. That's an escape code working as intended (though there is a bug that we accept single byte escape for terminal identification, instead of requiring the utf-8 double byte encoding, but that is trivial to fix in theory and unrelated to this issue).

> I think I misread #2858. But anyway, urandom isn't blocking, and alacritty seems to process it and render it at constant speed.

So if I understand this correctly, you cannot identify any problem by looking at Alacritty, however trying to stop it with Ctrl+C does not work anymore? It seems like @08A has a slightly different problem, where even Alacritty actually starts locking up (though that could be caused by issues with the WM I suppose?).

I ran the tests again myself, just to make sure and after over 5 minutes of running `cat /dev/urandom` Alacritty is still working exactly as expected.

**Comment by kchibisov** [comment] 2019-11-30 14:10
FWIW I can repro the issue with `cat /dev/urandom` and it becomes unresponsive quite fast for me, however wit `cat -v /dev/urandom`, I can't repro  it. I can't stop cat with `Ctrl + C` in first case, but can in the second one. So I guess draining /dev/urandom doesn't matter.

**Comment by dnkl** [comment] 2019-11-30 14:10
>>    Wild guess is the input flow is starved in some way.

> That would have been my assumption, that Alacritty drains /dev/urandom because it is faster and that can cause other systems to fail that rely on these pseudo-random numbers.

Well, I meant "input" as in user/keyboard-input. It doesn't look like /dev/urandom is drained (which would have been strange).

**Comment by dnkl** [comment] 2019-11-30 14:12
Maybe an issue with the Wayland backend?

**Comment by kchibisov** [comment] 2019-11-30 14:15
>Maybe an issue with the Wayland backend?

Hm, I can't repro `Ctrl + C` part on X11, so probably.

**Comment by chrisduerr** [comment] 2019-11-30 14:23
> Maybe an issue with the Wayland backend?

The original issue was created for dwm, so that seems kinda unlikely.

**Comment by mbaz** [comment] 2019-11-30 17:17
I can confirm the behavior described by @08A.

OS: Archlinux with X11 running in VirtualBox under Windows 10
WM: openbox
CPU: Intel i7-7820HQ (8) @ 2.900GHz
GPU: Virtualbox VBoxSVGA, without 3D acceleration
Alacritty: 0.4.0

I ran `cat /dev/urandom` in alacritty. The output was "bursty", with the screen updating very quickly maybe twice a second and static most of the time. I let it run for 10 seconds or so. I hit Ctrl-C to interrupt the process and I saw a bunch of `6c6c6c...` as reported by @dnkl .

Then I hit Ctrl-D to close alacritty and noticed that openbox was frozen. The mouse and all keybindings became unresponsive. I couldn't switch virtual desktops by clicking on my panel (xfce4-panel).

Fortunately I had another terminal open (urxvt) and it got focus. There I found that alacritty was no longer running, even though its window was still there -- probably a consequence of openbox being unresponsive. I tried running `xprop` and it returned `Error: cannot grab mouse` (or similar, I'm going by memory).

In the end I had to kill openbox -- I couldn't get it to respond again.

**Comment by nixpulvis** [comment] 2019-12-01 01:56
I'd be curious if people in this thread have tested this under other terminals, and how their WMs handle that. I'm thinking that, perhaps if other terminals cannot replicate, it's a matter of alacritty being fast enough that it's making enough random calls to the system to overwhelm it.

On my system running X11/i3 I couldn't seem to replicate it however.

**Comment by chrisduerr** [comment] 2019-12-01 02:49
> have we actually verified that this is a "crash"?

I've labeled it as a crash because it will cause Alacritty to freeze and become completely unresponsive to user input. So 'crash' seems like the closest equivalent, even though it might not close completely.

Especially in the original report, there didn't seem like there were much other choices than killing Alacritty and if Alacritty is put into a state where the only reasonable action is killing it, that seems to be kinda fitting for a 'crash'.

I've picked this label mainly because I didn't think 'performance' or 'bug' really captured the root problem very well, since as mentioned /dev/urandom performance shouldn't be great and Alacritty isn't doing anything wrong, but it stops doing anything at all. But definitely not a clear crash.

**Comment by 08A** [comment] 2019-12-01 22:27
>  I tried another terminal such as kitty or st and it work more smoothly.

@nixpulvis i tried under other terminals. The main difference is that my WM stop responding with alacritty.

I tried with another configuration and it crash.
**OS**: Archlinux with X11
**WM**: dwm
**CPU**: AMD Ryzen 7 2700X (16) @ 3.700GHz
**GPU**: NVIDIA GeForce GTX 1060 6GB

I switched to i3 and the crash disappeared. I believe that it is the the way that some WM handle the interaction with alacritty.
**crash**: dwm
**no probleme**: i3

**Comment by chrisduerr** [comment] 2019-12-01 22:28
After some troubleshooting with @kchibisov, this could be identified as a duplicate of https://github.com/jwilm/alacritty/issues/511. It just seems to behave especially bad with your dwm setup.

**Closed** 2019-12-01 22:29 UTC
Labels: A - needs repro, B - crash, H - linux, P - low

**Comment by 08A** [comment] 2019-12-01 22:43
@chrisduerr I tried on openbox and it crashed (I used the default configuration /etc/xdg/openbox). The bug is easily reproducible.
**dwm config**: https://github.com/08A/suckless
**dotfile**: https://github.com/08A/dotfile

**Comment by kchibisov** [comment] 2019-12-01 22:45
@08A Did you get the output from dwm and the reason why it crashed?

**Comment by chrisduerr** [comment] 2019-12-01 22:52
If `cat -v /dev/urandom` also crashes, that's a different story. But otherwise this will be fixed with #511.

**Comment by 08A** [comment] 2019-12-01 22:59
@kchibisov Until now it just freeze. But if i wait 1 to 5 min i regain access to the WM. During the freeze, the process xorg (/usr/lib/Xorg) used 80-95 % cpu (on one core).

**Comment by 08A** [comment] 2019-12-01 23:01
> If cat -v /dev/urandom also crashes, that's a different story. But otherwise this will be fixed with #511.

@chrisduerr No problem with ```cat -v /dev/urandom```

**Comment by akvadrako** [comment] 2022-10-26 10:01
Today I found my terminal doing something weird when using `git diff` and alacritty 0.12.0-dev. I found this bug because I get the same spurious `6c6c6c6c`. It doesn't happen in gnome-terminal so I suppose it's related, thought I haven't come up with a reproducable test case so I'm just adding a comment here in case it helps someone down the line.
