### ISSUE TITLE
alacritty terminfo is not compatible with GNU dircolors

### ISSUE THREAD

**Issue by iicurtis** [jwilm/alacritty#2210] opened 2019-03-25 00:46 UTC
> Which operating system does the issue occur on?

Arch Linux - 5.0.3

> If on linux, are you using X11 or Wayland?

X11 with KDE Plasma. This problem does not seem to happen on Wayland with Sway.

**Summary** - The environment variable `LS_COLORS` is defined, but set to empty string. This causes issues with nearly all programs relying on this for color output. Unsetting this variable seems to fix most problems.

```
$ env | grep COLOR

COLORTERM=truecolor
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS= 
```

**Expected Behavior** - `LS_COLORS` is set depending on the colors defined in the alacritty config file.

**Strange Notes** This behavior seems to be unique to my KDE Plasma setup. The same computer with Sway on Wayland produces the correct `LS_COLORS` behavior. However, my setup with KDE Plasma is repeatable across multiple machines.

**Comment by chrisduerr** [comment] 2019-03-25 00:53
Alacritty does not mess with the `LS_COLORS` environment variable. If something is changing your `LS_COLORS`, it's probably your shell's profile or rc file.

**Comment by iicurtis** [comment] 2019-03-25 01:28
My apologies. I can confirm that alacritty does not set LS_COLORS.

I have identified the offending line in my zsh rc config:

```
~/.zshrc

antigen use oh-my-zsh
```

However, I assumed this was an alacritty specific bug because **other terminal emulators work**, including kitty (another GPU accelerated terminal) and konsole.

So, digging deeper, I now suspect this to be a problem with alacritty's `TERMINFO` file. Both `xterm-kitty` and `xterm-256color` result in the correct variable being set. 

Indeed, in alacritty's config file, setting TERM=xterm-256color works. 

--- 

I'll check out the oh-my-zsh problem. It could be as simple as it looks for the `xterm` in front of the TERMINFO. I'll file a bug there if that's the case.

**Comment by iicurtis** [comment] 2019-03-25 01:42
The issue is not with oh-my-zsh as I thought, but with **GNU dircolors** (part of the coreutils). 

However, it is as simple as I thought. Here are my thoughts:

---

## Solution 1 

Rename the alacritty TERM to an accepted term match, such as **xterm-alacritty** or **color-alacritty**. This should solve the issue. 

**Explanation** GNU dircolors matches a TERM against the following directories, taken from the manpage:

```
TERM Eterm
TERM ansi
TERM *color*
TERM con[0-9]*x[0-9]*
TERM cons25
TERM console
TERM cygwin
TERM dtterm
TERM gnome
TERM hurd
TERM jfbterm
TERM konsole
TERM kterm
TERM linux
TERM linux-c
TERM mlterm
TERM putty
TERM rxvt*
TERM screen*
TERM st
TERM terminator
TERM tmux*
TERM vt100
TERM xterm*
```

## Solution 2

Submit a pull request to upstream GNU requesting they adopt our TERM file name, alacritty. I strongly suspect this to be met with significant pushback. Likely this will be fighting an uphill battle.

## Solution 3

Force everyone who relies on dircolors functionality to rely on setting their TERM to `xterm-256color` in the alacritty.yml file. I personally don't like this approach because I experience coloring issues when I use a different TERM.

**Comment by chrisduerr** [comment] 2019-03-25 16:16
> Rename the alacritty TERM to an accepted term match, such as xterm-alacritty or color-alacritty. This should solve the issue.

Alacritty is not a version of xterm. Advertising it as such is incorrect and will just lead to packages like vim requiring to add more and more complex hacks.

> Submit a pull request to upstream GNU requesting they adopt our TERM file name, alacritty. I strongly suspect this to be met with significant pushback. Likely this will be fighting an uphill battle.

GNU dircolors is at fault here, so that's where the issue needs to be fixed. I would not expect a lot of pushback, other applications have been very cooperative in resolving similar issues.

Since this is not an Alacritty issue, this is the wrong place to resolve and discuss it.

Note that setting `LS_COLORS` yourself works perfectly fine and I haven't run into any issues with that. So if the `dircolors` command does not support terminal emulators that don't fit into their custom terminfo table, circumventing it by just taking the result from xterm and reusing it in Alacritty should be trivial (something like `export LS_COLORS='ow=36:di=34:fi=32:ex=31:ln=35:'`  is all it takes).

**Closed** 2019-03-25 16:16 UTC

**Comment by iicurtis** [comment] 2019-03-25 16:25
Thanks! I'll give it a shot at GNU dircolors. Until then, I'll set `LS_COLORS` manually.

**Comment by chrisduerr** [comment] 2019-03-25 16:35
Thanks, feel free to keep us updated. I'm happy to help too.

**Comment by pschyska** [comment] 2019-06-16 18:16
@chrisduerr I just thought about that issue as well. What do you think about adding `/etc/DIR_COLORS.alacritty` to extra/linux?
That way we could ship it in packages (I would do it for RPM :-), and the out-of-the-box experience would be a bit better. I for one was confused about the missing colors in ls.

For manual builders it would be another manual step like installing terminfo and man pages.

**Comment by chrisduerr** [comment] 2019-06-16 18:20
I don't think the Alacritty upstream is a good place to maintain a dircolors fork. If packagers would be interested in forking, then a separate repo should probably be created. It's not only Alacritty that might run into this issue after all.

**Comment by pschyska** [comment] 2019-06-16 18:24
OK, I understand. I think it's best to contact the coreutils folks. @iicurtis Did you try that already?

**Comment by iicurtis** [comment] 2019-06-16 19:51
Sorry, but I did not. Looks like someone has submitted it to the mailing list though, but it has stalled out:

https://lists.gnu.org/archive/html/bug-coreutils/2019-05/msg00030.html

Perhaps someone here could bump the thread and provide a little background to the project and why we need our own definition.

**Comment by pschyska** [comment] 2019-06-16 20:08
> Sorry, but I did not. Looks like someone has submitted it to the mailing list though, but it has stalled out:
> 
> https://lists.gnu.org/archive/html/bug-coreutils/2019-05/msg00030.html
> 
> Perhaps someone here could bump the thread and provide a little background to the project and why we need our own definition.

Thanks for pointing me to that thread. I looked into the Fedora packaging for coreutils-common, and it looks like they heavily patch the DIR_COLORS files there. I doubt they can be convinced to add alacritty when it's not packaged in Fedora proper yet.

What worked for me is putting the following lines into .bash_profile:

```
eval "$(TERM=xterm-256color dircolors --sh /etc/DIR_COLORS.256color)"
export USER_LS_COLORS="$LS_COLORS"
```

(So I'm lying about TERM, but only temporarily). The way `/etc/profile.d/colorls.sh` is set up, setting USER_LS_COLORS is circumventing the automatic detection. Just exporting `LS_COLORS` did not work for me.
Another option is to copy `/etc/DIR_COLORS.256color` to `$HOME/.dir_colors` and adding a `TERM alacritty` line to it.

**Comment by pschyska** [comment] 2019-06-16 20:15
I spoke too early, sorry I'm a bit tired. I thought Fedora just added all the TERMs into these files during packaging, but I checked the patch again and they *are* in upstream. If `st` and `terminator` are named, I don't see a reason why alacritty couldn't :smirk:. I'll look into it tomorrow, maybe it's best to just revive this thread.

I think it should be easy to argue changing alacritty's TERM like they suggested is not an option here, as it is already officially packaged for many distributions...

**Comment by chrisduerr** [comment] 2019-06-16 20:23
Changing Alacritty's TERM to match some arbitrary list of TERMs also doesn't make much sense at all.

The question why Alacritty requires its own TERM should really always be the other way around, there's very little reason why any terminal emulator should use the TERM of another, since that will only cause problems.

Requiring to be in the Fedora repos also seems like an extremely weird restriction, since Fedora is not any more of a 'default' Linux distro than many of the other distros that Alacritty is already supported on. Only because some arbitrarily chosen Linux distro doesn't support a specific terminal emulator, should never mean that a bug in an existing application shouldn't be fixed.

Generally it just seems mostly to be an opposition to change, rather than the change itself. This is also why I'm not personally interested in driving this discussion forward. I don't have the time to convince every application developer why they should make their apps work with every commonly used terminal emulator. However if the users interested in these changes are willing to put in this effort, that would be much appreciated of course.

**Comment by pschyska** [comment] 2019-06-16 20:42
> Requiring to be in the Fedora repos also seems like an extremely weird restriction, since Fedora is not any more of a 'default' Linux distro than many of the other distros that Alacritty is already supported on.

I was just thinking Fedora adds the TERMs of the packaged terminals to dircolors during packaging, but I was mistaken as they are  already present in the upstream (GNU coreutils). If Fedora *would* have added them, I would have to ask the Fedora coreutils package maintainer to add it. Then there would be grounds to question it when alacritty is not officially packaged (in theory). But I misunderstood the situation.

And no, Fedora shouldn't be a factor in decision w.r.t. to GNU coreutils.

**Comment by freswa** [comment] 2020-02-21 16:30
Has anyone here picked this up and replied the coreutils guys? Can't find anything...

**Comment by chrisduerr** [comment] 2020-02-21 16:34
> Has anyone here picked this up and replied the coreutils guys

This issue is caused by coreutils people not responding, not the other way around. There has been no change to that and we cannot do anything about it. Just bypass dircolors, there's really no need for it.

**Comment by tomquinn8** [comment] 2020-12-02 21:46
As alacritty is a terminal which supports colour and it would solve this issue/enable alacritty to be compatible with dircolors could the TERM used not be changed to alacritty-color as per Solution 1 above?
