### ISSUE TITLE
Alacritty sometimes freezes on user inactivity.

### ISSUE THREAD

**Issue by MaximeHouis** [jwilm/alacritty#2430] opened 2019-05-09 09:37 UTC
### Which operating system does the issue occur on?
Linux - Arch Linux
### If on linux, are you using X11 or Wayland?
X11
### Description
Hello,
When I run a long program (system updates, custom servers, ...), the terminal would freeze. It unfreezes when a user action happens (mouse move, mouse click, keyboard action).
My system is up to date and reinstalling alacritty has not solved the issue.
### How to reproduce
I haven't find any way of reproducing this bug consitently. The freeze happens when running long time commands, but I wasn't able to reproduce the issue with commands such as `tree /` or `ls -lRa /`.

**Comment by chrisduerr** [comment] 2019-05-09 09:40
Duplicate of https://github.com/jwilm/alacritty/issues/2217.

**Closed by chrisduerr** 2019-05-09 09:40 UTC
