### ISSUE TITLE
Image display with w3mimgdisplay almost works (?)

### ISSUE THREAD

**Issue by 22459** [jwilm/alacritty#1089] opened 2018-02-05 05:23 UTC
I'm on x11, and this happens in a plain old session. Package manager says `alacritty-unstable-2017-12-29`.

Using the script from the bottom of this page: http://blog.z3bra.org/2014/01/images-in-terminal.html image display seems to almost work on alacritty. The image displays for a spit second and disappears while flickering.

Is this the current expected behavior?

**Comment by chrisduerr** [comment] 2018-02-05 07:11
This is a duplicate of #1021. Currently there are some issues with tools like w3m.

**Closed by chrisduerr** 2018-02-05 07:11 UTC

**Comment by 22459** [comment] 2018-02-05 15:36
Ah, now I know that this is the huge hack I expected it to be. https://github.com/jwilm/alacritty/issues/1021#issuecomment-359184981

**Comment by chrisduerr** [comment] 2018-02-05 16:54
Calling w3m images a huge hack is a bit of an understatement. :laughing: 
However it's a hack a lot of people got used to, so better support for it would be nice ofc.

**Comment by 22459** [comment] 2018-02-05 17:43
I still think its pretty cool.
