### ISSUE TITLE
Support for vi-like mode(Insert, Selection)

### ISSUE THREAD

**Issue by hiteshpaul** [jwilm/alacritty#737] opened 2017-08-17 08:23 UTC
For users those who prefer window managers(and command line) in general, tend to use their keyboard for all purposes. 

I like alacritty but I miss a feature from [termite](https://github.com/thestinger/termite) such as selection mode, which enables me to select text in the terminal with just the help of keyboard(just to mention, it is lot more efficient than using the mouse and selecting terminal output text!). 

Are there any plans on implementing such feature?

**Comment by gmile** [comment] 2017-08-17 14:07
Alacritty is a rendered. I believe what you're asking for must be done one level higher. In `tmux`, for isntance.

**Comment by bearcatsandor** [comment] 2017-08-17 15:40
@hitrshpaul You might want to give Neovim a try. It has a terminal you can start via : terminal which gives you all the power of vim in a terminal window. It's changed my life.

**Comment by wayneashleyberry** [comment] 2017-08-17 16:24
zsh also has a great vi-mode: https://dougblack.io/words/zsh-vi-mode.html

**Comment by jwilm** [comment] 2017-08-17 16:41
Duplicate of #262

**Closed by jwilm** 2017-08-17 16:41 UTC

**Comment by hiteshpaul** [comment] 2017-08-17 17:56
@wayneashleyberry yes, zsh also has a vi-mode(oh-my-zsh) plugin. But that is limited to the current line in prompt. You cannot navigate/interact with the previous outputs. In such scenario, its either the terminal or some program like tmux/screen which will help.

@bearcatsandor Never gave a try to neovim. Will try sometimes soon!
