### ISSUE TITLE
Font weight

### ISSUE THREAD

**Issue by gonczolp** [jwilm/alacritty#1932] opened 2018-12-27 22:58 UTC
I'm trying to use a font (Monaco) that does not have an italic / bold variant. Until now I relied upon FreeType having the ability to create these missing styles, and it works like a charm in e.g urxvt `URxvt.font: xft:Monaco:weight=200:size=10`, st `static char *font = "Monaco:weight=200:size=10";` and other software like vscode. I tried adding the `weight` property to the alacritty config:
```yaml
 # Bold font face
  bold:
    family: Monaco
    weight: 200
```
However it doesn't seem to work, and I didn't find detailed documentation on this other than the comments in the default conf. [This](https://wiki.archlinux.org/index.php/font_configuration#Create_bold_and_italic_styles_for_incomplete_fonts) might be a solution, but the cache location `/usr/share/fonts/fonts.cache-1` looks to be outdated, I need to delve into that.

I'm new to the Linux font stack (Arch, X11), please let me know if something I assumed is incorrect or I missed any clearly written documentation. Thanks!

**Comment by gonczolp** [comment] 2018-12-27 23:01
My bad, this is relevant to [#1754](https://github.com/jwilm/alacritty/issues/1754)

**Comment by chrisduerr** [comment] 2018-12-27 23:02
Closing as duplicate of #1754.

**Closed by chrisduerr** 2018-12-27 23:02 UTC
