### ISSUE TITLE
5009566ea broken on Debian Stretch 

### ISSUE THREAD

**Issue by liuw** [jwilm/alacritty#742] opened 2017-08-21 08:39 UTC
Got the following when running 5009566ea.

Something is wrong with winit.

```
thread 'main' panicked at 'XOpenIM failed', /local/home/wei/.cargo/git/checkouts/winit-5993d63686bf7f83/200ef9c/src/platform/linux/x11/mod.rs:692
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: winit::platform::platform::x11::Window2::new
             at /local/home/wei/.cargo/git/checkouts/winit-5993d63686bf7f83/200ef9c/src/platform/linux/x11/mod.rs:692
   7: winit::platform::platform::Window2::new
             at /local/home/wei/.cargo/git/checkouts/winit-5993d63686bf7f83/200ef9c/src/platform/linux/mod.rs:181
   8: winit::window::<impl winit::WindowBuilder>::build
             at /local/home/wei/.cargo/git/checkouts/winit-5993d63686bf7f83/200ef9c/src/window.rs:113
   9: glutin::platform::platform::x11::Context::new
             at /local/home/wei/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.9.2/src/platform/linux/x11.rs:213
  10: glutin::platform::platform::Context::new
             at /local/home/wei/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.9.2/src/platform/linux/mod.rs:52
  11: glutin::GlWindow::new
             at /local/home/wei/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.9.2/src/lib.rs:322
  12: alacritty::window::Window::new
             at src/window.rs:193
  13: alacritty::display::Display::new
             at src/display.rs:141
  14: alacritty::run
             at src/main.rs:92
  15: alacritty::main
             at src/main.rs:45
  16: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  17: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:59
  18: main
  19: __libc_start_main
  20: _start
```

**Comment by VegarM** [comment] 2017-08-21 12:30
Same issue on Ubuntu 16.04.3

**Comment by jwilm** [comment] 2017-08-21 16:30
Hmm, works fine for me on Ubuntu 16.04.2. Never a good thing when winit fails in an _X_ call; it's really hard to get at the actual errors. Does anything change if you remove the `with_transparency(true)` call that was added in that PR?

**Comment by liuw** [comment] 2017-08-21 17:32
Hmm... I cleared cargo caches, cloned a fresh copy of alacritty and rebuilt. Could see the issue anymore.

It could be me having done something stupid which messed up my setup.

**Comment by jwilm** [comment] 2017-08-21 18:20
Thanks for the feedback @liuw.

@VegarM can you try running `cargo clean` and rebuilding?

**Comment by jrupac** [comment] 2017-08-21 23:11
Same symptoms as #732?

**Comment by VegarM** [comment] 2017-08-23 11:14
@jwilm 
I've now tried (on fresh master branch):
1. `cargo clean`, `cargo build --release`
2. `rm -fr ~/.cargo`, `curl https://sh.rustup.rs -sSf | sh`, `cargo build --release`
3. Also tried this in a newly cloned repository.
4. Also tried default alacritty.yaml

Nothing has worked for me, still the same error.

**Comment by addobandre** [comment] 2017-09-01 23:59
I ran git bisect and concluded that this was introduced on 4c4c2f5
This is the backtrace when running from there:
(using elementary OS 0.4.1 loki - based off Ubuntu 16.04.2 LTS)
```
thread 'main' panicked at 'XOpenIM failed', /home/breda/.cargo/git/checkouts/winit-5993d63686bf7f83/cc89d56/src/platform/linux/x11/mod.rs:680:16
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:71
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:380
   2: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:396
             at /checkout/src/libstd/panicking.rs:611
   3: std::panicking::begin_panic_new
             at /checkout/src/libstd/panicking.rs:553
   4: winit::platform::platform::x11::Window2::new
             at /home/breda/.cargo/git/checkouts/winit-5993d63686bf7f83/cc89d56/src/platform/linux/x11/mod.rs:680
   5: winit::window::<impl winit::WindowBuilder>::build
             at /home/breda/.cargo/git/checkouts/winit-5993d63686bf7f83/cc89d56/src/platform/linux/mod.rs:181
             at /home/breda/.cargo/git/checkouts/winit-5993d63686bf7f83/cc89d56/src/window.rs:113
   6: glutin::platform::platform::x11::Context::new
             at /home/breda/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.9.1/src/platform/linux/x11.rs:213
   7: alacritty::window::Window::new
             at /home/breda/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.9.1/src/platform/linux/mod.rs:52
   8: alacritty::display::Display::new
             at src/display.rs:140
   9: alacritty::run
```

**Comment by liuw** [comment] 2017-09-03 11:42
I really messed up a lot of things. Cleaning up the cache won't work.

My bisection points to 4c4c2f5f5c81e6efb580e50ea993606160809469.

**Comment by addobandre** [comment] 2017-09-03 11:45
Then this is most likely a duplicate of #732

Try starting IBus or fcitx or equivalent before alacritty

**Comment by liuw** [comment] 2017-09-03 14:23
@addobandre That's just a workaround. I now know why it failed -- it is actually an issue in winit, which insists IM to be valid or panic otherwise. I will ask winit developers for opinion. I think their current setting is too strict.

**Closed** 2017-09-03 14:35 UTC
