### ISSUE TITLE
Multiple Allacritty instances crash with "ghost" windows are closed

### ISSUE THREAD

**Issue by leandrosansilva** [jwilm/alacritty#2961] opened 2019-11-07 12:52 UTC
I have been using Allacritty 0.3.3 (released binary from github) on Windows 10 for a while and today, when I had multiple instances opened, all of them crashed simultaneously with the error dialog:

---------------------------
Alacritty: Runtime Error
---------------------------
panicked at 'PostMessage failed; is the messages queue full?', C:\Users\travis\.cargo\registry\src\github.com-1ecc6299db9ec823\winit-0.19.1\src\platform\windows\events_loop.rs:302:13

Press Ctrl-C to Copy
---------------------------
OK   
---------------------------

One thing I noticed before the crash was that there were many "ghost" entries in the task bar. They were grouped in the allacritty "task", but the windows did not exist and maybe the fact I closed all of them has some impact on the crash :-)

**Comment by kchibisov** [comment] 2019-11-07 13:12
Seems like a duplicate of https://github.com/jwilm/alacritty/issues/2656

Could you try to repro on the latest master?

**Comment by chrisduerr** [comment] 2019-11-08 02:17
@kchibisov Why do you think this is a duplicate of #2656? There's no mention of Alacritty crashing in there.

**Comment by kchibisov** [comment] 2019-11-08 05:14
>@kchibisov Why do you think this is a duplicate of #2656? There's no mention of Alacritty crashing in there.

I think the crash is due to alacritty reached a window limit, so Windows just killed the entire thing, and it was treated as crash.

I'm not very familiar with Windows, but as you can see in both issues, we're creating invisible windows over time.

**Comment by chrisduerr** [comment] 2019-11-08 05:34
The fact that all Alacritty instances are crashing is what seems strange to me but I guess it's a plausible explanation (though still very strange).

I think our best choice is to unify the issues and report to winit and check again once it has been fixed.

**Closed by chrisduerr** 2019-11-08 05:34 UTC
Labels: B - crash, H - windows
