### ISSUE TITLE
`--title` flag doesn't work anymore

### ISSUE THREAD

**Issue by Tezkerek** [jwilm/alacritty#1350] opened 2018-06-04 15:48 UTC
Arch Linux, kernel 4.16, X11

alacritty 0.1.0

    $ alacritty --title "scratchpad"
    $ xprop # and select the alacritty window

Expected to see the window title set to "scratchpad", instead it is the default, "Alacritty".

I think it stopped working since updating to `winit 0.15`, so it may be an issue with that library.

**Comment by chrisduerr** [comment] 2018-06-04 15:52
Are you sure this doesn't work anymore? It has always set the window class, not the window title (which is a bit counter-intuitive).

**Comment by Tezkerek** [comment] 2018-06-04 15:54
It worked before, I had a bspwm config set up. And a few days ago it stopped working.

**Comment by chrisduerr** [comment] 2018-06-04 16:12
Ah okay, if it worked before and doesn't work now, it's definitely a regression. Thanks for the report. :)

Not sure what caused this but updating to `winit 0.15` is a good guess.

**Comment by francesca64** [comment] 2018-06-04 16:59
You just have to set it here: https://github.com/jwilm/alacritty/blob/2fcdd40a81105128b12b9060c257c85e8be32306/src/window.rs#L324-L328

winit doesn't derive `WM_CLASS` from the initial window title anymore, since doing that never made any sense.

**Comment by nixpulvis** [comment] 2018-06-04 17:08
Is it possible to set the `WM_CLASS` at all in alacritty?

**Comment by francesca64** [comment] 2018-06-04 17:09
Not until someone makes it possible to change the values passed to `with_class`.

**Comment by nixpulvis** [comment] 2018-06-04 17:13
I know what I'm (trying to) do tonight.

**Comment by Tezkerek** [comment] 2018-06-04 17:17
Looks pretty simple to do, you can add a `WM_CLASS` parameter to `platform_builder_ext`.

**Comment by chrisduerr** [comment] 2018-06-04 17:57
@francesca64 I find the parameters "class" and "instance" a bit confusing. Because I understand one running application as one "instance" of the application.

I'd assume this refers to res_name of the X11 call (https://tronche.com/gui/x/xlib/ICC/client-to-window-manager/wm-class.html), is that correct?

**Comment by francesca64** [comment] 2018-06-04 20:04
It's explicitly *not* supposed to be updated: https://tronche.com/gui/x/icccm/sec-4.html#WM_CLASS

(I though I'd included that link in the docs. I apologize for that omission.)

In the *vast* majority of apps, both strings are the same, except the class usually has capitalization (whereas the instance is almost always the name of the binary).

**Comment by chrisduerr** [comment] 2018-06-04 20:41
Yeah, I've misunderstood the documentation on the first read. the name is ***not*** `WM_NAME`.

So it seems like the right choice to have the `res_name` fixed at `Alacritty`, then set the window class using a `--class` flag (and potentially a config option?). Then having a `--title` flag which sets the title (this should currently work already). And I'm assuming that winit already sets the title using the `WM_NAME` property, so that should be good too.

Thanks for the clarification @francesca64, as always a great help.

**Comment by nixpulvis** [comment] 2018-06-04 20:48
@chrisduerr Sounds correct to me.

**Comment by sentriz** [comment] 2018-06-05 22:05
same issue here (also using alacritty as a scratchpad 😎)

**Comment by chrisduerr** [comment] 2018-06-05 22:11
#1351 fixes this issue, so it should be good once that's merged.

**Closed** 2018-06-07 16:53 UTC
Labels: B - bug
