### ISSUE TITLE
window disappears after first application switch

### ISSUE THREAD

**Issue by andrewbanchich** [jwilm/alacritty#1888] opened 2018-12-10 13:15 UTC
Which operating system does the issue occur on?
Mac OS Mojave

If I have Alacritty open and then switch to another application, use that application, and then swipe up with three fingers and click the Alacritty window, it appears and then disappears again. Alacritty is still the program in the title bar, but the terminal window isn't visible anymore. If I swipe up with three fingers again and select it again, it stays in view and I can use it.

**Comment by chrisduerr** [comment] 2018-12-10 14:05
Is this a recent regression or has this never worked on your machine?

If this regression has been introduced in 0.2.4, I think the commit at fault might be https://github.com/jwilm/alacritty/commit/ca9a259caa59e48db3bdfdf021ee26c8bb85be99. If that's the case, please try to revert before that commit to confirm this was the breaking change.

**Comment by chrisduerr** [comment] 2018-12-10 15:22
Thanks for the note @dm1try, #1704 looks like the exact same issue (repro steps similar to this issue are in the comments), so closing as a duplicate.

**Closed by chrisduerr** 2018-12-10 15:22 UTC
Labels: H - macos
