### ISSUE TITLE
Display issue with mutt + alacritty, possibly curses-related?

### ISSUE THREAD

**Issue by UnixRonin** [jwilm/alacritty#2006] opened 2019-01-13 20:54 UTC
System:  Gentoo Linux 17.0 using X11 (xorg-server 1.20.3) and nvidia-drivers 415.25

When running the mutt mail client in alacritty, there is a problem with random characters vanishing and displaying as a blank space.  Erasing and retyping the character will USUALLY resolve it.  It occasionally takes more than one try.  The character and position appear to be pretty much random.  Usually, the character is present when types, then vanishes after 10-20 more characters are typed.

No idea how to test to narrow this down, but so far I have only seen it with mutt running in alacritty, no other combination of application and terminal displays the behavior.

I can't confirm whether the character(s) affected are actually physically **gone**, or just foreground color for that cell randomly changed to background color, but I'm going to try to test this hypothesis.

**Comment by chrisduerr** [comment] 2019-01-13 21:18
Duplicate of https://github.com/jwilm/alacritty/issues/1933.
Fixed in https://github.com/jwilm/alacritty/pull/1994 (please let me know if this doesn't resolve the problem for you).

**Closed by chrisduerr** 2019-01-13 21:18 UTC
