### ISSUE TITLE
Noticable delay in initial window render compared to urxvt

### ISSUE THREAD

**Issue by jmesmon** [jwilm/alacritty#1637] opened 2018-10-08 03:39 UTC
Linux X11, using i3 window manager.

Outline of alacrity window appears quickly, but is "unfilled" (showing previous screen contents) for several moments before it fills in. URxvt in comparison appears & fills quickly.

Other notes: I'm opening the terminal in a horizontal split with firefox in it. When a terminal opens, alacritty takes the approximately the same time to "fill in" as firefox takes to resize itself (to now being half the screen). URxvt, on the other had, appears ready several moments prior to firefox rendering in response to the resize.

More info:
distro: Archlinux, kernel: 4.18.7-arch1-1-ARCH.

glxinfo | grep OpenGL:
```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) Sandybridge Mobile
OpenGL core profile version string: 3.3 (Core Profile) Mesa 18.2.2
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.0 Mesa 18.2.2
OpenGL shading language version string: 1.30
OpenGL context flags: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.0 Mesa 18.2.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.00
OpenGL ES profile extensions:
```

**Comment by chrisduerr** [comment] 2018-10-08 09:09
This is a duplicate of #782.

**Closed by chrisduerr** 2018-10-08 09:09 UTC

**Comment by aude** [comment] 2018-11-28 13:17
@chrisduerr, this is not the same as #782 in my opinion.

I'm reproducing the issue mentioned here, and I can see what @jmesmon means.

- #782 is about slow startup time of alacritty. Ie. `time alacritty -e false` is slow.
- However, issue is about the time from the window has appeared until there is text in the window.

I have been using `st` for a while, in part because of good performance. That's why I also notice that if you for example have a Firefox browser open, then open an `alacritty` instance vertically split, it takes longer time for `alacritty` to start rendering text than for `st` (_in addition_ to having a longer startup time, which is tracked in #782).
