### ISSUE TITLE
MacOS: CMD+H is hiding alacritty forever

### ISSUE THREAD

**Issue by timorunge** [jwilm/alacritty#3098] opened 2019-12-13 19:34 UTC
On MacOS it's not possible to bring alacritty back to focus once you've put it with `CMD+H` in the background. The window is completely gone and hidden forever.

### System

OS: `MacOS 10.14.6 (18G1012)`, `MacOS 10.15.2 (19C57)` (verified on both)
Version: `alacritty 0.4.0 (b115b90)`

### Logs

Keyboard and bindings: `alacritty --print-events`

```
Created log file at "/var/folders/hh/fvdkn9pj6fnccpl9dt1f74tw0000gn/T/Alacritty-58853.log"                                                                                                                                             [2019-12-13 20:21] [INFO] Welcome to Alacritty
[2019-12-13 20:21] [INFO] Configuration loaded from "/Users/timo/.config/alacritty/alacritty.yml"
[2019-12-13 20:21] [INFO] Device pixel ratio: 2
[2019-12-13 20:21] [INFO] Initializing glyph cache...                                                                                                                                                                                  [2019-12-13 20:21] [INFO] ... finished initializing glyph cache in 0.022745343s
[2019-12-13 20:21] [INFO] Estimated DPR correctly, skipping resize
[2019-12-13 20:21] [INFO] Cell Size: 14 x 29
[2019-12-13 20:21] [INFO] Padding: 0 x 0                                                                                                                                                                                               [2019-12-13 20:21] [INFO] Width: 1120, Height: 696
[2019-12-13 20:21] [INFO] PTY Dimensions: Line(24) x Column(80)
[2019-12-13 20:21] [INFO] Initialisation complete
[2019-12-13 20:21] [INFO] glutin event: NewEvents(Init)                                                                                                                                                                                [2019-12-13 20:21] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140584678462368)), event: HiDpiFactorChanged(2.0) }
[2019-12-13 20:21] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140584678462368)), event: Resized(LogicalSize { width: 560.0, height: 348.0 }) }
[2019-12-13 20:21] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140584678462368)), event: RedrawRequested }
[2019-12-13 20:21] [INFO] glutin event: EventsCleared
[2019-12-13 20:21] [INFO] Font size changed to Size(24) with DPR of 2                                                                                                                                                                  [2019-12-13 20:21] [INFO] Width: 1120, Height: 696                                                                                                                                                                                     [2019-12-13 20:21] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 37705102474789 }, requested_resume: None })
[2019-12-13 20:21] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140584678462368)), event: Focused(true) }                                                                                                                 [2019-12-13 20:21] [INFO] glutin event: EventsCleared
[2019-12-13 20:21] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 37705122574290 }, requested_resume: None })                                                                                                      [2019-12-13 20:21] [INFO] glutin event: EventsCleared                                                                                                                                                                                  
...                                                                                                                                                                         [2019-12-13 20:21] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 37705614612435 }, requested_resume: None })
[2019-12-13 20:21] [INFO] glutin event: EventsCleared
[2019-12-13 20:21] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 37706222210169 }, requested_resume: None })
[2019-12-13 20:21] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140584678462368)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 55, state: Pressed, virtual_keycode: Some(LWin),
 modifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
[2019-12-13 20:21] [INFO] glutin event: EventsCleared
[2019-12-13 20:21] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 37708916879548 }, requested_resume: None })
[2019-12-13 20:21] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140584678462368)), event: KeyboardInput { device_id: DeviceId(DeviceId), input: KeyboardInput { scancode: 4, state: Pressed, virtual_keycode: Some(H), mod
ifiers: ModifiersState { shift: false, ctrl: false, alt: false, logo: true } } } }
[2019-12-13 20:21] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140584678462368)), event: ReceivedCharacter('h') }
[2019-12-13 20:21] [INFO] glutin event: EventsCleared
[2019-12-13 20:21] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 37709431936798 }, requested_resume: None })
[2019-12-13 20:21] [INFO] glutin event: WindowEvent { window_id: WindowId(Id(140584678462368)), event: Focused(false) }
[2019-12-13 20:21] [INFO] glutin event: EventsCleared
[2019-12-13 20:21] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 37709440452938 }, requested_resume: None })
[2019-12-13 20:21] [INFO] glutin event: EventsCleared
[2019-12-13 20:21] [INFO] glutin event: NewEvents(WaitCancelled { start: Instant { t: 37709440690233 }, requested_resume: None })
...
```

**Comment by nixpulvis** [comment] 2019-12-13 19:42
I'm pretty sure this is a duplicate of #1465, if it's not please feel free to reopen this issue.

**Closed by nixpulvis** 2019-12-13 19:42 UTC
