### ISSUE TITLE
font scales wrongly on different resolution monitors

### ISSUE THREAD

**Issue by JoshRagem** [jwilm/alacritty#1372] opened 2018-06-13 20:39 UTC
Which operating system does the issue occur on?
ubuntu 18 on macbook pro

If on linux, are you using X11 or Wayland?
x11

If I create an alacritty window on a normal DPI screen (i.e. external monitor) the font size seems fine (though comes up bigger than my last build from a couple months ago), If I move that window to the built in retina display the font shows up tiny as expected due to resolution difference.
If, however, I create the window on the retina display first, the font appears ordinary size (i.e. not tiny) but becomes comically large when moved to the external display.

**Comment by chrisduerr** [comment] 2018-06-13 20:54
This seems to be a duplicate of #71, there's currently some work going on to fix this, however it will still take a bit because it depends on an external library.

**Closed by chrisduerr** 2018-06-13 20:54 UTC
