### ISSUE TITLE
Title is set to "Unbekannt" ("Unknown") and there's no icon if started as Wayland client

### ISSUE THREAD

**Issue by KopfKrieg** [jwilm/alacritty#1875] opened 2018-12-06 23:04 UTC
> Which operating system does the issue occur on?

Archlinux with Gnome Shell 3.30. System is up to date.

> If on linux, are you using X11 or Wayland?

Wayland.

Picture to visualize everything:
![Screenshot](https://user-images.githubusercontent.com/5047813/49616963-ea961780-f9b2-11e8-9006-4c00449c4707.png)
The picture shows part of the application menu of the Gnome Shell. The first icon is the icon for alacritty if started as Wayland client, the text next to it is its title ("Unbekannt", German for "Unknown"). The icon below shows the correct behaviour (terminal icon as icon, title is "Alacritty") after starting alacritty as XWayland client.

It would be nice if alacritty shows the correct behaviour regardless of X11 or Wayland.

**Comment by davidlgj** [comment] 2019-02-05 13:35
This seems to be a duplicate of #1582 (or I guess the other way around)

**Comment by chrisduerr** [comment] 2019-02-05 16:04
Instead of closing this as duplicate, I've decided to fix the issue in #2077. Please let me know if this works.

**Closed** 2019-02-06 21:10 UTC
Labels: DS - Wayland, H - linux, enhancement

**Comment by KopfKrieg** [comment] 2019-02-10 15:51
> Instead of closing this as duplicate, I've decided to fix the issue in #2077. Please let me know if this works.

Just wanted to let you know it works here :)

Thanks for the fix.

**Comment by rhajdacki** [comment] 2019-02-12 18:41
I have just tested 0.2.9 on Sway and setting title with `--title` still fails. `swaymsg -t get_tree` still reports `null` in name field of the window. However now `--class` works and `app_id` field contains correct value.

**Comment by chrisduerr** [comment] 2019-02-12 18:48
Please see https://github.com/jwilm/alacritty/issues/2104 regarding window title, since that's a separate issue.

**Comment by myfreeweb** [comment] 2020-02-29 21:04
Currently the app_id is `Alacritty` but the desktop file is lowercase `alacritty.desktop`. This is really up to distributions to install correctly but it would be nice if the file in the repo was also capitalized `Alacritty.desktop`.

**Comment by nixpulvis** [comment] 2020-03-06 07:03
@myfreeweb I've opened #3425 to address this, let me know if this works.
