### ISSUE TITLE
alacritty processes continue running after closing

### ISSUE THREAD

**Issue by shoober420** [jwilm/alacritty#1276] opened 2018-04-27 04:41 UTC
On a fully up to date Arch Linux set up on X11 with NVIDIA proprietary driver's (396.18) and the composite extension disabled, transparency and vsync disabled (via .yml), alacritty processes continue to run and don't stop even after closing the terminal windows. My CPU cores will rise to 100% and there will be many alacritty processes running, even if you shut down the X.Org display server. I have to manually kill each alacritty process with htop for my CPU to stop maxing out at 100%.

**Comment by shoober420** [comment] 2018-04-29 18:44
This bug is actually a blessing, as it has motivated me to use tmux instead of spawning multiple terminal windows for each desired process.

**Comment by chrisduerr** [comment] 2018-04-29 19:03
Not sure what the cause of this is, it kinda sounds like there's a loop which is just running without anything ever blocking it.

But maybe there's a workaround for now? I'd assume you're closing alacritty using your window manager, you could try using `exit` or `Ctrl+D` to close alacritty, maybe that would work?

**Comment by shoober420** [comment] 2018-04-30 00:50
I'll give that a try when I get home, I was using my window manage keybinds to kill the terminals.

**Comment by shoober420** [comment] 2018-04-30 05:29
Interesting. Using both "Ctrl+D" and "exit" cleanly close the process. It's only when I close it with my window manager that the processes remain open and spike my CPU cores to 100%.

**Comment by shoober420** [comment] 2018-04-30 05:40
To double check, I switched back to my old terminal emulator "simple terminal" to make sure my window manager closes out of it properly, and it does for sure. So for some reason, bspwm isn't killing the alacritty process when closing the terminal windows

**Comment by Aaron1011** [comment] 2018-06-02 02:42
@shoober420 I've unable to reproduce this on Arch Linux (using Gnome Shell) with the latest version of alacritty. What window manager are you using?

**Comment by shoober420** [comment] 2018-06-02 09:20
Bspwm

**Comment by chrisduerr** [comment] 2018-06-02 13:27
Are you running a compositor? I'm pretty sure ST doesn't support transparency but both Kitty and Alacritty probably launch as transparent windows. It's a long shot but just an idea.

**Closed** 2019-03-12 19:44 UTC
Labels: B - bug
