### ISSUE TITLE
Broken rendering of MC dialogs, introduced in 0.3.2

### ISSUE THREAD

**Issue by TheIndifferent** [jwilm/alacritty#2498] opened 2019-06-02 14:04 UTC
Versions of everything:
* macos 10.14.5
* tmux stable 2.9a (current latest from brew)
* mc stable 4.8.22 (current latest from brew)

Configs:
* alacritty config, mostly key bindings are modified: https://github.com/TheIndifferent/dotfiles/blob/master/macos/alacritty_and_tmux/.config/alacritty/alacritty.yml
* tmux config, custom thingy to show current dir: https://github.com/TheIndifferent/dotfiles/blob/master/macos/alacritty_and_tmux/.tmux.conf
* mc custom skin: https://github.com/TheIndifferent/dotfiles/tree/master/macos/alacritty_and_tmux/.config/mc

Steps to reproduce:
1. Upgrade Alacritty from 0.3.1 to 0.3.2.
2. Open Alacritty to full screen on 1920x1080 resolution.
3. Open mc and try to delete a file.
4. Renders correctly when resized to quarter or half screen.
5. When copying files, seems like there is a similar rendering issue but hard to catch because it goes with jumping mc progress bar.

![Screenshot 2019-06-02 at 15 51 06](https://user-images.githubusercontent.com/9323482/58762380-e4db5200-854f-11e9-87eb-8c6cda0fa7b5.png)

**Comment by chrisduerr** [comment] 2019-06-02 15:40
Duplicate of https://github.com/jwilm/alacritty/issues/2217.

**Closed by chrisduerr** 2019-06-02 15:40 UTC

**Comment by TheIndifferent** [comment] 2019-06-02 15:45
@chrisduerr the original issue is reported for version 0.2.7, but for me every version from 0.2.4 to 0.3.1 works perfectly fine (currently downgraded to 0.3.1 to workaround the issue) 🤔  can it be the same issue?

**Comment by chrisduerr** [comment] 2019-06-02 15:50
Oh, I linked the wrong issue, sorry. Changed it to https://github.com/jwilm/alacritty/issues/2353.

**Comment by TheIndifferent** [comment] 2019-06-02 15:51
Yup, that one looks correct 😃  thanx! It's weird that right now I cannot reproduce it on 0.3.2 either, and the original issue is reported for 0.3.1, so it is probably correct.

**Comment by chrisduerr** [comment] 2019-06-02 15:53
The issue has to do with a cache filling, so it's tough to reliably reproduce it. However the latest master should fully fix it.
