### ISSUE TITLE
Maximized opened alacritty is mispositioned under Gnome/Wayland. Invisible titlebar.

### ISSUE THREAD

**Issue by Porkepix** [jwilm/alacritty#3146] opened 2020-01-04 10:49 UTC
For bug reports, the following information can help speed up the process. Please describe the bug that you have found and what you would expect to happen instead.

### System

OS: Linux
Version: alacritty 0.4.0
Linux/BSD: Wayland, Gnome

/!\ In `alacritty.yml`, `startup_mode` is set to `Maximized`. The option works perfectly well under KDE/Plasma with X11 or Gnome & X11 for example, but might lead to the following bug.

On Gnome/Wayland, when opening Alacritty, the window gets the correct available size (ie. the size of the screen, less the height of the Gnome-shell bar on the top taken off), but get *positioned* from pixel 0,0 on top left. The result is that the title-bar is not visible and there is an unused space that have top bar's height unused on the bottom. User doesn't have access to the title bar either.

See the first joined screenshot:
![Screenshot from 2020-01-04 11-40-17](https://user-images.githubusercontent.com/709500/71764423-033f6c80-2ee8-11ea-9917-3774734e9a67.png)

Another maybe related curious point: title-bar is visible when using the expose feature, but is kinda "eaten up" on the border, see this screenshot:
![Screenshot from 2020-01-04 11-40-25](https://user-images.githubusercontent.com/709500/71764440-32ee7480-2ee8-11ea-816b-1b6cd5c996f9.png)

**Comment by kchibisov** [comment] 2020-01-04 11:46
duplicate of #3070

**Closed** 2020-01-04 14:36 UTC
