### ISSUE TITLE
Touchpad scrolling is janky

### ISSUE THREAD

**Issue by ashkitten** [jwilm/alacritty#721] opened 2017-08-11 15:19 UTC
I don't know exactly what's going on, but when I scroll with the touchpad it requires me to scroll a lot before it will even register, and then it scrolls a ton at once.

**Comment by ashkitten** [comment] 2017-08-11 15:22
According to hwinfo it's a "ETPS/2 Elantech Touchpad", if that helps at all

**Comment by jwilm** [comment] 2017-08-11 15:55
Could you run alacritty with `alacritty --print-events`, try scrolling, and pastebin the log? My initial guess is that we are getting funny data out of winit.

**Comment by maximbaz** [comment] 2017-08-11 18:36
Huh, I experience that too, although I always blamed tmux for this - but no, in sakura terminal the scrolling is smooth.

The log:

https://gist.github.com/maximbaz/7cc8521f033e04a53924416f26332164

What happens in the log:

- Alacritty starts, I type "tmux", then "tree", then cancel with with Ctrl+C after a bit.
- Scroll up with touchpad with my usual speed of scrolling (nothing is being scrolled in tmux)
- Scroll up much faster (tmux begins to scroll up)
- Scroll up with usual speed again (nothing is being scrolled in tmux)
- Scroll up much faster (tmux scrolls up)
- Close tmux and then terminal with Ctrl+D.

**Comment by jwilm** [comment] 2017-08-11 18:43
Thanks @maximbaz.

Here's the interesting part. All of these events have fractional line deltas.

```
MouseWheel { device_id: DeviceId(X(DeviceId(2))), delta: LineDelta(0, 0.16228071), phase: Moved } 
```

Alacritty [assumes that they will be integer values], and the floats are truncated accordingly. This is obviously wrong. We'll need to track a bit more state to get this right.

[assumes that they will be integer values]: https://github.com/jwilm/alacritty/blob/492d1bd3d56af94d4d1d05e17fb8a6acf354a170/src/input.rs#L354-L364

**Comment by maximbaz** [comment] 2017-08-11 18:52
Heh I can certainly see why it is made like that 🙂 

This is a one stop of a scroll with an external mouse:

```
glutin event: WindowEvent { window_id: WindowId(X(WindowId(65011715))), event: MouseWheel { device_id: DeviceId(X(DeviceId(2))), delta: LineDelta(0, 1), phase: Moved } }
```

And this is one stop of a scroll with touchpad:

```
glutin event: WindowEvent { window_id: WindowId(X(WindowId(65011715))), event: MouseWheel { device_id: DeviceId(X(DeviceId(2))), delta: LineDelta(0, 0.040570177), phase: Moved } }
```

I wonder if you have a general idea how to normalize values coming from touchpad?

----

It is also surprising that scrolling with mouse produces way more WindowEvents than scrolling with a touchpad. 

Mouse, full list of events for one scroll stop:


```
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(18))), event: Motion { axis: 3, value: -15 } }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(65011715))), event: MouseWheel { device_id: DeviceId(X(DeviceId(2))), delta: LineDelta(0, 1), phase: Moved } }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(65011715))), event: MouseEntered { device_id: DeviceId(X(DeviceId(2))) } }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(65011715))), event: MouseLeft { device_id: DeviceId(X(DeviceId(2))) } }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(65011715))), event: MouseEntered { device_id: DeviceId(X(DeviceId(2))) } }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(65011715))), event: MouseLeft { device_id: DeviceId(X(DeviceId(2))) } }
```

Touchpad:

```
glutin event: DeviceEvent { device_id: DeviceId(X(DeviceId(13))), event: Motion { axis: 3, value: -0.6085526316892356 } }
glutin event: WindowEvent { window_id: WindowId(X(WindowId(65011715))), event: MouseWheel { device_id: DeviceId(X(DeviceId(2))), delta: LineDelta(0, 0.040570177), phase: Moved } }
```

**Comment by jwilm** [comment] 2017-08-11 19:15
@Ralith is this behavior normal for trackpads on x11? (**TLDR:** external mouse wheel gives integer line deltas, trackpad gives fractional line deltas). I'm trying to figure out if this should be resolved in winit or Alacritty. The trackpad events almost seem like they should be generating a pixel delta instead of line delta.

**Comment by Ralith** [comment] 2017-08-11 19:24
This is the intended behavior. Alacritty should not be truncating scroll values; if they were guaranteed to be integers, then winit wouldn't use floats there in the first place. The meaning of a fractional line delta is literally a fraction of a line (or more generally, a scroll unit). Smooth scrolling devices are not in general directly related to pixels, after all.

**Comment by jwilm** [comment] 2017-08-11 19:40
@Ralith thank you for the clarification! For some reason I had it in my head that smooth scrolling would always use pixels as a reference.

**Comment by lheckemann** [comment] 2017-08-12 11:18
Is this a new issue? I just started using alacritty and it just so happens that I encountered this issue just now.

**Comment by lheckemann** [comment] 2017-08-12 15:46
8a65870 fixes this. I'm unfamiliar both with Rust and with alacritty's structure, so this is indubitably the wrong way to do it (the state is getting passed all over the place, I used terrible names, and it's largely just a result of changing stuff until the compiler was happy without really knowing what I was doing). A review of how I should have done this would be very welcome :)

**Comment by jwilm** [comment] 2017-08-13 00:00
@lheckemann not a new issue, but I don't think a lot of people were likely to encounter it. It requires running x11 on a laptop with a trackpad that generates fractional line deltas in an application that supports scrolling with someone who uses the mouse in terminal. Probably why is hasn't been reported until recently.

Love that you've put together a patch for it! I would be happy to provide feedback. Would you mind putting up a PR so we can use the GitHub review tool on it?

**Closed** 2017-09-02 19:29 UTC
Labels: bug
