### ISSUE TITLE
Alacritty stops rendering after some times usage

### ISSUE THREAD

**Issue by korken89** [jwilm/alacritty#2483] opened 2019-05-26 14:44 UTC
On a fresh Archlinux install, after some times usage alacritty stops rendering the window, but commands running in the window continue to work fine. On switching of workspace the alacritty window get whatever is on the other workspace frozen in is windows instead. The following has been tested:
* New alacritty windows can be opened that continue to work (for a while).
* I ran with `alacritty -v` from another terminal emulator to see if there is any error or warning in the log, but there is not.
* Calling `kill` on the window (via i3) does not close the window, only a `killall alacritty` seems to work

I'm not sure where to start hunting this issue to give better help, as I can't find any warnings nor errors anywhere. 

---

Which operating system does the issue occur on?
* Archlinux, fresh install
* Linux 5.1.4-arch1-1-ARCH SMP PREEMPT Wed May 22 08:06:56 UTC 2019 x86_64 GNU/Linux
* alacritty version 0.3.2

If on linux, are you using X11 or Wayland?
* X11 - i3 version 4.16.1 (2019-01-27)
* A high DPI screen (3000 x 2000 pixels)

---

Attached example of other workspace in the frozen window after switching workspace.

![image](https://user-images.githubusercontent.com/913109/58383305-59087980-7fd5-11e9-9687-1f44e1b5a950.png)

---

Attached example of maximizing a frozen window.

![image](https://user-images.githubusercontent.com/913109/58383244-8bfe3d80-7fd4-11e9-8e74-2edd12b0291d.png)

**Comment by chrisduerr** [comment] 2019-05-26 16:18
Duplicate of #2217.

**Closed by chrisduerr** 2019-05-26 16:18 UTC
