### ISSUE TITLE
Linux: Auto-detect scaling factor.

### ISSUE THREAD

**Issue by kevincox** [jwilm/alacritty#165] opened 2017-01-07 08:40 UTC
On linux the default scaling factor should be auto detected so that the default user experience isn't a tiny little window.

**Comment by jshook** [comment] 2017-01-07 16:51
On a 3200x1800 laptop screen, Alacritty is unusable without this. At the very least, a setting for scaling factor should be added to the config file.

**Comment by jwilm** [comment] 2017-01-08 06:27
Thanks for the report!

You can set your screen's DPI in the config file as a workaround to autodetection. Closing as a duplicate of #202

**Closed by jwilm** 2017-01-08 06:27 UTC
