### ISSUE TITLE
Output delay every 20 seconds on large `tree` output

### ISSUE THREAD

**Issue by SamuelMarks** [jwilm/alacritty#2274] opened 2019-04-09 03:09 UTC
Which operating system does the issue occur on?
macOS 10.14.4 (18E226) with new—first time use—Alarcritty

If on linux, are you using X11 or Wayland?

I run `tree` from my home directory to impress a colleague, and every 20 seconds or so it just pauses, then starts working again a second or two later (repainting the screen really fast, which is what I was trying to show off!).

I'm assuming this isn't a problem with `tree`, but if you'd like me to try a similar program I'm all ears.

Using `tree v1.8.0`. I have many files in my home dir:
```
$ fd -HI | wc -l
3661611
```

**Comment by chrisduerr** [comment] 2019-04-09 08:06
If you keep pressing keys while the tree output is going on, does that fix the freezing issues?

**Comment by laerus** [comment] 2019-05-03 09:24
seems related to  #2217

**Comment by chrisduerr** [comment] 2019-05-03 11:20
Since there hasn't been any response, it probably makes sense to close this as a duplicate of #2217. I'd expect that to solve this too.

**Closed by chrisduerr** 2019-05-03 11:20 UTC
Labels: A - needs repro, B - bug, B - performance, H - macos

**Comment by SamuelMarks** [comment] 2019-05-07 04:31
All good, I'll wait for that to merge before trying alacritty again
