### ISSUE TITLE
buttonless title bar blocks selection

### ISSUE THREAD

**Issue by lsnch** [jwilm/alacritty#2208] opened 2019-03-23 22:46 UTC
macOS 10.13.6

![Screen Shot 2019-03-24 at 01 42 55](https://user-images.githubusercontent.com/20382674/54872527-55d6ee80-4dd6-11e9-9baf-fdafe01a3406.png)

Number 40 here cannot be selected. Window gets dragged instead.

**Comment by chrisduerr** [comment] 2019-03-23 22:59
Duplicate of https://github.com/jwilm/alacritty/issues/1671.

**Closed by chrisduerr** 2019-03-23 22:59 UTC

**Comment by sodiumjoe** [comment] 2019-03-25 05:04
Oh, this is interesting, I never ran into this because I have a pretty big padding set on all sides. I agree with @chrisduerr about it basically boiling down to #1671 though.
